== Living Together in Love

=== §. 10. #emph[Of mutual love betwixt man and wife.]

Hitherto of those common mutual duties which tend to the preservation of the very #emph[being] of marriage, and are in that respect absolutely necessary. The other common mutual duties (though they be not of so absolute necessity as the former) are in their kind necessary for the good estate of marriage, and for the better preserving of that knot: so as, if they be not performed, the end and right use of marriage will be perverted, & that estate made uncomfortable, & very burdensome. The first of these is #emph[love.] A loving mutual affection must pass betwixt husband and wife, or else no duty will be well performed: this is the ground of all the rest. In some respects #emph[love] is proper and peculiar to an husband, as #footnote[Treat. 4. §. 2.] I purpose to show when I come to speak of an husbands particular duties. But #emph[love] is also required of wives, and they are commanded to be #emph[lovers of their husbands,] as well as husbands #emph[to love their wives:] #footnote[#emph[Tit.] 2. 4. #emph[Col.] 3. 19.] so as it is a common mutual duty belonging to husband and wife too: and that is true wedlock, when man and wife are linked together by the bond of love. Under #emph[love] all other duties #footnote[#emph[Hoc verum est coniugium, quando vinculo charitatis sunt concatenati. Chrys. hom.] 45. #emph[in Gen.]] are comprised: for without it no duty can be well performed. #footnote[#emph[Rom.] 13. 10.] #emph[Love is the fulfilling of the Law,] that is, the very life of all those duties which the law requireth. It is the #footnote[#emph[Col.] 3. 14.] #emph[bond of perfection,] which bindeth together all those duties that pass betwixt party and party. Where #emph[love] aboundeth, there all duties will readily and cheerfully be performed. Where #emph[love] is wanting, there every duty will either be altogether neglected, or so carelessly performed, that as good not be performed at all: in which respect the Apostle willeth, that #emph[all things be done] #footnote[1 #emph[Cor.] 16. 14.] #emph[in love. Love] as it provoketh the party in whom it ruleth to do all the good it can; so it stirreth up the party loved to repay good for good. It is like fire, which is not only hot in it self, but also conveyeth heat into that which is near it: whence ariseth a reflection of heat from one to another. Note how admirably this is set forth betwixt Christ and his Spouse in the #emph[Song of Solomon:] and it is further manifested in the examples of all good husbands and wives noted in the Scripture: they did mutually bear a very loving affection one to another.

Though #emph[love] be a general duty which every one oweth to another, #footnote[#emph[Matth.] 5. 44.] even to his enemy, yet the nearer that God hath linked any together, the more are they bound to this duty, and the more must they abound therein. But of all others are #footnote[Treat. 1. §. 79, 80.] man and wife most nearly and firmly linked together. Of all others therefore are they most bound hereunto, & that in the highest degree that may be, even like to #emph[Jonathans] love, who #emph[loved David] #footnote[1 #emph[Sam.] 18. 1. #emph[Prov.] 18. 22.] #emph[as his own soul. Solomon] saith, #emph[He that findeth a wife findeth a good thing, and obtaineth favour of the Lord:] which by the rule of relation is also true of an husband, #emph[She that findeth an husband findeth a good thing, and obtaineth favour of the Lord.] Man and wife therefore are each to other an especial pledge of Gods favour, and in this respect above all others under God to be loved. If this be the ground (as it ought to be) of their mutual #footnote[That which in #emph[Treat.] 4. §. 2. 9. 11. is spoken of an husbands love and entire affection, may also be applied in some respects to a wife: and so serve to amplify this common mutual duty of love.] love, their love will be fervent and constant. Neither will the want, or withering of any outward allurements, as beauty, personage, parentage, friends, riches, honours, or the like, with-hold or with-draw, extinguish or extenuate their love: neither will any excellencies of nature or grace in other husbands and wives draw their hearts from their own to those other: nor yet will the love of a former yoke-fellow dead and gone, any whit lessen the love of the living mate.

This instance I have the rather mentioned, because in many, #footnote[Love of after venters to be as entire as of former.] who are far from setting their affection on strange flesh, their love of a former husband or wife departed is so fast fixed in their heart, as they can never again so entirely love any other. They who are so minded are not fit to be joined with another yoke-fellow after they are loosed from one. If they marry again, and manifest such a mind, they plainly show that they respect this or that person more then Gods ordinance. By Gods ordinance man and wife are no longer bound one to another then they live together. Death is an absolute diremption, and maketh an utter dissolution of the marriage bond. #emph[If the man] #footnote[#emph[Rom.] 7. 2, 3.] #emph[be dead, the wife is delivered from the law of the man, so as she may take another man.] Which liberty is also given to the man. Being now free, if they marry another (that other being now a true husband or wife) their love must be as entire to that other as it was to the former: yea, and more entire, if there were any defect in the former. For as children married out of their parents house must not retain such a love of their parents as shall swallow up their love of the party to whom they are married, but must according to the law, leave father and mother, and cleave to their yoke-fellow: so neither must the love of a former husband or wife be predominant when they are married to another. This other must be as close cleaved unto, as if they had never been joined to a former. The living husband or wife is the present pledge of Gods favour. He is now thine #emph[own] husband: and she is now thine #emph[own] wife: and not the party that is dead. I deny not but the memory of a virtuous husband or wife ought to be precious to the surviving party: for #emph[the memorial of the just is blessed.] #footnote[#emph[Prov.] 10. 7.] But as the virtue of a person deceased may not be buried with the dead corpse: so neither may the person be kept above ground with the memory of his or her virtue: which after a sort is done, when love of the party deceased either taketh away, or extenuateth the love of the living. This is to give dominion to the dead over the living: which is more then the law enjoineth.

=== §. 11. #emph[Of husbands and wives mutual hatred contrary to love.]

There is a generation of so crabbed and crooked a disposition #footnote[\* See Treat. 3. §. 8. #emph[&] Treat. 4. §. 10.] as they cannot love, but rather hate one another because they are man and wife: for many husbands having wives, and wives husbands every way worthy to be loved, will notwithstanding say to the astonishment of the hearers, #emph[I have indeed a good husband, or I have a good wife: but I cannot love him,] or #emph[I cannot love her:] and being demanded a reason, stick not openly and impudently to reply, #emph[I think I could love him if he were not mine husband,] or #emph[I think I could love her if she were not my wife.] O more then monstrous impudency! Is not this directly to oppose against Gods ordinance, and against that order which he hath set betwixt man and woman? Is it not to trample under foot Gods favour? Though there were nothing else to move love but this, that #emph[such an one is thine husband,] or #emph[such an one is thy wife,] yet this should be motive enough. And shall this be the ground of thine hatred? Assuredly such a spirit is a plain diabolical spirit, contrary to that spirit which is from above; and if it be not cast out, it will cast those whom it possesseth into the fire of hell.

=== §. 12. #emph[Of mutual peace betwixt Man and Wife.]

Among other means of maintaining an inward loving affection betwixt man and wife, #emph[outward mutual peace,] concord, and agreement is one of the principal. Whereupon the Apostle exhorteth to #emph[keep the unity of the spirit in the bond of] #footnote[#emph[Ephes.] 4. 3.] #emph[peace:] for peace is a bond that tieth one to another, and maketh them to be as one, even one in spirit: as on the contrary side outward discord disunites mens spirits. We are enjoined to #emph[follow peace with all men:] how much more of all persons ought #footnote[#emph[Heb.] 12. 14.] husbands to have peace with their wives, and wives with their husbands? They are nearer then brothers and sisters. Behold then how good and pleasant a thing it is for them to dwell together in unity. #footnote[§. 14. #emph[Prov.] 21. 9.] Dwell together they must: but without peace there is no dwelling together: #emph[It is better to dwell in a corner of the house top then with a contentious woman in a wide house.] Persons at variance were far better be out of sight and place, then present together. Out of sight and place man and wife must not be, at peace therefore #footnote[#emph[Portus est mulier, & maximum securitatis remedium. Si ventis & fluctibus portum liberaueris ex foro reuersus tranquillè viues. Chrys. hom.] 26. #emph[in] 1 #emph[Cor.] 11.] they must be. Mutual peace betwixt them is a great refreshing to their minds, being beaten with the discords of others. It is said that a wife is in this respect as an haven to man (how much more man to his wife?) If the haven be calm, and free from storms and tempests, what a refreshing will it be to the Mariner that hath been tossed in the sea with winds and waves?

For maintaining peace,

1. All offences so much as possibly may be must be avoided. #footnote[Directions for maintaining peace betwixt Man and Wife.] The husband must be watchful over himself that he give no offence to his wife: and so the wife on the other side. Offences cause contentions.

2. When an offence is given by the one party, it must #footnote[1\. Avoid offence.] not be taken by the other; but rather passed by: and then will not peace be broken. The second blow makes #footnote[2\. Take not offence.] the fray. #footnote[3\. Offer reconciliation.]

3. If both be incensed together, the fire is like to be the greater: with the greater speed therefore must they both labour to put it out. Wrath must not lie in bed with two such #footnote[#emph[Eph.] 4. 26.] bed-fellows: neither may they part beds for wrath sake. That this fire may be the sooner quenched, they must both strive first to offer reconciliation. Theirs is the glory who do first begin, for they are most properly the #emph[blessed peacemakers.] Not #footnote[#emph[Mat.] 5. 9.] to accept peace when it is offered is more then heathenish: but when wrath is incensed, to seek atonement is the duty of a Christian, and a grace that cometh from above.

4. Children, servants, nor any other in the family must be #footnote[4\. Take no part with others.] bolstered up by the one against the other. The mans partaking with any of the house against his wife, or the wives against her husband, is an usual cause of contention betwixt man and wife.

5. They must forbear to twit one another in the teeth #footnote[5\. Make not comparisons.] with the husbands or wives of other persons: or with their own former husbands or wives (in case they have had any before.) Comparisons in this kind are very odious. They stir up much passion, and cause great contentions.

6. Above all they must take heed of rash and unjust jealousy, #footnote[6\. Be not jealous.] which is the bane of marriage, and greatest cause of discontent that can be given betwixt man and wife. Jealous persons are ready to pick quarrels, and to seek occasions of discord: they will take every word, look, action, and motion, in the worse part, and so take offence where none is given. When jealousy is once kindled, it is as a flaming fire that can hardly be put out. It maketh the party whom it possesseth implacable. #footnote[#emph[Pro.] 6. 34, 35.]

7. In all things that may stand with a good conscience they must endeavour to please one another: and either of #footnote[7\. Please one another.] them suffer their own will to be crossed, rather then discontent to be given to the other. Saint #emph[Paul] noteth this as a common #footnote[1 #emph[Cor.] 7. 33, 34.] mutual duty belonging to them both, and expresseth their care thereof under a word that signifieth more then ordinary care, and implieth a #emph[dividing of the mind] into divers thoughts, casting this way, and that way, and every way how to give best content.

=== §. 13. #emph[Of contentions betwixt man and wife.]

Contrary to mutual peace are #emph[contentions] betwixt man and wife: which are too frequent in most families, and by which #footnote[#emph[Cùm vir & vxor domi dissentiunt, nihilo melius naui iactata domus illa disponitur, cùm gubernator aduersus prorae directorem dissentiat. Chrys. loc. citat. Gen.] 13. 8.] the common good is much hindered. Discord betwixt man and wife in an house is as contention betwixt the master and pilot in a ship: may not great danger, and much mischief be thence justly feared? We heard before that man to his wife, and she to him, is as an haven. Now by experience we find that if the haven be tempestuous it is much more troublesome, and dangerous to the Mariner then the wide sea. Wherefore let man and wife be of the same mind one to another as #emph[Abraham] was to #emph[Lot,] and when occasions of discord are offered, say, #emph[Let there be no strife betwixt thee and me, for we are man and wife: no more two, but one flesh.]

=== §. 14. #emph[Of husbands and wives dwelling together.]

From a mutual affection of #emph[love] proceedeth #emph[a mutual provident care] in husband and wife one for another. In handling whereof we will first note the #emph[means] whereby their mutual providence may be the better effected and manifested, and then the #emph[matter] whereabout it must be conversant. The means in one word is #emph[cohabitation.] For a duty it is that man and wife dwell together. The phrase used in setting out the womans creation (he #emph[built] a woman, whereby the erecting of #footnote[#emph[Vide Musc. in Gen.] 2. 22. See #emph[Treat.] 1. §. 79.] a family is intimated) implieth as much: so doth the law of marriage whereby man is enjoined to #emph[leave father and mother, and to cleave unto his wife,] that is, to go out of his fathers house, and to dwell with his wife: and so doth this phrase #emph[(forget] #footnote[#emph[Psal.] 45. 10.] #emph[thy fathers house)] taken from the duty of a wife, and mystically applied to the Church. Saint #emph[Peter] expressly chargeth husbands #footnote[1 #emph[Pet.] 3. 7.] to #emph[dwell with their wives:] and Saint #emph[Paul] layeth it to #footnote[1 #emph[Cor.] 7. 12, 13.] the charge both of husbands and wives not to leave one another, but to dwell together, yea though the one be an infidel. Surely it was conscience of this duty which made the #footnote[#emph[Judg.] 19. 3.] Levite to go after his wife, that went away from him, to bring her home again: and which made #footnote[#emph[Gen.] 31. 14.] #emph[Jacobs] wives to leave their fathers house, and go with their husband. #footnote[#emph[coniux.] #emph[vxor.]] The word under which Saint #emph[Peter] compriseth this duty is a title appropriated to an husband: and an answerable title is appropriated to a wife: from which the notation of our two usual English words #emph[(husband, housewife)] doth not much differ.

The power which the one hath of the others body, and #footnote[Reasons for cohabitation.] the advantage which by living asunder, they give unto #emph[Satan,] (both of which are expressly noted, 1 #emph[Cor.] 7. 4, 5.) do show the necessity of this duty: and the many benefits arising from thence do further press the equity of it. By husbands and #footnote[Benefits of cohabitation.] wives dwelling together all marriage duties are better performed: mutual love is better bred, preserved, and increased: the good gifts of either of them are better observed by the other: better help and succour is mutually by each afforded to the other: and in fine they are made more capable of doing good one to another, and of receiving good one from another. Why then should they have any mind of living asunder, unless they be forced by extraordinary occasions, as captivity, close imprisonment, contagious sickness, and such like, which are no faults of theirs, but crosses to be borne with grief; and instant prayer, together with all other good means, to be used to bring them together again? Yea if the imprisonment, banishment, or other like kind of absence, #footnote[D. #emph[Fulke] against #emph[Rhem.] on 1 #emph[Cor.] 7. §. 6.] be such as one may if they will come at the other, the party that is free ought to come to the other, if at least that other require it.

=== §. 15. #emph[Of the respects for which man and wife may for a time live asunder.]

#strong[#emph[Quest.] May there be any just causes for man and wife willingly to live asunder?]

#emph[Answ.] There can nor ought to be any cause of utter relinquishing one another, which is a kind of #footnote[§. 3.] #emph[desertion:] but for living asunder for a time there may be just causes, as

1. #emph[Weighty and urgent affairs] which concern the good of the Church, or commonwealth: as when a man is sent forth to war, or on an ambassage (in which case though he may take his wife with him, yet is he not necessarily bound thereto, especially if the place whither he is sent be far off, the passage thereto difficult and dangerous, and his abode there not long.) When #footnote[#emph[Numb.] 32. 26, 27.] #emph[Reuben, Gad,] and half the tribe of #emph[Manasseh] passed over Jordan to help their brethren in their battles against the Canaanites, they left their wives behind them in their families: #footnote[2 #emph[Sam.] 11. 3, 6.] when #emph[Uriah] went to war, he left his wife at home: and #footnote[#emph[Exo.] 18. 2.] when #emph[Moses] was to bring Israel out of Egypt, his wife remained at her fathers house.

2. #emph[Main duties of their particular calling:] as of #emph[Mariners,] who are oft to be on the sea: #emph[Merchants] who trade in other countries: #emph[Lawyers] who attend public places of justice: #emph[Courtiers,] who in their months, or quarters, attend their Prince: #emph[Keepers] of women in child-bed, and sick persons: and other #emph[nurses.]

Provided always that in these, and other like cases, there be #footnote[Absence, 1. not without consent. 1 #emph[Cor.] 7. 5.] a joint and mutual consent of both parties: for if man and wife may not defraud one another for a time to give themselves to fasting and prayer #emph[without consent:] much less may they for lighter occasions live any time asunder without #footnote[2\. Not with delight. #emph[Si vir ad peregrina contenderit, nulla longinquitas, nulla absentia complacitam minuat charitatem. Ambr. Hexaem. l.] 5. #emph[c.] 7.] consent. Provided also that they take no delight to live asunder, but rather be grieved that they are forced so to do: and in testimony thereof to take all occasions that they can to manifest their longing desire one after another by letters, messages, tokens, and other like kindnesses: and to return with all the speed they can. No distance, or absence ought any whit to diminish their mutual love.

=== §. 16. #emph[Of the error of Papists about man and wifes separation.] #footnote[#emph[Si quis dixerit Ecclesiam errare cùm ob multas causas separationem inter coniuges quoad thorum, seu cohabitationem, ad certum, incertumue tempus fieri posse decernit, Anathema sit. Concil. Trid.] §. 24. #emph[can.] 8.]

Contrary to the duty of #emph[cohabitation] is the doctrine of Papists, whereby they teach, that

#emph[Separation may be made betwixt man and wife for many causes from bed, or cohabitation, for a certain or uncertain time.] The Council of Trent is bold to denounce #emph[Anathema] against such as say, #emph[the Church erreth therein.] If the many causes which they allege, besides adultery, be well weighed, we shall find them without all warrant of Gods word. #footnote[#emph[Bellarm. de Matrim. l.] 1. #emph[c.] 14.] They draw them to two heads, 1. #emph[Mutual consent.] 2. #emph[Demerit.]

#emph[By consent] (say they) #emph[of both parties married to attain a greater and perfecter estate, marriage consummate may be loosed from bed and cohabitation.]

#emph[Answ.] 1. In marriage there is #emph[a covenant of God] (Prov. 2. 17.) as well as of the two parties: the consent therefore of parties is not sufficient to break it.

2. No estate in this world can be greater or perfecter then is meet for married persons. #emph[Adam] and #emph[Eve] in their best estate were married: and now is #emph[marriage honourable in all.] #footnote[#emph[Heb.] 13. 4.]

3. The estates which they count more perfect, are either such as are not in mans power #emph[(as perpetual continency)] or such as may be as well performed by married persons as by single persons (as #emph[Ecclesiastical functions)] if at least they be such as are warranted by Gods word. High Priests, and other Priests, all sorts of Levites, extraordinary Prophets and Apostles were married. What greater functions then these?

The causes which for #emph[demerit,] they say, make a separation, are 1. #emph[Adultery.] 2. #emph[Departing from the Catholic faith.] 3. #emph[Soliciting or impelling unto sin.]

Concerning #footnote[See §. 5.] #emph[Adultery,] we deny not, but that it giveth just cause of divorce: but withal we say (as #footnote[#emph[Matth.] 5. 32.] we have good warrant from Christs words) that it is the only cause of just divorce. For to make a separation for #emph[departing from the Catholic faith,] #footnote[#emph[Fidei gratia vxorem ne eijcias. Chrys. hom.] 19. #emph[in] 1 #emph[Cor.] 7.] is directly contrary to #emph[S. Pauls] and #emph[S. Peters] doctrine, 1 Cor. 7. 12, 13, 14. 1 Pet. 3. 1.

As for #emph[soliciting and impelling unto sin,] though it may be cause to move an husband or a wife to walk more warily and #footnote[#emph[Si ferus moribus sit coniux, perferat illum vxor, nec vllam ob causam societatem, vinculumque dissoluere patiatur. Basil. Hexaem. hom.] 7. #emph[Matth.] 5. 29.] wisely, and in extremity to avoid society for a time, or to complain to the Magistrate for relief, who may see it meet to lay the delinquent person in prison, or else otherwise keep them sunder till that delinquent be reclaimed and brought to a better mind: yet is it no sufficient cause finally to dissolve marriage in regard of bed and cohabitation.

They urge that #emph[if the right eye cause to offend, it must be plucked out.]

#emph[Ans.] 1. That is but a metaphor, and may sundry other ways be applied.

2. The words are not simply, but by way of comparison to be taken, #emph[rather pluck it out, then to be made to stumble thereby.]

3. #emph[Plucking out,] applied to the point in hand, may be by many other ways, then by dissolving marriage.

4. That general inhibition #emph[(whosoever shall put away his wife,] #footnote[#emph[Matth.] 5. 32.] #emph[causeth her to commit adultery)] restrained only with the exception of fornication, admitteth neither this, nor any other such cause of dissolving marriage.

=== §. 17. #emph[Of husbands and wives unlawful absenting themselves one from another.]

Contrary also to the forenamed duty of #emph[cohabitation,] is the practise of many men, who living themselves in one place (suppose at #emph[London)] send their wives unto some country house, and there even mew them up, as Hawks, never caring to come at them, but are then most merry, when their wives are farthest off. If their wives live at home they will be abroad, mealing and lodging where their wives shall not know: their own house is as a prison to them: they are not well, but when they are out of it. Of the like lewd conceit and practise are many wives, who on no other occasion then mere lightness, being eager in pursuing their pleasures, and satisfying their lusts, gad out of their own houses in the day, lie out of them in the night, and remain in other company days and nights: or at least are glad when their husbands have occasion to be from home; not unlike to the light huswife which #emph[Solomon] describeth, #emph[Prov.] 7. 10. etc. I speak of matters too famous, or rather infamous. I would there were no just cause to tax this lightness. But let such as desire to approve themselves to God or man, take heed of these heinous and more then heathenish vices. #emph[Though Israel play the harlot, yet let not Judah] #footnote[#emph[Hos.] 4. 15.] #emph[offend.]

Too near to the forenamed kind of unlawful separation #footnote[Man and wifes fault in parting rooms and beds in the same house.] do they come, who though they live both in one house, yet make that house by their estranging themselves one from another as two houses: the man abiding in one end thereof, his wife in another: and so have their several rooms, several tables, several servants, all several: Or if the straitness of their house will not suffer them so to part other rooms, yet they will have several bed-chambers, or at least several beds: so as they that shall call them bed-fellows, shall but nick-name them. Thus they rob each other of that due benevolence which they mutually owe one to another, they expose themselves to the devils snares, they more and more estrange their hearts one from another, and deprive themselves of such mutual comforts and helps, as by matrimonial society they might afford to, and receive from one another.
