== Guarding Each Other’s Health, Reputation, and Property

=== §. 29. #emph[Of husbands and wives mutual care over one anothers body.]

After the good of the soul followeth the good of the body, wherein husband and wife must show their provident care each over other: and do what lieth in them to procure the well-fare of one anothers person, and to nourish and cherish one anothers body. This duty the Apostle layeth down under the comparison of a body which he calleth #emph[flesh,] saying, #footnote[#emph[Eph.] 5. 29.] #emph[No man hateth his own flesh, but nourisheth and cherisheth it:] now man and wife are #footnote[#emph[Eph.] 5. 31.] #emph[one flesh.] This duty the Apostle in particular applieth to husbands. At the first institution of marriage it was in particular applied to the wife, whom God made to be #footnote[#emph[Gen.] 2. 18.] #emph[an help meet for man:] so as it is a mutual duty appertaining to both. It seemeth that #footnote[#emph[Gen.] 27. 14.] #emph[Rebekah] was so careful of #emph[Isaac] in this respect, that she could readily make #emph[savoury meat] for him, #emph[such as he loved.]

This duty extendeth it self to all estates both of prosperity and adversity, of health and sickness: for so much do they mutually covenant and promise when they are first joined together in marriage, #emph[I take thee] (saith each to other) #emph[for better for worse, for richer for poorer, in sickness and in health to love and to cherish.] Wherefore they ought mutually both to rejoice in the well-fare of one another, and also in all distress to succour and comfort each other, putting their shoulders under one anothers burden, and helping to ease one another as much as they can. That which #emph[Solomon] said of a friend and a brother, may fitly be applied in this case to husband and wife, #emph[a friend loveth at all times, and a brother is born for adversity,] #footnote[#emph[Pro.] 17. 17.] that is, a trusty and faithful friend is constant in his goodwill, and ready to perform all duties, of kindness at any time, whether it be prosperity or adversity: the change of outward estate maketh no alteration in his loving affection and friendly carriage: yea he seemeth to be as it were born and brought forth against the time of trouble and affliction, because then is his provident care and tender affection most manifested. Of all friends none ought to be more careful, none more faithful one to another then man and wife. How then ought they to love at all times, and if any trial come to either of them, the other so to carry himself, as it may be truly said they were joined together for adversity?

Thus shall they verify the truth of that whereby God was moved to create of mankind male, and female, namely that #emph[it was not good for man to be alone,] but that it was rather good, #footnote[#emph[Gen.] 2. 18.] that is, needful, profitable, and comfortable for man and woman to be together. In which respect the wise-man saith, #emph[he that findeth a wife findeth a good thing;] and by the rule of #footnote[#emph[Pro.] 18. 22.] relation we may infer, #emph[she that findeth an husband findeth a good thing.]

=== §. 30. #emph[Of husbands and wives backwardness to help one another in time of need.]

Contrary to this duty is a certain unnatural affection in sundry husbands and wives, who much grudge to provide the things that are needful for one another. The man commonly thinks the charge too great, the woman thinks the pains too much: they are affected one to another as if they were mere strangers: nay many strangers will be more ready to perform, and more cheerful in performing needful duties (as occasion is offered) then such unnatural husbands and wives. If a little sickness, or other like cross fall on one of them, the other thinks, #emph[never any had such a burden;] and by their discontent make the burden much more heavy then otherwise it would be: even as when two oxen are in one yoke, and the one holdeth back, the draught is made much harder to the other. Thus do they pervert one of the principal ends of marriage, which is to be a continual comfort and #footnote[#emph[Gen.] 2. 18.] #emph[help] each to other, and to ease the burdens of one another: in which respect they are made yoke-fellows. #emph[Jobs] wife by her unnatural carriage towards him in his affliction #footnote[#emph[Job] 2. 9.] did much aggravate his misery: when he stood in most need of her help, she afforded least unto him: it appears by #emph[Jobs] complaint of her, in these words, #emph[my breath is strange to] #footnote[#emph[Job] 19. 17.] #emph[my wife,] that she altogether neglected him in his misery. The common speech of many after their husband or wife having long lien sick is departed, bewrayeth their unnatural affection: their speech is this, #emph[if my husband] (or wife) #emph[had died so much sooner I had saved so much money.] What doth this intimate but that they could have been contented their husband (or wife) should have died sooner that they might have spared the more.

=== §. 31. #emph[Of Husbands and Wives mutual respect of one anothers good name.]

The provident care of husbands and wives ought further to extend it self to the credit and good name of one another. As dear ought the good name of the wife be unto the husband, and of the husband to the wife, as their own. #footnote[#emph[Mat.] 1. 19.] The great regard that #emph[Joseph] had of the credit of #emph[Mary] his espoused wife, made him think of putting her away privily when he observed her to be with child and knew not of whom: for he was not willing #emph[to make her a public example.] The same respect moved #footnote[2 #emph[Sam.] 11. 5.] #emph[Bathsheba] to send secretly to #emph[David,] and tell him that she was with child. The commendation which the good husband (#footnote[#emph[Pro.] 31. 28. 1. A good name is precious.] noted by #emph[Solomon)] giveth of his wife being approved by the Holy Ghost, showeth how man and wife ought in that respect to honour each other: and that on good grounds. For

1. A good name is a most precious thing: #footnote[#emph[Eccl.] 7. 3.] #emph[better then precious ointment,] which giveth a sweet savour, and #footnote[#emph[Pro.] 22. 1.] to be chosen #emph[above great riches.] #footnote[2\. The good name of the one is the honour of the other.]

2. So nearly are husbands and wives joined together, the good name of the one cannot but tend to the honour and credit of the other; so that herein they seek their own honour also.

=== §. 32. #emph[Of husbands and wives preventing each others discredit.]

For direction herein, consider we how this duty may be #footnote[Directions concerning a good name.] #emph[performed,] and how it may be #emph[manifested.]

For the better performing of it, care must be had both to #emph[prevent] and #emph[redress an ill name,] and also to #emph[procure] and #emph[preserve a good name.]

To #emph[prevent an ill name] respect must be had of these three things following, #footnote[1\. Prevent an ill name, and that]

- 1\. What one relateth of another, and how.
- 2\. What ear they give to things related by others.
- 3\. What censure they give of one another.

For the #emph[first,] husbands and wives may in no case delight to #footnote[1\. By concealing things of ill report.] discover unto others, and spread abroad the infirmities, and imperfections of one another, or any thing that may tend to the discredit of either of them: but rather cover and conceal them as much as they may with a good conscience. It is expressed that #footnote[#emph[Mat.] 1. 19.] #emph[Joseph being a just man] laboured to conceal that blemish which he imagined to be in his wife, so as this may stand with #emph[justice:] yea also it is a part of #emph[love,] for #footnote[1 #emph[Pet.] 4. 8.] #emph[love covereth a multitude of sins.]

For the #emph[second,] husbands and wives must not have their #footnote[2\. By closing ears against ill reports.] ears wide opened to hear every tale and report that shall be brought to one against the other, but rather show themselves displeased and offended with them that are ready to relate things of evil report. If an husband or wife manifest a willingness to hearken after tales and reports of one another, the devil will stir up instruments enow to fill their heads with tales, and those for the most part both frivolous and forged: not only strangers, but children, servants, and they which are of the same family will ever be telling some tale or other, to curry favour, as we speak. But an utter dislike of such flattering tale-bearers, will take away occasion from them of telling untrue, or slight reports.

For the #emph[third,] the judgment and censure which husbands #footnote[3\. By forbearing to censure rashly.] and wives give one of another must either be very charitable, or very sparing. If one hear reported any notorious crime of the other, they may not be over-heady or hasty to judge and condemn, no though they think they see some evidence thereof, but rather suspend their judgment. This seemeth to be the mind of #emph[Joseph:] though he observed #emph[Mary] to be with #footnote[#emph[Mat.] 1. 19.] child, yet would he not presently judge her to be a notorious adulteress, or condemn her for an hypocrite, unworthy to live, and therefore would not make her a public example.

In brief, that husbands and wives may be the more sparing in censuring one another, they must not rashly believe any evil report of one another, but rather suppress all light suspicions as much as they can.

That the judgment which they give one of another, may be charitable, in judging they must well observe the properties of love, which are 1. To interpret doubtful things in the better part. 2. To mitigate, so far as truth and justice will suffer, the faults which are evident. #emph[Michal] offended against #footnote[2 #emph[Sam.] 6. 20.] the first in an high degree, and was cursed. #emph[Abigail] observed #footnote[1 #emph[Sam.] 25. 25.] the latter, and was blessed.

=== §. 33. #emph[Of the wisdom of husbands and wives, in redressing one anothers ill name.]

To #emph[redress an ill name,] husbands and wives must first give one another notice of the report that goeth of them, and endeavour #footnote[2\. Redress an ill name.] to work in them both a sight, and also a sense of those evils which are in the mouths of others: after notice given, they must labour to bring them to repentance of those sins, for which they are ill reported of, and to a manifestation of repentance, by doing things meet for repentance, which is by a zealous and conscionable practise of such virtues as are clean contrary to the vices for which they were evil spoken of. It may with good probability be gathered out of the history of the Levite, whose wife played the whore, that thus he #footnote[#emph[Judg.] 19. 1, 2, #emph[etc.]] dealt with her. And thus #emph[Abigail] endeavoured to deal with her husband. #footnote[1 #emph[Sam.] 25. 37.]

=== §. 34. #emph[Of husbands and wives care in procuring one anothers good name.]

To #emph[procure a good report,] husbands and wives must #footnote[3\. Procure a good report.] First, take notice of the good qualities which are in one another, and as one hath occasion to speak of the other, to make those good qualities the subject of their speech: as we #footnote[#emph[Pro.] 31. 28, 29.] heard it before commended in the husband of that wife which is described by #emph[Solomon.]

Secondly, they must lend a willing and joyful ear to such as shall (so far as they can conceive) truly and unfeignedly, without flattery or hypocrisy, speak any thing in commendation of the one or of the other: not thinking themselves dispraised (which is the conceit of many) when their bed-fellow is praised: but rather having their hearts the more enlarged to praise God, for bestowing on them such an excellent token and pledge of his favour.

Thirdly, they must imitate those good things which they behold, or hear to be in one another, and so imitate them as they which have before time known both husband and wife, may say, this she learned of him, or this he learned of her.

=== §. 35. #emph[Of husbands and wives wisdom, in preserving each others good name.]

To #emph[preserve a good name,] it will be meet for an husband or #footnote[4\. Preserve a good name.] wife, wisely and seasonably to give one another notice of that good fame which is raised of them, thereby to provoke them both to give glory to God for the same (#footnote[#emph[Col.] 1. 3, 4.] as the Apostle thanketh God for that report which was spread abroad of the faith and love of the Colossians) and also to walk worthy of that good report (as the Apostle who had given a great testimony of the bounty of the Corinthians, earnestly exhorteth them to finish their benevolence, #emph[lest] (saith he) #emph[I should be ashamed in] #footnote[2 #emph[Cor.] 9. 4.] #emph[this my constant boasting.)] For if they of whom there is once a good report raised, decay, wax cold, grow backward, or fall into notorious and scandalous sins, they will clean extinguish and put out their good name among men, and turn it into an evil report, according to that which #emph[Solomon] saith, #emph[Dead flies cause the ointment of the Apothecary to send forth a] #footnote[#emph[Eccles.] 10. 1.] #emph[stinking savour: so doth a little folly him that is in reputation for wisdom and honour.] #footnote[5\. Manifest a care of one anothers good name.]

=== §. 36. #emph[Of husbands and wives like affection towards one anothers credit.]

In the last place, to manifest a mutual provident care of one anothers good name, husbands and wives must be so affected with the report that goeth of either of them, as if the report were of their own selves. If the report be good, to be glad thereof, and to rejoice thereat; if it be evil, to be grieved, and after an holy manner vexed at it: thus shall they show a true sympathy and fellow feeling of one anothers credit, according to that general rule of the Apostle, #footnote[#emph[Rom.] 12. 15.] #emph[Rejoice with them that rejoice, and weep with them that weep.]

=== §. 37. #emph[Of the vices contrary to that mutual care, which man and wife should have of one anothers credit.]

Vices contrary to these duties concerning the good name of #footnote[Contrary vices.] an husband and wife, are in general two.

One is a readiness to disgrace and discredit one another, #footnote[1\. To discredit each other, and that] like #emph[Michal] the wife of #emph[David,] of whom we heard before. A hateful and detestable vice this is, which cannot stand with #footnote[2 #emph[Sam.] 6. 20.] true matrimonial love, but rather argueth an utter dislike, and a plain hatred of one another.

Husbands and wives discredit one another, either by procuring an ill name, or hindering a good name.

An ill name is procured by these means following.

1. By blazing abroad one anothers infirmities: as when #footnote[1\. By blazing one anothers infirmities abroad.] tattling Gossips meet, their usual prate is about their husbands, complaining of some vice or other in them: #emph[My husband,] saith one, #emph[is covetous: I cannot get of him any thing almost: he maketh me go as no body goeth. And my husband,] replieth another, #emph[is so furious as none can tell how to speak to him:] so one after another goeth on in this track, some discovering such infirmities as should be concealed; others (which is worse) plainly belying their husbands. In like manner also husbands when they meet with their boon companions, make their wives the common subject of all their talk: one accusing his wife of one vice; another his, of another. There are two respects for which this vice (most detestable in it self) is made more odious in an husband or a wife. 1. Because they know more then any other of one anothers infirmities: so as if they be so evilly minded, they may much more discredit one another, then any other can. 2. Because in regard of their near union they are most bound to conceal and cover each others imperfections. #footnote[#emph[Gen.] 9. 22, 25.] #emph[Ham] was cursed for revealing his fathers nakedness. But a more horrible curse do husbands and wives deserve, that so do.

2. By opening their ears, and giving credit to every light #footnote[2\. By hearing and believing others ill reports.] report that any shall raise. More secret heart-burning of one against the other, and more open quarrels and contentions betwixt them, ordinarily arise from hence then from any other thing.

3. By perverting and mis-interpreting one anothers actions, #footnote[3\. By turning every thing to the worst.] words, yea and thoughts also: taking every thing in the worst part.

4. By concealing from one another the common evil rumors #footnote[4\. By concealing evil rumors.] which are raised of them, and are in every mans mouth: of all other, bedfellows are most fit to disclose such things one to another: and most bound to do it. Most fit, because of their mutual familiarity: most bound, because of their near union.

Many husbands and wives do hinder one anothers good #footnote[5\. By envying and gainsaying good reports.] name by envying one at the good report that is made of the other, and gainsaying the same: as if the credit of the one must needs turn to the discredit of the other. Thus as water quencheth hot iron, so this envious disposition is a means to extinguish the heat of fame, and to put out the glorious light of a good name. Whereby as they impair the credit and honour of one another, so they monstrously discredit and dishonour themselves.

The other general vice in this kind, is a careless regard, #footnote[2\. Neglect of each others fame.] or plain neglect of one anothers fame: when the husband is no way affected with any report that goeth of his wife, nor the wife with any of the husband: but as if they were mere strangers one to another, they pass by all reports made of one another. What mutual love can there be in such? Howsoever their hands have been joined together, surely their hearts were never united, so as it had been better they had never known one another, unless the Lord do afterwards knit their hearts, and unite their affections more nearly and firmly together.

=== §. 38. #emph[Of husbands and wives mutual providence about the goods of the family.]

Yet there remaineth one thing more, whereabout husbands #footnote[Treatise 3. §. 29.] and wives ought to manifest a mutual provident care each over other: and that is about the goods of this world. Howsoever the husband, while he liveth with his wife, hath the truest property in them, and the greatest title unto them, yet I refer this to those mutual duties which man and wife owe each to other, in three respects.

First, because in conscience they appertain to the use of the wife, as well as of the husband.

Secondly, because the wife is by Gods providence appointed a joint governor with the husband of the family, and in that respect ought to be an help in providing such a sufficiency of the goods of this world, as are needful for that estate wherein God hath set them, and for that charge which God hath committed to them.

Thirdly, because the wife, if she survive the husband, ought to have such a portion of those goods, as are meet for her place and charge.

In these respects we see it requisite, yea a bounden duty, that husband and wife, even in a mutual regard one of another, be as provident as they can be with a good conscience in getting, keeping, and disposing competent goods and riches for the mutual good one of another. Concerning the husbands duty in this respect no question is made: the practise of all good husbands mentioned in Scripture, the care of providing for their #footnote[1 #emph[Tim.] 5. 8. See Treat. 4. §. 46.] #emph[own] enjoined to them, their place and office to be their wives #emph[head,] with many other like arguments, whereof we shall more distinctly speak, when we come to declare the particular duties of husbands, do prove as much. The greatest question is concerning the wife, whether she be bound to take any care about the goods. But if the Scripture be thoroughly searched, we shall find proof enough to show that even she also is bound hereunto. For first, the general end which God aimed at in making the woman (namely to be #footnote[#emph[Gen.] 2. 18.] #emph[an help] to man) implieth as much: for herein may she be a very great help, as we shall see by and by in sundry particulars. 2. That general property attributed to a wife to be #footnote[#emph[Prov.] 18. 22.] #emph[a good thing,] confirmeth as much: for that which is profitable is called good: and it is one respect wherein a wife is termed a #emph[good thing,] that she may by her providence and diligence bring much profit to her husband: and therefore in this, among other respects, the good wife which #emph[Solomon] describeth, is said #footnote[#emph[Prov.] 31. 12.] to #emph[do good] to her husband all the days of her life: for by her industry and providence she did so preserve and increase his goods, that #footnote[#emph[Vers.] 11.] #emph[the heart of her husband trusted in her, and he had no need of spoil.] If the particular actions whereby that good wife is described be well noted, we may easily observe that she was an especial help unto her husband, even in his outward estate. From all which, we may infer these two points. First, that this provident care about outward temporal goods is lawful, not unbeseeming a Christian man or woman. Secondly, that it is a mutual duty appertaining both to husband and wife.

For the first, how needful the goods of this world are for preservation of life and health, estate of the family, good of Church and common-wealth, relief of the poor, with the like uses, no man can be ignorant. God hath given them as blessings to his children, and that often times in great abundance; and his children have accordingly been thankful for them: so as a provident care about them is not unlawful, but very expedient and needful.

For the second, If there should not be a joint care herein, the care and pains of the one might be altogether in vain. For suppose an husband be industrious, as #footnote[#emph[Gen.] 31. 40.] #emph[Jacob] was, and get much abroad, if the wife either by her unthriftiness, idleness, negligence, or the like vices, suffer that which is brought home to be embezzled and wasted; or by her prodigality, bravery, or love of vain company, consume it her self, where will be the profit of the husbands pains? Or on the other side, if a wife should be as painful and prosperous in getting, as #footnote[#emph[Prov.] 31. 10. #emph[etc.]] the good housewife before mentioned was, and the husband by carding, dicing, drinking, revelling, or other like means should waste all away, what fruit would remain of the wives providence? In this mutual provident care of husband and wife, each of them must have an eye to their own place: affairs abroad do most appertain to the man, and are especially #footnote[Externa negotia viro permitte. Greg. Naz. ad Olymp.] to be ordered by him: that which the wife is especially to care for, is the business of the house: for the Apostle layeth it down as a rule for wives (as we shall hereafter more particularly declare) that they #footnote[#emph[Tit.] 2. 5.] #emph[keep at home,] and #footnote[1 #emph[Tim.] 5. 14.] #emph[govern the house.] By this means may they be very profitable each to other.

=== §. 39. #emph[Of the vices contrary to the good providence of husband and wife, about the goods of the family.]

Contrary to that duty, are these vices following.

1. #emph[Covetousness,] and overmuch care for themselves: as #footnote[Contrary vices.] when an husband so raketh, and scrapeth, and hoardeth up for himself, as he neither affordeth unto his wife so much as is #footnote[1\. Covetousness.] meet for her place while he liveth with her, nor thinketh of providing sufficient maintenance for her, if she over-live him, but rather thinketh how to defraud her of that which the law casteth upon her. Or when a wife secretly hoardeth up whatsoever she can get, either by her own industry, or else by purloining from her husband: sometimes selling corn, wares, household-stuff, or other like commodities, so privily as the husband shall never know it: sometimes taking money out of his counter, box, bag, chest, or the like, so as either it shall not be missed, or if it be, it shall not be known who had it. Many there be who in mistrust of their husbands providence, or in dislike of them, or on some other by-respects, commit whatsoever they can get to the trust and custody of others, whereby it oft cometh to pass, that they themselves, meeting with deceitful friends, are utterly defeated, even because they dare not make their fraud known. As Covetousness is in it self an odious sin; so it is made much more heinous by defrauding husband or wife, who ought to be as dear each to other as themselves.

2. #emph[Prodigality,] and too lavish spending upon themselves, #footnote[2\. Prodigality.] and those things which are most agreeable to their own corrupt humor: as when husbands without any mean or measure, spend their goods abroad in hunting, hawking, carding, dicing, eating, drinking, or the like, and suffer their wives to want at home, and yet took their wives to maintain them, and therefore had their portion. Or when wives bring their husbands into debt, and weaken, if not clean overthrow their estate, by gorgeous decking and adorning their houses, by brave and costly apparel, by dainty fare, by gossipping abroad, with the like. Many wives are so violent herein, that if their desire and humour be not satisfied, their husbands shall have no rest (forsooth they brought a portion, and maintained they must and will be; it skilleth not whether their husbands estate can bear it or no) in so much as many are forced wittingly, for quietness sake, to suffer their estate to sink. O foolish and wretched wives! How little do they consider that they were married to do their husbands good, and not evil all the days of their life? Is this to be an help to man? Or rather is it not clean to thwart Gods counsel, and pervert his purpose? Can we think that God will forbear, and not be avenged of them? Yet much more will God be avenged of the forenamed husbands, because of that image of himself which he hath placed in them, and because of that place and authority wherein he hath set them. The Apostle expressly saith of them, that #emph[they are worse then Infidels,] which being so, they must look for #footnote[1 #emph[Tim.] 5. 8.] the greater judgment.

3. #emph[Idleness,] and a careless neglect of their estate. Many #footnote[3\. Idleness.] men spend day after day, like a bird that flieth up and down, as it falleth out, from tree to tree, from twig to twig: they go from place to place, but know not for what end: as they meet with any company, so they abide as long as the company tarrieth, and then seek after other company, and are ready to go with any to Ale-house, Tavern, Play-house, Bowling-alley, or other like places. Many women also spend all the forenoon in lying a bed and tiring themselves, and the afternoon as occasion is offered in sitting idly at home, or walking forth to little purpose, but only to wear out time, little regarding their husbands estate, whether it increase, or diminish. Thus by the idleness and carelessness of husband and wife, come fair estates many times to ruin, and both of them brought to penury and beggary.
