== Serving Together in Family Ministry

=== §. 40. #emph[Of husbands and wives joint care in governing the family.]

Hitherto I have delivered such common duties as mutually respect the husband and wife, and are to be performed of each to other. There are other common duties which they are both jointly bound to perform to other persons: and those either #emph[members] of the family, or #emph[strangers] coming to the family.

Concerning the #emph[members] of the family, though there be some peculiar duties belonging to the master, and some to the mistress, some to the father, and some to the mother, of which we shall speak in their due place; yet in general the government of the family, and the several members thereof belongeth to the husband and wife both (if at least they have a family) and a joint common duty it is to be helpful one to another therein.

#emph[Object.] Seeing it is not necessarily required, that a husband and wife should have a family to govern, for two may be married and have neither children nor servants (as many are) and yet be true husband and wife; why is this care of a family ranked among the duties of husband and wife?

#emph[Answ.] 1. Because ordinarily when two are married they gather a family, and are the governors thereof: so as though it fail in some particulars, yet for the most part it holdeth.

2. Because the joint government whereof I speak in this place is by virtue of the marriage-bond: for if a man and a woman should live together in an house, and by mutual consent have a joint authority and government, this would be very offensive to all that should know it, or hear of it: neither were they by any ordinance of God bound to be so helpful one to another as husband and wife: nor the members of a family so bound to subject themselves to both.

3. The duty whereof I speak, though it be about the government of a family, yet hath it respect to an husband as he is an husband, and to a wife as she is a wife; namely, that by virtue of their marriage-bond, and near union, they be helpful one to another in well-ordering the things of the family.

Whether the man ought to look to the good government of his house is a question without all question. He is the highest in the family, and hath both authority over all, and the charge of all is committed to his charge: he is as a king in his own house: as a king is to see that land well governed where he is king, so he that is the chief ruler in an house. The duty which the Apostle applieth in particular to Bishops & Deacons, in general appertaineth to all husbands, #footnote[1 #emph[Tim.] 3. 4.] that they #emph[rule their own house honestly:] and again, #footnote[#emph[Vers.] 12.] that they be #emph[such as can rule their children well, and their own households.] The care of many husbands is in this respect commended in Scripture, as of #footnote[#emph[Gen.] 18. 19.] #emph[Abram,] of #footnote[#emph[&] 35. 2, #emph[etc.]] #emph[Jacob,] of #footnote[#emph[Jos.] 24. 15.] #emph[Joshua,] of #footnote[#emph[Psal.] 101. 2. #emph[etc.]] #emph[David,] the #footnote[#emph[Joh.] 4. 53.] Ruler at Galilee, and of many other. That the wife also ought to be an help to him therein, is very evident: for the Apostle layeth it expressly to their charge, #footnote[1 #emph[Tim.] 5. 14.] that they #emph[govern the house:] would the Wise man have so highly commended a wife #footnote[#emph[Prov.] 31. 11, #emph[etc.]] for well governing her husbands house if it had not appertained to her? It is very likely that wise #emph[Abigail] had a great hand in governing #emph[Nabals] house, because the servants made complaint to her of #emph[Nabals] churlishness, and because she had the servants at command, readily to do what she would have them; yea also, because she could so readily prepare such store of provision for #emph[David] and his men, as she did. Hence is it that the wife is called #footnote[Mater-familias.] #emph[mistress of the house,] as well as the husband #footnote[Pater-familias.] #emph[master of the house.]

#emph[Object.] #footnote[1 #emph[Tim.] 2. 12.] #emph[A woman is not to teach, nor to usurp authority over the man.]

#emph[Answ.] 1. That branch of #emph[teaching] hath respect to public assemblies, and Churches, in which she may not #emph[teach:] but not to private families, in which she may, and ought to #emph[teach:] for #footnote[#emph[Pro.] 31. 4.] #emph[Bathsheba] taught #emph[Solomon.] When #footnote[#emph[Acts] 18. 26.] #emph[Apollos] was brought to the house of #emph[Aquila, Priscilla] the wife of #emph[Aquila] did help to expound to #emph[Apollos] the way of God more perfectly.

2. The other branch concerning #emph[authority,] hath not reference to the inferior members in the family, over which the wife of an household governor hath authority, but only to the husband, over whom if she take any #emph[authority,] she usurpeth it. Therefore neither this place of Scripture, nor any other doth exclude the wife, being jointly considered with the husband, to rule & govern those in the family which are under them both.

2. #emph[Object.] This joint government of the wife doth much impair the dignity and authority of the husband.

#emph[Answ.] Nothing less: for she is subordinate to her husband, and must so rule others as she be subject to her husband, and not command any thing against his command, (provided that his command be not against the Lord, and his word.) We see that in all estates the king or highest governor hath other Magistrates under him, who have a command over the subjects, and yet thereby the kings supreme authority is no whit impaired, but rather the better established, and he the more honoured. So is it in a family. #footnote[1\. #emph[Reason.] Husbands and wives by their mutual assistance bring great help one to another. #emph[Plus vident oculi quàm oculus. Arist. Polit. li.] 3. #emph[c.] 7.]

Let therefore husbands and wives herein assist one another, for so they may be very helpful one to another, and bring, by their mutual help in governing, much good to the family. The husband by his help aiding his wife, addeth much authority unto her, and so causeth that she is not despised, nor lightly esteemed. The wife by her help causeth many things to be espied, and so redressed, which otherwise might never have been found out: for two eyes see more then one, especially when one of those is more at hand, and in presence, as the #footnote[2\. #emph[Reason.] Many things in a family more fit for the one to meddle with, then for the other.] wife is in the house.

Besides there are many things in well governing a family more fit for one to meddle withal then for the other: as for the husband to meddle with the great and weighty affairs of the family (as performing Gods worship, appointing and settling good orders, providing convenient house-room, and other necessaries for the family: keeping children when they grow #footnote[#emph[In familia dispertita sunt officia: suntque alia viri, alia vxoris propria. Prosunt ergo vterque alteri sua in commune conferentes: ob eamque causam suauitas in hac tali amicitia inest, vtilitasque maxima. Arist. Eth. li.] 8. #emph[ca.] 12.] great, or wax stubborn, in awe: ruling men servants, with the like.) And for the wife to meddle with some less, but very needful matters, as nourishing and instructing children when they are young, adorning the house, ordering the provision brought into the house, ruling maid servants, with the like. Yea further, as the man especially is to perform the very actions of prayer, reading the word, catechizing, and other like duties in the family, so the wife may be a great help in putting her husband in mind both of the duty it self, and of the time of performing it, and encouraging him to do it, in gathering the family together, and exhorting them to be forward, in making her self an example to the rest by her diligent and reverend attention, in oft urging and pressing to her children and servants such points of instruction as her husband hath taught; yea, in praying, reading, teaching, and performing like exercises her self, so far as she is able, when her husband is absent, or negligent and careless, and will not himself do them; or it may be, is not able to do them: or if she perform them not her self, in getting some other to perform them.

=== §. 41. #emph[Of the vices contrary to a joint care of governing the family.]

The mind and practise of many, both husbands and wives, #footnote[Vices contrary.] is contrary to this duty.

Many a husband because the wives office is especially to #footnote[1\. When husbands put off all government to their wives.] abide at home, will put off all government to the wife: leaving it to her not only to order the things in the house, but also to bring in all needful things, to order and govern the children both young and old, yea even to provide for them also, to take in, to put out, to use all sorts of servants as pleaseth her: yea, if servants shall be stubborn and stout against her, he will take no notice of it, nor endure to be told of it, much less afford her his assistance, but suffer her to be disgraced and despised. As for religious duties, he will no way meddle with them. Oh base minded men, unworthy to be husbands and heads of wives! Shall your wives who were made to be an help to you, have no help from you, no not in those things which especially belong to your charge? Shall the weaker vessels bear all the burden? Assuredly as the man carrieth away the greatest reputation and honour when a family is well governed (though it be by the joint care and wisdom of his wife) so lieth he most open to the judgment of God if the government thereof be neglected, and through the neglect thereof, children and servants grow impious: instance #footnote[1 #emph[Sam.] 3. 12, 13.] #emph[Eli,] and #footnote[2 #emph[Sam.] 15.] #emph[David.] For as in a common-wealth, the greatest honour of good government, victorious battles, happy peace, and prosperity, and the greatest dishonor and damage of the contrary, redoundeth to the king, so to the man who is chief governor in a family: for it is presupposed, that all which do any good are instruments of the highest governor: if any evil or mischief fall out, that it is through his negligence.

On the other side, because the husband is the most principal, #footnote[2\. When wives refuse to add their aid.] many wives think that the government of the family nothing at all appertains to them, and thereupon are careless of the good thereof, and will not stir their least finger to order any thing aright: but, if any thing be amiss, lay all the blame on their husbands. Do not such pervert that main end for which God made them, even #emph[to be an help?] Do they not carry themselves most unworthy of the place wherein God hath set them, namely to be joint-governors with their husbands, and partakers of their dignities? As by their negligence they make themselves accessary to all the evil which falleth out in the family, so assuredly shall they have their part in those judgments which are executed on the head thereof.

Most contrary to the forenamed duty is the practise of #footnote[3\. When husbands or wives are hindrances each to other.] such as are hindrances one to another in governing the family: as when wives are not only negligent themselves in coming to religious exercises, but keep back children and servants, and so are a great grief unto their religious husbands: or when they use any of the children or servants to be instruments of iniquity; or are themselves disquiet and troublesome in the house, like to her of whom #emph[Solomon] speaketh in this proverb, #emph[It is better to dwell in the corner of the house] #footnote[#emph[Pro.] 21. 9.] #emph[top, then with a contentious woman in a wide house.]

Husbands also are oft an hindrance to that good government which their wives would help forward, when they scoff and scorn at that good counsel which their wives give them for that purpose, or when they will not suffer their wives to meddle with any thing at all, nor endure that they should find any fault, much less take in hand to redress any thing that is amiss. These and such like perverse dispositions are in husbands and wives, whereby it cometh to pass that they who were joined together to be a mutual help each to other, prove heavy, yea intolerable burdens.

=== §. 42. #emph[Of husbands and wives mutual help in hospitality.]

The next common duty of husband and wife respecteth such as come to their house, but are no particular members thereof, whether they be kindred, alliance, acquaintance, or strangers, especially if they be Saints, to whom #footnote[#emph[Heb.] 13. 2. #emph[Rom.] 12. 13.] #emph[hospitality,] that is, a kind and courteous entertainment, is due. Herein therefore must husbands and wives be helpful one to another: for as it is required of #footnote[1 #emph[Tim.] 3. 2.] husbands, so also of #footnote[#emph[&] 5. 10.] wives #emph[to be harborous,] namely while they are married, together with their husbands, and when they are widows, of themselves. #footnote[#emph[Gen.] 18. 6. #emph[etc.]] #emph[Abraham] and #emph[Sarah] were herein an help one to another, when the three Angels in shapes of men came to their house: so were #footnote[2 #emph[King.] 4. 8.] the Shunammite and her husband when #emph[Elisha] the Prophet came to their house.

For hospitality, that it is a commendable duty belonging #footnote[#emph[Reasons.] 1. Hospitality a commendable duty.] to such as are house-keepers and able to give entertainment, is evident by the precepts and examples before specified, as also by the blessing which God thereupon hath brought to the houses of them that were given thereunto, which the Apostle intimateth in these words, #footnote[#emph[Heb.] 13. 2.] #emph[thereby some have entertained Angels unawares.] Now therefore husbands and wives being (as we have heard) joint governors, as in other things, so in this they ought to lend an helping hand each to other, and that for these reasons.

1. Because in giving entertainment there are sundry #footnote[2\. The entertainment will be the better by a mutual help.] things to be done, whereof some are proper to the husbands place, and some to the wives. To take order for the provision of things without doors is more fit for the husband, #footnote[#emph[Gen.] 18. 7.] #emph[Abraham] did it: to order the smaller things within doors is more fit for the wife; that was left to #footnote[#emph[Vers.] 6.] #emph[Sarah.]

2. Because it is meet that guests should know they are welcome #footnote[3\. Guests will be more cheerful.] both to the husband and to the wife, that so they may be the more cheerful.

3. Because a mutual consent, and cheerful help herein will #footnote[4\. Mutual love will be more firm.] be an especial means, as to manifest their mutual affection, so to hold the hearts of man and wife firm and close together, and make them the better like and love one the other: especially if the husband shall show himself as ready and willing to entertain his wives friends and kindred as his own, and so the wife her husbands (as they ought.) For as they themselves are made one flesh, so ought each of them to esteem of the others friends as of their own.

4. Because thus they show a mutual desire of bringing #footnote[5\. A desire of one anothers good manifested.] Gods blessing on each other, and upon their whole family.

=== §. 43. #emph[Of vices contrary to mutual help in hospitality.]

Contrary to this duty is for the most part covetousness in the husband, and laziness in the wife. The man, because the charge of the family lieth on him, distrustfully feareth lest he should want for his own.

I deny not but that a provident care for our own, & namely for them of the family, is needful and commendable, #footnote[1 #emph[Tim.] 5. 8.] #emph[he that provideth not for them is worse then an infidel:] so as a man may be overlavish in giving entertainment, if he go beyond his means, impoverish his estate, and disable himself to provide for his own, as many do: yet when a man hath sufficient, yea and abundance, when there is no just cause, but merely upon an undue fear too carkingly, and distrustfully to pinch, and grudge to give entertainment to any, is unbeseeming a Christian, yea also to be worse then an infidel; not worthy to have an house, or any thing fit for entertainment; no nor worthy of common society.

The woman on the other side grudgeth at the pains she must take, and trouble she must undergo about entertaining guests, and thereupon is loth that any at any time should come to their house.

Concerning a wife, I deny not but that an husband may be in this kind overburdensome to her, by being too jovial, as they speak, and bringing guests too often into the house, especially if they be guests of no good name; and by that means make her even weary of her life: but yet for a wife to refuse all pains in that kind, and to be discontented when her husband invites any friends, or when any come (as the three Angels did to #emph[Abraham)] unawares, argueth not a loving affection, nor a wivelike subjection unto her husband, to be in her.

These faults are so much the greater when the husband, or wife, are free and forward in entertaining their own kindred and friends: but are backward, and grudge at the entertainment of each others friends and kindred. Hence commonly ariseth much heart-burning of one against the other: yea much jar and contention betwixt them: and from dislike of the practise of one another in this kind oft followeth a dislike of one anothers person: so that as the fault is bad in it self, it proves to be much worse in the mischiefs that follow upon it.

=== §. 44. #emph[Of husbands and wives mutual help in relieving the poor.]

The last common and joint duty wherein husband and wife ought to be helpful each to other, respecteth those that are without the house, namely the #emph[poor,] and such as stand in need of their help, who are to be #emph[relieved and succoured.] Because man and wife usually meal together, and are joint partakers of Gods good creatures, they must put one another in mind of that precept of charity which was given to the Jews when they were at their meals, #footnote[#emph[Neh.] 8. 10.] #emph[send part unto them for whom none is provided.] The good wife which is set forth by the holy Ghost for a pattern and example unto others to follow, together with her husband, are noted to be helpful one to another in this duty: for she is said #footnote[#emph[Pro.] 31. 20.] #emph[to stretch out her hand to the poor, and to the needy:] and he is said #footnote[#emph[Vers.] 28.] #emph[to praise her,] thereby encouraging her to hold on in doing those good things which she did. What liberty the wife hath, or how far forth she may be restrained in case her husband utterly refuse to give consent, we shall #footnote[#emph[Treat.] 3. §. 23. 33.] hereafter declare in the particular duties of wives: the point here noted is, that both the husband himself must according to his ability be bountiful to the poor, and suffer his wife, yea provoke her so to be, and withal allow her wherewithal to be bountiful: and that the wife also must stir up her husband to liberality in this respect, and her self open her hand to the poor in the things which lawfully she may give.

There is nothing whereby a man or wife can bring more profit to the house, then by giving to the poor: that which is given to the poor is #footnote[#emph[Prov.] 19. 17.] #emph[lent to the Lord, and he will repay it with great increase:] it is as #footnote[2 #emph[Cor.] 9. 6.] #emph[seed,] which being #emph[liberally sown,] will bring forth a #emph[plentiful] harvest: yea, it is a means to make us #footnote[#emph[Luke] 16. 9.] #emph[friends,] to speak a good word for us at the bar of Christs judgment seat: and it bringeth not only the #footnote[#emph[Job] 29. 13. & 31. 20.] #emph[blessing of men,] but #footnote[#emph[Matth.] 5. 7.] #emph[of God] also, even the greatest blessing of all, the #footnote[#emph[Mat.] 25. 34.] blessing of eternal life: for it is #footnote[#emph[Heb.] 13. 16.] #emph[a sacrifice with which God is well pleased.] The Apostle noteth this to be one of Christs oracles, which by word of mouth he left unto his Disciples, #footnote[#emph[Acts] 20. 35.] #emph[It is more blessed to give then to receive.]

Besides, husbands and wives in distributing alms, may receive #footnote[2\. Husband and wife in place to give good direction one to another.] good direction one from another: the husband by telling the wife who are fit to be relieved (for commonly husbands better know those which are abroad out of the family) the wife by telling the husband what things are fittest to be given away: for wives commonly know of what things there is greatest store, and what may in the house be best spared.

=== §. 45. #emph[Of husbands and wives unmercifulness to the poor.]

Contrary is the unmercifulness of many husbands, who #footnote[Vices contrary.] are not only hard-hearted themselves (never giving any thing unless by the law of the land they be forced, & then they part #footnote[1\. Unmercifulness of the husband.] with that which is given, so grudgingly, as it is nothing at all acceptable to God (for #footnote[2 #emph[Cor.] 9. 7.] #emph[God loveth a cheerful giver)] but also tie their wives hands, and suffer them to give nothing. Wherein #footnote[2\. Binding his wives hands.] they bring both the cry of the poor, and also the groans and grief of a merciful wife who is thus restrained, upon their own necks, and aggravate their sin in an high degree.

On the other side, the unmercifulness of many wives is also contrary to the forenamed duty: for there are many, who though they have liberty to give of the common goods, and also allowance of their own out of which they may give, yet covetously hoard up all they can get, give not a pennies worth, but rather suffer victuals and other things to perish in the house, and when they are naught to fling them away, then that any thing whilst it is good should be given out of the house. Shall not the creatures which are spoiled in an house, and the poor that have wanted, make a loud cry in the ears #footnote[Read #emph[Jam.] 5. 1, 2. #emph[etc.]] of the Lord against them? Yea further, many wives are grieved at their husbands bounty, and still moving him to shut his hand, and give no more. Are they not plain devils herein, opposing against that which is good?
