== A Wife’s Active Obedience to Her Husband

=== §. 43. #emph[Of a wives active Obedience.]

It is a good proof and trial of a wives obedience, to abstain from doing such things as otherwise she would do, if her husbands contrary will did not restrain her: but yet that is not sufficient, there must be an active, as well as a passive obedience yielded. That old Law before mentioned #emph[(thy desire shall be subject to thine husband, and he shall rule over thee)] implieth so much also. If she refuse to do what he would have her to do, her desire is not subject to him, but to her self, neither doth he rule over her.

This active part of her obedience hath respect

1. To his #emph[commandments,] readily to do what he lawfully #footnote[A wives active obedience respecteth first her husbands commandment.] commands.

2. To his #emph[reproofs,] carefully to redress what he justly blameth.

For the first, so far ought a wife to be from thinking scorn to be commanded by her husband, that the very knowledge which by any means she hath of her husbands mind and will, sought to have the force of a straight commandment with her. This readiness to obey is commended in the wives of #emph[Jacob,] to whom when #emph[Jacob] had declared what motives he had to depart from their fathers house, intimating thereby that he meant to depart, and would have them to go with him, yet before he particularly expressed his will, they readily answered, #emph[Whatsoever God] #footnote[#emph[Gen.] 31. 16.] #emph[hath said unto thee, do:] whereby they gave him to understand that they were ready to yield unto whatsoever he would have done.

=== §. 44. #emph[Of a wives willingness to] #footnote[Treat. 4. §. 18.] #emph[dwell where her husband will.]

To make this part of a wives obedience somewhat more clear, I will exemplify it by two or three particular instances, recorded and approved in Gods word.

The first is, that #emph[a wife ought to be willing to dwell where her husband will have her dwell.]

The wives of #emph[Abraham, Isaac,] and #emph[Jacob,] herein manifested their wive-like obedience: though their husbands brought them from their own country, and from their fathers house, yet they refused not to go with them, but dwelt in a strange country, and that in tents.

Note in particular what #emph[Jacob's] wives say to their husband in this case, #emph[Is there any portion or inheritance for us in our fathers] #footnote[#emph[Gen.] 31. 14.] #emph[house?] implying thereby, that seeing it was their husbands pleasure to be gone, they would not any longer tarry in their fathers house, to look for any more portion or inheritance there.

These examples do further show that if an husband have just occasion to remove from one country to another, and in those countries from place to place, his wife ought to yield to go with him, if he require it at her hands. Note what the Apostle saith, #emph[have we not power to lead about a wife?] That interrogation #footnote[1 #emph[Cor.] 9. 5.] implieth a strong asseveration. The husband then having power to lead about a wife from place to place, she ought to submit her self to that power. This clause #emph[(as well as other Apostles, and as the brethren of the Lord and Cephas)] showeth, that this was not only a power which might be used, but which was used by husbands, and yielded unto by wives.

#strong[#emph[Object.] The forenamed examples are extraordinary, and that upon extraordinary occasions.]

#emph[Answ.] Yet they may be patterns for ordinary occasions which are lawful and warrantable. Was it not an extraordinary fact of #emph[Eliah] to pray first that there might be no rain, and #footnote[#emph[Iam.] 5. 17.] then again that there might be rain? Yet is this propounded as a general pattern to move us to pray for things lawful.

Now in laying down this duty I added the clause and caveat of #emph[just occasion,] to meet both with such as upon discontent, or superstition, leave the land where the true Gospel is maintained, and preached, and go into idolatrous places: and also with such wandering giddy heads as only to satisfy their own humour, and to see fashions, as we speak, can never rest in a place, but are continually removing from country to country, and from place to place: I think (to use the words of the Apostle) #emph[a wife is not under bondage in such cases.] #footnote[1 #emph[Cor.] 7. 15.]

But if a man be sent of an ambassage by his Prince, or country: or if a Preacher or Professor be called into another country, as #emph[Bucer] and #emph[Peter Martyr] were into England in King #emph[Edwards] days (which to this day is usual in other countries) or if a man be adjudged unto long imprisonment, and upon these and other like occasions shall require his wife to be with him, she ought in duty to yield unto his demand.

Contrary is the mind and practise of many wives, who #footnote[Contrary, when a wife makes her husband dwell where she will.] being affected and addicted to one place more then another, as to the place where they were bred and brought up, where their greatest, best, and most friends dwell, and where they have good acquaintance, refuse to go and dwell where their husbands calling lieth, though he require, and desire them never so much. Thus many husbands are forced to their great damage for peace sake to yield unto their wives, and so either to relinquish their calling, or to have two houses; whence it followeth, that sometimes they must neglect their servants and calling, and sometimes be absent from their wives, if not from their children also. Some wives pretend that they cannot endure the smoke of the city, other that they cannot endure the air of the country: whereas indeed their own humour and conceit stuffs them more then either city smoke or country air. I cannot call such the #emph[daughters of Sarah] herein: #footnote[1 #emph[Pet.] 3. 5, 6.] they are not like those forenamed #emph[holy women that trusted in God, and were subject to their husbands,] but rather like to that light housewife of the Levite, who would not dwell in her husbands #footnote[#emph[Judg.] 19. 2.] house at #emph[mount Ephraim,] but at her fathers house in #emph[Beth-lehem Judah.] Such wives as I speak of, in matrimonial chastity may be more honest, but in wivelike subjection are little more dutiful. Let this be taken for a fault, and it will be the sooner amended.

=== §. 45. #emph[Of a wives] #footnote[Treat. 4. §. 29.] #emph[readiness to come to her husband when he requires it.]

Another particular instance of a wives readiness to yield unto her husbands commandment is, #emph[to come to her husband when her husband requireth it,] either by calling her, or sending for her. The forenamed #footnote[#emph[Gen.] 31. 4.] wives of #emph[Jacob] being sent for to their husband in the field where he was, made no excuse, but came presently. So far ought wives herein to subject their wills to their husbands, that though it may seem to them some disparagement to come, yet if their husbands will have it so they must yield, otherwise they seem even to #footnote[#emph[Esth.] 1. 17.] #emph[despise their husbands.]

Contrary is #emph[Vashty-]like stoutness, when wives think and #footnote[Contrary, stoutness in refusing to come.] say, it is a servants part to come when they are called or sent for, and they will never yield to be their husbands servants, to come at his command. By the same reason may all duties of subjection be rejected. But for this particular, let such stout #footnote[#emph[Esth.] 1. 16, #emph[etc.]] dames note the issue of #emph[Vashties] stubbornness. As many excuses might be alleged for her as I think for any: for First, she was #footnote[#emph[Hebraei docent Vasthiam natam fuisse ex Baltbasare rege Chaldaeorum. Feuard. in Esth.] 1. #emph[Alij, ex Cyro. Merl. in Esth.]] royally descended, being the daughter of a King. Secondly, she was then among the honourable women of the kingdom. Thirdly, the King was in drink when he sent for her. Fourthly, he sent for her to show her beauty before multitudes of men, which was not seemly. But all these were not sufficient to excuse her fault, and free her from blame. First, though she were of royal parentage, yet she was a wife, and her husband sent for her. Secondly, being among the noble women of the kingdom, she should the rather have showed her self a pattern of subjection in this kind. Thirdly, though he were in drink, yet remained he an husband: and the thing which he commanded was not such but that she might have done it without sin. Fourthly, if she thought the thing unseemly, she should first have used all the fair means she could to have been spared; but if by all she could not have prevailed, then (the thing being not simply unlawful and a sin) she should have yielded.

#strong[#emph[Object.] Her fault was not in that as a #emph[wife] she came not to her #emph[husband,] but in that as a #emph[subject] she came not to her #emph[Sovereign.]]

#emph[Answ.] Her fault was in both: and in the judgment passed against her, that former was most urged, namely that by her #footnote[#emph[Esth.] 1. 17.] example all women might learn to #emph[despise their husbands.]

#strong[2. #emph[Object.] Her fact is so censured but by heathen men, that had no understanding of Gods word.]

#emph[Answ.] 1. The holy Scripture by the several circumstances so distinctly noted intimateth that her rebellious fact was a notorious fault: and accordingly both #footnote[Pellican. Lauater. Gualt. Strigel. Cuper. Merlin. Feuard. Bellator. Rupert. Isiodor. Hisp. Raban. alijque Comment. in Esth.] judicious commenters, and also Preachers do tax her of sinful disobedience to her husband.

2. Though they were heathen, yet they showed what subjection is required of wives to their husbands by the very light of nature, whereby this sin is aggravated.

3. #emph[Abimelech] was but a heathen man, yet his sentence concerning a womans subjection in these words, #emph[he is to thee a] #footnote[#emph[Gen.] 20. 16.] #emph[covering of the eyes,] is taken to be judicious, and being approved by the holy Ghost, to be a good proof. As for that particular of #emph[Uashty,] why is it so largely recorded in the Scripture but for instruction, and admonition unto wives?

=== §. 46. #emph[Of a wives readiness to] #footnote[Treat. §. 29.] #emph[do what her husband requireth.]

A third particular instance of a wives readiness to yield unto her husbands commandment, is, #emph[to perform what business he requireth of her.] When of a sudden there came three men to #emph[Abram,] and he was desirous to entertain them, he bid his wife #emph[make ready quickly three measures of meal,] etc. And she #footnote[#emph[Gen.] 18. 6.] did it accordingly. #emph[Jeroboam] having a weighty occasion to send to #emph[Ahijah] the Prophet, thought it meet to send by his #footnote[1 #emph[King.] 14. 2, #emph[etc.]] wife, she accordingly (though a Queen) went: she did as her husband would have her.

Contrary is the humour of many wives who will not do #footnote[Contrary, stubbornness in refusing to do a thing upon command.] any thing upon command. If such a wives husband being desirous to entertain a friend on the sudden, shall use #emph[Abrams] phrase, #emph[make ready quickly,] etc. She will say, let him come and do it himself, if he will have it so quickly done, I will not be his drudge: or if, having a matter of moment and secrecy, he will his wife her self to do it, she will reply, I am none of your servants; cannot you put it to one of them, or do it your self? Yet will such wives be ready to command their husbands to do every toy, and if he do it not, they can reply, is this such a matter? And may not a wife speak to her husband? Were the point of obedience well learned, it would cast such wives into another mould.

These few particulars may serve for direction in many hundreds. I proceed to the other part of a wives active obedience, which respecteth the reproofs of her husband.

=== §. 47. #emph[Of a wives] #footnote[Treat. 4. §. 34, 35.] #emph[meek taking a reproof.]

The husband having authority over his wife, by virtue thereof he hath power, yea it is his duty as there is needful cause to rebuke her: By just consequence therefore it followeth, #footnote[A wives active obedience to her husbands reproof. The best trial of obedience.] that it is her duty to yield obedience thereunto. Which ought the rather to be done because the chiefest trial of sound obedience lieth herein. For nothing goeth so much against ones stomach as reproof: she that yields when she is rebuked, will much more when she is entreated. This point of obedience is manifested two ways.

1. By meekness in taking a reproof.

2. By endeavour to redress what is justly reproved. The very point of obedience especially consisteth in this latter: the former is as a good preparative thereunto, without which it will hardly be done, at least not well done.

Meekness in this case is one of the most principal fruits of #footnote[1\. She must meekly take reproof. 1 #emph[Pet.] 3. 4. #emph[Gen.] 30. 1.] that #emph[meek and quiet spirit] which #emph[S. Peter] commendeth unto wives. Howsoever #emph[Rachel] justly deserved blame for coming in a fuming chafe, and with an imperious command to her husband, yet in that she meekly took his sharpe reproof (for she replied not against it, but meekly gave a direction for the better accomplishment of her desire) her example is commendable: commendable I say, not in the matter of her direction, but in her patient bearing of reproof.

Much wisdom may be learned hereby: for when any #footnote[Wisdom learned.] meekly take a reproof, thereby they suppress their passion, and keep it from rising as a cloud before their understanding and darkning it, and so may they better judge of the matter reproved whether it be just or no: and whether it need redress or no: whereof they who are impatient of reproof, and fret and fume against it, cannot so well judge. The virgin #emph[Mary] made good use of Christs reproving her, and thereby #footnote[#emph[Joh.] 2. 4, 5.] learned and taught a good point of wisdom, namely so to refer our affairs to Christ as we expect his pleasure; and not prescribe time, means, manner, or any other like circumstances unto him.

#strong[#emph[Quest.] What if the husbands reproof be bitter? #footnote[#emph[Suadeo mulieribus vt viros etiam asperiores perserant. Chrys. hom.] 26. #emph[in] 1. #emph[Cor.] 11.]]

#emph[Answ.] He therein forgets his place, yet thereupon she must not forget her duty. If #emph[Jacob's] reproof be well noted, we shall find it very tart, for it is expressly said that #emph[his anger was kindled against her,] (Gen. 30. 2.) so as he spake in anger: the manner and form of his words being with an interrogation, and the #footnote[Excandescenti marito cede, & molli oratione iuva. Greg. Naz. ad Olymp.] matter also, #emph[am I in Gods stead,] etc. Declare #emph[tartness:] yet (as was declared before) she showed #emph[meeknese.]

#strong[#emph[Quest.] What if his reproof be unjust?]

2. #emph[Answ.] Yet may not #emph[meekness] be forgotten. In such a case a wife may make a just apology to clear her own innocency, and manifest her husbands error: but if he refuse to hear her, or will not believe her, then (as #emph[S. Peter] speaketh in another #footnote[1 #emph[Pet.] 2. 19, 20.] case) she must #emph[endure grief for conscience toward God.]

The two reasons which there he rendreth in that other case may not unfitly be applied to this.

1. In general this is #emph[thank-worthy,] it is a grace, a glory to her: a matter that deserueth praise and commendation.

2. In particular it is #emph[acceptable to God:] howsoever their husbands may deal roughly and untowardly with them, yet God will graciously respect them, if they shall patiently in obedience to his ordinance bear their husbands unjust reproofs.

3. I may add this reason also, that thus they shall show themselves good Christians indeed, in that #emph[they are not overcome] #footnote[#emph[Rom.] 12. 21.] #emph[of evil.]

Contrary is their mind who by no means will brooke a rebuke at their husbands hands: it skills not whether it be just or unjust: if their husbands reprove them, they shall be sure to have the reproof rebounded back again upon their faces, and that with greater violence then ever it came from them. There be some that seem to be very good wives till they be tried by the touch-stone of reproof: but then though the reproof be for matter most just, for manner most mild, and that in private betwixt their husbands and themselves, yet they grow so impatient, or rather mad, as they forbear not to give their husbands the most scornful speeches that they can invent, using withal bitter imprecations and execrations, and threaten to drown or hang themselves if they be crossed of their wills. Yea further, if wise husbands shall forbear them in their passion, and after it is allaied tell them how unbeseeming their places they carried themselves, they will seek to justify themselves, and lay all the blame on their husbands for crossing them in their will: or if they cannot but see their fault, yet they will only say, it is my infirmity: but yet ever continue in that infirmity: and though they make show of fearing God, yet labour not to purge this corrupt humour out of their hearts. Hence is it for the most part that contentions arise betwixt man and wife. If wives would learn in this point to be subject, many jars, which from time to time arise betwixt them, would be allaied, if not prevented. #emph[Michal] #footnote[2 #emph[Sam.] 6. 20, #emph[etc. Job] 2. 10.] the wife of #emph[David,] and #emph[Jobs] wife (though they gave just occasion to be most sharply reproved, yet) shall rise up in judgment against these wives, because they were silent after they were reproved, and replied not. #emph[Solomon] oft titles such as cannot bear rebuke #emph[scorners:] so as hereby wives show that #footnote[#emph[Prov] 9. 7, 8.] they are very scornful.

=== §. 48. #emph[Of a wives] #footnote[Treat. 4. §. 35.] #emph[readiness to redress what her husband justly reproveth in her.]

A further degree of obedience in bearing reproof is, that #footnote[2 She must redress what is justly reproved.] #emph[a wife readily redress what is justly reproved by her husband:] I say #emph[justly,] because where no fault is, there needs no amendment: patience may be needful (as was before showed) but no repentance of that which is not amiss. But where any thing is amiss, there must be a redress. #emph[Rachel] did amiss in #footnote[#emph[Gen.] 31. 19.] bringing Idols into her husbands house: her husband in #footnote[#emph[&] 35. 2, 4.] bidding her among others to #emph[put away their strange gods,] reproved them all. Whereupon she with all the rest #emph[gave to him all their strange gods.] This was a good redress.

A reproof may be justly given either for a good duty omitted; or for an evil thing committed: and accordingly must the redress or amendment be. A duty formerly omitted must after the reproof be more carefully observed and performed, if it be a continual duty, and may be again performed: otherwise the redress is a testification of true sorrow for that fault. When an evil is committed, if any means can be used to make up the hurt, and redress the mischief that followed thereupon, it must be done: if not, sorrow as before, must be testified, and care taken that the same, or the like be not committed again.

As a good conscience requireth as much of all Christians by whomsoever they be reproved, so the respect which a wife oweth to an husband doth after an especial manner require it. Otherwise her fault is doubled, 1. By continuance in her sin;

2. By disobedience to her husband.

Contrary is their spirit who for reproof wax the worse: #footnote[Contrary, to be worse for reproving. #emph[Prov.] 9. 8.] being like those #emph[scorners] (of whom #emph[Solomon] speaketh) that #emph[hate those that reprove them.] It is the speech of some wives, that if their husbands would let them alone they would do the better: but upon rebuke they will never amend: the more their husbands find fault, the more will they go on, in doing what they do. What other judgment can be given of such, then that which the wise man giveth, #emph[there is more hope] #footnote[#emph[Prov.] 26. 12.] #emph[of a fool then of them.]

=== §. 49. #emph[Of a wives] #footnote[Treat. 4. §. 50] #emph[contentment with her husbands present estate.] Of submission hitherto.

#emph[Contentment] is also a part of #emph[obedience:] it hath respect to a mans outward estate and ability, in and with which a wife must rest satisfied and contented, whether it be high or low, great or mean, wealthy or needy, above, equal, or under that estate wherein she was before marriage: yea though a man have been sometimes great in estate, yet, if he decay therein, and be brought to a mean estate, she ought to rest content. Thus much #emph[Job] implieth in his reply to his wife, saying, #emph[shall we receive] #footnote[#emph[Job] 2. 10. expounded.] #emph[good at the hand of God, and not receive evil?] The evil he speaketh of was the loss of his goods, servants, and children, together with other miseries that Satan through Gods permission inflicted upon him: the #emph[receiving of evil] which he speaketh of was a resting content with it, and a patient bearing of it. Evil may be laid on any, and so they forced to bear it: but they only receive it, who are content with it. Now in that he useth the plural number (WE) and speaking to his wife saith #emph[(shall not we receive evil)] he showeth that his wife ought as well as he to have rest contented in that poor and miserable estate: For

1. Man and wife being #emph[one flesh,] by virtue of their matrimonial union, both his advancement, and also his abasement is #emph[hers:] as she riseth with him, so she falleth with him. Wherefore as she is willing to be advanced with him, so she must be content to be abased with him.

2. If at the time of marriage her husband was of meaner estate then she, she voluntarily put her self into that mean estate: for a wife taketh her husband (as he her) #emph[for better for worse, for richer for poorer.] And shall she not be content with her own act? If after marriage his estate decay, and wax meaner then it was, she is to be persuaded that by God it was so ordered, and that God aimed at #emph[her] humiliation as well as #emph[his:] and thereupon she ought in her dutiful submission to Gods over-ruling providence to be patient and content: this #emph[Job] implieth under this phrase, #emph[shall we not receive evil at the hand of God?] and under this, #emph[The Lord taketh away.]

3. A wives contentment is a great ease to her husband lying under a cross: and it maketh the burden seem much lighter then otherwise it would, if at least he be a kind husband, and affected with his wives passion, as he ought to be. For a loving husband in every distress is more perplexed for his wife, then for himself.

=== §. 50. #emph[Of wives discontent at their husbands estate.]

Contrary is the impatiency, and discontent of wives at #footnote[Discontent manifested.] the meanness, and (as they think) baseness of their husbands estate: which is many ways manifested.

1. Some when they are married finding their husbands estate #footnote[1\. By repenting their marriage.] weaker then they imagined, repent their marriage, and stick not to tell their husbands, that if they had before known them to be no better men then they find them to be, they should have been no husbands for them. Wherein first they bewray their foolish indiscretion by saying, when it is too late, #emph[if I had] #footnote[#emph[Non est sapientis dicere non putâram. Cic. Offic. lib.] 1.] #emph[thought this;] and withal they manifest their own rashness and unaduisedness, in that they gave their hands and plighted their troth to those whom they knew not. If they say, they were deceived by their friends whom they put in trust, I answer that marriage is too weighty a matter to be wholly referred over to the trust of friends: every one that yieldeth to be married, ought well to know the party unto whom in this case they yield: and above all they ought to seek direction, help, and blessing from God. If notwithstanding all the means which possibly they could use, they be deceived, they are to look unto God, and to behold his providence therein: and duly to weigh whether the Lord have crossed their desire for their humiliation, or for trial of their patience, wisdom and other like graces, or else to wean them from some vain and worldly delights, whereunto they were too much addicted.

2. Others observing their husbands estate to be decaied #footnote[2\. By impatient carriage.] and wasted, never search after the occasion, but lay all the blame upon their husbands, and with their discontented looks, passionate words, and impatient carriage, so vex their hearts, as they make the cross much more heavy then otherwise it could be. Though the estate should be overthrown by the unthriftiness of an husband, yet ought a wife to look unto Gods providence therein, as was noted before.

3. Others scorning to stoop, and to come down to their #footnote[3\. By refusing to stoop.] husbands present condition, through their pride and vaineglory are a great means to make his estate much the worse: for they, so long as by any means they can get it, will not abate any thing of their brave apparel, dainty cheer, rich furniture, and other like things, which are causes of great expence to their husbands: hereby also it cometh oft to pass that husbands are thought to be wealthier then indeed they are, and so greater taxations and charges then they can bear are laid upon them for King, Country, Church, Poor, and the like.

4. Others, through discontent lie long lazing in their beds, #footnote[4\. By refusing to help.] or idly sit still when they are up, and will not take any whit the more pains to raise up and increase their husbands estate: whereby God is provoked more and more to weaken their estates, that so he may the more punish such pride and laziness in wives.
