== Chapter II

#block(inset: (x: 1em))[What it is to “enter into temptation”—Not barely being tempted—Not to be conquered by it—To fall into it—The force of that expression—Things required unto entering into temptation—Satan or lust more than ordinarily importunate—The soul’s entanglement—Seasons of such entanglements discovered—Of the “hour of temptation,” Rev. iii. 10, what it is—How any temptation comes to its hour—How it may be known when it is so come—The means of prevention prescribed by our Saviour—Of watching, and what is intended thereby—Of prayer.]

II. Having showed what temptation is, I come, secondly, to manifest what it is to #emph[enter] into temptation.

1\. This is not merely to #emph[be tempted]. It is impossible that we should be so freed from temptation as not to be at all tempted. Whilst Satan continues in his power and malice, whilst the world and lust are in being, we shall be tempted. “Christ,” says one, “was made like unto us, that he might be tempted; and we are tempted that we may be made like unto Christ.” Temptation in general is comprehensive of our whole warfare; as our Saviour calls the time of his ministry the time of his “temptations,” Luke xxii. 28. We have no promise that we shall not be tempted at all; nor are to pray for an absolute freedom from temptations, because we have no such promise of being heard therein. The direction we have for our prayers is, “Lead us not into temptation,” Matt. vi. 13; it is “entering into temptation” that we are to pray against. We may be tempted, yet not enter into temptation. So that,—

2\. Something more is intended by this expression than the #emph[ordinary work] of Satan and our own lusts, which will be sure to tempt us every day. There is something signal in this entering into temptation, that is not the saints’ every day’s work. It is something that befalls them peculiarly in reference to seduction unto sin, on one account or other, by the way of allurement or affrightment.

3\. It is not #emph[to be conquered] by a temptation, to fall down under it, to commit the sin or evil that we are tempted to, or to omit the duties that are opposed. A man may “enter into temptation,” and yet not fall under temptation. God can make a way for a man to escape; when he is in, he can break the snare, tread down Satan, and make the soul more than a conqueror, though it have entered into temptation. Christ #emph[entered] into it, but was not in the least #emph[foiled] by it. But,—

4\. It is, as the apostle expresseth it, 1 Tim. vi. 9, ἐμπίπτειν,“to fall into temptation,” as a man falls into a pit or deep place where are gins or snares, wherewith he is entangled; the man is not presently killed and destroyed, but he is entangled and detained,—he knows not how to get free or be at liberty. So it is expressed again to the same purpose, 1 Cor. x. 13, “No temptation hath taken you;” that is, to be taken by a temptation and to be tangled with it, held in its cords, not finding at present a way to escape. Thence saith Peter, 2 Epist. ii. 9, “The Lord knoweth how to deliver the godly out of temptations.” They are entangled with them; God knows how to deliver them out of them. When we suffer a temptation to enter into us, then we “enter into temptation.” Whilst it knocks at the door we are at liberty; but when any temptation comes in and parleys with the heart, reasons with the mind, entices and allures the affections, be it a long or a short time, do it thus insensibly and imperceptibly, or do the soul take notice of it, we “enter into temptation.”

So, then, unto our entering into temptation is required,—

(1.) That by some #emph[advantage], or on some occasion, Satan be more earnest than ordinary in his solicitations to sin, by affrightments or allurements, by persecutions or seductions, by himself or others; or that some lust or corruption, by his instigation and advantages of outward objects, provoking, as in prosperity, or terrifying, as in trouble, do tumultuate more than ordinary within us. There is a special acting of the author and principles of temptation required thereunto.

(2.) That the heart be so far entangled with it as to be put to #emph[dispute] and argue in its own defence, and yet not be wholly able to eject or cast out the poison and leaven that hath been injected; but is surprised, if it be never so little off its watch, into an entanglement not easy to be avoided: so that the soul may cry, and pray, and cry again, and yet not be delivered; as Paul “besought the Lord” thrice for the departure of his temptation, and prevailed not. The entanglement continues. And this usually falls out in one of these two seasons:—

\[1.\] When Satan, by the permission of God, for ends best known to himself, hath got some #emph[peculiar] advantage against the soul; as in the case of Peter,—he sought to winnow him, and prevailed.

\[2.\] When a man’s lusts and corruptions meet with peculiarly provoking #emph[objects] and occasions, through the condition of life that a man is in, with the circumstances of it; as it was with David: of both which afterward.

In this state of things, a man is entered into temptation; and this is called the “hour of temptation,” Rev. iii. 10,—the season wherein it grows to a head: the discovery whereof will give farther light into the present inquiry, about what it is to “enter into temptation;” for when the hour of temptation is come upon us, we are entered into it. Every great and pressing temptation hath its hour, a season wherein it grows to a head, wherein it is most vigorous, active, operative, and prevalent. It may be long in rising, it may be long urging, more or less; but it hath a season wherein, from the conjunction of other occurences, such as those mentioned, outward or inward, it hath a dangerous hour; and then, for the most part, men enter into it. Hence that very temptation, which at one time hath little or no power on a man,—he can despise it, scorn the motions of it, easily resist it,—at another, bears him away quite before it. It hath, from other circumstances and occurrences, got new strength and efficacy, or the man is enervated and weakened; the hour is come, he is entered into it, and it prevails. David probably had temptations before, in his younger days, to adultery or murder, as he had in the case of Nabal; but the hour of temptation was not come, it had not got its advantages about it, and so he escaped until afterward. Let men look for it that are exposed unto temptations, as who is not? They will have a season wherein their solicitations will be more urgent, their reasonings more plausible, pretences more glorious, hopes of recovery more appearing, opportunities more broad and open, the doors of evil made more beautiful than ever they have been. Blessed is he who is prepared for such a season; without which there is no escaping. This, as I said, is the first thing required to entering into temptation; if we stay here, we are safe.

Before I descend to other particulars, having now entered hereon, I shall show in general,—1#emph[st]. How or by what means commonly any temptation attains its #emph[hour]\; 2#emph[dly]. How we may know when any temptation is come to its high #emph[noon], and is in its hour.

1#emph[st]. It doth the first by several ways:—

(1#emph[st].) By long #emph[solicitations], causing the mind frequently to converse with the evil solicited unto, it begets extenuating thoughts of it. If it makes this process, it is coming towards its hour. It may be when first it began to press upon the soul, the soul was amazed with the ugly appearance of what it aimed at, and cried, “Am I a dog?” If this indignation be not daily heightened, but the soul, by conversing with the evil, begins to grow, as it were, familiar with it, not to be startled as formerly, but rather inclines to cry, “Is it not a little one?” then the temptation is coming towards its high noon; lust hath then enticed and entangled, and is ready to “conceive,” James i. 15: of which more at large afterward, in our inquiry how we may know whether we are entered into temptation or no. Our present inquest is after the hour and power of temptation itself.

(2#emph[dly].) When it hath prevailed on #emph[others], and the soul is not #emph[filled with dislike] and abhorrency of them and their ways, nor with pity and prayer for their deliverance. This proves an advantage unto it, and raises it towards its height. When that temptation sets upon any one which, at the same time, hath possessed and prevailed with many, it hath so great and so many advantages thereby, that it is surely growing towards its hour. Its prevailing with others is a means to give it its hour against us. The falling off of Hymeneus and Philetus is said to “overthrow the faith of some,” 2 Tim. ii. 17–18.

(3#emph[dly].) By #emph[complicating] itself with many considerations that, perhaps, are not absolutely evil. So did the temptation of the Galatians to fall from the purity of the gospel,—freedom from persecution, union and consent with the Jews. Things in themselves good were pleaded in it, and gave life to the temptation itself. But I shall not now insist on the several advantages that any temptation hath to heighten and greaten itself, to make itself prevalent and effectual with the contribution that it receives to this purpose from various circumstances, opportunities, specious pleas and pretences, necessities for the doing that which cannot be done without answering the temptation, and the like; because I must speak unto some of them afterward.

2#emph[dly]. For the second, it may be known,—

(1#emph[st].) By its restless #emph[urgency] and arguing. When a temptation is in its hour it is restless; it is the time of battle, and it gives the soul no rest. Satan sees his advantage, considers his conjunction of forces, and knows that he must now prevail, or be hopeless for ever. Here are opportunities, here are advantages, here are specious pleas and pretences; some ground is already got by former arguings; here are extenuations of the evil, hopes of pardon by after endeavours, all in a readiness: if he can do nothing now, he must sit down lost in his undertakings. So when he had got all things in a readiness against Christ, he made it the “hour of darkness.” When a temptation discovers “mille nocendi artes,” presses within doors by imaginations and reasonings, without by solicitations, advantages, and opportunities, let the soul know that the hour of it is come, and the glory of God, with its own welfare, depends on its behaviour in this trial; as we shall see in the particular cases following.

(2#emph[dly].) When it makes a conjunction of #emph[affrightments and allurements], these two comprise the whole forces of temptation. When both are brought together, temptation is in its hour. They were both in David’s case as to the murder of Uriah. There was the fear of his revenge on his wife, and possibly on himself, and fear of the publication of his sin at least; and there was the allurement of his present enjoyment of her whom he lusted after. Men sometimes are carried into sin by love to it, and are continued in it by fear of what will ensue upon it. But in any case, where these two meet, something allures us, something affrights us, and the reasonings that run between them are ready to entangle us,—then is the hour of temptation.

This, then, it is to “enter into temptation,” this is the “hour” of it; of which more in the process of our discourse.

III. There is the means of prevention prescribed by our Saviour; they are two:—1. “Watch;” 2. “Pray.”

1\. The first is a general expression by no means to be limited to its native signification of waking from sleep; to watch is as much as to be on our guard, to take heed, to consider all ways and means as to be on our guard, to take heed, to consider all ways and means whereby an enemy may approach to us: so the apostle, 1 Cor. xvi. 13. This it is to “watch” in this business, to “stand fast in the faith,” as good soldiers, to “quit ourselves like men.” It is as much as προσέχειν, to “take heed,” or look to ourselves, as the same thing is by our Saviour often expressed; so Rev. iii. 2. A universal carefulness and diligence, exercising itself in and by all ways and means prescribed by God, over our hearts and ways, the baits and methods of Satan, the occasions and advantages of sin in the world, that we be not entangled, is that which in this word is pressed on us.

2\. For the second direction, of prayer, I need not speak to it. The duty and its concernments are known to all. I shall only add, that these two comprise the whole endeavour of faith for the soul’s preservation from temptation.
