== Chapter III

#block(inset: (x: 1em))[The doctrine—Grounds of it; our Saviour’s direction in this case—His promise of preservation—Issues of men entering into temptation—1. Of ungrounded professors—2. Of the choicest saints, Adam, Abraham, David—Self-consideration as to our own weakness—The power of a man’s heart to withstand temptation considered—The considerations that it useth for that purpose—The power of temptation; it darkens the mind—The several ways whereby it doth so—1. By fixing the imaginations—2. By entangling the affections—3. Temptations give fuel to lust—The end of temptation considered, with the issue of former temptations—Some objections answered.]

Having thus opened the words in the foregoing chapters so far as is necessary to discover the foundation of the truth to be insisted on and improved, I shall lay it down in the ensuing observation:—

#emph[It is the great duty of all believers to use all diligence in the ways of Christ’s appointment, that they fall not into temptation.]

I know God is “able to deliver the godly out of temptations;” I know he is “faithful not to suffer us to be tempted above what we are able, but will make a way for our escape:” yet I dare say I shall convince all those who will attend unto what is delivered and written, that it is our great duty and concernment to use all diligence, watchfulness, and care, that we enter not into temptation; and I shall evince it by the ensuing considerations:—

1\. In that #emph[compendious] instruction given us by our Saviour concerning what we ought to pray for, this of not entering into temptation is expressly one head. Our Saviour knew of what concernment it was to us not to “enter into temptation,” when he gave us this as one special subject of our daily dealing with God, Matt. vi. 13. And the order of the words shows us of what importance it is: “Lead us not into temptation, but deliver us from evil.” If we are led into temptation, evil will befall us, more or less. How God may be said to tempt us, or to “lead us into temptation,” I showed before. In this direction, it is not so much the not #emph[giving us up to it], as the powerful #emph[keeping us from it] that is intended. The last words are, as it were, exegetical, or expository of the former: “Lead us not into temptation, but deliver us from evil;”—“So deal with us that we may be powerfully delivered from that evil which attends our entering into temptation.” Our blessed Saviour knows full well our state and condition; he knows the power of temptations, having had experience of it, Heb. ii. 18; he knows our vain confidence, and the reserves we have concerning our ability to deal with temptations, as he found it in Peter; but he knows our weakness and folly, and how soon we are cast to the ground, and therefore doth he lay in this provision for instruction at the entrance of his ministry, to make us heedful, if possible, in that which is of so great concernment to us. If, then, we will repose any confidence in the wisdom, love, and care of Jesus Christ towards us, we must grant the truth pleaded for.

2\. Christ promiseth this freedom and deliverance as a great #emph[reward] of most acceptable obedience, Rev. iii. 10. This is the great promise made to the church of Philadelphia, wherein Christ found nothing that he would blame, “Thou shalt be kept from the hour of temptation.” Not, “Thou shalt be preserved #emph[in] it;” but he goes higher, “Thou shalt be kept #emph[from] it.” “There is,” saith our Saviour, “an hour of temptation coming; a season that will make havoc in the world: multitudes shall then fall from the faith, deny and blaspheme me. Oh, how few will be able to stand and hold out! Some will be utterly destroyed, and perish for ever. Some will get wounds to their souls that shall never be well healed whilst they live in this world, and have their bones broken, so as to go halting all their days. But,” saith he, “ ‘because thou hast kept the word of my patience,’ I will be tender towards thee, and ‘keep thee from this hour of temptation.’ ” Certainly that which Christ thus promises to his beloved church, as a reward of her service, love, and obedience, is no light thing. Whatever Christ promiseth to his spouse is a fruit of unspeakable love; that is so in an especial manner which is promised as a reward of special obedience.

3\. Let us to this purpose consider the general issues of men’s entering into temptation, and that of bad and good men, of ungrounded professors, and of the choicest saints.

(1.) For the first I shall offer but one or two texts of Scripture. Luke viii. 13, “They on the rock are they, which, when they hear, receive the word with joy, and have no root, but for a while believe.” Well! how long do they believe? They are affected with the preaching of the word, and believe thereon, make profession, bring forth some fruits; but until when do they abide? Says he, “In the time of temptation they fall away.” When once they enter into temptation they are gone for ever. Temptation withers all their profession, and slays their souls. We see this accomplished every day. Men who have attended on the preaching of the gospel, been affected and delighted with it, that have made profession of it, and have been looked on, it may be, as believers, and thus have continued for some years; no sooner doth temptation befall them that hath vigour and permanency in it, but they are turned out of the way, and are gone for ever. They fall to hate the word they have delighted in, despise the professors of it, and are hardened by sin. So Matt. vii. 26, “He that heareth these sayings of mine, and doeth them not, is like unto a foolish man, which built his house upon the sand.” But what doth this house of profession do? It shelters him, keeps him warm, and stands for a while. But saith he, verse 27, “When the rain descends, when temptation comes, it falls utterly, and its fall is great.” Judas follows our Saviour three years, and all goes well with him: he no sooner enters into temptation, Satan hath got him and winnowed him, but he is gone. Demas will preach the gospel until the love of the world befall him, and he is utterly turned aside. It were endless to give instances of this. Entrance into temptation is, with this sort of men, an entrance into apostasy, more or less, in part or in whole; it faileth not.

(2.) For the #emph[saints] of God themselves, let us see, by some instances, what issue they have had of their entering into temptation. I shall name a few:—

Adam was the “son of God,” Luke iii. 38, created in the image of God, full of that integrity, righteousness, and holiness, which might be and was an eminent resemblance of the holiness of God. He had a far greater inherent stock of ability than we, and had nothing in him to entice or seduce him; yet this Adam no sooner enters into temptation but he is gone, lost, and ruined, he and all his posterity with him. What can we expect in the like condition, that have not only in our temptations, as he had, a #emph[cunning devil] to deal withal, but a #emph[cursed world] and a #emph[corrupt heart] also?

Abraham was the father of the faithful, whose faith is proposed as a pattern to all them that shall believe; yet he, entering twice into the same temptation, namely, that of fear about his wife, was twice overpowered by it, to the dishonour of God, and no doubt the disquietment of his own soul, Gen. xii. 12, 13, xx. 2.

David is called a “man after God’s own heart” by God himself; yet what a dreadful thing is the story of his entering into temptation! He is no sooner entangled, but he is plunged into adultery; thence seeking deliverance by his own invention, like a poor creature in a toil, he is entangled more and more, until he lies as one dead, under the power of sin and folly.

I might mention Noah, Lot, Hezekiah, Peter, and the rest, whose temptations and falls therein are on record for our instruction. Certainly he that hath any heart in these things cannot but say, as the inhabitants of Samaria upon the letter of Jehu, “ ‘Behold, two kings stood not before him, how shall we stand?’ O Lord, if such mighty pillars have been cast to the ground, such cedars blown down, how shall I stand before temptations? Oh, keep me that I enter not in!” “Vestigia terrent.” Behold the footsteps of them that have gone in. Whom do you see retiring without a wound? a blemish at least? On this account would the apostle have us to exercise tenderness towards them that are fallen into sin: Gal. vi. 1, “Considering thyself, lest thou also be tempted.” He doth not say, “Lest thou also sin, or fall, or be overtaken with a fault;” but, “Lest thou also be tempted.” “Thou seest the power of temptation in others, and knowest not how soon thou mayst be tempted, nor what will be the state and condition of thy soul thereupon.” Assuredly, he that hath seen so many better, stronger men than himself fail, and cast down in the trial, will think it incumbent on him to remember the battle, and, if it be possible, to come there no more. Is it not a madness for a man that can scarce crawl up and down, he is so weak (which is the case of most of us), if he avoid not what he hath seen giants foiled in the undertaking of? Thou art yet whole and sound; take heed of temptation, lest it be with thee as it was with Abraham, David, Lot, Peter, Hezekiah, the Galatians, who fell in the time of trial.

In nothing doth the folly of the hearts of men show itself more openly, in the days wherein we live, than in this cursed boldness, after so many warnings from God, and so many sad experiences every day under their eyes, of running into and putting themselves upon temptations. Any society, any company, any conditions of outward advantages, without once weighing what their strength, or what the concernment of their poor souls is, they are ready for. Though they go over the dead and the slain that in those ways and paths but even now fell down before them, yet they will go on without regard or trembling. At this door are gone out hundreds, thousands of professors, within a few years. But,—

4\. Let us #emph[consider ourselves],—what our weakness is; and what temptation is,—its power and efficacy, with what it leads unto:—

(1.) For ourselves, we are #emph[weakness] itself. We have no strength, no power to withstand. Confidence of any strength in us is one great part of our weakness; it was so in Peter. He that says he can do any thing, can do nothing as he should. And, which is worse, it is the worst kind of weakness that is in us,—a weakness from treachery,—a weakness arising from that party which every temptation hath in us. If a castle or fort be never so strong and well fortified, yet if there be a treacherous party within, that is ready to betray it on every opportunity, there is no preserving it from the enemy. There are traitors in our hearts, ready to take part, to close, and side with every temptation, and to give up all to them; yea, to solicit and bribe temptations to do the work, as traitors incite an enemy. Do not flatter yourselves that you shall hold out; there are secret lusts that lie lurking in your hearts, which perhaps now stir not, which, as soon as any temptation befalls you, will rise, tumultuate, cry, disquiet, seduce, and never give over until they are either killed or satisfied. He that promises himself that the frame of his heart will be the same under a temptation as it is before will be wofully mistaken. “Am I a dog, that I should do this thing?” says Hazael. Yea, thou wilt be such a dog if ever thou be king of Syria; temptation from thy interest will unman thee. He that now abhors the thoughts of such and such a thing, if he once enters into temptation will find his heart inflamed towards it, and all contrary reasonings overborne and silenced. He will deride his former fears, cast out his scruples, and contemn the consideration that he lived upon. Little did Peter think he should deny and forswear his Master so soon as ever he was questioned whether he knew him or no. It was no better when the hour of temptation came; all resolutions were forgotten, all love to Christ buried; the present temptation closing with his carnal fear carried all before it.

To handle this a little more distinctly, I shall consider the means of safety from the power of temptation, if we enter therein, that may be expected from ourselves; and that in general as to the spring and rise of them, and in particular as to the ways of exerting that strength we have, or seem to have:—

\[1.\] In general, all we can look for is from our #emph[hearts]. What a man’s heart is, that is he; but now what is the heart of a man in such a season?

1#emph[st]. Suppose a man is not a #emph[believer], but only a #emph[professor] of the gospel, what can the heart of such a one do? Prov. x. 20, “The heart of the wicked is little worth;” and surely that which is little worth in any thing is not much worth in this. A wicked man may in outward things be of great use; but come to his heart, that is false and a thing of nought. Now, withstanding of temptation is heartwork; and when it comes like a flood, can such a rotten trifle as a wicked man’s heart stand before it? But of these before. Entering into temptation and apostasy is the same with them.

2#emph[dly]. Let it be whose heart it will, Prov. xxviii. 26, “He that trusteth in his own heart is a fool;” he that doth so, be he what he will, in that he is foolish. Peter did so in his temptation; he trusted in his own heart: “Though all men forsake thee, I will not.” It was his folly; but why was it his folly? He shall not be delivered; it will not preserve him in snares; it will not deliver him in temptations. The heart of a man will promise him very fair before a temptation comes. “Am I a dog,” says Hazael, “that I should do this thing?” “Though all men should deny thee,” \[says Peter,\] “I will not. Shall I do this evil? It cannot be.” All the arguments that are suited to give check to the heart in such a condition are mustered up. Did not Peter, think you, do so? “What! deny my Master, the Son of God, my Redeemer, who loves me? Can such ingratitude, unbelief, rebellion, befall me? I will not do it.” Shall, then, a man rest in it that his heart will be steadfast? Let the wise man answer: “He that trusteth in his own heart is a fool.” “The heart is deceitful,” Jer. xvii. 9. We would not willingly trust any thing wherein there is any deceit or guile; here is that which is “deceitful above all things.” It hath a thousand shifts and treacheries that it will deal withal; when it comes to the trial, every temptation will steal it away, Hos. iv. 11. Generally men’s hearts deceive them no oftener than they do trust in them, and then they never fail so to do.

\[2.\] Consider the particular ways and means that such a heart hath or can use to safeguard itself in the hour of temptation, and their insufficiency to that purpose will quickly appear. I shall instance in some few only:—

1#emph[st]. Love of #emph[honour] in the world. Reputation and esteem in the church, obtained by former profession and walking, is one of the heart’s own weapons to defend itself in the hour of temptation. “Shall such a one as I fly? I who have had such a reputation in the church of God, shall I now lose it by giving way to this lust, to this temptation? by closing with this or that public evil?” This consideration hath such an influence on the spirits of some, that they think it will be a shield and buckler against any assaults that may befall them. They will die a thousand times before they will forfeit that repute they have in the church of God! But, alas! this is but a withe, or a new cord, to bind a giant temptation withal. What think you of the “third part of the stars of heaven?” Rev. xii. 4. Had they not shone in the firmament of the church? Were they not sensible, more than enough, of their own honour, height, usefulness, and reputation? But when the dragon comes with his temptations, he casts them down to the earth. Yea, great temptations will make men, who have not a better defence, insensibly fortify themselves against that dishonour and disreputation that their ways are attended withal. “Populus sibilet, at mihi plaudo.” Do we not know instances yet living of some who have ventured on compliances with wicked men after the glory of a long and useful profession, and within a while, finding themselves cast down thereby from their reputation with the saints, have hardened themselves against it and ended in apostasy? as John xv. 6. This kept not Judas; it kept not Hymeneus nor Philetus; it kept not the stars of heaven; nor will it keep thee.

2#emph[dly]. There is, on the other side, the consideration of #emph[shame], reproach, loss, and the like. This also men may put their trust in as a defence against temptations, and do not fear but to be safeguarded and preserved by it. They would not for the world bring that shame and reproach upon themselves that such and such miscarriages are attended withal! Now, besides that this consideration extends itself only to #emph[open sins], such as the world takes notice of and abhors, and so is of no use at all in such cases as wherein pretences and colours may be invented and used, nor in public temptations to loose and careless walking, like those of our days, nor in cases that may be disputable in themselves, though expressly sinful to the consciences of persons under temptations, nor in heart sins,—in all which and most other cases of temptation there are innumerable reliefs ready to be tendered unto the heart against this consideration; besides all this, I say, we see by experience how easily this cord is broken when once the heart begins to be entangled. Each corner of the land is full of examples to this purpose.

3#emph[dly]. They have yet that which outweighs these lesser considerations,—namely, that they will not wound their own #emph[consciences], and disturb their peace, and bring themselves in danger of hell fire. This, surely, if any thing, will preserve men in the hour of temptation. They will not lavish away their peace, nor venture their souls by running on God and the thick bosses of his buckler! What can be of more efficacy and prevalency? I confess this is of great importance; and oh that it were more pondered than it is! that we laid more weight upon the preservation of our peace with God than we do! yet I say that even this consideration in him who is otherwhere off from his watch, and doth not make it his work to follow the other rules insisted on, it will not preserve him; for,—

(1#emph[st].) The peace of such a one may be #emph[false peace] or security, made up of presumption and false hopes; yea, though he be a believer, it may be so. Such was David’s peace after his sin, before Nathan came to him; such was Laodicea’s peace when ready to perish; and Sardis her peace when dying. What should secure a soul that it is otherwise, seeing, it is supposed, that it doth not universally labour to keep the word of Christ’s patience, and to be watchful in all things? Think you that the peace of many in these days will be found to be true peace at last? Nothing less. They go alive down to hell, and death will have dominion over them in the morning. Now, if a man’s peace be such, do you think that can preserve him which cannot preserve itself? It will give way at the first vigorous assault of a temptation in its height and hour. Like a broken reed, it will run into the hand of him that leaneth on it. But,—

(2#emph[dly].) Suppose the #emph[peace] cared for, and proposed to safeguard the soul, be true and good, yet when all is laid up in this one bottom, when the hour of temptation comes, so many reliefs will be tendered against this consideration as will make it useless. “This evil is #emph[small]\; it is #emph[questionable]\; it falls not openly and downright upon #emph[conscience]. I do but fear #emph[consequences]\; it may be I may be keep my peace notwithstanding. Others of the people of God have fallen, and yet kept or recovered their peace. If it be lost for a season, it may be obtained again. I will not solicit its station any more; or though peace be lost, safety may remain.” And a thousand such pleas there are, which are all planted as batteries against this fort, so that it cannot long hold out.

(3#emph[dly].) The fixing on this particular only is to make good one #emph[passage] or entrance, whilst the enemy assaults us round about. It is true, a little armour would serve to defend a man if he might choose there his enemy should strike him; but we are commanded to take the “whole armour of God” if we intend to resist and stand, Eph. vi. This we speak of is but one piece; and when our eye is only to that, temptation may enter and prevail twenty other ways. For instance, a man may be tempted to worldliness, unjust gain, revenge, vain-glory, or the like. If he fortify himself alone with this consideration, he will not do this thing, and wound his conscience and lose his peace; fixing his eye on this particular, and counting himself safe whilst he is not overcome on that hand, it may be neglect of private communion with God, sensuality, and the like, do creep in, and he is not one jot in a better condition than if he had fallen under the power of that part of the temptation which was most visibly pressing on him. Experience gives to see that this doth and will #emph[fail] also. There is no saint of God but puts a valuation on the peace he hath; yet how many of them fail in the day of temptation!

(4#emph[thly].) But yet they have another consideration also, and that is, the vileness of sinning against God. How shall they do this thing, and sin against God, the God of their mercies, of their salvation? How shall they wound Jesus Christ, who died for them? This surely cannot but preserve them. I answer,—

First, We see every day this consideration failing also. There is no child of God that is overcome of temptation but overcomes this consideration. It is not, then, a sure and infallible defensative.

Secondly, This consideration is twofold: either it expresses the thoughts of the soul with particular reference to the temptation contended withal and then it will not preserve it; or it expresses the universal, habitual frame of heart that is in us, upon all accounts, and then it falleth in with what I shall tender as the universal medicine and remedy in this case in the process of this discourse; whereof afterward.

(2.) Consider #emph[the power of temptation], partly from what was showed before, from the #emph[effects] and fruits of it in the saints of old, partly from such other effects in general as we find ascribed to it; as,—

\[1.\] It will #emph[darken the mind], that a man shall not be able to make a right judgment of things, so as he did before he entered into it. As in the men of the world, the god of this world blinds their minds that they should not see the glory of Christ in the gospel, 2 Cor. iv. 4, and “whoredom, and wine, and new wine, take away their hearts,” Hos. iv. 11; so it is in the nature of every temptation, more or less, to take away the heart, or to darken the understanding of the person tempted.

And this it doth divers ways:—

1#emph[st]. By #emph[fixing] the imagination and the thoughts upon the #emph[object] whereunto it tends, so that the mind shall be diverted from the consideration of the things that would relieve and succour it in the state wherein it is. A man is tempted to apprehend that he is forsaken of God, that he is an object of his hatred, that he hath no interest in Christ. By the craft of Satan the mind shall be so #emph[fixed] to the consideration of this state and condition, with the distress of it, that he shall not be able to manage any of the reliefs suggested and tendered to him against it; but, following the fulness of his own thoughts, shall walk on in darkness and have no light. I say, a temptation will so possess and fill the mind with thoughtfulness of itself and the matter of it, that it will take off from that clear consideration of things which otherwise it might and would have. And those things whereof the mind was wont to have a vigorous sense, to keep it from sin, will by this means come to have no force or efficacy with it; nay, it will commonly bring men to that state and condition, that when others, to whom their estate is known, are speaking to them the things that concern their deliverance and peace, their minds will be so possessed with the matter of their temptation as not at all to understand, scarce to hear one word, that is spoken to them.

2#emph[dly]. By #emph[woful entangling of the affections]\; which, when they are engaged, what influence they have in blinding the mind and darkness and darkening the understanding is known. If any know it not, let him but open his eyes in these days, and he will quickly learn it. By what ways and means it is that engaged affections will becloud the mind and darken it I shall not now declare; only, I say, give me a man engaged in hope, love, fear, in reference to any particulars wherein he ought not, and I shall quickly show you wherein he is darkened and blinded. This, then, you will fail in if you enter into temptation:— The present judgment you have of things will not be utterly altered, but darkened and rendered infirm to influence the will and master the affections. These, being set at liberty by temptation, will run on in madness. Forthwith detestation of sin, abhorring of it, terror of the Lord, sense of love, presence of Christ crucified, all depart, and leave the heart a prey to its enemy.

3#emph[dly]. Temptation will give #emph[oil and fuel] to our lusts,—incite, provoke, and make them tumultuate and rage beyond measure. Tendering a lust, a corruption, a suitable object, advantage, occasion, it heightens and exasperates it, makes it for a season wholly predominant: so dealt it with carnal fear in Peter, with pride in Hezekiah, with covetousness in Achan, with uncleanness in David, with worldliness in Demas, with ambition in Diotrephes. It will lay the reins on the neck of a lust, and put spurs to the sides of it, that it may rush forward like a horse into the battle. A man knows not the pride, fury, madness of a corruption, until it meet with a suitable temptation. And what now will a poor soul think to do? His mind is darkened, his affections entangled, his lusts inflamed and provoked, his relief is defeated; and what will be the issue of such a condition?

(3.) Consider that temptations are either #emph[public or private]\; and let us a little view the efficacy and power of them apart:—

\[1.\] There are public temptations; such as that mentioned, Rev. iii. 10, that was to come upon the world, “to try them that dwell upon the earth;” or a combination of persecution and seduction for the trial of a careless generation of professors. Now, concerning such a temptation, consider that,—

1#emph[st]. It hath an #emph[efficacy] in respect of God, who sends it to revenge the neglect and contempt of the gospel on the one hand, and treachery of false professors on the other. Hence it will certainly accomplish what it receives commission from him to do. When Satan offered his service to go forth and seduce Ahab that he might fall, God says to him, “Thou shalt persuade him, and prevail also: go forth, and do so,” 1 Kings xxii. 22. He is permitted as to his wickedness, and commissionated as to the event and punishment intended. When the Christian world was to be given up to folly and false worship for their neglect of the truth, and their naked, barren, fruitless, Christ-dishonouring profession, it is said of the temptation that fell upon them, that “God sent them strong delusion, that they should believe a lie,” 2 Thess. ii. 11. That that comes so from God in a #emph[judiciary] manner, hath a power with it and shall prevail. That selfish spiritually-slothful, careless , and worldly frame of spirit, which in these days hath infected almost the body of professors, if it have a commission from God to kill hypocrites, to wound negligent saints, to break their bones, and make them scandalous, that they may be ashamed, shall it not have a power and efficacy so to do? What work hath the spirit of error made amongst us! Is it not from hence, that as some men delighted not to retain God in their hearts, so he hath “given them up to a reprobate mind,” Rom. i. 28. A man would think it strange, yea, it is matter of amazement, to see persons of a sober spirit, pretending to great things in the ways of God, overcome, captivated, ensnared, destroyed by weak means, sottish opinions, foolish imaginations, such as a man would think it impossible that they should ever lay hold on sensible or rational men, much less on professors of the gospel. But that which God will have to be strong, let us not think weak. No strength but the strength of God can stand in the way of the weakest things of the world that are commissionated from God for any end or purpose whatever.

2#emph[dly]. There is in such temptations the secret insinuation of #emph[examples] in those that are accounted #emph[godly] and are professors: Matt. xxiv. 12, “Because iniquity shall abound, the love of many shall wax cold,” etc. The abounding of iniquity in some will insensibly cast water on the zeal and love of others, that by little and little it shall wax cold. Some begin to grow negligent, careless, worldly, wanton. They break the ice towards the pleasing of the flesh. At first others blame, judge them, perhaps reprove them. In a short space their love also waxes cold; and the brunt being over, they also conform to them, and are cast into the same mould with them. “A little leaven leaveneth the whole lump.” Paul repeats this saying twice, 1 Cor. v. 6, and Gal. v. 9. He would have us take notice of it; and it is of the danger of the infection of the whole body, from the ill examples of some, whereof he speaks. We know how insensibly leaven proceedeth to give a savour to the whole; so it is termed a “root of bitterness” that “springeth up and defileth many,” Heb. xii. 15. If one little piece of leaven, if one bitter root, may endanger the whole, how much more when there are many roots of that nature, and much leaven is scattered abroad! It is easy following a multitude to do evil, and saying “A conspiracy” to them to whom the people say “A conspiracy.” Would any one have thought it possible that such and such professors, in our days, should have fallen into ways of self, of flesh, of the world? to play at cards, dice, revel, dance? to neglect family, closet duties? to be proud, haughty, ambitious, worldly, covetous, oppressive? or that they should be turned away after foolish, vain, ridiculous opinions, deserting the gospel of Christ? In which two lies the great temptation that is come on us, the inhabitants of this world, to try us. But doth not every man see that this is come to pass? And may we not see how it is come to pass? Some loose, empty professors, who had never more than a form of godliness, when they had served their turn of that, began the way to them; then others began a little to comply, and to please the flesh in so doing. This, by little and little, hath reached even the top boughs and branches of our profession, until almost all flesh hath corrupted its way. And he that departeth from these iniquities makes his name a prey, if not his person.

3#emph[dly]. Public temptations are usually accompanied with #emph[strong reasons and pretences], that are too hard for men, or at least insensibly prevail upon them to an undervaluation of the evil whereunto the temptation leads, to give strength to that complicated temptation which in these days hath even cast down the people of God from their excellency,—hath cut their locks, and made them become like other men. How full is the world of specious pretences and pleadings! As there is the liberty and freedom of Christians, delivered from a bondage frame, this is a door that, in my own observation, I have seen sundry going out at, into sensuality and apostasy; beginning at a light conversation, proceeding to a neglect of the Sabbath, public and private duties, ending in dissoluteness and profaneness. And then there is leaving of public things to Providence, being contented with what is;—things good in themselves, but disputed into wretched, carnal compliances, and the utter ruin of all zeal for God, the interest of Christ or his people in the world. These and the like considerations, joined with the ease and plenty, the greatness and promotion of professors, have so brought things about, that whereas we have by Providence shifted places with the men of the world, we have by sin shifted spirits with them also. We are like a plantation of men carried into a foreign country. In a short space they degenerate from the manners of the people from whence they came, and fall into that of the country whereunto they are brought; as if there were something in the soil and the air that transformed them. Give me leave a little to follow my similitude: He that should see the prevailing party of these nations, many of those in rule, power, favour, with all their adherents, and remember that they were a colony of Puritans,—whose habitation was “in a low place,” as the prophet speaks of the city of God,—translated by a high hand to the mountains they now possess, cannot but wonder how soon they have forgot the customs, manners, ways, of their own old people, and are cast into the mould of them that went before them in the places whereunto they are translated. I speak of us all, especially of us who are amongst the lowest of the people, where perhaps this iniquity doth most abound. What were those before us that we are not? what did they that we do not? Prosperity hath slain the foolish and wounded the wise.

\[2.\] Suppose the temptation is private. This hath been spoken to before; I shall add two things:—

1#emph[st]. Its #emph[union and incorporation] with lust, whereby it gets within the soul, and lies at the bottom of its actings. John tells us, 1 Epist. ii. 16, that the things that are “in the world” are, “the lust of the flesh, the lust of the eyes, the pride of life.” Now, it is evident that all these things are principally in the #emph[subject], not in the #emph[object],—in the #emph[heart], not in the #emph[world]. But they are said to be “in the world,” because the world gets into them, mixes itself with them, unites, incorporates. As faith and the promises are said to be “mixed,” Heb. iv. 2, so are lust and temptation mixed: they twine together; receive mutual improvement from one another; grow each of them higher and higher by the mutual strength they administer to one another. Now, by this means temptation gets so deep in the heart that no contrary reasonings can reach unto it; nothing but what can kill the lust can conquer the temptation. Like leprosy that hath mingled itself with the wall, the wall itself must be pulled down, or the leprosy will not be cured. Like a gangrene that mixes poison with the blood and spirits, and cannot be separated from the place where it is, but both must be cut off together. For instance, in David’s temptation to uncleanness, ten thousand considerations might have been taken in to stop the mouth of the temptation; but it had united itself with his lust, and nothing but the killing of that could destroy it, or get him the conquest. This deceives many a one. They have some pressing temptation, that, having got some advantages, is urgent upon them. They pray against it, oppose it with all powerful considerations, such as whereof every one seems sufficient to conquer and destroy it, at least to overpower it, that it should never be troublesome any more; but no good is done, no ground is got or obtained, yea, it grows upon them more and more. What is the reason of it? It hath incorporated and united itself with the lust, and is safe from all the opposition they make. If they would make work indeed, they are to set upon the whole of the lust itself; their ambition, pride, worldliness, sensuality, or whatever it be, that the temptation is united with. All other dealings with it are like tamperings with a prevailing gangrene: the part or whole may be preserved a little while, in great torment; excision or death must come at last. The soul may cruciate itself for a season with such a procedure; but it must come to this,—its lust must die, or the soul must die.

2#emph[dly]. In what part soever of the soul the lust be seated wherewith the temptation is united, it draws after it #emph[the whole soul] by one means or other, and so prevents or anticipates any opposition. Suppose it be a lust of the mind,—as there are lusts of the mind and uncleanness of the spirit, such as ambition, vain-glory, and the like,—what a world of ways hath the understanding to bridle the affections that they should not so tenaciously cleave to God, seeing in what it aimeth at there is so much to give them contentment and satisfaction! It will not only prevent all the reasonings of the mind, which it doth necessarily,—being like a bloody infirmity in the eyes, presenting all things to the common sense and perception in that hue and colour,—but it will draw the whole soul, on other accounts and collateral considerations, into the same frame. It promises the whole a share in the spoil aimed at; as Judas’s money, that he first desired from covetousness, was to be shared among all his lusts. Or be it in the more sensual part, and first possesseth the affections,—what prejudices they will bring upon the understanding, how they will bribe it to an acquiescence, what arguments, what hopes they will supply it withal, cannot easily be expressed, as was before showed. In brief, there is no particular temptation, but, when it is in its hour, it hath such a contribution of assistance from things good, evil, indifferent, is fed by so many considerations that seem to be most alien and foreign to it, in some cases hath such specious pleas and pretences, that its strength will easily be acknowledged.

(4.) Consider the end of any temptation; this is Satan’s end and sin’s end,—that is, the dishonour of God and the ruin of our souls.

(5.) Consider what hath been the #emph[issue] of any former temptations that thou hast had. Have they not defiled thy conscience, disquieted thy peace, weakened thee in thy obedience, clouded the face of God? Though thou wast not prevailed on to the outward evil or utmost issue of thy temptation, yet hast thou not been foiled? hath not thy soul been sullied and grievously perplexed with it? yea, didst thou ever in thy life come fairly off, without sensible loss, from any temptation almost that thou hadst to deal withal; and wouldst thou willingly be entangled again? If thou art at liberty, take heed; enter no more, if it be possible, lest a worse thing happen to thee.

These, I say, are some of those many considerations that might be insisted on, to manifest the importance of the truth proposed, and the fulness of our concernment in taking care that we “enter not into temptation.”

Against what hath been spoken, some objections that secretly insinuate themselves into the souls of men, and have an efficacy to make them negligent and careless in this thing, which is of such importance to them,—a duty of such indispensable necessity to them who intend to walk with God in any peace, or with any faithfulness,—are to be considered and removed. And they are these that follow:—

#emph[Obj.] 1. “Why should we so fear and labour to avoid temptation? James i. 2, we are commanded to ‘count it all joy when we fall into divers temptations.’ Now, certainly I need not solicitously avoid the falling into that which, when I am fallen into, I am to count it all joy.” To which I answer,—

1\. You will not hold by this rule in all things,—namely, that a man need not seek to avoid that which, when he cannot but fall into, it is his duty to rejoice therein. The same apostle bids the rich “rejoice that they are made low,” chap. i. 10. And, without doubt, to him who is acquainted with the goodness, and wisdom, and love of God in his dispensations, in every condition that is needful for him, it will be a matter of rejoicing to him: but yet, how few rich, godly men can you persuade not to take heed, and use all lawful means that they be not made poor and low! and, in most cases, the truth is, it were their sin not to do so. It is our business to make good our stations, and to secure ourselves as we can; if God alter our condition we are to rejoice in it. If the temptations here mentioned befall us, we may have cause to rejoice; but not if, by a neglect of duty, we fall into them.

2\. Temptations are taken #emph[two ways]:—

(1.) Passively and merely #emph[materially], for such things as are, or in some cases may be, temptations; or,—

(2.) #emph[Actively], for such as do entice to sin. James speaks of temptations in the first sense only; for having said, “Count it all joy when ye fall into divers temptations,” verse 2; he adds, verse 12, “Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life.” But now whereas a man might say, “If this be so, then temptations are good, and from God;”—“No,” says James; “take temptation in such a sense as that it is a thing enticing and leading to sin, so God tempts none; but every man is tempted of his own lust,” verse 13, 14. “To have such temptations, to be tempted to sin, that is not the blessed thing I intend; but the enduring of afflictions that God sends for the trial of our faith, that is a blessed thing. So that, though I must count it all joy when, through the will of God, I fall into divers afflictions for my trial, which yet have the matter of temptation in them, yet I am to use all care and diligence that my lust have no occasions or advantages given unto it to tempt me to sin.”

#emph[Obj.] 2. “But was not our Saviour Christ himself tempted; and is it evil to be brought into the same state and condition with him? Yea, it is not only said that he was tempted, but his being so is expressed as a thing advantageous, and conducing to his mercifulness as our priest: Heb. ii. 17, 18, ‘In that he himself hath suffered, being tempted, he is able to succour them that are tempted.’ And he makes it a ground of a great promise to his disciples, that they had ‘abode with him in his temptations,’ Luke xxii. 28.”

#emph[Ans.] It is true, our Saviour was tempted; but yet his temptations are reckoned among the #emph[evils] that befell him in the days of his flesh,—things that came on him through the malice of the world and the prince thereof. He did not wilfully cast himself into temptation, which he said was “to tempt the Lord our God,” Matt. iv. 7; as, indeed, willingly to enter into any temptation is highly to tempt God. Now, our condition is so, that, use the greatest diligence and watchfulness that we can, yet we shall be sure to be tempted, and be made like to Christ therein. This hinders not but that it is our duty to the utmost to prevent our falling into them; and that namely on this account:—Christ had only the #emph[suffering] part of temptation when he entered into it; we have also the #emph[sinning] part of it. When the prince of this world came to Christ, he had “no part in him;” but when he comes to us, he hath so in us. So that though in one effect of temptations, namely trials and disquietness, we are made like to Christ, and so are to rejoice as far as by any means that is produced; yet by another we are made unlike to him,—which is our being defiled and entangled: and are therefore to seek by all means to avoid them. We never come off like Christ. Who of us “enter into temptation” and are not defiled?

#emph[Obj.] 3. “But what need this great endeavour and carefulness? Is it not said that ‘God is faithful, who will not suffer us to be tempted above what we are able, but will with the temptation also make a way to escape?’ 1 Cor. x. 13; and ‘He knoweth how to deliver the godly out of temptations,’ 2 Pet. ii. 9. What need we, then, be solicitous that we enter not into them?”

#emph[Ans.] I much question what assistance he will have from God in his temptation who willingly enters into it, because he supposes God hath promised to deliver him out of it. The Lord knows that, through the craft of Satan, the subtlety and malice of the world, the deceitfulness of sin, that doth so easily beset us, when we have done our utmost, yet we shall enter into divers temptations. In his love, care, tenderness, and faithfulness, he hath provided such a sufficiency of grace for us, that they shall not utterly prevail to make an everlasting separation between him and our souls. Yet I have three things to say to this objection:—

(1.) He that #emph[wilfully] or negligently enters into temptation hath no reason in the world to promise himself any assistance from God, or any deliverance from the temptation whereunto he is entered. The promise is made to them whom temptations do befall in their way, whether they will or not; not them that wilfully fall into them,—that run out of their way to meet with them. And therefore the devil (as is usually observed), when he tempted our Saviour, left out that expression of the text of Scripture, which he wrested to his purpose, “All thy ways.” The promise of deliverance is to them who are in their ways; whereof this is one principal, to beware of temptation.

(2.) Though there be a sufficiency of grace provided for all the #emph[elect], that they shall by no temptation fall utterly from God, yet it would make any gracious heart to tremble, to think what dishonour to God, what scandal to the gospel, what woful darkness and disquietness they may bring upon their own souls, though they perish not. And they who are scared by nothing but fear of hell, on whom other considerations short thereof have no influence, in my apprehension have more reason to fear it than perhaps they are aware of.

(3.) To enter on temptation on this account is to venture on sin (which is the same with “continuing in sin”) “that grace may abound,” Rom. vi. 1, 2; which the apostle rejects the thoughts of with greatest detestation. Is it not a madness, for a man willingly to suffer the ship wherein he is to split itself on a rock, to the irrecoverable loss of his merchandise, because he supposes he shall in his own person swim safely to shore on a plank? Is it less in him who will hazard the shipwreck of all his comfort, peace, joy, and so much of the glory of God and honour of the gospel as he is entrusted with, merely on supposition that his soul shall yet escape? These things a man would think did not deserve to be mentioned, and yet with such as these do poor souls sometimes delude themselves.
