== Chapter I

#block(inset: (x: 1em))[The words of the text, that are the foundation of the ensuing discourse—The occasion of the words, with their dependence—The things specially aimed at in them—Things considerable in the words as to the general purpose in hand—Of the general nature of temptation, wherein it consists—The special nature of temptation—Temptation taken actively and passively—How God tempts any—His ends in so doing—The way whereby he doth it—Of temptation in its special nature; of the actions of it—The true nature of temptation stated.]

#block(inset: (x: 1em))[“Watch and pray, that ye enter not into temptation.”—Matt. xxvi. 41]

These words of our Saviour are repeated with very little alteration in three evangelists; only, whereas Matthew and Mark have recorded them as above written, Luke reporteth them thus: “Rise and pray, lest ye enter into temptation;” so that the whole of his caution seems to have been, “Arise, watch and pray, that ye enter not into temptation.”

Solomon tells us of some that “lie down on the top of a mast in the midst of the sea,” Prov. xxiii. 34,—men overborne by security in the mouth of destruction. If ever poor souls lay down on the top of a mast in the midst of the sea, these disciples with our Saviour in the garden did so. Their Master, at a little distance from them, was “offering up prayers and supplications, with strong crying and tears,” Heb. v. 7, being then taking into his hand and beginning to#footnote[Heb. ii. 9; Gal. iii. 13; 2 Cor. v. 21.] taste that cup that was filled with the curse and wrath due to their sins;—the Jews, armed for #emph[his] and #emph[their] destruction, being but a little more distant from them, on the other hand. Our Saviour had a little before informed them that that night he should be betrayed, and be delivered up to be slain; they saw that he was “sorrowful, and very heavy,” Matt. xxvi. 37; nay, he told them plainly that his “soul was exceeding sorrowful, even unto death,” verse 38, and therefore entreated them to tarry and watch with him, now he was dying, and that for them. In this condition, leaving them but a little space, like men forsaken of all love towards him or care of themselves, they fall fast asleep! Even the best of saints, being left to themselves, will quickly appear to be less than men,—to be nothing. All our own strength is weakness, and all our wisdom folly. Peter being one of them,—who but a little before had with so much self-confidence affirmed that though all men forsook him, yet he never would so do,—our Saviour expostulates the matter in particular with him: verse 40, “He saith unto Peter, Could you not watch with me one hour?” as if he should have said, “Art thou he, Peter, who but now boastedst of thy resolution never to forsake me? Is it likely that thou shouldst hold out therein, when thou canst not watch with me one hour? Is this thy dying for me, to be dead in security, when I am dying for thee?” And indeed it would be an amazing thing to consider that Peter should make so high a promise, and be immediately so careless and remiss in the pursuit of it, but that we find the root of the same treachery abiding and working in our own hearts, and do see the fruit of it brought forth every day, the most noble engagements unto obedience quickly ending in deplorable negligence, Rom. vii. 18.

In this estate our Saviour admonishes them of their condition, their weakness, their danger, and stirs them up to a prevention of that ruin which lay at the door: saith he, “Arise, watch and pray.”

I shall not insist on the particular aimed at here by our Saviour, in this caution to them that were then present with him; the great temptation that was coming on them, from the scandal of the cross, was doubtless in his eye;—but I shall consider the words as containing a general direction to all the disciples of Christ, in their following of him throughout all generations.

There are three things in the words:—

I. The #emph[evil] cautioned against,—#emph[temptation].

II. The #emph[means] of its prevalency,—by our #emph[entering into it].

III. The #emph[way] of preventing it,—#emph[watch and pray].

It is not in my thoughts to handle the common-place of temptations, but only the danger of them in general, with the means of preventing that danger; yet, that we may know what we affirm, and whereof we speak, some concernments of the general nature of temptation may be premised.

I. First, For the #emph[general] nature of tempting and temptation, it lies among things indifferent; to try, to experiment, to prove, to pierce a vessel, that the liquor that is in it may be known, is as much as is signified by it. Hence God is said sometime to tempt; and we are commanded as our duty to tempt, or try, or search ourselves, to know what is in us, and to pray that God would do so also. So temptation is like a knife, that may either cut the meat or the throat of a man; it may be his food or his poison, his exercise or his destruction.

Secondly, Temptation in its #emph[special] nature, as it denotes any evil, is considered either actively, as it #emph[leads] to evil, or passively, as it #emph[hath] an evil and suffering in it: so temptation is taken for affliction, James i. 2; for in that sense, we are to “count it all joy when we fall into temptation;” in the other, that we “enter not into it.”

Again, actively considered, it either denotes in the tempter a design for the bringing about of the special end of temptation, namely, #emph[a leading into evil]\; so it is said, that “God tempts no man,” James i. 13, with a design for sin as such;—or the general nature and end of temptation, which is trial; so “God tempted Abraham,” Gen. xxii. 1. And he proveth or tempteth by false prophets, Deut. xiii. 3.

Now, as to God’s tempting of any, two things are to be considered:—1. The end why he doth it; 2. The way whereby he doth it.

1\. For the first, his general ends are two:—

(1.) He doth it to #emph[show] unto man what is in him,—that is, the man himself; and that either as to his grace or to his corruption. (I speak not now of it as it may have a place and bear a part in judiciary obduration.) Grace and corruption lie deep in the heart; men oftentimes deceive themselves in the search after the one or the other of them. When we give vent to the soul, to try what grace is there, corruption comes out; and when we search for corruption, grace appears. So is the soul kept in uncertainty; we fail in our trials. God comes with a gauge that goes to the bottom. He sends his instruments of trial into the bowels and the inmost parts of the soul, and lets man see what is in him, of what metal he is constituted. Thus he tempted Abraham to show him his #emph[faith]. Abraham knew not what faith he had (I mean, what power and vigour was in his faith) until God drew it out by that great trial and temptation.#footnote[Gen. xxii. 1, 2.] When God says he knew it, he made Abraham know it. So he tried Hezekiah to discover his #emph[pride]\; God left him that he might see what was in his heart, 2 Chron. xxxii. 31. He knew not that he had such a proud heart, so apt to be lifted up, as he appeared to have, until God tried him, and so let out his filth, and poured it out before his face. The issues of such discoveries to the saints, in thankfulness, humiliation, and treasuring up of experiences, I shall not treat of.

(2.) God doth it to #emph[show himself] unto man, and that,—

\[1.\] In a way of #emph[preventing grace]. A man shall see that it is God alone who keeps from all sin. Until we are tempted, we think we live on our own strength. Though all men do this or that, we will not. When the trial comes, we quickly see whence is our preservation, by standing or falling. So was it in the case of Abimelech, Gen. xx. 6, “I withheld thee.”

\[2.\] In a way of #emph[renewing grace]. He would have the temptation continue with St Paul, that he might reveal himself to him in the sufficiency of his renewing grace, 2 Cor. xii. 9. We know not the power and strength that God puts forth in our behalf, nor what is the sufficiency of his grace, until, comparing the temptation with our own weakness, it appears unto us. The efficacy of an antidote is found when poison hath been taken; and the preciousness of medicines is made known by diseases. We shall never know what strength there is in grace if we know not what strength there is in temptation. We must be tried, that we may be made sensible of being preserved. And many other good and gracious ends he hath, which he accomplisheth towards his saints by his trials and temptations, not now to be insisted on.

2\. For the ways whereby God accomplisheth this his search, trial, or temptation, these are some of them:—

(1.) He puts men on #emph[great duties], such as they cannot apprehend that they have any strength for, nor indeed have. So he tempted Abraham by calling him to that duty of #emph[sacrificing his son]\;—a thing absurd to reason, bitter to nature, and grievous to him on all accounts whatever. Many men know not what is in them, or rather what is ready for them, until they are put upon what seems utterly above their strength; indeed, upon what is really above their strength. The duties that God, in an ordinary way, requires at our hands are not proportioned to what strength we have in ourselves, but to what help and relief is laid up for us in Christ; and we are to address ourselves to the greatest performances with a settled persuasion that we have not ability for the least. This is the law of grace; but yet, when any duty is required that is extraordinary, that is a secret not often discovered in the yoke of Christ, it is a trial, a temptation.

(2.) By putting them upon #emph[great sufferings]. How many have unexpectedly found strength to die at a stake, to endure tortures for Christ! yet their call to it was a trial. This, Peter tells us, is one way whereby we are brought into trying temptations, 1 Pet. i. 6, 7. Our temptations arise from the “fiery trial;” and yet the end is but the trial of our faith.

(3.) By his providential disposing of things so as that #emph[occasions] unto sin will be administered unto men, which is the case mentioned, Deut. xiii. 3; and innumerable other instances may be adjoined.

Now, they are not properly the temptations of God, as coming from him, with his end upon them, that are here intended; and therefore I shall set these apart from our present consideration. It is, then, temptation in its special nature, as it denotes an #emph[active efficiency towards sinning] (as it is managed with evil unto evil) that I intend.

In this sense temptation may proceed either singly from Satan, or the world, or other men in the world, or from ourselves, or jointly from all or some of them, in their several combinations:—

(1.) Satan tempts sometimes #emph[singly] by himself, without taking advantage from the world, the things or persons of it, or ourselves. So he deals in his injection of evil and blasphemous thoughts of God into the hearts of the saints; which is his own work alone, without any advantage from the world or our own hearts: for nature will contribute nothing thereunto, nor any thing that is in the world, nor any man of the world; for none can conceive a God and conceive evil of him. Herein Satan is alone in the #emph[sin], and shall be so in the #emph[punishment]. These fiery darts are prepared in the forge of his own malice, and shall, with all their venom and poison, be turned into his own heart for ever.

(2.) Sometimes he makes #emph[use of the world], and joins forces against us, without any helps from within. So he tempted our Saviour, by “showing him all the kingdoms of the world, and the glory of them.”#footnote[Matt. iv. 8.] And the variety of the assistances he finds from the world, in persons and things which I must not insist on,—the innumerable instruments and weapons he takes from thence of all sorts and at all seasons,—are inexpressible.

(3.) Sometimes he takes in #emph[assistance from ourselves also]. It is not with us as it was with Christ when Satan came to tempt him. He declares that he “had nothing in him,” John xiv. 30. It is otherwise with us: he hath, for the compassing of most of his ends, a sure party within our own breasts, James i. 14, 15. Thus he tempted Judas: he was at work #emph[himself]\; he put it into his heart to betray Christ; Luke xxii. 3, “he entered into him” for that purpose. And he sets the #emph[world] at work, the things of it, providing for him “thirty pieces of silver” (verse 5, “They covenanted to give him money”); and the #emph[men of it], even the priests and the Pharisees; and calleth in the assistance of his #emph[own corruption],—he was covetous, “a thief, and had the bag.”

I might also show how the world and our own corruptions do act singly by themselves, and jointly in conjunction with Satan and one another, in this business of temptation. But the truth is, the principles, ways, and means of temptations, the kinds, degrees, efficacy, and causes of them, are so inexpressibly large and various; the circumstances of them, from providence, natures, conditions, spiritual and natural, with the particular cases thence arising, so innumerable and impossible to be comprised within any bound or order, that to attempt the giving an account of them would be to undertake that which would be endless. I shall content myself to give a description of the general nature of that which we are to watch against; which will make way for what I aim at.

Temptation, then, in general, is #emph[any thing, state, way, or condition that, upon any account whatever, hath a force or efficacy to seduce, to draw the mind and heart of a man from that obedience, which God requires of him, into any sin, in any degree of it whatever].

In particular, that is a temptation to any man which causes or occasions him to sin, or in any thing to go off from his duty, either by #emph[bringing] evil into his heart, or #emph[drawing] out that evil that is in his heart, or any other way diverting him from communion with God, and that constant, equal, universal obedience, in matter and manner, that is required of him.

For the clearing of this description I shall only observe, that though temptation seems to be of a more active importance, and so to denote only the power of seduction to sin itself, yet in the Scripture it is commonly taken in a neuter sense, and denotes the matter of the temptation or the thing whereby we are tempted. And this is a ground of the description I have given of it. Be it what it will, that from any thing whatever, within us or without us, hath advantage to hinder in duty, or to provoke unto or in any way to occasion sin, that is a temptation, and so to be looked on. Be it business, employment, course of life, company, affections, nature, or corrupt design, relations, delights, name, reputation, esteem, abilities, parts or excellencies of body or mind, place, dignity, art,—so far as they further or occasion the promotion of the ends before mentioned, they are all of them no less truly temptations than the most violent solicitations of Satan or allurements of the world, and that soul lies at the brink of ruin who discerns it not. And this will be farther discovered in our process.
