== Chapter VI

#block(inset: (x: 1em))[Of watching that we enter not into temptation—The nature and efficacy of that duty—The first part of it, as to the special seasons of temptation—The first season, in unusual prosperity—The second, in a slumber of grace—Third, a season of great spiritual enjoyment—The fourth, a season of self-confidence.]

The other part of our Saviour’s direction,—namely, to “watch,”—is more general, and extends itself to many particulars. I shall fix on some things that are contained therein:—

3\. Watch the #emph[seasons] wherein men usually do “enter into temptation.”

There are sundry seasons wherein an hour of temptation is commonly at hand, and will unavoidably seize upon the soul, unless it be delivered by mercy in the use of watchfulness. When we are under such a season, then are we peculiarly to be upon our guard that we enter not into, that we fall not under, the power of temptation. Some of those seasons may be named:—

(1.) A season of #emph[unusual outward prosperity] is usually accompanied with an hour of temptation. Prosperity and temptation go together; yea, prosperity is a temptation, many temptations, and that because, without eminent supplies of grace, it is apt to cast a soul into a frame and temper exposed to any temptation, and provides it with fuel and food for all. It hath provision for lust and darts for Satan.

The wise man tells us that the “prosperity of fools destroys them,” Prov. i. 32. It #emph[hardens] them in their way, makes them despise instruction, and put the evil day (whose terror should influence them into amendment) far from them. Without a special assistance, it hath an inconceivably malignant influence on believers themselves. Hence Agur prays against riches, because of the temptation that attends them: “Lest,” saith he, “I be full and deny thee, and say, Who is the Lord?” Prov. xxx. 8, 9;—lest, being filled with them, he should forget the Lord; as God complains that his people did, Hos. xiii. 6. We know how David was mistaken in this case: Ps. xxx. 6, “I said in my prosperity, I shall never be moved.” All is well, and will be well. But what was at hand, what lay at the door, that David thought not of? Verse 7, “Thou didst hide thy face, and I was troubled.” God was ready to hide his face, and David to enter into a temptation of desertion, and he knew it not.

As, then, unto a #emph[prosperous] condition. I shall not run cross to Solomon’s counsel, “In the day of prosperity rejoice,” Eccles. vii. 14. Rejoice in the God of thy mercies, who doth thee good in his patience and forbearance, notwithstanding all thy unworthiness. Yet I may add to it, from the same fountain of wisdom, “Consider,” also, lest evil lie at the door. A man in that state is in the midst of snares. Satan hath many advantages against him; he forgeth darts out of all his enjoyments; and, if he watch not, he will be entangled before he is aware.

Thou wantest that which should poise and ballast thy heart. Formality in religion will be apt to creep upon thee; and that lays the soul open to all temptations in their full power and strength. Satisfaction and delight in creature-comforts, the poison of the soul, will be apt to grow upon thee. In such a time be vigilant, be circumspect, or thou wilt be surprised. Job says, that in his affliction “God made his heart soft,” chap. xxiii. 16. There is a hardness, an insensible want of spiritual sense, gathered in prosperity, that, if not watched against, will expose the heart to the deceits of sin and baits of Satan. “Watch and pray” in this season. Many men’s negligence in it hath cost them dear; their woful experience cries out to take heed. Blessed is he that feareth always, but especially in a time of prosperity.

(2.) As in part was manifested before, a time of #emph[the slumber of grace], of neglect in communion with God, of formality in duty, is a season to be watched in, as that which hath certainly some other temptation attending it.

Let a soul in such an estate awake and look about him. His enemy is at hand, and he is ready to fall into such a condition as may cost him dear all the days of his life. His present estate is bad enough in itself; but it is an indication of that which is worse that lies at the door. The disciples that were with Christ in the mount had not only a bodily, but a spiritual drowsiness upon them. What says our Saviour to them? “Arise; watch and pray, that ye enter not into temptation.” We know how near one of them was to a bitter hour of temptation, and not watching as he ought, he immediately entered into it.

I mentioned before the case of the spouse, Cant. v. 2–8. She slept, and was drowsy, and unwilling to gird up herself to a vigorous performance of duties, in a way of quick, active communion with Christ. Before she is aware, she hath lost her Beloved; then she moans, inquires, cries, endures woundings, reproaches, and all, before she obtains him again. Consider, then, O poor soul, thy state and condition! Doth thy light burn dim? or though it give to others as great a blaze as formerly, yet thou seest not so clearly the face of God in Christ by it as thou hast done? 2 Cor. iv. 6. Is thy zeal cold? or if it do the same works as formerly, yet thy heart is not warmed with the love of God and to God in them as formerly, but only thou proceedest in the course thou hast been in? Art thou negligent in the duties of praying or hearing? or if thou dost observe them, thou doest it not with that life and vigour as formerly? Dost thou flag in thy profession? or if thou keep it up, yet thy wheels are oiled by some sinister respects from within or without? Does thy delight in the people of God faint and grow cold? or is thy love to them changing from that which is purely spiritual into that which is very carnal, upon the account of suitableness of principles and natural spirits, if not worse foundations? If thou art drowsing in such a condition as this, take heed; thou art falling into some woful temptation that will break all thy bones, and give thee wounds that shall stick by thee all the days of thy life. Yea, when thou awakest, thou wilt find that it hath indeed laid hold of thee already, though thou perceivedst it not; it hath smitten and wounded thee, though thou hast not complained nor sought for relief or healing.

Such was the state of the church of Sardis, Rev. iii. 2. “The things that remained were ready to die.” “Be watchful,” says our Saviour, “and strengthen them, or a worse thing will befall thee.” If any that reads the word of this direction be in this condition, if he hath any regard of his poor soul, let him now awake, before he be entangled beyond recovery. Take this warning from God; despise it not.

(3.) A season of #emph[great spiritual enjoyments] is often, by the malice of Satan and the weakness of our hearts, turned into a season of danger as to this business of temptation.

We know how the case stood with Paul, 2 Cor. xii. 7. He had glorious spiritual revelations of God and Jesus Christ. Instantly Satan falls upon him, a messenger from him buffets him; so that he earnestly begs its departure, but yet is left to struggle with it. God is pleased sometimes to give us especial discoveries of himself and his love, to fill the heart with his kindness; Christ takes us into the banqueting-house, and gives our hearts their fills of love; and this by some signal work of his Spirit, overpowering us with a sense of love in the unspeakable privilege of adoption, and so fills our souls with joy unspeakable and glorious. A man would think this was the securest condition in the world. What soul does not cry with Peter in the mount, “It is good for me to be here; to abide here for ever?” But yet very frequently some bitter temptation is now at hand. Satan sees that, being possessed by the joy before us, we quickly neglect many ways of approach to our souls, wherein he seeks and finds advantages against us. Is this, then, our state and condition? Does God at any time give us to drink of the rivers of pleasure that are at his right hand, and satisfy our souls with his kindness as with marrow and fatness? Let us not say, “We shall never be moved;” we know not how soon God may hide his face, or a messenger from Satan may buffet us.

Besides, there lies oftentimes a greater and worse deceit in this business. Men cheat their souls with their own fancies, instead of a sense of God’s love by the Holy Ghost; and when they are lifted up with their imaginations, it is not expressible how fearfully they are exposed to all manner of temptations;—and how, then, are they able to find relief against their consciences from their own foolish fancies and deceivings, wherewith they sport themselves? May we not see such every day,—persons walking in the vanities and ways of this world, yet boasting of their sense of the love of God? Shall we believe them? We must not, then, believe truth itself; and how woful, then, must their condition needs be!

(4.) A fourth season is a season of #emph[self-confidence]\; then usually temptation is at hand.

The case of Peter is clear unto this: “I will not deny thee; though all men should deny thee I will not; though I were to die for it, I would not do it.” This said the poor man when he stood on the very brink of that temptation that cost him in the issue such bitter tears. And this taught him so far to know himself all his days, and gave him such acquaintance with the state of all believers, that when he had received more of the Spirit and of power, yet he had less of confidence, and saw it was fit that others should have so also, and therefore persuades all men to “pass the time of their sojourning here in fear,” 1 Pet. i. 17; not to be confident and high as he was, lest, as he did, they fall. At the first trial he compares himself with others, and vaunts himself above them: “Though all men should forsake thee, yet I will not.” He fears every man more than himself. But when our Saviour afterward comes to him, and puts him directly upon the comparison, “Simon, son of Jonas, lovest thou me more than these?” John xxi. 15, he hath done comparing himself with others, and only crieth, “Lord, thou knowest that I love thee.” He will lift up himself above others no more. Such a season oftentimes falls out. Temptations are abroad in the world, false doctrines, with innumerable other allurements and provocations: we are ready every one to be very confident that we shall not be surprised with them: though all men should fall into these follies yet we would not: surely we shall never go off from our walking with God; it is impossible our hearts should be so sottish. But says the apostle, “Be not high-minded, but fear; let him that thinketh he standeth take heed lest he fall.” Wouldst thou think that Peter, who had walked on the sea with Christ, confessed him to be the Son of God, been with him in the mount, when he heard the voice from the excellent glory, should, at the word of a servant-girl, when there was no legal inquisition after him, no process against him nor any one in his condition, instantly fall a-cursing and swearing that he knew him not? Let them take heed of self-confidence who have any mind to take heed of sin. And this is the first thing in our watching, to consider well the seasons wherein temptation usually makes its approaches to the soul, and be armed against them. And these are some of the seasons wherein temptations are nigh at hand.
