== Chapter V

#block(inset: (x: 1em))[The second case proposed, or inquiries resolved—What are the best directions to prevent entering into temptation—Those directions laid down—The directions given by our Saviour: “Watch and pray”—What is included therein—(1.) Sense of the danger of temptation—(2.) That it is not in our power to keep ourselves—(3.) Faith in promises of preservation—Of prayer in particular.]

2\. Having seen the danger of entering into temptation, and also discovered the ways and seasons whereby and wherein men usually do so, our second inquiry is, What general directions may be given to preserve a soul from that condition that hath been spoken of? And we see our Saviour’s direction in the place spoken of before, Matt. xxvi. 41. He sums up all in these two words, “Watch and pray.” I shall a little labour to unfold them, and show what is inwrapped and contained in them; and that both jointly and severally:—

(1.) There is included in them a clear, #emph[abiding apprehension of the great evil] that there is in entering into temptation. That which a man watches and prays against, he looks upon as evil to him, and by all means to be avoided.

This, then, is the #emph[first] direction:—#emph[Always bear in mind the great danger that it is for any soul to enter into temptation.]

It is a woful thing to consider what slight thoughts the most have of this thing. So men can keep themselves from sin itself in open action, they are content, they scarce aim at more; on any temptation in the world, all sorts of men will venture at any time. How will young men put themselves on any company, any society; at first, being delighted with #emph[evil company], then with the #emph[evil of the company]! How vain are all admonitions and exhortations to them to take heed of such persons, debauched in themselves, corrupters of others, destroyers of souls! At first they will venture on the company, abhorring the thoughts of practising their lewdness; but what is the issue? Unless it be here or there one, whom God snatches with a mighty hand from the jaws of destruction, they are all lost, and become after a while in love with the evil which at first they abhorred. This open door to the ruin of souls is too evident; and woful experience makes it no less evident that it is almost impossible to fasten upon many poor creatures any fear or dread of temptation, who yet will profess a fear and abhorrency of sin. Would it were only thus with young men, such as are unaccustomed to the yoke of the Lord! What sort of men is free from this folly in one thing or other? How many professors have I known that would plead for their #emph[liberty], as they called it! They could hear any thing, all things,—all sorts of men, all men; they would try all things whether they came to them in the way of God or no; and on that account would run to hear and to attend to every broacher of false and abominable opinions, every seducer, though stigmatized by the generality of the saints: for such a one they had their liberty,—they could do it; but the opinions they hated as much as any. What hath been the issue? I scarce ever knew any come off without a wound; the most have had their faith overthrown. Let no man, then, pretend to fear sin that doth not fear temptation to it. They are too nearly allied to be separated. Satan hath put them so together that it is very hard for any man to put them asunder. He hates not the fruit who delights in the root.

When men see that such ways, such companies, such #emph[courses], such businesses, such studies and #emph[aims], do entangle them, make them cold, careless, are quench-coals to them, indispose them to even, universal, and constant obedience, if they adventure on them, sin lies at the door. It is a tender frame of spirit, sensible of its own weakness and corruption, of the craft of Satan, of the evil of sin, of the efficacy of temptation, that can perform his duty. And yet until we bring our hearts to this frame, upon the considerations before-mentioned, or the like that may be proposed, we shall never free ourselves from sinful entanglements. Boldness upon temptation, springing from several pretences, hath, as is known, ruined innumerable professors in these days, and still continues to cast many down from their excellency; nor have I the least hope of a more fruitful profession amongst us until I see more fear of temptation. Sin will not long seem great or heavy unto any to whom temptations seem light or small.

This is the first thing inwrapped in this general direction:—The daily exercise of our thoughts with an apprehension of the great danger that lies in entering into temptation, is required of us. Grief of the Spirit of God, disquietment of our own souls, loss of peace, hazard of eternal welfare, lies at the door. If the soul be not prevailed withal to the observation of this direction, all that ensues will be of no value. Temptation despised will conquer; and if the heart be made tender and watchful here, half the work of securing a good conversation is over. And let not him go any further who resolves not to improve this direction in a daily conscientious observation of it.

(2.) There is this in it also, that it is #emph[not a thing in our own power], to keep and preserve ourselves from entering into temptation. Therefore are we to pray that we may be preserved from it, because we cannot save ourselves.

This is another means of preservation. As we have no strength to resist a temptation when it doth come, when we are entered into it, but shall fall under it, without a supply of sufficiency of grace from God; so to reckon that we have no power or wisdom to keep ourselves from entering into temptation, but must be kept by the power and wisdom of God, is a preserving principle, 1 Pet. i. 5. We are in all things “kept by the power of God.” This our Saviour instructs us in, not only by directing us to pray that we be not led into temptation, but also by his own praying for us, that we may be kept from it: John xvii. 15, “I pray not that thou shouldest take them out of the world, but that thou shouldest keep them from the evil,”—that is, the temptations of the world unto evil, unto sin,—ἐκ τοῦ πονηροῦ, “out of the evil” that is in the world, that is temptation, which is all that is evil in the world; or from the evil one, who in the world makes use of the world unto temptation. Christ prays his Father to keep us, and instructs us to pray that we be so kept. It is not, then, a thing in our own power. The ways of our entering into temptation are so many, various, and imperceptible,—the means of it so efficacious and powerful,—the entrances of it so deceitful, subtle, insensible, and plausible,—our weakness our unwatchfulness, so unspeakable,—that we cannot in the least keep or preserve ourselves from it. We fail both in wisdom and power for this work.

Let the heart, then commune with itself and say, “#emph[I] am poor and weak; #emph[Satan] is subtle, cunning, powerful, watching constantly for advantages against my soul; the #emph[world] earnest, pressing, and full of specious pleas, innumerable pretences, and ways of deceit; my #emph[own corruption] violent and tumultuating, enticing, entangling, conceiving sin, and warring in me, against me; #emph[occasions] and advantages of temptation innumerable in all things I have done or suffer, in all businesses and persons with whom I converse; the #emph[first beginnings] of temptation insensible and plausible, so that, left unto myself, I shall not know that I am ensnared, until my bonds be made strong, and sin hath got ground in my heart: therefore on God alone will I rely for preservation, and continually will I look up to him on that account.” This will make the soul be always committing itself to the care of God, resting itself on him, and to do nothing, undertake nothing, etc, without asking counsel of him. So that a double advantage will arise from the observation of this direction, both of singular use for the soul’s preservation from the evil feared:—

\[1.\] The engagement of the grace and compassion of God, who hath called the #emph[fatherless] and #emph[helpless] to rest upon him; nor did ever soul fail of supplies, who, in a sense of want, rolled itself on him, on the account of his gracious invitation.

\[2.\] The #emph[keeping] of it in such a frame as, on various accounts, is useful for its preservation. He that looks to God for assistance in a due manner is both sensible of his danger, and conscientiously careful in the use of means to preserve himself: which two, of what importance they are in this case, may easily be apprehended by them who have their hearts exercised in these things.

\[3.\] This also is in it,—act #emph[faith] on the #emph[promise] of God for preservation. To believe that he will preserve us is a means of preservation; for this God will certainly do, or make a way for us to escape out of temptation, if we fall into it under such a believing frame. We are to pray for what God hath promised. Our requests are to be regulated by his promises and commands, which are of the same extent. Faith closes with the promises, and so finds relief in this case. This James instructs us in, chap. i. 5–7. What we want we must “ask of God;” but we must “ask in faith,” for otherwise we must not “think that we shall receive any thing of the Lord.” This then, also, is in this direction of our Saviour, that we act faith on the promises of God for our preservation out of temptation. He hath promised that he will keep us in all our ways; that we shall be directed in a way that, though we are fools, “we shall not err therein,” Isa. xxxv. 8; that he will lead us, guide us, and deliver us from the evil one. Set faith on work on these promises of God, and expect a good and comfortable issue. It is not easily conceived what a train of graces faith is attended withal, when it goes forth to meet Christ in the promises, nor what a power for the preservation of the soul lies in this thing; but I have spoken to this elsewhere.#footnote[Mortification of Sin in Believers, chap. xiv.]

\[4.\] Weigh these things #emph[severally], and first, take prayer into consideration. To pray that we enter not into temptation is a means to preserve us from it. Glorious things are, by all men that know aught of those things, spoken of this #emph[duty]\; and yet the truth is, not one half of its excellency, power, and efficacy is known. It is not my business to speak of it in general; but this I say as to my present purpose,—he that would be little in temptation, let him be much in prayer. This calls in the suitable help and succour that is laid up in Christ for us, Heb. iv. 16. This casteth our souls into a frame of opposition to every temptation. When Paul had given instruction for the taking to ourselves “the whole armour of God,” that we may resist and stand in the time of temptation, he adds this general close of the whole, Eph. vi. 18, “Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication.”

Without this all the rest will be of no efficacy for the end proposed. And therefore consider what weight he lays on it: “Praying always,”—that is, at all times and seasons, or be always ready and prepared for the discharge of that duty, Luke xviii. 1, Eph. vi. 18; “with all prayer and supplication in the Spirit,”—putting forth all kinds of desires unto God, that are suited to our condition, according to his will, and which we are assisted in by the Spirit; “and watching thereunto,” lest we be diverted by any thing whatever; and that not for a little while, but “with all perseverance,”—continuance lengthened out to the utmost: so shall we stand. The soul so framed is in a sure posture; and this is one of the means without which this work will not be done. If we do not abide in prayer, we shall abide in cursed temptations. Let this, then, be another direction:—Abide in prayer, and that expressly to this purpose, that we “enter not into temptation.” Let this be one part of our daily contending with God,—that he would preserve our souls, and keep our hearts and our ways, that we be not entangled; that his good and wise providence will order our ways and affairs, that no pressing temptation befall us; that he would give us diligence, carefulness, and watchfulness over our own ways. So shall we be delivered when others are held with the cords of their own folly.
