== Chapter VIII

#block(inset: (x: 1em))[The last general direction, Rev. iii. 10: Watch against temptation by constant “keeping the word of Christ’s patience”—What that word is—How it is kept—How the keeping of it will keep us from the “hour of temptation.”]

The directions insisted on in the former chapters are such as are partly given us, in their several particulars, up and down the Scripture; partly arise from the nature of the thing itself. There is one general direction remains, which is comprehensive of all that went before, and also adds many more particulars unto them. This contains an approved antidote against the poison of temptation,—a remedy that Christ himself hath marked with a note of efficacy and success; that is given us, Rev. iii. 10, in the words of our Saviour himself to the church of Philadelphia. “Because,” saith he, “thou hast kept the word of my patience, I will also keep thee from the hour of temptation, which shall come upon all the world, to try them that dwell in the earth.” Christ is “the same yesterday, today, and for ever.” As he dealt with the church of Philadelphia, so will he deal with us. If we “keep the word of his patience,” he will “keep us from the hour of temptation.” This, then, being a way of rolling the whole care of this weighty affair on him who is able to bear it, it requires our peculiar attention.

And, therefore, I shall show,—(1.) What it is to “keep the word of Christ’s patience,” that we may know how to perform our duty; and, (2.) How this will be a means of our preservation, which will establish us in the faith of Christ’s promise.

(1.) The word of Christ is the word of the gospel; the word by him revealed from the bosom of the Father; the word of the Word; the word spoken in time by the eternal Word. So it is called “The word of Christ,” Col. iii. 16; or “The gospel of Christ,” Rom. i. 16, 1 Cor. ix. 12; and “The doctrine of Christ,” Heb. vi. 1. “Of Christ,” that is, as its author, Heb. i. 1, 2; and of him, as the chief subject or matter of it, 2 Cor. i. 20. Now, this word is called “The word of Christ’s patience,” or tolerance and forbearance, upon the account of that patience and long-suffering which, in the dispensation of it, the Lord Christ exerciseth towards the world, and to all persons in it; and that both actively and passively, in his bearing with men and enduring from them:—

\[1.\] He is patient towards his #emph[saints]\; he bears with them, suffers from them. He is “patient to us-ward,” 2 Pet. iii. 9,—that is, that believe. The gospel is the word of Christ’s patience even to believers. A soul acquainted with the gospel knows that there is no property of Christ rendered more glorious therein than that of his patience. That he should bear with so many unkindnesses, so many causeless breaches, so many neglects of his love, so many affronts done to his grace, so many violations of engagements as he doth, it manifests his gospel to be not only the word of his grace, but also of his patience. He suffers also #emph[from] them in all the reproaches they bring upon his name and ways; and he suffers #emph[in] them, for “in all their afflictions he is afflicted.”

\[2.\] Towards his #emph[elect] not yet effectually called. Rev. iii. 20, he stands waiting at the door of their hearts and knocks for an entrance. He deals with them by all means, and yet stands and waits until “his head is filled with the dew, and his locks with the drops of the night,” Cant. v. 2; as enduring the cold and inconveniences of the night, that when his morning is come he may have entrance. Oftentimes for a long season he is by them scorned in his person, persecuted in his saints and ways, reviled in his word, whilst he stands at the door in the word of his patience, with his heart full of love towards their poor rebellious souls.

\[3.\] To the #emph[perishing world]. Hence the time of his kingdom in this world is called the time of his “patience,” Rev. i. 9. He “endures the vessels of wrath with much long-suffering,” Rom. ix. 22. Whilst the gospel is administered in the world he is patient towards the men thereof, until the saints in heaven and earth are astonished and cry out, “How long?” Ps. xiii. 1, 2; Rev. vi. 10. And themselves do mock at him as if he were an idol, 2 Pet. iii. 4. He endures from them bitter things, in his name, ways, worship, saints, promises, threats, all his interest of honour and love; and yet passeth by them, lets them alone, does them good. Nor will he cut this way of proceeding short until the gospel shall be preached no more. Patience must accompany the gospel.

Now, this is the word that is to be kept, that we may be kept from “the hour of temptation.”

(2.) Three things are implied in the keeping of this word: \[1.\] Knowledge; \[2.\] Valuation; \[3.\] Obedience:—

\[1.\] #emph[Knowledge]. He that will keep this word must know it, be acquainted with it, under a fourfold notion:—1#emph[st]. As a word of #emph[grace] and #emph[mercy], to save him; 2#emph[dly]. As a word of #emph[holiness] and #emph[purity], to sanctify him; 3#emph[dly]. As a word of #emph[liberty] and #emph[power], to ennoble him and set him free; 4#emph[thly]. As a word of #emph[consolation], to support him in every condition:—

1#emph[st]. As a word of #emph[grace] and #emph[mercy], able to save us: “It is the power of God unto salvation,” Rom. i. 16; “The grace of God that bringeth forth salvation,” Tit. ii. 11; “The word of grace that is able to build us up, and to give us an inheritance among all them that are sanctified,” Acts xx. 32; “The word that is able to save our souls,” James i. 21. When the word of the gospel is known as a word of mercy, grace, and pardon, as the sole evidence for life, as the conveyance of an eternal inheritance; when the soul finds it such to itself, it will strive to keep it.

2#emph[dly]. As a word of #emph[holiness] and #emph[purity], able to sanctify him: “Ye are clean through the word I have spoken unto you,” saith our Saviour, John xv. 3. To that purpose is his prayer, chap. xvii. 17. He that knows not the word of Christ’s patience as a sanctifying, cleansing word, in the power of it upon his own soul, neither knows it nor keeps it. The empty profession of our days knows not one step towards this duty; and thence it is that the most are so overborne under the power of temptations. Men full of self, of the world, of fury, ambition, and almost all unclean lusts, do yet talk of keeping the word of Christ! See 1 Pet. i. 2; 2 Tim. ii. 19.

3#emph[dly]. As a word of #emph[liberty] and #emph[power], to ennoble him and set him free;—and this not only from the guilt of sin and from wrath, for that it doth as it is a word of grace and mercy; not only from the power of sin, for that it doth as it is a word of holiness; but also from all outward respects of men or the world that might entangle him or enslave him. It declares us to be “Christ’s freemen,” and in bondage unto none, John viii. 32; 1 Cor. vii. 23. We are not by it freed from due subjection unto superiors, nor from any duty, nor unto any sin, 1 Pet. ii. 16; but in two respects it is a word of freedom, liberty, largeness of mind, power and deliverance from bondage:—

(1#emph[st].) In respect of #emph[conscience] as to the worship of God, Gal. v. 1.

(2#emph[dly].) In respect of #emph[ignoble], slavish respects unto the men or things of the world, in the course of our pilgrimage. The gospel gives a free, large, and noble spirit, in subjection to God, and none else. There is administered in it a spirit “not of fear, but of power, and of love, and of a sound mind,” 2 Tim. i. 7; a mind “in nothing terrified,” Phil. i. 28,—not swayed with any by-respect whatever. There is nothing more unworthy of the gospel than a mind in bondage to persons or things, prostituting itself to the lusts of men or affrightments of the world. And he that thus knows the word of Christ’s patience, really and in power, is even thereby freed from innumerable, from unspeakable temptations.

4#emph[thly]. As a word of #emph[consolation], to support him in every condition, and to be a full portion in the want of all. It is a word attended with “joy unspeakable and full of glory.” It gives supportment, relief, refreshment, satisfaction, peace, consolation, joy, boasting, glory, in every condition whatever. Thus to know the word of Christ’s patience, thus to know the gospel, is the first part, and it is a great part, of this condition of our preservation from the hour and power of temptation.

\[2.\] #emph[Valuation] of what is thus known belongs to the keeping of this word. It is to be kept as a treasure. 2 Tim. i. 14, Τὴν καλὴν παρακαταθήκην,—that excellent “depositum” (that is, the word of the gospel),—“keep it,” saith the apostle, “by the Holy Ghost;” and, “Hold fast the faithful word,” Tit. i. 9. It is a good treasure, a faithful word; hold it fast. It is a word that comprises the whole interest of Christ in the world. To value that as our chiefest treasure is to keep the word of Christ’s patience. They that will have a regard from Christ in the time of temptation are not to be regardless of his concernments.

\[3.\] #emph[Obedience]. Personal obedience, in the universal observation of all the commands of Christ, is the keeping of his word, John xiv. 15. Close adherence unto Christ in holiness and universal obedience, then when the opposition that the gospel of Christ doth meet withal in the world doth render it signally the word of his patience, is the life and soul of the duty required.

Now, all these are to be so managed with that intention of mind and spirit, that care of heart and diligence of the whole person, as to make up a keeping of this word; which evidently includes all these considerations.

We are arrived, then, to the sum of this safeguarding duty, of this condition of freedom from the power of temptation:—He that, having a due acquaintance with the gospel in its excellencies, as to him a word of mercy, holiness, liberty, and consolation, values it, in all its concernments, as his choicest and only treasure,—makes it his business and the work of his life to give himself up unto it in universal obedience, then especially when opposition and apostasy put the patience of Christ to the utmost,—he shall be preserved from the hour of temptation.

This is that which is comprehensive of all that went before, and is exclusive of all other ways for the obtaining of the end proposed. Nor let any man think without this to be kept one hour from entering into temptation; wherever he fails, there temptation enters. That this will be a sure preservative may appear from the ensuing considerations:—

(1.) It hath the #emph[promise] of preservation, and this alone hath so. It is solemnly promised, in the place mentioned, to the church of Philadelphia on this account. When a great trial and temptation was to come on the world, at the opening of the seventh seal, Rev. vii. 3, a caution is given for the preservation of God’s sealed ones, which are described to be those who keep the word of Christ; for the promise is that it should be so.

Now, in every promise there are three things to be considered:—\[1.\] The #emph[faithfulness] of the Father, who gives it. \[2.\] The #emph[grace] of the Son, which is the matter of it. \[3.\] The #emph[power] and #emph[efficacy] of the Holy Ghost, which puts the promise in execution. And all these are engaged for the preservation of such persons from the hour of temptation.

\[1.\] The #emph[faithfulness] of God accompanieth the promise. On this account is our deliverance laid, 1 Cor. x. 13. Though we be tempted, yet we shall be kept from the hour of temptation; it shall not grow too strong for us. What comes on us we shall be able to bear; and what would be too hard for us we shall escape. But what security have we hereof? Even the faithfulness of God: “God is faithful, who will not suffer you,” etc. And wherein is God’s faithfulness seen and exercised? “He is faithful that promised,” Heb. x. 23; his faithfulness consists in his discharge of his promises. “He abideth faithful: he cannot deny himself,” 2 Tim. ii. 13. So that by being under the promise, we have the faithfulness of God engaged for our preservation.

\[2.\] There is in every promise of the covenant #emph[the grace of the Son]\; that is the subject-matter of all promises: “I will keep thee.” How? “By my grace with thee.” So that what assistance the grace of Christ can give a soul that hath a right in this promise, in the hour of temptation it shall enjoy it. Paul’s temptation grew very high; it was likely to have come to its prevalent hour. He “besought the Lord, that is, the Lord Jesus Christ, for help, 2 Cor. xii. 8; and received that answer from him, “My grace is sufficient for thee,” verse 9. That it was the Lord Christ and his grace with whom he had peculiarly to do is evident from the close of that verse: “I will glory in my infirmity, that the power of Christ may rest upon me;” or “the efficacy of the grace of Christ in my preservation be made evident.” So Heb. ii. 18.

\[3.\] The #emph[efficacy] of the Spirit accompanieth the promises. He is called “The Holy Spirit of promise;” not only because he is promised by Christ, but also because he effectually makes good the promise, and gives it accomplishment in our souls. He also, then, is engaged to preserve the soul walking according to the rule laid down. See Isa. lix. 21. Thus, where the promise is, there is all this assistance. The faithfulness of the Father, the grace of the Son, the power of the Spirit, all are engaged in our preservation.

(2.) This #emph[constant, universal] keeping of Christ’s word of patience will keep the heart and soul in such a frame, as wherein no prevalent temptation, by virtue of any advantages whatever, can seize upon it, so as totally to prevail against it. So David prays, Ps. xxv. 21, “Let integrity and uprightness preserve me.” This integrity and uprightness is the Old Testament keeping the word of Christ,—universal close walking with God. Now, how can they preserve a man? Why, by keeping his heart in such a frame, so defended on every side, that no evil can approach or take hold on him. Fail a man in his integrity, he hath an open place for temptation to enter, Isa. lvii. 21. To keep the word of Christ, is to do it universally, as hath been showed. This exercises grace in all the faculties of the soul, and compasses it with the whole armour of God. The understanding is full of light; the affections, of love and holiness. Let the wind blow from what quarter it will, the soul is fenced and fortified; let the enemy assault when or by what means he pleaseth, all things in the soul of such a one are upon the guard; “How can I do this thing, and sin against God?” is at hand. Especially, upon a twofold account doth deliverance and security arise from this hand:—

\[1.\] By the #emph[mortification] of the heart unto the matter of temptations. The prevalency of any temptation arises from hence, that the heart is ready to close with the matter of it. There are lusts within, suited to the proposals of the world or Satan without. Hence James resolves all temptations into our “own lusts,” chap. i. 14; because either they proceed from or are made effectual by them, as hath been declared. Why doth terror or threats turn us aside from a due constancy in the performance of our duty? Is it not because there is unmortified, carnal fear abiding in us, that tumultuates in such a season? Why is it that the allurements of the world and compliances with men entangle us? Is it not because our affections are entangled with the things and considerations proposed unto us? Now, keeping the word of Christ’s patience, in the manner declared, keeps the heart mortified to these things, and so it is not easily entangled by them. Saith the apostle, Gal. ii. 20, “I am crucified with Christ.” He that keeps close to Christ is crucified with him, and is dead to all the desires of the flesh and the world; as more fully, chap. vi. 14. Here the match is broken, and all love, entangling love, dissolved. The heart is crucified to the world and all things in it. Now the matter of all temptations almost is taken out of the world; the men of it, or the things of it, make them up. “As to these things,” says the apostle, “I am crucified to them,” (and it is so with every one that keeps the word of Christ.) “My heart is mortified unto them. I have no desire after them, nor affection to them, nor delight in them, and they are crucified unto me. The crowns, glories, thrones, pleasures, profits of the world, I see nothing desirable in them. The lusts, sensual pleasures, love, respects, honours of men, name and reputation among them, they are all as a thing of nought. I have no value nor estimation of them.” This soul is safeguarded from assaults of manifold temptations. When Achan saw the “goodly Babylonian garment, and two hundred shekels of silver, and a wedge of gold,” first he “coveted them,” then he “took them,” Josh. vii. 21. Temptation subtly spreads the Babylonish garment of favour, praise, peace, the silver of pleasure or profit, with the golden contentments of the flesh, before the eyes of men. If now there be that in them alive, unmortified, that will presently fall a-coveting; let what fear of punishment will ensue, the heart or hand will be put forth unto iniquity.

Herein, then, lies the security of such a frame as that described: It is always accompanied with a mortified heart, crucified unto the things that are the matter of our temptations; without which it is utterly impossible that we should be preserved one moment when any temptation doth befall us. If liking, and love of the things proposed, insinuated, commended in the temptation, be living and active in us, we shall not be able to resist and stand.

\[2.\] In this frame the heart is #emph[filled with better things] and their excellency, so far as to be fortified against the matter of any temptation. See what resolution this puts Paul upon, Phil. iii. 8; all is “loss and dung” to him. Who would go out of his way to have his arms full of loss and dung? And whence is it that he hath this estimation of the most desirable things in the world? It is from that dear estimation he had of the excellency of Christ. So, verse 10, when the soul is exercised to communion with Christ, and to walking with him, he drinks new wine, and cannot desire the old things of the world, for he says “The new is better.” He tastes every day how gracious the Lord is; and therefore longs not after the sweetness of forbidden things,—which indeed have none. He that makes it his business to eat daily of the tree of life will have no appetite unto other fruit, though the tree that bare them seem to stand in the midst of paradise. This the spouse makes the means of her preservation; even the excellency which, by daily communion, she found in Christ and his graces above all other desirable things. Let a soul exercise itself to a communion with Christ in the good things of the gospel,—pardon of sin, fruits of holiness, hope of glory, peace with God, joy in the Holy Ghost, dominion over sin,—and he shall have a mighty preservative against all temptations. As the full soul loatheth the honey-comb,—as a soul filled with carnal, earthly, sensual contentments finds no relish nor savour in the sweetest spiritual things; so he that is satisfied with the kindness of God, as with marrow and fatness,—that is, every day entertained at the banquet of wine, wine upon the lees, and well refined,—hath a holy contempt of the baits and allurements that lie in prevailing temptations, and is safe.

(3.) He that so keeps the word of Christ’s patience is always furnished with #emph[preserving considerations] and preserving principles,—moral and real advantages of preservation.

\[1.\] He is furnished with preserving #emph[considerations], that powerfully influence his soul in his walking diligently with Christ. Besides the sense of duty which is always upon him, he considers,—

1#emph[st]. The #emph[concernment] of Christ, whom his soul loves, in him and his careful walking. He considers that the presence of Christ is with him, his eye upon him; that he ponders his heart and ways, as one greatly concerned in his deportment of himself, in a time of trial. So Christ manifests himself to do, Rev. ii. 19–23. He considers all,—what is acceptable, what is to be rejected. He knows that Christ is concerned in his honour, that his name be not evil spoken of by reason of him; that he is concerned in love to his soul, having that design upon him to “present him holy, and unblamable, and unreprovable in his sight,” Col. i. 22,—and his Spirit is grieved where he is interrupted in this work; concerned on the account of his gospel, the progress and acceptation of it in the world,—its beauty would be slurred, its good things reviled, its progress stopped, if such a one be prevailed against; concerned in his love to others, who are grievously scandalized, and perhaps ruined, by the miscarriages of such. When Hymeneus and Philetus fell, they overthrew the faith of some. And says such a soul, then, who is exercised to keep the word of Christ’s patience, when intricate, perplexed, entangling temptations, public, private, personal, do arise, “Shall I now be careless? shall I be negligent? shall I comply with the world and the ways of it? Oh what thoughts of heart hath he concerning me, whose eye is upon me! Shall I contemn his honour, despise his love, trample his gospel in the mire under the feet of men, turn aside others from his ways? Shall such a man as I fly, give over resisting? It cannot be.” There is no man who keeps the word of the patience of Christ but is full of this soul-pressing consideration. It dwells on his heart and spirit; and the love of Christ constrains him so to keep his heart and ways, 2 Cor. v. 14.

2#emph[dly]. The great consideration of #emph[the temptations of Christ] in his behalf, and the conquest he made in all assaults for his sake and his good, dwell also on his spirit. The prince of this world came upon him, the glory of this world was showed unto him, every thing in earth or hell that hath either allurement or affrightment in it was proposed to him, to divert him from the work of mediation which for us he had undertaken. This whole life he calls the time of his “temptations;” but he resisted all, conquered all, and is become a Captain of salvation to them that obey him. “And,” says the soul, “shall this temptation, these arguings, this plausible pretence, this sloth, this self-love, this sensuality, this bait of the world, turn me aside, prevail over me, to desert him who went before me in the ways of all temptations that his holy nature was obnoxious unto, for my good?”

3#emph[dly]. #emph[Dismal thoughts] of the #emph[loss of love], of the smiles of the countenance of Christ, do also frequently exercise such a soul. He knows what it is to enjoy the favour of Christ, to have a sense of his love, to be accepted in his approaches to him, to converse with him, and perhaps hath been sometimes at some loss in this thing; and so knows also what it is to be in the dark, distanced from him. See the deportment of the spouse in such a case, Cant. iii. 4. When she had once found him again, she holds him; she will not let him go; she will lose him no more.

\[2.\] He that keeps the word of Christ’s patience hath preserving #emph[principles] whereby he is acted. Some of them may be mentioned:—

1#emph[st]. In all things he lives by #emph[faith], and is acted by it in all his ways, Gal. ii. 20. Now, upon a twofold account hath faith, when improved, the power of preservation from temptation annexed unto it:—

(1#emph[st].) Because it empties the soul of its #emph[own wisdom], understanding, and fulness, that it may act in the wisdom and fulness of Christ. The only advice for the preservation in trials and temptations lies in that of the wise man, Prov. iii. 5, “Trust in the Lord with all thine heart; and lean not unto thine own understanding.” This is the #emph[work] of faith; it #emph[is] faith; it is to #emph[live] by faith. The great \[cause of\] falling of men in trials is their leaning to, or leaning upon, their own understanding and counsel. What is the issue of it? Job xviii. 7, “The steps of his strength shall be straitened, and his own counsel shall cast him down.” First, he shall be entangled, and then cast down; and all by his own counsel, until he come to be ashamed of it, as Ephraim was, Hos. x. 6. Whenever in our trials we consult our own understandings, hearken to self-reasonings, though they seem to be good, and tending to our preservation, yet the principle of living by faith is stifled, and we shall in the issue be cast down by our own counsels. Now, nothing can empty the heart of this self-fulness but faith, but living by it, but not living to ourselves, but having Christ live in us by our living by faith on him.

(2#emph[dly].) Faith, making the soul poor, empty, helpless, destitute in itself, #emph[engages] the heart, will, and power of Jesus Christ for assistance; of which I have spoken more at large elsewhere.

2#emph[dly]. #emph[Love] to the saints, with care that they suffer not upon our account, is a great preserving principle in a time of temptations and trials. How powerful this was in David, he declares in that earnest prayer, Ps. lxix. 9, “Let not them that wait on thee, O Lord God of hosts, be ashamed for my sake: let not those that seek thee be confounded for my sake, O God of Israel;”—“O let not me so miscarry, that those for whom I would lay down my life should be put to shame, be evil spoken of, dishonoured, reviled, contemned on my account, for my failings.” A selfish soul, whose love is turned wholly inwards, will never abide in a time of trial.

Many other considerations and principles that those who keep the word of Christ’s patience, in the way and manner before described, are attended withal, might be enumerated; but I shall content myself to have pointed at these mentioned.

And will it now be easy to determine whence it is that so many in our days are prevailed on in the time of trial,—that the hour of temptation comes upon them, and bears them down more or less before it? Is it not because, amongst the great multitude of professors that we have, there are few that keep the word of the patience of Christ? If we wilfully neglect or cast away our interest in the promise of preservation, is it any wonder if we be not preserved? There is an hour of temptation come upon the world, to try them that dwell therein. It variously exerts its power and efficacy. There is not any way or thing wherein it may not be seen acting and putting forth itself. In worldliness; in sensuality; in looseness of conversation; in neglect of spiritual duties, private, public; in foolish, loose, diabolical opinions; in haughtiness and ambition; in envy and wrath; in strife and debate, revenge, selfishness; in atheism and contempt of God, doth it appear. They are but branches of the same root, bitter streams of the same fountain, cherished by peace, prosperity, security, apostasies of professors, and the like. And, alas! how many do daily fall under the power of this temptation in general! How few keep their garments girt about them, and undefiled! And if any urging, particular temptation befall any, what instances almost have we of any that escape? May we not describe our condition as the apostle that of the Corinthians, in respect of an outward visitation: “Some are sick, and some are weak, and many sleep?” Some are wounded, some defiled, many utterly lost. What is the spring and fountain of this sad condition of things? Is it not, as hath been said?—we do not keep the word of Christ’s patience in universal close walking with him, and so lose the benefit of the promise given and annexed thereunto.

Should I go about to give instances of this thing, of professors coming short of keeping the word of Christ, it would be a long work. These four heads would comprise the most of them:—First, #emph[Conformity] to the world, which Christ hath redeemed us from, almost in all things, with joy and delight in promiscuous compliances with the men of the world. Secondly, #emph[Neglect] of duties which Christ hath enjoined, from close meditation to public ordinances. Thirdly, #emph[Strife], variance, and debate among ourselves, woful judging and despising one another, upon account of things foreign to the bond of communion that is between the saints. Fourthly, #emph[Self-fulness] as to principles, and selfishness as to ends. Now, where these things are, are not men carnal? Is the word of Christ’s patience effectual in them? Shall they be preserved? They shall not.

Would you, then, be preserved and kept from the hour of temptation? would you watch against entering into it?—as deductions from what hath been delivered in this chapter, take the ensuing cautions:—

1\. Take heed of leaning on deceitful assistances; as,—

(1.) On your own #emph[counsels], understandings, reasonings. Though you argue in them never so plausibly in your own defence, they will leave you, betray you. When the temptation comes to any height, they will all turn about, and take part with your enemy, and plead as much for the matter of the temptation, whatever it be, as they pleaded against the end and issue of it before.

(2.) The most vigorous actings, by prayer, fasting, and other such means, against that #emph[particular lust], corruption, temptation, wherewith you are exercised and have to do. This will not avail you if, in the meantime, there be neglects on other accounts. To hear a man wrestle, cry, contend as to any particular of temptation, and immediately fall into worldly ways, worldly compliances, looseness, and negligence in other things,—it is righteous with Jesus Christ to leave such a one to the hour of temptation.

(3.) The general #emph[security] of saints’ perseverance and preservation from total apostasy. Every security that God gives us is good in its kind, and for the purpose for which it is given to us; but when it is given for one end, to use it for another, that is not good or profitable. To make use of the general assurance of preservation from total apostasy, to support the spirit in respect of a particular temptation, will not in the issue advantage the soul; because notwithstanding that, this or that temptation may prevail. Many relieve themselves with this, until they find themselves to be in the depth of perplexities.

2\. Apply yourselves to this great preservation of faithful keeping the word of Christ’s patience, in the midst of all trials and temptations:—

(1.) In particular, wisely consider wherein the word of Christ’s patience is most likely to suffer in the days wherein we live and the seasons that pass over us, and so vigorously set yourselves to keep it in that particular peculiarly. You will say, “How shall we know wherein the word of Christ’s patience in any season is like to suffer?” I answer, Consider what works he peculiarly performs in any season; and neglect of his word in reference to them is that wherein his word is like to suffer. The works of Christ wherein he hath been peculiarly engaged in our days and seasons seem to be these:—

\[1.\] The #emph[pouring of contempt] upon the great men and great things of the world, with all the enjoyments of it. He hath discovered the nakedness of all earthly things, in overturning, overturning, overturning, both men and things, to make way for the things that cannot be shaken.

\[2.\] The #emph[owning of the lot] of his own inheritance in a distinguishing manner, putting a difference between the precious and the vile, and causing his people to dwell alone, as not reckoned with the nations.

\[3.\] In being #emph[nigh] to faith and prayer, honouring them above all the strength and counsels of the sons of men.

\[4.\] In recovering his #emph[ordinances] and institutions from the carnal administrations that they were in bondage under by the lusts of men, bringing them forth in the beauty and the power of the Spirit.

Wherein, then, in such a season, must lie the peculiar neglect of the word of Christ’s patience? Is it not in setting a value on the world and the things of it, which he hath stained and trampled under foot? Is it not in the slighting of his peculiar lot, his people, and casting them into the same considerations with the men of the world? Is it not in leaning to our own counsels and understandings? Is it not in the defilement of his ordinances, by giving the outward court of the temple to be trod upon by unsanctified persons? Let us, then, be watchful, and in these things keep the word of the patience of Christ, if we love our own preservation.

(2.) In this frame urge the Lord Jesus Christ with his blessed promises, with all the considerations that may be apt to take and hold the King in his galleries, that may work on the heart of our blessed and merciful High Priest, to give suitable succour at time of need.
