== To the Reader

Christian Reader,

If thou art in any measure awake in these days wherein we live, and hast taken notice of the manifold, great, and various temptations wherewith all sorts of persons that know the Lord and profess his name are beset, and whereunto they are continually exposed, with what success those temptations have obtained, to the unspeakable scandal of the gospel, with the wounding and ruin of innumerable souls, I suppose thou wilt not inquire any farther after other reasons of the publishing of the ensuing warnings and directions, being suited to the times that pass over us, and thine own concernment in them. This I shall only say to those who think meet to persist in any such inquiry, that though my first engagement for the exposing of these meditations unto public view did arise from the desires of some, whose avouching the interest of Christ in the world by personal holiness and constant adhering to every thing that is made precious by its relation to him, have given them power over me to require at any time services of greater importance; yet I dare not lay my doing of it so upon that account, as in the least to intimate that, with respect to the general state of things mentioned, I did not myself esteem it seasonable and necessary. The variety of outward providences and dispensations wherewith I have myself been exercised in this world, with the inward trials they have been attended withal, added to the observation that I have had advantages to make of the ways and walkings of others,—their beginnings, progresses, and endings, their risings and falls, in profession and conversation, in darkness and light,—have left such a constant sense and impression of the power and danger of temptations upon my mind and spirit, that, without other pleas and pretences, I cannot but own a serious call unto men to beware, with a discovery of some of the most eminent ways and means of the prevalency of present temptations, to have been, in my own judgment, in this season needful.

But now, reader, if thou art amongst them, who takest no notice of these things, or carest not for them,—who hast no sense of the efficacy and dangers of temptations in thine own walking and profession, nor hast observed the power of them upon others,—who discernest not the manifold advantages that they have got in these days, wherein all things are shaken, nor hast been troubled or moved for the sad successes they have had amongst professors; but supposest that all things are well within doors and without, and would be better couldst thou obtain fuller satisfaction to some of thy lusts in the pleasures or profits of the world,—I desire thee to know that I write not for thee, nor do esteem thee a fit reader or judge of what is here written. Whilst all the issues of providential dispensations, in reference to the public concernments of these nations, are perplexed and entangled, the footsteps of God lying in the deep, where his paths are not known; whilst, in particular, unparalleled distresses and strange prosperities are measured out to men, yea, to professors; whilst a spirit of error, giddiness, and delusion goes forth with such strength and efficacy, as it seems to have received a commission to go and prosper; whilst there are such divisions, strifes, emulations, attended with such evil surmises, wrath, and revenge, found amongst brethren; whilst the desperate issues and products of men’s temptations are seen daily in partial and total apostasy, in the decay of love, the overthrow of faith, our days being filled with fearful examples of backsliding, such as former ages never knew; whilst there is a visible declension from reformation seizing upon the professing party of these nations, both as to personal holiness and zeal for the interest of Christ;—he that understands not that there is an “hour of temptation” come upon the world, to “try them that dwell upon the earth,” is doubtless either himself at present captivated under the power of some woful lust, corruption, or temptation, or is indeed stark blind, and knows not at all what it is to serve God in temptations. With such, then, I have not at present to do. For those who have in general a sense of these things,—who also, in some measure are able to consider that the plague is begun, that they may be farther awakened to look about them, lest the infection have approached nearer to them, by some secret and imperceptible ways, than they did apprehend; or lest they should be surprised at unawares hereafter by any of those temptations that in these days either waste at noon or else walk in darkness,—is the ensuing warning intended. And for the sake of them that mourn in secret for all the abominations that are found among and upon them that profess the gospel, and who are under the conduct of the Captain of their salvation, fighting and resisting the power of temptations, from what spring soever they rise in themselves, are the ensuing directions proposed to consideration.

That our faithful and merciful High Priest, who both suffered and was tempted, and is on that account touched with the feeling of our infirmities, would accompany this small discourse with seasonable supplies of his Spirit and suitable mercy to them that shall consider it, that it may be useful to his servants for the ends whereunto it is designed, is the prayer of him who received this handful of seed from his storehouse and treasure.

John Owen.
