#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  ./fgb build gives the
// cover the compiled interior's page count and trim, and the spine is Lulu's
// own formula (scripts/panel_cover.typ); `pages` here is only for compiling
// the cover by itself.  VERIFY against a downloaded live 5.5x8.5
// perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-vol-4-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume IV],
  subtitle: [The Seventh and Eighth Treatises: Of Servants and Masters],
  author: [William Gouge],
  pages: 179,
  trim-width: 5.5in,
  trim-height: 8.5in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [The last of the eight treatises, with the exposition of Ephesians 6:5-9 they are raised out of: what a servant owes his master in reverence, obedience and faithfulness, and what a master owes his servants in authority, provision, employment and wages — under the Master they both have in heaven.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
