#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  The page count is read
// from the compiled interior, so recompile the four volumes
// and re-run before ordering.
//
// The spine uses Lulu's own formula rather than page-count-times-caliper.
// The two agree under about 240 pages and drift apart above it; at 300 pages
// they differ by 0.06in, and the trim tolerance is 0.125in.  VERIFY against a
// downloaded live 6x9 perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-ebook-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  subtitle: [Eight Treatises on the Duties of Husbands and Wives, Parents and Children, Masters and Servants],
  author: [William Gouge],
  pages: 837,
  spine: lulu-spine(837),
  paper: "cream-60",
  trim-width: 6in,
  trim-height: 9in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [London, 1622. Eight treatises preached to the parish of Blackfriars: an exposition of Ephesians 5:21-6:9, and then the duties of husband and wife, of wives, of husbands, of children, of parents, of servants, and of masters — each set against the faults that answer to it.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
