#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  ./fgb build gives the
// cover the compiled interior's page count and trim, and the spine is Lulu's
// own formula (scripts/panel_cover.typ); `pages` here is only for compiling
// the cover by itself.  VERIFY against a downloaded live 5.5x8.5
// perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-vol-3-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume III],
  subtitle: [The Fifth and Sixth Treatises: Of Children and Parents],
  author: [William Gouge],
  pages: 230,
  trim-width: 5.5in,
  trim-height: 8.5in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [The duties children owe their parents — reverence, consent, obedience, and the recompense owed to age — and then the parents' own: love and prayer, nursing and nurture, teaching and correction, and the settling of a child in a calling and a marriage.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
