#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  ./fgb build gives the
// cover the compiled interior's page count and trim, and the spine is Lulu's
// own formula (scripts/panel_cover.typ); `pages` here is only for compiling
// the cover by itself.  VERIFY against a downloaded live 5.5x8.5
// perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-vol-2-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume II],
  subtitle: [The Second, Third and Fourth Treatises: Of Husband and Wife],
  author: [William Gouge],
  pages: 348,
  trim-width: 5.5in,
  trim-height: 8.5in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [Who may marry and how a marriage is made; the duties husband and wife owe each other in common; and then, at length, the particular duties of wives and of husbands — each duty set against the fault that answers to it.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
