#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  The page count is read
// from the compiled interior, so recompile domestical-duties-vol-1.pdf
// and re-run before ordering.
//
// The spine uses Lulu's own formula rather than page-count-times-caliper.
// The two agree under about 240 pages and drift apart above it; at 300 pages
// they differ by 0.06in, and the trim tolerance is 0.125in.  VERIFY against a
// downloaded live 6x9 perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-vol-1-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume I],
  subtitle: [The First Treatise: An Exposition of That Part of Scripture Out of Which Domestical Duties Are Raised],
  author: [William Gouge],
  pages: 195,
  spine: lulu-spine(195),
  paper: "cream-60",
  trim-width: 6in,
  trim-height: 9in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [The first of Gouge's eight treatises: a verse-by-verse exposition of Ephesians 5:21-6:4, the passage the whole work is raised out of. Wives and husbands, children and parents, and above them the marriage of Christ and His church.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
