#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  The page count is read
// from the compiled interior, so recompile domestical-duties-vol-3.pdf
// and re-run before ordering.
//
// The spine uses Lulu's own formula rather than page-count-times-caliper.
// The two agree under about 240 pages and drift apart above it; at 300 pages
// they differ by 0.06in, and the trim tolerance is 0.125in.  VERIFY against a
// downloaded live 6x9 perfect-bound template before ordering.
//
//   ./fgb build gouge renders the front panel alone (the ebook cover, and a
//   picture for the web) as cover-vol-3-front.png.
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume III],
  subtitle: [The Fifth and Sixth Treatises: Of Children and Parents],
  author: [William Gouge],
  pages: 194,
  spine: lulu-spine(194),
  paper: "cream-60",
  trim-width: 6in,
  trim-height: 9in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [The duties children owe their parents — reverence, consent, obedience, and the recompense owed to age — and then the parents' own: love and prayer, nursing and nurture, teaching and correction, and the settling of a child in a calling and a marriage.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
