#import "../../../scripts/panel_cover.typ": *

// GENERATED BY sources/build_edition.py --covers.  The page count is read
// from the compiled interior, so recompile domestical-duties-vol-4.pdf
// and re-run before ordering.
//
// The spine uses Lulu's own formula rather than page-count-times-caliper.
// The two agree under about 240 pages and drift apart above it; at 300 pages
// they differ by 0.06in, and the trim tolerance is 0.125in.  VERIFY against a
// downloaded live 6x9 perfect-bound template before ordering.
//
//   front-panel crop for the ebook cover, at 300 dpi:
//     magick -density 300 "cover-vol-4.pdf[0]" -background white \
//       -alpha remove -crop 1800x2700+1959+38 +repage \
//       -resize 900x1350 -quality 92 cover-vol-4-front.jpg
#panel-cover(
  title: [Of Domestical Duties],
  volume: [Volume IV],
  subtitle: [The Seventh and Eighth Treatises: Of Servants and Masters],
  author: [William Gouge],
  pages: 153,
  spine: lulu-spine(153),
  paper: "cream-60",
  trim-width: 6in,
  trim-height: 9in,
  palette: "hearth",
  spine-style: "plain",
  title-size: 26pt,
  back-lead: [The last of the eight treatises, with the exposition of Ephesians 6:5-9 they are raised out of: what a servant owes his master in reverence, obedience and faithfulness, and what a master owes his servants in authority, provision, employment and wages — under the Master they both have in heaven.],
  epigraph: ["Submitting your selves one to another in the fear of God."],
  epigraph-source: [— Ephesians 5:21],
  // Uncomment once the volume has an ISBN; this puts the white field the
  // printer drops the barcode into on the back cover.
  // isbn: "978-0-000000-00-0",
)
