#import "@local/fgbooks:0.5.2": *

// GENERATED BY sources/build_edition.py -- edit edition.json, not this file.
//
// 6x9 rather than the template's 5.5x8.5, and 10.5pt: at 290,000 words the
// whole work is four times the length of anything else in the imprint, and
// the larger trim is what keeps each volume inside a binder's page limit
// while still reading as one column.  The inside margin follows Lulu's
// recommendation for a block this thick.

#show outline: set text(9.5pt)

#show: book.with(
  title: [Of Domestical Duties],
  subtitle: [Volume IV — The Seventh and Eighth Treatises: Of Servants and Masters],
  author: "William Gouge",
  page-width: 6in,
  page-height: 9in,
  page-margin: (bottom: 0.75in, top: 0.75in, outside: 0.75in, inside: 1.0in),
  publishing-info: [
    This copy is provided to you free of charge under the Creative Commons CC0 1.0 Universal license.

    https://creativecommons.org/publicdomain/zero/1.0/

    #image("lcc_standard_pd.png", width: 50%)

    Freely you have received; freely give. - Matthew 10:8b

    To get more free ebooks or at-cost printed copies, visit:

    https://books.freely.giving

    Printed books are at the cost of the printing, no revenue or
    royalty is made from printings so you can get ahold of
    physical prints at the lowest cost possible.

    Set from William Gouge's _Of Domesticall Dvties_ (London, printed by John
    Haviland for William Bladen, 1622), with the spelling modernized. The text
    is the Text Creation Partnership transcription of the first edition
    (EEBO-TCP A68107).

    Book formatted by Courtney Allen Hicks

    #link("mailto:books@lyndnex.com")

    ebook and PDF also available.

    This is volume 4 of four. The complete work is in eight treatises:
    I, an exposition of Ephesians 5:21–6:9; II, of husband and wife; III, of
    wives; IV, of husbands; V, of children; VI, of parents; VII, of servants;
    VIII, of masters.

  ],
  preface: [
    #align(center + horizon)[
      #text(size: 12pt)[
        _Submitting your selves one to another in the fear of God._

        — Ephesians 5:21
      ]
    ]
  ]
)

#set text(font: "Liberation Serif", size: 10.5pt)

#metadata[Servants and Masters in the Apostle’s Words] <short>
#include "chapters/typ/vol-4/01-servants-and-masters-in-the-apostles-words.typ"

#metadata[A Servant’s Reverence for His Master] <short>
#include "chapters/typ/vol-4/02-a-servants-reverence-for-his-master.typ"

#metadata[A Servant’s Obedience to His Master] <short>
#include "chapters/typ/vol-4/03-a-servants-obedience-to-his-master.typ"

#metadata[A Servant’s Faithful and Willing Service] <short>
#include "chapters/typ/vol-4/04-a-servants-faithful-and-willing-service.typ"

#metadata[A Servant’s Duty and Its Limits under God] <short>
#include "chapters/typ/vol-4/05-a-servants-duty-and-its-limits-under-god.typ"

#metadata[A Master’s Authority Rightly Maintained] <short>
#include "chapters/typ/vol-4/06-a-masters-authority-rightly-maintained.typ"

#metadata[A Master’s Correcting and Governing of His Household] <short>
#include "chapters/typ/vol-4/07-a-masters-correcting-and-governing-of-his-household.typ"

#metadata[A Master’s Care for His Servants’ Souls and Bodies] <short>
#include "chapters/typ/vol-4/08-a-masters-care-for-his-servants-souls-and-bodies.typ"

#metadata[A Master’s Employing and Rewarding of His Servants] <short>
#include "chapters/typ/vol-4/09-a-masters-employing-and-rewarding-of-his-servants.typ"

#metadata[A Master’s Own Master in Heaven] <short>
#include "chapters/typ/vol-4/10-a-masters-own-master-in-heaven.typ"

#metadata[Some faults escaped thus to be corrected.] <short>
#include "chapters/typ/vol-4/errata.typ"
