#import "@local/fgbooks:0.5.5": *

// GENERATED BY sources/build_edition.py -- edit edition.json, not this file.
//
// The imprint's 5.5x8.5 trim (the template's), at 10.5pt: at 290,000 words
// the whole work is four times the length of anything else in the imprint,
// and the smaller type keeps each volume a comfortable thickness.  The
// inside margin follows Lulu's recommendation for a block this thick.

#show outline: set text(9.5pt)

#show: book.with(
  title: [Of Domestical Duties],
  subtitle: [Volume II — The Second, Third and Fourth Treatises: Of Husband and Wife],
  author: "William Gouge",
  page-margin: (bottom: 0.6in, top: 0.9in, outside: 0.75in, inside: 1.0in),
  publishing-info: [
    This copy is provided to you free of charge under the Creative Commons CC0 1.0 Universal license.

    https://creativecommons.org/publicdomain/zero/1.0/

    #image("lcc_standard_pd.png", width: 50%)

    Freely you have received; freely give. - Matthew 10:8b

    To get more free ebooks or at-cost printed copies, visit:

    https://books.freely.giving

    Printed books are at the cost of the printing, no revenue or
    royalty is made from printings so you can get ahold of
    physical prints at the lowest cost possible.

    Set from William Gouge's _Of Domesticall Dvties_ (London, printed by John
    Haviland for William Bladen, 1622), with the spelling modernized. The text
    is the Text Creation Partnership transcription of the first edition
    (EEBO-TCP A68107).

    Book formatted by Courtney Allen Hicks

    #link("mailto:books@lyndnex.com")

    ebook and PDF also available.

    This is volume 2 of four. The complete work is in eight treatises:
    I, an exposition of Ephesians 5:21–6:9; II, of husband and wife; III, of
    wives; IV, of husbands; V, of children; VI, of parents; VII, of servants;
    VIII, of masters.

  ],
  preface: [
    #align(center + horizon)[
      #text(size: 12pt)[
        _Submitting your selves one to another in the fear of God._

        — Ephesians 5:21
      ]
    ]
  ]
)

#set text(font: "Liberation Serif", size: 10.5pt)

#metadata[A Parallel of the Duties of Husbands and Wives] <short>
#include "chapters/typ/vol-2/parallel-of-duties.typ"

#metadata[Seeking Marriage] <short>
#include "chapters/typ/vol-2/01-seeking-marriage.typ"

#metadata[Getting Married] <short>
#include "chapters/typ/vol-2/02-getting-married.typ"

#metadata[Marital Unity and Sexual Faithfulness] <short>
#include "chapters/typ/vol-2/03-marital-unity-and-sexual-faithfulness.typ"

#metadata[Living Together in Love] <short>
#include "chapters/typ/vol-2/04-living-together-in-love.typ"

#metadata[Caring for Each Other’s Souls] <short>
#include "chapters/typ/vol-2/05-caring-for-each-others-souls.typ"

#metadata[Guarding Each Other’s Health, Reputation, and Property] <short>
#include "chapters/typ/vol-2/06-guarding-each-others-health-reputation-and-property.typ"

#metadata[Serving Together in Family Ministry] <short>
#include "chapters/typ/vol-2/07-serving-together-in-family-ministry.typ"

#metadata[A Wife’s Respect for Her Husband] <short>
#include "chapters/typ/vol-2/08-a-wifes-respect-for-her-husband.typ"

#metadata[A Wife’s Not Going Against Her Husband’s Will (I)] <short>
#include "chapters/typ/vol-2/09-a-wifes-not-going-against-her-husbands-will-i.typ"

#metadata[A Wife’s Not Going Against Her Husband’s Will (II)] <short>
#include "chapters/typ/vol-2/10-a-wifes-not-going-against-her-husbands-will-ii.typ"

#metadata[A Wife’s Active Obedience to Her Husband] <short>
#include "chapters/typ/vol-2/11-a-wifes-active-obedience-to-her-husband.typ"

#metadata[A Wife’s Submission to Christ First] <short>
#include "chapters/typ/vol-2/12-a-wifes-submission-to-christ-first.typ"

#metadata[A Husband’s Affectionate Authority over His Wife] <short>
#include "chapters/typ/vol-2/13-a-husbands-affectionate-authority-over-his-wife.typ"

#metadata[A Husband’s Humble Gentleness to His Wife] <short>
#include "chapters/typ/vol-2/14-a-husbands-humble-gentleness-to-his-wife.typ"

#metadata[A Husband’s Patient Correcting of His Wife] <short>
#include "chapters/typ/vol-2/15-a-husbands-patient-correcting-of-his-wife.typ"

#metadata[A Husband’s Kind Conduct toward His Wife] <short>
#include "chapters/typ/vol-2/16-a-husbands-kind-conduct-toward-his-wife.typ"

#metadata[A Husband’s Providing for His Wife] <short>
#include "chapters/typ/vol-2/17-a-husbands-providing-for-his-wife.typ"

#metadata[A Husband’s Sincere and Steady Love for His Wife] <short>
#include "chapters/typ/vol-2/18-a-husbands-sincere-and-steady-love-for-his-wife.typ"
