#show align: it => html.elem("div", attrs: (style: "text-align: " + repr(it.alignment)))[#it.body]
#show pagebreak: it => context if target() == "html" { } else { it }

// GENERATED BY sources/build_edition.py -- edit edition.json, not this file.
// The print edition is four volumes; the ebook is deliberately one file, so a
// reader searching for a duty is not searching four books.

#text(size: 24pt, weight: "bold")[Of Domestical Duties]

Eight treatises on the duties of husbands and wives, parents and children,
masters and servants.

This copy is provided to you free of charge under the Creative Commons CC0 1.0 Universal license.

https://creativecommons.org/publicdomain/zero/1.0/

#image("lcc_standard_pd.png", width: 50%)

Freely you have received; freely give. - Matthew 10:8b

To get more free ebooks or at-cost printed copies, visit:

https://books.freely.giving

Printed books are at the cost of the printing, no revenue or
royalty is made from printings so you can get ahold of
physical prints at the lowest cost possible.

Set from William Gouge's _Of Domesticall Dvties_ (London, printed by John
Haviland for William Bladen, 1622), with the spelling modernized. The text
is the Text Creation Partnership transcription of the first edition
(EEBO-TCP A68107).

Book formatted by Courtney Allen Hicks

#link("mailto:books@lyndnex.com")

ebook and PDF also available.

#text(size: 16pt)[_Submitting your selves one to another in the fear of God._ — Ephesians 5:21]


#text(size: 20pt, weight: "bold")[Volume I: The First Treatise: An Exposition of That Part of Scripture Out of Which Domestical Duties Are Raised]

#include "chapters/typ/vol-1/dedication.typ"

#include "chapters/typ/vol-1/01-serving-each-other-in-the-fear-of-the-lord.typ"

#include "chapters/typ/vol-1/02-particular-callings-and-the-wifes-submission.typ"

#include "chapters/typ/vol-1/03-headship-in-marriage-and-the-church.typ"

#include "chapters/typ/vol-1/04-husbands-and-the-love-of-christ.typ"

#include "chapters/typ/vol-1/05-love-that-purifies-the-unclean.typ"

#include "chapters/typ/vol-1/06-redeemed-for-glory.typ"

#include "chapters/typ/vol-1/07-marital-love-and-self-love.typ"

#include "chapters/typ/vol-1/08-christs-union-with-his-beloved-body.typ"

#include "chapters/typ/vol-1/09-the-ancient-law-and-unique-bond-of-marriage.typ"

#include "chapters/typ/vol-1/10-the-mystery-and-practice-of-marriage.typ"

#include "chapters/typ/vol-1/11-the-childs-duties-to-his-parents.typ"

#include "chapters/typ/vol-1/12-the-parents-duty-towards-their-children.typ"

#text(size: 20pt, weight: "bold")[Volume II: The Second, Third and Fourth Treatises: Of Husband and Wife]

#include "chapters/typ/vol-2/parallel-of-duties.typ"

#include "chapters/typ/vol-2/01-seeking-marriage.typ"

#include "chapters/typ/vol-2/02-getting-married.typ"

#include "chapters/typ/vol-2/03-marital-unity-and-sexual-faithfulness.typ"

#include "chapters/typ/vol-2/04-living-together-in-love.typ"

#include "chapters/typ/vol-2/05-caring-for-each-others-souls.typ"

#include "chapters/typ/vol-2/06-guarding-each-others-health-reputation-and-property.typ"

#include "chapters/typ/vol-2/07-serving-together-in-family-ministry.typ"

#include "chapters/typ/vol-2/08-a-wifes-respect-for-her-husband.typ"

#include "chapters/typ/vol-2/09-a-wifes-not-going-against-her-husbands-will-i.typ"

#include "chapters/typ/vol-2/10-a-wifes-not-going-against-her-husbands-will-ii.typ"

#include "chapters/typ/vol-2/11-a-wifes-active-obedience-to-her-husband.typ"

#include "chapters/typ/vol-2/12-a-wifes-submission-to-christ-first.typ"

#include "chapters/typ/vol-2/13-a-husbands-affectionate-authority-over-his-wife.typ"

#include "chapters/typ/vol-2/14-a-husbands-humble-gentleness-to-his-wife.typ"

#include "chapters/typ/vol-2/15-a-husbands-patient-correcting-of-his-wife.typ"

#include "chapters/typ/vol-2/16-a-husbands-kind-conduct-toward-his-wife.typ"

#include "chapters/typ/vol-2/17-a-husbands-providing-for-his-wife.typ"

#include "chapters/typ/vol-2/18-a-husbands-sincere-and-steady-love-for-his-wife.typ"

#text(size: 20pt, weight: "bold")[Volume III: The Fifth and Sixth Treatises: Of Children and Parents]

#include "chapters/typ/vol-3/01-children-showing-respect-for-parents.typ"

#include "chapters/typ/vol-3/02-children-getting-parents-permission.typ"

#include "chapters/typ/vol-3/03-children-obeying-parents-instruction-and-correction.typ"

#include "chapters/typ/vol-3/04-children-giving-back-to-parents.typ"

#include "chapters/typ/vol-3/05-children-honoring-father-and-mother-in-the-lord.typ"

#include "chapters/typ/vol-3/06-parents-loving-praying-and-providing-for-children.typ"

#include "chapters/typ/vol-3/07-parents-nurturing-teaching-and-training-children.typ"

#include "chapters/typ/vol-3/08-parents-admonishing-and-correcting-children.typ"

#include "chapters/typ/vol-3/09-parents-directing-children-into-adulthood.typ"

#include "chapters/typ/vol-3/10-parents-being-faithful-to-all-under-their-care.typ"

#text(size: 20pt, weight: "bold")[Volume IV: The Seventh and Eighth Treatises: Of Servants and Masters]

#include "chapters/typ/vol-4/01-servants-and-masters-in-the-apostles-words.typ"

#include "chapters/typ/vol-4/02-a-servants-reverence-for-his-master.typ"

#include "chapters/typ/vol-4/03-a-servants-obedience-to-his-master.typ"

#include "chapters/typ/vol-4/04-a-servants-faithful-and-willing-service.typ"

#include "chapters/typ/vol-4/05-a-servants-duty-and-its-limits-under-god.typ"

#include "chapters/typ/vol-4/06-a-masters-authority-rightly-maintained.typ"

#include "chapters/typ/vol-4/07-a-masters-correcting-and-governing-of-his-household.typ"

#include "chapters/typ/vol-4/08-a-masters-care-for-his-servants-souls-and-bodies.typ"

#include "chapters/typ/vol-4/09-a-masters-employing-and-rewarding-of-his-servants.typ"

#include "chapters/typ/vol-4/10-a-masters-own-master-in-heaven.typ"

#include "chapters/typ/vol-4/errata.typ"
