== A Servant’s Duty and Its Limits under God

=== §. 35. #emph[Of the meanes to make seruants faithfull.]

Among many other meanes to make seruants faithfull to their master, and carefull to performe other duties sincerely, willingly, cheerefully, and diligently, as hath before beene noted, this is one of the most generall, namely, that #emph[seruants,] in all things they doe for their master, #emph[make their masters case their owne,] and so doe for him as they would for themselues, or as they would haue their owne seruants doe for them. The generall rule of the Law is, #footnote[#emph[Leu.] 19. 18.] #emph[Loue thy neighbour as thy selfe;] and #footnote[#emph[Mat.] 7. 12.] #emph[whatsoeuer you would that men should doe to you, doe you even so to them.] If thus euery man must respect another, yea though he be a stranger, then much more must seruants respect their master, because all that they can doe is after an especiall manner as a debt due to their masters: in which respect Christ saith, that #emph[when they haue done all that is] #footnote[#emph[Luke] 17. 10.] #emph[commanded, they haue but done their dutie.]

This I haue the rather noted, because the practise of most seruants is contrary thereunto. For while they worke for their masters, they will cry out that they are ouer-burdened, and tired with that worke which they will easily goe thorow withall when they worke for themselues. They that while they worke for their master, must be called to it againe and againe, and forced to stand to it, and to hold out till it be done, what paines will they take, how early will they rise, how late will they sit vp, how diligent will they be for themselues? When Iourneymen receiue increase of wages according to the worke which they doe, they will dispatch more then a prentise that hath but cloth, food, and lodging. Againe, many that in their masters goods are very lauish, and wastfull, when they come to befor themselues are very sparing, sauing, and prouident. What doe these things argue but that seruants doe not beare to their masters that minde which they should: they doe not for them as they would doe for themselues. Very requisite it is therefore that the forenamed generall rule be obserued.

#quote(block: true)[Hitherto of the seuerall kindes of seruants duties, and of the manner of performing them. It remaineth to speake both of the extent of their duties, and also of the restraint of that extent.]

=== §. 36. #emph[Of seruants endeuour to make their iudgement agree with their masters.]

The extent of seruants duties is in my text only implied vnder this indefinite particle #emph[(Obey)] (w#super[ch] being not restrained to any particulars, must be extended to #emph[euery thing)] but in other places it is expresly laid downe in these generall termes, #footnote[#emph[Col.] 3. 22.] #emph[Obey in all things,] #footnote[#emph[Tit.] 2. 9.] #emph[Please well in all things.] It is not therefore sufficient that seruants performe their duties well in some things, they must doe it in all things, yea in things that may be against their owne minde and liking, if their master will haue it so. For this end let seruants note these two rules. The same extent and restraint #footnote[Extent of seruants duties.] that was #footnote[Treat. 3. §. 63, #emph[&c.] & Treat. 5. §. 35.] before noted in laying forth the duties of other inferiors, is here also to be obserued in the duties of seruants: for therein they all agree. The same rules therfore that were before set downe, may here againe be applied. I refer the reader to those places for a more large amplification of the generals: and here I will content my selfe with adding such particular proofes as are most proper and pertinent to seruants.

1. That they #emph[labour to bring their iudgement to the bent of their masters iudgement,] and to thinke that meet and good which #footnote[Seruants must labour to bring their iudgement to agree with their masters.] he doth. Thus the #footnote[#emph[Iudg.] 19. 11, 12, #emph[&c.]] seruant of the Leuire which thought it meetest to turne into one of the Cities of the Iebusites to lodge there, because the day was far spent, when he saw his master to be of another minde, yeelded to him. So did #footnote[#emph[Luk.] 19. 25, #emph[&c.]] those seruants yeeld to their master, who at first thought it vnmeet that he that had ten talents should haue one peece more: and #footnote[#emph[Mat.] 13. 28, #emph[&c.]] those seruants also, that at first thought it meet that the tares should be plucked vp from the wheat. This rule is to be obserued in the particular points before deliuered, as the worke which seruants doe, and the manner of doing it, their apparell, their allowance, yea and in the correction which their master giueth them, and the rest.

Contrary is that great conceit which many seruants haue of #footnote[Seruants conceit of their owne wit.] their owne iudgement, wit, and wisdome, thinking themselues wiser then their masters; as #emph[Gehazi,] who opposing his owne wit to his masters wisdome, said, #footnote[2 #emph[King.] 5. 20.] #emph[Behold my master hath spared Naaman this Syrian, in not receiuing at his hands that which he brought: but as the Lord liueth, I will runne after him, and take somewhat of him.] This was also a fault in #footnote[2 #emph[King.] 2. 16.] the children of the Prophets, that would not rest on #emph[Elishas] iudgement, but importuned him against his minde to send some to seeke the bodie of #emph[Eliah.] This selfe-conceit is the cause of many mischiefes: as of discontentednesse at the worke their master appointeth them, and at the allowance of meat and drinke which they haue; of much libertie they take to themselues, of pride in apparell, and other vices before noted: if the forenamed rule were duely obserued, many of those mischiefes would be auoided, and much better obedience yeelded.

=== §. 37. #emph[Of seruants yeelding to doe such things at their masters command, as they cannot thinke to be most meet.]

The second rule which seruants must obserue is this, that

#emph[Though they cannot in their iudgement thinke that fit to be done which their master will haue done, yet vpon his peremptorie command they must yeeld to the doing of it:] It appeareth by #emph[Peters] answer to Christ that he did so, for being commanded to let downe his net for a draught, thus he answereth, #emph[Master, we haue toyled all the night, and haue taken nothing] (here he sheweth that #footnote[#emph[Luke] 5. 5.] his opinion was that it would be in vaine to let downe their nets) #emph[neuerthelesse at thy word I will let downe the net] (here is his obedience against his opinion.) More cleare is the example of #emph[Ioab] for this purpose: when the King commanded him to number the #footnote[2 #emph[Sam.] 24. 2, #emph[&c.]] people, he declared that he thought it a very vnmeet thing to doe, by this phrase, #emph[Why doth my Lord the King delight in this thing?] yet against his iudgement he yeelded to the Kings peremptorie command, for it is said, that #emph[the Kings word preuailed against Ioab.]

#strong[#emph[Obiect.] This is no fit example, because #emph[Ioab] sinned in obeying.]

#emph[Answ. Ioab] cannot iustly be charged with sinne, because it was not simply vnlawfull to number the people. #emph[Dauids] sinne was not in the act of numbring the people, but in his minde which moued him to doe it: for there was no iust cause to doe it: only pride and curiositie moued him, as may be gathered out of his owne reason in these words, #emph[that I may know the number of the people.] To doe such a thing only to know it, was #emph[curiositie.] But why would he know it? surely on a proud conceit that he had so many worthies, so many Captaines, so many men of warre.

Out of #emph[Ioabs] example seruants may here learne in humilitie and reuerence to render some reasons to moue their master not to presse vpon them that which they thinke to be vnmeet; but yet if their master will not hearken to their reasons, but stand vpon his authoritie, #emph[his word must preuaile.]

Contrary is their peremptorinesse, who by no meanes will be drawne to doe any thing at their masters command, which they themselues thinke not most meet to be done. Such an one is that foole whom #emph[Solomon] thus describeth, #emph[Though thou shouldest] #footnote[#emph[Pro.] 27. 22.] #emph[bray a foole in a morter among wheat with a pestle, yet will not his foolishnesse depart from him.] These fooles bring much mischiefe vpon their owne pates in disobeying their masters: for exceedingly they prouoke his wrath who hath power to take vengeance of them. Neither let them thinke to receiue comfort in their suffering, because they refuse an vnmeet thing, for #emph[meetnesse] is not a sufficient warrant against #emph[vnlawfulnesse.] To disobey in a thing which lawfully may be done, is vnlawfull: if therefore the pretext be only an #emph[vnmeet thing,] meetnesse is preferred before lawfulnesse, and vnlawfulnesse lesse accounted of then vnmeetnesse.

=== §. 38. #emph[Of seruants forbearing to obey their master against God.]

That the extent of seruants obedience be not too farre stretched, #footnote[Restraint of the extent of seruants duties] the Apostle setteth downe an excellent limitation thereof: and that in these foure phrases, #emph[As vnto Christ, As the seruants of Christ, Doing the will of God, As to the Lord;] all which doe shew that the #emph[Obedience which seruants yeeld to their master] #footnote[See the cautions, Treat. 3. §. 51, 52, &c.] #emph[must be such as may stand with their obedience to Christ.] So that if masters command their seruants neuer so peremptorily to doe any vnlawfull thing, that is, any thing forbidden by Gods #footnote[#emph[Nolite fieri serui hominum, i. nolite eis parere cùm turpia praecipiunt. Chrys. in] 1 #emph[Cor.] 7. #emph[hom.] 19. #emph[Exo.] 1. 17.] word, they may not yeeld to it. The midwiues of the Hebrew women did well in refusing to doe any thing to helpe forward the murderous practises of the King of Egypt in slaying all the male-children of the Hebrewes: it is expresly said, that #emph[they feared God and did not as the King commanded them:] so as their disobedience in this kinde was a token of their feare of God. In this case #emph[Ioseph] is commended for not hearkening to his mistresse: and the seruants of #emph[Saul] for refusing to slaie the #footnote[#emph[Gen.] 39. 9. 1 #emph[Sam.] 22. 17.] Lords Priests at their masters command. Thus if a master should command his seruant to kill, to steale, to forsweare himselfe, to lie, to vse false measures and weights, to goe to masse, or doe any other vnlawfull thing, he ought not obey him.

Againe, if masters forbid their seruants to doe that which #footnote[Seruis competit vt obediant dominis in ijs quibus mandato Dei nihil derogatur. Basil.] God hath commanded them to doe, they must, notwithstanding their masters prohibition, doe it. The Rulers of Israel forbid the Apostles to preach, yet because Christ had commanded them to preach, they would not forbeare: nor would #emph[Daniel] forbeare to pray to God, though the King and Nobles #footnote[#emph[Ethic. defin.] 75. #emph[Act.] 4. 19. #emph[Dan.] 6. 10.] by expresse decree forbad him. So if a profane or popish master shall forbid his seruant to goe to Church, or to heare the word, or to take the Sacrament, or to dwell with his wife if he be maried, or to make restitution of that which he hath fraudulently gotten, or any other bounden dutie, herein they must say, #emph[we ought to obey God rather then men.] For when masters #footnote[#emph[Act.] 5. 29.] command and forbid any thing against God, they goe beyond their commission, and therein their authoritie ceaseth.

Contrary to this restraint is both a parasiticall pleasing of masters: and also a base feare of them. It is the property of a #footnote[Ais? aio. Negas? nego. Terent. in Eun.] parasite to say what a master will haue him say, and denie what he will haue him denie, and so to doe what he will haue him to doe. #emph[Doeg] that fawning dog at #emph[Sauls] word slew all the Lords #footnote[1 #emph[Sam.] 22. 18.] Priests: and #emph[Absoloms] seruants at his word killed #emph[Amnon:] for #footnote[2 #emph[Sam.] 13. 28, 29.] all the reason which they had to commit that murder was this speech of their master, #emph[haue not I commanded you?] So prone are seruants to sooth their masters, as there is no sinne so horrible which at their masters command they will not be ready to doe. Thus is that verified which the Prophet long since foretold, #footnote[#emph[Isa.] 24 2.] #emph[like master like seruant, like mistresse like maid.] It is also the propertie of base fearefull seruants to doe nothing but what their master will haue them doe, and to forbeare any dutie, though neuer so necessary, that he forbiddeth them to doe. What dutie more necessary then praier? We are commanded to #emph[pray continually:] yet the seruants of #emph[Darius] were content to #footnote[1 #emph[Thess.] 5. 17. #emph[Dan.] 6. 7, #emph[&c.]] forbeare that dutie thirtie daies together, because it was against the decree of their Lord and King. The like is noted of the people in Christs time, #emph[they durst not make open profession of] #footnote[#emph[Ioh.] 7. 13. #emph[&] 9. 22.] #emph[Christ for feare of the Iewes.] So in our daies many seruants there be that dare not make profession of the Gospell, nor goe to Church, nor read the word, nor performe other holy religious duties, which they know to be bounden duties, for feare of their masters. Had not then the Apostle iust cause to strike so much vpon this string as here he hath done, expresly forbidding #emph[eie-seruice, man-pleasing,] and #emph[doing seruice to men,] namely in opposition to God?

=== §. 39. #emph[Of seruants chusing good masters.]

As a iust consequence following from the forenamed extent and restraint of seruants duties, I may further gather these two lessons for seruants.

1. It is very behouefull that seruants make choice of good masters: at least if it be in their power to chuse.

2. It is behouefull that they continue and abide vnder good masters: at least if they continue seruants, and abide vnder any masters.

That these consequences iustly follow as aforesaid, is euident: for seeing seruants are bound to obey in all things which are not #emph[against God,] and must obey in nothing but what is #emph[in the Lord,] it is very requisite that seruants be vnder such masters as beare the Image of God in the inward disposition, and grace of their heart, as well as in their outward function and place: and will goe along with God in vsing their authoritie, commanding nothing but what a seruant may doe with a good conscience, and without transgressing against God: and forbidding nothing that God hath bound a seruant to doe. There will be comfort in seruing such masters: and our obedience to them will be obedience to God. Such masters therefore must be chosen. Yea and with such must seruants abide, (if not with the very same, yet with such as they are, of the same disposition) for if they goe to other, their former comfort will be taken away, and their seruitude will seeme so much the more miserable, by how much more knowledge and experience they haue had of the benefit of their former libertie (for #footnote[Qui fidelem habet dominum, saluo eius dominio, diligat vt patrem.] we may well call seruice vnder vnconscionable masters #emph[seruitude,] and in opposition thereunto, seruice vnder religious masters, #emph[libertie.)] He therefore that hath a master that is faithfull, due respect had to his authoritie, must loue him as a father, and #footnote[#emph[Constit. Apost. l.] 4. #emph[c.] 12.] so abide with him.

For choice of good masters, note what is #footnote[#emph[Exo.] 12. 38.] recorded of many of the Egyptians and other people: they left their owne countrie, and went out with the Israelites: what should moue them but conscience of the true God whom they knew that Israel serued? Now many of these went out as seruants, as may be gathered from those many #footnote[#emph[Leu.] 25. 45. #emph[Deut.] 5. 14. #emph[&] 12. 18. #emph[&] 23. 15. #emph[&] 23. 7.] lawes which were made in the behalfe of seruants that were strangers, and in speciall that were Egyptians. The knowledge which #footnote[#emph[Ruth] 1. 16.] #emph[Ruth] had that #emph[Naomi] her mother in law serued the true God, moued her to leaue her owne countrie, and to goe as a seruant with #emph[Naomi.]

For abiding with good masters we haue a worthy patterne in the twelue Disciples. #footnote[#emph[Ioh.] 6. 66. #emph[&c.]] When many of Christs Disciples at large, #emph[went backe, and walked no more with him,] Christ asking the twelue whether they also would goe away, #emph[Peter] in the name of all the rest answered, #emph[Lord to whom shall we goe? Thou hast the words of eternall life.]

Contrary is the minde and practise of many seruants: they neuer inquire after the religious disposition of their master, nor care though he be popish, or profane, so they may haue good wages, diet and lodging: and yet by this meanes, if at least there be any sparke of Gods feare in their heart, they cast themselues vpon many sore temptations, and bring themselues into many hard straits, and dangerous snares. And, if God open their eies to see that wretched condition whereinto they haue implunged themselues, they will be forced to crie out and complaine as #emph[Dauid] did, when he was in forraine countries where he could not freely serue his God, #footnote[#emph[Psal.] 120. 5.] #emph[Woe is me that I soiourne in Mesech, that I dwell in the tents of Kedar.]

Much more contrary is their minde and disposition who refuse to serue religious masters, and shun them most of all: or being in their seruice are neuer quiet till they be out of it againe. Of these we spake #footnote[§. 16.] before.

#quote(block: true)[Hitherto haue we dealt about seruants duties. The reasons which the Apostle rendreth to enforce those duties remaine to be declared.]

=== §. 40. #emph[Of the first motiue, the place of masters.]

The first reason which the Apostle vseth to inforce seruants #footnote[I.] duties is implied vnder this phrase, #emph[as to Christ;] it intimateth the #emph[place] of a master, which is to be in #emph[Christs stead.] In this respect the title #emph[Lord] is giuen to a master. The word which the Apostle vseth in Greeke is that which in the new testament answereth to that proper Hebrew name of God #emph[Iehouah,] and it setteth forth the absolute soueraignty of God, and power ouer all creatures: #footnote[#emph[Matt.] 28. 18.] which power Because the Father hath giuen to his sonne as Mediator, God-man, he is called the #footnote[1 #emph[Cor.] 8. 6..] #emph[one] or #emph[only Lord:] and because masters by vertue of their office and place beare Christs image, and stand in his stead, by communication of Christs authority to them, they are called #emph[Lords,] yea also #footnote[#emph[Psal.] 82. 6.] #emph[Gods] (for that which a Magistrate is in the Common-wealth a master is in the family)

Hence it followeth that seruants in performing duty to their master performe duty to Christ, and in rebelling against their master they rebell against Christ; as the Lord said to #emph[Samuel] of the peoples reiecting his gouernment, #emph[they haue not reiected] #footnote[1 #emph[Sam.] 8. 7.] #emph[thee, but they haue reiected me that I should not raigne ouer them.] Is not this a strong motiue to prouoke seruants to all duty, and to restraine them from rebellion? if it be well weighed what Christ is, it cannot be but a weighty reason. For though masters should neither reward their good seruice, nor reuenge their ill seruice, yet will Christ doe both.

=== §. 41. #emph[Of the second motiue, the place of seruants.]

The second reason is implied vnder this phrase, #emph[as seruants] #footnote[II.] #emph[of Christ:] it noteth the place of a seruant: which though it may seeme to be a meane and base place, yet is it indeed an honourable place. Men count it an honour to bee seruants to a King: but Christ is higher then all Kings. On this ground the Apostle saith, #emph[Art thou called being a seruant? care not for it:] #footnote[1 #emph[Cor.] 7. 21, 22.] and that vpon this reason, #emph[He that is called in the Lord being a seruant, is the Lords freeman.] This reason is to be noted against the conceit that most haue of a seruants place, that it is so meane and base as there can be no honour nor comfort in doing the duties thereof. But that is a foolish, and vniust conceit: looke to Christ the highest master, and there is as much honour, and comfort in doing the duties of the lowest seruants place, as of the highest masters.

=== §. 42. #emph[Of the third motiue, Gods will.]

The third reason is implied vnder this phrase, #emph[doing the] #footnote[III.] #emph[will of God,] which declareth the ground of seruants subiection. God in his word hath plainly made it knowne that it is his pleasure that they who are vnder the authority of masters should obey them, therefore as seruants would please God, they must obey: if they refuse to obey, they thwart the #emph[will of God.] This also is a motiue of moment: for Gods will is that marke which euery one ought to aime at, and it is much vrged by the Holy Ghost, as a generall reason to all duty in these and such like phrases, #footnote[1 #emph[Thes.] 4. 3.] #emph[This is the will of God,] #footnote[1 #emph[Pet.] 2. 15.] #emph[So is the will of God:] vpon which ground we are exhorted to #footnote[#emph[Ephef.] 5. 17.] #emph[vnderstand,] and to #footnote[#emph[Rom.] 12. 2.] #emph[proue what is the will of God.]

Good reason there is to presse this reason: for

1. Gods will is the very ground of goodnesse: things are therefore good because they are agreeable to Gods will: Gods will giueth the very being to goodnesse.

2. Gods will is a rule to square all our actions by, euen as the kings statutes and proclamations are to his subiects.

3. It is a perfect rule #emph[(the law of the Lord is perfect)] so as we #footnote[#emph[Psal.] 19. 7.] may be sure not to swerue, if we hold close thereunto.

4. It is a sufficient rule, it will giue euery one (and among other, seruants) direction how to carry themselues in euery thing they take in hand, yea in euery thing that appertaineth to them. For, #emph[Gods word is giuen to make vs perfect, thorowly] #footnote[2 #emph[Tim.] 3. 17.] #emph[furnished vnto all good workes.]

5. It is a good warrant to iustifie vs in all our actions: so as, going along with it, we need not care what any man can say against vs. If a man be sure that he haue statute law, or the kings proclamation on his side, he is bold.

From this reason which is of such weight, I gather two propositions to adde force to this motiue.

1. That seruants obey their masters, is no arbitrary matter, but a necessary duty: not left to his will whether he will doe it or no, but a thing whereunto he is bound: and that not only by ciuill constitutions of men, but also by a diuine institution of God: so as it is not only a matter of ciuill policy, but also of conscience, to be done for conscience sake.

2. That no creature can dispence with seruants, so as they should be exempted from doing their duty to their master. If they could, they were greater then God, and their will aboue Gods will. Among creatures, masters themselues are to be reckoned: now because it is Gods will that seruants should be in subiection, their masters cannot exempt them from it. Masters may let them goe free: but retaining them as seruants, they cannot exempt them from a seruants subiection. Wherefore though masters be carelesse in exacting dutie, yet let seruants be conscionable in yeelding duty, because it is Gods will.

=== §. 43. #emph[Of the fourth reason, the reward of good seruice.]

The fourth reason is plainly and largely expressed in these #footnote[IIII.] words, #emph[Knowing that whatsoeuer good thing any man doth, the] #footnote[#emph[Sciat seruus Deum redditurum seruitutis mercedem. Constit. Apost. l.] 4. #emph[c.] 12. #emph[Col.] 3. 24.] #emph[same shall he receiue of the Lord, whether he be bond or free.] The generall summe whereof is a #emph[Declaration of the reward of good seruice.] To which purpose saith the Apostle to seruants in another place, #emph[Of the Lordye shall receiue a reward.]

This first is to be noted to adde force to the former reasons. For if any aske, what if masters stand in Christs stead, what maketh that to the purpose? surely it maketh much to moue seruants: because masters stand in his roome who will reward that which is done for his sake.

If againe they aske, what benefit is it to be Christs seruant? it may be answered, #emph[very great:] for Christ will reward all his seruants.

If further it be asked, what is gotten by doing Gods will?

#emph[Answ.] Euen that which all aime at, reward for seruice.

As this addeth weight to al the other reasons, so is it in it selfe a weighty reason, as weighty as any can be to our corrupt nature. Hope of reward is it which maketh all sorts of people to take the paines which they doe in their seuerall places. But hauing #footnote[Treat. 1. §. 127.] before handled this generall point of reward, I will here more distinctly shew what kinde of reward it is wherewith the Lord will recompence the good seruice of faithfull seruants.

Gods reward is both of temporall and eternall blessings.

The temporall blessings which heretofore God hath bestowed #footnote[What reward God giueth to good seruants.] on faithfull seruants, and which on that ground other like seruants may expect, are these especially.

1. He will moue masters to respect such seruants, as he moued #footnote[#emph[Est.] 6. 3.] #emph[Ahash-verosh] to recompence the fidelity of #emph[Mordecai.]

2. If masters faile therein, he will moue strangers to recompence them: as he moued #footnote[#emph[Gen.] 39. 21.] the Iaylor to fauour #emph[Ioseph] when his master had cast him in prison: and #footnote[#emph[&] 41. 40.] #emph[Pharaoh] to aduance him to great dignity.

3. To draw the hearts of their masters and others the more vnto them, he will make the things which they take in hand to prosper. Thus did he blesse #footnote[#emph[Gen] 39. 2.] #emph[Ioseph,] and #footnote[#emph[&] 24. 56.] #emph[Abrahams] seruant.

4. In dealing for themselues he will blesse their labours, as he blessed #footnote[#emph[Gen.] 30. 43.] #emph[Iaakobs.]

5. He will, when they come to keepe seruants, prouide such seruants for them, as they were to their masters. #footnote[#emph[Gen.] 43. 23.] In Egypt God blessed #emph[Ioseph] with a faithfull seruant. #emph[Dauid,] who #footnote[1 #emph[Sam.] 17. 34.] ventured his life to saue his fathers sheepe, had #footnote[2 #emph[Sam.] 21. 17. #emph[&] 23. 15.] many seruants that ventured their liues for him.

To this purpose may be applied that prouerbe which Christ oft vseth, #footnote[#emph[Luk.] 6. 38.] #emph[with what measure yee mete shall it be measured to you againe.]

The eternall reward is expressed in this phrase, #footnote[#emph[Col.] 3. 24.] #emph[the reward of the inheritance,] for that inheritance is meant which Christ mentioneth in this clause, #footnote[#emph[Mat.] 25. 34.] #emph[Come ye blessed of my Father, inherit the kingdome prepared for you from the beginning of the world,] and Saint #emph[Peter] in this, #footnote[1 #emph[Pet.] 1. 4.] #emph[an inheritance incorruptible, and vndesiled, and that fadeth not away, reserued in heauen.] What can be more said? What shall not be vndergone for this reward? How willingly doe prentises passe ouer their prentiship in hope of a temporarie freedome of an earthly citie? #footnote[#emph[Gen.] 29. 20.] Many yeares seruice were but as a few daies to #emph[Iaakob] because he liked his reward. But behold here a greater reward, which we must needs like much better. If this be not sufficient to moue seruants to all dutie, I know not what can be sufficient.
