== Living Together in Love

=== §. 10. #emph[Of mutuall loue betwixt man and wife.]

Hitherto of those common mutuall duties which tend to the preseruation of the very #emph[being] of mariage, and are in that respect absolutely necessarie. The other common mutuall duties (though they be not of so absolute necessitie as the former) are in their kinde necessary for the good estate of mariage, and for the better preseruing of that knot: so as, if they be not performed, the end and right vse of mariage will be peruerted, & that estate made vncomfortable, & very burdensome. The first of these is #emph[Loue.] A louing mutuall affection must passe betwixt husband and wife, or else no dutie will be well performed: this is the ground of all the rest. In some respects #emph[Loue] is proper and peculiar to an husband, as #footnote[Treat. 4. §. 2.] I purpose to shew when I come to speake of an husbands particular duties. But #emph[Loue] is also required of wiues, and they are commanded to be #emph[louers of their husbands,] as well as husbands #emph[to loue their wiues:] #footnote[#emph[Tit.] 2. 4. #emph[Col.] 3. 19.] so as it is a common mutuall dutie belonging to husband and wife too: and that is true wedlocke, when man and wife are linked together by the bond of loue. Vnder #emph[loue] all other duties #footnote[#emph[Hoc verum est coniugium, quando vinculo charitatis sunt concatenati. Chrys. hom.] 45. #emph[in Gen.]] are comprised: for without it no dutie can be well performed. #footnote[#emph[Rom.] 13. 10.] #emph[Loue is the fulfilling of the Law,] that is, the very life of all those duties which the law requireth. It is the #footnote[#emph[Col.] 3. 14.] #emph[bond of perfection,] which bindeth together all those duties that passe betwixt partie and partie. Where #emph[loue] aboundeth, there all duties will readily and cheerefully be performed. Where #emph[loue] is wanting, there euery duty will either be altogether neglected, or so carelesly performed, that as good not be performed at all: in which respect the Apostle willeth, that #emph[all things be done] #footnote[1 #emph[Cor.] 16. 14.] #emph[in loue. Loue] as it prouoketh the partie in whom it ruleth to doe all the good it can; so it stirreth vp the partie loued to repay good for good. It is like fire, which is not only hot in it selfe, but also conueigheth heat into that which is neere it: whence ariseth a reflection of heat from one to another. Note how admirably this is set forth betwixt Christ and his Spouse in the #emph[Song of Salomon:] and it is further manifested in the examples of all good husbands and wiues noted in the Scripture: they did mutually beare a very louing affection one to another.

Though #emph[loue] be a general duty which euery one oweth to another, #footnote[#emph[Matth.] 5. 44.] euen to his enemie, yet the neerer that God hath linked any together, the more are they bound to this dutie, and the more must they abound therein. But of all others are #footnote[Treat. 1. §. 79, 80.] man and wife most neerely and firmly linked together. Of all others therefore are they most bound hereunto, & that in the highest degree that may be, euen like to #emph[Ionathans] loue, who #emph[loued Dauid] #footnote[1 #emph[Sam.] 18. 1. #emph[Prou.] 18. 22.] #emph[as his owne soule. Salomon] saith, #emph[He that findeth a wife findeth a good thing, and obtaineth fauour of the Lord:] which by the rule of relation is also true of an husband, #emph[Shee that findeth an husband findeth a good thing, and obtaineth fauour of the Lord.] Man and wife therefore are each to other an especiall pledge of Gods fauour, and in this respect aboue all others vnder God to be loued. If this be the ground (as it ought to be) of their mutuall #footnote[That which in #emph[Treat.] 4. §. 2. 9. 11. is spoken of an husbands loue and intire affection, may also be applied in some respects to a wife: and so serue to amplifie this common mutuall dutie of loue.] loue, their loue will be feruent and constant. Neither will the want, or withering of any outward allurements, as beautie, personage, parentage, friends, riches, honours, or the like, with-hold or with-draw, extinguish or extenuate their loue: neither will any excellencies of nature or grace in other husbands and wiues draw their hearts from their owne to those other: nor yet will the loue of a former yoake-fellow dead and gone, any whit lessen the loue of the liuing mate.

This instance I haue the rather mentioned, because in many, #footnote[Loue of after venters to be as intire as of former.] who are farre from setting their affection on strange flesh, their loue of a former husband or wife departed is so fast fixed in their heart, as they can neuer againe so intirely loue any other. They who are so minded are not fit to be ioined with another yoke-fellow after they are loosed from one. If they mary againe, and manifest such a minde, they plainly shew that they respect this or that person more then Gods ordinance. By Gods ordinance man and wife are no longer bound one to another then they liue together. Death is an absolute diremption, and maketh an vtter dissolution of the mariage bond. #emph[If the man] #footnote[#emph[Rom.] 7. 2, 3.] #emph[be dead, the wife is deliuered from the law of the man, so as shee may take another man.] Which liberty is also giuen to the man. Being now free, if they mary another (that other being now a true husband or wife) their loue must be as intire to that other as it was to the former: yea, and more intire, if there were any defect in the former. For as children maried out of their parents house must not retaine such a loue of their parents as shall swallow vp their loue of the partie to whom they are maried, but must according to the law, leaue father and mother, and cleaue to their yoke-fellow: so neither must the loue of a former husband or wife be predominant when they are maried to another. This other must be as close cleaued vnto, as if they had neuer beene ioined to a former. The liuing husband or wife is the present pledge of Gods fauour. He is now thine #emph[owne] husband: and she is now thine #emph[owne] wife: and not the partie that is dead. I denie not but the memorie of a vertuous husband or wife ought to be pretious to the suruiuing partie: for #emph[the memoriall of the iust is blessed.] #footnote[#emph[Prou.] 10. 7.] But as the vertue of a person deceased may not be buried with the dead corps: so neither may the person be kept aboue ground with the memorie of his or her vertue: which after a sort is done, when loue of the partie deceased either taketh away, or extenuateth the loue of the liuing. This is to giue dominion to the dead ouer the liuing: which is more then the law enioyneth.

=== §. 11. #emph[Of husbands and wiues mutuall hatred contrary to loue.]

There is a generation of so crabbed and crooked a disposition #footnote[\* See Treat. 3. § 8. #emph[&] Treat. 4. §. 10.] as they cannot loue, but rather hate one another because they are man and wife: for many husbands hauing wiues, and wiues husbands euery way worthy to be loued, will notwithstanding say to the astonishment of the hearers, #emph[I haue indeed a good husband, or I haue a good wife: but I cannot loue him,] or #emph[I cannot loue her:] and being demanded a reason, sticke not openly and impudently to reply, #emph[I thinke I could loue him if he were not mine husband,] or #emph[I thinke I could loue her if she were not my wife.] O more then monstrous impudencie! Is not this directly to oppose against Gods ordinance, and against that order which he hath set betwixt man and woman? Is it not to trample vnder foot Gods fauour? Though there were nothing else to moue loue but this, that #emph[such an one is thine husband,] or #emph[such an one is thy wife,] yet this should be motiue enough. And shall this be the ground of thine hatred? Assuredly such a spirit is a plaine diabolicall spirit, contrary to that spirit which is from aboue; and if it be not cast out, it will cast those whom it possesseth into the fire of hell.

=== §. 12. #emph[Of mutuall peace betwixt Man and Wife.]

Among other meanes of maintaining an inward louing affection betwixt man and wife, #emph[outward mutuall peace,] concord, and agreement is one of the principall. Whereupon the Apostle exhorteth to #emph[keepe the vnitie of the spirit in the bond of] #footnote[#emph[Ephes.] 4. 3.] #emph[peace:] for peace is a bond that tieth one to another, and maketh them to be as one, euen one in spirit: as on the contrary side outward discord disunites mens spirits. We are enioined to #emph[follow peace with all men:] how much more of all persons ought #footnote[#emph[Heb.] 12. 14.] husbands to haue peace with their wiues, and wiues with their husbands? they are neerer then brothers and sisters. Behold then how good and pleasant a thing it is for them to dwell together in vnity. #footnote[§. 14. #emph[Prou.] 21. 9.] Dwell together they must: but without peace there is no dwelling together: #emph[It is better to dwell in a corner of the house top then with a contentious woman in a wide house.] Persons at variance were farre better be out of sight and place, then present together. Out of sight and place man and wife must not be, at peace therefore #footnote[#emph[Portus est mulier, & maximun securitatis remedium. Si ventis & fluctibus portum liberaueris ex foro reuersus tranquillè viues. Chrys. hom.] 26. #emph[in] 1 #emph[Cor.] 11.] they must be. Mutuall peace betwixt them is a great refreshing to their mindes, being beaten with the discords of others. It is said that a wife is in this respect as an hauen to man (how much more man to his wife?) If the hauen be calme, and free from stormes and tempests, what a refreshing will it be to the Mariner that hath beene tossed in the sea with windes and waues?

For maintaining peace,

1. All offences so much as possibly may be must be auoided. #footnote[Directions for maintaining peace betwixt Man and Wife.] The husband must be watchfull ouer himselfe that he giue no offence to his wife: and so the wife on the other side. Offences cause contentions.

2. When an offence is giuen by the one partie, it must #footnote[1\. Auoid offence.] not be taken by the other; but rather passed by: and then will not peace be broken. The second blow makes #footnote[2\. Take not offence.] the fray. #footnote[3\. Offer reconciliation.]

3. If both be incensed together, the fire is like to be the greater: with the greater speed therefore must they both labour to put it out. Wrath must not lie in bed with two such #footnote[#emph[Eph.] 4. 26.] bed-fellowes: neither may they part beds for wrath sake. That this fire may be the sooner quenched, they must both striue first to offer reconciliation. Theirs is the glory who doe first begin, for they are most properly the #emph[blessed peacemakers.] Not #footnote[#emph[Mat.] 5. 9.] to accept peace when it is offered is more then heathenish: but when wrath is incensed, to seeke atonement is the dutie of a Christian, and a grace that commeth from aboue.

4. Children, seruants, nor any other in the family must be #footnote[4\. Take no part with others.] bolstred vp by the one against the other. The mans partaking with any of the house against his wife, or the wiues against her husband, is an vsuall cause of contention betwixt man and wife.

5. They must forbeare to twit one another in the teeth #footnote[5\. Make not comparisons.] with the husbands or wiues of other persons: or with their owne former husbands or wiues (in case they haue had any before.) Comparisons in this kinde are very odious. They stir vp much passion, and cause great contentions.

6. Aboue all they must take heed of rash and vniust iealousie, #footnote[6\. Be not iealous.] which is the bane of mariage, and greatest cause of discontent that can be giuen betwixt man and wife. Iealous persons are ready to picke quarrels, and to seeke occasions of discord: they will take euery word, looke, action, and motion, in the worse part, and so take offence where none is giuen. When iealousie is once kindled, it is as a flaming fire that can hardly be put out. It maketh the partie whom it possesseth implacable. #footnote[#emph[Pro.] 6. 34, 35.]

7. In all things that may stand with a good conscience they must endeuour to please one another: and either of #footnote[7\. Please one another.] them suffer their owne will to be crossed, rather then discontent to be giuen to the other. Saint #emph[Paul] noteth this as a common #footnote[1 #emph[Cor.] 7. 33, 34.] mutuall dutie belonging to them both, and expresseth their care thereof vnder a word that signifieth more then ordinarie care, and implieth a #emph[diuiding of the minde] into diuers thoughts, casting this way, and that way, and euery way how to giue best content.

=== §. 13. #emph[Of contentions betwixt man and wife.]

Contrary to mutuall peace are #emph[contentions] betwixt man and wife: which are too frequent in most families, and by which #footnote[#emph[Cùm vir & vxor domi dissentiunt, nihilo melius naui iactata domus illa disponitur, cùm gubernator aduersus prorae directo. rem dissentiat. Chrys. loc. citat. Gen.] 13. 8.] the common good is much hindered. Discord betwixt man and wife in an house is as contention betwixt the master and pilot in a ship: may not great danger, and much mischiefe be thence iustly feared? We heard before that man to his wife, and she to him, is as an hauen. Now by experience we finde that if the hauen be tempestuous it is much more troublesome, and dangerous to the Mariner then the wide sea. Wherefore let man and wife be of the same minde one to another as #emph[Abraham] was to #emph[Lot,] and when occasions of discord are offered, say, #emph[Let there be no strife betwixt thee and me, for we are man and wife: no more two, but one flesh.]

=== §. 14. #emph[Of husbands and wiues dwelling together.]

From a mutuall affection of #emph[loue] proceedeth #emph[a mutuall prouident care] in husband and wife one for another. In handling whereof we will first note the #emph[meanes] whereby their mutuall prouidence may be the better effected and manifested, and then the #emph[matter] whereabout it must be conuersant. The meanes in one word is #emph[cohabitation.] For a dutie it is that man and wife dwell together. The phrase vsed in setting out the womans creation (he #emph[built] a woman, whereby the erecting of #footnote[#emph[Vide Musc. in Gen.] 2. 22. See #emph[Treat.] 1. §. 79.] a family is intimated) implieth as much: so doth the law of mariage whereby man is enioyned to #emph[leaue father and mother, and to cleaue vnto his wife,] that is, to goe out of his fathers house, and to dwell with his wife: and so doth this phrase #emph[(forget] #footnote[#emph[Psal.] 45. 10.] #emph[thy fathers house)] taken from the dutie of a wife, and mystically applied to the Church. Saint #emph[Peter] expresly chargeth husbands #footnote[1 #emph[Pet.] 3 7.] to #emph[dwell with their wiues:] and Saint #emph[Paul] layeth it to #footnote[1 #emph[Cor.] 7. 12, 13.] the charge both of husbands and wiues not to leaue one another, but to dwell together, yea though the one be an infidell. Surely it was conscience of this dutie which made the #footnote[#emph[Iudg.] 19. 3.] Leuite to goe after his wife, that went away from him, to bring her home againe: and which made #footnote[#emph[Gen.] 31. 14.] #emph[Iaakobs] wiues to leaue their fathers house, and goe with their husband. #footnote[#emph[coniux.] #emph[vxor.]] The word vnder which Saint #emph[Peter] compriseth this dutie is a title appropriated to an husband: and an answerable title is appropriated to a wife: from which the notation of our two vsuall English words #emph[(husband, housewife)] doth not much differ.

The power which the one hath of the others body, and #footnote[Reasons for cohabitation.] the aduantage which by liuing asunder, they giue vnto #emph[Satan,] (both of which are expresly noted, 1 #emph[Cor.] 7. 4, 5.) doe shew the necessity of this dutie: and the many benefits arising from thence doe further presse the equity of it. By husbands and #footnote[Benefits of cohabitation.] wiues dwelling together all mariage duties are better performed: mutuall loue is better bred, preserued, and increased: the good gifts of either of them are better obserued by the other: better helpe and succour is mutually by each afforded to the other: and in fine they are made more capable of doing good one to another, and of receiuing good one from another. Why then should they haue any minde of liuing asunder, vnlesse they be forced by extraordinary occasions, as captiuity, close imprisonment, contagious sicknesse, and such like, which are no faults of theirs, but crosses to be borne with griefe; and instant praier, together with all other good meanes, to be vsed to bring them together againe? Yea if the imprisonment, banishment, or other like kinde of absence, #footnote[D. #emph[Fulke] against #emph[Rhem.] on 1 #emph[Cor.] 7. §. 6.] be such as one may if they will come at the other, the partie that is free ought to come to the other, if at least that other require it.

=== §. 15. #emph[Of the respects for which man and wife may for a time liue asunder.]

#strong[#emph[Quest.] May there be any iust causes for man and wife willingly to liue asunder?]

#emph[Answ.] There can nor ought to be any cause of vtter relinquishing one another, which is a kinde of #footnote[§. 3.] #emph[desertion:] but for liuing asunder for a time there may be iust causes, as

1. #emph[Weighty and vrgent affaires] which concerne the good of the Church, or commonwealth: as when a man is sent forth to warre, or on an ambassage (in which case though he may take his wife with him, yet is he not necessarily bound there to, especially if the place whither he is sent be farre off, the passage thereto difficult and dangerous, and his abode there not long.) When #footnote[#emph[Numb.] 32. 26, 27.] #emph[Reuben, Gad,] and halfe the tribe of #emph[Manassch] passed ouer Iorden to helpe their brethren in their battels against the Canaanites, they left their wiues behinde them in their families: #footnote[2 #emph[Sam.] 11. 3, 6.] when #emph[Vriah] went to warre, he left his wife at home: and #footnote[#emph[Exo.] 18. 2.] when #emph[Moses] was to bring Israel out of Egypt, his wife remained at her fathers house.

2. #emph[Maine duties of their particular calling:] as of #emph[Mariners,] who are oft to be on the sea: #emph[Merchants] who trade in other countries: #emph[Lawyers] who attend publike places of iustice: #emph[Courtiers,] who in their months, or quarters, attend their Prince: #emph[Keepers] of women in child-bed, and sicke persons: and other #emph[nurses.]

Prouided alwaies that in these, and other like cases, there be #footnote[Absence, 1. not without consent. 1 #emph[Cor.] 7. 5.] a ioynt and mutuall consent of both parties: for if man and wife may not defraud one another for a time to giue themselues to fasting and praier #emph[without consent:] much lesse may they for lighter occasions liue any time asunder without #footnote[2\. Not with delight. #emph[Si vir ad peregrina contenderit, nulla longin. quitas, nulla absentia complacitam minuat charitatem. Ambr. Hexaem. l.] 5. #emph[c.] 7.] consent. Prouided also that they take no delight to liue asunder, but rather be grieued that they are forced so to doe: and in testimony thereof to take all occasions that they can to manifest their longing desire one after another by letters, messages, tokens, and other like kindnesses: and to returne with all the speed they can. No distance, or absence ought any whit to diminish their mutuall loue.

=== §. 16. #emph[Of the errour of Papists about man and wifes separation.] #footnote[#emph[Si quis dixerit Ecclesiam errore cùm ob multas causas separationem inter coniuges quoad thorum, sen cohabitationem, ad certum, incertumue tempus fieri posse decernit, Anathema sit. Concil. Trid.] §. 24. #emph[can.] 8.]

Contrarie to the dutie of #emph[cohabitation] is the doctrine of Papists, whereby they teach, that

#emph[Separation may be made betwixt man and wife for many causes from bed, or cohabitation, for a certaine or vncertaine time.] The Councell of Trent is bold to denounce #emph[Anathema] against such as say, #emph[the Church erreth therein.] If the many causes which they alledge, besides adulterie, be well weighed, we shall finde them without all warrant of Gods word. #footnote[#emph[Bellarm. de Matrim. l.] 1. #emph[c.] 14.] They draw them to two heads, 1. #emph[Mutuall consent.] 2. #emph[Demerit.]

#emph[By consent] (say they) #emph[of both parties maried to attaine a greater and perfecter estate, mariage consummate may be loosed from bed and cohabitation.]

#emph[Answ.] 1. In mariage there is #emph[a couenant of God] (Prou. 2. 17.) as well as of the two parties: the consent therefore of parties is not sufficient to breake it.

2. No estate in this world can be greater or perfecter then is meet for maried persons. #emph[Adam] and #emph[Eue] in their best estate were maried: and now is #emph[mariage honourable in all.] #footnote[#emph[Heb.] 13. 4.]

3. The estates which they count more perfect, are either such as are not in mans power #emph[(as perpetuall continencie)] or such as may be as well performed by maried persons as by single persons (as #emph[Ecclesiasticall functions)] if at least they be such as are warranted by Gods word. High Priests, and other Priests, all sorts of Leuites, extraordinarie Prophets and Apostles were maried. What greater functions then these?

The causes which for #emph[demerit,] they say, make a separation, are 1. #emph[Adulterie.] 2. #emph[Departing from the Catholike faith.] 3. #emph[Soliciting or impelling vnto sinne.]

Concerning #footnote[See §. 5.] #emph[Adulterie,] we denie not, but that it giueth must cause of diuorce: but withall we say (as #footnote[#emph[Matth.] 5. 32.] we haue good warrant from Christs words) that it is the only cause of iust diuorce. For to make a separation for #emph[departing from the Catholike faith,] #footnote[#emph[Fidei gratia vxorem ne eijcias. Chrys. hom.] 19. #emph[in] 1 #emph[Cor.] 7.] is directly contrarie to #emph[S. Pauls] and #emph[S. Peters] doctrine, 1 Cor. 7. 12, 13, 14. 1 Pet. 3. 1.

As for #emph[soliciting and impelling vnto sinne,] though it may be cause to moue an husband or a wife to walke more warily and #footnote[#emph[Si ferus moribus fit coniux, perferat illum vxor, nec vllam ob causam societatem, vinculumque dissoluere patiatur. Basil. Hexaem. bom.] 7. #emph[Matth.] 5. 29.] wisely, and in extremitie to auoid societie for a time, or to complaine to the Magistrate for releefe, who may see it meet to lay the delinquent person in prison, or else otherwise keepe them sunder till that delinquent be reclaimed and brought to a better minde: yet is it no sufficient cause finally to dissolue manage in regard of bed and cohabitation.

They vrge that #emph[if the right eye cause to offend, it must be plucked out.]

#emph[Ans.] 1. That is but a metaphor, and may sundry other wayes be applied.

2. The words are not simply, but by way of comparison to be taken, #emph[rather plucke it out, then to be made to stumble thereby.]

3. #emph[Plucking out,] applied to the point in hand, may be by many other wayes, then by dissoluing mariage.

4. That generall inhibition #emph[(whosoeuer shall put away his wife,] #footnote[#emph[Matth.] 5. 32.] #emph[causeth her to commit adulterie)] restrained only with the exception of fornication, admitteth neither this, nor any other such cause of dissoluing mariage.

=== §. 17. #emph[Of husbands and wiues vnlawfull absenting themselues one from another.]

Contrarie also to the forenamed dutie of #emph[cohabitation,] is the practise of many men, who liuing themselues in one place (suppose at #emph[London)] send their wiues vnto some countrey house, and there euen mew them vp, as Hawkes, neuer caring to come at them, but are then most merrie, when their wiues are farthest off. If their wiues liue at home they will be abroad, mealing and lodging where their wiues shall not know: their owne house is as a prison to them: they are not well, but when they are out of it. Of the like lewd conceit and practife are many wiues, who on no other occasion then meere lightnesse, being eager in pursuing their pleasures, and satisfying their lusts, gad out of their owne houses in the day, lie out of them in the night, and remaine in other company dayes and nights: or at least are glad when their husbands haue occasion to be from home; not vnlike to the light huswife which #emph[Salomon] describeth, #emph[Prou.] 7. 10. &c. I speake of matters too famous, or rather infamous. I would there were no iust cause to taxe this lightnesse. But let such as desire to approue themselues to God or man, take heed of these hainous and more then heathenish vices. #emph[Though Israel play the harlot, yet let not Iudah] #footnote[#emph[Hos.] 4. 15.] #emph[offend.]

Too neere to the forenamed kinde of vnlawfull separation #footnote[Man and wifes fault in parting roomes and beds in the same house.] doe they come, who though they liue both in one house, yet make that house by their estranging themselues one from another as two houses: the man abiding in one end thereof, his wife in another: and so haue their seuerall roomes, seuerall tables, seuerall seruants, all seuerall: Or if the straitnesse of their house will not suffer them so to part other roomes, yet they will haue seuerall bed-chambers, or at least seuerall beds: so as they that shall call them bed-fellowes, shall but nicke-name them. Thus they rob each other of that due beneuolence which they mutually owe one to another, they expose themselues to the deuils snares, they more and more estrange their hearts one from another, and depriue themselues of such mutuall comforts and helpes, as by matrimoniall societie they might afford to, and receiue from one another.
