== Caring for Each Other’s Souls

=== §. 18. #emph[Of husbands and wiues mutuall prayers.]

The #emph[matter] whereabout husbands and wiues mutuall prouidence ought to be conuersant, is in generall the #emph[good] of one another; that each of them doe that for the other, which #emph[Salomon] in particular applieth to a wife, viz. #emph[good and not euill all] #footnote[#emph[Prou.] 31. 12.] #emph[the dayes of their life.] Now the good of man extendeth to his #emph[soule, bodie, good name, and goods.]

A generall dutie tending to the good of all these is #emph[prayer.] #footnote[Prayer a mutuall dutie. 1 #emph[Pet] 3. 7.] #emph[S. Peter] requireth such a cariage of man and wife one towards another, as #emph[their prayers be not hindred:] whereby he taketh it for grant, that prayer is a mutuall dutie which one oweth to the other: which dutie #emph[Isaak] performed for his wife. Herein may #footnote[#emph[Gen.] 25. 21.] man and wife be helpfull each to other in all things needfull to either of them: for it is the meanes which God in wisdome #footnote[#emph[Matth.] 7. 7. #emph[I am.] 5. 16.] hath sanctified for the obtaining of euerie needfull blessing for ourselues or others. By many it is counted but a slight dutie and of small vse; but the truth is, that to performe it aright, in truth and faith, is both difficult in the deed, and powerfull in the effect. It is the best dutie that one can performe for another, and the least to be neglected. We heard before, that #emph[Isaak] prayed for his wife: and to shew the good he did to her thereby, it is noted, that #emph[the Lord was intreated of him:] so as she, being #footnote[#emph[Gen.] 25. 21.] #emph[barren] before, by that meanes #emph[conceiued.] All the physicke in the world could not haue done her so much good. #footnote[#emph[Luke] 18. 1.] #emph[Alwayes] therefore, #footnote[1 #emph[Thess.] 5. 17.] #emph[without ceasing] is this dutie to be performed. Whensoeuer man and wife make any prayer, therein they must be mindfull of one another: yea and oft must they of purpose take occasion to make prayers in speciall one for another: and that both in absence, and also in presence of one another.

This latter doth especially concerne the husband, who is as a Priest vnto his wife, and ought to be her mouth to God when they two are together: yet I doubt not, but that the wife may pray in the husbands presence when they two are alone, either for #emph[triall] (that he may haue knowledge of her abilitie and gift in that kinde) or for #emph[helpe] (if the wife be much better able to performe that duty then the man is, as many wiues are.) Not without cause therefore haue I reckoned this among common mutuall duties.

=== §. 19. #emph[Of the things for which husbands and wiues are to pray alone.]

There are sundry needfull blessings which husbands and wiues are to pray for that appertaine only to themselues, and are most meet to be mentioned in priuate praier betwixt themselues, as

1. That as they two are #emph[one flesh,] so they may be also #emph[one spirit:] that their hearts may be as one, knit together by a true, spirituall, matrimoniall loue: alwayes delighting one in another, euer helpfull one to another, and readie with all willingnesse and cheerefulnesse to performe all those duties which they owe one to another.

2. That their mariage bed may be sanctified: and as it is by Gods ordinance, so it may remaine to them by their well vsing it, #emph[a bed vndefiled.] There is no other thing, for which mutuall prayer in priuate betwixt man and wife is more needfull: and that so much the rather, because of the naturall heat of lust which is in most: which if it be not by prayer (the best meanes for that purpose) asswaged, it may proue a defilement #footnote[#emph[Intemperans in coniugio quid aliud nisi quidam adulter vxoris est? Aug. ex Ambr. contr. Iulian. lib.] 2.] of the vndefiled bed: and man and wife become adulterers one to another. As other things, so this also is #emph[sanctified by the word and praier.] The #emph[word] giueth a warrant and direction for the vse of it: #emph[praier] both seasoneth it, and procureth a blessing vpon it.

3. That they may haue children, and those such as may be heires of saluation, and liue in this world to their owne and others good: that they may be comely and well proportioned children: nor ideots in vnderstanding, nor monsters in bodily shape, nor yet lewd and infamous in their liues: which could not but be a griefe to their parents, and might also open the mouthes of the wicked against them.

4. That God would giue them competencie of this worlds goods, and other good meanes well to nourish, nurture, and place forth their children: and a sufficiencie for the maintenance of their family, and of that estate wherein God setteth them.

5. That such needfull gifts and graces as are wanting in either of them may be wrought: and such vices and infirmities as they are subiect vnto may be redressed.

These and many other like things giue occasion to man and wife in speciall manner to pray one for another, and one with another.

=== §. 20. #emph[Of husbands and wiues hatefull imprecations and wishes one against another.]

Contrary to that holy and heauenly dutie of praier are those direfull and hellish imprecations and execrations, which ordinarily doe passe out of the mouthes of many husbands and wiues against one another (and that many times for very light occasions) cursing the day that euer they knew one another, and wishing that one of them had beene vnder the ground before they came together. Most odious are these and such like execrations in any mans mouth, but more then most odious in the mouth of man and wife against one another.

Many who for outward shame for beare to belch forth such rotten stinking speech, make small conscience of wishing the like in their hearts. If an husband be any whit harsh, and a wife shrewish: or if through sicknesse, or any other like occasion they seeme burdensome each to other: or if any dislike of one arise in the heart of the other: or if their hearts be set vpon others: or if the suruiuor be to carry away the goods and lands, their hearts will be filled with a thousand wishes of one anothers death. Yea, many times such as haue very good husbands or wiues, without any shew of reason (only through an inward corrupton of their heart, and malicious instigation of Satan, not taking notice of their owne good) are ready to wish they were in heauen: making thereby a pretence of their eternall blisse to whom they so wish, whereas indeed their only desire is to be loosed and freed from them. God oft meets with such wicked wishers (whereby he sheweth how hatefull such wishes are to him) for sometimes according to their wish he taketh away good husbands and wiues from those that are euill: and when they are gone he maketh their losse to be so sensibly felt, as those vngodly wishers doe, (as we speake) in euery veine of their heart repent them of their rash wishes. Yea, to aggrauate their wretchednesse the more, he giueth them such crabbed and peruerse husbands and wiues in the roome and stead of those good ones (for seldome comes a better) as they are forced with many deepe sighs and groanes to wish (but all in vaine) their former wiues and husbands #footnote[Quam chara sint carendo intelligunt. Cic. in Orator.] aliue againe, and so to verifie the prouerbe, #emph[A good thing is not so well discerned by enioying, as by wanting it.] Sometimes againe God in anger crosseth their wishes, and first taketh away the wishers of others death: or else prolongeth the life of both to #footnote[Amicitiae quid haberent voluptatis carendo magis intellexi quàm sruendo. Idem in oration. post red.] their greater vexation.

=== §. 21. #emph[Of husbands and wiues neglect of mutuall praier.]

The very neglect of mutuall prayer in husbands and wiues for each other is also a sinne contrary to the forenamed dutie of praier: whereof if all that are guiltie were as well knowne to man as to God, how many vnkinde husbands and wiues carelesse of one anothers good would be noted, more then are? Rare are those husbands and wiues, that haue their seasons to pray alone together one with another, if euer they pray one for another. Though in outward complements they may seeme very kinde, and in the outward things of this world, very prouident, yet if they pray not one for another, they are neither kinde, nor prouident. Heartie, feruent, frequent prayer is the greatest token of kindnesse, and best part of prouidence that can be.

=== §. 22. #emph[Of husbands and wiues mutuall care for one anothers saluation.]

From the generall dutie of #emph[praier] which is profitable to all things, I come to the particular branches of man and wiues #footnote[#emph[Admonendi sunt coniuges vt exhortantes inuicem saluent. Greg. in Past. part.] 3. #emph[Adm.] 28.] mutuall prouident care: and will first begin with that which is first to be sought, #emph[the good of one anothers soule:] which the Apostle intimateth to be a thing to be sought after, where he saith, #footnote[1 #emph[Cor.] 7. 16.] #emph[What knowest thou, ô wife, whether thou shalt] SAVE #emph[thine husband, or what knowest thou, ô man, whether thou shalt] SAVE #emph[thy wife?] #footnote[1 #emph[Pet.] 3. 1.] #emph[S. Peter] enioyneth wiues to doe their endeuour to #emph[win] their husbands: and #footnote[#emph[Epb.] 5. 25.] #emph[S. Paul] setteth before husbands the patterne of Christs loue, which had especiall respect #footnote[Of the particular dutie of husbands in this respect, See Treat. 4. §. 47.] to the soule and the saluation thereof: so as this is a mutuall dutie appertaining to them both, which #emph[S. Peter] further implieth where he stileth them #emph[coheires of the grace of life.]

It is the greatest good that one can possibly doe for another, to be a meanes of helping forward his saluation. And there is #footnote[1 #emph[Pet.] 3. 7..] nothing that can more soundly and firmely knit the heart of one to another, then to be a meanes thereof.

=== §. 23. #emph[Of husbands and wiues care to win one the other, when one of them is not called.]

That the saluation of the soule may be the better effected, respect must be had to the present and particular estate of husband or wife. If one be a #emph[beleeuer] the other not, the beleeuer must vse all the meanes that may be, to draw on the other also to beleeue. If both be beleeuers, their mutuall care must be to edifie one another in thier most holy faith.

For the first, it is the maine drift of #emph[S. Peters] exhortation to #footnote[1 #emph[Pet.] 3. 1.] beleeuing wiues, about their conuersation, to draw on their vnbeleeuing husbands to the true faith. His phrase #emph[(that they] #emph[may be wonne] or gained) as in generall it hath respect to their soules saluation, so in particular to their first conuersion. Now if this dutie appertaine to a wife, much more to an husband, who is appointed an #emph[head] to his wife, and a #emph[Saniour.] To this end doth #emph[S. Paul] aduise beleeuing husbands and wiues that #footnote[#emph[Eph.] 5. 23. 1 #emph[Cor.] 7. 12, 13] are maried to vnbeleeuers, to dwell with them.

For what a wofull thing is it, that two which in this world #footnote[A wofull thing that #emph[one flesh] should be in heauen and hell. #emph[Luk.] 17. 34.] are so neerely linked together as to make #emph[one flesh,] should in the world to come be so farre separated one from another, as heauen is from hell. This indeed shall so fall out in many: for Christ hath expresly foretold it, that of #emph[two] that were #emph[in one] bed together (who are more fitly set forth vnder this phrase then man and wife, who most vsually are stiled bedfellowes?) #emph[one shall be taken] (to mercy and glory) #emph[the other shall be for saken] or left to endlesse and easelesse torture and torment.) But though it be foretold that thus it shall fall out with many a couple, yet our care must be, and that with our vttermost power, #footnote[Meanes of conuersion the best cause of loue.] to preuent it, as in our selues, so in our bedfellow.

If it please the Lord to giue such a blessing to the endeuour of an husband or wife, as to be a meanes of the conuersion of their bedfellow, then will the partie conuerted both intirely loue the other, and also heartily blesse God (as there is iust cause) that euer they were so neerely linked together.

This dutie of winning one another, is to be applied to such as are maried not only to plaine infidels, but also to Papists or other like Idolaters, to Atheists, or any other profane persons, to heretiques, separatists, schismatiques, or any that beleeue not aright.

=== §. 24. #emph[Of husbands and wiues edifying one another.]

The second dutie tending to the #emph[soules saluation] is, that two beleeuers being maried together, they endeuour mutually to build vp one another more and more. #footnote[1 #emph[Thess.] 5. 11] One Christian oweth this dutie to another: much more man and wife. #footnote[#emph[Heb.] 12. 15.] #emph[Take heed] (saith the Apostle) #emph[that no man fall away from the grace of God.] If no man, then nor wife nor husband.

A spirituall edifying of one another is the best vse which #footnote[Spiritual edification a main end of matrimoniall coniunction.] we can make (and ought to make) of those #footnote[#emph[Col.] 2. 19.] #emph[ioynts] and #emph[bonds] whereby we are knit one to another. By vertue of them #footnote[#emph[Eph.] 4. 16.] #emph[the body] (namely the mysticall body of Christ) #emph[receiueth increase to the edifying of it selfe,] and #footnote[#emph[Col.] 2. 19.] #emph[increaseth with the increase of God.] Now the bond of mariage being of all other the firmest, and that whereby we are neerest knit together, by vertue of what bond should we edifie one another, if not by vertue of the #emph[mariage bond?]

=== §. 25. #emph[Of husbands and wiues hindering sinne one in another.]

Two things are requisite vnto spirituall edification.

One respecteth the #emph[hinderances] of growth in grace.

The other the #emph[helpes] thereof.

The #emph[hinderances] of grace are all manner of sinnes. Sinne to grace is as water to fire: it slaketh the heat of it, and if without hoe it be powred on it, it will cleane put it out. In regard hereof there ought to be a mutuall care in husbands and wiues, both to #emph[preuent] sinne before it be committed, and also to make what #emph[redresse] they can after it is committed.

That it is a mutuall dutie for husbands and wiues so much #footnote[Man and wife to preuent sin in one another.] as they can, to preuent sinne one in another is euident, by that reason which the Apostle vseth, to keepe them from defrauding one another, in these words, #emph[that Satan tempt you not.] #footnote[1 #emph[Cor.] 7. 5.] For out of the scope and matter of those words, this generall doctrine may be gathered, #emph[Husbands and wiues ought to be carefull to keepe one another from the temptations of Satan,] that is, from sinne, whereunto all his temptations tend. #footnote[#emph[Gen.] 27. 6, #emph[&c.]] #emph[Rebekah] performed the dutie of a good wife in keeping #emph[Isaak] from blessing #emph[Esau:] which if he had done, he had sinned against #footnote[#emph[Gen.] 25. 23.] Gods expresse word. Though she failed in the manner of doing it, yet her end was good.

As that loue they owe one to another, so that care which they #footnote[By preuenting sinne in each other, they keepe iudgements from themselues.] ought to haue of themselues requireth as much, for sinne prouoketh Gods wrath, his wrath sendeth downe vengeance, that vengeance which falleth on the husband can hardly misse the wife, or that the husband, which falleth on the wife; and that by reason of their neere vnion: though it fall not on both their pates, yet it cannot but much affect, and euen afflict the partie that escapeth. The wiues of those rebells who were #footnote[#emph[Num.] 16. 27, 32] swallowed vp quicke in the wildernesse, perished in like manner with their husbands. For they who are so neere as husbands and wiues, and doe not what they can to preuent one anothers sinnes, make themselues accessary thereto.

For the better effecting of this dutie, husbands and wiues #footnote[Direction for preuenting sinne.] must be watchfull ouer one another, and obserue what sinnes either of them are giuen vnto, or what occasions are offered to draw either of them into sinne. If either of them be cholericke or prone to be angry on a sudden, the other must endeuour to take away all occasions of offence: and if both should be testie and hastie to wrath, when the one seeth the other first moued, the partie whose passion is not yet stirred, ought the rather to be setled and composed to all meeknesse and patience, lest, if both together be prouoked, the whole houshold be set on fire. If either of them be giuen to drunkennesse, couetousnesse, or any other sinne, the other ought by wise and gentle perswasions to keepe them (as much as they can) from those sinnes. Yea they may also get others, that are discreet and able, to disswade them: or vse what other good meanes they can to that purpose.

=== §. 26. #emph[Of husbands and wiues redressing sinne in one another.]

When either husband or wife is fallen into any sinne, a mutuall dutie it is for the other, to vse what redresse may be of that sinne: as if one of them were wounded, the other must take care for the healing of that wound. #emph[Abigail] performed #footnote[1 #emph[Sam.] 25.] her dutie in this kinde, when, after she had heard what churlish entertainment her husband gaue to #emph[Dauids] seruants, she hastened to carry store of prouision to #emph[Dauid,] and humbled her selfe before him, and so moued #emph[Dauid] to asswage his wrath: yea she tooke a seasonable time also to tell her husband his fault, and the danger whereinto he brought himselfe thereby.

More directly, and with better successe did #emph[Iaakob] redresse the superstition, or rather Idolatrie of his wife #emph[Rachel,] as may

be gathered by comparing

+ #emph[Gen.] 31. 19, 34.
+ #emph[Gen.] 35. 2, 4.

A brother at large must not suffer sinne to lie on his brother: #footnote[#emph[Leu.] 19. 17.] much lesse may husband or wife the one vpon the other.

#emph[Thou shalt not hate thy brother] (saith the law) #emph[and suffer] #footnote[It is a branch of hatred to suffer sin to lie on any.] #emph[sinne to lie on him.] To doe this then is a token and fruit of hatred. If an husband should see his wife, or a wife her husband lying in the fire, or water, ready to be burnt or drowned, and not afford their best helpe to pull them out, might they not iustly be thought to hate them? But sinne is as fire and water, which will burne and drowne men in perdition.

This dutie may be performed by meeke instructions, pithy perswasions, gentle reproofes: yea, and by the helpe of some #footnote[#emph[Mat.] 18. 16.] good Minister, or other discreet and faithfull friend.

=== §. 27. #emph[Of husbands and wiues helping forward the growth of grace in each other.]

Hitherto of preuenting, and redressing hinderances of grace. Hereunto must be added an helping forward of the growth thereof: which man and wife must mutually endeuour to effect one in another. The care which #emph[Elkanah] had to carry his #footnote[1 #emph[Sam.] 1. 4. #emph[&c.]] wiues along with himselfe vnto the Tabernacle of the Lord yeere by yeere, sheweth that his desire was to vphold them in the feare of God: yea the gifts and portions, which at that time he vsed to bestow on them, implie the care that he had to encourage them to hold on in seruing the Lord. It was without question the maine end which the Shunamite aimed at in #footnote[2 #emph[King.] 4. 10.] prouiding lodging for the Prophet, that both she and her husband might be built vp in Grace.

This duty may be the better effected by these means following. #footnote[How growth in grace may be helped forward.]

1. By taking notice of the beginning, and least measure of Grace: and approuing the same.

2. By frequent conference about such things as concerne the same: mutually propounding questions one to another thereabouts, and answering the same.

3. By their mutuall practise and example: making themselues each to other a patterne of pietie.

4. By performing exercises of religion, as praying, singing psalmes, reading the word, and the like together.

5. By maintaining holy and religious exercises in the familie. #footnote[#emph[Nemo magister ita persuadere poterit quemadmodum vxor. Chrys. hom.] 19. 1 #emph[Cor.] 7.] Though this dutie especially appertaine to the husband, yet the wife must put her husband in minde thereof, if he forget it; and stirre him vp, if he be backward: Thus did the good Shunamite, 2 #emph[King.] 4. 9, 10. No mans perswasion in this kinde, can so much preuaile with a man as his wiues.

6. By stirring vp one another to goe to the house of God, #footnote[Maritum co adducito vt sanctorum dierum rationem habeat. Greg. Naz. ad Olymp.] to heare the word, partake of the Sacrament, and conscionably performe all the parts of Gods publike worship.

Great need there is, that husbands and wiues should endeuour to helpe forward the growth of grace in each other, because we are all so prone to fall away and wax cold, euen as #footnote[1\. Great need thereof.] water if the fire goe out, and more fewell be not put vnder. #footnote[2\. Husbands and wiues may be very helpfull one to another therein.] And of all other, husbands and wiues may be most helpfull herein, because they can soonest espie the beginning of decay by reason of their neere, and continuall familiaritie together.

=== §. 28. #emph[Of the sinnes of husbands and wiues contrary to a mutuall care of one anothers saluation.]

The vices contrary to that generall mutuall dutie of husbands and wiues in procuring the #emph[Saluation] of one another, and to the particular branches comprised vnder it, are many: As

1. #emph[A carelesse neglect thereof:] when as husbands and wiues #footnote[1\. Care only for temporall things.] so minde earthly things, as they thinke it enough if they be prouident one for another in the things of this life. Hereof most that liue in this earth are guiltie: and among others, euen many of them who haue the name of very good and kinde husbands and wiues. But whatsoeuer the opinion of others be of them, the truth is, that if they faile in this point, they goe no further then the very heathen haue done, and their kindnesse may be as the apes kindnesse, which causeth death.

2. #emph[The vnworthy walking, and vnchristian cariage of a beleeuer] #footnote[2\. Vnworthy walking.] #emph[that is maried to one that beleeueth not:] hereby the vnbeleeuer is kept off from embracing the Gospell, and made the more to dislike and detest it. If a popish or profane husband be maried to a wife that maketh profession of the truth of the Gospell, and she be stout, proud, wanton, waspish, wastefull, or giuen to any other like vices, will he not be ready thereupon to inueigh against the religion she professeth, and vtterly protest against it? So also a popish or profane wife, if she be maried to such an husband.

3. #emph[Negligence in obseruing one anothers disposition or conuersation:] #footnote[3\. Negligence in preuenting sin.] whereby it commeth to passe that they keepe not backe, nor restraine one another from running into any sinne: but proue such husbands and wiues one to another as #emph[Eli] proued a father to his sonnes: whence it fell out, that Gods seuere vengeance fell vpon the necke of the one, and of the other. #emph[Pilats] wife though an heathenish woman, shall rise vp in iudgement against many such wiues, for she did what she could to keepe #footnote[#emph[Mat.] 27. 19.] her husband from shedding innocent bloud.

4. #emph[Acomplement all soothing of one anothers humour,] and seeking #footnote[4\. Man-pleasing.] mutually to please one another in all things, without respect of good or euill. Such as these the Scripture termeth #footnote[#emph[Eph.] 6. 6.] #emph[men-pleasers.] Hence it commeth to passe that husbands and wiues are so farre from drawing one another from sinne, that the better rather yeelds vnto the worse, and both runne into #footnote[#emph[Diabolus saepe sollicitus est subuertere viros per os coniugum. Orig. in Iob. lib.] 2.] euill, as #emph[Adam] was perswaded by his wife to transgresse against Gods expresse charge: and wise #emph[Salomon] was drawne by his wiues vnto Idolatrie, 1 #emph[King.] 11. 4. and #emph[Sapphira] consented to the sacriledge of #emph[Ananias] her husband, #emph[Act.] 5. 2.

5. #emph[An vndue feare of offending one another] by Christian instruction, #footnote[5\. Vndue feare of offence.] admonition, reproofe, and the like. Many who are oft moued in conscience to make knowne to their husbands and wiues the sinnes wherein they liue, and the danger wherein they lie by reason thereof, doe notwithstanding through carelesse and causelesse feare, refraine and forbeare to doe so.

6. #emph[An impious, and enuious disposition,] whereby many husbands #footnote[6\. Scoffing at the signes of grace.] and wiues are moued to mocke, and scoffe at that holy zeale, and forwardnesse which they obserue in their bedfellowes: as #emph[Michal] who resembled #emph[Dauid] to a foole, or #footnote[2 #emph[Sam.] 6. 20.] vaine-fellow, because he manifested his zeale by dancing before the Arke. Thus doe many nip the worke of the spirit in the very bud, and cause grace soone to wither. But cursed be that husband, or wife, that thus peruerteth the maine end of their neere coniunction.
