== Guarding Each Other’s Health, Reputation, and Property

=== §. 29. #emph[Of husbands and wiues mutuall care ouer one anothers body.]

After the good of the soule followeth the good of the body, wherein husband and wife must shew their prouident care each ouer other: and doe what lieth in them to procure the well-fare of one anothers person, and to nourish and cherish one anothers body. This dutie the Apostle layeth down vnder the comparison of a body which he calleth #emph[flesh,] saying, #footnote[#emph[Eph.] 5. 29.] #emph[No man hateth his owne flesh, but nourisheth and cherisheth it:] now man and wife are #footnote[#emph[Eph.] 5. 31.] #emph[one flesh.] This dutie the Apostle in particular applieth to husbands. At the first institution of mariage it was in particular applied to the wife, whom God made to be #footnote[#emph[Gen.] 2. 18.] #emph[an helpe meet for man:] so as it is a mutuall dutie appertaining to both. It seemeth that #footnote[#emph[Gen.] 27. 14.] #emph[Rebecha] was so carefull of #emph[Isaak] in this respect, that she could readily make #emph[sauory meat] for him, #emph[such as he loued.]

This dutie extendeth it selfe to all estates both of prosperity and aduersity, of health and sicknesse: for so much doe they mutually couenant and promise when they are first ioyned together in mariage, #emph[I take thee] (saith each to other) #emph[for better for worse, for richer for poorer, in sicknesse and in health to loue and to cherish.] Wherefore they ought mutually both to reioyce in the well-fare of one another, and also in all distresse to succour and comfort each other, putting their shoulders vnder one anothers burden, and helping to ease one another as much as they can. That which #emph[Salomon] said of a friend and a brother, may fitly be applied in this case to husband and wife, #emph[a friend loueth at all times, and a brother is borne for aduersity,] #footnote[#emph[Pro.] 17. 17.] that is, a trusty and faithfull friend is constant in his goodwill, and ready to performe all duties, of kindnesse at any time, whether it be prosperity or aduersity: the change of outward estate maketh no alteration in his louing affection and friendly cariage: yea he seemeth to be as it were borne and brought forth against the time of trouble and affliction, because then is his prouident care and tender affection most manifested. Of all friends none ought to be more carefull, none more faithfull one to another then man and wife. How then ought they to loue at all times, and if any triall come to either of them, the other so to carrie himselfe, as it may be truly said they were ioyned together for aduersity?

Thus shall they verifie the truth of that whereby God was moued to creare of mankinde male, and female, namely that #emph[it was not good for man to be alone,] but that it was rather good, #footnote[#emph[Gen.] 2. 18.] that is, needfull, profitable, and comfortable for man and woman to be together. In which respect the wise-man saith, #emph[he that findeth a wife findeth a good thing;] and by the rule of #footnote[#emph[Pro.] 18. 22.] relation we may inferre, #emph[she that findeth an husband findeth a good thing.]

=== §. 30. #emph[Of husbands and wiues backwandnesse to helpe one another in time of need.]

Contrary to this duty is a certaine vnnaturall affection in sundry husbands and wiues, who much grudge to prouide the things that are needfull for one another. The man commonly thinkes the charge too great, the woman thinkes the paines too much: they are affected one to another as if they were meere strangers: nay many strangers will be more ready to performe, and more cheerefull in performing needfull duties (as occasion is offered) then such vnnaturall husbands and wiues. If a little sicknesse, or other like crosse fall on one of them, the other thinkes, #emph[neuer any had such a burden;] and by their discontent make the burden much more heauy then otherwise it would be: euen as when two oxen are in one yoke, and the one holdeth backe, the draught is made much harder to the other. Thus doe they peruert one of the principall ends of mariage, which is to be a continuall comfort and #footnote[#emph[Gen.] 2. 18.] #emph[helpe] each to other, and to ease the burdens of one another: in which respect they are made yoke-fellowes. #emph[Iobs] wife by her vnnaturall cariage towards him in his affliction #footnote[#emph[Iob] 2. 9.] did much aggrauate his misery: when he stood in most need of her helpe, she afforded least vnto him: it appeares by #emph[Iobs] complaint of her, in these words, #emph[my breath is strange to] #footnote[#emph[Iob] 19. 17.] #emph[my wife,] that she altogether neglected him in his misery. The common speech of many after their husband or wife hauing long lien sicke is departed, bewrayeth their vnnaturall affection: their speech is this, #emph[if my husband] (or wife) #emph[had died so much sooner I had saued so much mony.] What doth this intimate but that they could haue beene contented their husband (or wife) should haue died sooner that they might haue spared the more.

=== §. 31. #emph[Of Husbands and Wiues mutuall respect of one anothers good name.]

The prouident care of husbands and wiues ought further to extend it selfe to the credit and good name of one another. As deare ought the good name of the wife be vnto the husband, and of the husband to the wife, as their owne. #footnote[#emph[Mat.] 1. 19.] The great regard that #emph[Ioseph] had of the credit of #emph[Marie] his espoused wife, made him thinke of putting her away priuily when he obserued her to be with childe and knew not of whom: for he was not willing #emph[to make her a publike example.] The same respect moued #footnote[2 #emph[Sam.] 11. 5.] #emph[Bethsheba] to send secretly to #emph[Dauid,] and well him that she was with childe. The commendation which he good husband (#footnote[#emph[Pro.] 31. 28. 1. A good name is pretious.] noted by #emph[Salomon)] giueth of his wife being approued by the holy Ghost, sheweth how man and wife ought in that respect to honour each other: and that on good grounds. For

1. A good name is a most pretious thing: #footnote[#emph[Eccl.] 7. 3.] #emph[better then precious ointment,] which giueth a sweet sauour, and #footnote[#emph[Pro.] 22. 1.] to be chosen #emph[loue great riches.] #footnote[2\. The good name of the one is the honour of the other.]

2. So neerely are husbands and wiues ioyned together, the good name of the one cannot but tend to the honour and credit of the other; so that herein they seeke their owne honour also.

=== §. 32. #emph[Of husbands and wiues preuenting each others discredit.]

For direction herein, consider we how this dutie may be #footnote[Directions concerning a good name.] #emph[performed,] and how it may be #emph[manifested.]

For the better performing of it, care must be had both to #emph[preuent] and #emph[redresse an ill name,] and also to #emph[procure] and #emph[preserue a goodname.]

To #emph[preuent an ill name] respect must be had of these three things following, #footnote[1\. Preuent an ill name, and that]

- 1\. What one relateth of another, and how.
- 2\. What eare they giue to things related by others.
- 3\. What censure they giue of one another.

For the #emph[first,] husbands and wiues may in no case delight to #footnote[1\. By concealing things of ill report.] discouer vnto others, and spread abroad the infirmities, and imperfections of one another, or any thing that may tend to the discredit of either of them: but rather couer and conceale them as much as they may with a good conscience. It is expressed that #footnote[#emph[Mat.] 1. 19.] #emph[Ioseph being a iust man] laboured to conceale that blemish which he imagined to be in his wife, so as this may stand with #emph[iustice:] yea also it is a part of #emph[Ioue,] for #footnote[1 #emph[Pet.] 4. 8.] #emph[loue couereth a multitude of sinnes.]

For the #emph[second,] husbands and wiues must not haue their #footnote[2\. By closing eares against ill reports.] eares wide opened to heare euery tale and report that shall be brought to one against the other, but rather shew themselues displeased and offended with them that are ready to relate things of euill report. If an husband or wife manifest a willingnesse to hearken after tales and reports of one another, the deuill will stirre vp instruments enow to fill their heads with tales, and those for the most part both friuolous and forged: not only strangers, but children, seruants, and they which are of the same family will euer be telling some tale or other, to currie fauour, as we speake. But an vtter dislike of such flattering tale-bearers, will take away occasion from them of telling vntrue, or slight reports.

For the #emph[third,] the iudgement and censure which husbands #footnote[3\. By forbearing to censure rashly.] and wiues giue one of another must either be very charitable, or verie sparing. If one heare reported any notorious crime of the other, they may not be ouer-headie or hastie to iudge and condemne, no though they thinke they see some euidence thereof, but rather suspend their iudgement. This seemeth to be the minde of #emph[Ioseph:] though he obserued #emph[Marie] to be with #footnote[#emph[Mat.] 1. 19.] childe, yet would he not presently iudge her to be a notorious adulteresse, or condemne her for an hypocrite, vnworthie to liue, and therefore would not make her a publike example.

In briefe, that husbands and wiues may be the more sparing in censuring one another, they must not rashly beleeue any euill report of one another, but rather suppresse all light suspitions as much as they can.

That the iudgement which they giue one of another, may be charitable, in iudging they must well obserue the properties of loue, which are 1. To interpret doubtfull things in the better part. 2. To mitigate, so farre as truth and iustice will suffer, the faults which are euident. #emph[Michal] offended against #footnote[2 #emph[Sam.] 6. 20.] the first in an high degree, and was cursed. #emph[Abigail] obserued #footnote[1 #emph[Sam.] 25. 25.] the latter, and was blessed.

=== §. 33. #emph[Of the wisdome of husbands and wiues, in redressing one anothers ill name.]

To #emph[redresse an ill name,] husbands and wiues must first giue one another notice of the report that goeth of them, and endeuour #footnote[2\. Redresse an ill name.] to worke in them both a sight, and also a sense of those euils which are in the mouths of others: after notice giuen, they must labour to bring them to repentance of those sinnes, for which they are ill reported of, and to a manifestation of repentance, by doing things meet for repentance, which is by a zealous and conscionable practise of such vettues as are cleane contrarie to the vices for which they were euill spoken of. It may with good probabilitie be gathered out of the historie of the Leuite, whose wife plaid the whore, that thus he #footnote[#emph[Iudg.] 19. 1, 2, #emph[&c.]] dealt with her. And thus #emph[Abigail] endeuoured to deale with her husband. #footnote[1 #emph[Sam.] 25. 37.]

=== §. 34. #emph[Of husbands and wiues care in procuring one anothers good name.]

To #emph[procure a good report,] husbands and wiues must #footnote[3\. Procure a good report.] First, take notice of the good qualities which are in one another, and as one hath occasion to speake of the other, to make those good qualities the subiect of their speech: as we #footnote[l #emph[Pro.] 31. 28, 29.] heard it before commended in the husband of that wife which is described by #emph[Salomon.]

Secondly, they must lend a willing and ioyfull eare to such as shall (so farre as they can conceiue) truly and vnfainedly, without flatterie or hypocrisie, speake any thing in commendation of the one or of the other: not thinking themselues dispraised (which is the conceit of many) when their bed-fellow is praised: but rather hauing their hearts the more enlarged to praise God, for bestowing on them such an excellent token and pledge of his fauour.

Thirdly, they must imitate those good things which they behold, or heare to be in one another, and so imitate them as they which haue before time knowne both husband and wife, may say, this she learned of him, or this he learned of her.

=== §. 35. #emph[Of husbands and wiues wisdome, in preseruing each others good name.]

To #emph[preserue a good name,] it will be meet for an husband or #footnote[4\. Preserue a good name.] wife, wisely and seasonably to giue one another notice of that good fame which is raised of them, thereby to prouoke them both to giue glorie to God for the same (#footnote[#emph[Col.] 1. 3, 4.] as the Apostle thanketh God for that report which was spred abroad of the faith and loue of the Colossians) and also to walke worthie of that good report (as the Apostle who had giuen a great testimony of the bountie of the Corinthians, earnestly exhorteth them to finish their beneuolence, #emph[lest] (saith he) #emph[I should be ashamed in] #footnote[2 #emph[Cor.] 9. 4.] #emph[this my constant boasting.)] For if they of whom there is once a good report raised, decay, wax cold, grow backward, or fall into notorious and scandalous sinnes, they will cleane extinguish and put out their good name among men, and turne it into an euill report, according to that which #emph[Salomon] saith, #emph[Dead flies cause the ointment of the Apothecarie to sendforth a] #footnote[#emph[Eccles.] 10. 1.] #emph[stinking sauour: so doth a little folly him that is in reputation for wisdome and honour.] #footnote[5\. Manifest a care of one anothers good name.]

=== §. 36. #emph[Of husbands and wiues like affection towards one anothers credit.]

In the last place, to manifest a mutuall prouident care of one anothers good name, husbands and wiues must be so affected with the report that goeth of either of them, as if the report were of their owne selues. If the report be good, to be glad thereof, and to reioyce thereat; if it be euill, to be grieued, and after an holy manner vexed at it: thus shall they shew a true sympathie and fellow feeling of one anothers credit, according to that generall rule of the Apostle, #footnote[#emph[Rom.] 12. 15.] #emph[Reioyce with them that reioyce, and weepe with them that weepe.]

=== §. 37. #emph[Of the vices contrarie to that mutuallcare, which man and wife should haue of one anothers credit.]

Vices contrarie to these duties concerning the good name of #footnote[Contrarie vices.] an husband and wife, are in generall two.

One is a readinesse to disgrace and discredit one another, #footnote[1\. To discredit each other, and that] like #emph[Michal] the wife of #emph[Dauid,] of whom we heard before. A hatefull and detestable vice this is, which cannot stand with #footnote[2 #emph[Sam.] 6. 20.] true matrimoniall loue, but rather argueth an vtter dislike, and a plaine hatred of one another.

Husbands and wiues discredit one another, either by procuring an ill name, or hindring a good name.

An ill name in procured by these meanes following.

1. By blazing abroad one anothers infirmities: as when #footnote[1\. By blazing one anothers infirmities abroad.] tatling Gossips meet, their vsuall prate is about their husbands, complaining of some vice or other in them: #emph[My husband,] saith one, #emph[is couetous: I cannot get of him any thing almost: he maketh me goe as no body goeth. And my husband,] replieth another, #emph[is so furious as none can tell how to speake to him:] so one after another goeth on in this tracke, some discouering such infirmities as should be concealed; others (which is worse) plainly belying their husbands. In like manner also husbands when they meet with their boone companions, make their wiues the common subiect of all their talke: one accusing his wife of one vice; another his, of another. There are two respects for which this vice (most detestable in it selfe) is made more odious in an husband or a wife. 1. Because they know more then any other of one anothers infirmities: so as if they be so euilly minded, they may much more discredit one another, then any other can. 2. Because in regard of their neere vnion they are most bound to conceale and couer each others imperfections. #footnote[#emph[Gen.] 9. 22, 25.] #emph[Cam] was cursed for reuealing his fathers nakednesse. but a more horrible curse doe husbands and wiues deserue, that so doe.

2. By opening their eares, and giuing credit to euery light #footnote[2\. By hearing and beleeuing others ill reports.] report that any shall raise. More secret heart-burning of one against the other, and more open quarrels and contentions betwixt them, ordinarily arise from hence then from any other thing.

3. By peruerting and mis-interpreting one anothers actions, #footnote[3\. By turning euerie thing to the worst.] words, yea and thoughts also: taking euery thing in the worst part.

4. By concealing from one another the common euill rumors #footnote[4\. By concealing euill rumors.] which are raised of them, and are in euery mans mouth: of all other, bedfellowes are most fit to disclose such things one to another: and most bound to doe it. Most fit, because of their mutuall familiaritie: most bound, because of their neere vnion.

Many husbands and wiues doe hinder one anothers good #footnote[5\. By enuying and gainesaying good reports.] name by enuying one at the good report that is made of the other, and gainsaying the same: as if the credit of the one must needs turne to the discredit of the other. Thus as water quencheth hot iron, so this enuious disposition is a meanes to extinguish the heat of fame, and to put out the glorious light of a good name. Whereby as they impaire the credit and honour of one another, so they monstrously discredit and dishonour themselues.

The other generall vice in this kinde, is a carelesse regard, #footnote[2\. Neglect of each others fame.] or plaine neglect of one anothers fame: when the husband is no way affected with any report that goeth of his wife, nor the wife with any of the husband: but as if they were meere strangers one to another, they passe by all reports made of one another. What mutuall loue can there be in such? howsoeuer their hands haue beene ioyned together, surely their hearts were neuer vnited, so as it had beene better they had neuer knowne one another, vnlesse the Lord doe afterwards knit their hearts, and vnite their affections more neerely and firmely together.

=== §. 38. #emph[Of husbands and wiues mutuall prouidence about the goods of the family.]

Yet there remaineth one thing more, whereabout husbands #footnote[Treatise 3. §. 29.] and wiues ought to manifest a mutuall prouident care each ouer other: and that is about the goods of this world. Howsoeuer the husband, while he liueth with his wife, hath the truest propertie in them, and the greatest title vnto them, yet I referre this to those mutuall duties which man and wife owe each to other, in three respects.

First, because in conscience they appertaine to the vse of the wife, as well as of the husband.

Secondly, because the wife is by Gods prouidence appointed a ioynt gouernour with the husband of the familie, and in that respect ought to be an helpe in prouiding such a sufficiencie of the goods of this world, as are needfull for that estate wherein God hath set them, and for that charge which God hath committed to them.

Thirdly, because the wife, if she suruiue the husband, ought to haue such a portion of those goods, as are meet for her place and charge.

In these respects we see it requisite, yea a bounden dutie, that husband and wife, euen in a mutuall regard one of another, be as prouident as they can be with a good conscience in getting, keeping, and disposing competent goods and riches for the mutuall good one of another. Concerning the husbands dutie in this respect no question is made: the practise of all good husbands mentioned in Scripture, the care of prouiding for their #footnote[1 #emph[Tim.] 5. 8. See Treat. 4. §. 46.] #emph[owne] enioyned to them, their place and office to be their wiues #emph[head,] with many other like arguments, whereof we shall more distinctly speake, when we come to declare the particular duties of husbands, doe proue as much. The greatest question is concerning the wife, whether she be bound to take any care about the goods. But if the Scripture be thorowly searched, we shall finde proofe enough to shew that euen the also is bound hereunto. For first, the generall end which God aimed at in making the woman (namely to be #footnote[#emph[Gen.] 2. 18.] #emph[an helpe] to man) implieth as much: for herein may she be a verie great helpe, as we shall see by and by in sundry particulars. 2. That generall property attributed to a wife to be #footnote[#emph[Prou.] 18. 22.] #emph[a good thing,] confirmeth as much: for that which is profitable is called good: and it is one respect wherein a wife is termed a #emph[good thing,] that she may by her prouidence and diligence bring much profit to her husband: and therefore in this, among other respects, the good wife which #emph[Salomon] describeth, is said #footnote[#emph[Prou.] 31. 12.] to #emph[doe good] to her husband all the daies of her life: for by her industry and prouidence shee did so preserue and increase his goods, that #footnote[#emph[Vers.] 11.] #emph[the heart of her husband trusted in her, and he had no need of spoile.] If the particular actions whereby that good wife is described be well noted, we may easily obserue that she was an especiall helpe vnto her husband, euen in his outward estate. From all which, we may inferre these two points. First, that this prouident care about outward temporall goods is lawfull, not vnbeseeming a Christian man or woman. Secondly, that it is a mutuall dutie appertaining both to husband and wife.

For the first, how needfull the goods of this world are for preseruation of life and health, estate of the family, good of Church and Common-wealth, releefe of the poore, with the like vses, no man can be ignorant. God hath giuen them as blessings to his children, and that often times in great abundance; and his children haue accordingly beene thankfull for them: so as a prouident care about them is not vnlawfull, but very expedient and needfull.

For the second, If there should not be a ioint care herein, the care and paines of the one might be altogether in vaine. For suppose an husband be industrious, as #footnote[#emph[Gen.] 31. 40.] #emph[Iaakob] was, and get much abroad, if the wife either by her vnthriftinesse, idlenesse, negligence, or the like vices, suffer that which is brought home to be embeaseled and wasted; or by her prodigalitie, brauerie, or loue of vaine companie, consume it her selfe, where will be the profit of the husbands paines? Or on the other side, if a wife should be as painfull and prosperous in getting, as #footnote[#emph[Prou.] 31. 10. #emph[&c.]] the good houswife before mentioned was, and the husband by carding, dicing, drinking, reuelling, or other like meanes should waste all away, what fruit would remaine of the wiues prouidence? In this mutuall prouident care of husband and wife, each of them must haue an eye to their owne place: affaires abroad doe most appertaine to the man, and are especially #footnote[Externa negotia viro permitte. Greg. Naz. ad Olymp.] to be ordered by him: that which the wife is especially to care for, is the businesse of the house: for the Apostle laieth it downe as a rule for wiues (as we shall hereafter more particularly declare) that they #footnote[#emph[Tit.] 2. 5.] #emph[keepe at home,] and #footnote[1 #emph[Tim.] 5. 14.] #emph[gouerne the house.] By this means may they be very profitable each to other.

=== §. 39. #emph[Of the vices contrary to the good prouidence of husband and wife, about the goods of the family.]

Contrary to that dutie, are these vices following.

1. #emph[Couetousnesse,] and ouermuch care for themselues: as #footnote[Contrary vices.] when an husband so raketh, and scrapeth, and hoordeth vp for himselfe, as he neither affordeth vnto his wife so much as is #footnote[1\. Couetousnesse.] meet for her place while he liueth with her, nor thinketh of prouiding sufficient maintenance for her, if shee ouer-liue him, but rather thinketh how to defraud her of that which the law casteth vpon her. Or when a wife secretly hoordeth vp whatsoeuer she can get, either by her owne industry, or else by purloining from her husband: sometimes selling corne, wares, houshold-stuffe, or other like commodities, so priuily as the husband shall neuer know it: sometimes taking money out of his counter, box, bagge, chest, or the like, so as either it shall not be missed, or if it be, it shall not be knowne who had it. Many there be who in mistrust of their husbands prouidence, or in dislike of them, or on some other by-respects, commit whatsoeuer they can get to the trust and custody of others, whereby it oft commeth to passe, that they themselues, meeting with deceitfull friends, are vtterly defeated, euen because they dare not make their fraud knowne. As Couetousnesse is in it selfe an odious sinne; so it is made much more hainous by defrauding husband or wife, who ought to be as deare each to other as themselues.

2. #emph[Prodigalitie,] and too lauish spending vpon themselues, #footnote[2\. Prodigality.] and those things which are most agreeable to their owne corrupt humor: as when husbands without any meane or measure, spend their goods abroad in hunting, hauking, carding, dicing, eating, drinking, or the like, and suffer their wiues to want at home, and yet tooke their wiues to maintaine them, and therefore had their portion. Or when wiues bring their husbands into debt, and weaken, if not cleane ouerthrow their estate, by gorgeous decking and adorning their houses, by braue and costly apparell, by dainty fare, by gossipping abroad, with the like. Many wiues are so violent herein, that if their desire and humour be not satisfied, their husbands shall haue no rest (forsooth they brought a portion, and maintained they must and will be; it skilleth not whether their husbands estate can beare it or no) in so much as many are forced wittingly, for quietnesse sake, to suffer their estate to sinke. O foolish and wretched wiues! how little do they consider that they were maried to doe their husbands good, and not euill all the daies of their life? is this to be an helpe to man? or rather is it not cleane to thwart Gods counsell, and peruert his purpose? can we thinke that God will forbeare, and not be auenged of them? yet much more will God be auenged of the forenamed husbands, because of that image of himselfe which he hath placed in them, and because of that place and authority wherein he hath set them. The Apostle expresly saith of them, that #emph[they are worse then Infidels,] which being so, they must looke for #footnote[1 #emph[Tim.] 5. 8.] the greater iudgement.

3. #emph[Idlenesse,] and a carelesse neglect of their estate. Many #footnote[3\. Idlenesse.] men spend day after day, like a bird that flieth vp and downe, as it falleth out, from tree to tree, from twigge to twigge: they goe from place to place, but know not for what end: as they meet with any company, so they abide as long as the company tarrieth, and then seeke after other company, and are ready to goe with any to Ale-house, Tauerne, Play-house, Bowlingalley, or other like places. Many women also spend all the forenoone in lying a bed and tyring themselues, and the afternoone as occasion is offered in sitting idly at home, or walking forth to little purpose, but only to weare out time, little regarding their husbands estate, whether it increase, or diminish. Thus by the idlenesse and carelesnesse of husband and wife, come faire estates many times to ruine, and both of then brought to penury and beggery.
