== Serving Together in Family Ministry

=== §. 40. #emph[Of husbands and wiues ioint care in gouerning the family.]

Hitherto I haue deliuered such common duties as mutually respect the husband and wife, and are to be performed of each to other. There are other common duties which they are both iointly bound to performe to other persons: and those either #emph[members] of the family, or #emph[strangers] comming to the family.

Concerning the #emph[members] of the family, though there be some peculiar duties belonging to the master, and some to the mistresse, some to the father, and some to the mother, of which we shall speake in their due place; yet in generall the gouernment of the family, and the seuerall members thereof belongeth to the husband and wife both (if at least they haue a family) and a ioint common dutie it is to be helpfull one to another therein.

#emph[Obiect.] Seeing it is not necessarily required, that a husband and wife should haue a family to gouerne, for two may be maried and haue neither children nor seruants (as many are) and yet be true husband and wife; why is this care of a family ranked among the duties of husband and wife?

#emph[Answ.] 1. Because ordinarily when two are maried they gather a family, and are the gouernours thereof: so as though it faile in some particulars, yet for the most part it holdeth.

2. Because the ioint gouernment whereof I speake in this place is by vertue of the mariage-bond: for if a man and a woman should liue together in an house, and by mutuall consent haue a ioint authority and gouernment, this would be very offensiue to all that should know it, or heare of it: neither were they by any ordinance of God bound to be so helpfull one to another as husband and wife: nor the members of a family so bound to subiect themselues to both.

3. The duty whereof I speake, though it be about the gouernment of a family, yet hath it respect to an husband as he is an husband, and to a wife as shee is a wife; namely, that by vertue of their mariage-bond, and neere vnion, they be helpfull one to another in well-ordering the things of the family.

Whether the man ought to look to the good gouernment of his house is a question without all question. He is the highest in the family, and hath both authoritie ouer all, and the charge of all is committed to his charge: he is as a king in his owne house: as a king is to see that land well gouerned where he is king, so he that is the chiefe ruler in an house. The dutie which the Apostle applieth in particular to Bishops & Deacons, in generall appertaineth to all husbands, #footnote[1 #emph[Tim.] 3. 4.] that they #emph[rule their owne house honestly:] and againe, #footnote[#emph[Vers.] 12.] that they be #emph[such as can rule their children well, and their owne housholds.] The care of many husbands is in this respect commended in Scripture, as of #footnote[#emph[Gen.] 18. 19.] #emph[Abram,] of #footnote[#emph[&] 35. 2, #emph[&c.]] #emph[Iaakob,] of #footnote[#emph[Jos ] 4. 15.] #emph[Iosuah,] of #footnote[#emph[Psal.] 101. 2. #emph[&c.]] #emph[Dauid,] the #footnote[#emph[Ioh.] 4 53.] Ruler at Galile, and of many other. That the wife also ought to be an helpe to him therein, is very euident: for the Apostle layeth it expresly to their charge, #footnote[1 #emph[Tim.] 5. 14.] that they #emph[gouerne the house:] would the Wise man haue so highly commended a wife #footnote[#emph[Prou.] 31. 11, #emph[&c.]] for well gouerning her husbands house if it had not appertained to her? It is very likely that wise #emph[Abigail] had a great hand in gouerning #emph[Nabals] house, because the seruants made complaint to her of #emph[Nabals] churlishnesse, and because she had the seruants at command, readily to doe what she would haue them; yea also, because she could so readily prepare such store of prouision for #emph[Dauid] and his men, as she did. Hence is it that the wife is called #footnote[Mater-familias.] #emph[mistresse of the house,] as well as the husband #footnote[Pater-familias.] #emph[master of the house.]

#emph[Obiect.] #footnote[1 #emph[Tim.] 2. 12.] #emph[A woman is not to teach, nor to vsurpe authoritie ouer the man.]

#emph[Answ.] 1. That branch of #emph[teaching] hath respect to publike assemblies, and Churches, in which she may not #emph[teach:] but not to priuate families, in which she may, and ought to #emph[teach:] for #footnote[#emph[Pro.] 31. 4.] #emph[Barthshebah] taught #emph[Salomon.] When #footnote[#emph[Acts] 18. 26.] #emph[Apollos] was brought to the house of #emph[Aquila, Priscilla] the wife of #emph[Aquila] did helpe to expound to #emph[Apollos] the way of God more perfectly.

2. The other branch concerning #emph[authoritie,] hath not reference to the inferiour members in the family, ouer which the wife of an houshold gouernour hath authoritie, but only to the husband, ouer whom if she take any #emph[authoritie,] she vsurpeth it. Therfore neither this place of Scripture, nor any other doth exclude the wife, being iointly considered with the husband, to rule & gouerne those in the family which are vnder them both.

2. #emph[Obiect.] This ioint gouernment of the wife doth much impaire the dignity and authority of the husband.

#emph[Answ.] Nothing lesse: for she is subordinate to her husband, and must so rule others as she be subiect to her husband, and not command any thing against his command, (prouided that his command be not against the Lord, and his word.) We see that in all estates the king or highest gouernour hath other Magistrates vnder him, who haue a command ouer the subiects, and yet thereby the kings supreme authoritie is no whit impaired, but rather the better established, and he the more honoured. So is it in a family. #footnote[1\. #emph[Reason.] Husbands and wiues by their mutuall assistance bring great help one to another. #emph[Plus vident oculi quàm oculus. Arist. Polit. li.] 3. #emph[c.] 7.]

Let therefore husbands and wiues herein assist one another, for so they may be very helpfull one to another, and bring, by their mutuall helpe in gouerning, much good to the family. The husband by his helpe aiding his wife, addeth much authoritie vnto her, and so causeth that she is not despised, nor lightly esteemed. The wife by her helpe causeth many things to be espied, and so redressed, which otherwise might neuer haue beene found out: for two eies see more then one, especially when one of those is more at hand, and in presence, as the #footnote[2\. #emph[Reason.] Many things in a family more fit for the one to meddle with, then for the other.] wife is in the house.

Besides there are many things in well gouerning a family more fit for one to meddle withall then for the other: as for the husband to meddle with the great and weightie affaires of the family (as performing Gods worship, appointing and setling good orders, prouiding conuenient house-roome, and other necessaries for the family: keeping children when they grow #footnote[#emph[In familia dispertita sunt officia: suntque alia viri, alia vxoris propria. Pro▪ sunt ergo vterque alteri sua in commune confe rentes: ob eamque causam suauitas in hac tali amicitia inest, vtilitasque maxima. Arist. Eth. li.] 8. #emph[ca.] 12.] great, or waxe stubborne, in awe: ruling men seruants, with the like) And for the wife to meddle with some lesse, but very needfull matters, as nourishing and instructing children when they are young, adorning the house, ordering the prouision brought into the house, ruling maid seruants, with the like. Yea further, as the man especially is to performe the very actions of prayer, reading the word, catechizing, and other like duties in the family, so the wife may be a great helpe in putting her husband in minde both of the dutie it selfe, and of the time of performing it, and incouraging him to doe it, in gathering the family together, and exhorting them to be forward, in making her selfe an example to the rest by her diligent and reuerend attention, in oft vrging and pressing to her children and seruants such points of instruction as her husband hath taught; yea, in praying, reading, teaching, and performing like exercises her selfe, so farre as she is able, when her husband is absent, or negligent and carelesse, and will not himselfe doe them; or it may be, is not able to doe them: or if she performe them not her selfe, in getting some other to performe them.

=== §. 41. #emph[Of the vices contrary to a ioint care of gouerning the family.]

The minde and practise of many, both husbands and wiues, #footnote[Vices contrary.] is contrary to this dutie.

Many a husband because the wiues office is especially to #footnote[1\. When husbands put off all gouernment to their wiues.] abide at home, will put off all gouernment to the wife: leauing it to her not only to order the things in the house, but also to bring in all needful things, to order and gouerne the children both young and old, yea euen to prouide for them also, to take in, to put out, to vse all sorts of seruants as pleaseth her: yea, if seruants shall be stubborne and stout against her, he will take no notice of it, nor endure to be told of it, much lesse afford her his assistance, but suffer her to be disgraced and despised. As for religious duties, he will no way meddle with them. Oh base minded men, vnworthy to be husbands and heads of wiues! shall your wiues who were made to be an helpe to you, haue no helpe from you, do not in those things which especially belong to your charge? shall the weaker vessels beare all the burden? Assuredly as the man carrieth away the greatest reputation and honour when a family is well gouerned (though it be by the ioynt care and wisdome of his wife) so lieth he most open to the iudgement of God if the gouernment thereof be neglected, and through the neglect thereof, children and seruants grow impious: instance #footnote[1 #emph[Sam.] 3. 12, 13.] #emph[Elie,] and #footnote[2 #emph[Sam.] 15.] #emph[Dauid.] For as in a common-wealth, the greatest honour of good gouernment, victorious battels, happy peace, and prosperity, and the greatest dishonor and dammage of the contrary, redoundeth to the king, so to the man who is chiefe gouernour in a family: for it is presupposed, that all which doe any good are instruments of the highest gouernour: if any euill or mischiefe fall out, that it is through his negligence.

On the other side, because the husband is the most principall, #footnote[2\. When wiues refuse to adde their aide.] many wiues thinke that the gouernment of the family nothing at all appertaines to them, and thereupon are carelesse of the good thereof, and will not stirre their least finger to order any thing aright: but, if any thing be amisse, lay all the blame on their husbands. Doe not such peruert that maine end for which God made them, euen #emph[to be an helpe?] Doe they not carrie themselues most vnworthy of the place wherein God hath set them, namely to be ioynt-gouernours with their husbands, and partakers of their dignities? As by their negligence they make themselues accessary to all the euill which falleth out in the family, so assuredly shall they haue their part in those iudgements which are executed on the head thereof.

Most contrary to the forenamed dutie is the practise of #footnote[3\. When husbands or wiues are hinderances each to other.] such as are hindrances one to another in gouerning the family: as when wiues are not only negligent themselues in comming to religious exercises, but keepe backe children and seruants, and so are a great griefe vnto their religious husbands: or when they vse any of the children or seruants to be instruments of iniquity; or are themselues disquiet and troublesome in the house, like to her of whom #emph[Salomon] speaketh in this prouerbe, #emph[It is better to dwell in the corner of the house] #footnote[#emph[Pro.] 21. 9.] #emph[top, then with a contentious woman in a wide house.]

Husbands also are oft an hinderance to that good gouernment which their wiues would helpe forward, when they scoffe and scorne at that good counsell which their wiues giue them for that purpose, or when they will not suffer their wiues to meddle with any thing at all, nor endure that they should finde any fault, much lesse take in hand to redresse any thing that is amisse. These and such like peruerse dispositions are in husbands and wiues, whereby it commeth to passe that they who were ioyned together to be a mutuall helpe each to other, proue heauy, yea intolerable burdens.

=== §. 42. #emph[Of husbands and wiues mutuall helpe in hospitality.]

The next common duty of husband and wife respecteth such as come to their house, but are no particular members thereof, whether they be kindred, alliance, acquaintance, or strangers, especially if they be Saints, to whom #footnote[#emph[Heb.] 13. 2. #emph[Rom.] 12. 13.] #emph[hospitality,] that is, a kinde and courteous entertainment, is due. Herein therefore must husbands and wiues be helpfull one to another: for as it is required of #footnote[1 #emph[Tim.] 3. 2.] husbands, so also of #footnote[#emph[&] 5. 10.] wiues #emph[to be harborous,] namely while they are maried, together with their husbands, and when they are widowes, of themselues. #footnote[#emph[Gen.] 18 6. #emph[&c.]] #emph[Abraham] and #emph[Sarah] were herein an helpe one to another, when the three Angels in shapes of men came to their house: so were #footnote[2 #emph[King.] 4. 8.] the Shunemite and her husband when #emph[Elisha] the Prophet came to their house.

For hospitality, that it is a commendable dutie belonging #footnote[#emph[Reasons.] 1. Hospitality a commendable dutie.] to such as are house-keepers and able to giue entertainment, is euident by the precepts and examples before specified, as also by the blessing which God thereupon hath brought to the houses of them that were giuen thereunto, which the Apostle intimateth in these words, #footnote[#emph[Heb.] 13. 2.] #emph[thereby some haue entertained Angels vnawares.] Now therfore husbands and wiues being (as we haue heard) ioynt gouernours, as in other things, so in this they ought to lend an helping hand each to other, and that for these reasons.

1. Because in giuing entertainment there are sundry #footnote[2\. The entertainment will be the better by a mutuall helpe.] things to be done, whereof some are proper to the husbands place, and some to the wiues. To take order for the prouision of things without doores is more fit for the husband, #footnote[#emph[Gen.] 18. 7.] #emph[Abraham] did it: to order the smaller things within doores is more fit for the wife; that was left to #footnote[#emph[Vers.] 6.] #emph[Sarah.]

2. Because it is meet that guests should know they are welcome #footnote[3\. Guests will be more cheerefull.] both to the husband and to the wife, that so they may be the more cheerefull.

3. Because a mutuall consent, and cheerefull help herein will #footnote[4\. Mutuall loue will be more firme.] be an especiall means, as to manifest their mutuall affection, so to hold the hearts of man and wife firme and close together, and make them the better like and loue one the other: especially if the husband shall shew himselfe as ready and willing to entertaine his wiues friends and kindred as his owne, and so the wife her husbands (as they ought.) For as they themselues are made one flesh, so ought each of them to esteeme of the others friends as of their owne.

4. Because thus they shew a mutuall desire of bringing #footnote[5\. A desire of one anothers good manifested.] Gods blessing on each other, and vpon their whole family.

=== §. 43. #emph[Of vices contrary to mutuall helpe in hospitality.]

Contrary to this dutie is for the most part couetousnesse in the husband, and lasinesse in the wife. The man, because the charge of the family lieth on him, distrustfully feareth lest he should want for his owne.

I denie not but that a prouident care for our owne, & namely for them of the family, is needfull and commendable, #footnote[1 #emph[Tim.] 5. 8.] #emph[he that prouideth not for them is worse then an infidell:] so as a man may be ouerlauish in giuing entertainment, if he goe beyond his meanes, impouerish his estate, and disable himselfe to prouide for his owne, as many doe: yet when a man hath sufficient, yea and abundance, when there is no iust cause, but meerely vpon an vndue feare too carkingly, and distrustfully to pinch, and grudge to giue entertaiment to any, is vnbeseeming a Christian, yea also to be worse then an infidell; not worthy to haue an house, or any thing fit for entertainment; no nor worthy of common society.

The woman on the other side grudgeth at the paines she must take, and trouble she must vndergoe about entertaining guests, and thereupon is loth that any at any time should come to their house.

Concerning a wife, I denie not but that an husband may be in this kinde ouerburdensome to her, by being too ioueall, as they speake, and bringing guests too often into the house, especially if they be guests of no good name; and by that meanes make her euen weary of her life: but yet for a wife to refuse all paines in that kinde, and to be discontented when her husband inuites any friends, or when any come (as the three Angels did to #emph[Abraham)] vnawares, argueth not a louing affection, nor a wiuelike subiection vnto her husband, to be in her.

These faults are so much the greater when the husband, or wife, are free and forward in entertaining their owne kindred and friends: but are backward, and grudge at the entertainment of each others friends and kindred. Hence commonly ariseth much heart-burning of one against the other: yea much iarre and contention betwixt them: and from dislike of the practise of one another in this kinde oft followeth a dislike of one anothers person: so that as the fault is bad in it selfe, it proues to be much worse in the mischiefes that follow vpon it.

=== §. 44. #emph[Of husbands and wiues mutuall helpe in releeuing the poore.]

The last common and ioynt dutie wherein husband and wife ought to be helpfull each to other, respecteth those that are without the house, namely the #emph[poore,] and such as stand in need of their helpe, who are to be #emph[releeued and succoured.] Because man and wife vsually meale together, and are ioynt partakers of Gods good creatures, they must put one another in minde of that precept of charity which was giuen to the Iewes when they were at their meales, #footnote[#emph[Neh.] 8. 10.] #emph[send part vnto them for whom none is prouided.] The good wife which is set forth by the holy Ghost for a patterne and example vnto others to follow, together with her husband, are noted to be helpfull one to another in this dutie: for she is said #footnote[#emph[Pro.] 31. 20.] #emph[to stretch out her hand to the poore, and to the needy:] and he is said #footnote[#emph[Vers.] 28.] #emph[to praise her,] thereby incouraging her to hold on in doing those good things which she did. What liberty the wife hath, or howfar forth she may be restrained in case her husband vtterly refuse to giue consent, we shall #footnote[#emph[Treat.] 3. §. 23. 33.] hereafter declare in the particular duties of wiues: the point here noted is, that both the husband himselfe must according to his abilitie be bountifull to the poore, and suffer his wife, yea prouoke her so to be, and withall allow her wherewithall to be bountifull: and that the wife also must stirre vp her husband to liberalitie in this respect, and her selfe open her hand to the poore in the things which lawfully she may giue.

There is nothing wherby a man or wife can bring more profit to the house, then by giuing to the poore: that which is giuen to the poore is #footnote[#emph[Prou.] 19. 17.] #emph[lent to the Lord, and he will repay it with great increase:] it is as #footnote[2 #emph[Cor.] 9. 6.] #emph[seed,] which being #emph[liberally sowen,] will bring forth a #emph[plentifull] haruest: yea, it is a meanes to make vs #footnote[#emph[Luke] 16. 9.] #emph[friends,] to speake a good word for vs at the barre of Christs iudgement seat: and it bringeth not only the #footnote[#emph[Iob] 29. 13. & 31. 20.] #emph[blessing of men,] but #footnote[#emph[Matth.] 5. 7.] #emph[of God] also, euen the greatest blessing of all, the #footnote[#emph[Mat.] 25. 34.] blessing of eternall life: for it is #footnote[#emph[Heb.] 13. 16.] #emph[a sacrifice with which God is well pleased.] The Apostle noteth this to be one of Christs oracles, which by word of mouth he left vnto his Disciples, #footnote[#emph[Acts] 20. 35.] #emph[It is more blessed to giue then to receiue.]

Besides, husbands and wiues in distributing almes, may receiue #footnote[2\. Husband and wife in place to giue good direction one to another.] good direction one from another: the husband by telling the wife who are fit to be releeued (for commonly husbands better know those which are abroad out of the family) the wife by telling the husband what things are fittest to be giuen away: for wiues commonly know of what things there is greatest store, and what may in the house be best spared.

=== §. 45. #emph[Of husbands and wiues vnmercifulnesse to the poore.]

Contrarie is the vnmercifulnesse of many husbands, who #footnote[Vices contrarie.] are not only hard-hearted themselues (neuer giuing any thing vnlesse by the law of the land they be forced, & then they part #footnote[1\. Vnmercifulnesse of the husband.] with that which is giuen, so grudgingly, as it is nothing at all acceptable to God (for #footnote[2 #emph[Cor.] 9. 7.] #emph[God loueth a cheerfull giuer)] but also tie their wiues hands, and suffer them to giue nothing. Wherein #footnote[2\. Binding his wiues hands.] they bring both the cry of the poore, and also the groanes and griefe of a mercifull wife who is thus restrained, vpon their owne necks, and aggrauate their sinne in an high degree.

On the other side, the vnmercifulnesse of many wiues is also contrarie to the forenamed dutie: for there are many, who though they haue libertie to giue of the common goods, and also allowance of their owne out of which they may giue, yet couetously hoord vp all they can get, giue not a pennies worth, out rather suffer victuals and other things to perish in the house, and when they are naught to fling them away, then that any thing whilst it is good should be giuen out of the house. Shall not the creatures which are spoiled in an house, and the poore that haue wanted, make a loud crie in the eares #footnote[Read #emph[Iam.] 5. 1, 2. #emph[&c.]] of the Lord against them? Yea further, many wiues are grieued at their husbands bountie, and still mouing him to shut his hand, and giue no more. Are they not plaine deuils herein, opposing against that which is good?
