== A Wife’s Active Obedience to Her Husband

=== §. 43. #emph[Of a wiues actiue Obedience.]

It is a good proofe and triall of a wiues obedience, to abstaine from doing such things as otherwise she would doe, if her husbands contrarie will did not restraine her: but yet that is not sufficient, there must be an actiue, as well as a passiue obedience yeelded. That old Law before mentioned #emph[(thy desire shall be subiect to thine husband, and he shall rule ouer thee)] implieth so much also. If she refuse to doe what he would haue her to doe, her desire is not subiect to him, but to her selfe, neither doth he rule ouer her.

This actiue part of her obedience hath respect

1. To his #emph[commandements,] readily to doe what he lawfully #footnote[A wiues actiue obedience respecteth first her husbands commandement.] commands.

2. To his #emph[reproofes,] carefully to redresse what he iustly blameth.

For the first, so farre ought a wife to be from thinking scorne to be commanded by her husband, that the very knowledge which by any meanes she hath of her husbands minde and will, sought to haue the force of a straight commandement with her. This readinesse to obey is commended in the wiues of #emph[Iaakob,] to whom when #emph[Iaakob] had declared what motiues he had to depart from their fathers house, intimating thereby that he meant to depart, and would haue them to goe with him, yet before he particularly expressed his will, they readily answered, #emph[Whatsoeuer God] #footnote[#emph[Gen.] 31. 16.] #emph[hath said vnto thee, doe:] whereby they gaue him to vnderstand that they were ready to yeeld vnto whatsoeuer he would haue done.

=== §. 44. #emph[Of a wiues willingnesse to] #footnote[Treat. 4. §. 18.] #emph[dwell where her husband will.]

To make this part of a wiues obedience somewhat more cleare, I will exemplifie it by two or three particular instances, recorded and approued in Gods word.

The first is, that #emph[a wife ought to be willing to dwell where her husband will haue her dwell.]

The wiues of #emph[Abraham, Isaak,] and #emph[Iaakob,] herein manifested their wiue-like obedience: though their husbands brought them from their owne countrey, and from their fathers house, yet they refused not to goe with them, but dwelt in a strange countrey, and that in tents.

Note in particular what #emph[Iaakobs] wiues say to their husband in this case, #emph[Is there any portion or inheritance for vs in our fathers] #footnote[#emph[Gen.] 31. 14.] #emph[house?] implying thereby, that seeing it was their husbands pleasure to be gone, they would not any longer tarry in their fathers house, to looke for any more portion or inheritance there.

These examples doe further shew that if an husband haue iust occasion to remoue from one country to another, and in those countries from place to place, his wife ought to yeeld to goe with him, if he require it at her hands. Note what the Apostle saith, #emph[haue we not power to lead about a wife?] That interrogation #footnote[1 #emph[Cor.] 9. 5.] implieth a strong asseueration. The husband then hauing power to lead about a wife from place to place, she ought to submit her selfe to that power. This clause #emph[(as well as other Apostles, and as the brethren of the Lord and Cephas)] sheweth, that this was not only a power which might be vsed, but which was vsed by husbands, and yeelded vnto by wiues.

#strong[#emph[Obiect.] The forenamed examples are extraordinary, and that vpon extraordinary occasions.]

#emph[Answ.] Yet they may be patternes for ordinary occasions which are lawfull and warrantable. Was it not an extraordinary fact of #emph[Eliah] to pray first that there might be no raine, and #footnote[#emph[Iam.] 5. 17.] then againe that there might be raine? yet is this propounded as a generall patterne to moue vs to pray for things lawfull.

Now in laying downe this dutie I added the clause and caueat of #emph[iust occasion,] to meet both with such as vpon discontent, or superstition, leaue the land where the true Gospell is maintained, and preached, and goe into idolatrous places: and also with such wandring giddy heads as only to satisfie their owne humour, and to see fashions, as we speake, can neuer rest in a place, but are continually remouing from countrey to countrey, and from place to place: I thinke (to vse the words of the Apostle) #emph[a wife is not vnder bondage in such cases.] #footnote[1 #emph[Cor.] 7. 15.]

But if a man be sent of an ambassage by his Prince, or countrey: or if a Preacher or Professor be called into another countrey, as #emph[Bucer] and #emph[Peter Martyr] were into England in King #emph[Edwards] daies (which to this day is vsuall in other countries) or if a man be adiudged vnto long imprisonment, and vpon these and other like occasions shall require his wife to be with him, she ought in dutie to yeeld vnto his demand.

Contrary is the minde and practise of many wiues, who #footnote[Contrary, when a wife makes her husband dwell where she will.] being affected and addicted to one place more then another, as to the place where they were bred and brought vp, where their greatest, best, and most friends dwell, and where they haue good acquaintance, refuse to goe and dwell where their husbands calling lieth, though he require, and desire them neuer so much. Thus many husbands are forced to their great dammage for peace sake to yeeld vnto their wiues, and so either to relinquish their calling, or to haue two houses; whence it followeth, that sometimes they must neglect their seruants and calling, and sometimes be absent from their wiues, if not from their children also. Some wiues pretend that they cannot endure the smoake of the citie, other that they cannot endure the aire of the countrie: whereas indeed their owne humour and conceit stuffes them more then either citie smoake or countrie aire. I cannot call such the #emph[daughters of Sarah] herein: #footnote[1 #emph[Pet.] 3. 5, 6.] they are not like those forenamed #emph[holy women that trusted in God, and were subiect to their husbands,] but rather like to that light housewife of the Leuite, who would not dwell in her husbands #footnote[#emph[Iudg.] 19. 2.] house at #emph[mount Ephraim,] but at her fathers house in #emph[Beth-lehem Iudah.] Such wiues as I speake of, in matrimoniall chastitie may be more honest, but in wiuelike subiection are little more dutifull. Let this be taken for a fault, and it will be the sooner amended.

=== §. 45. #emph[Of a wiues] #footnote[Treat. 4. §. 29.] #emph[readinesse to come to her husband when he requires it.]

Another particular instance of a wiues readinesse to yeeld vnto her husbands commandement is, #emph[to come to her husband when her husband requireth it,] either by calling her, or sending for her. The forenamed #footnote[#emph[Gen.] 31. 4.] wiues of #emph[Iaakob] being sent for to their husband in the field where he was, made no excuse, but came presently. So farre ought wiues herein to subiect their wills to their husbands, that though it may seeme to them some disparagement to come, yet if their husbands will haue it so they must yeeld, otherwise they seeme euen to #footnote[#emph[Esth.] 1. 17.] #emph[despise their husbands.]

Contrary is #emph[Vashtie-]like stoutnesse, when wiues thinke and #footnote[Contrary, stoutnesse in refusing to come.] say, it is a seruants part to come when they are called or sent for, and they will neuer yeeld to be their husbands seruants, to come at his command. By the same reason may all duties of subiection be reiected. But for this particular, let such stout #footnote[#emph[Esth.] 1. 16, #emph[&c.]] dames note the issue of #emph[Vashties] stubbornnesse. As many excuses might be alleaged for her as I thinke for any: for First, she was #footnote[#emph[Hebraei docent Vasthiam natam fuisse ex Baltbasare rege Chaldaeorum. Feuard. in Esth.] 1. #emph[Alij, ex Cyro. Merl. in Esth.]] royally descended, being the daughter of a King. Secondly, she was then among the honourable women of the kingdome. Thirdly, the King was in drinke when he sent for her. Fourthly, he sent for her to shew her beautie before multitudes of men, which was not seemely. But all these were not sufficient to excuse her fault, and free her from blame. First, though she were of royall parentage, yet she was a wife, and her husband sent for her. Secondly, being among the noble women of the kingdome, she should the rather haue shewed her selfe a patterne of subiection in this kinde. Thirdly, though he were in drinke, yet remained he an husband: and the thing which he commanded was not such but that she might haue done it without sinne. Fourthly, if she thought the thing vnseemely, she should first haue vsed all the faire meanes she could to haue beene spared; but if by all she could not haue preuailed, then (the thing being not simplie vnlawfull and a sinne) she should haue yeelded.

#strong[#emph[Obiect.] Her fault was not in that as a #emph[wife] she came not to her #emph[husband,] but in that as a #emph[subiect] she came not to her #emph[Soueraigne.]]

#emph[Answ.] Her fault was in both: and in the iudgement passed against her, that former was most vrged, namely that by her #footnote[#emph[Esth.] 1. 17.] example all women might learne to #emph[despise their husbands.]

#strong[2. #emph[Obiect.] Her fact is so censured but by heathen men, that had no vnderstanding of Gods word.]

#emph[Answ.] 1. The holy Scripture by the seuerall circumstances so distinctly noted intimateth that her rebellious fact was a notorious fault: and accordingly both #footnote[Pellican. Lauater. Gualt. Strigel. Cuper. Merlin. Feuard. Bellator. Rupert. Isiodor. Hisp. Raban. alijque Comment. in Esth.] iudicious commenters, and also Preachers doe taxe her of sinfull disobedience to her husband.

2. Though they were heathen, yet they shewed what subiection is required of wiues to their husbands by the very light of nature, whereby this sinne is aggrauated.

3. #emph[Abimelech] was but a heathen man, yet his sentence concerning a womans subiection in these words, #emph[he is to thee a] #footnote[#emph[Gen.] 20. 16.] #emph[couering of the eyes,] is taken to be iudicious, and being approued by the holy Ghost, to be a good proofe. As for that particular of #emph[Uashtie,] why is it so largely recorded in the Scripture but for instruction, and admonition vnto wiues?

=== §. 46. #emph[Of a wiues readinesse to] #footnote[Treat. §. 29.] #emph[doe what her husband requireth.]

A third particular instance of a wiues readinesse to yeeld vnto her husbands commandement, is, #emph[to performe what businesse he requireth of her.] When of a sudden there came three men to #emph[Abram,] and he was desirous to entertaine them, he bid his wife #emph[make readie quickly three measures of meale,] &c. and she #footnote[#emph[Gen.] 18. 6.] did it accordingly. #emph[Ieroboam] hauing a weightie occasion to send to #emph[Ahijah] the Prophet, thought it meet to send by his #footnote[1 #emph[King.] 14. 2, #emph[&c.]] wife, she accordingly (though a Queene) went: she did as her husband would haue her.

Contrary is the humour of many wiues who will not doe #footnote[Contrary, stubbornnesse in refusing to doe a thing vpon command.] any thing vpon command. If such a wiues husband being desirous to entertaine a friend on the sudden, shall vse #emph[Abrams] phrase, #emph[make readie quickly,] &c. she will say, let him come and doe it himselfe, if he will haue it so quickly done, I will not be his drudge: or if, hauing a matter of moment and secrecie, he will his wife her selfe to doe it, she will reply, I am none of your seruants; cannot you put it to one of them, or doe it your selfe? Yet will such wiues be ready to command their husbands to doe euery toy, and if he doe it not, they can reply, is this such a matter? and may not a wife speake to her husband? Were the point of obedience well learned, it would cast such wiues into another mould.

These few particulars may serue for direction in many hundreds. I proceed to the other part of a wiues actiue obedience, which respecteth the reproofes of her husband.

=== §. 47. #emph[Of a wiues] #footnote[Treat. 4. §. 34, 35.] #emph[meeke taking a reproofe.]

The husband hauing authoritie ouer his wife, by vertue thereof he hath power, yea it is his dutie as there is needfull cause to rebuke her: By iust consequence therefore it followeth, #footnote[A wiues actiue obedience to her husbands reproofe. The best triall of obedience.] that it is her dutie to yeeld obedience thereunto. Which ought the rather to be done because the chiefest triall of sound obedience lieth herein. For nothing goeth so much against ones stomach as reproofe: she that yeelds when she is rebuked, will much more when she is intreated. This point of obedience is manifested two waies.

1. By meeknesse in taking a reproofe.

2. By endeuour to redresse what is iustly reproued. The very point of obedience especially consisteth in this latter: the former is as a good preparatiue thereunto, without which it will hardly be done, at least not well done.

Meeknesse in this case is one of the most principall fruits of #footnote[1\. She must meekly take reproofe. 1 #emph[Pet.] 3. 4. #emph[Gen.] 30. 1.] that #emph[meeke and quiet spirit] which #emph[S. Peter] commendeth vnto wiues. Howsoeuer #emph[Rachel] iustly deserued blame for comming in a fuming chafe, and with an imperious command to her husband, yet in that she meekly tooke his sharpe reproofe (for she replied not against it, but meekly gaue a direction for the better accomplishment of her desire) her example is commendable: commendable I say, not in the matter of her direction, but in her patient bearing of reproofe.

Much wisdome may be learned hereby: for when any #footnote[Wisdome learned.] meekly take a reproofe, thereby they suppresse their passion, and keepe it from rising as a cloud before their vnderstanding and darkning it, and so may they better iudge of the matter reproued whether it be iust or no: and whether it need redresse or no: whereof they who are impatient of reproofe, and fret and fume against it, cannot so well iudge. The virgin #emph[Mary] made good vse of Christs reprouing her, and thereby #footnote[#emph[Joh.] 2. 4, 5.] learned and taught a good point of wisdome, namely so to referre our affaires to Christ as we expect his pleasure; and not prescribe time, meanes, manner, or any other like circumstances vnto him.

#strong[#emph[Quest.] What if the husbands reproofe be bitter? #footnote[#emph[Suadeo mulieribus vt viros etiam asperiores perserant. Chrys. hom.] 26. #emph[in] 1. #emph[Cor.] 11.]]

#emph[Answ.] He therein forgets his place, yet thereupon she must not forget her duty. If #emph[Iaakobs] reproofe be well noted, we shall finde it very tart, for it is expresly said that #emph[his anger was kindled against her,] (Gen. 30. 2.) so as he spake in anger: the manner and forme of his words being with an interrogation, and the #footnote[Excandescenti marito cede, & molli oratione iuva. Greg. Naz. ad Olymp.] matter also, #emph[am I in Gods stead,] &c. declare #emph[tartnesse:] yet (as was declared before) she shewed #emph[meeknese.]

#strong[#emph[Quest.] What if his reproofe be vniust?]

2. #emph[Answ.] Yet may not #emph[meeknesse] be forgotten. In such a case a wife may make a iust apologie to cleare her owne innocencie, and manifest her husbands error: but if he refuse to heare her, or will not beleeue her, then (as #emph[S. Peter] speaketh in another #footnote[1 #emph[Pet.] 2. 19, 20.] case) she must #emph[endure griefe for conscience toward God.]

The two reasons which there he rendreth in that other case may not vnfitly be applied to this.

1. In generall this is #emph[thank-worthy,] it is a grace, a glory to her: a matter that deserueth praise and commendation.

2. In particular it is #emph[acceptable to God:] howsoeuer their husbands may deale roughly and vntowardly with them, yet God will graciously respect them, if they shall patiently in obedience to his ordinance beare their husbands vniust reproofes.

3. I may adde this reason also, that thus they shall shew themselues good Christians indeed, in that #emph[they are not ouercome] #footnote[#emph[Rom.] 12. 21.] #emph[of euill.]

Contrary is their minde who by no meanes will brooke a rebuke at their husbands hands: it skills not whether it be iust or vniust: if their husbands reproue them, they shall be sure to haue the reproofe rebounded backe againe vpon their faces, and that with greater violence then euer it came from them. There be some that seeme to be very good wiues till they be tried by the touch-stone of reproofe: but then though the reproofe be for matter most iust, for manner most milde, and that in priuate betwixt their husbands and themselues, yet they grow so impatient, or rather mad, as they forbeare not to giue their husbands the most scornfull speeches that they can inuent, vsing withall bitter imprecations and execrations, and threaten to drowne or hang themselues if they be crossed of their wills. Yea further, if wise husbands shall forbeare them in their passion, and after it is allaied tell them how vnbeseeming their places they carried themselues, they will seeke to iustifie themselues, and lay all the blame on their husbands for crossing them in their will: or if they cannot but see their fault, yet they will only say, it is my infirmitie: but yet euer continue in that infirmitie: and though they make shew of fearing God, yet labour not to purge this corrupt humour out of their hearts. Hence is it for the most part that contentions arise betwixt man and wife. If wiues would learne in this point to be subiect, many iarres, which from time to time arise betwixt them, would be allaied, if not preuented. #emph[Michal] #footnote[2 #emph[Sam.] 6. 20, #emph[&c. Iob] 2. 10.] the wife of #emph[Dauid,] and #emph[Iobs] wife (though they gaue iust occasion to be most sharply reproued, yet) shall rise vp in iudgement against these wiues, because they were silent after they were reproued, and replied not. #emph[Salomon] oft titles such as cannot beare rebuke #emph[scorners:] so as hereby wiues shew that #footnote[#emph[Prou] 9. 7, 8.] they are very scornfull.

=== §. 48. #emph[Of a wiues] #footnote[Treat. 4. §. 35.] #emph[readinesse to redresse what her husband iustly reproueth in her.]

A further degree of obedience in bearing reproofe is, that #footnote[2 She must redresse what is iustly reproued.] #emph[a wife readily redresse what is iustly reproued by her husband:] I say #emph[iustly,] because where no fault is, there needs no amendment: patience may be needfull (as was before shewed) but no repentance of that which is not amisse. But where any thing is amisse, there must be a redresse. #emph[Rachel] did amisse in #footnote[#emph[Gen.] 31. 19.] bringing Idols into her husbands house: her husband in #footnote[#emph[&] 35. 2, 4.] bidding her among others to #emph[put away their strange gods,] reproued them all. Whereupon she with all the rest #emph[gaue to him all their strange gods.] This was a good redresse.

A reproofe may be iustly giuen either for a good dutie omitted; or for an euill thing committed: and accordingly must the redresse or amendment be. A dutie formerly omitted must after the reproofe be more carefully obserued and performed, if it be a continuall dutie, and may be againe performed: otherwise the redresse is a testification of true sorrow for that fault. When an euill is committed, if any meanes can be vsed to make vp the hurt, and redresse the mischiefe that followed thereupon, it must be done: if not, sorrow as before, must be testified, and care taken that the same, or the like be not committed againe.

As a good conscience requireth as much of all Christians by whomsoeuer they be reproued, so the respect which a wife oweth to an husband doth after an especiall manner require it. Otherwise her fault is doubled, 1. by continuance in her sin;

2. by disobedience to her husband.

Contrary is their spirit who for reproofe waxe the worse: #footnote[Contrary, to be worse for reprouing. #emph[Prou.] 9. 8.] being like those #emph[scorners] (of whom #emph[Salomon] speaketh) that #emph[hate those that reproue them.] It is the speech of some wiues, that if their husbands would let them alone they would doe the better: but vpon rebuke they will neuer amend: the more their husbands finde fault, the more will they goe on, in doing what they doe. What other iudgement can be giuen of such, then that which the wise man giueth, #emph[there is more hope] #footnote[#emph[Prou.] 26. 12.] #emph[of a foole then of them.]

=== §. 49. #emph[Of a wiues] #footnote[Treat. 4. §. 50] #emph[contentment with her husbands present estate.] Of submission hitherto.

#emph[Contentment] is also a part of #emph[obedience:] it hath respect to a mans outward estate and abilitie, in and with which a wife must rest satisfied and contented, whether it be high or low, great or meane, wealthy or needy, aboue, equall, or vnder that estate wherein she was before mariage: yea though a man haue beene sometimes great in estate, yet, if he decay therein, and be brought to a meane estate, she ought to rest content. Thus much #emph[Iob] implieth in his replie to his wife, saying, #emph[shall we receiue] #footnote[#emph[Job] 2. 10. expounded.] #emph[good at the hand of God, and not receiue euill?] The euill he speaketh of was the losse of his goods, seruants, and children, together with other miseries that Satan through Gods permission inflicted vpon him: the #emph[receiuing of euill] which he speaketh of was a resting content with it, and a patient bearing of it. Euill may be laid on any, and so they forced to beare it: but they only receiue it, who are content with it. Now in that he vseth the plurall number (WE) and speaking to his wife saith #emph[(shall not we receiue euill)] he sheweth that his wife ought as well as he to haue rest contented in that poore and miserable estate: For

1. Man and wife being #emph[one flesh,] by vertue of their matrimoniall vnion, both his aduancement, and also his abasement is #emph[hers:] as she riseth with him, so she falleth with him. Wherefore as she is willing to be aduanced with him, so she must be content to be abased with him.

2. If at the time of mariage her husband was of meaner estate then she, she voluntarily put her selfe into that meane estate: for a wife taketh her husband (as he her) #emph[for better for worse, for richer for poorer.] And shall she not be content with her own act? If after mariage his estate decay, and wax meaner then it was, she is to be perswaded that by God it was so ordered, and that God aimed at #emph[her] humiliation as well as #emph[his:] and thereupon she ought in her dutifull submission to Gods ouer-ruling prouidence to be patient and content: this #emph[Iob] implieth vnder this phrase, #emph[shall we not receiue euill at the hand of God?] and vnder this, #emph[The Lord taketh away.]

3. A wiues contentment is a great ease to her husband lying vnder a crosse: and it maketh the burden seeme much lighter then otherwise it would, if at least he be a kinde husband, and affected with his wiues passion, as he ought to be. For a louing husband in euery distresse is more perplexed for his wife, then for himselfe.

=== §. 50. #emph[Of wiues discontent at their husbands estate.]

Contrary is the impatiencie, and discontent of wiues at #footnote[Discontent manifested.] the meannesse, and (as they thinke) basenesse of their husbands estate: which is many waies manifested.

1. Some when they are maried finding their husbands estate #footnote[1\. By repenting their mariage.] weaker then they imagined, repent their mariage, and sticke not to tell their husbands, that if they had before knowne them to be no better men then they finde them to be, they should haue beene no husbands for them. Wherein first they bewray their foolish indiscretion by saying, when it is too late, #emph[if I had] #footnote[#emph[Non est sapientis dicere non putâram. Cic. Offic. lib.] 1.] #emph[thought this;] and withall they manifest their own rashnesse and vnaduisednesse, in that they gaue their hands and plighted their troth to those whom they knew not. If they say, they were deceiued by their friends whom they put in trust, I answer that mariage is too weightie a matter to be wholly referred ouer to the trust of friends: euery one that yeeldeth to be maried, ought wel to know the party vnto whom in this case they yeeld: and aboue all they ought to seeke direction, helpe, and blessing from God. If notwithstanding all the meanes which possibly they could vse, they be deceiued, they are to looke vnto God, and to behold his prouidence therein: and duly to weigh whether the Lord haue crossed their desire for their humiliation, or for triall of their patience, wisdome and other like graces, or else to weine them from some vaine and worldly delights, whereunto they were too much addicted.

2. Others obseruing their husbands estate to be decaied #footnote[2\. By impatient cariage.] and wasted, neuer search after the occasion, but lay all the blame vpon their husbands, and with their discontented lookes, passionate words, and impatient cariage, so vex their hearts, as they make the crosse much more heauy then otherwise it could be. Though the estate should be ouerthrowne by the vnthriftinesse of an husband, yet ought a wife to looke vnto Gods prouidence therein, as was noted before.

3. Others scorning to stoope, and to come downe to their #footnote[3\. By refusing to stoope.] husbands present condition, through their pride and vaineglory are a great means to make his estate much the worse: for they, so long as by any meanes they can get it, will not abate any thing of their braue apparell, dainty cheere, rich furniture, and other like things, which are causes of great expence to their husbands: hereby also it commeth oft to passe that husbands are thought to be wealthier then indeed they are, and so greater taxations and charges then they can beare are laid vpon them for King, Countrey, Church, Poore, and the like.

4. Others, through discontent lie long lazing in their beds, #footnote[4\. By refusing to helpe.] or idly sit still when they are vp, and will not take any whit the more paines to raise vp and increase their husbands estate: whereby God is prouoked more and more to weaken their estates, that so he may the more punish such pride and lazinesse in wiues.
