== A Husband’s Providing for His Wife

=== §. 46. #emph[Of an husbands prouident care for his wife.]

An husband that tenderly respecteth his wife, but prouidently careth not for her, sheweth more affection then discretion: he may haue a kinde heart, but he wants a wise head. How then can he be a good head vnto his wife? Some present contentment she may haue by him: but small profit and benefit can she reape from him. Those duties therefore which haue beene deliuered must be done, but these that follow must by no meanes be left vndone.

An husbands prouident care is noted in that office of Christ, wherein an husband resembleth him, namely, to be #emph[a Sauiour of] #footnote[#emph[Eph.] 5. 23.] #emph[the bodie,] as hath beene #footnote[Treat. 1. §. 15. & Treat. 3. §. 73.] before declared. It consisteth

- 1\. In prouiding things needfull for his wife.
- 2\. In protecting her from things hurtfull.

1. A carefull #emph[prouiding of things needfull,] is a principall part of #footnote[1\. Prouiding things needfull.] that #emph[honour,] which husbands are to giue vnto their wiues. For where the Apostle saith, that #emph[Elders are worthy of double honour,] #footnote[1 #emph[Pet.] 3. 7. 1 #emph[Tim.] 5. 17.] he meaneth #emph[maintenance] as well as #emph[reuerence.] The Apostle counteth him #emph[worse then an Infidell, that prouideth not for his owne, and specially for those of his owne house.] Who are of an husbands house, #footnote[1 #emph[Tim.] 5. 8.] if not his wife? in his house, who more properly #emph[his owne,] then his wife? If then an husband prouide not for his wife, what is he #footnote[#emph[Recordare quòd pater vxoris tanquam depositum quoddam filiam tibi tradidit, & omnibus relictis, matre, domo, & seipso, omnem eius curan tuae dexterae commisit. Chrys. hon.] 26. #emph[in] 1. #emph[Cor.] 11.] to be accounted?

Great reason he should prouide for her, because he hath taken her from her parents and friends, and hath receiued that portion which they allotted her, and hath authoritie committed vnto him ouer her, and she is put in subiection vnder him: her friends hauing giuen away her portion, and their power ouer her, and committed all to him, will take no further care for her: she being in subiection vnder him cannot without him prouide for her selfe. Who then shall prouide for her if he doe not, whose wholy and only she is?

Contrary is their minde, who take a wife only for their owne #footnote[Contrary, to take a wife only for himselfe.] content, or delight, or gaine, and neuer thinke of that charge which together with a wife they take vpon them. According to their minde is their practise: for when they haue a wife they neglect her in euery thing but what may stand with their owne ends. Much haue they to answer for: and so much the more, because a wife is an especiall pledge of Gods fauour. #footnote[#emph[Pro.] 18. 22.]

=== §. 47. #emph[Of an husbands prouiding meanes of spirituall edisication for his wife.]

+ In this prouident care which an husband ought to haue of
+ His wife, we will consider the

+ Extent
+ Continuance

thereof.

It ought to extend both to #emph[her selfe,] and to #emph[others.]

In regard of her selfe, to her

+ Soule.
+ Body.

For her #emph[Soule,] meanes of spirituall edification must be provided, and those both priuate and publike. Priuate meanes, are #footnote[Priuate means of edification.] holy and religious exercises in the house, as reading the word, praier, catechising, and such like; which being the spirituall food of the soule are to be euery day, as our bodily food, prouided and vsed. An husband as a master of a family must provide these for the good of his whole house; but as an husband, in speciall for the good of his wife: for to his wife, as well as to the whole house he is a King, a Priest, and a Prophet.

By himselfe therefore, for his wiues good, ought he to performe these things, or to prouide that they may be done by some other. #emph[Cornelius] himselfe performed those exercises. #footnote[#emph[Act.] 10. 2, 30. #emph[Iudg.] 17. 10.] #emph[Micah] hired a Leuite (though his Idolatry were euill, yet his care to haue a Leuite in his house was commendable.) The #footnote[2 #emph[King.] 4. 11.] Shunemites husband prouided a chamber for the Prophet, and that especially for his wiues sake, for it was at her request.

Publike meanes are the holy ordinances of God publikly #footnote[Publike meanes of edification.] performed by Gods Minister. The care of an husband for his wife in this respect is, so to order his habitation, and prouide other needfull things, as his wife may be made partaker thereof. It is expresly noted of #emph[Elkanah] that he so prouided for his #footnote[1 #emph[Sam.] 1. 7. & 2. 19. #emph[Luk.] 2. 41.] wiues, that they went with him euery yeere to the house of God: the like is intimated of #emph[Ioseph] the husband of the virgin #emph[Mary.] In those daies there was a publike place and house of God, whither all Gods people (how farre soeuer they dwelt from it) were to resort euery yeere: the places where #emph[Elkanah] and #emph[Ioseph] dwelt, were farre remote from the house of God, yet they so prouided, as not only themselues, but their wiues also went to the publike worship of God. Now there are many houses of God, places for the publike worship of God, but yet through the corruption of our times, the ministery of the word (the most principall meanes of spirituall edification) is not euery where to be enioyed: therefore such ought an husbands care for his wife in this respect to be, as to dwell where she may haue the benefit of preaching the word, or else so to prouide for her, as she may weekly goe where it may be had.

If men of wisdome and abilitie make a purchase, or build an house for their habitation, they will be sure it shall be where sweet riuers and waters are, and good pasture ground, and where all needfull prouision may be had. Gods word preached is a spring of water of life; the place where it is preached a pleasant, profitable pasture; all needfull prouision for the soule may there be had. Let this therefore be most of all inquired after: and no habitation setled but where this may be had.

=== §. 48. #emph[Of neglecting their wiues edification.]

Contrary is their practise, who hauing their calling in places where the word is plentifull, yet vpon outward respects of pleasure, delight, ease, and profit, remoue their families into remote places where preaching is scarce, if at all; and there leaue their wiues to gouerne the family, not regarding their want of the word, for as much as they themselues oft comming to London or other like places by reason of their calling, enioy the word themselues. Many Citizens, Lawyers, and others are guiltie of great neglect of their wiues in this respect.

So also are they, who abandon all religious exercises out of their houses, making their houses rather stewes of the deuill, then Churches of God. If for want of meanes, either publike or priuate, a wife liue and die in ignorance, profanenesse, infidelitie, and impenitencie, which cause eternall damnation, assuredly her bloud shall be required at his hands: for an husband #footnote[#emph[Ezek.] 3. 18. #emph[&c.]] is Gods watchman to his wife.

=== §. 49. #emph[Of an husbands prouiding things needfull for his wiues boay.]

To the body also must an husbands prouident care of his wife extend: and that both in health and sicknesse. In health by prouiding such things as are needfull to preserue health, as competent food, raiment, and the like necessaries. Where the #footnote[#emph[Jsa.] 4. 1.] Prophet to aggrauate the misery of the people saith, #emph[Seuen women shall take hold of one man,] saying, #emph[We will eat our owne bread, and weare our owne apparell, only let vs be called by thy name,] intimateth, that it was an husbands dutie to prouide bread and apparell, that is, all necessaries for his wife. Which the #footnote[#emph[Exo.] 21. 10.] law also implieth, where it inioyneth him that taketh one wife vpon another, not to diminish the food and raiment of the former. In sicknesse such things are to be prouided as are needfull either to recouer her health, or to comfort, cherish and refresh her in her sicknesse.

This was #footnote[Treat. 2. Part. 2. §. 29.] before noted among common mutuall duties; for by vertue of the matrimoniall bond it belongeth both to man and wife: but to the man it appertaineth by vertue of that power and charge which he hath ouer his wife: and therefore it was needfull here to be touched.

=== §. 50. #emph[Of an husbands] #footnote[Treat. 3. §. 49.] #emph[prouident care for his wife about her child-bearing.]

Most proper to this place is that prouident care which husbands ought to haue of their wiues both before and in the time of their trauell and child-bed: and that in two things especially.

1. In procuring for their wiues to the vttermost of their power and abilitie, such things as may saue their longing, in case they doe long (as in all ages women in the time of breeding and bearing childe, haue beene subiect thereunto.) For it is well knowne, that it is very dangerous both for mother and childe to want her longing: the death sometimes of the one, sometimes of the other, sometimes of both hath followed thereupon.

2. In prouiding such things as are needfull for their trauell and lying in childbed. This time is especially to be prouided for, in many respects.

1. Because it is a time of weaknesse, wherein the woman cannot well prouide for her selfe.

2. Because her weaknesse is ioyned with much paine: the #footnote[The paines of womens trauell.] paine of a women in trauell is the greatest paine that ordinarily is endured by any for the time: none know it so well as they that feele it: and many husbands because they are not subiect thereto, thinke but lightly of it: but if we duly weigh #footnote[#emph[Psal.] 48 6. #emph[Isa.] 13. 8. & 21. 3 #emph[Ier.] 4. 31. & 30. 6. #emph[Mic.] 49.] that the holy Ghost when he would set forth the extremitie of any paines and pangs, resembleth them to the paines of a woman in trauell, we may well gather, that of all they are the greatest: which is further manifested by the screekes and outcries which not only weake, and faint-hearted women vtter in the time of their trauell, but also are forced from the strongest, and stoutest women that be, and that though before hand they resolue to the contrary. Neither may we wonder thereat; for their body is as it were set on a racke (if at least the trauell be sharpe) and all their parts so stretched, as a wonder it is they should euer recouer their health and strength againe: or that they should hold out the brunt, and not die with their trauell, as #emph[Rachel,] and the wife of #emph[Phinchas,] and many in all ages haue #footnote[#emph[Gen.] 35. 16, #emph[&c.] 1 #emph[Sam.] 4. 19. 20.] done. Surely among ordinary deliuerances I know none so neere a miracle, none wherein the Almighty doth so euidently manifest his great power and good prouidence, as in the safe deliuerie of women. Besides the great pang of trauell, women are also after their deliuerie subiect to many #emph[after-throws] which are very painfull. From all these paines and great weaknesse which befalleth women in childbed, especially if they nurse their children, men by reason of their sex are freed: Now then to apply this point, seeing women are brought to such paines and weaknesse in bringing forth those children which are the mans as well as hers, and he freed from all; is it not very iust and meet that he should prouide all things needfull for her welfare, ease, and recouery of strength?

3. Because the want of things needfull is at that time very dangerous: dangerous to the health and life of the woman and childe also.

=== §. 51. #emph[Of neglecting wiues in their weaknesse.]

Contrary to an husbands prouident care in generall are those vices which were taxed in the treatise of common duties, #footnote[\* See Treat 2. Part. 2. § 30. 39.] as #emph[grudging at the charges bestowed on a wife: Couetousnesse, Prodigality,] and #emph[Idlenesse.]

But contrary in particular to an husbands care for his wife in childbed, is the inhumane and more then barbarous vnkindnesse of many husbands, who no whit consider the weaknesse of their wiues in this case, to helpe, ease, and comfort them, but rather make their burden much more heauy. For,

1. Some through couetousnesse refuse before hand to afford meanes to their wife to prouide such things as are needfull for her selfe and child: & when the time commeth, if their wife be desirous of a Midwife that requireth somwhat more charges then she that is next, she shall haue none if she will not haue the next. And as for a nurse to tend her, they thinke their Maid will serue the turne wel enough: they need not be at the charges to bring a Nurse into the house. In regard of conuenient lodging some will not sticke to say, Cannot my wife be brought to bed in a roome without a chimney as well as the Virgin #emph[Mary?] Why should my wife need more things then she did? Yea further there be many that when the time that their wife should be deliuered approacheth neere, carie her from al her friends into a place where she is not knowne, lest her friends should by importunity draw him to expend and lay out more vpon his wife then he is willing. In the time while their wife is weake in childbed, many are loath to allow them any other diet then is for themselues and children prouided in the house, not considering that her stomach cannot be like theirs.

Many other such bitter fruits of vnkinde husbands arising from couetousnesse might be reckoned vp, whereby husbands plainely shew that they loue their wealth better then their wiues: they had rather lose #emph[them,] then part with #emph[that.]

2. Others through iealous suspicion forbeare not euen in #footnote[#emph[Si quid vxor peccauerit consolare & noli moerorem augere. Chrys. hom.] 26. #emph[in] 1 #emph[Cor.] 11.] the time of their wiues paine and weaknesse, to vpbraid them with lightnesse, and to say that the childe is none of theirs. To lay this to a wiues charge vniustly, is at any time a most shamefull and odious reproach: but in the time of childebirth whether iust or vniust, a thing too too spightfull and reuengefull. Some wiues are so farre ouercome thereby, (especially in the time of their weaknesse) as they are not able to beare it, but euen faint and die vnder the reproach: others more stout vow neuer to know their husbands againe. Many like mischiefes follow on such vnkindnesse.

=== §. 52. #emph[Of an husbands] #footnote[Treat. 3. §. 38.] #emph[prouiding for his wife according to his estate and abilitie.]

In an husbands prouiding for the body of his wife respect must be had to the #emph[measure,] and to the #emph[manner.]

The #emph[measure] must extend to his ability: for an husband ought to maintaine his wife in as good an estate and fashion as himselfe; by mariage she is aduanced to as high an estate, and dignity in relation to others as he is: and for her owne vse she is made a partner of all his goods, and accordingly ought to partake thereof.

For the #emph[manner,] he must suffer her (if at least he obserue her to haue any competent discretion) to order such things as are needfull for her selfe according to her best liking: as #emph[Elkanah] in another case said to his wife, #emph[Doe what seemeth thee best.] #footnote[1 #emph[Sam.] 1. 23.]

Both in the #emph[measure] and in the #emph[manner] of prouiding, there must be a difference put betwixt a wife, and seruants or children. These may haue their portions of meat, apparrell, and like necessaries, proportioned out and stinted vnto them, which is vnmeet to be done to a wife. Neither is it needfull that so plentifull a prouision be made for them as for her.

=== §. 53. #emph[Of an husbands nigardlynesse to his wife.]

Contrary is an husbands nigardly dealing with his wife: when the allowance she hath is both farre vnder his estate, and also so giuen her by little and little, as if she were a childe. Many husbands make their wiues drudge at home, fare hardly, and goe meanly; who are themselues braue in apparrell, frolicke in their feasting abroad, and so exceed their wiues as they are ashamed to be seene in company with them. They who marry their maids, or others of meaner ranke then themselues, oft so deale with them: esteeming them but as seruants and meane persons though they be their wiues. But it hath beene #footnote[§. 6.] before shewed, that wiues by marriage are aduanced to their husbands dignity, how meane soeuer they were before.

=== §. 54. #emph[Of husbands] #footnote[Treat. 3. §. 23. 29. 33.] #emph[allowing their wiues to bestow on others, as they see good occasion.]

So farre ought the prouident care of an husband for his wife to extend, as she may haue (beside things needfull to her selfe) to bestow on such as it is requisite for her to giue vnto: as namely, on children and seruants in the house, and others also out of the house. For so much is noted in #emph[Salomons] description #footnote[#emph[Pro.] 31. 15. #emph[&c. Vers.] 21. #emph[Uers.] 28.] of a good wife; #emph[She giueth meat to her houshold, and a portion to her maidens: all her houshold is clothed with scarlet] (namely, by her ordering and disposing the matter.) #emph[Her children rise vp and call her blessed,] as for her generall cariage in the family, so for her particular fauours bestowed on themselues. As for #footnote[#emph[Vers.] 20.] others out of the house, it is also noted, that #emph[she stretcheth out her hand to the poore, and reacheth forth her hands to the needie.] These things she did by virtue of that power and liberty which her husband gaue her: as appeareth by two points there noted:

1. In that before any mention is made of those things #footnote[#emph[Vers.] 11.] which she did, it is said, #emph[The heart of her husband doth safely trust in her.]

2. In that, after all her good deedes are reckoned vp, it is #footnote[#emph[Uers.] 28.] said, #emph[Her husband praiseth her.]

After this patterne it is meete that other husbands (whose wiues are wise and faithfull) should deale with their wiues: that in the house they might haue the more honour of children and seruants: and that out of the house they might giue the better tryall of their charity.

For considering the many excellent promises that are made to workes of mercy and charity, and the many terrible threatnings that are denounced not onely against such as exercise cruelty, but also against such as shew no mercy: considering also that wiues together with their husbands, are #emph[heires of the] #footnote[1 #emph[Pet.] 3. 7.] #emph[grace of life,] it is very needfull yea euen necessary, that they should manifest their faith by some worke of mercy and charity. Now vnlesse her husband doe giue vnto her something at her owne discretion to bestow on others, true and through try all of her mercifull and charitable minde cannot be made. If she giue of that which her husband hath reserued to himselfe, as her giuing is vnlawfull, so she may be thought liberall, not because she is mercifull, but because notwithstanding her liberality she parteth with nothing of her owne: yea though she haue a generall consent to giue as she seeth cause of the common goods of the family, yet is not that so sure and sound a tryall of her charity, and mercifulnesse, as if she had something of her owne which she might retaine or giue away as pleaseth her selfe; and what she giues not away, lay vp as her owne stocke proper to her selfe. For there is naturally such a selfe loue in man, and a desire to keepe that which is proper to ones selfe, that he is very loath to part with any of it, vnlesse conscience and grace alter this corruption of nature, and so moue him readily to lay out something on charitable vses. But otherwise of that which in whole or in part belongeth to another (be that other, husband, parent, master, friend, or any else) he is easily moued to be liberall and bountifull: a man will willingly cut a large thong (as we speake) out of anothers leather.

It is knowne that many children and seruants, who, when they come to be possessers of their owne, are very niggards and misers, haue beene liberall of their parents and masters goods vnto the poore. Yea parteners in a stocke will be much more forward in giuing away that which is common with another, then that which is proper to each of them. The truest triall of a mercifull and charitable heart lieth in the distribution of that which is proper to ones selfe.

It is therefore meet vpon this very ground, that an husband should according to his ability let his wife haue some stocke, and portion of her owne, free to her selfe to dispose as she seeth good: intimating vnto her that the principall end why he prouideth so plentifully for her, is, that she may shew forth the fruits of her faith by some workes of charity: and exhorting her so to doe. Many religious, wise, kinde husbands thus doe: some giuing quarterly allowance in money to their wiues, others giuing their wiues power to receiue a certaine portion of rent out of certaine lands or houses; others making their wiues an absolute estate of some inheritance, and suffering them to receiue the profits and reuenewes thereof; others giuing them certaine fees of their offices, or of their trade; others, that are poore, suffering them to worke for themselues, & dispose their earnings as they see cause: some one way, some another: euery one in his place best knoweth the meanes how to gratifie his wife in this kinde: it shall be sufficient for me to haue laide downe the generall rule.

=== §. 55. #emph[Of husbands too great straitnesse ouer their wiues.]

Contrary is their strait-handednesse to their wiues, who allow them no more then may be for their owne priuat vse. They thinke it a great matter and as much as an husband is bound to doe, to let her haue apparrell, meat and drinke, and such necessaries as are befitting her ranke, but all other ouerplus they thinke needlesse. Thus their wiues are not only depriued of meanes to gaine respect of their children and seruants at home, and to gratifie such as are obedient and ready to doe seruice to them, but also to performe such workes of mercie as both opportunity requireth, and also their conscience moueth them to doe. Yea many wiues of rich husbands are brought to great shame hereby, in that being in places where there is iust occasion of contributing to some charitable vse, and by reason of their rich and costly apparell it is expected they should be bountiful, they haue not any thing at all to bestow. The fault of some husbands in this respect is great many waies. As 1. in that they bring shame and griefe to their wiues, whom they ought with all tendernesse to respect. 2. In that they dishonour their owne places: for they who take notice of this straitnesse to their wiues, will be ready to iudge them both couetous, and vnkinde. 3. The omitting of that worke of mercie which their wiues should haue done shall be laid to their charge: they shall heare that dreadfull doome; #emph[Goe yee cursed into euerlasting fire,] for #emph[I was an hungred and yee fed me not &c.] and if they answer, #emph[When saw we thee an hungred &c.] it shall be replied, #emph[In that yee suffered not your wiues to doe it, you did it not.]

Thus much of the #emph[extent] of an husbands prouident care for the good of his wife. It followeth to speake of the continuance thereof.

=== §. 57. #emph[Of an husbands care to prouide for his wife so long as she shall liue.]

The #emph[continuance] of an husbands prouident care for his wife must be so long as she liueth, yea though she out-liue him: not that he can actually when he is dead prouide for her, but that he may before his death so prouide for her, as she may haue wherewithall to maintaine her selfe, and to liue according to that place whereunto by him she is aduanced: at least that he leaue her not only so much as he had with her, but something more also in testimony of his loue to her, and care for her. Husbands haue the example of Christ to presse this duty vpon them: for when he went away from his Church here on #footnote[#emph[Eph] 4. 8.] earth, he left his spirit, which furnished it with gifts as plentifully, as if Christ had still remained with her, if not more aboundantly.

For the better performance of this duty, husbands which die before the wiues, must obserue among other things two especially.

1. That plainly and expresly they declare their minde and #footnote[Husbands before they die must make their will euen for their wiues good.] will before they die, lest their wiues should be circumuented and defrauded of that which they intended them. Thus did #emph[Dauid] vpon the motion of #emph[Bathshebah,] he setled his estate, and caused #emph[Bathshebahs] sonne to be actually crowned before he himselfe gaue vp the Ghost: which he did, as for other weighty reasons, so in particular for his wiues good, as may be gathered from that reason she alleaged to the King in these #footnote[1 #emph[King.] 1. 21. Husbands on their deathbed must commend their wiues to some faithfull friend. #emph[Iob.] 19 26, 27. #emph[Reason.] Truest triall of loue at departure.] words; #emph[Else when my Lord the King shall sleepe-with his fathers, I shall be reputed vile.]

2. That he request some faithfull friend in his steed to be an helper vnto her; (as Christ commended his mother vnto his disciple #emph[Iohn)] which will be needfull in regard of her weaknesse, by reason of her sex, and want of experience to manage such affaires especially as are out of the house.

At the time of a mans departure out of this world from his wife, will the truest triall of his affection to his wife be giuen: for many that beare their wiues faire in hand while they liue with them, at their death shew that there was no soundnesse of affection in their heart towards them: all was but a meere shew for some by-respects.

=== §. 58. #emph[Of husbands neglect of their wiues future estate.]

Contrary are diuers practises of vnkinde husbands. For #footnote[Contrary. 1. A wilfull inability.]

1. Some through improuidence, vnthriftinesse and prodigality, disable themselues from doing good to their wiues after their death; and so leaue their wiues nothing, or (that which is worse then nothing) in debt, and with a great charge of children. That care which husbands ought to haue of their wiues should make them thinke before hand of the time to come, and euen for their wiues sake be some-what the more diligent, thrifty, and prouident, and cut off many vnnecessary expences, else their sinne is doubled. 1. By a needlesse wasting their estate. 2. By neglecting their wiues.

2. Others by fawning, or forcing meanes draw their wiues #footnote[2 Making away their wiues ioynter, or any other right.] to yeeld vp that interest they haue in money, goods, house or land by ioynter, inheritance, or any other way, and yet make them no sufficient recompence in another kinde: but at their death leaue their wiues in a farre worse estate then they were in before mariage, beside a greater charge then they had before. As this is a great part of vnkindnesse, so also a maine point of iniustice.

3. Others grudging against the lawes vnder which they #footnote[3\. Defeating of #emph[thirds.]] liue for prouiding for a wife by #emph[thirds] or otherwise, vse all the fraudulent meanes they can to depriue her of that which otherwise the law would lay vpon her. The ciuill politique awes of the place where we liue ought to be the rule of our ciuill actions (so farre as they are not repugnant to Gods word) and we ought for #emph[conscience sake] to be subiect vnto #footnote[#emph[Rom.] 13. 5.] them. Besides an husband ought (though the law forced him not) to leaue at least the #emph[thirds] to his wife, as a testimony of his loue to her, and care for her: so as this also is a double fault. 1. A transgression of the law. 2. A note of vnkindnesse.

4. Orthers hauing aged and sickly wiues, or otherwise #footnote[4\. Making no will.] thinking that their wiues may, or rather hoping that their wiues will die before themselues, put off the making of their wills of purpose that they might not put in their wiues #emph[thirds,] but dispose them some other way. Besides that these husbands shew no good affection towards their wiues, they prouoke God to disappoint them of their hopes: and so he doth often-times: for he taketh them away before their wiues, and so taketh them away, as hauing no time to make their will, not only their wiues enioy their #emph[thirds] (which they so much desired to auoid) but also some other (whom of all in their life time they misliked) seaze vpon the other two parts.

=== §. 58. #emph[Of an husbands protecting his wife from danger.]

Hauing shewed how an husband is to prouide things needfull for his wife: It remaineth to shew how he is to protect her from things hurtfull.

In regard of that #emph[protection] which an husband oweth his wife, he is called #emph[the veile of her eies:] which phrase as it implieth #footnote[#emph[Gen.] 20 16.] #emph[Subiection] on the wiues part, so also #emph[Protection] on the husbands: to protect one, is as it were, to #emph[couer] them, namely, from danger; to be negligent and carelesse of them, is, as it were, to lay them open to danger. The same duty is implied vnder another like phrase of #emph[spreading his wing] ouer his wife. #footnote[#emph[Ruth] 3. 9.] The metaphor is taken from winged fowles, which to keepe their young ones from hurt, vse to spread their wings ouer them: this phrase and metaphor is also attributed to God, to #footnote[#emph[Ruth] 2. 12.] set forth his protection.

But most pertinent to this purpose is the title, #footnote[Treat. 1. §. 15. and treat. 3. §. 73.] #emph[Saniour,] giuen to an husband in relation to his wife.

For this end the Lord who subiected a woman vnto her husband, gaue to his sexe greater strength, courage and boldnesse then to hers, that he might protect her which is the #emph[weaker vessell.] In this duty of #emph[protection] Christ sheweth himselfe an excellent patterne and president vnto husbands.

The better to performe this dutie, an husband must bee carefull,

1. To preuent, as much as he may, such dangers as his wise is like to fall into.

2. To recouer her out of such as she is fallen into.

For this purpose did #emph[Dauid] carry his wiues into #emph[Gath,] lest, if #footnote[1 #emph[Sam.] 27. 3.] they were left in Israel, #emph[Saul] should worke them some mischiefe: and againe, when they were taken by the #emph[Amalakites,] he recouered #footnote[#emph[&] 30. 18.] them.

According to that danger whereunto wiues are subiect, must an husbands care of protecting his wife be manifested.

1. If she be in danger to be seduced and inticed, as #emph[Euah] was, #footnote[A wife must be kept from being seduced.] by any euill instruments of the deuill, as Iesuits, Priests, Friers, profane, blasphemous, lasciuious, or riotous persons; his care must be either to keepe them away that they come not at her, or to put them away from her so soone as he can: he may not suffer them to harbour in his house.

2. If by any sleight she be drawne from his house, he must #footnote[A wise stolne away must be fetched home. #emph[Iudg.] 19. 2. 2 #emph[San.] 3. 13, 14. 1 #emph[Sam.] 30. 18. A wiues credit must be maintained.] seeke her, and fetch her againe, as the #emph[Leuite] did his wife: or cause her (if he can) to be brought home againe, as #emph[Dauid] caused #emph[Michal] to be brought: especially if they be taken away by force, as #emph[Ahinoam,] and #emph[Abigail, Dauids] wiues, were.

3. If she be vniustly slandered, he is to maintaine her credit and reputation as much as his owne: as #emph[Christ] accounteth himselfe despised, when his Church is, so must he. This care must he #footnote[See Treat. 2. Part 2. §. 31. &c.] haue of his wiues credit, euen after her death, as well as while she liueth.

4. What other mischiefe so euer is intended or practised against #footnote[#emph[Luke] 10. 16. A wife must be defended against strangers, seruants, and children. #emph[Est.] 7. 7, 8. #emph[&c.]] her, he must be a tower of defence to protect her, (as #emph[Ahoshuerosh] was to #emph[Ester] against #emph[Haman)] and that not only against strangers without the house, but also against children and seruants in the house. Children growne to yeeres, that are stout and stubborne, will be ready to rise vp against their mother, especially if she be a mother in law, because she is the weaker sex: the countenance of a father for the most part keepeth most in awe. Wherefore the husband must be an helpe to his wife, and maintaine her honour against them: yea though they be children of a former wife.

=== §. 59. #emph[Of an husbands maintaining his wife against children of a former venter, and seruants.]

#emph[Obiect.] Mothers in law often proue vnkinde, and vniust stepmothers, and deale vnmercifully with their husbands children: must an husband in such cases assist his wife against his children?

#emph[Answ.] The protection, I speake of, is in case a wife be wronged, then her husband is to doe what he can to right her (as we speake.) But if she be the wrong-doer, he may by no meanes boulster her vp against his children, and so make their wrong the greater. Yet so far ought he to respect his wife, as by all the faire meanes he can, to labour to pacific her minde, and turne her heart towards them: and if he obserue her heart to be cleane alienated from them, then to put them forth to be brought vp in some other place, and so to take away from her the obiect of her displeasure, that he and she may liue more quietly together. For #emph[if a man must forsake father and mother,] he must also forsake children, and #emph[cleaue to his wife.] Peace and vnitie betwixt man and wife must of all other be kept inuiolable. #emph[Though thou cast away] #footnote[#emph[Licèt omnia proijcias, nihil molestius continget quàm non habere beneuolam domi vxorem: peccatum nullum magis dolendum inueneris, quàm cum vxore seditionem habere. Chrysost. hon.] 26. #emph[in] 1. #emph[Cor.] 11. #emph[Genes.] 16. 6. #emph[&] 21. 14.] #emph[all, nothing can happen more troublesome to thee then not to haue a quiet wife at home. Thou canst finde no sinne more grieuous then to haue contention with a wife.]

If a wife must be maintained against the stubbornnesse of children, much more against the insolencie of seruants: for which purpose the example of #emph[Abraham] is recorded, whose seruant might haue a priuiledge aboue others, because he had made her his bedfellow; yet when she waxed insolent against her mistresse, first he put her into her mistresses hand to doe to her as it pleased her; and afterwards he cast her out of his house.

=== §. 60. #emph[Of neglecting to maintaine their wiues.]

Contrary is a dissolute carelesnesse of husbands, who care no more to helpe and succour their wiues then any other.

1. Some more feare to offend their wiues then they care to doe #footnote[Contrary, Dissolute carelesnesse. 1. In suffering seducers to come to the house.] them good, and in that respect they let any sort of people come to their wiues that are welcome to them. If Magistrates in a Common-wealth shall answer for suffering seducers to come into their dominions to deceiue their people, much more shall husbands answer for suffering them to come and deceiue their wiues.

- 1\. Because they haue a greater charge ouer their wiues then Magistrates ouer their people.
- 2\. Because wiues ought to be dearer to husbands then people to Magistrates.
- 3\. Because they may sooner espie them in their house, then Magistrates in the Common-wealth.
- 4\. Because they may be much more easily kept out of an house, then out of a Common-wealth, or a Citie.

2. Others care not whither their wiues wander: and if they #footnote[2\. In suffering] doe goe out of their house, they shall neuer be sought after by their #footnote[wiues to goe whither they list.] husbands: though this may be a iust punishment on wandring wiues, yet is it not iust for husbands so to deale with them. If Christ our husband should so deale with vs, we should soone be lost: for wee oft goe astray like wandring sheepe, but hee is that good shepherd, who seeketh after the lost sheepe vntill he #footnote[#emph[Luke] 15. 4.] finde it.

3. No maruell then that many husbands are no more affected #footnote[3\. In not regarding ill reports of wiues.] with the ill reports and rumors raised against their wiues, when they so little regard who come to them, or whither they goe. Assuredly the discredit of a wife will turne to the mans dishonour: for as #emph[a vertuous wife is a crowne to her husband,] so by the #footnote[#emph[Pro.] 12. 4.] rule of contraries, an infamous wife is a shame to her husband. If therefore not for his wiues sake, yet for his owne sake a man ought not too carelesly passe ouer the ill reports which are raised against his wife.

4. There be such vnkinde husbands as are moued with no ill #footnote[4\. In suffering wiues to be misused.] vsage done vnto their wiues, nor will heare any complaint that they make vnto them: yea if they see them misused, they will either not seeme to see it, or but smile at it, and so goe their way, and suffer their wiues to right themselues as well as they can. As this beseemeth not any Christian to suffer his neighbour to be wronged, (for it is noted as a commendable matter in #emph[Moses,] that #footnote[#emph[Exod.] 2. 13.] when he saw two Hebrewes striuing together, he tooke his part that had wrong done to him, and reproued the other) so much lesse an husband, to whose safe-guard his wife is committed. Nature teacheth vs that the head is as much affected with a wrong done to the bodie, as to it selfe: so ought an husband. #footnote[5\. In boulstring vp children or seruants against wiues.]

5. As the wrong which is done by those who are in subiection in the house vnder the wife, is greater then that which is done by strangers: so is the husbands fault the greater in suffering it: for he hath more power ouer them in his house, then ouer others. #footnote[Si illam quae secundum post te locum obtinet contumelia afficis, non parum tui principatus honori derogas. Chrys. loc. cit.] What then may we thinke of such, as either by their conniuence, or by taking part against their wiues, suffer both children and seruants to insult ouer them? Assuredly those husbands themselues will finde some smacke of the bitter and euill fruit thereof: and that not only by that great discontent which their wiues must needs take thereat; but also by that contempt which will follow on their owne persons, both by their wiues (who cannot thinke them meet heads to gouerne others) but also by their children and seruants, who thereby will take occasion to waxe proud, and presumptuous against him. By despising the weaker, men grow by little and little to despise the stronger. This men of wisdome and experience well know: whereupon in Common-wealths and Policies gouerned by wise men, the authoritie of inferiour Magistrates is vpheld and maintained: superiour Magistrates will not suffer them who are in authoritie vnder them to be despised: for it is well knowne, that it tends not to the honour and ease only, but to the safetie also of the supreme Magistrate, to haue the power and authoritie of inferiour Magistrates respected, and not trampled vnder feet. It argueth therefore both want of affection, and of discretion and vnderstanding in husbands, to suffer childe, seruant, or any other in the house, to insult ouer their wiues, who are ioynt gouernours with them ouer the house.
