== 5. Other Things to Apply Yourselves To

And as you must take heed of these five things, so there are several other things that you must carefully and conscientiously apply yourselves to, as ever you would be found faithful and constant in this great duty of closet prayer.

Now they are these:

=== a. Lament Greatly and Mourn Bitterly over the Neglect of This Duty
First, lament greatly and mourn bitterly over the neglect of this choice duty. He that doth not make conscience of mourning over the neglect of this duty will never make conscience of performing this duty. Oh, that your heads were waters, and your eyes a fountain of tears, that you might weep day and night for the great neglect of closet prayer (Jer 9:1). He that mourns most for the neglect of this duty will be found most in the practice of this duty. He that makes most conscience to accuse, arraign, and condemn himself for neglecting closet prayer, he will make most conscience of giving himself up to closet prayer. It is said of Adam that he turned his face towards the garden of Eden and from his heart bitterly lamented his great fall. Oh, that you would turn your faces towards your closets and bitterly lament your rarely going into them.

#pagebreak()

=== b. Make Private Prayer Your Constant Trade
Secondly, habituate yourselves, accustom yourselves, to closet prayer. Make private prayer your constant trade. Frequency begets familiarity, and familiarity confidence. We can go freely and boldly into that friend’s house whom we often visit. What we are habituated to we do with ease and delight. A man that is habituated or accustomed to write, to read, to ride, to run, or to play on this or that musical instrument, he doth it all with delight and ease. And so a man that doth habituate himself to closet prayer will manage it with delight and ease.

=== c. Keep a Diary of All Your Closet Experiences
Thirdly, keep a diary of all your closet experiences (Deu 7:18-19; Psa 66:12). Oh, carefully record and book down all your closet mercies! Oh, be often in reading over your closet experiences, and be often in meditating and in pondering upon your closet experiences! There is no way like this to inflame your love to closet prayer and to engage your hearts in this secret trade of private prayer.

Oh, remember that at such a time you went into your closets with hard hearts and dry eyes, but before you came out of your closets, ah, how sweetly, how evangelically, how powerfully were you melted and humbled before the Lord (Psa 6:6; 39:12; 56:8). Oh, remember how that at another time you went into your closets clouded and benighted but came out of your closets with as glorious a shine of God upon your souls as Moses had upon his face when he came down from the mount from communing with God (Exo 34:28-29)! Oh, remember how often you have gone into your closets with cold, frozen spirits, but before you came out of your closets what a fire hath God kindled in your souls, what a spirit of burning have you found in your hearts (Luk 24:31-32; Isa 4:4)! Oh, remember how often you have gone into your closets straitened and shut up, but before you have come out, how have your souls been like the chariots of Amminadib (Song 6:12)! Oh, remember what power God hath given you against corruptions in your closets, and what strength God hath given you against temptations in your closets! Oh, remember the sweet discoveries of divine love that you have had when in your closets! Oh, remember the secret visits, the secret kisses, the secret embraces, the secret whispers, the secret love-tokens that Christ hath given you in your closets! Oh, seriously ponder upon these things, and then closet duties will be sweet unto you!

It was a sweet saying of Bernard, “O saint, knowest thou not that thy husband Christ is bashful and will not be familiar in company? Retire thyself by meditation into thy closet, or into the fields, and there thou shalt have Christ’s embraces” (Song 8:11-12). “Meditation is the nurse of prayer. Oh, the more any man meditates upon his closet experiences, the more he shall find his heart engaged to closet duties. The more you ponder upon closet experiences, the sweeter will closet experiences be to your souls. And the sweeter closet experiences are to your souls, the more your souls will delight to be with God in your closets.

Pliny tells us of one Messala Corvinus, whose memory was so bad that he forgot his own name. And I am afraid that many of your memories are so bad that you forget your closet mercies, your closet experiences.

I have read of such a pestilential disease once at Athens as took away the memories of those that were infected with it, so that they forgot their own names. Oh, that I had not cause to fear that some pestilential disease or other hath so taken away the memories of many that they have quite forgot their closet experiences. Well, friends, remember this, though stony hearts are bad, yet iron memories are good. And oh, that you would all labor after iron memories, that so you may remember and ponder upon your closet experiences. I have read of the heathens how they made use of white and black stones for these two ends: first, they gave them to persons at their arraignment before the judges. If they were condemned to death, they gave him a black stone, but if absolved and set free, a white stone. To which custom the Holy Ghost seems to allude in Revelation 2:17, “To him that overcometh will I give…a white stone.” A second use of those stones was this: that by them they might keep an account of all the good days or evil days they had met withal in their lives. Hence, Giacopo Senzaro having been long in love, and much crossed about his match, he filled a pot full of black stones, putting only one white stone among them, and being asked the reason, answered, “There will come one white day,” meaning his marriage day, “which will make amends for all my black days.”

Ah, friends! How often hath God given you the white stone in your closets! Certainly, you have had more white stones than black stones. Your closet mercies and experiences have been more than your public crosses and miseries. Sirs! Did you but reckon your good days according to the white stones you have had in your closets, it would make you more in love with closet prayer than ever.

=== d. Spend Not So Much Time in Public Duties That None Is Left for Private
Fourthly, be sure that you do not spend so much of your precious time in public duties and ordinances as that you can spare none for private duties, for secret services. Though Pharaoh’s kine ate up one another, yet our duties must not eat up one another (Gen 41:4). Public duties must not eat up family duties; family duties must not eat up public duties; neither of them must eat up closet duties. The wisdom of a Christian doth most eminently sparkle and shine in giving every duty its proper time and place. I was going to say that either he was no Christian, or at least no excellent Christian, that is all eye to read, or all ear to hear, or all tongue to speak, or all knee to bow, to kneel, to pray (Ecc 8:5). Ah! How many are there that spend so much time in hearing of this man and that, and in running up and down from meeting to meeting, that they have no time to meet with God in their closets. O sirs! Your duties are never so amiable and lovely, they are never so orient and beautiful, as when they are seasonably and orderly performed.

Oh, how wise are the men of this world so to order all their civil affairs that no one business shall interfere with another. They set apart for each business a convenient proportion of time. They allot an hour for one business, two for another, three for another, etc. Oh, that we were as wise for our souls, as wise for eternity, as they are for this world. Oh, that our hearts would so consult with our heads, that we may never want a convenient time to seek God in a corner! That devil that loves to set one man against another, and one nation against another, and one Christian against another, that devil loves to set one ordinance against another, and one duty against another. Hence it is that on the one hand he works some to cry up public prayers in opposition to secret prayer. And on the other hand, he works others to cry up private duties in opposition to all public duties. Whereas all Christians stand obliged by God so to manage one sort of duties as not to shut out another sort of duties. Every Christian must find time and room for every duty incumbent upon him.

#pagebreak()

=== e. Love Christ with a More Inflamed Love
Fifthly, love Christ with a more inflamed love. Oh, strengthen your love to Christ, and your love to closet duties. Lovers love much to be alone, to be in a corner together (Song 7:10-12). Certainly, the more any man loves the Lord Jesus, the more he will delight to be with Christ in a corner. There was a great deal of love between Jonathan and David (1Sa 18-20); and according to their love, so was their private converse, their secret communion one with another. They were always best when in the field together, or when in a corner together, or when behind the door together, or when locked up together. And just so would it be with you, did you but love the Lord Jesus Christ with a more raised and a more inflamed love. You would be always best when you were most with Christ in a corner.

Divine love is like a rod of myrtle, which, as Pliny reports, makes the traveler that carries it in his hand so lively and cheerful that he never faints or grows weary. Ah friends, did you but love the Lord Jesus with a stronger, with a more raised love, you would never faint in closet duties nor would you ever grow weary of closet duties. Look, as the Israelites removed their tents from Mithcah to Hashmonah, from sweetness to swiftness, as the words import (Num 33:29), so the sweetness of divine love will make a man move swiftly on in a way of closet duties. Divine love will make all closet duties easier to the soul and more pleasant and delightful to the soul. And therefore, do all you can to strengthen your love to Christ and your love to closet work.

It was observed among the primitive Christians that they were so full of love one to another that they could be acquainted one with another as well in half an hour as in half a year. O sirs, if your hearts were but more full of love to Christ and closet duties, you would quickly be better acquainted with them, you would quickly know what secret communion with Christ behind the door means.

=== f. Be Fixedly Resolved to Keep Close to Closet Duties
Sixthly, be highly, thoroughly, and fixedly resolved, in the strength of Christ, to keep close to closet duties in the face of all difficulties and discouragements that you may meet withal (Psa 44:17-20). A man of no resolution, or of weak resolution, will be won with a nut and lost with an apple. Satan, and the world, and carnal relations, and your own hearts will cast in many things to discourage you and take you off from closet prayer. But be ye nobly and firmly resolved to keep close to your closets, let the world, the flesh, and the devil do and say what they can. Daniel was a man of an invincible resolution. Rather than he would omit praying in his chamber, he would be cast into the den of lions. Of all the duties of religion, Satan is the most deadly enemy to this of secret prayer, partly because secret prayer spoils him in his most secret designs, plots, and contrivances against the soul; and partly because secret prayer is so musical and delightful to God; and partly because secret prayer is of such rare use and advantage to the soul; and partly because it lays not the soul so open to pride, vain-glory, and worldly applause as prayer in the synagogue doth. And therefore, he had rather that a man should pray a thousand times in the synagogues, in the corner of the streets, or behind a pillar, than that he should pray once in his closet. And therefore, you had need to steel your hearts with holy courage and resolution that whatever suggestions, temptations, oppositions, or objections you may encounter with, that yet you will keep close to closet prayer.

There is not any better bulwark in the day of battle than a heroic resolution of heart before the day of battle. Sanctified resolutions do exceedingly weaken and discourage Satan in his assaults. They do greatly daunt and dishearten him in all his undertakings against the soul. That man will never long be quiet in his closet who is steadfastly resolved to seek the Lord in a corner, though all the powers of darkness should make head against him. O sirs! Divine fortitude, holy resolutions, will make you like a wall of brass that no arrows can pierce. They will make you like armor of proof that no shot can hurt. They will make you like that angel that rolled away the stone from before the door of the sepulcher (Mat 28:2). They will either enable you to remove the greatest mountains of oppositions that lie between you and closet prayer, or else they will enable you to step over them.

Luther was a man of great resolution and a man that spent much time in closet prayer. And such another was Nehemiah, who met with so much opposition that had he not been steeled by a strong and obstinate resolution he could never have rebuilt the temple but would have sunk in the midst of his works. Now, he was a man for private prayer as I have shown in the beginning of this treatise. Who more resolute than David? And who more for secret prayer than David? The same I might say of Paul, Basil, and many others who have been famous in their generations.

O sirs! Sanctified resolutions for closet prayer will chain you faster to closet prayer than ever Ulysses’ resolutions did chain him to the mast of the ship. It was a noble resolution that kept Ruth close to her mother when her sister Orpah only compliments her, kisses her, and takes her leave of her (Ru 1:10-20). Be but nobly resolved for closet prayer, and then you will keep close to it when others only court it and take their leave of it.

In the Salentine country, there is mention made of a lake that is still brimful. If you put in never so much, it never runs over; if you draw out never so much, it is still full. The resolution of every Christian for closet prayer should be like this lake, still brimful. Tide life tide death, come honor or reproach, come loss or gain, come liberty or bonds, come what can come, the true-bred Christian must be fully and constantly resolved to keep close to his closet.

=== g. Labor for a Greater Effusion of the Holy Spirit
Seventhly, labor for a greater effusion of the Holy Spirit; for the greater measure any man hath of the Spirit of God, the more that man will delight to be with God in secret. “And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications…And the land shall mourn, every family apart; the family of the house of David apart, and their wives apart; the family of the house of Nathan apart, and their wives apart; The family of the house of Levi apart, and their wives apart; the family of Shimei apart, and their wives apart; All the families that remain, every family apart, and their wives apart” (Zec 12:10, 12-14). Mark, in the last of the last days, when men shall be generally under a greater effusion of the Holy Spirit than ever (Joe 2:28-29; Isa 44:3), then they shall be more given up to secret prayer than ever. There will never be such praying apart, and such mourning apart, as there will be when the Lord shall pour out most richly, gloriously, abundantly, of His Spirit upon His poor people. Now, everyone shall pour out his tears and his soul before God in a corner to show the soundness of their sorrow and to show their sincerity by their secrecy, for “He grieves with a witness that grieves without a witness.”

Certainly, the more any man is now under the blessed pouring out of the Spirit of Christ, the more that man gives himself up to secret communion with Christ. Every man is more or less with Christ in his closet as he is more or less under the anointings of the Spirit of Christ. The more any man hath of the Spirit of Christ, the more he loves Christ; and the more any man loves Christ, the more he delights to be with Christ alone. Lovers love to be alone. The more any man hath of the Spirit of Christ, the more his heart will be set to please Christ. Now, nothing pleaseth Christ more than the secret prayers of His people. “O my dove, that art in the clefts of the rock, in the secret places of the stairs, let me see thy countenance, let me hear thy voice; for sweet is thy voice, and thy countenance is comely” (Song 2:14). And therefore, such a one will be much in secret prayer. The more any man hath of the Spirit of Christ, the more his heart will be set upon glorifying and exalting Christ. Now, nothing glorifies Christ more, nor exalts him more, than secret prayer; and therefore, the more any man hath of the Spirit of Christ, the more that man will be found in secret prayer.

There are many persons who say they would be more in their closets than they are, but that they meet with many hindrances, many occasions, many diversions, many temptations, many oppositions, many difficulties, many discouragements which prevent them. Ah, friends! Had you a greater measure of the Holy Spirit upon you, none of these things should ever be able to hinder your secret trade heavenward. Had you a richer anointing of the Spirit upon you, you would never plead, “There is a lion in the way; a lion is in the streets” (Pro 26:13). But were there a thousand lions between you and your closets, you would either step over them or make your way through them that so you might enjoy communion with Christ in your closets.

=== h. Be Frequent in the Serious Consideration of Eternity
Eighthly and lastly, as ever you would keep close to private prayer, be frequent in the serious consideration of eternity. Oh, see eternity standing at the end of every closet prayer, and this will make you pray to purpose in your closets.

O sirs! Every work you do is a step to a blessed or to a cursed eternity. Every motion, every action in this life, is a step toward eternity. As every step that a traveler takes brings him forward to his journey’s end, so every step that a man takes in the secret ways of righteousness and holiness, such as closet duties are, they bring him nearer to his journey’s end. They bring him nearer to a blessed eternity. Look, as every step the sinner takes in a way of wickedness brings him nearer to hell, so every step that a saint takes in a way of holiness brings him nearer to heaven. Look, as every step that a wicked man takes in the ways of unrighteousness brings him nearer to a cursed eternity, so every step that a godly man takes in a way of righteousness brings him nearer to a blessed eternity.

Zeuxis, the famous painter, was so exceeding careful and cautious in drawing all his lines that he would let no piece of his go abroad into the world to be seen of men until he had turned it over and over, and viewed it on this side and that side, again and again, to see if he could spy any fault in it. And being asked the reason why he was so curious and so long in drawing his lines, answered, “I paint for eternity.” O sirs! We all pray for eternity, we fast for eternity, we read for eternity, we hear for eternity, we wait for eternity, we weep for eternity. And therefore, oh, how curiously, how exactly, how wisely, how faithfully, how carefully, how diligently, how unweariedly should we be in all our closet duties and services, seeing that all we do is in order to eternity! Friends! You must all ere long be eternally blessed or eternally cursed; eternally happy or eternally miserable; eternally saved or eternally damned; eternally accepted or eternally rejected. And therefore, what infinite cause have you frequently to shut your closet doors and to plead mightily with God in a corner for the lives of your poor, precious, and immortal souls, that they may be eternally saved in the Great Day of our Lord Jesus. O sirs! When any hindrances to closet prayer present themselves to you, seriously remember eternity, and that will remove them.

It is related of one Pachomius that whensoever he felt any unlawful desires to arise in his mind, he was wont to drive them away with the remembrance of eternity.

The same author relates a story out of #emph[Benedictus Rhexanus] of an ungodly fellow who on a certain night could not sleep, who, upon the serious consideration of death and eternity and the damned lying in hell, could not be at rest, but eternity did still run in his mind. Fain would he have shaken off the thoughts thereof as gnawing worms. Therefore, he followed sports, pastimes, merry-meetings, and sought out companions like himself, and sat oftentimes so long at his cups that he laid his conscience asleep, and so seemed to take some rest. But when he was awakened, his conscience flew in his face and would still be suggesting sad thoughts of eternity to him. Of all things in the world, he could not bear to be kept awake in the night. But so it happened that being sick he was kept awake one night and could not sleep at all, whereupon these thoughts rise in him: “What? Is it so tedious then to be kept from sleep one night and to lie a few hours in the dark? Oh, what is it then to be kept in torments and everlasting darkness! I am here in my own house upon a soft bed in the dark, kept from sleep but one night. But to lie in flames and endless misery, how dreadful must that needs be!” These and such like meditations were the happy means of this young man’s conversion.

I have read a notable story of one Theodorus, a Christian young man in Egypt, who, when there was a great deal of feasting, mirth, and music in his father’s house, withdrew himself from all the company, and being got alone, he thus thought with himself, “Here is content and delight enough for the flesh. I may have what I desire, but how long will this last? This will not hold out long.” Then falling down upon his knees before the Lord in secret, he said, “Lord, my heart is open unto Thee. I indeed know not what to ask but only this: Lord, let me not die eternally. O Lord, Thou knowest I love Thee. Let me live eternally to praise Thee.”

If there be any way or means on earth to bring us upon our knees before God in secret, it is the serious and solemn thoughts of eternity. Oh, that the fear of eternity might fall upon all your souls! Oh, that you would all seriously consider that after a short time is expired you must all enter upon an eternal estate! Oh, consider that eternity is an infinite, endless, bottomless gulf which no line can fathom, no time can reach, no age can extend to, no tongue can express. It is a duration always present, a being always in being. It is “one perpetual day,” which shall never see light. O sirs! This is, and must be, for a lamentation: that eternity is a thing that most men never think of or else very slenderly—a snatch and away, as dogs are said to lap and away at the river Nile. But as ever you would have your hearts chained to your closets and to closet duties—as the men of Tyrus chained their god Apollo to a post that they might be sure of him—then seriously and frequently ponder upon eternity, and with those forty valiant martyrs be still a crying out, “O eternity, eternity!”

Mr. Wood, after some holy discourse, fell a-musing and cried out before all present for near half a quarter of an hour together, “Forever, forever, forever.” Augustine’s prayer was, “Hack me, hew me, burn me here, but spare me hereafter, spare me hereafter.” Certainly, if Christians would but spare one quarter of an hour every day in the solemn thoughts of eternity, it would make them more in love with closet prayer than ever. Yea, it would make them more fearful of omitting closet prayer than ever and more careful and conscientious in the discharge of all closet duties than ever.

And thus, according to my weak measure, I have given out all that at present the Lord hath graciously given in to my poor soul concerning this most necessary, most glorious, and most useful point of points: closet prayer. I shall, by assisting grace, follow this poor piece with my prayers that it may be so blessed from on high as that it may work mightily to the internal and eternal welfare both of reader, hearer, and writer.
