== 4. Means, Rules, and Directions

I have now but one thing more to do before I shut up this discourse, and that is, to lay down some means, rules, or directions that may be of use to help you on in a faithful and conscientious discharge of this great duty of closet prayer. And therefore, thus,

=== a. Take Heed of an Idle and Slothful Spirit

First, as ever you would give up yourselves to private prayer, take heed of an idle and slothful spirit. If Adam in the state of innocence must work and dress the garden, and if after his Fall when he was monarch of all the world he must yet labor, why should any be idle or slothful? Idleness is a sin against the law of creation. God creating man to labor, the idle person violates this law of creation; for by his idleness he casts off the authority of his Creator Who made him for labor. Idleness is a contradiction to the principles of our creation. Man in innocence should have been freed from weariness but not from employment; he was to dress the garden by divine appointment. “And the Lord God took the man, and put him into the garden of Eden to dress it and to keep it” (Gen 2:15). All weariness in labor, and all vexing, tiring, and tormenting labor, came in by the Fall. “In the sweat of thy face shalt thou eat bread” (Gen 3:19). The bread of idleness is neither sweet nor sure. “An idle soul shall suffer hunger,” saith Solomon (Pro 19:15). An idle life and an holy heart are far enough asunder. “By doing nothing,” saith the heathen man, “men learn to do evil things.” It is easy slipping out of an idle life into an evil and wicked life. Yea, an idle life is of itself evil, for man was made to be active, not to be idle. The Cyclops thought man’s happiness did consist #emph[in nihil agendo], in doing nothing, but no excellent thing can be the child of idleness. Idleness is a mother-sin, a breeding-sin. It is #emph[pulvinar diaboli], the devil’s cushion, on which he sits, and the devil’s anvil on which he frames very great and very many sins (Eph 4:28; 2Th 3:10, 12). Look, as toads and serpents breed most in standing waters, so sin thrives most in idle persons. Idleness is that which provokes the Lord to forsake men’s bodies and the devil to possess their souls.

No man hath less means to preserve his body and more temptations to infect his soul than an idle person. Oh, shake off sloth! The sluggish Christian will be sleeping, or idling, or trifling, when he should be in his closet a-praying. Sloth is the green-sickness of the soul; get it cured, or it will be your eternal bane. Of all devils, it is the idle devil that keeps men most out of their closets. There is nothing that gives the devil so much advantage against us as idleness. It was good counsel that Jerome gave to his friend, #emph[Facito aliquid operis, ut te semper Diabolus inveniat occupatum], “Do some work so that the devil always finds you busy,” that when the devil comes with a temptation you may answer him you are not at leisure.

It was the speech of Mr. Greenham, a famous and painful preacher of this nation, that when the devil tempted a poor soul, she came to him for advice how she might resist the temptation, and he gave her this answer: “Never be idle but be always well employed. For in my own experience, I have found it, when the devil came to tempt me, I told him that I was not at leisure to hearken to his temptations; and by this means I resisted all his assaults.” Idleness is the hour of temptation; and an idle person is the devil’s tennis-ball, tossed by him at his pleasure.

“He that labors,” said the old hermit, “is tempted but by one devil, but he that is idle is assaulted by all.” Cupid complained that he could never fasten upon the Muses because he could never find them idle. The fowler bends his bow and spreads his net for birds when they are set, not when they are upon the wing. So Satan shoots his most fiery darts at men when they are most idle and slothful. And this the Sodomites found by woeful experience (Eze 16:49), when God rained hell out of heaven upon them, both for their idleness, and for those other sins of theirs, which their idleness did expose them to.

It was said of Rome that during the time of their wars with Carthage and other enemies in Africa, they knew not what vice meant; but no sooner had they got the conquest but through idleness they came to ruin. Idleness is a sin, not only against the law of grace, but also against the light of nature. You cannot look any way, but every creature checks and upbraids your idleness and sloth. If you look up to the heavens, there you shall find all their glorious lights constant in their motions. The sun “rejoiceth as a strong man to run a race” (Psa 19:5; 104:23). The winds blow, the waters run, the earth brings forth her pleasant and delightful fruits. All the fish in the sea, fowls in the air, and beasts in the fields and on the mountains have their motions and operations, all which call aloud upon man not to be idle, but active.

Solomon sends the sluggard to the ant to learn industry (Pro 6:6). The ant is a very little creature but exceeding laborious. Nature hath put an instinct into her to be very busy and active all the summer; she is early and late at it and will not lose an hour unless the weather hinder. And the prophet Jeremiah sends the Jews to school to learn to wait and observe of the stork, the turtle dove, the crane, and the swallow (Jer 8:7). And our Savior sends us to the sparrows and lilies to learn attendance upon providence (Mat 6:26, 28). And let me send you to the busy bee to learn activity and industry. Though the bee be little in bulk, yet it is great in service. She flies far, examines the fields, hedges, trees, orchards, gardens, and loads herself with honey and wax, and then returns to her hive.

Now how should the activity of these creatures put the idle person to a blush. O sirs! Man is the most noble creature, into whom God hath put principles of the greatest activity, as capable of the greatest and highest enjoyments; and therefore, idleness is a forgetting man’s dignity, a forsaking of that rank that God hath set him in, and a debasing of himself below the least and meanest creatures, who constantly in their order obediently serve the law of their creation. Nay, if you look up to the blessed angels above you, you shall still find them active and serviceable. “Are they not all ministering spirits, sent forth to minister for them who shall be heirs of salvation?” (Heb 1:14). And if you look down to the angels of darkness below you, oh, how laborious and industrious are they to destroy and damn your precious and immortal souls (1Pe 5:8)!

For a close, remember that idleness is so great an evil that it hath been condemned and severely punished by the very worst of men. Among the Egyptians, idleness was a capital crime. Among the Lucans, he that lent money to an idle person was to lose it. By Solon’s law, idle persons were to suffer death. And Seneca had rather be sick than idle. The Lacedaemonians called men to an account for their idle hours. Among the Corinthians, idle persons were delivered to the #emph[carnifex], the executioner.

Antoninus Pius, being emperor, caused the roofs and coverings of all such houses as were known to receive in idle people to be taken away, affirming that nothing was more uncomely, or absurd to be suffered, than such idle caterpillars and slow-worms to have their food and nourishment from that commonwealth in the maintenance of which there was no supply from their industry and labor. All which should steel us and arm us against sloth and idleness. I have the longer insisted on this because there is not a greater hindrance to closet prayer than sloth and idleness. Slothful and idle persons commonly lie so long a-bed and spend so much precious time between the comb and the glass, and in eating, drinking, sporting, and trifling, etc., that they can find no time for private prayer. Certainly, such as had rather go sleeping to hell than sweating to heaven will never care much for closet prayer. And therefore, shun sloth and idleness as you would shun a lion in the way, poison in your meat, or coals in your bosom, or else you will never find time to wait upon God in your closets.

=== b. Take Heed of Spending Your Precious Time about Circumstantials

Secondly, take heed of spending too much of your precious time about circumstantials, about the little things of religion, as “mint and anise and cummin” (Mat 23:23), or in searching into the circumstances of worship, or in standing stoutly for this or that ceremony, and in the mean while neglect the studying of the covenant of grace, or about inquiring what fruit that was that Adam ate in Paradise, or in inquiring after the authors of such and such books, whose names God in His infinite wisdom hath concealed, or in inquiring what God did before the world was made. When one asked Augustine that question, he answered that he was preparing hell for such busy questionists as he was. It was a saying of Luther, “From a vain-glorious doctor, from a contentious pastor, and from unprofitable questions, the good Lord deliver His church.”

It is one of Satan’s great designs to hinder men in the great and weighty duties of religion by busying them most about the lowest and least matters of religion. Satan is never better pleased than when he sees Christians puzzled and perplexed about those things in religion that are of no great moment or importance (Col 2:21). Such as negotiate and trade in religion more for a good name than a good life, for a good report than a good conscience, for to humor others than to honor God, etc., such will take no pleasure in closet duties. Such as are more busied about ceremonies than substances, about the form of godliness than the power (2Ti 3:5), such will never make it their business to be much with God in their closets, as is evident in the scribes and Pharisees (Mat 6:1-6). Such as are more taken up with the outward dress and garb of religion than they are with the spirit, power, and life of religion—such will never affect to drive a secret trade heavenwards (Luk 11:34-40). There cannot be a surer nor a greater character of an hypocrite than to make a great deal of stir about little things in religion and in the mean while neglect the great and main things in religion. Such as these have all along in the Scripture discovered a strangeness and a perfect carelessness as to closet duties. I never knew any man hot and zealous about circumstantials, about the little things of religion, that was ever famous for closet prayer.

=== c. Take Heed of Curiosity in Searching Dark and Abstruse Truths

Thirdly, take heed of curiosity, and of spending too much of your precious time in searching into those dark, abstruse, mysterious, and hidden truths and things of God and religion that lie most remote from the understanding of the best and wisest of men. Curiosity is the spiritual adultery of the soul. Curiosity is a spiritual drunkenness; for look, as the drunkard is never satisfied unless he see the bottom of the cup, be it never so deep, so those that are troubled with the itch of curiosity will say they can never be satisfied until they come to the bottom of the most deep and profound things of God. They love to pry into God’s secrets and to scan the mysteries of religion by their weak, shallow reason and to be wise above what is written. Curious searchers into the deep mysterious things of God will make all God’s depths to be shallows rather than they will be thought not able to fathom them by the short line of their own reason.

Oh, that men would once learn to be contentedly ignorant where God would not have them knowing! Oh, that men were once so humble as to account it no disparagement to them to acknowledge some depths in God and in the blessed Scripture, which their shallow reason cannot fathom! They are only a company of fools in folio that affect to know more than God would have them. Did not Adam’s tree of knowledge make him and his posterity mere fools? He that goes to school to his own reason hath a fool for his schoolmaster. The ready way to grow stark blind is to be still prying and gazing upon the body of the sun; so the ready way to spiritual blindness is to be still prying into the most secret and hidden things of God (Deu 29:29). Are there not many who, by prying long into the secrets of nature, are become archenemies to the grace of God (Rom 9:20)? Oh, that we were wise to admire those deep mysteries which we cannot understand and to adore those depths and counsels which we cannot reach (Rom 11:33).

Oh, let us check our curiosity in the things of God and sit down satisfied and contented to resolve many of God’s actions into some hidden causes which lie secret in the abyss of His eternal knowledge and infallible will. Christ, when He was on earth, very frequently, severely, and sharply condemned curious inquirers, as is evident by these scriptures (Joh 21:22; Act 1:6-7; Luk 13:23-24). And the great reason why our Savior did so frequently check this humor of curiosity was because the great indulgers of it were too frequent neglecters of the more great, necessary, and important points of religion.

Curiosity is one of Satan’s most dangerous engines by which he keeps many souls out of their closets, yea, out of heaven. When many a poor soul begins in good earnest to look towards heaven and to apply himself to closet duties, then Satan begins to bestir himself and to labor with all his might so to busy the poor soul with vain inquiries and curious speculations and unprofitable curiosities that the soul hath no time for closet prayer. Ah! How well might it have been with many a man had he but spent one quarter of that time in closet prayer that he hath spent in curious inquiries after things that have not been fundamental to his happiness.

The heathenish priests affected curiosity; they had their mythologies and strange canting expressions of their imaginary inaccessible deities, to amaze and amuse their blind superstitious followers, and thereby to hold up their popish and apish idolatries in greater veneration. Oh, that there were none of this heathenish spirit among many in these days who have their faces toward heaven! Ah! How many are there that busy themselves more in searching after the reasons of the irrecoverableness of man’s Fall than they do to recover themselves out of their fallen estate! Ah, how many are there that busy themselves more about the apostasy of the angels than they do about securing their interest in Christ! And what a deal of precious time have some spent in discovering the natures, distinctions, properties, and orders of angels.

That high-soaring, counterfeit Dionysius describes the hierarchy of angels as exactly as if he had dwelt among them. He saith there are nine orders of them, which he grounds upon nine words which are found partly in the Old Testament and partly in the New: as seraphims, cherubims, thrones, powers, hosts, dominions, principalities, archangels, and angels. And at large he describes their several natures, distinctions, and properties, as that the first three orders are for immediate attendance on the Almighty, and the next three orders for the general government of the creatures, and the last three orders for the particular good of God’s elect; that the archangel surpasses the beauty of angels ten times, principalities surpass the archangels twenty times, and that powers surpass the principalities forty times, etc. How he came by this learning is not known, and yet this hierarchy in these nine several orders hath passed for current through many ages of the church.

The Platonics were the first that divided the angels into three orders, as, some above heaven, called #emph[supercoelestes]\; others in heaven, called #emph[coelestes]\; and others under heaven, called #emph[subcoelestes], and accordingly they assign them several offices. As,

First, they above heaven, I mean this visible heaven, continually stand before God, as they say, praising, and lauding, and magnifying of His name.

Secondly, they in heaven are there seated to move, rule, and govern the stars.

Thirdly, they under heaven are some to rule kingdoms, others provinces, others cities, others particular men.

Several Christian writers that have written on the hierarchy of angels follow these opinions. Now, if we should take these surmises for real truths, then it will follow that the highest angels do not minister to the saints but only and immediately to God Himself, which is expressly contrary to several scriptures, as you may see by these among others (Jude 1:9; Luk 1:19, 26; Zec 4:10; Rev 5:6; Heb 1:14). When I was upon the ministration of the blessed angels, I did then prove in several exercises, as some of you may remember, that all the angels in heaven were commanded and commissionated by God to be serviceable and useful to the heirs of salvation. “Are they not all ministering spirits, sent forth to minister for them who shall be heirs of salvation?” (Heb 1:14).

The devil knows he is no loser, and the curious soul but a very little gainer, if he can but persuade him to spend most of his precious time in studying and poring upon the most dark, mysterious, and hidden things of God. He that affects to read the Revelation of John more than his plain epistles, or Daniel’s prophecies more than David’s psalms, and is more busy about reconciling difficult scriptures than he is about mortifying of unruly lusts, or that is set more upon vain speculations than upon things that make most for edification, he is not the man that is cut out for closet prayer.

Such as affect sublime notions, obscure expressions, and are men of abstracted conceits are but a company of wise fools that will never take any delight to be with God in a corner. Had many men spent but half that time in secret prayer that they have spent in seeking after the philosopher’s stone, how happy might they have been! Oh, how holy, how happy, how heavenly, how humble, how wise, how knowing, might many men have been had they spent but half that time in closet prayer that they have spent in searching after those things that are “hard to be understood” (2Pe 3:16)!

=== d. Take Heed of Engaging in a Crowd of Worldly Businesses

Fourthly, take heed of engaging yourselves in a crowd of worldly businesses. Many have so much to do on earth that they have no time to look up to heaven. As much earth puts out the fire, so much worldly business puts out the fire of heavenly affections. Look, as the earth swallowed up Korah, Dathan, and Abiram (Num 16:32), so much worldly business swallows up so much precious time that many men have no leisure to be with God in their closets. “This business is to be done, and that business cannot be omitted, and the other necessary occasion must be attended, so that I have no leisure to step out of my shop into my closet,” saith the earthly-minded man (Phi 3:19).

Thus, a crowd of worldly businesses crowds closet prayer quite out of doors. Many drive so great a trade in their shops that their private trade to heaven is quite laid by. There is nothing that hath kept men more from Christ and closet prayer than the shop, the exchange, the farm, and the oxen (Luk 14:16-22). The stars which have least circuit are nearest the pole; and men that are least perplexed with worldly businesses are commonly nearest to God, to Christ, to heaven, and so the fitter for closet prayer. It is sad when men grasp so much business that they can have no leisure for communion with God in a corner. The noise is such in a mill as hinders all private intercourse between man and man; and so a multitude of worldly businesses make such a noise as that it hinders all private intercourse between God and the soul. If a man of much business should now and then slide into his closet, yet his head and his heart will be so filled and distracted with the thoughts of his employments that God shall have little of him but his bodily presence, or, at most, but bodily exercise, which profits little (1Ti 4:8). If Christ blamed Martha for the multitude of her domestical employments (Luk 10:40-42), though they were undertaken for the immediate service and entertainment of Himself, because they hindered her in her soul-concernments, oh, how will He one day blame all those who, by running themselves into a crowd of worldly businesses, do cut themselves off from all opportunities of pouring out their souls before Him in secret.

=== e. Take Heed of Secret Sins

Fifthly, take heed of secret sins. There is no greater hindrance to secret prayer in all the world than secret sins; therefore, stand upon your watch and arm yourselves with all your might against them. There is an antipathy between secret sinning and secret praying, partly from guilt, which makes the soul shy of coming under God’s secret eye; and partly from those fears, doubts, disputes, and disorders that secret sins raise in the heart. Light is not more opposite to darkness, Christ to Belial, nor heaven to hell, than secret prayer is to secret sins; and therefore, whatever you do, look that you keep clear of secret sins. To that purpose consider these four things:

==== 1. God Is Privy to Our Most Secret Sins

First, that God is privy to our most secret sins. His eye is as much upon secret sins as it is upon open sins. “Thou hast set our iniquities before thee, our secret sins in the light of thy countenance” (Psa 90:8). God hath an eye upon our inmost evils; He seeth all that is done in the dark. “Can any hide himself in secret places that I shall not see him? saith the LORD. Do not I fill heaven and earth? saith the LORD” (Jer 23:24). “The eyes of the LORD are in every place, beholding the evil and the good” (Pro 15:3). To say that God doth not see the most secret sins of the children of men is not only derogatory to His omniscience but also to His mercy; for how can God pardon those sins which He doth not see to be sins? There is no cloud, nor curtain, nor moment of darkness, that can stand betwixt the eyes of God and the ways of men. “The ways of man are before the eyes of the LORD, and he pondereth all his goings” (Pro 5:21). In this scripture, Solomon mainly speaks of the ways of the adulterer, which usually are plotted with the most cunning secrecy, yet God seeth all those ways. Look, as no boldness can exempt the adulterer from the justice of God, so no secrecy can hide him from the eye of God. Though men labor to hide their ways from others and from themselves yet it is but labor in vain to endeavor to hide them from God. Men that labor to hide God from themselves can never hide themselves from God.

I have read that Paphnutius converted Thais and Ephron, two famous strumpets, from uncleanness only with this argument, “That God seeth all things in the dark, when the doors are fast, the windows shut, and the curtains drawn.” “Neither is there any creature that is not manifest in his sight: but all things are naked and opened (anatomized) unto the eyes of him with whom we have to do” (Heb 4:13). It is an allusion to the priests under the law, who, when they killed a beast, all things that were within the beast were laid open and naked before the priest that he might see what was sound and what was corrupted. Though evil be done out of the eye of all the world, yet it is naked and manifest in His sight with Whom we have to do.

Those sins which lie closest and are most secretly lurking in the heart are as obvious and odious to God as those that are most fairly written upon a man’s forehead. God is πανόφθαλμος, “all eye”; so that He sees all the most secret turnings and windings of our hearts. Our most secret sins are as plainly seen by Him as anything can be by us at noonday. “If I say, Surely the darkness shall cover me; even the night shall be light about me. Yea, the darkness hideth not from thee; but the night shineth as the day: the darkness and the light are both alike to thee” (Psa 139:11-12). It is not the thickest clouds that can bar out His observance, Whose eyes fill heaven and earth. What is the curtain, or the darkest night, or the double lock, or the secret chamber, to Him Who clearly observes all things in a perfect nakedness. God hath an eye upon the most inward intentions of the heart and the most subtle motions of the spirit. Those philosophers were out that held the eye and care of God descended no lower than the heavens. Certainly, there is not a creature, not a thought, not a thing but lies open to the all-seeing eye of God. The Lord knows our secret sinnings as exactly as our visible sinnings. “He knoweth the secrets of the heart” (Psa 44:21). Would not a malefactor speak truly at the bar did he know, did he believe, that the judge had windows that did look into his breast?

Athenodorus, a heathen, could say that all men ought to be careful in the actions of their life because God was everywhere and beheld all that was done.

Zeno, a wise heathen, affirmed that God beheld even the thoughts.

It was an excellent saying of Ambrose, “If thou canst not hide thyself from the sun, which is God’s minister of light, how impossible will it be to hide thyself from Him Whose eyes are ten thousand times brighter than the sun.” Though a sinner may baffle his conscience, yet he cannot baffle the eye of God’s omniscience. Oh, that poor souls would remember that as they are never out of the reach of God’s hand, so they are never from under the view of His eye. God is #emph[totus oculus], “all eye.” “For mine eyes are upon all their ways: they are not hid from my face, neither is their iniquity hid from mine eyes” (Jer 16:17). “For his eyes are upon the ways of man, and he seeth all his goings. There is no darkness, nor shadow of death, where the workers of iniquity may hide themselves” (Job 34:21-22). “For thine eyes are open upon all the ways of the sons of men: to give every one according to his ways, and according to the fruit of his doings” (Jer 32:19).

You know what Ahasuerus, that great monarch, said concerning Haman, when coming in he found him cast upon the queen’s bed on which she sat. “What?” saith he, “Will he force the queen…before me in the house?” (Est 7:8). There was the killing emphasis in the words “before me.” “Will he force the queen…#emph[before me].” What, will he dare to commit such villainy, and I stand and look on? O sirs! To sin in the sight of God, to do wickedly under the eye of God, is a thing that He looks upon as the greatest affront, and as the highest indignity that can possibly be done unto Him. What, saith He, wilt thou be drunk before Me? Wilt thou swear and blaspheme before Me? Wilt thou be wanton and unclean before Me? Wilt thou be unjust and unrighteous under Mine eye? Wilt thou profane My Sabbaths, and pollute My ordinances before My face? Wilt thou despise and persecute My servants in My presence?

This, then, is the killing aggravation of all sin, that it is done before the face of God, that it is committed in the royal presence of the King of kings—whereas the very consideration of God’s omnipresence should bravely arm us against sin and Satan. The consideration of His all-seeing eye should make us shun all occasions of sin and make us shy of all appearances of sin. Shall the eye of the master keep the scholar from blotting his copy? Shall the eye of the judge keep the malefactor from picking and stealing? Shall the eye of the master keep the servant from idling and trifling? Shall the eye of the father keep the child from wandering and gadding? Shall the eye of the husband keep the wife from extravagancies and indecencies? Shall the sharp eye of wise Cato, or the quick eye of a near neighbor, or the severe eye of a bosom friend keep thee from many enormities and vanities? And shall not the strict, the pure, the jealous eye of an all-seeing God keep thee from sinning in the secret chamber when all curtains are drawn, doors bolted, and everyone in the house a-bed or abroad but thee and thy Delilah? Oh, what dreadful atheism is bound up in that man’s heart who is more afraid of the eye of his father, his pastor, his child, his servant, than he is of the eye, the presence, of the eternal God? Oh, that all whom this concerns would take such serious notice of it as to judge themselves severely for it, as to mourn bitterly over it, as to strive mightily in prayer with God both for the pardon of it and for power against it.

The apostle sadly complains of some in his time who wallowed in secret sins. “For it is a shame even to speak of those things which are done of them in secret” (Eph 5:12). He speaks of such as lived in secret fornications and uncleanness. There were many that had put on a form of godliness who yet did allow themselves in the secret actings of abominable wickedness and filthiness, as if there were no God to behold them, nor conscience to accuse them, nor Judgment Day to arraign them, nor justice to condemn them, nor hell to torment them. Oh! How infinitely odious must they be in the eyes of a holy God who can highly court and compliment Him in public and yet are so bold as to provoke Him to His face in private. These are like those whores who pretend a great deal of affection and respect to their husbands abroad and yet at home will play the harlots before their husbands’ eyes.

Such as perform religious duties only to cloak and color over their secret filthinesses, their secret wickednesses; such as pretend to pay their vows and yet wait for the twilight (Pro 7:13-15; Job 24:15); such as commit wickedness in a corner and yet with the harlot wipe their mouths and say, “What have we done?”—such shall at last find the chambers, the stones out of the wall, the beam out of the timber, the seats they sit on, and the beds they lie on, to witness against all their wanton dalliances, and lascivious carriages in secret (Hab 2:11). “Whoremongers and adulterers God will judge” (Heb 13:4). He will sentence them Himself. And why but because such sinners carry it so closely and craftily that oftentimes none but God can find them out? Magistrates often neglect the punishing of such sinners when their secret wickedness is made known; and therefore, God Himself will sit in judgment upon them. Though they may escape the eyes of men, yet they shall never escape the judgment of God. Heart iniquities fall not under any human sentence. Usually, whoremongers and adulterers are marvelous close and secret and subtle to conceal their abominable filthiness; therefore the harlot is said to be subtle of heart (Pro 7:10). The Hebrew by Rabbi Solomon is translated #emph[munito corde], “and having her heart fenced.” “For,” saith he, “as a city is environed with fortifications, so her heart is fortified round about with subtilty.” Or else it may be rendered #emph[occlusa corde], “fast shut up in the heart, even as close as a besieged city,” that is, “most secret in the subtilty of her heart, how open soever she be in the boldness of her outward carriage.” So the prophet Agur reckoneth the way of a man with a maid and the way of an adulterous woman among those things which neither himself nor any other man was possibly able to discover and find out, and compares it to the way of three things which no wit nor industry of man is able to descry. But yet God seeth all and will bring them to the bar for all (Pro 30:19-20).

==== 2. Secret Sins Shall Be Revealed

Secondly, consider that secret sins shall be revealed. The most hidden works of darkness shall be openly manifested, for though the actings of sin be in the dark, yet the judgings of sin shall be in the light. “For nothing is secret, that shall not be made manifest; neither any thing hid, that shall not be known and come abroad” (Luk 8:17). The slanders of the Jews concerning the magical arts of Christ and His apostles, the horrible lies of the pagans concerning the incestuous copulations of the Christians and their drinking man’s blood, were in time discovered what they were. “God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil” (Ecc 12:14). Mark, he doth not say “some work,” but “every work”; and not only works, but secrets; and not only secrets, but every secret; and not only secret good things but evil too. Whether good works or ill works, whether secret or open, all must be brought to judgment. The books of God’s omniscience and man’s conscience shall then be opened; and then secret sins shall be as legible in thy forehead as if they were written with the most glittering sunbeams upon a wall of crystal. All men’s secret sins are printed in heaven, and God will at last read them aloud in the ears of all the world. “Judge nothing before the time, until the Lord come, who both will bring to light the hidden things of darkness, and will make manifest the counsels of the hearts” (1Co 4:5).

Look, as there are a world of flies and motes in the air which we never see until the sun shines, so there are many thousand thousands of proud thoughts, and unclean thoughts, and worldly thoughts, and malicious thoughts, and envious thoughts, and bloody thoughts, which the world sees not, knows not. But in the Great Day, when the counsels of all hearts shall be manifest, then all shall out, then all shall appear, both to the upper and the lower world. In the great day all masks, vizards, and hoods shall be pulled off, and then all shall out. All that ever thou hast done in the secret chamber, in the dark corner, shall be made known to men and angels, yea, to the whole court of heaven and to all the world beside. “In the day when God shall judge the secrets of men by Jesus Christ” (Rom 2:16). In this Great Day, God will judge not only our words but our works, not only our open works but also our secret works and ways. When Jehoiakim was dead there was found the characters, superstitious marks, and prints of his sorcery upon his body (2Ch 36:8), which shows how deeply idolatry was rooted in his heart, seeing he bare the marks in his flesh during his life. He being a king bore it out bravely and kept all close; but when he was dead, then all came out, then the marks of his abominable idolatry appeared upon his body. Though sinners, though the greatest of sinners, may hide and keep close their horrid abominations for a time; yet there will come a time when all shall out, when all their secret marks and secret abominations shall be obvious to all the world.

But sinners may be ready to object and say, “Let us but alone in our secret sins until that day, and then we shall do well enough.” And therefore,

==== 3. God Many Times Discovers Secret Sins Even in This Life

In the third place, consider that God many times doth, even in this life, discover and make known to the world men’s secret sins (Isa 41:21-23).

God loves to act suitable to His own names. Now, to be “a revealer of secrets” is one of His names (Dan 2:47); and accordingly, even in this world, He often brings to light the most hidden things of darkness.

Of all the glorious attributes of God, there is none that suffers so deeply by secret sins as the attribute of His omniscience; and therefore, in this world God often stands up to vindicate the honor of that attribute by unmasking of sinners and by bringing to the light all those secret paths and ways of wickedness wherein they have long walked undiscovered. It was for the honor of this blessed attribute of God that the secret-plotted sin of Ananias and Sapphira was so openly discovered (Act 5:1-12). “And great fear came upon all the church, and upon as many as heard these things” (Act 5:11).

Joseph’s brethren for a long time hid their malice, their craft, their cruelty, their envy, their treachery, in selling their brother into Egypt; but at last by amazing and amusing providences all was brought to light (Gen 42:21-22; 50:15-22). Conscience, that for a time may seem to be asleep, yet will in time awake and make the sinner know that he is as faithful in recording as he is fearful in accusing; and this Joseph’s brethren found by sad experience.

So Gehazi, he sins secretly, he lies fearfully, and after all he defends it stoutly. But at last all comes out, and instead of being clothed richly, he and his posterity were clothed with a leprosy forever. And instead of two changes of garments, God hangs them up in chains as a monument of His wrath to all generations (2Ki 5:20ff).

So Achan secretly and sacrilegiously steals a goodly Babylonish garment, and two hundred shekels of silver, and a wedge of gold of fifty shekels’ weight, and hides them in the earth in the midst of his tent, and by reason of this, Israel flies before their enemies. But at last Achan is taken, and all comes out, and his golden wedge proved a wedge to cleave him, and his Babylonish garment a garment to shroud him (Jos 7). Joshua makes a bonfire of all that he had secretly and sinfully stolen and in it burns him and his children and all that he had. Oh, how openly, how severely, doth God sometimes punish men for their most secret iniquity!

The same you may see in that great instance of David. “Wherefore hast thou despised the commandment of the LORD, to do evil in his sight? thou hast killed Uriah the Hittite with the sword (this was done in a secret letter), and hast taken his wife to be thy wife…Now therefore the sword shall never depart from thine house; because thou hast despised me, and hast taken the wife of Uriah the Hittite to be thy wife. Thus saith the LORD, Behold, I will raise up evil against thee out of thine own house, and I will take thy wives before thine eyes, and give them unto thy neighbour, and he shall lie with thy wives in the sight of this sun. For thou didst it secretly, but I will do this thing before all Israel, and before the sun” (2Sa 12:9-12; 16:22). David was very studious and very industrious to hide his sin and to save his credit, but the covering made of Uriah’s blood was too short and too narrow to hide his folly with Bathsheba; and therefore, when he had done all he could his sin was tossed like a ball from man to man through court, city, and country.

I have read of one Parthenius, a murderer, treasurer to Theodobert king of France, who, having traitorously slain an especial friend of his called Ausanius with his wife Papianilla, when no man suspected or accused him thereof, he detected and accused himself after this strange manner. As he slept in his bed, suddenly he roared out most pitifully, crying for help, or else he perished; and being demanded what he ailed, he, half asleep, answered that his friend Ausanius and his wife, whom he had slain long ago, summoned him to judgment before God. Upon which confession he was apprehended and, after due examination, stoned to death. Thus the terrors and horrors of his own conscience discovered that secret wickedness which none could prove against him.

I have read how that Mahomet the great Turk had with great rewards procured two Turks to undertake to kill Scanderbeg. These traitors came to Scanderbeg making such a show of the detestation both of Mahomet’s tyrannical government and vain superstition that they were both by Scanderbeg and others reputed to be indeed the men they desired to be accounted; and so after they had learned the principles of the Christian religion, they were both, by their own desire, baptized. Soon after, by a providence, it so fell out that these two traitors fell at variance betwixt themselves, by which means the plot came to be discovered; and after due examination and confession of the fact, they were presently condemned and executed.

Conscience is God’s spy in the bosom. Conscience, as a scribe, a register, sits in the closet of your hearts with pen in hand and makes a diurnal of all your secret ways and secret crimes which are above the cognizance of men. Conscience sets down the time when, the place where, the manner how, and the persons with whom such and such secret wickednesses have been committed—and that so clear and evident that, go where you will and do what you can, the characters of them shall never be cancelled or razed out until God appear in judgment.

Let a man sin in the closest retirement that human policy can contrive; let him take all the ways he can to hide his sins, to cloak and cover his sin, as Adam did, yet conscience will so play the judge that it will bring in the evidence, produce the law, urge the penalty, and pass the sentence of condemnation upon him. There is many a man who makes a fair profession and who hath a great name in the world who yet is αὐτοκατάκριτος, self-condemned for those secret sins which are not obvious to the eyes of man nor punishable by the laws or hands of men. Yea, many times in this life, God raiseth such a hell of horror and terror in many men’s consciences by reason of their secret sins that they can have no rest nor quiet, neither at bed nor at board, neither lying down nor rising up. Fain would they conceal their sins, unwilling they are that the world should know how vile they have been in secret. But conscience being upon the rack and still a-gnawing, accusing, and condemning of them, they can hold no longer. Now all must out, and now those sins that were most secret and concealed come to be published upon the housetop.

Some that have been under anguish of conscience, others that have been smitten with a frenzy, and many in their very sleep, have been often the blazers and proclaimers of their own secret filthiness and wickedness. In those cases, God hath made many a secret sinner cry out with the leper, “Unclean, unclean” (Lev 13:45), and with Judas before all present, “I have sinned, I have sinned” (Mat 27:4). Many times in this life, God doth very strangely and wonderfully discover those secret works of darkness in which persons have lived long undiscovered.

A Pythagorean bought a pair of shoes upon trust. The shoemaker dies; he is glad, thinks them gained. But a while after his conscience flies upon him and becomes a continual chider and tormentor of him. He hereupon repairs to the house of the dead, casts in his money with these words: “There, take thy due; thou livest to me, though dead to all besides.” But,

==== 4. Secret Sins Are in Some Respects More Dangerous Than Open Sins

Fourthly, consider that secret sins are in some respects more dangerous than open sins. Many a man bleeds to death inwardly, and no man perceives it. The more inward and secret the disease is, the more the man is in danger to lose his life. There are no fevers so dangerous as those that prey upon the spirits and inward parts; so there are no sins so dangerous and pernicious to the souls of men as those that are most inward and secret. Secret sins often reign in the souls of men most powerfully when least apparently.

First, consider that he who sins secretly deprives himself of those helps and remedies which, by a divine blessing, might arm him against sin, yea, make him victorious over sin, to wit, the prayers, counsels, reproofs, examples, and encouragements of friends, relations. A man’s house may be on fire, but whilst it is all inward, help comes not in. But when the fire flames out, when it catcheth the outside of the house, then help runs in; then help on all hands is ready. He that sins in secret debars himself of all public remedy and takes great pains to damn his soul in a corner and to go to hell in the dark.

Secondly, secret sins will make way for public sins. He that makes no conscience of sinning in the secret chamber will ere long, with Absalom, be ready to spread a tent upon the top of the house and to go in to his concubines in the sight of all Israel (2Sa 12:11). Such as have made no conscience of stealing a few pins or pence or a few shillings in private have in time come to be so bold as to take a purse on the road at high noon. The cockatrice must be crushed in the egg, else it will soon become a serpent. The very thought of sin, if not thought on, will break forth into action, action into custom, custom into habit, and then both body and soul are irrecoverably lost to all eternity.

If Satan can but wound our heel, as the poets feign of Achilles, he will make a hard shift, but he will send death from the heel to the heart. If this subtle serpent can but wriggle in his tail by an ill thought, he will soon get in his head by a worse action. Hence it is that Christ calls hatred murder, and a wanton eye adultery. Secret hatred often issues in open murder, and secret wanton glances of the eye do often issue in visible adultery. If Amnon be sick with the sinful conceptions of incestuous lust, how will his soul be in pain and travail until he hath brought forth! And how many are there that in secret have taken now and then but one cup more than enough, who now may be seen at high noon reeling against every post. Look, as secret diseases in the body, if not cured, will in time openly break forth, so secret sins in the soul, if not pardoned and purged, will in time be openly revealed. Covetousness was Judas’ secret sin; and no sooner doth an occasion or a temptation present itself, but he is very ready and forward to betray and sell his Lord and Master for thirty pieces of silver before all the world. “When lust hath conceived, it bringeth forth sin” (Jam 1:15)—and that thus:

First, sin hath its conception, and that is delight.

And then its formation, and that is design.

And then its birth, and that is action.

And then its growth, and that is custom.

And then its end, and that is damnation.

Thirdly, secret sinning puts far more respect and fear upon men than upon God. Thou wilt be unjust in secret, and wanton in secret, and unclean in secret, and treacherous in secret, and why but because thou art afraid that such or such men should know it, or that such and such friends should know it, or that such and such relations should know it? Ah! Poor wretch, art thou afraid of the eye of a man, “of a man that shall die, and of the son of man which shall be made as grass” (Isa 51:12)? And yet not tremble under His eye “whose eyes are as a flame of fire,” sharp and terrible, such as pierce into the inward parts (Rev 1:14; Heb 4:12-13)? Ah! How full of atheism is that man’s heart that tacitly saith, “If my sins be but hid from the eyes of the world I do not care though the Lord knows them, though the Lord strictly observes them, though the Lord sets a mark, a memorandum, upon them.” What is this, O man, but to brave it out with God, and to tempt Him, and provoke Him to His very face Who “is light, and in him there is no darkness at all” (1Jo 1:5)? Ah! Sinner, sinner, can man damn thee? Can man disinherit thee? Can man fill thy conscience with horrors and terrors? Can man make thy life a very hell? Can man bar the gates of glory against thee? Can man speak thee into the grave by a word of his mouth? And after all, can man cast thee into endless, easeless, and remediless torments? Oh, no! Can God do all this? Oh, yes! Why, then, doth not thy heart stand more in awe of the eye of the great God than it doth of the eye of a poor, weak, mortal man?

I have insisted the longer on this particular because there is not any one thing in all the world that doth more hinder secret communion with God and secret prayer than secret sins. And oh, that you would all make it your great business to watch against secret sins, and to pray against secret sins, and to mourn over secret sins, and deeply to judge and condemn yourselves for secret sins, and carefully and conscientiously to shun and avoid all occasions and provocations that may be as fuel to secret sins.

Certainly, there are no men or women that are so sincere and serious in closet prayer, or that are so frequent, so fervent, so constant in closet prayer, or that are so delightful, so resolute, so undaunted, or so unwearied in closet prayer, as those that keep themselves most clear and free from secret sins.

For a close, remember this: that though secret sins are in some respects more dangerous than other sins are, yet in three respects they are not so bad nor so dangerous as other sins are.

First, in that they do not so scandalize religion as open sins do.

Secondly, in that they do not shame, grieve, and wound the hearts of the saints as open sins do.

Thirdly, in that they are not so infectious to others, nor such provocations to others to sin against the Lord as open sins are.

And thus you may see what those things are that you must carefully take heed of, as ever you would addict yourselves to closet prayer.
