== 2. Christ Much Exercised Himself in Secret Prayer

Secondly, consider, when Christ was on earth He did much exercise Himself in secret prayer. He was often with God alone, as you may see in these famous scriptures: “And when he had sent the multitudes away, he went up into a mountain apart to pray: and when the evening was come, he was there alone” (Mat 14:23). Christ’s choosing solitudes for private prayer doth not only hint to us the danger of distraction and deviation of thoughts in prayer, but how necessary it is for us to choose the most convenient places we can for private prayers. Our own fickleness and Satan’s restlessness call upon us to get into such corners where we may most freely pour out our souls into the bosom of God. “And in the morning, rising up a great while before day, he went out, and departed into a solitary place, and there prayed” (Mar 1:35). As the morning time is the fittest time for prayer, so solitary places are the fittest places for prayer. “And when he had sent them away, he departed into a mountain to pray” (Mar 6:46). He that would pray to purpose had need be quiet when he is alone. “And he withdrew himself into the wilderness, and prayed” (Luk 5:16). The Greek, He “was departing and praying,” to give us to understand that He did thus often. When Christ was neither exercised in teaching nor in working of miracles, He was then very intent on private prayer. “And it came to pass in those days, that he went out into a mountain to pray, and continued all night in prayer to God” (Luk 6:12). Did Christ spend whole nights in private prayer to save our souls; and shall we think it much to spend an hour or two in the day for the furtherance of the internal and eternal welfare of our souls?

“And in the day time he was teaching in the temple; and at night he went out, and abode in the mount that is called the mount of Olives” (Luk 21:37). Christ frequently joins praying and preaching together, and those whom Christ hath joined together, let no man presume to put asunder. “And he came out, and went, as he was wont, to the mount of Olives; and his disciples also followed him…And he was withdrawn from them about a stone’s cast, and kneeled down, and prayed…And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood (clotted or congealed blood) falling down to the ground (never was garden watered before or since with blood as this was). And when he rose up from prayer, and was come to his disciples, he found them sleeping for sorrow” (Luk 22:39, 41, 44-45). Ah! What sad pieces of vanity are the best of men in an hour of trial and temptation! These very men that a little before did stoutly profess and promise that they would never leave Him nor forsake Him, and that they would go to prison for Christ, and die for Christ, yet when the day of trial came, they could not so much as watch with Him one hour. They had neither eyes to see nor hands to wipe off Christ’s bloody sweat. So John 6:15-17. Thus you see, by all these famous instances, that Christ was frequent in private prayer. Oh, that we would daily propound to ourselves this noble pattern for our imitation, and make it our business, our work, our heaven, to write after this blessed copy that Christ hath set us: to be much with God alone. Certainly, Christianity is nothing else but an imitation of the divine nature, a reducing of a man’s self to the image of God in which he was “created in righteousness and true holiness” (Eph 4:24). A Christian’s whole life should be nothing but a visible representation of Christ. The heathens had this notion amongst them, as Lactantius reports, that the way to honor their gods was to be like them. Sure I am that the highest way of honoring Christ is to be like to Christ: “He that saith he abideth in him ought himself also so to walk, even as he walked” (1Jo 2:6). Oh, that this blessed Scripture might always lie warm upon our hearts. Christ is the sun, and all the watches of our lives should be set by the dial of His motion. Christ is a pattern of patterns; His example should be to us instead of a thousand examples. It is not only our liberty, but our duty and glory, to follow Christ in all His moral virtues absolutely. Other patterns are imperfect and defective, but Christ is a perfect pattern; and of all His children, they are the happiest that come nearest to this perfect pattern.

Heliogabalus loved his children the better for resembling him in sin. But Christ loves His children the more for resembling Him in sanctity. I have read of some springs that change the color of the cattle that drink of them into the color of their own waters, as Du Bartas sings:

Cerona, Xanth, and Cephisus do make

The thirsty flocks, that of their waters take,

Black, red, and white; and near the crimson deep,

The Arabian fountain maketh crimson sheep.

Certainly, Jesus Christ is such a fountain, in which whosoever bathes, and of which whosoever drinks, shall be changed into the same likeness (2Co 3:18).

#emph[Question]. But why was our Lord Jesus so much in private prayer? Why was He so often with God alone?

#emph[Answer 1]. First, it was to put a very high honor and value upon private prayer; it was to enhance and raise the price of this duty. Men naturally are very apt and prone to have low and undervaluing thoughts of secret prayer. But Christ, by exercising Himself so frequently in it, hath put an everlasting honor and an inestimable value upon it.

#emph[Answer 2]. Secondly, He was much in private prayer, He was often with God alone, that He might not be seen of men, and that He might avoid all shows and appearances of ostentation and popular applause. He that hath commanded us to “abstain from all appearance of evil” (1Th 5:22) would not Himself, when He was in this world, venture upon the least appearance of evil. Christ was very shy of everything that did but look like sin; He was very shy of the very show and shadow of pride or vain glory.

#emph[Answer 3]. Thirdly, to avoid interruptions in the duty. Secrecy is no small advantage to the serious and lively carrying on of a private duty. Interruptions and disturbances from without are oftentimes quench-coals to private prayer. The best Christians do but bungle when they meet with interruptions in their private devotions.

#emph[Answer 4]. Fourthly, to set us such a blessed pattern and gracious example, that we should never please nor content ourselves with public prayers only, nor with family prayers only, but that we should also apply ourselves to secret prayer, to closet prayer. Christ was not always in public, nor always in His family, but He was often in private with God alone, that by His own example He might encourage us to be often with God in secret. Happy are they that tread in His steps and that write after His copy.

#emph[Answer 5]. Fifthly, that He might approve Himself to our understandings and consciences to be a most just and faithful High Priest (Heb 2:17; Joh 17). Christ was wonderfully faithful and careful in both parts of His priestly office: satisfaction and intercession. He was His people’s only spokesman. Ah! How earnest, how frequent was He in pouring out prayers, and tears, and sighs, and groans for His people in secret, when He was in this world (Heb 5:7). And now He is in heaven, He is still a-making intercession for them (Heb 7:25).

#emph[Answer 6]. Sixthly, to convince us that His Father hears and observes our private prayers, and bottles up all our secret tears, and that He is not a stranger to our closet desires, wrestlings, breathings, hungerings, and thirstings.
