== 13. Private Prayer in Times of Great Straits and Trials

Consider that in times of great straits and trials, in times of great afflictions and persecutions, private prayer is the Christian’s meat and drink. It is his chief city of refuge; it is his shelter and hiding place in a stormy day. When the saints have been driven by violent persecutions into holes, and caves, and dens, and deserts, and howling wildernesses, private prayer hath been their meat and drink, and under Christ their only refuge. When Esau came forth with hostile intentions against Jacob, secret prayer was Jacob’s refuge. “And the messengers returned to Jacob, saying, We came to thy brother Esau, and also he cometh to meet thee, and four hundred men with him, all cut-throats. Then Jacob was greatly afraid and distressed: and he divided the people that was with him, and the flocks, and herds, and the camels, into two bands; And said, If Esau come to the one company, and smite it, then the other company which is left shall escape” (Gen 32:6-8). When all is at stake, it is Christian prudence to save what we can, though we cannot save what we would. “And Jacob said, O God of my father Abraham, and God of my father Isaac, the LORD which saidst unto me, Return unto thy country, and to thy kindred, and I will deal well with thee” (v. 9). Promises in private must be prayed over. God loves to be sued upon His own bond, when He and His people are alone. “Deliver me, I pray thee, from the hand of my brother, from the hand of Esau: for I fear him, lest he will come and smite me, and the mother with the children” (v. 11)—or “upon the children,” meaning he will put all to death. Some look upon the words to be a metaphor taken from fowlers who kill and take away the young and the dams together contrary to that old law (Deu 22:6). Others say it is a phrase that doth most lively represent the tenderness of a mother, who, seeing her children in distress, spares not her own body nor life to hazard the same for her children’s preservation, by interposing herself, even to be massacred together with and upon them (Hos 10:14). When Jacob and all that was near and dear unto him was in eminent danger of being cut off by Esau and those men of blood that were with him, he betakes himself to private prayer as his only city of refuge against the rage and malice of the mighty.

And so, when Jeremiah was in a solitary and loathsome dungeon, private prayer was his meat and drink; it was his only city of refuge. “Moreover, the word of the LORD came unto Jeremiah the second time, while he was yet shut up in the court of the prison, saying, Thus saith the LORD the maker thereof, the LORD that formed it, to establish it; The LORD is his name; Call unto me, and I will answer thee, and shew thee great and mighty,” or hidden “things, which thou knowest not” (Jer 33:1-3). When Jeremiah was in a lonesome, loathsome prison, God encourages him by private prayer to seek for further discoveries and revelations of those choice and singular favors which in future times He purposed to confer upon His people.

“Wherefore the LORD brought upon them the captains of the host of the king of Assyria, which took Manasseh among the thorns, and bound him with fetters,” or chains, “and carried him to Babylon. And when he was in affliction, he besought the LORD his God, and humbled himself greatly before the God of his fathers, And prayed unto him: and he was intreated of him, and heard his supplication, and brought him again to Jerusalem into his kingdom. Then Manasseh knew that the LORD he was God” (2Ch 33:11-13). When Manasseh was in fetters in his enemy’s country, when he was stripped of all his princely glory and led captive into Babylon, he betakes himself to private prayer as his only city of refuge; and by this means he prevails with God for his restoration to his crown and kingdom.

Private prayer is a city of refuge that no power nor policy, no craft nor cruelty, no violence nor force, is ever able to surprise. Though the joint prayers of the people of God together were often obstructed and hindered in the times of the ten persecutions, yet they were never able to obstruct or hinder secret prayer, private prayer. When men and devils have done their worst, every Christian will be able to maintain his private trade with heaven. Private prayer will shelter a Christian against all the national, domestical, and personal storms and tempests that may threaten him. When a man is lying upon a sick-bed alone, or when a man is in prison alone, or when a man is with Job left upon the dunghill alone, or when a man is with John banished for the testimony of Jesus into this or that island alone, oh, then private prayer will be his meat and drink, his shelter, his hiding-place, his heaven. When all other trades fail, this trade of private prayer will hold good.
