== 6. God Lets Out Himself Most to His People in Secret

Sixthly, consider that God hath usually let out Himself most to His people when they have been in secret, when they have been alone at the throne of grace. Oh the sweet meltings, the heavenly warmings, the blessed cheerings, the glorious manifestations, and the choice communion with God that Christians have found when they have been alone with God in a corner, in a closet, behind the door! When had Daniel that vision and comfortable message, that blessed news by the angel that he was “greatly beloved,” but when he was all alone at prayer? “And whiles I was speaking, and praying, and confessing my sin, and the sin of my people Israel, and presenting my supplication before the LORD my God for the holy mountain of my God; Yea, whiles I was speaking in prayer, even the man Gabriel, whom I had seen in the vision at the beginning, being caused to fly swiftly, touched me about the time of the evening oblation. And he informed me, and talked with me, and said, O Daniel, I am now come forth to give thee skill and understanding. At the beginning of thy supplications the commandment came forth, and I am come to shew thee; for thou art greatly beloved: therefore understand the matter, and consider the vision” (Dan 9:20-23). While Daniel was at private prayer, God, by the angel Gabriel, reveals to him the secret of His counsel concerning the restoration of Jerusalem and the duration thereof, even to the Messiah. And while Daniel was at private prayer, the Lord appears to him, and in an extraordinary way assures him that he was a man “greatly beloved,” or as the Hebrew #emph[chumudoth] hath it, “a man of desires,” that is, a man whom God’s desires are towards, a man singularly beloved of God, and highly in favor with God, a man that is very pleasing and delightful to God. God loves to lade the wings of private prayer with the sweetest, choicest, and chiefest blessings. Ah! How often has God kissed a poor Christian at the beginning of private prayer, and spoken peace to him in the midst of private prayer, and filled him with light and joy and assurance upon the close of private prayer?

And so, Cornelius is highly commended and graciously rewarded upon the account of his private prayer. “There was a certain man in Caesarea called Cornelius, a centurion of the band called the Italian band, A devout man, and one that feared God with all his house, which gave much alms to the people, and prayed to God alway. He saw in a vision evidently about the ninth hour of the day an angel of God coming in to him, and saying unto him, Cornelius. And when he looked on him, he was afraid, and said, What is it, Lord? And he said unto him, Thy prayers and thine alms are come up for a memorial before God…And Cornelius said, Four days ago I was fasting until this hour (that is, until three o’clock in the afternoon, v. 3); and at the ninth hour I prayed in my house, and, behold, a man stood before me in bright clothing, And said…Thy prayer is heard, and thine alms are had in remembrance in the sight of God” (Act 10:1-4, 30-31). Mark, as he was praying in his house, namely, by himself alone, a man in bright clothing (that was an angel in man’s shape, v. 3) appeared to him, and said, “Cornelius, thy prayer is heard” (v. 31). He doth not mean only that prayer which he made when he fasted and humbled himself before the Lord; but, as verses 2-4 show, his prayers, his prayers which he made alone. For it seems none else were with him then, for he only saw that man in bright clothing; and to him alone the angel addressed his present speech, saying, “Cornelius, thy prayer is heard” (v. 31). Here you see that Cornelius’ private prayers are not only heard, but kindly remembered, and graciously accepted, and gloriously rewarded. Praying Cornelius is not only remembered by God, but he is also visited, sensibly and evidently, by an angel, and assured that his private prayers and good deeds are an odor, “a sweet smell, a sacrifice acceptable, and wellpleasing to God” (Phi 4:18).

And so when did Peter have his vision but when he was praying alone on the housetop? “On the morrow, as they went on their journey, and drew nigh unto the city, Peter went up unto the housetop to pray about the sixth hour: And he became very hungry, and would have eaten: but while they made ready, he fell into a trance, And saw heaven opened, and a certain vessel descending unto him, as it had been a great sheet knit at the four corners, and let down to the earth: Wherein were all manner of fourfooted beasts of the earth, and wild beasts, and creeping things, and fowls of the air. And there came a voice to him, Rise, Peter; kill, and eat” (Act 10:9-13). When Peter was upon the housetop at prayer alone, then he fell into a trance, and he saw heaven opened; and then he had his spirit raised, his mind elevated, and all the faculties of his soul filled with a divine revelation.

And so when Paul was at prayer alone, he saw “in a vision a man named Ananias coming in and putting his hand on him, that he might receive his sight” (Act 9:12). Paul had not been long at private prayer before it was revealed to him that he was a chosen vessel, and before he was filled with the gifts, graces, and comforts of the Holy Ghost.

And when John was alone in the isle of Patmos “for the word of God, and for the testimony of Jesus Christ” (Rev 1:9), whither he was banished by Domitian (Rev 1:9; 5:1-9), a most cruel emperor, then he had a glorious sight of the Son of Man, and then the Lord discovered to him most deep and profound mysteries, both concerning the present and future state of the church, to the end of the world. And when John was weeping, in private prayer doubtless, then the sealed book was opened to him.

So when Daniel was at private prayer, God dispatches a heavenly messenger to him, and his errand was to open more clearly and fully the blessed Scripture to him. Some comfortable and encouraging knowledge this holy man of God had attained unto before by his frequent and constant study in the Word, and this eggs him on to private prayer, and private prayer posts an angel from heaven to give him a clearer and fuller light. Private prayer is a golden key to unlock the mysteries of the Word unto us. The knowledge of many choice and blessed truths are but the returns of private prayer. The Word most dwells richly in their hearts who are most in pouring out their hearts before God in their closets. When Bonaventure, that seraphical doctor, as some call him, was asked by Aquinas from what books and helps he derived such holy and divine expressions and contemplations, he pointed to a crucifix, and said, “Prostrate in prayer at the feet of this image, my soul receiveth greater light from heaven than from all study and disputation.” Though this be a monkish tradition and superstitious fiction, yet some improvement may be made of it. Certainly, that Christian or that minister that in private prayer lies most at the feet of Jesus Christ shall understand most of the mind of Christ in the gospel, and he shall have most of heaven and the things of his own peace brought down into his heart.

There is no service wherein Christians have such a near, familiar, and friendly intercourse with God as in this of private prayer; neither is there any service wherein God doth more delight to make known His truth and faithfulness, His grace and goodness, His mercy and bounty, His beauty and glory to poor souls, than this of private prayer. Luther professed that he profited more in the knowledge of the Scripture by private prayer in a short space than he did by study in a longer space, as John by weeping in a corner got the sealed book opened. Private prayer crowns God with the honor and glory that is due to His name; and God crowns private prayer with a discovery of those blessed weighty truths to His servants that are a sealed book to others. Certainly, the soul usually enjoys most communion with God in secret. When a Christian is in a wilderness, which is a very solitary place, then God delights to speak friendly and comfortably to him. “Behold, I will allure her, and bring her into the wilderness, and speak friendly or comfortably unto her” (Hos 2:14), or as the Hebrew hath it, “I will speak to her heart.” When I have her alone, saith God, in a solitary wilderness, I will speak such things to her heart as shall exceedingly cheer her, and comfort her, and even make her heart leap and dance within her. A husband imparts his mind most freely and fully to his wife when she is alone; and so doth Christ to the believing soul. Oh, the secret kisses, the secret embraces, the secret visits, the secret whispers, the secret cheerings, the secret sealings, the secret discoveries, etc., that God gives to His people when alone, when in a hole, when under the stairs, when behind the door, when in a dungeon! When Jeremiah was calling upon God alone in his dark dungeon, he had great and wonderful things showed him that he knew not of (Jer 33:1-3).

Ambrose was wont to say, “I am never less alone than when I am alone; for then I can enjoy the presence of my God most freely, fully, and sweetly, without interruption.”

And it was a most sweet and divine saying of Bernard, “O saint, knowest thou not that thy husband Christ is bashful, and will not be familiar in company? Retire thyself therefore by prayer and meditation into thy closet or the fields, and there thou shalt have Christ’s embraces.”

A gentlewoman, being at private prayer and meditation in her parlor, had such sweet, choice, and full enjoyments of God that she cried out, “Oh, that I might ever enjoy this sweet communion with God!”

Christ loves to embrace His spouse, not so much in the open street, as in a closet; and certainly the gracious soul hath never sweeter views of glory than when it is most out of the view of the world. Wise men give their best, their choicest, and their richest gifts in secret; and so doth Christ give His the best of the best when they are in a corner, when they are all alone. But as for such as cannot spare time to seek God in a closet, to serve Him in secret, they sufficiently manifest that they have little fellowship or friendship with God, Whom they so seldom come to.
