== 12. God Hath Chosen You to Reveal His Secrets To

Twelfthly, consider you are the only persons in all the world that God hath made choice of to reveal His secrets to. “Henceforth I call you not servants; for the servant knoweth not what his lord doeth: but I have called you friends; for all things that I have heard of my Father I have made known unto you” (Joh 15:15). Everything that God the Father had communicated to Christ as mediator to be revealed to His servants, He did make known to His disciples as to His bosom friends. Christ loves His people as friends, and He uses them as friends, and He opens His heart to them as friends. There is nothing in the heart of Christ that concerns the internal and eternal welfare of His friends, but He reveals it to them. He reveals Himself, His love, His eternal good will, the mysteries of faith, and the secrets of His covenant to His friends. Christ loves to entertain His friends with things that are not commonly and vulgarly known. Christ will reveal the secrets of His mind, the secrets of His love, the secrets of His thoughts, the secrets of His heart, and the secrets of His purposes, to all His bosom friends. Samson could not hide his mind, his secrets, from Delilah, though it cost him his life (Jdg 16:15-17); and do you think that Christ can hide His mind, His secrets, from them for whom He hath laid down His life? Surely not. O sirs! Christ is

- a universal friend,
- an omnipotent friend, an almighty friend. He is no less than thirty times called Almighty in that book of Job; He can do above all expressions and beyond all apprehensions.
- He is an omniscient friend.
- He is an omnipresent friend.
- He is an indeficient friend.
- He is an independent friend.
- He is an unchangeable friend.
- He is a watchful friend.

- He is a tender and compassionate friend.
- He is a close and faithful friend.

Therefore, He cannot but open and unbosom Himself to all His bosom friends. To be reserved and close is against the very law of friendship. Faithful friends are very free in imparting their thoughts, their minds, their secrets, one to another. A real friend accounts nothing worth knowing unless he makes it known to his friends. He rips up his greatest and most inward secrets to his friends. Job calls his friends “inward friends,” or the men of his secrets (Job 19:19). All Christ’s friends are inward friends; they are the men of His secrets. “His secret is with the righteous” (Pro 3:32); that is, His covenant and fatherly affection, which is hid and secret from the world. He that is righteous in secret, where no man sees him, he is the righteous man, to whom God will communicate His closest secrets, as to His dearest bosom friend. It is only a bosom friend to whom we will unbosom ourselves. “The secret of the LORD is with them that fear him; and he will shew them his covenant” (Psa 25:14).

Now, there are three sorts of divine secrets:

(1) First, #emph[there are secrets of providence], and these He reveals to the righteous and to them that fear Him (Psa 107:43; Hos 14:9). The prophet Amos speaks of these secrets of providence: “Surely the Lord GOD will do nothing, but he revealeth his secret unto his servants the prophets” (Amo 3:7). Micah knew the secret of the Lord touching Ahab, which neither Zedekiah nor any other of the false prophets knew. “And the LORD said, Shall I hide from Abraham that thing which I do?” (Gen 18:17). The destruction of Sodom was a secret that lay in the bosom of God; but Abraham being a bosom friend, God communicates this secret to him (vv. 19-21). Abraham was a friend, a faithful friend, a friend by a specialty (Jam 2:23); and therefore, God makes him both of His court and counsel. Oh, how greatly doth God condescend to His people. He speaks to them as a man would speak to his friend; and there are no secrets of providence, which may be for their advantage, but He will reveal them to His faithful servants. As all faithful friends have the same friends and the same enemies, so they are mutual in the communication of their secrets one to another; and so it was between God and Abraham.

(2) Secondly, #emph[there are the secrets of His kingdom], and these He reveals to His people. “It is given unto you to know the mysteries of the kingdom of heaven, but to them it is not given…At that time Jesus answered and said, I thank thee, O Father, Lord of heaven and earth, because thou hast hid these things from the wise and prudent, and hast revealed them unto babes” (Mat 13:11; 11:25). “Let us not think,” saith Jerome, “that the gospel is in the words of Scripture, but in the sense; not in the outside, but in the marrow; not in the leaves of words, but in the root of reason.” Augustine humbly begged of God that if it were His pleasure, He would send Moses to him to interpret some more abstruse and intricate passages in his book of Genesis. There are many choice, secret, hidden, and mysterious truths and doctrines in the gospel, which Christ reveals to His people, that this poor, blind, ignorant world are strangers to. There are many secrets wrapped up in the plainest truths and doctrines of the gospel, which none can effectually open and reveal but the Spirit of the Lord, that “searcheth all things, yea, the deep things of God” (1Co 2:10). There are many secrets and mysteries in the gospel that all the learning and labor in the world can never give a man insight into. There are many that know the doctrine of the gospel, the history of the gospel, that are mere strangers to the secrets of the gospel. There is a secret power, a secret authority, a secret efficacy, a secret prevalence, a secret goodness, a secret sweetness in the gospel, that none experience but those to whom the Lord is pleased to impart gospel secrets to. “Seal the law among my disciples” (Isa 8:16; 29:11-12). The law of God to wicked men is a sealed book that they cannot understand (Dan 12:9-10). It is as blotted paper that they cannot read. Look, as a private letter to a friend contains secret matter that no man else may read because it is sealed; so the law of grace is sealed up under the privy seal of heaven, so that no man can open it or read it except Christ’s faithful friends to whom it is sent. The whole Scripture, saith Gregory, is but one entire letter dispatched from the Lord Christ to His beloved spouse on earth. The rabbins say that there are four keys that God hath under His girdle: 1) the key of the clouds; 2) the key of the womb; 3) the key of the grave; 4) the key of food. I may add a fifth key that is under His girdle, and that is the key of the Word, the key of the Scripture; which key none can turn but “he that hath the key of David, he that openeth, and no man shutteth; and shutteth, and no man openeth” (Rev 3:7).

O sirs! God reveals Himself and His mind and will and truth to His people in a more friendly and familiar way than He doth to others. “And he said unto them, Unto you it is given to know the mystery of the kingdom of God: but unto them that are without, all these things are done in parables…And he said, Unto you it is given to know the mysteries of the kingdom of God: but to others in parables; that seeing they might not see, and hearing they might not understand” (Mar 4:11; Luk 8:10). Though great doctors, and profound clerks, and deep-studied but unsanctified divines may know much of the doctrines of the gospel, and commend much the doctrines of the gospel, and dispute much for the doctrines of the gospel, and glory much in the doctrines of the gospel, and take a great deal of pains to dress and trim up the doctrines of the gospel, with the flowers of rhetoric or eloquence; though it be much better to present truth in her native plainness than to hang her ears with counterfeit pearls (the Word, without human adornments, is like the stone #emph[Garamantides] that hath drops of gold in itself, sufficient to enrich the believing soul), yet the special, spiritual, powerful, and saving knowledge of the doctrines of the gospel is a secret, a mystery, yea, a hidden mystery to them (Rom 16:25; 1Co 2:7).

Chrysostom compares the mysteries of Christ, in regard of the wicked, to a written book that the ignorant can neither read nor spell. He sees the cover, the leaves, and the letters, but he understands not the meaning of what he sees. He compares the mystery of grace to a dictated epistle, which an uneducated person viewing, he cannot read it, he cannot understand it. He knoweth it is paper and ink, but the sense, the matter, he knows not, he understands not. So unsanctified persons, though they are never so learned, and though they may perceive the bark of the mystery of Christ, yet they perceive not, they understand not, the mystery of grace, the inward sense of the Spirit in the blessed Scriptures. Though the devil be the greatest scholar in the world, and though he have more learning than all the men in the world have, yet there are many thousand secrets and mysteries in the gospel of grace that he knows not really, spiritually, feelingly, efficaciously, powerfully, thoroughly, savingly.

Oh, but now Christ makes known Himself, His mind, His grace, His truth, to His people, in a more clear, full, familiar, and friendly way. “For thou, O LORD of hosts, God of Israel, hast revealed to thy servant” (2Sa 7:27). So you read it in your books; but in the Hebrew it is thus: “Lord, thou hast revealed this to the ear of thy servant.” Now, the emphasis lieth in that word, “to the ear,” which is left out in your books. When God makes known Himself to His people, He revealeth things to their ears, as we use to do to a friend who is intimate with us: we speak a thing to his ear. There is many a secret which Jesus Christ speaks in the ears of His servants, which others never come to be acquainted with. “God, who commanded the light to shine out of darkness, hath shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ” (2Co 4:6).

The six several gradations that are in this scripture are worthy of our most serious consideration. Here is:

First, knowledge;

Second, the knowledge of the glory of God;

Third, the light of the knowledge of the glory of God;

Fourth, shining;

Fifth, shining into our hearts; and,

Sixth, shining into our hearts in the face of Jesus Christ.

And thus, you see that the Lord reveals the secrets of Himself, His kingdom, His truth, His grace, His glory, to the saints.

(3) Thirdly, there are #emph[the secrets of His favor], the secrets of His special love that He bears to them, the secret purposes of His heart to save them. And these are those great secrets, those “deep things of God,” which none can reveal “but the Spirit of God” (1Co 2:10-11). Now these great secrets, these deep things of God, God doth reveal to His people by His Spirit. “But God hath revealed them unto us by his Spirit: for the Spirit searcheth all things, yea, the deep things of God. For what man knoweth the things of a man, save the spirit of man which is in him? even so the things of God knoweth no man, but the Spirit of God. Now we have received, not the spirit of the world, but the spirit which is of God; that we might know the things that are freely given to us of God” (1Co 2:10-12). Now what are the things that are freely given to us of God, but our election, vocation, justification, sanctification, and glorification? And why hath God given us His Spirit, but that we should know “the things that are freely given to us of God” (v. 12)? Some by “secret” in the 25th Psalm do understand a particular assurance of God’s favors whereby happiness is secured to us, both for the present and for the future. They understand by “secret” the sealing of the Spirit, the hidden manna, the white stone, and the new name in it, which none knoweth but he that hath it. And so much those words, “He will shew them his covenant,” seem to import (Psa 25:14); for what greater secret can God impart to His people than that of opening the covenant of grace to them in its freeness, fulness, sureness, sweetness, suitableness, everlastingness, and in sealing up His good pleasure and all the spiritual and eternal blessings of the covenant to them? Such as love and serve the Lord shall be of His cabinet council, they shall know His soul secrets, and be admitted into a very gracious familiarity and friendship with Him. “He that hath my commandments, and keepeth them, he it is that loveth me: and he that loveth me shall be loved of my Father, and I will love him, and will manifest myself to him. Judas saith unto him, not Iscariot, Lord, how is it that thou wilt manifest thyself unto us, and not unto the world? Jesus answered and said unto him, If a man love me, he will keep my words: and my Father will love him, and we will come unto him, and make our abode with him” (Joh 14:21-23). God and Christ will keep house with them and manifest the secrets of Their love to them that are observant of Their commands. And thus, you see that the saints are the only persons to whom God will reveal the secrets of His providence, the secrets of His kingdom, and the secrets of His love unto. Christ came out of the bosom of His Father, and He opens all the secrets of His Father only to His bosom friends.

Now what an exceeding high honor is it for God to open the secrets of His love, the secrets of His promises, the secrets of His providences, the secrets of His counsels, and the secrets of His covenant to His people! Tiberius Caesar thought no man fit to know his secrets. And among the Persians none but noblemen, lords, and dukes might be made partakers of state secrets. They esteemed secrecy a godhead, a divine thing, as Ammianus Marcellinus affirms. But now such honor God hath put upon all His saints as to make them lords and nobles and the only privy statesmen in the court of heaven. The highest honor and glory that earthly princes can put upon their subjects is to communicate to them their greatest secrets. Now this high honor and glory the King of kings hath put upon His people. “The secret of the LORD is with them that fear him; and he will shew them his covenant” (Psa 25:14). It was a high honor to Elisha that he could tell the secrets that were spoken in the king’s bedchamber (2Ki 6:12). Oh, what an honor must it then be for the saints to know the secrets that are spoken in the presence-chamber of the King of kings!

Now I appeal to the very consciences of all that fear the Lord, whether it be not a just, equal, righteous, and necessary thing that the people of God should freely and fully lay open all the secrets of their hearts before the Lord, Who hath thus highly honored them as to reveal the secrets of His providence, kingdom, and favor to them? Yea, I appeal to all serious and ingenuous Christians, whether it be not against the light and law of nature, and against the law of love, and law of friendship, to be reserved and close, yea, to hide our secrets from Him Who reveals His greatest and His choicest secrets to us? And if it be, why then do not you in secret lay open all your secret sins, and secret wants, and secret desires, secret fears, etc., to Him that seeth in secret? You know all secrets are to be communicated only in secret. None but fools in folio will communicate secrets upon a stage or before many.
