== 19. Satan Is a Very Great Enemy to Secret Prayer

Consider that Satan is a very great enemy to secret prayer. Secret prayer is a scourge, a hell, to Satan. Every secret prayer adds to the devil’s torment, and every secret sigh adds to his torment, and every secret groan adds to his torment, and every secret tear adds to his torment. When a child of God is on his knees in his secret addresses to God, oh, the strange thoughts, the earthly thoughts, the wandering thoughts, the distracted thoughts, the hideous thoughts, the blasphemous thoughts, that Satan often injects into his soul, and all to wean him from secret prayer, and to weary him of secret prayer! Sometimes he tells the soul that it is in vain to seek God in secret. And at other times he tells the soul it is too late to seek God in secret, for the door of mercy is shut and there is no hope, no help, for the soul. Sometimes he tells the soul that it is enough to seek God in public; and at other times he tells the soul that it is but a precise trick to seek the Lord in private. Sometimes he tells the soul that it is not elected, and, therefore, all his secret prayers shall be rejected. And at other times he tells the soul that it is sealed up unto the day of wrath, and, therefore, a secret prayer can never reverse that seal. All this to dishearten and discourage a poor Christian in his secret retirements. Sometimes Satan will object to a poor Christian the greatness of his sins; and at other times he will object against a Christian the greatness of his unworthiness. Sometimes he will object against a Christian his want of grace; and at other times he will object against a Christian his want of gifts to manage such a duty as it should be managed. Sometimes he will object against a Christian his former straitenedness in secret prayer; and at other times he will object against a Christian the small yearnings that he makes of secret prayer. All to work the soul out of love with secret prayer, yea, to work the soul to loathe secret prayer, so deadly an enemy is Satan to secret prayer. Oh, the strange fears, fancies, and conceits that Satan often raises in the spirits of Christians when they are alone with God in a corner, and all to work them to cast off private prayer.

It is none of Satan’s least designs to interrupt a Christian in his private trade with God. Satan watches all a Christian’s motions so that he cannot turn into his closet, nor creep into any hole to converse privately with his God, but he follows him hard at heels, and will be still injecting one thing or another into the soul, or else objecting one thing or another against the soul. A Christian is as well able to tell the stars of heaven and to number the sands of the sea as he is able to number up the several devices and sleights that Satan uses to obstruct the soul’s private addresses to God. Now from that great opposition that Satan makes against private prayer, a Christian may safely conclude these five things:

(1) First, the #emph[excellency] of private prayer. Certainly, if it were not an excellent thing for a man to be in secret with God, Satan would never make such head against it.

(2) Second, the #emph[necessity] of this duty. The more necessary any duty is to the internal and eternal welfare of a Christian, the more Satan will bestir himself to blunt a Christian’s spirit in that duty.

(3) Third, the #emph[utility] or profit that attends a conscientious discharge of this duty. Where we are like to gain most, there Satan loves to oppose most.

(4) Fourth, the #emph[prevalence] of private prayer. If there were not a kind of omnipotence in it, if it were not able to do wonders in heaven, and wonders on earth, and wonders in the hearts and lives and ways of men, Satan would never have such an aching tooth against it as he hath.

(5) Fifth, that #emph[God is highly honored] by this duty, or else Satan would never be so greatly enraged against it. This is certain. The more glory God hath from any service we do, the more Satan will strive by all his wiles and sleights to take us either off from that service or so to interrupt us in that service that God may have no honor, nor we no good, nor himself no hurt, by our private retirements.
