== 20. You Are the Lord’s Secret Ones, His Hidden Ones

In the last place, consider that you are only the Lord’s secret ones, His hidden ones; and therefore, if you do not apply yourselves to private prayer and to your secret retirements that you may enjoy God in a corner, none will. It is only God’s hidden ones, His secret ones, that are spirited, principled, and prepared to wait on God in secret. “Then shall ye be a peculiar treasure unto me above all people” (Exo 19:5). The Hebrew word signifieth God’s special jewels, God’s proper ones, or God’s secret ones that He keeps in store for Himself and for His own special service and use. Princes lock up with their own hands in secret their most precious and costly jewels; and so doth God His. “For the LORD hath chosen Jacob unto himself, and Israel for his peculiar treasure” (Psa 135:4), or for His secret gem. “They have taken crafty counsel against thy people, and consulted against thy hidden ones” (Psa 83:3), or Thy secret ones—so called partly because God hides them in the secret of His tabernacle (Psa 31:20) and partly because God sets as high a value upon them as men do upon their hidden treasure, their secret treasure. Yea, He makes more reckoning of them than He doth of all the world besides. And so the world shall know when God shall arise to revenge the wrongs and injuries that have been done to His secret ones.

Neither are there any on earth that know so much of the secrets of His love, of the secrets of His counsels, of the secrets of His purposes, of the secrets of His heart, as His secret ones do. Neither are there any in all the world that are under those secret influences, those secret assistances, those secret incomes, those secret anointings of the Spirit, as His secret ones are under. And therefore, no wonder if God calls them again and again and again His “secret ones.” Now, what can be more comely or more desirable than to see their natures and their practices to answer to their names? They are the Lord’s secret ones, His hidden ones; therefore, how highly doth it concern them to be much with God in secret and to hide themselves with God in a corner! Shall Nabal’s nature and practice answer to his name? “Let not my lord, I pray thee, regard this man of Belial, even Nabal: for as his name is, so is he; Nabal is his name, and folly is with him” (1Sa 25:25). Nabal signifies a fool, a sot, a churl; it notes one that is void of wisdom and goodness. It signifieth one whose mind, reason, judgment, and understanding are withered and decayed. Now, if you look into the story, you shall find that as face answers to face, so Nabal’s nature and practice did echo and answer to his name. And why then should not our natures and practices answer to our names also? We are called the Lord’s secret ones, His hidden ones; and how highly therefore doth it concern us to be much with God in secret!

Why should there be any jarring or discord between our names and our practices? It is observable that the practice and carriage of other saints have been answerable to their names. Isaac signifies laughter, and Isaac was a gracious son, a dutiful son, a son that kept clear of those abominations with which many of the patriarchs had defiled themselves, a son that proved matter of laughter to his father and mother all their days. So, Josiah signifies “the fire of the Lord,” and his practice did answer to his name. Witness the pulling down of Jeroboam’s altar, and his burning of the vessels that were made for Baal, and his pulling down the idolatrous priests whom the kings of Judah had set up, and his burning the grove at the brook Kedron, and his stamping it to powder, and his breaking down the houses of the sodomites, and his defiling of the high places where the priests had burnt incense, and his breaking in pieces the images, and cutting down the groves, and filling their places with the bones of men, etc. (1Ki 13:2; 2Ki 23:4-21). So, Joshua signifies “a savior,” and his practice was answerable to his name. Though he could not save his people from their sins, yet he often saved them from their sufferings. Great and many were the deliverances, the salvations, that were instrumentally brought about by Joshua, as all know that have read the book of Joshua. So, John signifies “gracious,” and his practice was answerable to his name. He was so gracious in his teachings and in his walkings that he gained favor in the very eyes of his enemies.

By all these instances, and by many more that might be given, you see that other saints’ practices have answered to their names; and, therefore, let every one of us look that our practices do also answer to our names, that as we are called the Lord’s secret ones so we may be much with God in secret, that so there may be a blessed harmony between our names and our practices, and we may never repent another day that we have been called God’s secret ones, His “hidden ones” (Psa 83:3), but yet never made conscience of maintaining secret communion with God in our closets.

Thus, you see that there are no less than twenty arguments to persuade you to closet prayer and to maintain private communion with God in a corner.
