== Motives to Press the Duty of the Minister’s Maintenance, with an Answer to Other Objections

1\. Consider well, and remember that your pastors are the ministers; nay, the ambassadors of Jesus Christ; such who represent his sacred majesty, and have his commission, for what they act and do in his name, and dispense the mysteries of God to you, according to their duty; therefore the Lord Jesus will account that done to himself, which is done to his ministers: #emph[he that receiveth you] (saith he) #emph[receiveth me, and he that despiseth you, despiseth me, Mat.] 10:40. #emph[Luke] 10:16. If the name and authority of Christ will beget an awe in you, or his matchless and unspeakable love influence your souls; there is no doubt but his word will abide upon you, and cause you to discharge the duty we have pressed upon your spirits. If you acknowledge a religious respect and reverence due to the Son of God, exercise it in a humble obedience to his word; and if you love him and value his gospel, treat not his ministers in an unworthy manner: have you not called them off from other business? And are they not your servants? And is not from thence a gospel maintenance due to them from you, as is the wages of your other servants? Tho we fear some give more to the meanest servants in their house, than they do give to the ministers of Christ.

2\. ’Tis evident, they have a great charge committed to their trust, #emph[they watch for your souls, as they who must give an account, Heb.] 13:17. And therefore you ought to consider them, and pity them, and endeavour to assist them, and put them into the best capacity you are able to do, that they may make full proof of their ministry, and #emph[be free from the blood of all men;] ’tis the business of your own salvation, and concern of your precious and immortal souls, that your ministers are employed in; and therefore ’tis much more your own interest than his, and from hence ought to make conscience of your duty; for if they can't #emph[give their account with joy, that will not be profitable for you:] and how can they give an account of joy concerning you, when you have neglected one great and indispensable duty, by which means they were rendered unable to perform their work, as became them? Nor can indeed the ministry ever be effectual to your souls, if you be not sincere in obedience under it: besides, as one observes, will you be less careful for your souls, and their eternal welfare, than for your bodies, and the comforts of a temporal life? Can you be content to lay out your strength and substance to provide for these, and neglect the other? Is it not sad, saith one to consider, #emph[How many there are among professors, that live in this world, as if there were no truth in the report of that which is to come, and have the meanest esteem of the most necessary means of salvation?] Viz. #emph[The word and ordinances of Christ, and a gospel ministry; some can expend perhaps an hundred pounds] per annum, #emph[more or less, for ornaments or delights to adorn a frail carcass, but will grudge half so much for the poor saints, or to the support of the worship of the gospel, and his sinking interest.]

3\. Consider how many temptations and soul discouraging weaknesses your ministers lie under continually, both from within and without, if sensible of the greatness of their work; and of their own insufficiency: you know not their fears, their cares, their tears, and how hard they are put to it to keep up in their work, finding such strong oppositions made against them by the enemy, continually, so that you had need to strengthen, comfort, and encourage them, as much as you can; and not to add to their sorrow, and make them serve you in wants and necessities.

4\. We might tell you also what the apostle says in respect of his liberty as a minister, in forbearing to work at all: will any of you say your ministers must labour and provide for themselves, when God hath ordained the contrary; and also when the apostle saith, he had power to forbear working? See 1 #emph[Cor.] 9:6. #emph[Or I only and] Barnabas, #emph[Have we not power to forbear working? We certainly] (as well as the rest of Christ's ministers) #emph[if we will run out to the utmost end of the line of our liberty in things, without having regard to your circumstances, might forbear working with our hands, and expect that those among whom we labour should maintain it.] So the #emph[annotators] render it. Now, you would think this a hard thing, should any of your pastors make use of their liberty; yet if they should do it, provided they were faithful in their work and office, knowing also your ability, we would know whether any of you could charge them with sin, as we know you may and ought other persons, who work not; and though the apostle did sometimes work, it was of choice, and to prevent the glorying of those false apostles, and for some other reasons, which upon special circumstances for that time he mentioneth, and yet he accounts it amongst his afflictions.

Quest. #emph[Ought a pastor or minister to make terms with the church about his maintenance, before he take the charge of them?]

#emph[Answ.] We assert for no such thing, he is to take the charge freely, and of a ready mind: but we say there is as indispensable a duty lies upon the people to provide carnal or temporal good things for him, as there lies upon him to provide spiritual good things for them, and to give him grounds to believe they will be faithful to Christ and to him, in their duty upon that account.

Quest. #emph[But what shall that church do, who are not able to allow a sufficient maintenance to their pastor?]

#emph[Answ.] We have a three-fold answer to this question.

#emph[First,] if through the poverty of the church they cannot provide for their minister, they may make their case and circumstance known to other sister churches, and desire their aid and assistance herein; but if they can have none, and the church do their duty to the utmost themselves, and yet they are not able to supply his necessities, then he must be contented to suffer with the church. But

2\. If God bless a congregation with a plentiful portion of this world's good, it is their duty to make their ministers a party with them in their flourishing condition (and as a late author saith) #emph[Considering the place and employment he is in, and the service he attends, it would be extremely unworthy to think they have done enough, if his pressing necessities be answered; whilst they themselves abound in superfluities.] But if the congregation be poor, and there is no helps to be had, then their minister must and ought to be content to be poor with them; yea, rejoice to approve himself a minister of Christ, (as #emph[Paul] did) by hunger and nakedness, if the providence of God call him thereto; but whilst it is in the power of their hands to provide better for him, God expects it from them; and let none deceive themselves, #emph[God is not mocked,] nor will he suffer his commands to be slighted and evaded, without rendering a just rebuke to the offender, #emph[For whatsoever a man soweth that shall he reap.] Yet necessity is laid upon Christ's ministers, and woe be to them if they preach not the gospel.

3\. It may deserve our most mature consideration, whether a people may safely constitute themselves into a church state, when not able to provide for a ministry, especially as the case may be circumstanced; for possibly they might very well join themselves to another congregation near unto them, and be a great help to such a church, being embodied with them. And this we do say, for a people to put themselves into a church state, is one of the most weightiest things in the world, and ought with as great care and consideration to be done; we concluding in some places where there are many churches near to each other, it would be far better for some of those small and insufficient societies to unite themselves to some other congregation; and by that means the weight of those indispensable duties and obligations that are incumbent on them, would with much more ease be borne and answered, to the honour of Christ, reputation of the gospel, and their own edification: moreover, if all Christians ought to consider whether they may or ought to put themselves into a church state, except they have persons fitly qualified and furnished with gifts and graces for the ministry; which if they may not safely do, then by the same parity of reason ought they to consider whether they may proceed therein, if they know their own insufficiency in respect of their making a gospel provision for their maintenance, unless they live remote from any other church, and so necessity put them upon their so doing.

Obj. #emph[But is not this to build, that which you yourselves have destroyed,] viz. #emph[have you not disclaimed against such who preach for hire?]

#emph[Answ.] We never went about we hope to destroy any institution or ordinance of Jesus Christ, as the minister's maintenance is, as has sufficiently been proved. But for men to preach for hire, to make that their end, we mean in preaching the gospel, we still utterly disclaim any such practice, and say ’tis a low, carnal, and base end and design, and unworthy of any Christian man.

2\. We have always disowned, or do disclaim against #emph[tithes] or the #emph[tenths] of men's increase, declaring that #emph[they] are not the right of any gospel ministers by the #emph[Law of Jesus Christ,] or the due of the ministers of the #emph[New Testament,] by the appointment of the Lord Jesus; being only a #emph[Mosaical rite,] and that law to be abrogated, as #emph[Aaron's] priesthood is.

3\. We have always disowned and declared against such ministers, who use to strive to compel men by outward force to pay them what they call their dues, it looking so much like an Antichristian spirit and practice, and not agreeable to the gospel of Jesus Christ; were love to Christ, and the sense of duty, we find ought to be the only prevailing argument to excite and provoke every man to his duty in this great case. Moreover you must take heed you are not prejudiced against your duties from mistaken and false conclusions; because some will not preach unless you put into their mouths, and so make a mere trade of preaching. Will you not answer the requirement of God to those who are the faithful ministers of his word? Because some will not relieve their poor, unless they are forced to do it, will you disown your duty to the poor saints, and not relieve them, but object and say, ’tis too much like the national practice? Or, do you not like #emph[preaching] after that manner, #emph[i.e.] with a text, doctrine, reasons, and application; because such, and such do so, whom you disown, and cannot have communion with. Let all such weak #emph[objections] be avoided, and mentioned no more for ever.

Object. #emph[You have we fear over-done it; for though we do believe ’tis the duty of the churches to allow to their pastors a comfortable maintenance, who are low in the world, and so exposed to the distracting cares of this life, and thereby hindered in the discharge of their duty in the ministry. Yet for rich men who need it not, to have an allowance, we see no reason for that.]

#emph[Answ.] We answer, it is not an act of charity (to ministers that are poor) we plead for, but we have proved it is an ordinance of God, he hath been pleased #emph[to ordain, that those who preach the gospel should live of the gospel:] ’tis their due as they are #emph[Christ's] ministers; he is their portion now, as well as formerly under the law, and have therefore as much right to it, as you have to your inheritance; and from hence he willed them when he first sent them out, #emph[to take no money in their purses,] etc. And therefore the state of such you speak of, can't exempt you from that ordinance, nor your duty to them; besides, is it fitting (think you) that such ministers who have estates should waste their substance, and injure their children in their faithfulness to Christ in preaching the gospel, and in the services of your souls: for their work is such, that it calls for all their time and uttermost diligence (in a right discharge of their duty therein) and therefore thereby they are prevented of improving what they have, for the future comfort and advantage of their families: nay, and we have heard to our great trouble, how some worthy men, who have laboured fully to improve their ministry (through the people's neglect of their duty to them) have in process of time sunk in their estates, and in truth have been brought to a low condition; for ’tis rare to see a pastor of our churches to abound in riches: tho some (blessed be God) may be indifferent well to pass in the world: now to expose a rich man to poverty, or to let a poor man shift for himself under wants and necessities, are evils much of the like nature: and for a prevention of both, God hath ordered it so, that neither of these things should, or ought to be. Therefore this neglect (in short) exposeth ministers to temptations (considering the moral duty that lies upon them, in common with other men to provide for their families) namely, to content themselves in doing but one part of their work, #emph[viz.] to preach a sermon or two in the week, #emph[etc.] Now our desires are that they may all be wholly sequestered to the Lord's work and service; and not be other ways employing themselves, when they should be preaching the kingdom of God, but to labour to fulfill their ministry they have received of the Lord, so that they may have their accounts to give up with joy in the day of Christ.

Object. #emph[But our church is small, and our pastor can't take up all his time in the Lord's work.]

#emph[Answer.] We answer, if he wants work, who will hinder him from following of his secular business, provided he doth faithfully and fully discharge every part of the duty of his place and #emph[function?] But do not the neighbouring villages, and places adjacent want the gospel, having no bread for their souls, and this too by reason such pastors are unconcerned in this matter? And by which means ’tis doubtless that the glorious gospel is no more promulgated up and down in dark and blind corners of this nation, nor the church increases no more; besides do not many poor sinners daily perish hereby for want of knowledge? Brethren, ’tis not for ourselves, but for the Lord, and his sinking interest that we plead for; it grieves our souls to hear what cries there are in many parts of this kingdom for want of bread, some being forc'd, we hear, to go twelve or sixteen miles to hear a sermon; now if ministers of churches made it their whole business to preach the word, and concern themselves for the promoting of the truth, it would not be as it is at this very time; nor can we think it should be otherwise, unless we had a travelling ministry (which we fear we shall hardly find) unless pastors and teachers in the respective churches were taken off of all encumbrances, and so give themselves up to the ministry of the word.

God has done great things for us, and hath opened a mighty door, and shall not we do some great thing for him? The case, blessed be the Lord, is much altered: you may come now into any town and none dare forbid you, (if any one will but entertain you) and preach the gospel; and shall we not take care to answer this mercy; and do what we can that the poor blind world may be enlightened, and brought to the saving knowledge of Jesus Christ? If the present #emph[providence] of God be not answered by a due improvement to his glory, and the furtherance of the gospel: we may say with #emph[Solomon, Why is there a price in the hand of a fool, seeing he hath no heart to it,] Prov. 17:16. By this time we hope you may more clearly understand us, and what we drive at, and earnestly desire to see accomplished, #emph[viz.] that ministers may not only bear that name, but with all faithfulness do the work, they are called to; ’tis not to press our people to minister to such preachers who are idle and negligent in their business, whose hearts and hands are in the world, and eagerly pursue their own secular affairs, and matter not what becomes of the interest of Jesus Christ.

No, ’tis to encourage the faithful and laborious person, who is willing to give himself up to the Lord, in the discharge of that great trust committed to him, and to labour indeed in Christ's vineyard; it is in truth a shame for a minister to receive the Lord's wages, and not do the Lord's work; some there are in the world that do not deserve the name of ministers they doing the work of the Lord so deceitfully.

Our churches also are ’tis like in some places in the country but small, and are like to be smaller, if the ministry be not awakened to become more laborious: are there not such in some towns, who are hardly known by the inhabitants to be ministers at all, they are so little concerned in preaching, they are better known to be #emph[farmers, yeomen,] and #emph[tradesmen,] than preachers of the gospel; they are entangled so in the affairs of this life, that they have but little time to mind the great work they are called to: we would ask some ministers, whether they could not do much more, preach oftener, and in more places, and take greater pains, to promote the gospel, and gather in souls to Christ, than they do? Certainly they will and must say, yea, we might; why what is the reason of your not doing it? Ought we not with #emph[Mary] to do what we can? We conclude, this omission of duty either arises from the evil of your own hearts, or else from the remissness and neglect of the people, in respect of their duty to you. (1.) It may arise from the evil in your own hearts, in that you have not or do not espouse the interest of Jesus Christ, equal with, or above your own: can any be contented in doing a little service for Christ, tho his interest sinks in their hands; whilst they thrive in their own concerns, and grow rich in the world: Lord, what will become of such ministers in the day of judgment? Can they think to look Christ in the face with comfort, that have been such slothful servants; but God forbid there should be any among us who mind more their own trifling affairs, than the great work and business of their blessed Lord and master? Is this #emph[the making full proof of your ministry you have received of the Lord?] Christ's ministers are called #emph[labourers,] but we fear some labour but little, unless it be at their own work: should you be as remiss in your own affairs, as possibly you are in the Lord's, you would find quickly a decay in your estates, and be in a sinking condition in the world; which ’tis like, would soon startle you, and stir you up to greater care and industry; and ought you not to be as considerate in the great concernment of Christ, his gospel and churches? We take it not upon us to reprehend any of you but in love (as fellow servants may do) to caution you; pray remember, you have the most sacred interest and matters of Jesus Christ committed to your trust; ’tis the greatest charge in the world, and you and we must be called to an account, if souls perish in their sins, and #emph[the watchman gives not suitable warning, the blood of those sinners God will require at the watchman's hands,] Ezek. 3. Ministers ought to be the light of the world, they should shine therefore in life and doctrine, to all round about where they live, that the people may know they have a #emph[Noah,] a preacher of righteousness amongst them. But

2\. This grand fault may arise from the people's remissness of duty to their ministers; for hark, do we not hear many worthy and faithful pastors crying out? Alas brethren, we are no more in the Lord's work, no more in preaching, in visiting, #emph[etc.] because our families would suffer want, and what is necessary for them; we should gladly make the gospel our whole business, and not only watch over, and feed our own flocks, but preach the gospel up and down in towns and villages, lying near us, if we knew how our wives and children might be provided for; for should we neglect that great moral and indispensable duty, how would the holy name of God be reproached? Alas, our souls are bowed down in us, we must confess, we have daily calls to preach, in this and that place, where to this day there has hardly been any meeting; but we are not able to do it, and therefore, we are forc'd to send to #emph[London,] that some ministers might come down into our parts, to answer that great call and cry of men and women, for want of the bread of life.

This is a hard case indeed, #emph[i.e.] for the servants of Christ to have the due sense of the greatness of their work upon their hearts, but cannot discharge it according as they see there is a call and occasion, by reason the people neglect their duty to them: but however, do what you can, and venture out, God will provide for you, and move upon the hearts of such you preach the gospel to, or some other way provide for you: improve this present liberty, and do not #emph[let the Lord's house lie waste:] remember, #emph[Necessity is laid upon you, and woe be to you, if you preach not the gospel,] be not unbelieving, but trust the providence of God; great things he expecteth from us, who has so gloriously and graciously appeared for us, and for the land of our nativity.

Nevertheless, let none mistake us; we do not say, ’tis unlawful for preachers to work or follow callings; but as preaching doth not make working unlawful, neither should any worldly business hinder preaching, therefore when working with our hands will further the gospel, we may work; we have a call so to do (which was once #emph[Paul]'s case) but when working at trades and callings, does palpably tend to the hindrance of the promulgation of the gospel; we must give over such working, and wholly give up ourselves to preaching #emph[etc.] ’Tis but to make an expediment, if the people should fail you: you know your liberty, he that laboured with his hands, hath by that example set the consciences of ministers at liberty, to provide for the necessities of this life, by other employments, when they cannot live of the gospel; but this very thing #emph[Paul] accounted amongst his afflictions; and certainly, it must needs be a sore grief and exercise to any godly preacher in this respect, #emph[i.e.] when he hears people calling him, one day to this town to preach, and another day to that, and he finds he cannot answer neither of their calls, through the necessities of his family; and the truth is, all do readily grant, that no positive duty can discharge a man from the obligations of that pure moral and universal duty of providing for his families.

Brethren, you know when the harvest proves catching, and the painful and laborious harvest-men are taken off of their business, then they may do a little work for themselves, but when ’tis good harvest weather, and the harvest is great, and the labourers but few, they must stick to it and labour hard.

Even so when the late #emph[storms of persecution] were upon us, many of #emph[Christ's spiritual harvest-men] were much hindered and taken off of their work, and did may be employ themselves otherwise, in their other affairs (few being willing to open their doors to them;) but now the providence of God has opened a great door for the gospel, and sent us blessed harvest weather, and the labourers alas! being also very few, though the harvest is very great: how ought we to stick to our business?

There was never certainly such a call to ministers to work for God as there is now; therefore that servant that will not do his #emph[best] at such an hour, is like #emph[the son] (that #emph[Solomon] speaks of) #emph[that sleeps in harvest and so causeth shame.] And as a wise husband-man will not neglect a fit opportunity of gathering in his corn, upon presumption of much fair weather to come: so ought not we to lose the present season for gathering in souls to Christ, not knowing how soon clouds may rise, and another storm overtake us, when we cannot work for God as now we may; and if you have not such encouragement as you ought to have from the people, yet remember when night comes, the Lord Jesus will well reward you for all the pains you take in his work; yet since our Saviour saith the labourer is worthy of his hire, we can't think any (when they consider the matter a little better) will any way obstruct, or hinder you in your business through their neglect of duty to you.

Object. #emph[But doth not Christ tell his disciples? As they had freely received, so they should freely give.]

#emph[Answ.] We believe this text is not taken, or understood according to the meaning of our Saviour; for it cannot mean that Christ's ministers should receive neither money, meat, or clothes, whilst they are employ'd in his work and service, because in the very next verse he bids them #emph[Provide neither gold nor silver, nor brass in their purses, nor two coats, nor scrip for their journey;] because he plainly intimates all such things they were worthy of, and might expect them from the people to whom they preached. Therefore ’tis an horrible abuse put upon the text, to take the words in that sense; as if our blessed master should forbid his servants to receive a maintenance from the people; for then indeed they might have said, Lord, if we must preach so freely as not to receive any thing, it behoveth us to provide well for our journey; but since they were forbid to do so, it is clear that could not be our Saviour's meaning: besides, such a sense is directly opposite or repugnant to those other precepts the Lord Jesus hath laid down by his apostles in the #emph[epistles;] wherein it is positively asserted (as you have heard) that #emph[He that is taught in the word ought to communicate to him that teacheth in all good things,] Gal. 6:6. #emph[And that they who minister at the altar should partake of the altar; God having ordained that he that preaches the gospel, should live of the gospel,] 1 Cor. 9:14. Therefore we rather are of the opinion (in respect to this text) with a late worthy writer; #emph[The doctrine] (says he) #emph[they were to preach, they were empowered to confirm with miracles; which] #emph[He gives them a charge they should work freely, without receiving any reward for them; that the miracles might not be used to their private profit, but to the end they were appointed of God, which was the confirmation of their doctrine.]

2\. It may also teach us that ministers ought not to make a bargain with the people, or desire to know what they shall have before they enter on their work; for he who would approve himself a true minister of Jesus Christ, ought not to preach for hire or filthy lucre's sake, #emph[i.e.] that ought not to be the thing he aims at; that's a low and base design, but as you know churches provide and ought to provide for the poor; yet should any seek to come into your communion merely for a maintenance, you would say he or she that did so, were no better than hypocrites, and (may say truly) yet that would not free you from communicating to poor faithful Christians. Even so, if some deceitful and carnal persons should undertake the work of the ministry for filthy lucre's sake, and not in love to Christ, and to promote his interest and glory, they, doubtless act contrary to this precept of Christ. But yet nevertheless, the church is bound to communicate and allow a comfortable maintenance to her faithful ministers; and as he freely, and of a ready mind, and for Christ's sake, preaches the gospel, and is bound so to do if he will approve himself faithful; so in like manner are the people and churches of God bound freely and of a ready mind to minister to them, if they would show to all they are faithful Christians, such who have an equal respect to all Christ's commands and desire, to the utmost of their abilities, to further and not hinder the promulgation of the gospel in the world.

But by the way it is plain, had it not been the practice of the gospel churches in the apostles' time, to allow their pastors a maintenance, what room was there for the apostle to caution any minister or elder not to undertake the work for filthy lucre's sake, but of a ready mind. Moreover, very remarkable is it to consider how the #emph[Priests of God under the law] were to receive #emph[that portion Jehovah gave them:] they were not (as Mr. #emph[Ainsworth] noteth) #emph[To receive it after a base or servile manner, but as gifts due to the Lord, and to them from him: the] Hebrew canons (saith he) #emph[show the Israelites were to give them their portion with honour; and it was unlawful for the] priests #emph[or] Levites #emph[to snatch away the heave-offering, or the tithes; yea,] saith he, #emph[if they did but ask their portion with their mouth it was unlawful.] Read his Annotation on #emph[Numb.] 18. V. 12. And then on #emph[Deut.] 18:3. He saith again, #emph[the priest might not violently take the gifts, nor ask them with his mouth, but he received them when they were given him with honour.]

This may teach us two things. First, that Christ's servants ought to take heed they show all true and real zeal and love to Christ, when they undertake his work and service; and not to show such a servile and base spirit as to demand their portion that God has ordained for them, but leave it to the free will offering of the people. Secondly, it may also teach churches to see they do neither withhold the ministers' portion from them, nor give it them grudgingly, or in an unbecoming manner, but to hand out to them what they need with due respect and honour, they being worthy of it, and are to receive it as their part and portion from God, and as they are his stewards and faithful labourers, by virtue of a divine and holy law: nay, and the Lord's people ought to be as careful in discharge of this duty to Christ's ministers now, as the #emph[Israelites] were to the #emph[Levites;] tho' as we have already said, their portion is not the #emph[Tithes of men's increase,] nor #emph[the first fruits,] which law is abrogated. Yet saith #emph[reverend Ainsworth,] 'the equity of that law remaineth perpetually, as the apostle observeth, #emph[Do you not know that they which minister about holy things, live of the things of the temple; and they that wait at the] altar, #emph[are partakers with the] altar: #emph[Even so hath the Lord ordained,] etc. 1 Cor. 9:13, 14. Because the ministers of God then were enjoined to attend on his service, he would not have them cumbered with worldly affairs, lest (saith he) they should be hindered from doing their duties; as it is written, #emph[No man that warreth entangleth himself with the affairs of this life, that he may please him who hath called him to be a soldier.] 2 Tim. 2:4. From hence God hath ordered it thus for them.' Moreover, #emph[the Hebrews say from hence ’twas] Levi #emph[was not counted meet to have inheritance in the land of] Israel, #emph[or spoils with his brethren, because he was separated to serve the Lord, and to inherit him, and to teach his strait ways, and his just judgments unto the people: therefore was he separated from the ways of the world; they wage not war, as the rest of] Israel #emph[do, neither do they inherit nor earn for themselves with the strength of their bodies, but they are the Lord's power (or substance) as it is written,] Deut. 33:11. Bless Lord his power; #emph[and the blessed God earneth for them, as it is written] Numb. 18:20. #emph[I am thy part and thine inheritance.] Maim. Treat. of the release and jubilee, #emph[c.] 13. #emph[F.] 12.

The reason of the same law, ’tis evident of necessity does remain; the work of ministers is great now, and ’tis as holy and as honourable as ever, and the neglect of a faithful discharge herein, as great a sin as it was then; and God's people have as great, nay, greater benefit and divine profit by the ministry of the gospel, than those had who lived under the law; besides Christ's servants have the same need of it: moreover, our people are delivered from other great burdens and vast charges that the people of #emph[Israel] were continually at; and therefore how unjust and unreasonable a thing is it to with-hold a fit and convenient livelihood from them. Nay, and we must say, that which any with-hold from the servants of God, is the Lord's, and none of theirs; for he lays claim to part of their substance, as that which he has ordained to his own special service and use of his faithful ministers.

Quest. #emph[May every one then that preaches expect an allowance, though they preach but now and then.]

#emph[Answ.] That must be left to the wisdom and consideration of the church; who ought to consider the person's circumstances, with the call he hath to preach, #emph[etc.] But principally it belongs to those who are set apart to that work, whose strength and time is taken up about the great affairs of Christ and the gospel.

Thus we have endeavoured to discharge our duty as touching this great work, and have we hope answered all the material objections any have to bring, or urge against the minister's maintenance: but since we have a little room we shall add some brief hints further, to show the great charge and work of a true gospel minister, and so conclude; that all may see how needful a thing it is, that every one take care to discharge their duty in this matter to them, whereby also the justness and righteousness of the law, and appointment of God herein, may yet further appear to all.
