== A Regular Ministry in the Church Asserted

God in his Infinite Goodness having by his present Providences, not only given us respite from our former Sufferings, but we trust begun that great and glorious Work of the Churches Deliverance so long the hope and expectation of all that truly love and fear the Lord; We cannot but look upon our Selves concerned to endeavour to make a due Improvement of that Mercy and Goodness that is attending us herein; and taking into consideration the Condition of the Church of Jesus Christ, we cannot but be concerned with, and afflicted for the late and present wants She lies under in respect to the Ministry, God having of late Years removed so many able and pious Men, and seems to be near the removing many more by. Age and Bodily Infirmities. This with other things put us upon the Consideration how much the Honour of Christ, the reputation of his Glorious Gospel in the World; as likewise, the Good and Well-being of the Churches depends upon a regular and orderly Ministry, and the Continuation thereof: And for the Churches to be under a supine neglect herein is very sad.

First, #emph[Either in not endeavouring after, and calling forth such a regular and stated Ministry, according to Gospel Institution at all; or,]

Secondly, #emph[to be so weak and inadvertent as to call forth such as are not so duly furnished and qualified for it; or,]

Thirdly, #emph[Suffering such as are call'd forth to this great Work under competent Abilities, to lye under unsupportable Burthens, must needs be greatly blameable before our Lord Jesus Christ, the great Bishop and Shepherd of our Souls, as well as highly negligent of their own Edification and Well-being.]

1\. To proceed, it cannot be denied but Christ hath, and ought to have, a stated and regular Ministry in his Churches, according to his own Institution: Who himself, when he entered upon his Ministry, here on Earth, did call forth Apostles and Disciples to bear that part of the Work with him, which he called them to, and fitted them for: See #emph[Mark,] 3.13. To the 19. #emph[Christ went up into a Mountain, and called to him whom he would, and they came to him, and he ordained Twelve that they should be with Him, and that he might send them forth to Preach; to whom He gave the Name of Apostles.] Mat. 10.2. Luke 6.13. Which he did with great Solemnity and Invocation of the Father (for #emph[he continued all Night in Prayer to God) and when it was Day he chose the Twelve, and Named them Apostles.] After which he appointed other Seventy, #emph[and sent them forth by Two; and Two, before His Face, to every City and Place,] &c. Which were labourers with Him in the Harvest, V. 2. And He commanded them to give themselves up to the Work he had called them to, and not take Care what they should Eat or Drink, #emph[For the Labourer] (saith he) #emph[is worthy of his Hire] Ver. To 14. Here our Lord Jesus Christ Himself did Institute and Lay the Foundation of the Gospel Ministry in His own Authority; and accordingly takes care for the continuance of it after His Death and Resurrection, and actual Investiture in our Nature of all Power in Heaven and Earth, #emph[Matt] 28.18.19.20. #emph[And Jesus came and spake unto them, saying, All Power is given unto me in Heaven and in Earth▪ Go ye therefore Teach all Nations,] &&c. #emph[And lo I am with you always, even unto the End of the World.] Amen. Also after His Blessed and Glorious Ascention, and #emph[Sitting on the Throne of the Majesty in the Heavens.] Heb. 8.1. #emph[Angels, and Authorities, and Powers being made subject unto him.] 1 Pet. 3. & 22. Did by His Apostles give Commandment and Direction for the continuance hereof to the end of the World, and his Second #emph[Coming without Sin unto Salvation.] Heb. 9.28. As #emph[Acts] 14.21,22,23. After they had by their Ministry been blest with the Conversion of many Souls, they took care to direct them into the Duty of Church Communion; and by their Suffrages, #emph[Ordained them Elders in every Church.] So the Apostle gives this as the Reason, Why he #emph[left] Titus #emph[in] Creete; (he not having opportunity after Preaching the Gospel to them) to put things into due Order. #emph[Tit.] 1.5. #emph[That he should set in Order the things that were wanting] (or left undone by the Apostle) #emph[and Ordaine Elders in every City:] that is Church in every City, as before, #emph[Acts] 14. Who are called #emph[Elders, Bishops, or Pastors,] and #emph[Teachers;] Names significative of their Authority, Office and Work.

2\. Christ being now in Heaven and an extraordinary Call being ceased the Scriptures being a perfect and standing Rule to the Church through all Ages, he has committed this Care to her self, according to the Power given to Her, who is #emph[the Pillar and Ground of Truth,] to provide Ministers for her own Edification, in Obedience to his Commands and Rules given in his word, as he shall see good to Bless her with Spiritual Gifts and Abilities, in order to the fitting them for this Work; the Father also has Covenanted to give his Spirit in the Gifts and Graces of it, and promised that the Words #emph[he has put into Christs Mouth, and the spirit that is upon him, shall never depart from him, nor his seeds seed, for ever:] Likewise has according to the Circumstances of time the Church hath been under, blest her, as with his Grace so with all needful Spiritual Gifts. #emph[Eph.] 4.7.11. #emph[For the perfecting the saints for the Work of the Ministry, for the Edifying the Body of Christ.] So that whilst there is a Church Millitant, Saints on this side Perfection, any of the Members of Christ Mystical Body on Earth, those Spiritual Gifts needful to their present State, shall be given, and be amongst them, for the Support of the great Ordinance of the Ministry, and for the good of the Church.

3\. And as its the Duty of the Churches to Seek these Spiritual Abilities, and improve them when they are given to these great and Holy Ends; so they must walk regularly herein, in obedience to the Rules given by Christ in this Case; who hath laid down the qualifications both Negative and Positive, of all such as ought to be called to this great work and Trust of Ministering by Office, 1 #emph[Tim.] 3.1. To 9. #emph[Tit.] 1.6.9. We have no warrant to put any into the Ministry otherwise, save such as are here discribed, and competently fitted for it. For as it was a sin of Old in the Church to put any into the Ministry, but those whom God appointed by the Rules given to them▪ so it can be no less Evil for the Church now, to call any forth into Office, but such who are qualified as God's Word directs; and now, as Christ hath made this grant of Power to the Churches of choosing her own Officers for her Edification; so he hath left Rules for her, who, and how to chose, as we said before: So likewise he has laid down those special Duties of the Officers in the Church, who are to take the oversight, Feed, Govern, Go in and out before them. #emph[Acts] 20.17,18. 1. #emph[Pet.] 5. And 2.

4\. When the Church has had a Tryal of the meetness and Abilities of any Person, or Persons, for this work and service, they are by Election and Choice solemnly to set him, or them a part, by Prayer, and Laying on of Hands. #emph[Acts] 14.21,22,23. #emph[Acts] 6. By which a new relation ariseth of an Elder, and a Church, a Pastor, and a Flock: This must be therefore by the mutual voluntary acts of each other, by which the Duties of each relation becomes binding upon them, according to the Laws of Christ: It is the Pastors Duty now to Watch, Feed, and Govern the Flock, and to give himself up to it; It is the Churches Duty to submit themselves to Him in the Lord; to Love, Reverence, and Administer freely to him. 1 #emph[Pet.] 5.1,2,3,4,5. #emph[Heb.] 13.7.17. How greatly then must those Churches be to blame, that unconcernedly live in the neglect of so great a Duty, upon which the Edification of the Church, and her Well-being so much depends, as well as Gospel Order: For although the Essence and Being of a Church depends upon its Institution in respect both of Matter and Form: (A competent number of Believers may by mutual agreement lay the Foundation of the Being of a Gospel Church,) but they cannot be a Church Organical without Officers, which the Lord hath placed there for the orderly Exercise of his Authority committed to her; To neglect this, is to despise the Wisdom of Christ, who best knows what is for the good of His Church, and for Her Edification in this State. 2, To slight His Goodness in so useful and beneficial an Institution. 3, Its a contempt put upon his Authority, as King of Saints, who has in his Soveraign Right, in and over the Church, Ordained it so to be, for the Churches Good and Well-being.

#emph[Secondly,] As there should not be a neglect of this Duty, so there should be great care taken that we answer the Will of God herein, wherein His Name and Honour is so much concerned, in Respect of his Love to, and Care of his Church; therefore the greaest diligence should be taken that the Rules He has given be duly observed, and Applications made of the Qualifications laid down, in respect of all such that are called unto Office: The outward Call is an Act of the Church, the acceptation of the Person so called, is an Obediential Act of him to the Will of God; but neither of these can be regular, where there is not at previous indication of the Mind of God, in bestowing those Spiritual Gifts and Qualifications, as may render him competently fit to the Discharge of his Office and Work.

Now in a Churches undue proceeding herein, they discover their own weakness, if not Ignorance, in respect of the Rule it self, and injure the Person so called, in laying the weight of so great a Work upon him, who is not furnished with Spiritual Abilities to discharge it, & thereby expose the Honour of Christ, and Reputation of His Gospel in the World, which should be dear unto us.

And we have reason to reckon that some Churches not walking so regular herein, has been one cause of the want of that Reputation, which otherwise they might have gained amongst the Saints, and in the World, observe what #emph[Moses] said to #emph[Israel, Deut.] 4.6. #emph[Keep therefore, and do them, for this is your Wisdom and your Understanding in the sight of the Nations, which shall hear of all these Statutes; and say, Surely this great Nation is a wise and understanding People.] Who otherwise were the least of all Nations. We ought with far greater reason to take heed we deviate not from the Laws of the Son of God, who deserves greater Honour than #emph[Moses,] which he hath given to His Church, under the Gospel Dispensation; If in the choice of Deacons, #emph[Acts] 6.3. They were to look out #emph[from amongst themselves Men of honest Report, full of the Holy Ghost and Wisdom,] to be set apart to that Work: How much more in the choice of Pastors or Elders whose Work requires greater spiritual Abillities to a right discharge thereof?

For Churches therefore to be so unconcern'd, whether they have Officers or not, according to Gospel Rule, or so overly in the Choice of those they call into such high stations amongst them whether they are competently qualified or not, are greatly blameable.

#emph[Thirdly,] In the next place we conclude, It is very dishonourable to God, and a reproach to our #emph[Sacred Religion] for the Churches when they have called forth such Pastors and Ministers, who are competently qualified according to the Rule of the Gospel, to let them lye under those unsupportable burdens, of worldly Snares and Incumbrances, without providing a due maintenance for them, according to the Ordaination of our Lord Jesus Christ in the #emph[New Testament.]
