"""Illegible gaps filled for this edition, keyed by the TEI pipeline's gap
index (build_tei.py --list). Read from context, the scripture or author
quoted, Grosart's text (Monergism) and the page images of the 1652 and 1658
printings on archive.org (another setting of the same text; the 1653 copy
the TCP keyed is not there). Greek and Hebrew (reason="foreign") were read
from those scans by hand (#editor). Gaps in the catalogue and errata (not in
this edition) are left open."""

GAP_FIXES = {

    0: ('t', 'high', 'Multi ama[t] veritatem lucentem, oderunt redarguentem (Augustine); TCP "amā"'),
    1: ('e', 'high', 'J[e]rome'),
    2: ('1', 'high', 'Psal. 119. 11[1] (KJV "Thy testimonies have I taken as an heritage for ever")'),
    3: ('a', 'high', 'M[a]t. 5. 18'),
    4: ('a', 'high', 'Verit[a]s vincit'),
    5: ('c', 'high', 'Veritas vin[c]it'),
    6: ('s', 'high', 'res nostrae religioni[s] consistunt'),
    7: ('as', 'high', 'Luther: Deus amat currist[as], non quaeristas'),
    9: ('r', 'high', '[r]unner, glossing curristas'),
    11: ('s', 'medium', 'soul[s]; Monergism "a jest of damning their own souls"'),
    15: ('i', 'high', 'ex ins[i]diis'),
    24: ('e', 'high', 'S[e]rpent Scytale'),
    26: ('f', 'high', 'beauti[f]ull'),
    27: ('l', 'high', 'cou[l]d'),
    28: ('o', 'high', 'Chrysost[o]me'),
    33: ('e', 'high', 'h[e] should'),
    34: ('t', 'high', '[t]hat'),
    35: ('e', 'high', 'app[e]ar'),
    36: ('n', 'high', 'V[n]a guttula (Una), as "Ʋna guttula" p. 31'),
    37: ('t', 'high', 'no[t] onely'),
    38: ('r', 'high', 'fi[r]st'),
    40: ('e', 'high', 'mis[e]ry'),
    41: ('n', 'high', 'transgressio[n]s'),
    42: ('ſ', 'high', '[ſ]inne'),
    43: ('f', 'high', '[f]ainting under it'),
    45: ('t', 'high', 'stoutes[t]'),
    46: ('t', 'high', 'conscien[t]iae'),
    47: ('s', 'high', 'sorrow[s]; Monergism "their sorrows and repentance"'),
    48: ('r', 'high', '[r]epentance; Monergism'),
    49: ('e', 'high', 'rep[e]ntance; Monergism'),
    50: ('h', 'high', 'Hezekia[h]'),
    51: ('h', 'high', 'Hezekia[h]\'s'),
    52: ('h', 'high', 'Hezekia[h]'),
    53: ('as', 'high', "'tis [as] true; Monergism \"it is as true\""),
    54: ('e', 'high', 'hearing of the [e]are (Job 42. 5; book spells "eare")'),
    55: ('a', 'high', 'de dolore g[a]udet'),
    56: ('n', 'high', 'do[n]e (2 Sam. 12. 10)'),
    60: ('ſ', 'high', 'wont to [ſ]ay'),
    61: ('l', 'high', 'dive[l]ish'),
    62: ('r', 'high', '[r]ipe for hell'),
    64: ('e', 'high', 'besi[e]ged'),
    65: ('u', 'high', 'E[u]sebius'),
    66: ('s', 'high', 'thi[s] day'),
    67: ('e', 'high', 'non[e]'),
    69: ('e', 'high', 'b[e]fall'),
    70: ('t', 'high', '[t]o those'),
    71: ('i', 'high', 'h[i]m'),
    72: ('a', 'high', 'P[a]ntaurus'),
    74: ('s', 'high', 'a[s] truly'),
    75: ('a', 'high', '[a]n easie work'),
    77: ('e', 'high', 'R[e]medy'),
    84: ('e', 'high', 'crucifi[e] (book spells "crucifie")'),
    85: ('a', 'high', 'Ag[a]g'),
    86: ('i', 'high', 'pen[i]tentiall'),
    87: ('ti', 'high', 'immunditia pecca[ti] (Bernard: Quantum displicet Deo immunditia peccati, tantum placet erubescentia poenitentis)'),
    88: ('o', 'high', 'peccat[o]r'),
    89: ('t', 'medium', 'how shalt thou [t]ear, and rend thy self'),
    90: ('m', 'high', 'but a[m] now pierced'),
    91: ('r', 'high', 'cu[r]ed of sin'),
    92: ('ſ', 'high', 'as you may [ſ]ee'),
    94: ('t', 'high', 'bu[t] then he told them'),
    95: ('s', 'high', 'those sin[s], those darling lusts'),
    96: ('s', 'high', 'bad humor[s]; Monergism "as bad humours do endanger the blood"'),
    98: ('i', 'high', 'cui nil nunquam contigit advers[i] (Seneca)'),
    99: ('u', 'high', 'eno[u]gh'),
    100: ('r', 'high', 'cu[r]e the head ach'),
    101: ('r', 'high', 'no mo[r]e'),
    102: ('e', 'high', '[e]mptines'),
    103: ('t', 'high', 'som[t]hing'),
    104: ('a', 'high', '[a]nd golden Crown'),
    105: ('e', 'high', 'sit with the[e] upon thy Throne'),
    106: ('r', 'high', 'put[r]efaction'),
    107: ('a', 'high', 'The b[a]ll in the embleme saith, Percussa surgo'),
    108: ('e', 'medium', 'emblem[e]; the book spells "embleme" elsewhere'),
    109: ('r', 'high', 'Percussa Su[r]go'),
    110: ('e', 'high', "Stevens [e]ars; Monergism \"Stephen's ears\""),
    112: ('e', 'high', '[e]arnestly or vehemently; Monergism'),
    114: ('g', 'high', 'di[g]ged up'),
    115: ('f', 'high', '[f]ound a great deale of treasure'),
    116: ('t', 'high', '[t]hey have met withall'),
    119: ('re', 'high', 'when they a[re] afflicted'),
    120: ('t', 'high', 'tha[t]'),
    121: ('it', 'high', 'advers[it]y'),
    122: ('e', 'high', 'hon[e]y'),
    123: ('h', 'high', 'the [h]usk of Anaxarchus'),
    124: ('th', 'high', 'The [th]ird Remedy; Monergism "The third remedy"'),
    125: ('ce', 'high', 'Devi[ce]'),
    126: ('n', 'high', 'a[n]d'),
    127: ('tary', 'high', 'short and momen[tary] afflictions (2 Cor. 4. 17)'),
    128: ('n', 'high', 'afflictio[n]s'),
    129: ('e', 'high', 'Wh[e]n'),
    131: ('e', 'high', 'your fasts into [e]verlasting feasts; Monergism'),
    132: ('e', 'high', 'l[e]d thee these fourty yeares (Deut. 8. 2)'),
    133: ('tr', 'high', 'God [tr]ies his; Monergism "So God tries his by knocking"'),
    134: ('t', 'high', '[t]heir mercies; Monergism "snares in all their"'),
    135: ('t', 'high', 'forbidden frui[t]'),
    136: ('k', 'high', 'his head a[k]ed'),
    137: ('u', 'high', 'b[u]t'),
    138: ('u', 'high', 'the body of the S[u]n'),
    139: ('n', 'high', 'salvatio[n]'),
    140: ('t', 'high', 'shu[t] (Mat. 25. 10)'),
    141: ('s', 'high', 'Ne quaeramu[s] ubi sit, sed quomodo illam fugiamus (Chrysostom)'),
    142: ('o', 'high', 'dogs of Cong[o]'),
    145: ('i', 'high', 'D[i]ce'),
    146: ('e', 'high', 'Dic[e]'),
    148: ('e', 'high', 'Gods way[e]s'),
    149: ('f', 'high', '[f]all as stars from Heaven'),
    150: ('r', 'high', 'labou[r]'),
    151: ('b', 'high', 'bright but [b]rittle'),
    152: ('u', 'high', 'ind[u]re'),
    153: ('e', 'high', 'indur[e]'),
    154: ('m', 'high', 'ham[m]er'),
    155: ('l', 'high', 'go[l]d'),
    158: ('r', 'high', 'o[r]ient'),
    159: ('a', 'high', 's[a]ved by fire (1 Cor. 3. 15)'),
    160: ('o', 'high', 'm[o]re worth'),
    162: ('b', 'high', 'one [b]astard (Judg. 8. 30-31, Gideon and Abimelech)'),
    163: ('y', 'high', '[y]et that bastard'),
    164: ('t', 'high', 'ye[t]'),
    165: ('b', 'high', '[b]astard'),
    166: ('r', 'high', 'dest[r]oyed'),
    167: ('n', 'high', 'one tur[n]e may bring'),
    168: ('b', 'high', '[b]ring'),
    169: ('n', 'high', 'bri[n]g'),
    171: ('a', 'high', 'st[a]nd when others fall'),
    172: ('t', 'high', 'cried ou[t]'),
    174: ('t', 'high', 'goe on [t]o Heaven'),
    175: ('i', 'high', 'Rub[i]es; Monergism "gold or rubies"'),
    176: ('rt', 'high', 'that blessed Ma[rt]yr'),
    177: ('at', 'high', 'Hold th[at] fast which thou hast (Rev. 3. 11)'),
    179: ('a', 'high', 'he he[a]rd a voice'),
    181: ('e', 'high', 's[e]ared; Monergism "the consciences that error hath seared"'),
    182: ('f', 'high', 'twel[f]th; Monergism'),
    183: ('t', 'high', 'ou[t]-weigh'),
    184: ('o', 'high', 'sh[o]ne'),
    185: ('u', 'high', 'so[u]les'),
    187: ('f', 'high', 'out o[f]'),
    188: ('i', 'high', 'M[i]lo\'s'),
    189: ('o', 'high', 'Mil[o]\'s'),
    197: ('e', 'high', 'the n[e]ck'),
    198: ('r', 'high', 'F[r]ogs of Egypt'),
    200: ('v', 'high', 'le[v]ity'),
    202: ('ts', 'high', 'though[ts]; Monergism "more thoughts and time on the world"'),
    204: ('a', 'high', 're[a]d'),
    205: ('r', 'high', 'ad[r]ying'),
    206: ('e', 'high', 'sl[e]pt'),
    207: ('r', 'high', 'f[r]om'),
    208: ('m', 'high', 'fro[m]'),
    209: ('r', 'high', 'imagina[r]y'),
    212: ('e', 'high', 't[e]nth and 11th of the Hebrews'),
    213: ('a', 'high', 'tr[a]mple'),
    219: ('e', 'high', 'P[e]riissem nisi periissem'),
    221: ('t', 'high', 'e[t]ernall'),
    222: ('r', 'high', 'ete[r]nall'),
    224: ('c', 'high', '[c]ease the service'),
    227: ('e', 'high', 'wag[e]s; Monergism "the wages is great"'),
    228: ('n', 'high', 'passi[n]g'),
    229: ('e', 'high', 'I do[e] think'),
    230: ('s', 'high', 'a[s] for you'),
    231: ('t', 'high', 'quomodo vixerin[t]'),
    232: ('o', 'high', 'd[o]ing'),
    233: ('ſe', 'high', 'righteousnes[ſe] (book spells "righteousneſſe" 20x; 1 John 2. 29)'),
    234: ('n', 'high', 'walk i[n] darknesse (1 John 1. 6)'),
    235: ('e', 'high', 'th[e] commands'),
    236: ('t', 'high', 'Finis move[t] ad agendum'),
    237: ('a', 'high', 'm[a]gnitude'),
    238: ('n', 'medium', 'the Lord wil have a[n] high (esteem of you)'),
    239: ('l', 'high', 'sha[l]l'),
    240: ('m', 'high', '[m]easure'),
    241: ('u', 'high', '[u]pon'),
    242: ('t', 'high', '[t]hat'),
    243: ('n', 'high', 's[n]ares'),
    244: ('t', 'high', '[t]hem'),
    245: ('o', 'high', 'p[o]verty'),
    246: ('e', 'high', 'pov[e]rty'),
    247: ('e', 'high', 'p[e]rish'),
    249: ('r', 'high', 'fie[r]y crucible'),
    250: ('y', 'high', 'of m[y] very life'),
    251: ('f', 'high', 'i[f] once'),
    252: ('J', 'high', '[J]er. 4. 14 ("How long shall thy vain thoughts lodge within thee"); book uses "Jer." 10x, "Ier." 5x'),
    253: ('o', 'high', 'Zen[o]'),
    254: ('u', 'high', 'm[u]st'),
    255: ('o', 'high', 'c[o]st'),
    256: ('d', 'high', 'an[d]'),
    258: ('e', 'high', 'b[e]st services'),
    259: ('s', 'high', 'cordiall[s]'),
    260: ('t', 'high', 'cu[t] off'),
    261: ('t', 'high', 'cry out [t]o God'),
    263: ('u', 'high', 'b[u]t the blood of Christ'),
    264: ('a', 'high', 'p[a]rdon'),
    265: ('a', 'high', 'g[a]ve'),
    266: ('e', 'high', 'h[e]art'),
    267: ('e', 'high', 'li[e] a bleeding'),
    268: ('e', 'high', 'd[e]grees'),
    269: ('f', 'high', 'i[f] a man'),
    270: ('a', 'high', 'm[a]n'),
    271: ('t', 'high', 'fai[t]h'),
    272: ('r', 'high', 'st[r]ongest'),
    273: ('t', 'high', '[t]o consider'),
    274: ('r', 'high', 'g[r]eat measures'),
    275: ('t', 'high', 'those in [t]hat Isa. 50. 10'),
    276: ('t', 'high', 'tha[t]'),
    277: ('re', 'high', 'a [re]ceiving of Christ; "As many as received him" (John 1. 12)'),
    278: ('f', 'high', 'the [f]aith of reliance'),
    281: ('o', 'high', 'h[o]liest'),
    282: ('ſ', 'high', 'all [ſ]in'),
    284: ('o', 'high', 'jube qu[o]d vis (Augustine, Da quod jubes)'),
    285: ('t', 'high', 'command what thou wil[t] (Augustine, Da quod jubes et jube quod vis)'),
    288: ('t', 'high', 'Christ si[t]s'),
    289: ('t', 'high', 'the wan[t] of outward comforts'),
    290: ('t', 'high', '[t]he Father of it (John 8. 44)'),
    291: ('a', 'high', '[a]re very fruitfull'),
    292: ('e', 'high', 'H[e]ll'),
    293: ('e', 'high', 'B[e]leevers'),
    294: ('h', 'high', 'ab[h]orrest idols (Rom. 2. 22)'),
    296: ('t', 'high', '[t]hose'),
    298: ('l', 'high', 'Jay[l]or'),
    299: ('w', 'high', 'gro[w] (2 Tim. 3. 13)'),
    300: ('t', 'high', '[t]umults'),
    301: ('a', 'high', '[a]nd'),
    302: ('u', 'high', 'f[u]ll of holy affections'),
    303: ('t', 'high', 'ye[t]'),
    305: ('e', 'high', 'st[e]p of the ladder'),
    306: ('c', 'high', 'mu[c]h'),
    307: ('b', 'high', '[b]e'),
    308: ('t', 'high', 'aba[t]ed'),
    309: ('f', 'high', 'li[f]e'),
    310: ('e', 'high', 'd[e]ar'),
    311: ('r', 'high', 'dea[r]'),
    312: ('e', 'high', 'Win[e]presse (Isa. 63. 3)'),
    313: ('e', 'high', 'form[e]r'),
    314: ('o', 'high', 's[o]re troubles (Ps. 71. 20)'),
    315: ('o', 'high', 'rest[o]re comforts (Isa. 57. 18)'),
    316: ('e', 'high', 'm[e]rcy'),
    317: ('t', 'high', 'lit[t]le'),
    318: ('s', 'high', 'evidence[s]'),
    319: ('r', 'high', 'mo[r]e'),
    320: ('i', 'high', 'prom[i]sed'),
    321: ('p', 'high', 's[p]eak'),
    322: ('c', 'high', '[c]h. 12'),
    323: ('s', 'high', 'Sampson i[s] by the Spirit; Monergism "Samson is by the Spirit"'),
    324: ('e', 'high', 'ther[e]'),
    325: ('e', 'high', 'b[e]cause'),
    326: ('a', 'high', 'E[a]gle'),
    327: ('d', 'high', 'Vi[d]e'),
    328: ('e', 'high', 'Vide B[e]zam'),
    331: ('r', 'high', 'P[r]eacher'),
    332: ('ed', 'high', 'M[ed]itation, prayer, and temptation (Luther)'),
    333: ('So', 'high', '[So]metimes'),
    334: ('s', 'high', 'Sometime[s]'),
    335: ('ſ', 'high', '[ſ]hewes'),
    336: ('m', 'high', 'hi[m]'),
    337: ('li', 'high', '[li]ke the deluge'),
    338: ('e', 'high', 'm[e]n'),
    339: ('ſt', 'medium', '[ſt]amp\'t upon him; one-letter gap, the word needs two'),
    341: ('h', 'high', '[h]is goods'),
    342: ('ht', 'high', 'mig[ht]ier (Deut. 9. 14)'),
    343: ('h! ſ', 'medium', 'A[h! ſ]hould God; Monergism "Ah! should God make such an offer"'),
    344: ('k', 'high', 'See[k]ers'),
    346: ('4', 'high', 'John 5. [4]4 ("receive honour one of another")'),
    347: ('t', 'high', '[t]o slight them'),
    348: ('t', 'high', 'ea[t] no flesh (1 Cor. 8. 13)'),
    349: ('au', 'high', 'd[au]ghter'),
    350: ('i', 'high', 'd[i]ssension'),
    351: ('t', 'high', 'dissen[t]ion'),
    352: ('t', 'high', 'bi[t]er'),
    353: ('e', 'high', 'experi[e]nce'),
    354: ('a', 'high', 'm[a]n'),
    356: ('mee', 'high', 'most [mee]t that the child'),
    357: ('e', 'high', 'T[e]ll me'),
    358: ('s', 'high', 'i[s] solemnly'),
    359: ('p', 'high', '[p]ieces'),
    364: ('s', 'high', 'soul[s] in whom'),
    369: ('a', 'high', 'm[a]y edefie (Rom. 14. 19)'),
    370: ('ir', 'high', 'the[ir] graces'),
    371: ('or', 'high', 'Ign[or]at sane improbus omnis (Aristotle, Eth. 3. 1)'),
    372: ('t', 'high', 'Aririſ[t]otle (Aristotle; "Aririſ" as keyed)'),
    373: ('at', 'high', 'M[at]. 6. 22 (the light of the body is the eye)'),
    374: ('r', 'high', 'e[r]re'),
    376: ('r', 'high', '1 Co[r]. 2. 8'),
    378: ('t', 'high', 'pu[t] Ananias upon lying'),
    379: ('t', 'high', 'Adversaria po[t]e(stas) non habet vim cogendi, sed persuadendi (Isidore)'),
    381: ('o', 'high', 'c[o]gendi'),
    382: ('i', 'high', 'Is[i]dore'),
    383: ('r', 'high', 'Isido[r]e'),
    384: ('st', 'high', 'wor[st]'),
    385: ('l', 'high', 'Re[l]igion'),
    387: ('e', 'high', 'l[e]t us cleanse (2 Cor. 7. 1)'),
    388: ('f', 'high', '[f]eare of the Lord'),
    390: ('f', 'high', 'not [f]aint (Isa. 40. 31)'),
    394: ('e', 'high', 'N[e]hemiah\'s'),
    395: ('l', 'high', 'morta[l]l'),
    396: ('to', 'high', 'Pla[to]'),
    397: ('ti', 'high', 'stul[ti]tia'),
    398: ('s', 'high', 'Dru[s]ius'),
    399: ('ſ', 'medium', 'resi[ſ]te; Monergism "Job resists"; TCP keyed "te"'),
    401: ('l', 'high', 'ho[l]y gluttony'),
    402: ('a', 'high', 's[a]y'),
    403: ('r', 'high', 'lea[r]ned'),
    404: ('ſ', 'high', 'do[ſ]t'),
    405: ('u', 'high', 'Q[u]is pertransiet'),
    408: ('l', 'high', 'strict[l]y'),
    409: ('3', 'high', 'Mar. 1[3]. 33, 34, 35, 37'),
    410: ('ri', 'high', 'st[ri]ct watch'),
    411: ('e', 'high', 'conqu[e]red'),
    413: ('2', 'high', '45. 2[2] (Isa. 45. 22 "all the ends of the earth")'),
    414: ('t', 'high', 'wi[t]hout'),
    416: ('s', 'high', 'tast[s] (keyed "taft")'),
    417: ('a', 'high', 'H[a]man'),
    418: ('s', 'high', 'put[s]'),
    419: ('e', 'high', 'd[e]livered'),
    420: ('s', 'high', 'a[s] Dedalus'),
    421: ('a', 'high', 'Ded[a]lus'),
    422: ('s', 'high', 'other[s]'),
    423: ('t', 'high', 'sub[t]il'),
    425: ('e', 'high', 'migremus hinc, migr[e]mus hinc'),
    429: ('r', 'high', 'rent you[r] hearts (Joel 2. 13); Monergism'),
    430: (' hea', 'high', 'your [hea]rts (Joel 2. 13)'),
    431: ('s', 'high', 'read[s]'),
    432: ('s', 'high', 'i[s]'),
    433: ('t', 'high', 'wil[t]'),
    435: ('a', 'high', 'qu[a]lified'),
    437: ('s', 'high', 'daye[s]'),
    438: ('u', 'high', 'adie[u]'),
    8: ('a', 'medium', 'Luther: curristas, not qu[a]ristas; the book prints "quariſtas" at p. 164 (classical "quaeristas")'),
    23: ('is', 'high', 'regnat si consen-ser[is] (Augustine); 1652 scan n32: "conſen-ſeris"'),
    29: ('cc', 'high', 'Nil nisi pe[cc]atum timeo (Chrysostom); 1658 scan n35: "Nil nisi peccatum timeo"; TCP keyed "pr" for "pe"'),
    63: ('pœ', 'high', 'gravitate [pœ]nae compensat; 1658 scan n67: "gravitate pœna compensat"'),
    186: ('n', 'medium', 'The champions could [n]or (=not) wring an Apple; 1652 scan n191 reads "could not wring": the 1653 may read "not" (TCP "or")'),
    192: ('ſo', 'high', 'a ba[ſo]n full of Angells; 1652 scan n192 "in a baſon full of Angells"'),
    193: ('Ang', 'high', '[Ang]ells; 1652 scan n192 "Angells", 1658 n155 "Angels"'),
    196: ('d', 'high', 'it would not [d]oe; 1652 scan n192 "but it would not doe"'),
    199: ('ll', 'high', 'King of Vanda[ll]s; 1652 scan n193 "Gilimex King of Vandalls"'),
    215: ('æ', 'high', 'Nemo proprie l[æ]ditur nisi a seipso (Chrysostom); 1652 scan n213 "læditur"'),
    216: ('it', 'high', 'læd[it]ur; 1652 scan n213'),
    220: ('li', 'medium', 'Ze[li]slaus; 1652 scan n221 "Ze-liſlaus" (one-letter gap in TCP)'),
    304: ('i', 'medium', 'fade and w[i]ther; 1652 scan n329 "wi-ther" (two-letter gap: perhaps "i-")'),
    340: ('11', 'high', 'Gen. 13. 10, [11]; 1652 scan n367 "Gen. 13. 10, 11. v."'),
    361: ('4', 'high', 'Heb. 13. 1[4] ("Here we have no abiding city"); 1652 scan n406 "Heb. 13. 14."'),
    362: ('1', 'high', 'Heb. 1[1]. 13; 1652 scan n406 "Heb. 11. 13."'),
    363: ('13', 'high', 'Heb. 11. [13] (strangers on earth); 1652 scan n406'),
    386: ('.', 'medium', '1 Pet. 15. 16[.] (stop, not a letter); 1652 scan n433 "1 Pet. 15, 16."'),
    426: ('l', 'medium', 'spiritua[l] madnesse; Monergism "it is spiritual madness"'),
    427: (' m', 'medium', 'spiritual [m]adnesse (the space between the two TCP gaps is lost); Monergism; or "ſpirituall"'),
    # no letter in the other printings: a speck in the 1653 copy
    73: ('', 'high', '1658 scan n72 "stone or Pearl in the world": no letter'),
    113: ('', 'high', '1652 scan n147 "to be digged up": nothing between "be" and "digged"'),
    217: ('', 'high', '1652 scan n213 "nisi a seipso": no letter'),
    287: ('', 'high', '1652 scan n313 "pillar of fire": no letter'),
    389: ('', 'high', '1652 scan n433 "If he tempts you": no letter'),
    # Greek, Hebrew and longer losses, read from the scans by hand
    10: ('Καταπονούμενον ἐβασάνιζεν', 'high', '1658 n23 and 1652 n25 margin (both agree); 2 Pet. 2:7-8 καταπονούμενον, ἐβασάνιζεν', '#editor'),
    12: ('Πλεονεκτηθῶμεν', 'high', '1652 n27 margin (1658 n24 agrees, blurred); 2 Cor. 2:11 πλεονεκτηθῶμεν', '#editor'),
    13: ('ματα', 'high', '1652 n27 and 1658 n24 margin: Νοήματα (2 Cor. 2:11); the TCP\'s "Non" before the gap is the Greek Νοή- keyed as Latin, so the whole note should read Νοήματα', '#editor'),
    14: ('Μεθοδείας', 'high', '1658 n25 and 1652 n28 margin; Eph. 6:11 μεθοδείας', '#editor'),
    16: ('a μετα & ὁδὸς', 'medium', '1652 n28 margin, 1658 n26 agrees (partly cropped): "a μετα & ὁδὸς."; read à μετὰ & ὁδός (derivation of μεθοδεία); Latin "a" and "&" are part of the note', '#editor'),
    20: ('Ἀνανήψωσιν', 'high', '1658 n26 and 1652 n29 margin; 2 Tim. 2:26 ἀνανήψωσιν (1652 initial letter faint)', '#editor'),
    21: ('ἐζωγρημένοι', 'high', '1652 n30 and 1658 n26 margin; 2 Tim. 2:26 ἐζωγρημένοι', '#editor'),
    25: ('ἀποστυγοῦντες', 'high', '1658 n30 margin (print ἀ set apart, ου ligature); Rom. 12:9 ἀποστυγοῦντες', '#editor'),
    30: ('meo', 'high', '1658 n35 margin: "Nil nisi peccatum timeo" (TCP has "ti" before the gap)', '#editor'),
    31: ('Vale lu', 'medium', '1658 n35 margin: "Vale lumen amicum. Ambrose." The TCP keyed the rest as "nen" (read men: lumen); the gap is "Vale lu"', '#editor'),
    32: ('amicum', 'medium', '1658 n35 margin: "Vale lumen a-micum." (word broken over the line)', '#editor'),
    39: ('των λοιμων', 'high', '1652 n53 body: "(των λοιμων)", no accents visible; Ps. 1:1 LXX καθέδρᾳ λοιμῶν, correct τῶν λοιμῶν', '#editor'),
    57: ('ἔγω σοὶ τούτων αἰτία', 'medium', '1652 n71 margin "ἔγω σοὶ τού-των αἰτία." (1658 n61 agrees, blurred); Plutarch, De sera num. vind. (Apollodorus\' dream): correct ἐγώ σοι τούτων αἰτία', '#editor'),
    58: ('מוסר', 'high', '1652 n72 margin, Hebrew "מוסר" (musar, chastening/instruction), unpointed', '#editor'),
    59: ('Παιδεία', 'high', '1652 n72 margin, under the Hebrew: "Παιδεία."', '#editor'),
    68: ('ἀμελήσαντες', 'medium', '1652 n81 margin "ἀμελήσαν-τες." (breathing faint); Matt. 22:5 ἀμελήσαντες, made light of', '#editor'),
    76: ('πάντα ποιεῖν ἐδυνάμην', 'high', '1652 n90 margin "(παν-τα ποιεῖν ἐδυνάμην)"; parentheses are outside the gap in the TCP', '#editor'),
    78: ('תשובה', 'high', '1652 n91 margin, Hebrew teshuvah, unpointed (justified with a space: "תשוב ה")', '#editor'),
    79: ('שוב', 'high', '1652 n91 margin, Hebrew shuv, unpointed', '#editor'),
    80: ('μεταμελεῖν', 'high', '1652 n91 margin "μεταμε-λεῖν"', '#editor'),
    81: ('μετάνοια', 'high', '1652 n92 margin "μετάνοια,"', '#editor'),
    82: ('ἄνοια', 'high', '1652 n92 margin "Ab ἄνοια dementia & μετα post"', '#editor'),
    83: ('μετα', 'high', '1652 n92 margin, no accent printed; correct μετά', '#editor'),
    93: ('לפניו', 'high', '1652 n107 margin, Hebrew lephanav ("before his face"), unpointed', '#editor'),
    111: ('ודברתי על־לבה', 'high', '1652 n147 margin, two lines "ודברתי / על־לבה" (some points visible, e.g. dagesh in bet); Hos. 2:14 וְדִבַּרְתִּי עַל־לִבָּהּ; TCP then has "Vedibbartignal libbah"', '#editor'),
    117: ('ותשיח', 'high', '1652 n148 margin, unpointed; Lam. 3:20 (ketiv ותשיח, qere ותשוח)', '#editor'),
    118: ('שוה', 'medium', '1652 n148 margin "from שוה" (last letter looks like he); the root should be שוח/שחח (to bow down): probable misprint for שוח', '#editor'),
    130: ('Εν γὰρ μικρὸν ὅσον, ὅσον', 'medium', '1652 n155 margin "Εν γὰρ μικρὸν ὅσον, ὅσον."; Heb. 10:37 Ἔτι γὰρ μικρὸν ὅσον ὅσον: "Εν" a misprint for Ἔτι', '#editor'),
    143: ('ἐνέργειαν πλανης', 'medium', '1652 n172 margin, accent on πλάνης not visible; 2 Thess. 2:11 ἐνέργειαν πλάνης', '#editor'),
    144: ('ἐν τῆ κυβεία', 'medium', '1652 n172 margin "ἐν τῆ κυ-βεία, Gr." (no iota subscripts visible); Eph. 4:14 ἐν τῇ κυβείᾳ', '#editor'),
    147: ('ἐνοικείτω', 'high', '1652 n173 margin "Col. 3 v. 16. ἐνοικείτω."', '#editor'),
    156: ("rub'd", 'medium', '1652 n175 margin "which though rub\'d, or melted, remaines firme, and orient."', '#editor'),
    157: ('firme', 'high', '1652 n175 margin, as for 156', '#editor'),
    161: ('εἰς τα γένη', 'medium', '1652 n177 margin "True hatred is (εἰς τα γένη) to the whole kind"; parentheses outside the gap; Aristotle, Rhet. 2.4 (τὸ δὲ μῖσος καὶ πρὸς τὰ γένη): correct εἰς τὰ γένη', '#editor'),
    170: ('way', 'high', '1652 n178 margin "may bring a man quite out of the way."', '#editor'),
    173: ('γλυκὺ ἡ ἀλήθεια', 'medium', '1652 n178 margin "(γλυκὺ ἡ ἀλήθεια)", faint print; Plutarch, De Iside 68: γλυκὺ ἡ ἀλήθεια', '#editor'),
    178: ('Ἀντεχόμενον', 'high', '1652 n180 margin "Tit. 1. v. 9. \'Αντεχόμε-νον." (breathing set before the capital); Tit. 1:9 ἀντεχόμενον', '#editor'),
    180: ('ענוים ענה', 'high', '1652 n182 margin "Psa. 25. v. 9. a ענוים ענה Gnanavim from gnanah" (both Hebrew words in the one TCP gap), unpointed', '#editor'),
    190: ('nd', 'medium', '1652 n191 margin "an Apple out of Milo\'s hand, by strong hand"; TCP keyed "ha" before the gap; the comma may be the TCP\'s', '#editor'),
    191: ('rold', 'high', '1652 n192 margin "The Prior in Melancton rold his hands up and down in a bason full of Angells"', '#editor'),
    194: ('his', 'high', '1652 n192 margin "thinking thereby to have charmed his gout, but it would not doe" (TCP "gour" is gout)', '#editor'),
    195: ('it', 'high', '1652 n192 margin, as for 194', '#editor'),
    203: ('σχῆμα', 'high', '1652 n196 margin "1 Cor. 7. 31. σχῆμα intimateth"', '#editor'),
    210: ('me', 'high', '1652 n200 body "that doth attend men under great outward mercies" (TCP keeps the "n")', '#editor'),
    211: ('כבד', 'medium', '1652 n200 margin "Gen. 13. 2. כבד" (last letter dalet, could be read resh); Gen. 13:2 כָּבֵד, heavy, very rich', '#editor'),
    214: ('Ἀνέλου σαυτῷ σὺ γὰρ οὐκ εἰ Θεμιστοκλης', 'medium', '1652 n210 margin "(Ἀνέλου σαυτῷ σὺ γὰρ οὐκ εἰ Θεμιστο-κλης)", parentheses outside the gap; Plutarch, Themistocles 18: ἀνελοῦ σαυτῷ· σὺ γὰρ οὐκ εἶ Θεμιστοκλῆς', '#editor'),
    218: ('ἀμελήσαντες', 'high', '1652 n216 margin "ἀμελήσαν-τες." (as gap 68); Matt. 22:5', '#editor'),
    223: ('פגעת', 'high', '1652 n225 margin "Isa. 64. v. 5. פגעת Paganta"; Isa. 64:5 פָּגַעְתָּ, unpointed', '#editor'),
    225: ('χρηστὸς', 'high', '1652 n229 margin "χρηστὸς i. e. my yoke is a benigne"; Matt. 11:30 ὁ ζυγός μου χρηστός', '#editor'),
    226: ('πονηρὸς', 'medium', '1652 n229 margin "opposed to πονηρὸς, painfull", faint', '#editor'),
    248: ('ירוע רוע', 'medium', '1652 n258 margin, two lines "ירוע / רוע a Jeroange from ruang"; the TCP has one gap for both words (yeroa, from roa); unpointed', '#editor'),
    257: ('ἐμπλεκεται', 'medium', '1652 n269 margin "2 Tim. 2. 4. ἐμπλεκεται" (no accent visible); 2 Tim. 2:4 ἐμπλέκεται', '#editor'),
    262: ('מחה', 'medium', '1652 n281 margin (top of the page after the note\'s start): "מחה An hebrew participle"; first letter looks closed like samekh in the print; Isa. 43:25 מֹחֶה, blotting out', '#editor'),
    279: ('Καινὴ κτίσις', 'high', '1652 n304 margin "2 Cor. 5. 17. Καινὴ κτί-σις a new creation"', '#editor'),
    280: ('ſa', 'medium', '1652 n307 margin "Pſa. 51. 10." (1653 may have had "Pſal."; a 〈…〉 gap in the TCP)', '#editor'),
    283: ('וימלא', 'high', '1652 n311 margin "Numb. 14. 24. וימלא hath fulfilled after me"; Num. 14:24 וַיְמַלֵּא, unpointed (a dagesh may show in mem)', '#editor'),
    286: ('Iohn', 'medium', '1652 n313 margin "Iohn 6. 68." (1653 may spell John)', '#editor'),
    295: ('שנא', 'high', '1652 n320 margin "Sanethi from שנא which signifies to hate"', '#editor'),
    297: ('πρὸς γένη', 'high', '1652 n321 margin "True hatred is πρὸς γένη against the whole kinde"; Aristotle, Rhet. 2.4: πρὸς τὰ γένη (article missing in the print)', '#editor'),
    329: ('Grotium', 'high', '1652 n350 margin "Vide Bezam, Grotium, & Estium"', '#editor'),
    330: ('Estium', 'high', '1652 n350 margin, as for 329', '#editor'),
    345: ('יסוד עולם', 'high', '1652 n384 margin (top), two lines "יסוד / עולם"; Prov. 10:25 יְסוֹד עוֹלָם, unpointed', '#editor'),
    360: ('מריבה', 'high', '1652 n404 margin "Gen. 13. 8. מריבה Oh let there be no bitterness"; Gen. 13:8 מְרִיבָה', '#editor'),
    365: ('Διώκετε', 'medium', '1652 n409 margin "Heb. 12. 14. Διώκετε it signifies", heavy print; Heb. 12:14 Διώκετε', '#editor'),
    366: ('בקש', 'high', '1652 n409 margin after "Psal. 34. 14."; Ps. 34:14 בַּקֵּשׁ, unpointed', '#editor'),
    367: ('ורדפהו', 'medium', '1652 n409 margin; Ps. 34:14 וְרָדְפֵהוּ; the last letter descends like final kaf (print may read ורדפהך, a misprint)', '#editor'),
    368: ('a רדף', 'medium', '1652 n409 margin "a רדף" (from radaph); the Latin "a" belongs to the note, as the TCP note is only the gap', '#editor'),
    17: ('μεθοδείας', 'medium', '1652 n29 body "the Greek μεθοδείας being derived from μετα and ὁδὸς" (small Greek type, legible)', '#editor'),
    18: ('μετα', 'medium', '1652 n29 body, no accent visible; correct μετά', '#editor'),
    19: ('ὁδὸς', 'high', '1652 n29 body "ὁδὸς,"', '#editor'),
    375: ('ברמך', 'medium', '1658 n337 margin "Hos. 4. 6. ברמך Cut off." (1652 n422 the same, first letter like kaf); a corrupt print of Hos. 4:6 נִדְמוּ (nidmu, are cut off): correct נדמו', '#editor'),
    377: ('Τὸ πῦρ παρ’ ἡμῶν ἡ δὲ φλὸξ τοῦ πνεύματα', 'medium', '1652 n427 margin "Τὸ πῦρ παρ\' ἡμῶν ηδε φλὸξ τȣ πνεύμα-τα." (accents on ἡ δὲ not visible, ου ligature); the Nazianzen saying is not verified: "πνεύματα" probably a misprint (πνεύματος?)', '#editor'),
    380: ('ſtas', 'high', '1652 n430 margin "Adversaria potestas non habet vim cogendi" (TCP keyed "po •e")', '#editor'),
    391: ('διαβολοὶ', 'medium', '1652 n437 body "called διαβολοὶ, Accusers" (no acute on the alpha visible); correct διάβολοι', '#editor'),
    392: ('πονηροὶ', 'high', '1652 n437 body "and πονηροὶ, evill ones"', '#editor'),
    393: ('συντρίψει', 'high', '1652 n437 margin "Rom. 16. 20. v συντρίψει"', '#editor'),
    400: ('πληροῦσθε', 'high', '1652 n448 margin "Ephes. 5. 18. v πληροῦσθε." (ου ligature)', '#editor'),
    406: ('not', 'high', '1658 n404 margin "Agrippas dormouse, that would not awake, till cast into boyling lead"', '#editor'),
    407: ('is ſo', 'high', '1658 n404 margin "wherein this duty of watchfulnesse is so strictly enjoyned"', '#editor'),
    412: ('Iſa.', 'high', '1652 n457 margin "the earth, Isa. 45. ver. 22." (TCP "45. 2•." follows the gap)', '#editor'),
    415: ('χωρὶς ἐμοῦ', 'high', '1652 n457 margin "Iohn 15. 5. χωρὶς ἐμοῦ is seorsim a me"', '#editor'),
    424: ('ברח דודי', 'medium', '1652 n464 margin, two lines "ברח / דודי Berahh dodi"; the second word may print as דורי; Song 8:14 בְּרַח דּוֹדִי, unpointed', '#editor'),
    428: ('er', 'high', '1658 n343 (appendix, 1658 p. 322) body "and I will not keep anger for ever. So Joel 2. 13."; Jer. 3:12; the appendix is not in the 1652', '#editor'),
    434: ('Joh.', 'medium', '1658 n357 margin "Joh. 1. 12." beside "of slaves, \'twill make you worthy sons" (blurred)', '#editor'),
    436: ('cho', 'medium', '1658 n360 body "the sweetest, humblest, choysest, and fruitfullest Christians"; the TCP keeps "iſeſt", so 1653 read choiſeſt', '#editor'),
    44: ('ſink', 'medium', '1652 n62 body "they shall presse and ſink down the greatest" (the word is certain; the 1653 spelling may be ſinke, which the TCP has 3 times beside 4 ſink)', '#editor'),
    97: ('ברית כרתי', 'high', '1652 n119 margin, two lines "ברית / כרתי" (bet may carry a dagesh); Job 31:1 בְּרִית כָּרַתִּי', '#editor'),
}

# --- letters: notes from the reading
# Letter gaps left open:
#  22  "conſen• ſer•" (p.7 note): the line-end hyphen of conſen-ſeris (1652 scan
#      n32 "conſen-ſeris"), not a letter; 23 = "is". Wants '' or a hyphen join.
#  73  "Pearle• in the world" (p.48 note): 1658 scan n72 "stone or Pearl in the
#      world": no letter; perhaps a comma or a speck.
#  113 "the ſtone to be • di•ged up" (p.91 note): 1652 scan n147 "to be dig-ged
#      up": nothing between "be" and "digged"; a speck.
#  201 "Pſaln•es" (p.128): printed "Pſalmes" (1652 scan n195); the TCP "n" plus the
#      gap is one "m", so the keyed "n" needs an emendation, not a fill.
#  217 "niſi• a ſeipſo" (p.142 note): 1652 scan n213 "niſi a ſeipſo": no letter.
#  287 "cloud & pillar• of fire" (p.226 note): 1652 scan n313 "pillar of fire": no letter.
#  355 "Gods work• &" (p.292 note): punctuation (comma or colon), not checked on a scan.
#  389 "If he tempts• you" (p.322): 1652 scan n433 "If he tempts you": no letter.
#  439, 440: catalogue and errata, skipped as instructed.
# No letter gap was found to stand for Greek or Hebrew.

# --- Greek and Hebrew: notes from the reading
# Notes for the proofreader
# - All 87 gaps are filled; none left open. Scans used: the 1652 first edition
#   (clear, with OCR coordinates, so used for most) and the 1658 (dark, no usable
#   OCR; used where it could be located: 10, 12-14, 16, 20-21, 25, 30-32, 57,
#   375, 406-407, and the Appendix gaps 428, 434, 436, which the 1652 lacks).
#   Both are other typesettings, so accents and spellings may differ from 1653.
# - "nN" in the evidence is the archive.org scan index of that edition.
# - Gaps where the TCP split a word: 13 (TCP "Non" = Greek Νοή-, whole word
#   Νοήματα), 31 (TCP "nen" = "men" of "lumen"), 190 ("ha" + "nd"),
#   210 ("me" + "n"), 380 ("po •e" + "ſtas"), 436 ("cho" + "iſeſt").
# - Low-certainty or doubtful prints: 375 (Hebrew corrupt in both editions),
#   377 (Greek ending "πνεύματα" unverified), 118, 367, 424 (Hebrew letter
#   shapes ה/ח, ו/ך, ד/ר), 211 (ד/ר).
