== Serving Each Other in the Fear of the Lord

#align(center)[
  #block(width: 85%)[
    #set par(justify: false)
    #text(size: 0.9em, weight: 600)[EPHES. 5. 21.]

    #emph[Submit your selues one to another in the feare of God.]
  ]
]

#v(0.8em)

=== §. 1. #emph[Of the Apostles transition from generall duties to particulars.]

As there are two vocations whereunto it hath pleased God to call euery one; #emph[one Generall,] by vertue whereof certaine common duties which are to be performed of all men, are required, (as knowledge, faith, obedience, repentance, loue, mercie, iustice, truth, &c.) #emph[the other Particular,] by vertue whereof certaine peculiar duties are required of seuerall persons, according to those distinct places wherein the Diuine Prouidence hath set them in Common-wealth, Church, or family; so ought Gods Ministers to be carefull in instructing Gods people in both kindes of duties; both those which concerne their #emph[generall,] and those also which concerne their #emph[particular] calling. Accordingly #emph[S. Paul] (who, as #footnote[#emph[Num.] 12. 7.] #emph[Moses,] was #emph[faithfull in all the house of God)] after he had sufficiently instructed Gods Church in such #emph[generall] duties, as belong to all Christians, of what sex, state, degree, or condition soeuer they be, proceedeth to lay downe certaine #emph[particular] duties, which appertaine to particular callings and conditions: among which, he maketh choise of those which God hath established in a family. With excellent Art doth he passe from those #emph[generals,] to these #emph[particulars:] laying downe a #emph[transition] betwixt them, in these words, #emph[Submitting your selues one to another in the feare of God;] which words haue reference both to that which goeth before, and also to that which followeth after. The forme and manner of setting downe this verse, with a participle thus, #emph[submitting,] sheweth that it dependeth on that which went before, and so hath reference thereunto. Againe, the word it selfe being the very same which is vsed #footnote[submitting., submit.] in the next verse following, sheweth, that this verse containeth the #emph[summe] of that which followeth, and so hath reference thereunto, as a generall vnto particulars. This manner of passing from one point to another, by a #emph[perfect transition] which looketh both wayes, both to that which is past, and to that which commeth on, as it is very elegant, so is it frequent with this our Apostle. Whereby he teacheth vs, #footnote[Note.] so to giue heed to that which followeth, as we forget not that which is past: as we must giue diligent attention to that which remaineth, so we must well retaine that which we haue heard, and not let it slip: otherwise, if (as one naile driueth out another) one precept maketh another to be forgotten, it will be altogether in vaine to adde line vnto line, or precept vnto precept.

=== §. 2. #emph[Of ioyning seruice to men with our praising of God.]

As this verse hath reference to that which was deliuered before, concerning our dutie to God, it teacheth vs this lesson:

#emph[It is the dutie of Christians as to set forth the praise of God, so to be seruiceable one to another.] For this purpose in the #footnote[Doct.] Decalogue to the first table, which prescribeth that duty which we owe to God, is added the second table, which declareth the seruice that we owe one to another: and he that said, #footnote[#emph[Matt.] 22. 38, 39.] #emph[The first and great Commandement is this, Thou shalt loue the Lord,] &c. said also, #emph[The second is like to this, Thou shalt loue thy neighbour,] &c. whereupon the #footnote[#emph[Heb.] 13. 15, 16.] Apostle declaring what those sacrifices be wherewith God is well pleased, ioyneth these two together, #emph[to giue thankes to God, and to doe good to man.] The seruice which in the feare of God we performe one to another, is an euident and reall demonstration of the respect we beare vnto God. #footnote[#emph[Psal.] 16. 2.] #emph[To God our goodnesse extendeth not.] #footnote[#emph[Iob] 22. 3. & 35. 7.] He is so high aboue vs, so perfect and compleat in himselfe, that neither can we giue to him, nor he receiue of vs. But in his owne stead he hath placed our brother like to our selues; to whom, #footnote[#emph[Iob] 35. 8.] as we may doe hurt, so by our faithfull seruice we may doe much #footnote[#emph[Psal.] 16. 3.] good: in doing whereof God is much honoured.

This discouereth their hypocrisie, who make great pretence #footnote[1\. #emph[Vse.] A note of hypocrisie.] of praising God, and yet are scornfull, and disdainfull to their brethren, and slothfull to doe any seruice to man: #emph[These mens religion is vaine.] By this note did the Prophets #footnote[#emph[Iam.] 1. 26. #emph[Isa.] 58. 3 #emph[&c. Mic.] 6. 6. #emph[&c. Matt.] 23. 14. 1 #emph[Ioh.] 4. 20.] in their time, and Christ and his Apostles in their time also, discouer the hypocrisie of those among whom they liued: and so may we also in our times. For many there be, who frequently in their houses, and in the middest of the Congregation sing praise vnto God, and performe other parts of Gods outward worship, but towards one another, are proud, stout, enuious, vnmercifull, vniust, slanderous, and very backward to doe any good seruice. Surely, that outward seruice which they pretend to performe to God, doth not so much wipe out the spot of prophanesse, as their neglect of dutie vnto man brandeth their foreheads with the stampe of hypocrisie. #footnote[2\. #emph[Vse.] Put not off one dutie with another. #emph[Matt.] 23. 23.]

For our parts, let vs not vpon pretext of one dutie, though it may seeme to be the waightier, thinke to shift off another; lest that fearefull #emph[woe] which Christ denounced against the #emph[Scribes] and #emph[Pharisies] fall vpon our pates. As God is carefull to instruct vs how to carrie our selues both to his owne Maiestie, and also one to another, so let vs in both approue our selues to him: remembring what Christ said to the Pharisies, #emph[These ought ye to haue done, and not to leaue the other vndone.] The same Lord that requireth praise to his owne Maiestie, inioyneth mutuall seruice one to another; the neglect of this, as well as of that, sheweth too light respect of his will and pleasure: #emph[What therefore God] #footnote[#emph[Matth.] 19. 6.] #emph[hath ioyned together, let not man put asunder.]

=== §. 3. #emph[Of euery ones submitting himselfe to another.]

Againe, as this verse hath reference to that which followeth, it declareth the generall summe of all, which is mutually to submit our selues one to another in the feare of God. The parts hereof are two:

- 1\. An Exhortation.
- 2\. A Direction.

In the exhortation is noted, both the #emph[dutie] it selfe in this word #emph[submit,] and also the #emph[parties] to whom it is to be performed, #emph[one to another.]

Both branches of the exhortation, viz. the #emph[dutie,] and the #emph[parties] ioyned together, afford this doctrine, that

#emph[It is a generall mutuall dutie appertaining to all Christians,] #footnote[2\. #emph[Doct.]] #emph[to submit themselues one to another:] For this precept is as generall as any of the former, belonging to all sorts and degrees whatsoeuer: and so much doth this word #emph[one another] imply: in which extent the Apostle in another place exhorteth to #emph[serue one another:] and againe, #emph[euery man to seeke] #footnote[#emph[Gal.] 5. 13. 1 #emph[Cor.] 10. 24.] #emph[anothers wealth.]

Concerning #emph[inferiours,] it is without question cleare, that #footnote[Quest.] they ought to submit themselues to their superiours: yea, concerning #emph[equals] no great question can be made, but they #emph[in giuing honour must goe one before another,] and so submit #footnote[#emph[Rom.] 12. 10. How superiours ought to subiect themselues.] themselues: but concerning #emph[superiours,] iust question may be made, whether it be a dutie required of them to submit themselues to their inferiours.

To resolue this doubt, we must first distinguish betwixt #footnote[Answ.] subiection of #emph[reuerence,] and subiection of #emph[seruice.]

#emph[Subiection of reuerence] is that whereby one testifieth an eminencie and superioritie in them whom he reuerenceth, and that in speech, by giuing them titles of honour; or in gesture, by some kinde of obeysance; or in action, by a ready obeying of their commandement. This is proper to inferiours.

#emph[Subiection of seruice] is that whereby one in his place is #footnote[Difference betwixt subiection of #emph[Reuerence] and #emph[Seruice.]] ready to doe what good he can to another. This is common to all Christians: a dutie which euen superiours owe to inferiours, according to the fore-named extent of this word #emph[one another:] in which respect euen the highest gouernour on earth is called a #emph[minister,] for the good of such as #footnote[#emph[Rom.] 13. 4.] are vnder him.

Secondly, we must put difference betwixt the #emph[worke] it #footnote[Difference betwixt the #emph[worke] and #emph[manner] of doing it.] selfe, and the #emph[manner] of doing it. That worke which in it selfe is a worke of superioritie and authoritie, in the manner of doing it may be a worke of submission, viz. if it be done in humilitie and meeknesse of minde. The Magistrate by ruling with meeknesse and humilitie, submitteth himselfe to his subiect. In this respect the Apostle exhorteth that #emph[nothing] (no not the highest and greatest workes that #footnote[#emph[Phil.] 2. 3.] can be) #emph[be done in vaine-glory, but in meeknesse.]

Thirdly, we must distinguish betwixt the seuerall places wherein men are: for euen they who are superiours to some, #footnote[Euery one vnder some authoritie. #emph[Matth.] 8. 9.] are inferiours to others: as he that said, #emph[I haue vnder me, and am vnder authoritie.] The master that hath seruants vnder him, may be vnder the authoritie of a Magistrate. Yea, God hath so disposed euery ones seuerall place, as there is not any one, but in some respect is vnder another. The wife, though a mother of children, is vnder her husband. The husband, though head of a family, is vnder publike Magistrates. Publike Magistrates one vnder another, and all vnder the King. The King himselfe vnder God and his word deliuered by his Ambassadours, whereunto the highest are to submit themselues. And Ministers of the word, as subiects, are vnder their Kings and Gouernours. He that saith, #emph[Let euery soule be subiect to the higher powers,] #footnote[#emph[Rom.] 13. 1.] excepteth not Ministers of the word: and he that saith, #emph[obey them that haue the ouersight of you, and submit your selues,] #footnote[#emph[Heb.] 13. 17. Difference betwixt Magistrates and Ministers authoritie.] excepteth not kings: only the difference is in this, that the authoritie of the king is in himselfe, and in his owne name he may command obedience to be performed to himselfe: but the authoritie of a Minister is in Christ, and in Christs name only may he require obedience to be performed to Christ.

The reason why all are bound to submit themselues one #footnote[#emph[Reason.] Euery ones Office for the good of another.] to another is, because euery one is set in his place by God, not so much for himselfe, as for the good of others: whereupon the Apostle exhorteth, that #emph[none seeke his owne, but euery man anothers wealth.] Euen Gouernours are aduanced #footnote[1 #emph[Cor.] 10. 24.] to places of dignitie and authoritie, rather for the good of their subiects then for their owne honour. Their callings are in truth offices of seruice, yea burdens vnder which they must willingly put their shoulders, being called of God, and of which they are to giue an account concerning the good which they haue done to others: for the effecting whereof, it is needfull that they submit themselues.

Let euery one therefore high and low, rich and poore, #footnote[1\. #emph[Vse.] Exhòrtation vnto all to doe seruice.] superiour and inferiour, Magistrate and subiect, Minister and people, husband and wife, parent and childe, master and seruant, neighbours and fellowes, all of all sorts in their seuerall places take notice of their dutie in this point of submission, and make conscience to put it in practice: #emph[Magistrates,] by procuring the wealth and peace of their people, as #emph[Mordecai: Ministers,] by making themselues seruants #footnote[#emph[Est.] 10. 3.] vnto their people, not seeking their owne profit, but the #footnote[1 #emph[Cor.] 9. 19. & 10. 33.] profit of many, that they may be saued, as #emph[Paul: Fathers,] by well educating their children, and taking heed that they #emph[prouoke them not to wrath,] as #emph[Dauid: Husbands,] #footnote[#emph[Prou.] 4. 3, 4.] by dwelling with their wiues according to knowledge; giuing honour to the wife as to the weaker vessell, as #emph[Abraham:] #footnote[#emph[Gen.] 16. 6.] #emph[Masters,] by doing that which is iust and equall to their seruants, as the #emph[Centurion:] Euery one, by being of like #footnote[#emph[Luke] 7. 2.] affection one towards another, and by seruing one another in loue, according to the Apostles rule. Let this dutie of #footnote[#emph[Rom.] 12. 16. #emph[Gal.] 5. 13.] submission be first well learned, and then all other duties will better be performed.

Be not high minded, nor swell one against another. #footnote[2\. #emph[Vse.] Dehortation from swelling one against another.] Though in outward estate some may be higher than other, yet #emph[in Christ all are one whether bond or free:] all #emph[members of one and the same body.] Now consider the mutuall affection (as I may so speake) of the members of a naturall body one towards another: not any one of them will puffe it selfe vp, #footnote[#emph[Gal.] 3. 28.] and rise against the other: the head which is the highest #footnote[1 #emph[Cor.] 12. 27.] and of greatest honour will submit it selfe to the feet in performing the dutie of an head, as well as the feet to the head in performing their dutie; so all other parts. Neither is it hereby implied that they which are in place of dignitie and authoritie should forget or relinquish their place, dignitie, or authoritie, and become as inferiours vnder authoritie, no more than the head doth: for the head in submitting it selfe doth not goe vpon the ground and beare the body, as the feet; but it submitteth it selfe by directing and gouerning the other parts, and that with all the humilitie, meeknesse, and gentlenesse that it can. So must all superiours: much more must equals and inferiours learne with humilitie, and meeknesse, without scorne or disdaine, to performe their dutie: this is that which was before by the Apostle #footnote[#emph[Ephes.] 4. 2.] expresly mentioned, and is here againe intimated; none are exempted and priuileged from it. We know that it is vnnaturall, and vnbeseeming the head to scorne the feet, and to swell against them, but more than monstrous for one hand to scorn another: what shall we then say if the feet swel against the head? Surely such scorne and disdaine among the members, would cause not only great disturbance, but also vtter ruine to the body. And can it be otherwise in a politique body? But on the contrarie, when all of all sorts shall (as hath beene before shewed) willingly submit themselues one to another, the whole body, and euery member thereof will reape good thereby: yea, by this mutuall submission, as we doe good, so we shall receiue good.

=== §. 4. #emph[Of the feare of God.]

Hitherto of the #emph[exhortation.] The #emph[direction] followeth. #emph[In the feare of the Lord.] This clause is added, to declare partly the #emph[meanes,] how men may be brought to submit themselues readily one to another: and partly the #emph[manner,] how they ought to submit themselues. #emph[The feare of the Lord] is both the #emph[efficient cause] that moueth a true Christian willingly to performe all dutie to man, and also the #emph[end] whereunto he referreth euery thing that he doth. For the better conceiuing whereof, I will briefly declare

- 1\. What this feare of the Lord is.
- 2\. How the Lord is the proper obiect of it.
- 3\. What is the extent thereof.
- 4\. Why it is so much vrged.

First, feare of God is an awfull respect of the diuine Maiestie. #footnote[1\. What the feare of God is. The causes of it.] Sometimes it ariseth from faith in the mercy and goodnesse of God: for when the heart of man hath once felt a sweet taste of Gods goodnesse, and found that in his fauour only all happinesse consisteth, it is strucken with such an inward awe and reuerence, as it would not for any thing displease #footnote[Two effects of a filiall feare of God.] his Maiestie, but rather doe whatsoeuer it may know to be pleasing and acceptable vnto him. For these are two effects which arise from this kinde of feare of God:

1. #emph[A carefull endeuour to please God,] in which respect #footnote[#emph[Deum timere est nulla mala facere, & nulla bona quae faci enda sunt praete rire. Bernar. de modo benè viuen. ser.] 4.] good king #emph[Iehosaphat] hauing exhorted his Iudges to execute the iudgement of the Lord aright, addeth this clause as a motiue thereunto, #emph[Let the feare of the Lord be vpon you:] implying thereby that Gods feare would make them endeuour to approue themselues to God.

2. #emph[A carefull auoiding of such things as offend the Maiesty of God,] and grieue his spirit: in which respect the Wiseman #footnote[2 #emph[Chro.] 19. 6, 7.] saith, #emph[The feare of the Lord is to hate euill:] and of #emph[Iob] it is #footnote[#emph[Prou.] 8. 13.] said that he #emph[fearing God departed from euill.] #footnote[#emph[Job.] 1. 1.]

Sometimes againe, awe and dread of the diuine Maiestie ariseth from diffidence: For when a mans heart doubteth of Gods mercy, and expecteth nothing but vengeance, the very thought of God striketh an awe or rather dread into him, and so maketh him feare God.

From this double cause of feare, whereof one is contrary #footnote[Difference betwixt filiall and seruile feare.] to another, hath arisen that vsuall distinction of a #emph[filiall] or sonne-like feare, and a #emph[seruile] or slauish feare: which distinction is grounded on these words of the Apostle, #emph[ye haue not receiued the spirit of bondage againe to feare] (this is #footnote[Bernard. loc. citat.] a seruile feare) #emph[but ye haue receiued the spirit of adoption] #footnote[#emph[Rom.] 8. 15.] #emph[whereby we cry, Abba, father:] this causeth a filiall feare. The #emph[filiall] feare is such a feare as dutifull children beare to their fathers. But the #emph[seruile] feare is such an one as bondslaues beare to their masters. A sonne feareth simply to offend or displease his father: so as #footnote[#emph[Est timor ne amittatur gratia beneficij. Hic timor cast us est, non eum charitas eijcit, sed asciscit. August. epist.] 120.] it is accompanied with loue. A bondslaue feareth nothing but the punishment of his offence; so as it is ioyned with hatred: and such an one feareth not to sinne, but to burne in hell for sinne. Faithfull #emph[Abraham] like a gratious childe feared God (as Gods Angell beareth witnesse, #emph[Gen.] 22. 12.) when he was ready rather to sacrifice his only sonne, then offend God by refusing to #footnote[#emph[Qui gehennas metuit, non peccare metuit sed ardere. Aug. epist.] 144.] obey his commandement. But faithlesse #emph[Adam] like a seruile bondslaue feared God (as he himselfe testifieth against himselfe #emph[Gen.] 3 10.) when after he had broken Gods commandement, he hid himselfe from the presence of God. This slauish feare is a plaine diabolicall feare (for #emph[the deuils] #footnote[#emph[Jam.] 2. 19.] so feare as they #emph[tremble:)] It maketh men wish there were no hell, no day #emph[of Iudgement,] no Iudge, yea no God. This is that feare #emph[without which] we must serue the Lord. In this #footnote[#emph[Luke] 1. 74.] feare to submit ones selfe is nothing acceptable to God: It is therefore the #emph[filiall feare] which is here meant.

Secondly, of this feare God is the proper #emph[obiect,] as by #footnote[2\. How God is the proper obiect of feare.] this and many more testimonies of Scripture is euident, where the feare of #emph[God] and of #emph[the Lord] is mentioned. This feare hath so proper a relation vnto God, as the Scripture stileth God by a kinde of proprietie, with this title #emph[Feare:] for where #emph[Iaakob] mentioneth #emph[the feare of Isaak,] he meaneth #footnote[#emph[Gen.] 31. 42, 53.] the Lord whom #emph[Isaak] feared.

It is then vnlawfull to feare any but God? #footnote[Quest.]

No: Men also may be feared, as Princes, Parents, Masters, #footnote[#emph[Ans.] How men are to be feared.] and other superiours; For the Apostle exhorting to giue euery one their due, giueth this instance, #emph[feare,] #footnote[#emph[Rom.] 13. 7.] #emph[to whom feare is due.] But yet may God notwithstanding be said to be the proper obiect of feare, because all the feare that any way is due to any creature, is due to him in and for the Lord whose image he carrieth: so as in truth it is not so much the person of a man, as the image of God placed in him, by vertue of some authoritie or dignitie appertaining to him, which is to be feared. If there should fall out any such opposition betwixt God and man, as in fearing man our feare would be withdrawne from God, then the rule of Christ is to take place, which is this, #emph[feare not them which] #footnote[#emph[Matth.] 10. 28.] #emph[kill the body, but are not able to kill the soule: but rather feare him which is able to destroy both soule and body in hell.]

Thirdly, the extent of this true filiall feare of God is #footnote[3\. Euery dutie to be seasoned with a feare of God.] very large. No one point throughout the whole Scripture is more vrged than this #emph[feare of the Lord.] It is oft added to other duties, as that whereby they are seasoned, and without which they cannot well be performed: wherefore we are commanded to #emph[serue the Lord in feare, to perfect holinesse] #footnote[#emph[Psal.] 2. 11.] #emph[in the feare of God, to worke out our saluation with feare:] and #footnote[2 #emph[Cor.] 7. 1.] the Churches are commended for #emph[walking in the feare of the] #footnote[#emph[Phil.] 2. 12.] #footnote[#emph[Acts] 9. 31.] #emph[Lord:] so likewise particular men as #footnote[a #emph[Gen.] 22. 12.] #emph[Abram,] #footnote[b & 42. 18.] #emph[Ioseph,] #footnote[c #emph[Iob] 1. 1.] #emph[Iob,] and many other: yea the whole worship of God is oft comprised vnder this branch of #emph[feare:] whereupon our Sauiour Christ alleaging this text, #emph[thou shalt feare the Lord thy God,] #footnote[#emph[Deut.] 6. 13.] thus expresseth it, #emph[thou shalt worship the Lord thy God.] And #footnote[#emph[Matth.] 4. 10.] againe where the Lord by his Prophet #emph[Isay] saith, #emph[Their feare] #footnote[#emph[Isa.] 29. 13.] #emph[toward me is taught by the precept of men,] Christ thus quoteth that text, #emph[In vaine doe they worship me, teaching for doctrines] #footnote[#emph[Matth.] 15. 9.] #emph[the commandements of men:] out of which places compared together, it is euident, that vnder the #emph[feare] of God, is comprised the #emph[worship] of God. Yea, all that dutie which we owe to God and man is comprised vnder this title, #emph[the feare of God:] for #emph[Dauid] when he would in one word declare the summe and substance of all that which a Minister ought to teach his people, saith, #emph[I will teach you the feare of] #footnote[#emph[Psal.] 34. 11.] #emph[the Lord.] #footnote[4\. Why a feare of God is so much vrged.]

Fourthly, The reason why the Holy Ghost so much vrgeth #emph[the feare of God,] and that in so large an extent as hath beene shewed, I take to be this; to shew a difference betwixt that integritie and perfection of Gods image which was at mans creation first planted in him, and the renouation thereof while here he liueth in this world. So compleat and perfect was then Gods image in man, as he needed no other motiue to prouoke him to any dutie but #emph[loue.] Wherefore when the Holy Ghost would set forth that perfection of Gods image first planted in man, he addeth this title #emph[Loue] vnto other duties, whether they concerne God or man. Concerning God, #emph[Moses] exhorteth Israel to #emph[loue the] #footnote[#emph[Deut.] 11. 13.] #emph[Lord and serue him:] and againe, #emph[to loue the Lord, to walke in] #footnote[#emph[Deut.] 30. 16.] #emph[his waies, to keepe his commandements, &c.] Concerning man, the Apostle exhorteth to #emph[serue one another by loue:] and #emph[to doe] #footnote[#emph[Gal.] 5. 13.] #emph[all things in loue.] Yea, sometimes the Holy Ghost is pleased #footnote[1 #emph[Cor.] 16. 14.] to comprise all duties vnder #emph[loue:] In which respect Christ calleth this commandement #emph[(Thou shalt loue the Lord) the] #footnote[#emph[Matth.] 22. 38.] #emph[great commandement,] which compriseth all the commandements of the first table vnder it: and for the second table, #emph[S. Paul] saith, that #emph[loue is the fulfilling of the law.] But by #emph[Adams] #footnote[#emph[Rom.] 13. 10.] fall, and the corruption which thereby infected mans nature, the loue of God hath waxed cold in man, and though the Saints be created againe according to that image of God, yet while in this world they liue, that image is not so perfect as it was, the flesh remaineth in the best: in which respect God hath fast fixed this affection of #emph[feare] in mans heart, and thereby both restraineth him from sinne, and also prouoketh him vnto euery good dutie.

=== §. 5. #emph[Of the feare of God mouing vs to doe seruice to men.]

Hauing briefly declared the #emph[nature, obiect, extent,] and #emph[vse] of feare, I returne to the point in hand, #emph[viz.] to shew 1. how it is here laid downe as a motiue to stirre vp men to performe the dutie here required: for by this clause, #emph[in the feare of the Lord,] the Apostle implieth that

#emph[It is the feare of God which moueth men conscionably to submit] #footnote[Doct.] #emph[themselues one to another.] This made #footnote[2\. #emph[Sam.] 23. 3.] #emph[Dauid] so well to rule the people of God: and #footnote[#emph[Gen.] 42. 18.] #emph[Ioseph] to deale so well with his brethren: yea, #footnote[#emph[Isa.] 11. 2, 3.] this is noted to be the cause of the righteous regiment of Christ himselfe. Well did that good King #emph[Iehosaphat] know this, and therefore when he appointed Iudges ouer his people, as a motiue to stirre them vp to execute the iudgements of the Lord aright, he saith vnto them, #emph[Let the feare of the Lord be vpon you.] So also #emph[S. Peter,] #footnote[2 #emph[Chron.] 19. 7.] to moue subiects to honour their King, prefixeth this exhortation, #emph[Feare God.] #footnote[1 #emph[Pet.] 2. 17.]

By feare of man, may one be brought to submit himselfe #footnote[Obiect.] to another: as a magistrate may be moued to deale iustly and mildly with his people through feare of insurrections and rebellions: subiects may by seuere lawes and tyrannie be brought to submit themselues: and so other inferiours also by threats, by hard vsage, and other by-respects.

1. Though feare of man be a motiue, yet it followeth #footnote[Answ.] not, that therefore feare of God should be no motiue: it may be another motiue, and a better motiue.

2. The submission which is performed through feare of #footnote[Difference betwixt doing a thing for feare of God and feare of man.] man is a forced and a slauish submission, nothing acceptable to God: but that which is performed through a true filiall feare of God, is a free, willing, ready, cheerefull, conscionable submission: such a submission as will stirre vs vp to doe the best good we can thereby vnto them, to whom we submit our selues, and so is more acceptable to God, by reason of the cause thereof, and more profitable vnto man, by reason of the effect and fruit thereof.

For a true feare of God maketh vs more respect what #footnote[#emph[Reason.] The power of a feare of God.] God requireth and commandeth, than what our corrupt heart desireth and suggesteth: It subdueth our vnruly passions, and bringeth them within compasse of dutie: It maketh vs deny our selues and our owne desires: and though through the corruption of our nature and inborne pride we be loth to submit, yet will Gods feare bring downe that proud minde, and make vs humble and gentle. It will keepe those who are in authoritie from tyranny, crueltie, and ouer-much seueritie: and it will keepe those who are vnder subiection from dissimulation, deceit, and priuie conspiracies.

Behold how necessarie it is, that a true feare of the Lord #footnote[#emph[Vse.] The necessitie of a feare of God.] be planted in mens hearts, in the hearts of Kings and all Gouernours, in the hearts of subiects and all people, whether superiours or inferiours. Where no feare of God is, there will be no good submission vnto man. #emph[Abraham] #footnote[#emph[Gen.] 20. 11.] thought that the men of Gerar would haue no respect to him or his wife, nor make conscience of common honestie, nor abstaine from innocent bloud, because #emph[he saw no feare of God in that place:] and the Apostle hauing reckoned vp #footnote[#emph[Rom.] 3. 11, #emph[&c.]] many notorious effects of mans naturall corruption, concludeth all with this, as the cause of all, #emph[There is no feare of God before their eyes.] Wherefore let Magistrates, Parents, Masters, and all in authoritie, haue especiall care that their subiects, children, seruants, and all vnder them may be taught and brought to feare the Lord. I dare auouch it, that such inferiours which are taught to feare God, will doe better seruiee to their superiours, than such as feare their superiours only as men, and feare not God. Let Ministers especially vrge and presse vpon the consciences of men a feare of God. Let all inferiours pray that the feare of the Lord may be planted in the hearts of their superiours, that so they may liue a quiet and peaceable life in all godlinesse and honestie vnder them. Happie is that kingdome where Magistrates and subiects feare the Lord. Happie is that Church where Ministers and people feare the Lord. Happie is that family where husband and wife, parents and children, master and seruants feare the Lord. In such a Kingdome, Church, and family, will euery one, to the mutuall good one of another, submit themselues one to another. But if such as feare not God submit themselues, whether they be superiours or inferiours, it is for their owne ends and aduantages, and not for their good to whom they submit themselues.

=== §. 6. #emph[Of limiting all dutie to man, within the compasse of the feare of God.]

Againe, as this clause #emph[(In the feare of the Lord)] declareth the manner of submission, it sheweth, that

#emph[No submission is to be performed vnto man, but that which] #footnote[Doct.] #emph[may stand with the feare of God.] Whereby we shew that we haue respect to God, and labour aboue all to approue our selues to him. Thus #emph[Dauid] is commanded to #emph[rule in the] #footnote[2 #emph[Sam.] 23. 3.] #emph[feare of God:] and other Magistrates to performe their dutie #footnote[2 #emph[Chro.] 19 9.] #emph[in the feare of the Lord:] which #emph[Nehemiah] that good Gouernour #footnote[#emph[Neh.] 5. 15.] was carefull to doe. So also subiects are to obey in the #emph[feare of the Lord,] which the Apostle implieth by prefixing #footnote[1 #emph[Pet.] 2. 17.] this precept, #emph[Feare God,] before that, #emph[Honour the King;] as if he had said, so honour the King, as in and thereby you may manifest your feare of God: let not this latter crosse the former. Seruants likewise are commanded to be obedient vnto their Masters with this prouiso, #emph[fearing the Lord.] Such #footnote[#emph[Coloss.] 3. 22.] phrases as these, #emph[For the Lords sake, As vnto the Lord, In the] #footnote[1 #emph[Pet.] 2. 13.] #emph[Lord, As seruants of Christ,] with the like, being annexed to #footnote[#emph[Eph.] 5. 22. #emph[&] 6. 1, 6.] the duties of inferiours, doe imply as much.

Great reason there is that all seruice should be limited #footnote[1\. #emph[Reason.] God the highest Lord.] with the #emph[feare of God:] for God is the highest Lord to whom all seruice primarily and principally is due: whatsoeuer seruice is due to any man, high or low, is due in and for the Lord. The Lord hath set superiours in the places of eminencie, wherein they beare the image of God. The Lord also hath set inferiours in their places, and commended them as his charge to the gouernment of those who are ouer them. He that obeyeth not those who are ouer him #emph[in the feare of God,] sheweth no respect of Gods image: and he who gouerneth not those who are vnder him #emph[in the feare of God,] sheweth no respect of Gods charge.

Besides, God is that great Iudge to whom all of all sorts, #footnote[2\. #emph[Reason.] God the Iudge of all.] superiours and inferiours are to giue an account of their seruice. Though by our seruice we haue neuer so well approued our selues to men, yet if we haue not therein had respect vnto God, and approued our selues to him, with what face may we appeare before his dreadfull iudgement seat? #footnote[1\. #emph[Vse.] The folly of all those who feare man more than God.] Can the fauour of those whom we haue pleased in this world, protect and shelter vs from the fury of Gods displeasure?

Behold the folly of such Gouernours as wholly apply themselues to the fancie of their people, yea though it be against the Lord and his word. This was #emph[Adams] folly, who #footnote[#emph[Gen.] 3. 6.] at his wiues motion did eat of the forbidden fruit. This was #emph[Aarons] folly, who to please the people, erected an #footnote[#emph[Exod.] 32. 1.] Idoll. And this was #emph[Sauls] folly, who against Gods expresse #footnote[1 #emph[Sam.] 15. 21.] prohibition suffered his people to take some of the spoile of the Amalekites. The like may be said of #emph[Ioash,] who #footnote[2 #emph[Chro.] 24 7.] hearkned to his Princes to set vp Idols: and of #emph[Pilate,] who #footnote[#emph[Marke] 15. 15.] to please the people, against his conscience, deliuered Christ to be crucified. The fearefull issue of this their submission, not seasoned with a feare of God, but contrary thereunto, may be a warning to all superiours, to take heed how they seeke to please them that are vnder them, more than God who is aboue them. The issue of #emph[Adams, Aarons, Sauls,] and #emph[Ioash] his base submission, is noted by the Holy Ghost in their seuerall histories. Of #emph[Pilate] it is recorded, that being #footnote[#emph[Euscb. hist. Eccl. lib] 2. #emph[cap.] 7.] brought into extreme necessitie, he laid violent hands vpon himselfe.

Neither is it to be accounted folly only in superiours to submit themselues to their inferiours against the Lord, but also in inferiours to their superiours: for thereby they shew that they feare man more than God, which Christ expresly #footnote[#emph[Luke] 12. 4, 5.] forbiddeth his friends to doe. The captaines which went #footnote[2 #emph[King.] 1. 9, #emph[&c.]] to fetch #emph[Eliah,] obeyed their king therein; but what got they thereby? was the king able to saue them from the fire which God sent downe from heauen vpon them? The women #footnote[#emph[Ier.] 44. 19.] reproued for offering incense to the Queene of heauen, did it not without their husbands, yet were they not excused thereby. The children and others in the familie #footnote[#emph[Numb.] 16. 32.] submitted themselues to #emph[Dathan] and #emph[Abiram] in standing in the doore of their tents at defiance against #emph[Moses;] but because it was not in the Lord, but against him, they were not exempted from the iudgement. Wherefore let all of all sorts set the #emph[feare of God] as a marke before them to aime at in all their actions. Let superiours #footnote[#emph[Numb.] 11. 29.] neither doe any thing to giue content to their inferiours: #footnote[1 #emph[Sam.] 24. 8. #emph[&] 26. 9.] nor suffer any thing to be done for their sakes by their inferiours, which cannot stand with the #emph[feare of God.] And let inferiours #footnote[#emph[Gen.] 39. 10.] nor doe, #footnote[1 #emph[Sam.] 22. 17.] #footnote[#emph[Act.] 4. 19.] nor forbeare to doe at the will of their superiours any thing sweruing from the feare of God: but #emph[euery one submit themselues one to another in the feare of God.]
