== 2. Of the Household Service of God

A family, for the good estate of it self, is bound to the performance of two duties; one to God, the other to it self.

The duty unto God, is the private Worship and Service of God, which must be established and settled in every family. And the reasons hereof are these.

First, because this duty standeth by the express commandment of God, who by his Apostle willeth men #emph[to pray every where, lifting up pure hands, without wrath or doubting,] 1. Tim. 2. 8.

#emph[Again, it is confirmed by the custom and practise of holy men in their times;] I know #emph[(saith the Lord touching] Abraham) that he will command his sons and his household after him, that they keep the way of the Lord to do righteousness and judgement, that the Lord may bring upon Abraham, that which he hath spoken to him, #emph[Gen. 18. 19. To the same purpose speaketh] Joshua; If it seem evil unto you to serve the Lord, choose this day whom ye will serve, whether the gods whom your Fathers served (that were beyond the flood) or the gods of the Amorites in whose land ye dwell: But I and my house will serve the Lord, #emph[Josh. 24. 15. And] Cornelius #emph[is reported to have been] a devout man, and one that feared God with all his household, #emph[Act.] 10. 2.

#emph[Thirdly, common reason and equity showeth it to be a necessary duty; for the happy and prosperous estate of the family, which consisteth in the mutual love and agreement of the Man and wife, in the dutiful obedience of children to their parents, and in the faithful service of servants to their masters, wholly dependeth upon the grace and blessing of God, and this blessing is annexed to his worship: for 1. Tim.] 4. 8. Godliness hath the promises of this life, and the life to come. #emph[Psalm.] 127. 1. Except the Lord build the house, they labour in vain that build; except the Lord keep the City, the keeper watcheth in vain. #emph[Vers.] 2. It is in vain for you to rise early, and to lie down late, and eat the bread of sorrow, but he will surely give rest to his beloved. #emph[Vers.] 3. Behold, children are the inheritance of Jehovah, and the fruit of the womb his reward. #emph[Psalm.] 128. 1. Blessed is every one that feareth the Lord, and walketh in his ways. #emph[Vers.] 2. When thou eatest the labours of thy hands thou shalt be blessed, and it shall be well with thee. #emph[Vers.] 3. Thy wife shall be as the fruitful vine upon the sides of thy house, and thy children like Olive plants round about thy table. #emph[Vers.] 6. Yea, thou shalt see thy childrens children, and peace upon Israel. 1. #emph[Sam.] 1. 27. I prayed #emph[(saith] Hannah) for this child, and the Lord hath given me my desire which I asked of him.

#emph[The household service of God hath two parts; the first is a conference upon the word of God, for the edification of all the members thereof, to eternal life. The second is, Invocation of the name of God, with giving of thanks for his benefits; both these are commended in the Scriptures. Deut.] 6. 6. These words which I command thee this day, shall be in thy heart. #emph[Vers.] 7. And thou shalt whet them upon thy children, & talk of them when thou tariest in thine house, & as thou walkest by the way, and when thou liest down, and when thou risest up. #emph[Vers.] 20. When thy son shall ask thee in time to come, saying, what mean these testimonies, and ordinances, and laws, which the Lord our God hath commanded you? #emph[Vers.] 21. Then thou shalt say unto thy son, we were #emph[Pharaohs] bondmen in Egypt, but the Lord brought us out of Egypt with a mighty hand. #emph[Vers.] 24. Therefore the Lord hath commanded us to do all these ordinances, & to fear the Lord our God. #emph[Psal.] 14. 1. The fool hath said in his heart, There is no God. #emph[v.] 4. They cal not upon God.

The times of this service are these:

The morning, in which the family coming together in one place, is to call upon the name of the Lord, before they begin the works of their callings.

The evening also is another time to be used in prayer, because the family hath seen the blessing of God upon their labours the day before, and now the time or rest draweth on, in which every one is to commend his body and soul into the protection of the Lord; for no man knoweth what shall befall him before he rise again, neither knoweth any whether ever he shall rise again or not, it is therefore a desperate boldness without praying to go to rest.

Besides this, there be other times also wherein to perform this duty, as before and after meals; For meats and drinks are blessed to the receivers, by the word and prayer. 1. Tim. 4. 4. #emph[Whatsoever God hath created is good, neither is any thing to be refused, if it be taken with thanksgiving, for it is sanctified by the word of God and prayer.]

#emph[Now these times, the word of God approves. Deut.] 6. 6. Thou shalt talk of them, when thou liest down, and when thou risest up. #emph[Psalm.] 55. 18. Evening and morning and at noon, I will pray and make a noise, and he will hear my voice. #emph[Psa.] 127. 1. It is in vain to rise early, and to lie down late, and eat the bread of sorrow, #emph[except the Lord vouchsafe a blessing,] who will surely give rest to his beloved.

#emph[To these may sometimes be added the exercise of fasting, which is (as occasion serveth) to be used both publicly & privately, especially when they of the family be thereunto called by some present or imminent calamity. Hest. 4. 16.] Go and assemble all the Jews that are found in Shusan, and fast ye for me, and eat not, nor drink in three days, day nor night: I also and my maids will fast likewise, and so will I go in to the King, which is not according to the law; and if I perish, I perish. #emph[Zachar.] 12. 11. And in that day shall there be a great mourning in Jerusalem, and the land shall bewail, every family apart, the family of the house of #emph[David] apart, and their wives apart, the family of the house of #emph[Nathan] apart, and their wives apart, #emph[&c.]

Wherefore, those families wherein this service of God is performed, are, as it were, little Churches, yea even a kind of paradise upon earth. And for this purpose S. #emph[Paul] writing to #emph[Philemon, greeteth the Church that is in his house,] Philem. 1. 2. And in like manner, he sendeth salutations to the Church of Corinth, from #emph[Aquila] and #emph[Priscilla,] and #emph[the Church which was in their house,] 1. Cor. 16. 19. On the otherwise, where this duty of Gods service is not used, but either for the most part, or altogether neglected, a man may term those families, no better then companies of profane and graceless Atheists, who as they deny God in their hearts, so they are known by this note, that #emph[they do not call upon the name of the Lord,] Psalm. 14. 4. Yea such families are fitly compared to an heard of swine, which are always feeding upon the mast with greediness, but never look up to the hand that beateth it down, nor to the tree from whence it falleth.

The other duty concerning the house it self, is, That every member in the family, according to their ability, employ themselves in some honest and profitable business, to maintain the temporal estate and life of the whole. Gen. 3. 19. #emph[In the sweat of thy face shalt thou eat bread, till thou return to the earth, for out of it wast thou taken; for dust thou art, and to dust shalt thou return.] 1. Cor. 7. 20. #emph[Let every man abide in the same vocation wherein he was called.] Now if any one in the family starteth aside out of his calling, and enticeth another to idolatry, he is to be revealed, Deut. 13. 6. And again, their case is very fearful that do nothing in their houses, but go finely and fair daintily from day to day. This is the black mark that the Scripture sets upon the rich glutton, Luk. 16. 19. #emph[There was a certain rich man, which was clothed in purple and fine linen, and fared deliciously every day.]
