== 13. Of the Parent

Hitherto hath been treated of the first Couple, whereof the family consisteth, namely, of married folks. Now follow the other; and they are of two sorts; either such as, whereby the family is increased, and multiplied; or such as are helps thereunto.

Those whereby the family is enlarged, are also of two sorts; parents and children.

Parents are they which have power and authority over children.

The duties of parents are especially two; One to bring up their children; The other to bestow them, when they have brought them up.

Touching education or bringing up of children, the parents care must be, both that they may live, and also that they may live well, Ephes. 6. 4.

Touching the preservation of the life of the child, there are many duties required of the parents, specially four. First, the mother is her self to give the infant suck, and to wrap it up in swaddling clothes. #emph[Paul] commends it for a note of a good wife, #emph[to nurse her own children,] 1. Tim. 5. 10. Thus #emph[Sarah] gave suck to #emph[Isaac,] Gen. 21. 7. #emph[Hannah] nursed #emph[Samuel,] 1. Sam. 1. 22. #emph[David] in likelihood was nursed by his mother, Psal. 22. 9. #emph[Thou gavest me hope even at my mothers breasts.] And our Saviour Christ was also nursed by #emph[Mary] his mother, Luk. 11. 27. And swaddled, Luk. 2. 7. Now the reason hereof is plain. God hath given milk to women that bear children, & hath so appointed, that no meat is more natural to the child, then the mothers milk. And nature it self teacheth this in the course of other creatures. The earth nourisheth that which it bringeth forth. The fruit which the tree beareth is fed by the sap that comes from the root thereof. Yea amongst the brute beasts, even those that be most savage, as the Tigers, do give suck unto the young ones which they bring forth.

Yet in case of want of health, or ability, or any other just impediment, the mother may in equity be forborne, and the child committed unto a nurse. And so we read that #emph[Rebekah] the daughter of #emph[Bethuel,] and afterward the wife of #emph[Isaac] had a nurse, Genes. 24. 59. Whose name was #emph[Deborah,] Gen. 35. 8. And #emph[Pharaohs] daughter in a case of necessity, committed #emph[Moses] to be nursed of an Hebrew woman, whom she took not to be his mother, but a stranger; and her fact was allowed by God, Exod. 2. 7. 9.

The second duty of the parent is, to provide for his child meat, drink, and clothing. Our Saviour Christ saith, that parents even by the light of nature, though they be evil, will not deny or withhold necessary food from their children: Mat. 7. 9. 10. #emph[What man is there among you, that if his son ask him bread, will give him a stone, or if he ask a fish, will give him a scorpion?] And #emph[Paul] saith, #emph[If there be any that provideth not for his own, and namely for them of his household, he denieth the faith, and is worse then an Infidel,] 1. Tim. 5. 8.

The third duty is, when God giveth ability & means, to lay up some thing for the future maintenance of the child. 2. Cor. 12. 14.—#emph[for the children ought not to lay up for the fathers, but the fathers for the children.] Prov. 19. 14. #emph[House and riches are the inheritance of the fathers.]

The fourth is, to observe both the inclination, and the natural gifts of body and mind that are in the child, and accordingly to bestow it in some honest calling & course of life. Prov. 20. 11. #emph[A child is known by his actions, whether his work be pure and right.] In the Ecclesiastical history,#footnote[Ruffin. Eccles. hist. lib. 1. c. 14.] written by #emph[Ruffinus,] it is recorded, that #emph[Alexander] Bishop of #emph[Alexandria,] saw a far off, in a place near to the sea, a company of children playing together, and in their play imitating himself in sundry Ministerial actions. And when he had a while viewed them, he perceived that they examined & baptised one another, according to the solemn order used in the Congregation: which thing, when he had made some of his Clergy acquainted withal, and taken order that the children should be sent for, and brought before him, he demanded of them, what sport they used, and in what manner they played one with another. The children at first, for fear, denied what they had done, yet upon further examination they confessed, that they had made #emph[Athanasius] (who afterward became Bishop of the place) their Bishop, and that he instructed and baptised sundry of their company. He further asked both #emph[Athanasius] himself, and those which were said to have been baptised, what questions he asked them, and what answers they gave; and perceiving by their speeches, that they had framed themselves, though in sporting manner, to the Church-proceedings in those actions; upon conference had with his Clergy, he determined, that those which had first been asked, and had given answer fully, according to the form used in that Church, and thereupon baptised, should not be rebaptised. And for #emph[Athanasius] and the other children, which had done the part of Ministers in their kind, he sent for their parents, and gave them great charge that they should be brought up in learning and religion, that so they might in time be fit for the public Ministry. The like course we read to have been taken by the Heathen, for judgement of the inclination and towardness of their children.#footnote[Nazianz. epist. ad Eudoxam.] The Athenians made a law, that before children were bestowed in any calling, they should be first brought into a public place, where Instruments belonging to all sorts of trades were laid; and look in what kind of Instrument any of them took most delight, the child was thought to be most fit for the trade, whereunto that Instrument belonged, and afterward applied to the same with good success.

Now the parents first and principal care must be for the Church; that those of their children which have the most pregnant wit, and be indued with the best gifts, be consecrated unto God, and brought up in the study of the Scriptures, to serve afterward in the Ministry of the Church. Thus #emph[Hannah] dedicated #emph[Samuel] her son unto God by vow, 1. Sam. 1. 11. #emph[And she vowed a vow, and said, O Lord of Hosts, if thou wilt—give unto thine handmaid a man-child, then I will give him unto the Lord all the days of his life.] And she did according to her vow, and the Lord blessed #emph[Samuel] her son, who in process of time became a great Prophet.

The next point of education of children, is to provide that they may live well, and lead a godly life. To this purpose parents must do three things.

First, they are to be careful, that the child, so soon as may be, after it is borne, be admitted into the true Church of God by baptism, and have a fit name given unto it.

#emph[Secondly, they are to endeavour to sow the seeds of godliness and religion in the heart of the child, so soon as it comes to the use of reason and understanding; and as it grows in years, so care must be had that it grow in knowledge and grace. To this purpose is the vow and promise made in baptism, which parents are bound to call upon the child to remember, when it comes to years. It was the godly care of] Timothies #emph[parents, 2. Tim.] 3. 14. But continue thou in the things which thou hast learned, knowing of whom thou hast learned them, #emph[vers.] 15. And that thou hast known the holy Scriptures of a child, which are able to make thee wise unto salvation, through the faith which is in Christ Jesus. #emph[This was the commandment of God to the parents of his people, Deut.] 6. 7. Thou shalt rehearse these words which I command thee continually to thy children, and shalt talk of them when thou tarriest in the house. #emph[And vers.] 20. When thy son shall ask thee in time to come, saying; What mean these Testimonies, and Ordinances, and Laws, which the Lord our God hath commanded you? Then thou shalt say unto thy son; We were Pharaohs bondmen in Egypt, #emph[&c. This was observed by the Israelites in the ages succeeding: Psal.] 44. 1. We have heard with our ears, O God: our fathers have told us the works that thou hast done in their days in old time.

Thirdly, the first instruction of children in learning & religion, must be so ordered, that they may take it with delight. For which purpose, they may be sometimes allowed in moderate manner to play, and solace themselves in recreations fitting for their years. And if they do amiss in either, they are to be restrained by the bridle of discipline. First by reproof in word, and when that will not help, by the rod of correction. Zach. 8. 5. #emph[The streets of the city shall be full of boys and girls, playing in the streets thereof.] Prov. 29. 15. #emph[The rod and correction give wisdom, but a child set at liberty makes his mother ashamed.] vers. 17. #emph[Correct thy son, and he will give thee rest, and give pleasures to thy soul.] Hebr. 12. 9. #emph[We have had the fathers of our bodies which correct us, and we gave them reverence.]

Yet in this point, two extremes are carefully to be avoided; That the parent be not either too severe, or too indulgent to the child. For severity #emph[Paul] gives his rule, Ephes. 6. 4. #emph[Parents provoke not your children to anger,] that is, by too much austerity in government. For lenity, we have old #emph[Eli] his example, 1. Sam. 2. 23. #emph[And he said unto them, Why do ye such things? For of all this people, I hear evil reports of you. Do no more my sons,] &c. So much for education.

#emph[The second general duty of parents, is the bestowing of their children; This bestowing is, when they knowing their children fit for marriage, not to have the gift of continency, do use their best endeavour to provide matches for them in time, or at least, do advise them thereunto by themselves or by their friends: 1. Cor.] 7. 36. If any man think it uncomely for his virgin to pass the flower of her age, and need so require—let them be married. #emph[vers.] 38. He that giveth her to marriage, doth well. #emph[Jerem.] 29. 6. Take ye wives—and take wives for your sons, and give your daughters to husbands, #emph[&c. Gen.] 28. 1. Isaac called Jacob and blessed him, and charged him and said unto him; Take not a wife of the daughters of Canaan: Arise, get thee to Padan Aram—and thence take thee a wife of the daughters of Laban thy mothers brother. #emph[Judg.] 14. 2. Samson came and told his father and his mother, and said, I have seen a woman in Timnah of the daughters of the Philistines; now therefore give me her to wife.

This duty is now adays carelessly neglected of parents; and the fruit thereof is dangerous. For hence it comes to pass, that their children oftentimes do either commit whoredom, or undertake wicked and ungodly marriages.

In the choice of a husband or wife, the parents ought to have a greater respect unto piety and wisdom, then unto beauty and riches, or any other outward blessings. Yet where they all concur, the party so qualified is the more thankfully to be entertained. Upon these grounds the Priest or Prince of Midian, gave his daughter #emph[Zipporah] to #emph[Moses,] and #emph[Moses] agreed to take her, Exod. 2. 19. #emph[A man of Egypt delivered us from the Philistines, and also drew us water enough, & watered the sheep—And Moses agreed to dwell with the man, who gave unto Moses Zipporah his daughter.] Josu. 15. 16. #emph[Then Caleb said, He that smiteth Kiriath-sepher, and taketh it, even to him will I give Achsah my daughter to wife.] Yea it is a sin to marry only for beauty, without consideration of the better things. Thus the old world sinned, when #emph[the sons of God saw the daughters of men that they were fair, and took them wives of all that they liked,] Gen. 6. 2. And #emph[Samson,] who only upon the sight of the woman in Timnah, of the daughters of the Philistines, without further inquiry, desired that she might be given him for his wife, Judg. 14. 2.

Again, it is meet that parents should deal moderately with their children in this case, and not undertake at any hand to force and compel them to marry this or that party. This was the just commendation of #emph[Rebekahs] parents, who though they were Idolaters, yet had that regard of equity, that they first called her and asked her consent, before they sent her away with #emph[Abrahams] servant, to be married to #emph[Isaac,] Gen. 24. 58. Now in case the parents fail in their duty in this regard, the son or daughter may lawfully declare the matter first to their kinsfolk, and afterward (if need be) to the Minister, or Magistrate, and sue for redress by their means and direction.
