== 15. Of the Master

Next unto parents and children, whereby the family is increased, is a second sort of couples, which are helps thereunto. And they are masters and servants.

The master is a member in the family, which hath power and beareth rule over the servant. And his duty stands principally in three things.

First, To make a good choice of his servants; which is then done, when he inquireth first after such as fear God, and be willing to serve him. #emph[Paul] makes the service and fear of God the main ground of true obedience in servants, Ephes. 6. 5. 6. 7. Colos. 3. 22. It was the rule of #emph[Davids] choice, Psal. 101. 6. #emph[He that walketh in the perfect way, he shall serve me. Abrahams] chief servant of his house, was a man that feared God, as appeareth, in that he made conscience of his oath, Gen. 24. 2. 3. And prayed also for success in the business whereabout he was sent. Gen. 24. 12. #emph[O Lord God of my master Abraham, I beseech thee send me good speed this day, and show mercy to my master Abraham. Cornelius] of #emph[Caesarea,] the Captain of the Italian band, had a soldier that daily attended on him, #emph[who feared God,] and servants also beside him, to whom he made known the heavenly vision which he saw, Act. 10. 7.

Secondly, To enjoin them labour, and not to require more of them, then their strength will bear. The master is to rule over the servant #emph[in justice.] And then is his commandment unjust, when it will not stand with the course of nature, with the ability of his servant, or with the word of God. Therefore he is to require labour at their hands proportionable to their strength, & yield them sometimes intercession & rest. Levit. 25. 46. #emph[Over your brethren the children of Israel, ye shall not rule over one another with cruelty.] 1. Pet. 3. 8. #emph[Be pitiful, be courteous, one bear with another.] And for the furtherance of business, it is convenient that the master be oftentimes present with the servants in their works. Prov. 27. 23. #emph[Be diligent to know the state of thy flock, and take heed to thy herds.] The good matron #emph[overseeth the ways of her household,] Prov. 31. 27.#footnote[Arist. Oeconom. 7.] A man of Libya being asked, what it was that might make a horse fat; he answered, #emph[The masters eye.]

Thirdly, To recompense the diligence and pains of his servant, and that three ways.

First, by giving him his due of meat and drink for the present. The good matron #emph[giveth the portion to her household, and the ordinary to her maids,] Prov. 31. 15.

#emph[Secondly, by paying him his hire in the end of his service:] The labourer is worthy of his wages. #emph[Luk.] 10. 7. Well done, good servant and faithful; thou hast been faithful in little, I will make thee ruler over much; enter into thy masters joy. #emph[Mat.] 25. 21.

#emph[Here three caveats are to be observed. I. That the wages be proportionable to the work. II. That it be paid in due time, without deferring. So the master of the vine-yard,] when even was come, #emph[called his servants together, to] give them their hire, #emph[Mat. 20. 8. III. That the servant be not defrauded of any part of his due. For this is a crying sin; Deut. 24.] 15. Thou shalt give him his hire for his day, neither shall the Sun go down upon it—lest he cry against thee unto the Lord, and it be sin unto thee. #emph[Jam.] 5. 4. Behold, the hire of the labourers which have reaped your fields, which is kept back by fraud, crieth, and the cries of them which have reaped, are entered into the ears of the Lord of hosts.

Thirdly, if the servant in time of his service be sick, the masters care must be by all means possible to procure his recovery. Equity must be the rule in these cases; and masters are to #emph[do to their servants that which is just and equal.] Col. 4. 1. Now the servant haply falls sick by and in his service, and his health yields not only profit to his master, but encouragement also to himself. The good Centurion in case of his servants sickness, took the best course to have him restored, Matth. 8. 6.
