== 4. Of the Contract

Marriage hath two distinct parts, the first is the beginning; the second, the accomplishment or consummation thereof.

The Beginning, is the contract or Espousals; the End or accomplishment, is the solemn Manifestation of the contract, by that which properly we call marriage. Deut. 20. 7. #emph[What man is there that hath betrothed a wife, and hath not taken her? Let him go and return again unto his house, lest he die in battle, and another man take her.] Matth. 1. 18. #emph[When his mother] Mary #emph[was betrothed to] Joseph, #emph[before they came together, She was found with child of the Holy Ghost.]

Between the contract and marriage, there ought to be some certain space or distance of time. The reasons whereof may be these:

First, a business of so great importance as this is, would not be rashly or unadvisedly attempted, but should rather be done by degrees in process of time, according to that saying, not so ancient as true.#footnote[Diu deliberandum quod semel statuendum.] #emph[Actions of weight, before resolution, require mature deliberation,] Secondly, That during such a space, inquiry may be made, whether there be any just cause, which may hinder the consummation of marriage: considering that before the parties come and converse together, what is amiss may be remedied and amended, which to do afterward will be too late. Thirdly, In these cases, persons espoused must have regard of honesty, as well as of necessity; not presently upon the contract, seeking to satisfy their own fleshly desires, after the manner of bruit beasts, but proceeding therein upon mature deliberation.

The contract is a mention or mutual promise of future marriage, before fit and competent Judges and Witnesses.

The best manner of giving this promise, is, to make it#footnote[In verbis de praesenti.] #emph[in words touching the present time,] and simply without any exception or condition expressed or conceived. For by this means it comes to pass, that the bond is made the surer, and the ground or foundation of future marriage the better laid. And hence alone it is, that the persons betrothed in Scripture are termed man and wife. #emph[Jacob] speaking of #emph[Rachel,] who was only betrothed unto him, saith to #emph[Laban, Give me my wife,] Genes. 29. 21. Deut. 22. 23. #emph[If a maid be betrothed to a husband, and a man find her in the town, and lie with her, then shall ye bring them both out unto the gates of the city, and shall stone them with stones to death, the maid, because she cried not being in the city, and the man, because he hath humbled his neighbours wife.] Matth. 1. 20. #emph[Joseph fear not to take Mary thy wife.]

Now if the promise be uttered in words,#footnote[In futurum.] #emph[for time to come,] it doth not precisely bind the parties to performance. For example, if one of them saith to the other; #emph[N. I will take thee,] &c. And not, #emph[N. I do take thee,] &c. By this form of speech the match is #emph[not made, but only promised] to be made afterward. But if on the other side it be said, #emph[N. I do take thee,] and not, #emph[I will take thee;] by these terms, the marriage at that very instant is begun,#footnote[Non de facto, de iure.] not in regard of fact, yet in regard of right and interest, which the parties have each in another in deed and in truth. And this is the common opinion of the learned. Yet notwithstanding, if the parties contracting shall say each to other, #emph[I will take thee to,] &c. With intention to bind themselves at the present; the bond is in conscience precisely made before God, and so the contract is indeed made#footnote[De praesenti.] #emph[for the present] time before God. True it is, that he which standeth to his promise made, as much as in him lieth, doth well: yet if the promise hath or conceiveth some just cause, why he should afterward change his purpose, the contract expressed in terms for time to come, though it were formerly made, & confirmed by oath, must notwithstanding give place to the contract made for time present.

Those espousals, which are made upon condition, which is honest, possible, and belonging to marriage, do cease or depend: so far forth as the condition annexed ceaseth or dependeth. For example; If the one party promiseth to marry the other upon condition, that his or her kinsman will yield consent to the match; or upon condition of a dowry that she shall bring unto him, suitable to her education, and the family whereof she commeth: these conditions being kept or not kept, the promise doth likewise stand, or not stand.

But those conditions which are necessarily understood, or which may certainly be kept and come to pass, do neither hinder nor suspend marriage. As this: #emph[I promise thee marriage, if I live;] or, #emph[I promise to marry thee, if the Sun rise to morrow.]

Again, conditions that are either impossible or dishonest, are not to be accounted as promises annexed#footnote[Jn sauorem Matrimony.] in way of marriage. Of which sort are these, #emph[I will be thy wife, if thou wilt take unto thee wings and fly,] or, #emph[If thou wilt bring an untimely birth.]

Furthermore, if the parties betrothed, do lie together before the condition (though honest & appertaining to marriage) be performed; then the contract for time to come is, without further controversy, sure and certain. For where there hath been a carnal use of each others body, it is always presupposed, that a mutual consent, as touching marriage, hath gone before.
