== 12. Of the Wife

The wife is the other married person, who being subject to her husband, yieldeth obedience unto him.

Touching the subjection of the wife, the word of God mentioneth it in sundry places. Rom. 7. 2. #emph[The woman which is in subjection to the man, is bound by the law to the man, while he liveth.] Ephes. 5. 24. #emph[As the Church is in subjection to Christ, even so let the wives be to their husbands in every thing.] Colos. 3. 18. #emph[Wives submit your selves unto your husbands, as it is comely in the Lord.] 1. Tim. 2. 12. #emph[I permit not a woman—to usurp authority over the man.] And it was a law established by God immediately after the fall, Gen. 3. 16. #emph[Unto the woman he said, I will greatly increase,] &c. #emph[and thy desire shall be subject to thine husband, and he shall rule over thee.] Indeed the daughter, according to the Civil law, even when she is married is#footnote[In potestate patris.] #emph[in the power of her father,] and not of her husband. But this is directly against the law of #emph[Moses,] and crosseth the law of nature, Levit. 22. 12. 13. Numb. 30. 13.

Now the duties of the wife, are principally two.

The first is, to submit her self to her husband; and to acknowledge and reverence him as her head in all things. Gen. 20. 16. #emph[Likewise] Abimelech #emph[said unto] Sarah; #emph[Behold thy brother,] that is, thy husband, whom thou callest thy brother, #emph[is the veil of thine eyes to all that are with thee.] As if he should say, #emph[Thy husband is thy head, and hath power over thee, and thou oughtest to reverence him.] For of ancient times, the wife was covered with a veil in the presence of her husband, in token of subjection to him. Thus #emph[Rebekah] at the sight of #emph[Isaac] took a veil, #emph[and covered her head therewith,] Gen. 24. 65. 1. Cor. 11. 3. #emph[The man is the womans head.] Ephes. 5. 22. #emph[Wives submit your selves unto your husbands, as unto the Lord; for the husband is the wives head, even as Christ is the head of his Church.] The reason hereof is good. For the wife enjoyeth the privileges of her husband, and is graced by his honor and estimation amongst men. His Nobility maketh her noble, though otherwise she is base and mean; as contrariwise, his baseness and low degree, causeth her, though she be by birth noble and honorable, to be by estate base and mean.

The second duty is, to be obedient unto her husband in all things; that is, wholly to depend upon him, both in judgement and will. For look as the Church yields obedience to Christ her head, and yields her self to be commanded, governed, and directed by him, so ought the woman to the man. So #emph[Sarah] is said #emph[to obey Abraham,] and to give him the terms of obedience, #emph[She called him Lord, or Sir,] 1. Pet. 3. 6. Hence it followeth, that the woman is not to take liberty of wandering, and straying abroad from her own house, without the mans knowledge & consent. 2. King. 4. 22. #emph[Then she called to her husband and said, Send with me, I pray thee, one of the young men, and one of the asses; for I will haste to the man of God, and come again.] Again, that she is to follow her husband, when he flitteth or departeth from place to place, unless he forsake either her or Christ. To this purpose #emph[Paul] saith he #emph[had power to lead about a wife, being a sister, as well as the rest of the Apostles,] 1. Cor. 9. 5. Thus #emph[Sarah] went with #emph[Abraham] into Egypt, Gen. 12. 11. And out of Egypt, Gen. 13. 1. And to #emph[Gerar to sojourn there,] Gen. 20. 1. 2. 3. Thus the wives of #emph[Jacob] departed with him, from their father #emph[Laban,] Gen. 31. 17.

#emph[Contrary to these duties, are the sins of wives; To be proud, to be unwilling to bear the authority of their husbands; to chide and brawl with bitterness; to forsake their houses, &c. Prov.] 27. 15. A continual dropping in the day of rain, and a contentious woman are alike. #emph[vers.] 16. He that hideth her, hideth the wind, & she is as the oil in his right hand, that uttereth it self. #emph[Exod.] 4. 26. Then Zipporah said, O bloody husband; because of the Circumcision. #emph[It was the fault of the Levites concubine, Judg.] 19. 2. Who played the whore, and went away from him unto her fathers house to Bethlehem Judah, and there continued the space of four months. #emph[It was the sin of] Queen Vashi, who refused to come at the Kings word, which he had given in charge to the Eunuchs: therefore the King was very angry, and his wrath kindled in him, #emph[Esther 1. 12. Lastly, to be a cause of grief to their kindred. Thus the proud wives of] Esau, #emph[the daughters of the Hittites, were a grief of mind to] Isaac #emph[and] Rebekah, #emph[Gen. 26. 35. &] 27. 46.
