== 11. Of the Husband

Married folks are either husband or wife.

The husband is he which hath authority over the wife; hereupon in Scripture he is called the #emph[guide of her youth,] Prov. 2. 17. And they twain being but one flesh, he is also the head over his #emph[wife.]

The duties of the husband towards the wife, are these:

#emph[I. To love her as himself: Eph.] 5. 33. Let every one love his wife even as himself. #emph[Gen.] 24. 67. Afterward #emph[Isaac] brought her unto the tent of #emph[Sarah] his mother; and he took #emph[Rebekah] and she was his wife, and he loved her: so #emph[Isaac] left mourning for his mother. #emph[Note, how the love of the husband to the wife, mitigates sorrow for the death of the mother.]

#emph[He is to show this love in two things: First in protecting her from danger, Gen.] 20. 16. And unto #emph[Sarah] he said, behold I have given 1000. shekels of silver unto thy brother: behold he is the covering of thine eyes amongst all that are with thee. Let it be known amongst all, & be thou instructed. 1. #emph[Sam. 30. 5. Davids] two wives were taken prisoners also, #emph[Ahinoam] the Jezreelitess, and #emph[Abigail] the wife of #emph[Nabal] the Carmelite: #emph[v.] 8. Then #emph[David] asked counsel of the Lord saying; Shall I follow after this company? Shall I overtake them? And he answered him, Follow, for thou shalt surely overtake them, and recover all. #emph[Secondly, in regarding her estate as his own, and providing maintenance for her, both for his life time, and as much as he may, for time to come after his death. Ephes.] 5. 28. So ought men to love their wives, as their own bodies: he that loveth his wife loveth himself; #emph[vers.] 29. For no man yet hated his own flesh, but nourisheth it, #emph[&c. Exod.] 21. 10. If he take him another wife, he shall not diminish her food, her raiment, and recompense of her virginity. #emph[Ruth.] 3. 9. Unto whom he said, who art thou? Which said; I am #emph[Ruth] thine handmaid, spread therefore the wing of thy garment over thine handmaid; for thou art the kinsman.

II. To honor his wife: 1. Pet. 3. 7. #emph[Giving honor to the woman.]

This honor stands in three things: First, in making account of her, as his companion, or yoke-fellow. For this cause, the woman, when she was created, was not taken out of the mans head, because she was not made to rule over him; nor out of his feet, because God did not make her subject to him as a servant; but out of his side, to the end that man should take her as his mate. Secondly, in a wise & patient bearing or covering of her infirmities, as anger, waywardness and such like, in respect of the weakness of her sex, 1. Pet. 3. 7. #emph[Giving honor to the woman, as unto the weaker vessel, seeing ye are heirs together of the grace of life, that your prayers be not hindered.] Thirdly, by suffering himself sometimes to be admonished or advised by her. It was Gods commandment to #emph[Abraham] concerning #emph[Sarah] his wife; #emph[Let it not be grievous in thy sight for the child, and for thy bond-woman: in all that] Sarah #emph[shall say unto thee, hear her voice; For in] Isaac #emph[shall thy seed be called,] Gen. 21. 12. Thus #emph[Elkanah] was willing to subscribe unto his wife #emph[Hannah's] advice, for her tarrying at home till the child was weaned, 1. Sam. 1. 23. #emph[And] Elkanah #emph[her husband said unto her, do what seemeth thee best: tarry until thou hast weaned him: only the Lord accomplish his word.] Hereupon the Heathen Philosopher said,#footnote[Arist. Ethic. lib. 8.] #emph[That the master of the family exerciseth (after a sort) a power Tyrannical over his servants, a power Regal over his children; because Kings are fathers of their common-weals: but in respect of his wife, he exerciseth a power Aristocratic, not after his own will, but agreeable to the honor and dignity of the married estate;] and consequently, that he ought not in modesty to challenge the privilege of prescribing and advertising his wife in all matters domestic, but in some to leave her, to her own will and judgement.

Here question is moved, whether the husband may correct the wife?

#emph[Answ.] Though the husband be the wives head, yet it seemeth he hath no power nor liberty granted him in this regard. For we read not in the Scriptures, any precept or example to warrant such practise of his authority. He may reprove & admonish her in word only, if he seeth her in fault. For, thus we read, that #emph[Jacob] censured his wife, being impatient, even in anger, Gen. 30. 2. #emph[Am I in Gods stead, which hath withholden from thee, the fruit of the womb?] And #emph[Job] reproved his wife, Job 2. 10. #emph[Thou speakest like a foolish woman. What? Shall we receive good at the hand of God, and not receive evil?] But he may not chastise her either with stripes, or strokes. The reason is plain; wives are their husbands mates; and they two be one flesh. And no man will hate, much less beat his own flesh, but nourisheth and cherisheth it, Ephes. 5. 29. Again, it is the commandment of God, that man should not #emph[trespass against the wife of his youth,] Malac. 2. 15. #emph[Chrysostom] saith,#footnote[In 1. Cor. 11. Homil. 26.] #emph[It is the greatest reproach for any man, that can be, to beat his wife. Plutarch] in the life of #emph[Cato] the Censor, affirmeth, that #emph[he which smiteth his wife,] doth all one, #emph[as if he should lay violent hands upon the sacred images of the gods,] which was counted an high degree of offence among the Heathen.

It is alleged, husbands are commanded so to love their wives, as Christ doth his Church; now Christ chastiseth his Church, with strokes; & therefore so may the husband his wife. #emph[Answ.] As Christ doth entirely love his Church, so he may also chastise the same, because he is not only the husband, but also absolute Lord and King of his Church: so is not the husband absolute over the wife.

But his authority over the wife, is after a sort civil, as is the authority of the Magistrate over his people. #emph[Ans.] It is not so. For the Magistrate hath in his hand the power of the sword, by which power he inflicteth punishment in case of offence. But the husband can challenge to himself no such power:#footnote[L. Consensu. C. de diuortijs.] yea it is flatly forbidden in the Civil law, that he should scourge or strike his wife.

Nevertheless, if she grow to extremities, and be desperately perverse, so as there be no hope of amendment; then the Magistrate may be informed, who to prevent scandals, and to provide for public peace, both ought and may assign unto her necessary correction, and punishment according to her desert. Now the husband that hath a wife so stubborn and peevish, must bear it, if it may be borne, as the portion of his cross laid upon him by God. And in this case, if he be impatient, he may in some sort be pardoned and pitied, but he is not wholly to be excused.
