== 8. Of Marriage

Marriage is that, whereby the conjunction formerly begun in the contract, is solemnly manifested, and brought to perfection. Marriage is consummate by three sorts of actions; one of the parents of the bride and Bridegroom, the other of the Minister in public, the third of the persons coupled together.

The action of the parents is upon the marriage-day, to bring the bride, and deliver her to the bride-groom, that they two may become actually man and wife, and perform each to other all matrimonial duties.

And where the marriage is complete, in any other manner, so as the parents upon sound judgement and deliberation, shall deny their full and free consent, either in express words, or by connivence and silence, and that upon just and lawful cause; there, though in the civil courts of men, it may stand, and the children borne therein be legitimate before men, yet the truth is, before God it is of no force, but a mere nullity.

And because this doctrine, touching consent of parents in these Cases, is of great use, and availeth much to the supporting and maintaining of families; I will first open the truth thereof, and then prove it by reasons.

Under the name of parents are comprehended; First, the Father and mother. Secondly, all Tutors and Guardians, who have the proper & sole charge of wards, or others under years of discretion. Thirdly, all such as are kindred of blood, who are in stead of parents to children, as the uncle by the fathers side, the uncle by the mothers side, and such like.

Now touching the consent of parents, that is, of father and mother, I hold it requisite of necessity to marriage: For the authority of parents must not be resisted, or violated. As for Tutors, and such as have the place of parents, their consent is not required of necessity, but#footnote[De honestate.] of honesty at least, because the power and authority of the parent, though it be not taken away, yet it is lessened, when it is either transferred to another person, or in part resteth in the child already bestowed.

Secondly, by parents consent, I understand that which they give, not rashly, unadvisedly, or foolishly, but out of good & wise consideration, and upon true and sound judgement, of the business in hand: For otherwise, as much as in them lieth, they make the marriage void and of none effect. And they are then thought to carry a right judgement of the thing, when they be able to yield a just cause of yielding, or denying their consent. For example; if a father denies to bestow his daughter #emph[Julia] upon #emph[Sempronius,] because he knows him to be an Arrian, a Pelagian, or of any other sort of Heretics; he withholdeth his consent upon a good ground, & he doth that which he doth, of judgement.

Yet further I add, that where the parents do dissent, and can yield no probable cause thereof; the marriage consummate without their consent, ought to be confirmed and ratified by the authority of the Magistrate, who is #emph[Pater patriae.] And this seems to be the most equal course, both for the avoiding of greater scandals, & for the preventing of wrong, that may otherwise be done in some particular case, as to a woman that is deflowered and rejected.

Thirdly, consent of parents is either expressed, or implied; Expressed, when it is given by words; Implied, when it is yielded by silence. For it standeth with most equity and indifferency, to think that those parents do give consent, who do not by word expressly deny the same.

Fourthly, children are either subject to the authority of their parents in the family; or at their own liberty, & out of their parents subjection. Those that are at liberty, are tied necessarily to subjection in respect of marriage; but the other being still of the family, and under jurisdiction, are bound to be ordered, by their parents in the bestowing of themselves.

This is briefly the meaning of the question in hand. Now, for proof of this point, I will propound three sorts of arguments, whereof some are drawn from the law of God, some from the light of nature, and some from the judgement of the ancient Church.

For the first sort. According to the law of God, marriage is not only a civil and politic, but also a divine and spiritual conjunction, the author and ordainer whereof, upon special cause, was God himself: This our Saviour Christ witnesseth, when he saith, #emph[Those whom God hath joined together, let no man separate,] Matth. 19. 6. That therefore marriages may be soundly ratified and confirmed, the authority and power of God himself is necessarily to be interposed.

If it be asked, How God that is in heaven, should bring and join together man and wife upon the earth?

I answer, that he doth it not immediately by himself, as he brought #emph[Eve] unto #emph[Adam,] but in & by some solemn and lawful means. And this mean, is that great and ancient power and prerogative of parents. And the law of God hath given them this power, not in civil contracts and compositions alone, but even in the beginning and accomplishing of marriages. Deut. 7. 3. #emph[Thou shalt not give thy daughter unto his son, nor take his daughter unto thy son.] Jerem. 29. 6. #emph[Take wives for your sons, and give your daughters unto husbands, that they may bear sons and daughters.] 1. Cor. 7. 36. #emph[But if any man think that it is uncomely for his virgin, if she pass the flower of her age, and need so require, let him do what he will, he sinneth not, let them be married.]

Hence it was, that #emph[Abraham] by right of this authority, gave order what wife his servant should provide for his son; #emph[Thou shalt not take a wife to my son of the daughters of the Canaanites; But thou shalt go unto my country, and to my kindred, and take a wife unto my son Isaac,] Gen. 24. 3. 4. #emph[Samson,] though he was inflamed with the love of the woman in #emph[Timnath,] whom he saw to be beautiful in his eyes, yet he durst not take her to his wife, till she was given him of his parents, Judg. 14. It was an express law of God, that #emph[if a man enticed a maid that was not betrothed, and lay with her, he should endow her, and take her to his wife:] But how? Mark in what manner the holy Ghost proceedeth, #emph[If her father refuse to give her to him, he shall pay money according to the dowry of virgins,] Exod. 22. 16. 17. Deut. 22. 28. 29. In which text, #emph[Moses] plainly teacheth, that the consent of the two parties is not sufficient, no not though they have had society together, unless they have the free consent of their parents also. In like manner it was ordained by God, Numb. 30. 4. 5. 6. #emph[That if a woman vowed a vow unto the Lord, being in her fathers house, & her father hearing it, holdeth his peace concerning her,] that is, approves her vow by winking at it, #emph[her vow shall stand. But if her father disallow her,] that is, giveth no approbation or consent unto the vow made, #emph[it shall be of no value, and the Lord will forgive her, because her father consented not.] Now, if the vow of children made unto God, and pertaining to his worship, cannot be ratified without the parents approbation; of how much less force shall any private contract or marriage be, without their allowance?

The second argument is taken from the light of nature, and it is gathered by proportion on this manner: A son privily alienateth and selleth away his fathers lands, either in whole or in part. The question is, whether this alienation be good in law, yea or no? Answer is, No. And why? Because the land did not belong to the son, but was part of his fathers substance. In like manner, a son alienates himself, and is betrothed to a woman, to marry her without his parents knowledge: Is this act of the son warrantable and sound? By no means; for the son in respect of his body, is part of the fathers goods, and may not be alienated from him without consent. A notable reason hereof we find in Job 1. For when God had given Satan power to destroy and spoil all #emph[Jobs] goods, and whatsoever he had, the devil doth not only touch the wealth of #emph[Job,] but his children also, as a part of his substance. In this respect the Jews were permitted by God to sell their children. Exodus 21. 7.

Again, for the accomplishment of marriage, there must needs be a mutual donation, between the spouse and the espoused. And what is that which is mutually given? Surely their persons, or rather their bodies each to other, for so #emph[Paul] saith, 1. Cor. 7. 2. #emph[Let every man have his wife, and let every woman have her own husband.] But by whom is this donation to be made? By sons and daughters that are in the family, under the jurisdiction of their parents? It may not be; For nature her self taketh it for granted, that he which is not at his own liberty, cannot yield to the giving of himself. The donation therefore remains in the right of the parent, in as much as the will & consent of the child, ought to depend upon his will and consent, to whom God hath given power and authority in this behalf.

In the third place, let the judgement of the ancient Church be observed. #emph[Ambrose,] in his first book of the Patriarch #emph[Abraham,] chap. 9. requires this consent in marriages, which he saith is so equal and agreeable to nature, that even the Poets acknowledged the same. For which purpose he reciteth two verses out of the #emph[Grecian] Poet #emph[Euripides,] in his Tragedy called #emph[Andromacha,] wherein when #emph[Orestes] desired to marry #emph[Hermion,] she frames him this answer, That the matter of her marriage wholly depended upon the pleasure and authority of her father, & was not in her own power or liberty. #emph[Innocentius,] who was both a Pope and Martyr, in his decretal epistles, so strictly requireth consent of parents,#footnote[Sub Innocent. 3. canon. 51.] #emph[as where it is wanting, he concludes the marriage to be void.] In the Council of Lateran, it was decreed that Clandestine contracts & #emph[secret marriages, made and undertaken between party and party, should be holden as unlawful as marriages in those degrees of consanguinity and affinity, which are forbidden by God. Tertullian] saith,#footnote[Tertul. lib. ad vxorem, 2. ad finem.] That #emph[in this world the son cannot] #footnote[Ritè & Iure. Basil. epist. 1. ad Amphiloch. Canon, 42.] #emph[rightly and lawfully marry without the allowance of his father. Basil] in an Epistle to #emph[Amphilochius] Bishop of #emph[Iconium,] affirmeth; #emph[That marriages which are made without them which have power over the parties, are fornications, and therefore that they which are joined together in marriage, while their parents] or #emph[masters live, are in no sort free from imputation of sin, until they have approbation from them, for then marriage is ratified & confirmed, when they have yielded allowance thereunto.]

The second Action touching the consummation of marriage, is the action of the Minister. And that is the blessing or sanctification thereof, which is a solemn work, whereby the Minister pronouncing the parties contracted to be man and wife before the whole congregation, commendeth them and their estate unto God by solemn prayer.

This solemn sanctification is grounded upon the practise of God himself, who having given #emph[Eve] to #emph[Adam,] blessed them, saying, #emph[Increase and multiply,] Gen. 2. 22. and 1. 27. For that which God then gave, the Minister standing in his room, now prayeth may be given to the man and wife. Yea it is agreeable to the general rule of the Apostle, #emph[Let all things be done decently and in order,] 1. Cor. 14. 40.

Now that this action is to be approved and used in the Church, appears by these reasons.

#set enum(numbering: "I.")

+ Marriage as it is a public action, so it is after a sort a spiritual and divine ordinance, whereby it differeth from the contract: For the contract being merely civil, as it standeth by consent of men, so by the same consent, it may be broken and dissolved, but with marriage it is otherwise.
+ Marriage is the Seminary of the Church and common-wealth.
+ It was the practise of the Primitive Church. #emph[Tertullian] speaking of the marriage of Christians with Christians,#footnote[Lib. 2. ad vxorem.] acknowledgeth himself not to be able sufficiently to declare the happiness #emph[of that conjunction which is made by the Church, consecrated by prayers &] #footnote[Oblationem sic exponit Beatus Rhenanus. Niceph. lib. 14. cap. 55. Ambros. epistolar. lib. 9. epist. 70. ad Vigilium.] #emph[solemn service, witnessed by the Angels, and ratified by God himself. Nicephorus] reporteth of one #emph[Synesius,] who avouched that #emph[God & the laws, and the holy hand of Theophilus had given him a wife. Ambrose] saith, #emph[That marriage ought to be sanctified, with the veil wherewith the Priest was wont to cover the bride and the bride-groom in the public congregation, and with his blessing.]

The third and last action belonging to the accomplishment of this estate, is, that of the parties themselves, whereby the bride is in decent and modest manner, brought unto the house and home of the bride-groom. It is the law of this estate published by God himself in Paradise, that the man, even in respect of habitation, #emph[should leave father and mother and cleave to his wife,] Gen. 2. 24.

Here question is moved, whether marriage is to be solemnized with mirth and feasting. #emph[Answ.] I. It is lawful and warrantable to use feasting and mirth at marriages, because these be things indifferent, and we have examples thereof in the Scriptures. #emph[Laban] made a feast at the wedding of #emph[Jacob] and #emph[Rachel,] and invited all the men of the place to it, Gen. 29. 22. Christ himself did approve the resort of people to the marriage at Cana in Galilee, both by his presence, and by that honorable gift of six water-pots of the best wine, Joh. 2. 2. 7. 8. II. It is not only lawful, but convenient and fit to be done, if there be ability; according to the commendable custom of the place & country wherein men do dwell; so as in the use thereof, these cautions be observed. First, that in mirth and merry-making, there be care had that nothing be done which is dishonest, profane, or of ill report. Philip. 4. 8. #emph[Whatsoever things are honest, pure, of good report, think on these things.] Secondly, That joy in them be mixed and moderated with the fear of God, without which #emph[Laughter] and rejoicing is mere madness, Eccles. 2. 2. Thirdly, That it be performed in a moderate and sober use of the creatures, without riot & excess. Thus we read that at the great feast of #emph[Ahasuerus,] it was appointed by the King himself, #emph[that they should drink orderly,] & none might compel another to drink more then he thought convenient, Esther 1. 8. And where weddings are kept contrary to these directions, they are not feasts celebrated unto God, but unto the devil; which also may be said of all other festival meetings.

And so much touching the point of marriage, in which this is to be remembered for a conclusion, That where there is generally a nullity in the contract, or a separation following upon it, there is also a nullity in regard of the consummation of marriage.
