== 17. Of the Master of the Family or Goodman of the House

Thus much touching the divers and several combinations or couples belonging to the state Economical. From which do arise two persons of a mixed or compounded nature and condition, commonly called the Goodman, & the goodwife of the house.

The #emph[good man or master of the family,] is a person, in whom resteth the private and proper government of the whole household, and he comes not unto it by election, as it falleth out in other states, but by the ordinance of God, settled even in the order of nature. The husband indeed naturally bears rule over the wife; parents over their children, masters over their servants: but that person who by the providence of God, hath the place of an husband, a father, a master in his house, the same also by the light of nature, hath the principality & sovereignty therein, and he is #emph[Paterfamilias,] the father and chief head of the family: to him therefore the true right and power over all matters domestical, of right appertaineth. The duties of the master of the family, are specially five.

I. To bear the chief stroke, and to be the principal agent, director and furtherer of the worship of God within his family. Jos. 24. 15. #emph[I and my household will serve the Lord.] And this he doth partly by praying for & with his household, and partly by instructing them in the holy Scriptures, and in the grounds of religion, that they may grow in knowledge and reap benefit by the public Ministry. Thus God commanded the men of Israel to walk in their families. Deut. 6. 7. #emph[Thou shalt rehearse them continually unto thy children, and shalt talk of them, when thou tariest in thine house,—& when thou liest down, & when thou risest up.] Again, vers. 20. #emph[When thy son shall ask thee,—what mean these testimonies, and ordinances & laws, which the Lord our God commanded you? Then thou shalt say unto thy son, We were Pharaohs bondmen in Egypt, but the Lord brought us out of Egypt, with a mighty hand.] This testimony God gave of #emph[Abraham] before the law was given, Gen. 18. 19. #emph[For I know Abraham that he will command his sons, and his household after him, that they keep the way of the Lord.] And this household of #emph[Abraham] was very large, for the holy Ghost says long before, that he had #emph[three hundred and eighteen,] #footnote[\[Ethchanicau\] suos initiatos.] #emph[that were borne and brought up in his house,] Gen. 14. 14. It was in likelihood the course of #emph[Solomon] which he had learned of his father #emph[David,] and given for a rule to all masters of families. Prov. 4. 1. #emph[Hear O children the instruction of a father, and give ear to learn understanding—For I was my fathers son, dear and tender in the sight of my mother, when he taught me and said unto me, Let thine heart hold fast my words.] The company of the Disciples were the household of Christ, and he himself did administer all parts of the service of God with them and among them. Luk. 22. 15. To this purpose#footnote[In Ioan. tract. 51. in fine.] #emph[Augustine] saith, #emph[That the master of the family, doth after a sort, and in his measure perform the duty of a Churchman, or Bishop within his house.]

#emph[II. To bring his family to the Church or Congregation on the Sabbath day, to look that they do religiously there behave themselves, & after the public exercises ended, & the Congregation is dismissed, to take account of that which they have heard, that they may profit in knowledge and obedience. Act.] 10. 24. The day after, they entered into Caesarea; Now Cornelius waited for them, & had called together his kinsmen & special friends. #emph[vers.] 33. Now therefore #emph[(saith] Cornelius #emph[to] Peter) are we all here present before God, to hear all things that are commanded thee of God. #emph[Job] 1. 5. And when the days of their banqueting were gone about, Job sent and sanctified them, & rose up early in the morning, & offered burnt offerings, #emph[&c. 2. King. 4.] 23. And he said, wherefore wilt thou go to him to day? It is neither new moon nor Sabbath. #emph[For this very cause the fourth Commandment is given first of all & principally to the master of the family, that he might see the Sabbath kept, and be a principal doer in all parts of Gods worship therein. Exod.] 20. 10. In it thou shalt not do any work, thou nor thy son, nor thy daughter, thy man-servant, nor thy maid, nor thy cattle, nor thy stranger that is within thy gates.

Neither is this his care tied only to the Sabbath, but upon other days besides it, he ought to cause them of his household, as much as in him lieth, to repair to places, where the word of God is preached. Commendable was the practise of #emph[Mary] the sister of #emph[Martha,] in this case, who when Christ came to her house is said, #emph[to sit at his feet and attend unto his preaching,] Luk. 10. 39.

III. To provide for his family meat, drink and clothing, and that they may live a quiet & peaceable life, 1. #emph[Tim. 5. 8. Pro.] 27. 26. The lambs are for thy clothing, and the goats for the price of thy field. #emph[v.] 27. And let the milk of thy goats be sufficient for thy food, for the food of thy family, and for the sustenance of thy maids. 1. #emph[Cor.] 9. 9. Thou shalt not muzzle the mouth of the ox, that treadeth out the corn: doth God care for oxen? Either saith he it not altogether for our sakes? #emph[Matth.] 13. 52. Every scribe which is taught unto the kingdom of heaven is like unto an householder, that brings forth out of his treasury, things both new and old.

IV. To keep order, and to exercise discipline in his house, and that in this manner:

#emph[In case of offence, when a capital crime is committed, which incureth public censure; he is not to punish it himself, but to bring the offender to the civil Magistrate, to inform of his fault, that he may have his desert: It was a course established by the Judicial law, which God gave unto] Moses #emph[for his direction in causes criminal among the Israelites: Deut.] 21. 18. 19. 20. If any man hath a son that is stubborn, & disobedient, which will not hearken unto the voice of his father, nor the voice of his mother, and they have chastened him; then shall his father and his mother take him, and bring him out, unto the Elders of his city, and unto the gate of the place where he dwelleth, and shall say unto the Elders of his city; This our son is stubborn, and disobedient, and he will not obey our admonition: he is a rioter, and a drunkard. #emph[Again, Deut.] 13. 6. If thy brother the son of thy mother, or thine own son, or thy daughter, or the wife that lieth in thy bosom, or thy friend which is as thine own soul, entice thee secretly saying, Let us go and serve other gods (which thou hast not known, thou, I say, nor thy fathers) thou shalt not consent unto him, nor hear, neither shall thine eye pity, nor show mercy, nor keep him secret. #emph[Zach.] 13. 3. And when any shall yet prophesy, his father and his mother that begat him shall say unto him, Thou shalt not live: for thou speakest lies in the name of the Lord: and his father, and his mother that begat him, shall thrust him thorough when he prophesieth.

If the fault be of an inferior nature, and lesser in comparison; the master of the family ought to proceed by private censure upon the delinquent party, sometimes by admonition, otherwhiles by correction, and chastisement, according to the quality of the offence, & the condition & state of the person. Levit. 19. 17. #emph[Thou shalt plainly rebuke thy neighbour, and not suffer him to sin.] Mat. 18. 15. #emph[If thy brother sin against thee, go and tell him his fault between him and thee alone: If he hear thee not, take yet with thee one or two.] Prov. 29. 17. #emph[Correct thy son, and he will give thee rest, and will give pleasures to thy soul.]

When admonitions and corrections will not prevail, the party must be brought before the Ministers, and Governors of the Church, that they may censure him. Matth. 18. 17. #emph[If he will not hear them, tell it unto the Church.] And the Apostle #emph[James] giveth order that the Ministers of the Church should come to those that are sick, and pray for them, James 5. 14. Which if they do in case of infirmity; then they are also to be sought unto, in case of error and offence committed, for redress.

#emph[But when none of all these means will do good; if the party be a servant, his master may, and ought to remove him. Psal.] 101. 7. There shall no deceitful person dwell within mine house; he that telleth lies shall not remain in my sight. #emph[Joh. 8.] 35. The servant abideth not in the house for ever.

#emph[V. To give entertainment to those that are strangers, & not of the family, if they be Christians, and Believers; but specially to the Ministers of the Word. Rom.] 12. 13. Giving your selves to hospitality. #emph[Hebr.] 13. 2. Be not forgetful to lodge strangers: for hereby some have received Angels into their houses unawares. #emph[This duty the woman of Shunem & her husband performed unto the Prophet] Elisha, 2. #emph[King.] 4. 10. Let us make him a little chamber, I pray thee, with walls, and let us set him a bed there, and a table, and a stool, and a candlestick, that he may turn in hither, when he commeth to us. #emph[These are the duties.]

Here if it be demanded, whether the master of a family is always, and necessarily bound in his own person to do all these things?

I answer, that if there be just and necessary cause, either in respect of his own inability, or in regard of public employment, upon a lawful calling, whereby he is hindered, so as he cannot do any of them himself, at some times; it is lawful for him to have, and use a deputy. This our Saviour Christ teacheth in effect, when he saith, #emph[Who then is a faithful servant, and wise, whom his master hath made ruler over his household, to give them meat in season?] Mat. 24. 45. Thus #emph[Abraham] had a steward of his house, #emph[Eliezer] of Damascus, Gen. 15. 2. And he performed the weightiest matters, that concerned the establishment, and continuance of family, not by himself, but by his Steward, as namely the choice of a wife for his son #emph[Isaac,] Gen. 24. 2. #emph[Therefore Abraham said unto his eldest servant of his house, which had the rule over all that he had; Put now thine hand under my thigh,] &c. Thus #emph[Pharaoh] King of Egypt had #emph[Joseph,] Gen. 39. 4. #emph[So Joseph found favour in his sight, and served him, and he made him ruler of his house, and put all that he had in his hands.]
