== The Epistle Dedicatory

Right Honorable; Among all the societies & states, whereof the whole world of mankind from the first calling of #emph[Adam] in Paradise, unto this day, hath consisted, the first and most ancient is the family. For if we look into the Scriptures; The writings of #emph[Moses,] which in time go beyond all the Histories and Records of men, do evidently declare, it was the will of God, to sanctify that first conjunction of #emph[Adam] and #emph[Eve,] as the root wherein mans whole posterity was #emph[virtually] contained, and whence in the ages succeeding, both Church and common-weal should spring and grow to their perfection. And all those nations and Countries before the Flood, the Heads whereof lineally descended from the two first houses of #emph[Seth] and #emph[Cain,] had no outward form of civil government, by which they were ruled, nor any visible face of a Church whereto they had relation, but the whole frame of their policy both Civil and Ecclesiastical was confined within the precincts of private families. And from the flood, the house of #emph[Noah] became the common mother, in which the other two states were included, and out of whose bowels they issued afterward in the multiplication of posterity, for number, equal to the stars of the sky, and the sands by the sea shore.

Answerable to the voice of the scripture, hath been the verdict of the Heathen in this point. Some of the#footnote[Aristot. Politic. 1.] learned among them, have called the family,#footnote[Xenoph. in Oeconom.] #emph[the first society in nature, and the ground] of all the rest. Some again have compared it to the Bee-hive, which we call the Stock, wherein are bred many swarms, which thence do fly abroad into the world, to the raising and maintaining of other states.#footnote[Xenoph. ibid.] Others do not unfitly resemble the same to a Metropolis, or mother City, which first traineth up her native inhabitants, and then#footnote[ἀποικίζει. Cic. 3. de Nat. Deor.] removeth some of them to other places of abode, where they may be framed as members, to live in obedience to the laws of their Head.

Upon this condition of the family, being the Seminary of all other societies, it followeth, that the holy and righteous government thereof, is a direct mean for the good ordering, both of Church and common-wealth; yea that the laws thereof being rightly informed and religiously observed, are available to prepare and dispose men to the keeping of order in other governments. Hence it is, that the Holy Ghost in the book of the Scriptures, hath in great wisdom commended both rules for direction, and examples for imitation, to husbands and wives, to parents and children, to masters and servants in every point of Christian carriage touching God and man. For this first society, is as it were the School, wherein are taught and learned the principles of authority and subjection. And look as the Superior that faileth in his private charge, will prove uncapable of public employment;#footnote[1\. Tim. 3. 5] so the Inferior, who is not framed to a course of Economical subjection, will hardly undergo the yoke of civil obedience.

Again, the corruption or declination of this first government, must of necessity give way to the ruinating of the rest. For an error in the foundation, puts the body and parts of the whole building in apparent hazard. In the old world,#footnote[Gen. 6. 12.] before the flood, though #emph[all flesh had corrupted their ways;] yet the first ground of that universal overflow of sin, issued out of the state Economical, and thence was derived into the whole earth. It was the fault of the private government of #emph[Eli] the Priest, that made his sons #emph[Hophni] and #emph[Phinehas,] #footnote[1\. Sam. 2. 12. 23, 24, 25.] of ungracious children, ungodly Church-men. It was the error of #emph[David] in the administration and guidance of his own house,#footnote[2\. Sam. 14 33.] which encouraged #emph[Absalom] and #emph[Adoniah] his sons,#footnote[1\. King. 5. 6.] upon presumption of their Fathers indulgence,#footnote[2\. Sam. 15] to become ill common-wealths men,#footnote[1\. King. 1.] to aspire, and usurp the kingdom by plots and practises of Rebellion.

To forbear further matter of instance in this kind; by the due consideration of the premises, I hold it a thing both necessary and behooful for all estates, to be thoroughly informed of the right manner of erecting and ordering the private condition of the family, whereby they may be furnished with fit grounds for the common good in more public and open courses. For which end this present Discourse of Christian Economy, was first contrived by the author, and now thought fit to be set forth, for the instruction and edification of the multitude. Which as it commendeth it self by the shortness and perspicuity, both which being applied to understanding and memory, may give contentment to every well-disposed Reader; so it carrieth a kind of eminency above other Treatises of this nature before published, in sundry regards.

First, whereas Experience teacheth, that the Questions of conscience in matrimonial affairs, are very many in number, and difficult in nature; here we shall find either direct answers to some of them, or at least the grounds of resolution in divers cases, warranted by the word, in such sort, as little or nothing will appear, upon the trial, to be untouched, making for the Readers satisfaction.

Secondly, the maine scope of the author in the several branches hereof, is, to make plain this truth in particular, That no family can be interessed in the blessing and favour of God, which is not founded in his fear, and ordered according to his revealed will. For though the Heathen in their writings of the like argument,#footnote[Aristot. Politic. Xenoph. in Oecon.] do show, that nature by her dim light may afford some good directions to this purpose, and that men merely natural, have prospered in the practise of Economical virtues; yet the true happiness of houses and inhabitants wholly dependeth upon the special grace of God, and issueth out of his promise; and that is directed only #emph[to them that fear him and walk in his ways;] #footnote[Psal. 128. 1] it being #emph[godliness alone which hath the promises of this life and the life to come.] #footnote[1\. Tim. 4. 8] Therefore to dream of a blessing in any other state, which is not seasoned with godliness, and ordered by direction of divine law, is but a witless presumption; considering that the family it self from whence they grow, hath no further assurance of blessedness, then it hath right and title in the promise.

Lastly, it containeth here and there, some special grounds of truth, tending to the discovery of divers errors of Popish doctrine in points appertaining to marriage; as namely these;

// I. That this estate is free to all men, even to such as have the gift of continency; and for those who have not the power to abstain, it is expressly enjoined by God as necessary.#footnote[1\. Cor. 7. 1. 2. 8. 9.] Which discovereth that error of absolute inhibition thereof to some sorts of men, without the least exception of ability to forbear. And in this case, though the Church of Rome prescribeth an help by prayer and endeavour, where the gift is wanting; yet herein, she addeth two more absurdities to the former; imposing a necessity of containing, by her laws, where God hath given liberty, by his word; and causing to flee from that only Remedy which himself hath sanctified, to another, whereunto he neither giveth charge by his will, nor encouragement by promise.
// II. That Marriages consummate without the free and advised consent of parents, either #emph[explicit] in terms, or #emph[implicit] by connivence, are in the court of conscience, mere nullities. A doctrine cleared in this Book, both by Scriptures, and by consent of Antiquity. Wherein is challenged the Jesuits proposition, That the sole consent of the parties is sufficient,#footnote[Bellarm. de Matrim. Sacram. libr. c. 19.] #emph[ad Matrimonium firmum ac ratum efficiendum.] As also that decree of the Council of Trent,#footnote[Concil. Trident. Sess. 24. Decreto de clandest. Matrim.] which professeth a detestation of clandestine contracts, and yet with the same breath pronounceth the curse of Anathema upon them, who affirm that parents may ratify or make void Marriages contracted by their children, without their allowance.
// III. That Matrimony lawfully begun and consummate, is made void only by way of divorce in the case of Adultery. So saith our Saviour;#footnote[Matth. 5. 32.] #emph[Whosoever shall put away his wife, (except it be for fornication,] &c.) And this liberty granted by Christ both to dissolve, and to marry again, cannot be restrained or cut off by any humane ordinance. A point directly impugned by two other rules of that Council. One, that the Church of Rome erreth not, when she teacheth (as they profess,#footnote[Concil. Trid. Sess. 24. Can. 7.] #emph[Iuxta Euangelicam & Apostolicam doctrinam,] but in truth expressly contradictory thereunto) That the knot of marriage cannot be broken because of adultery, and that neither party may undertake to be married again, during the life of the other, after the dismission. The other, that the vow of Chastity and entering into holy Orders, is of force to loose the bond of marriage. And in this case, separation is made and allowed #emph[de facto,] by the sole authority of the Pope, notwithstanding the refusal of the settled party to yield consent. IV. That the judgement and determination of causes matrimonial, as of Contracts and their impediments, of degrees of kindred, of divorces, &c. Resteth #emph[originally] in the civil Magistrate, in whose power it is, to ordain and establish laws touching them, agreeable to Gods word, and to cause them to be put in execution. For this purpose, in doubtful and difficult cases, the#footnote[#emph[See the] Code #emph[in sundry places.] Lib. 5. tit. 4 de Nuptijs, tit. 5. de incesto, &c.] ancient Church hath not absolutely rested in her own decrees, but hath made recourse to the seat of Justice, specially under Christian Magistrates, submitting her self to their laws and constitutions in that kind. Whereas the#footnote[Concil. Trid. sess. 24. can. 12.] Church of Rome hath determined, that these causes do simply and only appertain to Ecclesiastical Judges; and therefore hath concluded marriage to be a sacrament; that the definition of cases conjugal, becoming, upon this ground, an action of a spiritual nature, might be transferred from the Civil to their spiritual Courts. The sovereignty whereof; in these affairs, by their own constitutions, is greatly enlarged. For though they admit, that politic Princes have some interest in them; yet they must hold it,#footnote[Bellarm. de Matrim. Sacram. cap. 32.] #emph[with subordination to the authority of the Church-Magistrate;] and when the Rector of the Province maketh a law hereof, he must do it #emph[approbante Principe Ecclesiastico,] by the allowance of the Pope; otherwise his laws are mere nullities. And among their reasons of policy, this is one of the principal, that they might by this means raise a commodity to the Sea of Rome, by the sale of their dispensations.

#set enum(numbering: "I.")

+ That this estate is free to all men, even to such as have the gift of continency; and for those who have not the power to abstain, it is expressly enjoined by God as necessary.#footnote[1\. Cor. 7. 1. 2. 8. 9.] Which discovereth that error of absolute inhibition thereof to some sorts of men, without the least exception of ability to forbear. And in this case, though the Church of Rome prescribeth an help by prayer and endeavour, where the gift is wanting; yet herein, she addeth two more absurdities to the former; imposing a necessity of containing, by her laws, where God hath given liberty, by his word; and causing to flee from that only Remedy which himself hath sanctified, to another, whereunto he neither giveth charge by his will, nor encouragement by promise.
+ That Marriages consummate without the free and advised consent of parents, either #emph[explicit] in terms, or #emph[implicit] by connivence, are in the court of conscience, mere nullities. A doctrine cleared in this Book, both by Scriptures, and by consent of Antiquity. Wherein is challenged the Jesuits proposition, That the sole consent of the parties is sufficient,#footnote[Bellarm. de Matrim. Sacram. libr. c. 19.] #emph[ad Matrimonium firmum ac ratum efficiendum.] As also that decree of the Council of Trent,#footnote[Concil. Trident. Sess. 24. Decreto de clandest. Matrim.] which professeth a detestation of clandestine contracts, and yet with the same breath pronounceth the curse of Anathema upon them, who affirm that parents may ratify or make void Marriages contracted by their children, without their allowance.
+ That Matrimony lawfully begun and consummate, is made void only by way of divorce in the case of Adultery. So saith our Saviour;#footnote[Matth. 5. 32.] #emph[Whosoever shall put away his wife, (except it be for fornication,] &c.) And this liberty granted by Christ both to dissolve, and to marry again, cannot be restrained or cut off by any humane ordinance. A point directly impugned by two other rules of that Council. One, that the Church of Rome erreth not, when she teacheth (as they profess,#footnote[Concil. Trid. Sess. 24. Can. 7.] #emph[Iuxta Euangelicam & Apostolicam doctrinam,] but in truth expressly contradictory thereunto) That the knot of marriage cannot be broken because of adultery, and that neither party may undertake to be married again, during the life of the other, after the dismission. The other, that the vow of Chastity and entering into holy Orders, is of force to loose the bond of marriage. And in this case, separation is made and allowed #emph[de facto,] by the sole authority of the Pope, notwithstanding the refusal of the settled party to yield consent.
+ That the judgement and determination of causes matrimonial, as of Contracts and their impediments, of degrees of kindred, of divorces, &c. Resteth #emph[originally] in the civil Magistrate, in whose power it is, to ordain and establish laws touching them, agreeable to Gods word, and to cause them to be put in execution. For this purpose, in doubtful and difficult cases, the#footnote[#emph[See the] Code #emph[in sundry places.] Lib. 5. tit. 4 de Nuptijs, tit. 5. de incesto, &c.] ancient Church hath not absolutely rested in her own decrees, but hath made recourse to the seat of Justice, specially under Christian Magistrates, submitting her self to their laws and constitutions in that kind. Whereas the#footnote[Concil. Trid. sess. 24. can. 12.] Church of Rome hath determined, that these causes do simply and only appertain to Ecclesiastical Judges; and therefore hath concluded marriage to be a sacrament; that the definition of cases conjugal, becoming, upon this ground, an action of a spiritual nature, might be transferred from the Civil to their spiritual Courts. The sovereignty whereof; in these affairs, by their own constitutions, is greatly enlarged. For though they admit, that politic Princes have some interest in them; yet they must hold it,#footnote[Bellarm. de Matrim. Sacram. cap. 32.] #emph[with subordination to the authority of the Church-Magistrate;] and when the Rector of the Province maketh a law hereof, he must do it #emph[approbante Principe Ecclesiastico,] by the allowance of the Pope; otherwise his laws are mere nullities. And among their reasons of policy, this is one of the principal, that they might by this means raise a commodity to the Sea of Rome, by the sale of their dispensations.

Now these points, together with the substance of this small discourse, I willingly commend unto your Lordship, desiring that under the wings of your Honourable protection, it may safely walk abroad in the world, to the view and benefit of others. The true report of your ancient love of the truth, and favourable inclination to the Ministers and dispensers thereof, hath given me encouragement in this action; the rather, for that the argument fitteth in some sort your present estate, whose house God hath adorned with olive plants,#footnote[Psal. 128. 3.] a virtuous and hopeful issue, whose young years being seasoned therein, by the sweet savour of their fathers virtues, may yield in time a plentiful increase of honour in this common-wealth; and consequently advance your Name in themselves and their posterity. To this may be added mine own desire to give some testimony of duty to your Lordship, as holding it your due, to be had in Honourable terms with men, whose care hath been to maintain the honour of the Highest by your constant profession and practise of Religion. And thus emboldening my self upon the persuasion of your Lordships favour and acceptance, I humbly take my leave, and commend you to the grace of#footnote[Act. 20. 32] God, who is able to build you up further, and give you an inheritance among them which are sanctified. #emph[Finching-field,] Septemb. 26. 1609.

#linebreak()
#linebreak()

#align(left)[Your Lordships to be commanded in all Christian duty,]

#align(right)[#emph[THO. Pickering.]]
