== Children Giving Back to Parents

=== §. 39. #emph[Of childrens Recompense.]

The general head whereunto all the duties which children owe to their parents in regard of their #emph[Necessity,] is in one word #emph[Recompense,] which is a duty whereby children indeavour as much as in them lieth, to repay what they can for their parents kindness, care, and cost towards them, and that in way #footnote[#emph[Arist. Ethic. l.] 8. #emph[c.] 14.] of thankfulness; which maketh a child think he cannot do too much for his parent, & well may he think so, for a parent doth much more for his child before it is able to do for it self, then the child possibly can do for the parent. So as if the parents #emph[authority] were laid aside, yet the law of #emph[equity] requireth this duty of #emph[Recompense:] so also doth the law of #emph[piety] and #emph[charity.] Wherefore of all other duties this is most due. #footnote[1 #emph[Tim.] 5. 4.] It is in express terms given in charge to children by the Apostle, who willeth them to learn to #emph[requite their parents.]

Contrary is neglect of parents in their need, which is more #footnote[It is monstrous ingratitude for children to neglect their parents.] then monstrous ingratitude. As all ingratitude is odious to God and man, so this most of all, and yet very many are guilty thereof. In them the proverb is verified that #emph[love is weighty.] For it is the property of weighty things to fall down apace, but to ascend slowly, and that not without some violence. Thus love from the parent to the child falleth down apace, but it hardly ascendeth from children to parents. In which respect another proverb saith, #emph[One father will better nourish nine children, then nine children one father.] Many children in this kind do no more for their parents, then for strangers. They either consider not how much their parents have done for them; or else they conceit that what their parents did, was of mere duty, and needeth no recompense. Fie upon such barbarous and inhumane children!

=== §. 40. #emph[Of infirmities whereunto parents are subject.]

The rule of the forenamed recompense is on the one side #footnote[A rule of recompense.] the #emph[parents Necessity,] and on the other, the #emph[childes Ability.] So as in every thing wherein a parent needeth his childes help, the child to his power must afford his best help. #emph[Beyond ones power nothing can be expected.] #footnote[Ultra posse non est esse.]

A parents #emph[Necessity] may be through

+ #emph[Natural infirmities.]
+ #emph[Casual extremities.]

Natural infirmities are

+ #emph[Inward.]
+ #emph[Outward.]

#emph[Inward] Infirmities are weakness of judgment, slipperiness of memory, violence of passion with the like; whence proceed frowardness, testiness, suspiciousness, jealousy, fear, grief, etc.

#emph[Outward] Infirmities are such as arise from some instant temptation, as were #footnote[#emph[Gen.] 9. 21.] #emph[Noahs] and #footnote[#emph[&] 19. 33.] #emph[Lots] drunkenness; #footnote[#emph[&] 19. 33.] #emph[Lots] and #footnote[2 #emph[Sam.] 11. 4.] #emph[David's] uncleanness; #footnote[#emph[Gen.] 12. 13.] #emph[Abraham's] and #footnote[#emph[&] 26. 7.] #emph[Isaacs] dissimulation; #footnote[#emph[&] 37. 34, 35.] #emph[Jacob's] and #footnote[2 #emph[Sam.] 18. 33.] #emph[David's] excessive lamentation, etc.

Some of these latter, which may seem most heinous and odious sins, are then to be accounted infirmities, when they who commit them make not a sport of them, nor delight to live and lie in them, as swine to wallow and lie in the mire: but only at some times, through some temptation, as it were unawares, fall into them; and after they are committed they are themselves more ashamed of them, and more grieved for them, then any other that see them, or hear of them.

In regard of the natural infirmities of parents, the duty of children is both to #emph[bear with them,] and also to #emph[cover them] so far as they can.

=== §. 41. #emph[Of childrens bearing with their parents infirmities.]

Children bear with their parents infirmities when they do not the less reverendly esteem their place, or person, nor perform the less duty to them because of their infirmities.

This is the first particular branch of recompense. For children in their younger and weaker years are subject to many infirmities: if parents had the less respected them for their infirmities, and from thence had taken occasion to neglect them, and would not have borne with them, surely they could not have been so well brought up. That great patience, long-sufferance, and much forbearance which parents have showed towards their children, requireth that children in way of recompense show the like to their parents as occasion is offered. It was a great infirmity in #emph[Isaac] to prefer #emph[Esau] a profane child, before #emph[Jacob] a religious child, especially against Gods express word concerning #emph[Jacob;] yet #emph[Jacob] respected not his father a whit the less for it, as appears by his #footnote[#emph[Gen.] 27. 12.] fear to offend him, and by his #footnote[#emph[&] 28. 5.] readiness to obey him. #footnote[#emph[&] 37. 10.] #emph[Jacob's] unjust reproof of #emph[Joseph] was no small infirmity, and yet how much #emph[Joseph] reverenced and every way respected his father the history following showeth. #emph[Sauls] infirmities were far more and much greater then any of theirs, yet what duty and faithfulness did #emph[Jonathan] his son perform to him, even to their deaths? For #footnote[1 #emph[Sam.] 31. 2.] he died with him.

We have herein the pattern of Christ himself: how great infirmity did his mother bewray, when over-rashly she rebuked him being about a good work, a bounden duty, his fathers business? Yet immediately thereupon it is noted that #emph[he went down with his parents, and was subject to them:] which #footnote[#emph[Luk.] 2. 51.] manifesteth the honour he gave to his mother, notwithstanding her infirmity.

Contrary to this duty do they, who take occasion from their parents infirmities to think basely of their person and #footnote[A child may not despise a parent for any infirmity.] their place, and thereupon grow careless in duty, either refusing to do any duty at all, or else doing it carelessly, grudgingly, disdainfully, and scornfully. #emph[Absalom] made a supposed infirmity of his father the ground of his rebellion. Had #footnote[2 #emph[Sam.] 15. 3.] his pretence been true, yet had it not been a sufficient cause for him to disgrace, and rise against his father, as he did. The law that threateneth Gods vengeance against such children as #emph[mock at their father, or despise to obey their mother,] maketh #footnote[#emph[Pro.] 30. 17.] no exception of parents infirmities.

=== §. 42. #emph[Of childrens covering their parents infirmities.]

Children cover their parents infirmities both by passing by them (as we speak) and taking no notice of them, and also by concealing them from others as much as they can. The Scripture noteth it to be a property of #emph[love] to #emph[cover a multitude] #footnote[1 #emph[Pet.] 4. 8.] #emph[of sins:] now in whom should love abound, if not in children? And who should more manifest this property of love then children?

Of passing by and concealing from others a parents infirmity, we have a worthy pattern in #emph[Shem] and #emph[Japhet:] when #emph[Noah] their father being drunken lay uncovered in the midst of his tent, #emph[they went backward] (that they might not themselves #footnote[#emph[Gen.] 9. 23.] see their fathers infirmity) and #emph[covered his nakedness] (that others might not see it.) The blessing which upon this occasion was then promised to them and their posterity, showeth how acceptable this duty was to God.

Contrary was #emph[Chams] practise, who discovered, and made #footnote[A sin for a child to discover a parents infirmity.] known his fathers nakedness. The curse thereupon denounced against him, showeth how odious that sin was unto God. Too many there be of #emph[Chams] cursed brood, who blaze abroad their parents infirmities, and make such things known of them, #footnote[#emph[Gen.] 9. 22. #emph[Vers.] 25.] as otherwise would not be known: whereby they bring much dishonour and shame upon their parents (which can be no honour #footnote[#emph[Parentis imprecatione nihil perniciosius excogitari potest. Plato de Leg. lib.] 11.] to the children,) and withal a curse from their parents on themselves, which the heathen accounted very dreadful.

More contrary was #emph[Absaloms] practise, who raised a most malicious slander of his father, and thereby alienated his subjects hearts from him. Too many #emph[Absalom-]like seek to raise a supposed #footnote[More then monstrous for a child to raise a slander of a parent.] reputation and honour to themselves by vilifying and disgracing their parents: but let them note #emph[Absaloms] end. Assuredly, if they hold on in that course, the like, or a worse, shall be their end.

=== §. 43. #emph[Of childrens bearing with their parents casual necessities.] #footnote[2 #emph[Sam.] 15. 3.]

Casual extremities, are all manner of crosses which by the providence of God are laid upon a man: whether upon his body, as blindness, lameness, sickness, etc. Or on his person, as captivity, banishment, imprisonment, etc. Or on his estate, as poverty, penury, etc. In all these, children must bear with their parents, as in the forenamed infirmities; neither less reverendly esteem of them, nor perform the less duty because of them. These are such necessities, as are not sinful in themselves; and therefore in regard of these, parents are much more to be borne withal. Though #emph[Isaac] were #emph[blind,] yet did not #emph[Jacob] a whit the less respect #footnote[#emph[Gen.] 27. 1. #emph[Ruth] 1. 16, 21.] him. Though #emph[Naomi] were poor, yet #emph[Ruth] her daughter in law continued to do a childs duty and service unto her.

Contrary is the unnatural disposition of such children, as #footnote[Unnatural to despise a parent for any casual infirmity.] take occasion from these casual necessities of their parents to despise them. God hath made an express law against despising those who are by any outward defects impotent, as #emph[deaf, blind,] etc. If no person may despise another, for these, much less children #footnote[#emph[Leu.] 19. 14.] their parents. They are worse then #emph[Cham] that do so, and may look for an heavier curse.

=== §. 44. #emph[Of childrens relieving their parents according to their need.]

Besides bearing with parents necessities, in such cases as parents stand in need of their childrens relief and succour, they must afford it them. In sickness they must visit them, as #footnote[#emph[Gen.] 48. 1.] #emph[Joseph] visited his father. In time of mourning, they must comfort them, as #footnote[#emph[&] 37. 35.] the children of #emph[Jacob.] In want, they must provide things needful for them, as #footnote[#emph[&] 42. 8.] the sons of #emph[Jacob,] who went up to buy food for their father; and as #footnote[#emph[&] 47. 12.] #emph[Joseph,] who sent for #emph[Jacob] into Egypt, and there nourished him. It is noted of #footnote[#emph[Ruth] 2. 18.] #emph[Ruth,] that she did not only glean for her mother a poor woman, but also reserved some of that food which was given to her self to eat, for her. In time of danger they must do what they can for their protection and preservation, as #footnote[1 #emph[Sam.] 22. 3, 4.] #emph[David] had in this respect an especial care of his father and mother. Yea, if God be pleased to #footnote[Vetustissima lex erat inscripta mentibus omnium, vt liberi si hoc officij grauentur impendere quod pulli ciconiarum reponunt suis parentibus, velut impij conijciantur in vincula. Erasm. Instit. Matrim.] take children out of this world before their parents, and their parents be succourless, they must take what order they can for the well-being of their parents after their own departure, as #footnote[#emph[John] 19. 27.] Christ, who commended his mother to his disciple #emph[John] a little before his death. These and such like duties are particular branches of #emph[recompense,] and are all comprised under that #footnote[1 #emph[Tim.] 5. 4.] #emph[requital,] which the Apostle requireth of children: And they are but a small part of requital of all the pains, care, and charges, that parents have been at with their children. Yea, this only thing, that parents have brought forth children into the world, can children never sufficiently requite. Nature hath taught thus much, not only unto heathen men, but also unto the unreasonable creatures. Among other unreasonable creatures, the example of the #footnote[Arist. Plin. Suidas.] #emph[Stork] is worthy to be noted: for it is recorded of that kind, that when the dams are old, the young ones feed them; and when through age, they are ready to faint in their flying, the young ones will help; and when they are past flying, the young ones carry them on their backs. The #footnote[Sin of Pharisees in freeing children from relieving their parents.] Greek name of a #emph[Stork] is taken from that #emph[word,] which signifieth, to #emph[requite a parents kindness:] or else this word is taken from that name: they are both of the same notation.

Contrary is the opinion of Pharisees, who thought that children by consecrating their substance to the Temple, might be freed from this duty of #emph[recompense] to parents, which is the mystery of that Hebrew word #footnote[#emph[Mar.] 7. 11.] #emph[Corban.] They made a mere pretext of piety to God, a cause of manifest impiety against parents. Christ giveth this verdict of them, that #footnote[#emph[vers.] 13.] #emph[they make the word of God of none effect.] #footnote[See §. 14. 1. Sin of children in denying relief to parents.] Papists are of the same opinion, and so under the same censure.

Contrary also is their practise, who having the goods of this world, suffer their parents to want. #footnote[1 #emph[Joh.] 3. 17. #emph[Iniquissimum est patrem egere, cùm filius sit in facultatibus. Digest. lib.] 25. #emph[tit.] 3. §. 5.] #emph[S. John] saith, that #emph[the love of God dwelleth not in him, who shutteth up his compassion from his brother] in that case; how then can it dwell in such a child? Not they only who suffer their parents to starve, offend in this extreme, but they also who suffer them to live poorly, and basely, when themselves #footnote[#emph[Luk.] 16. 19. 2. In bringing parents into extremities.] Dives-like fare delicately, and go gorgeously attired every day.

In an higher degree do they offend, who bring their parents to such extremities, as to poverty by their lavish spending; to prison by importuning them to be their sureties; to excessive grief by their mischievous practises, as #footnote[#emph[Gen.] 37. 34. 3. In striking parents.] the sons of #emph[Jacob.]

But what shall we say of such graceless children, as dare strike their parents? #footnote[#emph[Exod.] 21. 15. 4. In murthering parents.] Gods law accounteth such a child unworthy of life, and adjudgeth him to death.

Nay, what may be said of #emph[father-quellers,] and #emph[mother-quellers?] There was of old no particular law made against them, because it is supposed, that no child can be so unnatural and inhumane. In imitation whereof #footnote[Solon cùm interrogaretur, cur nullum supplicium constituisset. in eum qui parentem necasset, respondit, se id neminem facturum putasse. Cic. pro Ros. Amer.] #emph[Solon,] that wise law-maker among the heathen, made no law against them: and his reason being asked, he answered, that he thought no child would commit such a fact.

When afterwards such inhumane impiety was manifested in the world, the Civil Law ordained this punishment; #footnote[#emph[Si quis parentis fata properauerit, neque gladio, neque ignibus, neque vlli alij solenni poenae subiugetur, sed insutus culeo cum cane, & gallo gallinaceo, & vipera, & simia, vel in vicinum mare, vel in amnem proijciatur, etc. Justin. Cod. l.] 9. #emph[tit.] 17. #emph[Cur voluerint parricidas insui in culeum viuos, atque ita in flumen deijci, docet Cicero pro Ros. Amer. Ad famam filij attinet, vt videatur honorem debitum patri] defuncto #emph[praestitisse. Cic. Philip.] 9.] #emph[If any shall kill his parent, let him not be put to the sword, nor fire, nor any other usual punishment: but let him be sowed in a sack with a dog, and a cock, and a viper, and an ape, and cast into the next sea, or river; that while life is in him, he may begin to want all use of the elements, and be deprived, while he liveth, of the air, and when he is dead, of the earth.]

This sin having been committed among the heathen, the Apostle reckoneth it up among other most notorious and barbarous sins, 1 #emph[Tim.] 1. 9. As murder is one of those sins, which the earth can least bear, and which crieth loudest to heaven for vengeance; so among the several kinds of murder, this is the most unsupportable, and crying.

Thus much of the duties of children, which they are to perform while their parents live. It remaineth to speak of those which they are to perform when their parents are dead.

=== §. 45. #emph[Of childrens care to bury their parents being dead.]

The duties which children owe to their parents after they are dead, concern the

+ #emph[Body]
+ #emph[Credit]

of their deceased parent.

It is the duty of children to bring the bodies of their parents deceased, with such decency and honour, as may be answerable to the place and reputation wherein they lived.

So as both the #emph[thing] it self, and the #emph[manner] of doing it, is to be observed. #footnote[Burial a means to maintain hope of resurrection.]

The thing it self, namely #emph[Burial] of the corps of such as are deceased, hath ever been in use in Gods Church: and it hath been used as a means to maintain our hope of the resurrection of our bodies. Many of the heathen, who never dreamt of the resurrection, #footnote[#emph[Constituere pyras: huc corpora quisque suorum More tulere patrum, subiectisque ignibus, etc. Virg. Aeneid.] 11.] were wont to burn the dead bodies of their friends: other heathen learned this manner of burial from the Church, though they knew not the mystery thereof. It is more clear then needs be proved, that Gods people, from the beginning of the world, have performed this duty of burial to their friends; but it is not pertinent to the point in hand, to insist upon the general: that it belongs especially to children to procure this duty to be performed, is now the point to be proved, which is readily done by the approved examples of #footnote[#emph[Gen.] 25. 9.] #emph[Isaac,] #footnote[& 35. 29.] #emph[Jacob,] #footnote[& 50. 7.] #emph[Joseph,] and others expressly recorded in Scripture.

And great reason there is for it: for

1. It is a testimony of great love and good respect to the party #footnote[1\. #emph[Reason.]] deceased. Now who should manifest more love, and greater respect then a child?

2. It is a kind of #footnote[1 #emph[King.] 14. 13. 2 #emph[King.] 22. 20.] #emph[blessing,] promised by God to his Saints, #emph[to] #footnote[2\. #emph[Reason.]] #emph[be buried:] as on the other side, it is a #footnote[#emph[Jer.] 22. 19. 1 #emph[King.] 21. 23, 24. #emph[Psal] 79. 3.] #emph[curse] threatened against obstinate sinners, #emph[not to be buried.] In this respect, #footnote[2 #emph[Sam.] 2. 5.] #emph[David] blesseth the men of #emph[Jabesh Gilead] for burying #emph[Saul,] and acknowledgeth it a kindness done to #emph[Saul.] Now who ought rather to procure a blessing, and do a kindness to parents, then children, who are oft blessed through their parents means?

3. It being a great deformity to have a mans corps lie above #footnote[3\. #emph[Reason.]] ground (for no carcass will be more loathsome then a mans if it lie unburied) children, who are most bound to cover their parents deformity, are in this respect bound to bury their corps. #footnote[Sin of children to neglect their parents dead corps.]

Contrary is their practise whose minds are so set on their parents goods, as they clean neglect their bodies. So soon as their parents breath is out of their body, they so busy themselves about the things which they have left behind them, as their corps is ready to stink before care be taken for the burial of it. Yea, some will purposely keep their parents corps above ground till they be exceeding noisome, for receiving some revenues, or debts, or other accounts, which must be paid before the corps be buried. If their corps must needs for sometime be kept above ground, let them be embalmed, or so used as they may not savour. They who are careless hereof, show that they respect their parents wealth #footnote[Sin of children entering upon their parents estate before they are dead. 1 #emph[King.] 1. 5.] more then his person and honour.

In which respect they also heinously transgress, who are so greedy of their parents estate, as they must needs prevent his departure, and like #emph[Adoniah] enter upon their fathers estate, and take possession of his goods before breath is out of his body: whereby they do oft cause great disquietness to him that would depart in peace.

Again, others bearing an inward grudge and secret hatred #footnote[Sin of children disturbing their parents funeral.] against a brother, or other kinsman, whom their parent entirely loved, and in that respect durst not meddle with him in their parents life-time, so soon, as their parent is dead, pick a quarrel with the party hated, and so disturb and hinder their parents funeral. Such a plot #emph[Esau] intended: but God defeated #footnote[#emph[Gen.] 27. 41.] it, whereby it appeareth that God is displeased therewith.

=== §. 46. #emph[Of the decency wherewith children ought to see their parents buried.]

The #emph[manner] after which children ought to see their parents buried, must be with such #emph[decency] as is agreeable to the commendable custom of the country and Church where their parents die, and with such #emph[honour] as is in some measure answerable to the estate, and place of their parents while they lived (at least if it be not above the means that the parent hath left, or above the ability of the child that maketh the solemnity.) #emph[Joseph] was a great Governor in Egypt, by reason whereof his father when he came thither was highly accounted of: accordingly #footnote[#emph[Gen.] 50. 7.] with great honour did he carry him to his grave.

There are two extremes contrary to the forenamed #emph[decency] #footnote[Contrary, 1. Too sumptuous funerals.] and #emph[honour.] One is an overlavish and prodigal sumptuousness and solemnity at their parents funeral, far above the estate, and far beyond the means which the parent hath left, and far also above the estate and ability of the child himself. Some by the needless solemnity of their parents funeral are so far cast into debt, as they are never able to recover themselves again, and so bring more dishonour to their parents by the weakness of their childes estate, then honour by the solemnity of the funeral: there may be great honour, and much decency in a funeral, where is not extraordinary charges: instance #emph[Stephens] funeral. #footnote[#emph[Act.] 8. 2.]

The other extreme is too base and private a manner of #footnote[2\. Too base funerals.] burying their parents, much unbeseeming both their parents and their own estate, and means; which ariseth from a mixture of pride, and covetousness possessing their hearts. Pride maketh them have no solemnity at all, because covetousness will not suffer them to exceed in their solemnity. Hence it cometh to pass that they choose out strange places where neither their parents or selves are known, and the dead of the night that none may espy them; and appoint an uncertain time, that no friend may accompany them. God oft meeteth with such proud, covetous children in their kind, and causeth them with like dishonour to be brought to their graves.

=== §. 47. #emph[Of childrens paying their parents debts after their death.]

As children must have respect to the body of their parents #footnote[Childrens respect to the credit of their deceased parents.] deceased, so also to their credit and name, which is a thing of greater account, and honour: a thing wherein they may bring a kind of blessing to their parents and make them live after their death.

Parents themselves cannot do any thing when they are dead to preserve the same: children therefore being the living Image of their parents must endeavour to do it.

Three things there be which children must make conscience of, even in regard of their deceased parents credit, and reputation; one, to pay their debts: another, to suppress ill rumors: a third, to imitate their good example.

I. If the estate of parents, their goods or lands come to their children, their duty is to pay their debts, so far as they can: especially if by law those debts may be recovered at their hands. For what law may force others to do in equity and Justice, conscience must move good children to do in charity, and recompense to their parents. The holy Ghost makes it a #footnote[#emph[Psal.] 37. 21.] note of a wicked man #emph[to borrow and not to pay.] Wherefore to wipe away that blot from the name of a parent deceased, children must be ready in this kind to do what the parent himself, if he were living, would, or should do. Yea if children of themselves be well able, though their parents left not sufficient to pay all their debts, they ought to pay them. Herein especially a childlike affection is manifested to the parent.

Contrary is their practise who strive to get all they can of their parents, and yet make no conscience of paying any debts at all, unless law force them thereto. What they do in this case cannot be thought to be done for their parents sake, but rather for their own sake. Many so little respect their parents credit in this kind, as they privily convey away and utterly conceal much of their parents estate, of purpose to defeat Creditors: which as it is a part of apparent injustice, so it is a cause of opening the mouths of men against their parents, to their discredit and shame.

=== §. 48. #emph[Of childrens suppressing evil reports against their parents deceased.]

The direction given before concerning childrens speech #footnote[§. 7.] of their parents behind their backs, may fitly be applied also to the care which children ought to have of the speeches and reports which are made of their parents after their departure. It followeth as #emph[from the less to the greater,] that what children do for their parents credit in absence behind their backs, they must much more do when they are dead: for then there is no hope, no possibility that parents should do any thing to right their own wrong in that kind: it lieth therefore upon children to do it.

Do not they clean contrary, who take occasion from the departure of their parents, both to open their ears to receive any ill reports of them, and also to open their mouths to speak ill of them: then blazing abroad all their infirmities, and stretching their ill reports of their parents beyond the lists of truth. Ill birds they are that so bewray their own nest. They know that their parents being dead can have no notice thereof: whereby they show what little piety to God or parent is in their heart. But there is an ever-living, all-seeing, and all-knowing father that taketh notice of all: who beside other vengeance will cause such measure to be meted out to them, as they mete to their parents. There is no one thing wherein this proverb, #emph[(With what measure you mete it shall be measured] #footnote[#emph[Mat.] 7. 2.] #emph[to you again)] is more often verified then in childrens ingratitude #footnote[#emph[Quaecunque parentibus stipendia intuleris, eadem ipse a filiis expecta. Thal. Miles. apud Diog. Laert. l.] 1.] to their parents. All ages have given many instances thereof. (The very heathen observed it.) Which showeth Gods great indignation against it.

=== §. 49. #emph[Of childrens imitating their parents good example.]

If parents have been persons of good carriage in their life time, as religious towards God, just in their dealings with men, merciful to such as stood in need of their help, doing much good in their place, and so ended their days with much credit; it is an especial means to maintain and continue this their credit, for children to walk in their steps, and to endeavour to be like them.

Thus is a blessed memory of their parents kept fresh and green (as we speak) though their bodies be rotten. For when they who knew the parents behold the like good qualities and actions in their children, they will thereby be put in mind of the parties deceased, and say, Oh how such parents yet live! Behold a lively, and living Image of them. Thus did #emph[Solomon, Asa, Jehoshaphat, Hezekiah, Josiah] and such like good Kings which came of the stock and lineage of #emph[David,] keep the memory of their father #emph[David,] fresh, fair, and flourishing (long after his body was rotten) as is evident by these and such like phrases, #emph[He walked in the ordinances of David his] #footnote[1 #emph[King.] 3. 3.] #emph[father: he walked in all the ways of David his father: he did] #footnote[2 #emph[King.] 22. 2.] #emph[that which was right as David his father,] etc. There can be no #footnote[1 #emph[King.] 15. 11.] better monument of a parents piety, honesty, and virtue, then a childes lively representation of the same. Wherefore #footnote[#emph[Nullum monumentum clarius relinquere potuit, quàm effigiem morum suorum, virtutis, constantiae, pietatis filium. Cic. Philip.] 9.] as a motive to stir up children to walk in the good ways of their parents, God hath promised to #emph[show mercy to thousands of them that love him and keep his commandments,] that is, such as having religious and righteous parents walk in their steps.

Contrary are both those that are unlike good parents, and those that are like evil parents. The former sort do much impeach and dishonour the reputation of their parents, as #emph[Rehoboam,] who by his foolish rigorous and unjust carriage, made the people speak contemptuously of #emph[David.] #footnote[1 #emph[King.] 12. 16.]

The latter sort continue in memory the evil name, and the shame of their parents, and cause them to stink more and more: as the sons and successors of #emph[Jeroboam,] who following his idolatrous course, made it the more remembered, and caused this blur to remain in his style from age to age, #emph[Jeroboam which made Israel to sin.] #footnote[1 #emph[King.] 15. 26.]

As #emph[they] stop the current, and hinder the passage of the blessing of righteous parents: so #emph[these] propagate, and open a way for the curse of unrighteous parents.

=== §. 50. #emph[Of the superstitious duty enjoined by Papists to children after their parents decease.]

To the two forenamed duties of #emph[burying the corps,] and #emph[preserving the credit] of parents, #emph[Papists] add a third, and #emph[Heathen] a fourth, whereof neither are warrantable by Gods word, but directly contrary thereto.

That which #emph[Papists] add is, that children after their parents #footnote[#emph[Bellar. Tom.] 2. #emph[Contr.] 3. #emph[De Purgator. l.] 2. #emph[c.] 16. #emph[etc.]] death ought to procure #emph[Diriges, Masses, Pardons, Releases,] and such like toys for them, and make continual prayers to free them out of Purgatory, and bring them to rest in heaven: of the vanity of these prayers, and folly of the other toys I have #footnote[In whole armour of God Treat. 3. §. 39. 40. #emph[in Ephes.] 6. 18.] elsewhere spoken.

The Scripture expressly teacheth that after death the soul goeth to the place appointed for it, of endless bliss or woe: so as there is no means of altering the one, or helping forward the other.

=== §. 51. #emph[Of the unlawfulness of childrens seeking to revenge their parents wrongs.]

That which #emph[Heathen] add, is, that children after their parents #footnote[Seneca in Agamen. Poetae tradiderunt filios patris vlciscendi causa supplicium de matre sumpsisse, idque deorum iussis, atque oraculis fecisse. Cic. pro. Sex. Ros.] death revenge such wrongs as have been done to them in their life time. And they press this so far upon children, as they affright them with their parents #emph[Ghost,] saying, that if they neglect to revenge their parents wrongs, their Ghost will follow them, and not suffer them to live in quiet, but molest them continually. This conceit ariseth from the corruption of nature, which is exceeding prone to revenge: but it is expressly forbidden in Scripture, in these and such prohibitions, #emph[Resist not evil,] #footnote[#emph[Rom.] 12. 17,] #emph[Recompense to no man evil for evil.] #footnote[19.] #emph[Avenge not] #footnote[#emph[Mat.] 5. 39.] #emph[our selves] etc. Yet some in justification thereof allege #footnote[1 #emph[King.] 2. 5. 8.] #emph[David's] charge to #emph[Solomon] of taking vengeance on #emph[Joab] and #emph[Shimei,] after his death.

#emph[Answ.] The charge which #emph[David] gave, & #emph[Solomon's] execution thereof, was no matter of private revenge, but only a lawful execution of justice which children may and ought to do. Just reasons there were to move #emph[David] to put off the execution of justice upon the one & the other so long. #footnote[2 #emph[Sam.] 3. 39.] #emph[Joab] was too mighty to have execution done on him in #emph[David's] time: and #emph[Shemeis] #footnote[& 19. 23.] offence was committed in the time of #emph[David's] humiliation, which made him swear that he would not himself take Vengeance of him. Besides, #emph[Solomon] executed justice on the one and the other, not for the wrongs they did to his father, but for other crimes which they committed in his time: only their former offences were remembered to aggravate the matter.

Thus far of childrens #emph[duties.] The #emph[manner] of performing them followeth to be declared.
