== 2. Unworthiness

=== The second #emph[Device] that Satan hath to keep poor sinners from believing, from closing with a Saviour, is,

BY suggesting to them their unworthiness. Ah saith Satan! As thou art worthy of the greatest misery, so thou art unworthy of the least crumb of mercy; what, dost thou think saith Satan, that ever Christ will own, receive, or embrace such an unworthy wretch as thou art? No, no, if there were any worthiness in thee, then indeed Christ might be willing to be entertained by thee; thou art unworthy to entertain Christ into thy house, how much more unworthy art thou to entertain Christ into thy heart, etc.

#strong[Now the Remedies against this device of Satan are these that follow.]

The first #emph[remedy] against this #emph[device] of Satan, is, seriously to consider, that God hath no where in the Scripture required any worthiness in the creature before believing in Christ. If you make a diligent search through all the Scripture, you shall not find from#footnote[John 5. 39.] the first line in #emph[Genesis,] to the last line in the #emph[Revelation,] one word that speaks#footnote[Mat. 19. 8.] out God's requiring any worthiness in the creature before the soul's believing in Christ, before the soul's leaning and resting upon Christ for happiness, and blessedness; and why then should that be a bar and hindrance to thy faith, which God doth no where require of thee before thou comest to Christ, that thou mayest have life? Ah sinners! Remember Satan objects your unworthiness against you, only out of a design to keep Christ and your souls asunder for ever; and therefore in the face of all your unworthiness rest upon Christ, come to Christ, believe in#footnote[John 6. 40. 47.] Christ, and you are happy for ever.

The second #emph[remedy] against this #emph[device] of Satan's is, wisely to consider, that none never received Christ, embraced Christ, obtained mercy and pardon from Christ, but unworthy souls. Pray what worthiness was in #emph[Matthew, Zacchaeus, Mary Magdalen, Manasseh, Paul] and #emph[Lydia,] before their coming to Christ? Before their faith in Christ? Surely none. Ah sinners! You should reason thus, Christ hath bestowed the choicest mercies, the greatest favours, the highest dignities, the sweetest privileges upon unworthy sinners; and therefore O our souls do not you faint, do not you despair, but patiently and quietly wait for the salvation of the Lord; who can tell but that free grace and mercy may shine forth upon us, though we are unworthy, and give us a portion among those worthies that are now triumphing in heaven.

The third #emph[remedy] against this #emph[device] of Satan's is, that if the soul will keep off from Christ till it be worthy, it will never close with Christ, it will never embrace Christ, ’twill never be one with Christ, it must lie down in everlasting#footnote[Isa. 50. ult.] sorrow. God hath laid up all worthiness in Christ, that the creature may know where to find it, and may make out after it. There is no way on earth to make unworthy souls worthy, but by believing in Christ: believing in Christ, of slaves, ’twill make#footnote[Joh. 1. 12.] you worthy sons; of enemies, ’twill#footnote[James 2. 23.] make you worthy friends, etc. God will count none worthy, nor call none worthy, nor carry it towards none as worthy but believers, who are made#footnote[Revel. 3. 4.] worthy by the worthiness of Christ's person, righteousness, satisfaction, and intercession, etc.

The fourth and last #emph[remedy] against this #emph[device] of Satan's is, solemnly to consider, that if you make a diligent search into your own hearts, you shall find that ’tis the pride & folly of your own hearts that puts you upon bringing of a worthiness to Christ. Oh you would fain bring something to Christ that might render you acceptable to him, you are loath to come empty handed. The Lord cries out, #emph[Ho] #footnote[Isa. 55. 1, 2.] #emph[every one that thirsteth, come ye to the waters, and he that hath no money: come ye, buy, and eat, come buy wine and milk without money, and without price.]

#emph[Wherefore do you spend your money upon] #footnote[Verse 2.] #emph[that which is not bread? And your labour for that which satisfieth not?]

Here the Lord calls upon moneyless souls, upon penniless souls, upon unworthy souls, to come and partake of his precious favours freely: but sinners are proud and foolish, and because they have no money, no worthiness to bring, they'll not come, though he sweetly invites them. Ah sinners! What is more just than that you should perish for ever, that prefer husks among swine before the milk and wine, the sweet and precious things of the gospel that are freely and sweetly offered to you, etc. Well sinners, remember this; ’tis not so much the sense of thy unworthiness, as thy pride that keeps thee off from a blessed closing with the Lord Jesus.
