== 3. Want of Preparation

=== The third #emph[Device] that Satan hath to keep poor sinners from believing in Christ, from closing with Christ, from resting on Christ, #emph[etc.] is,

BY suggesting to them the want of#footnote[3 Device.] such and such preparations, and qualifications: saith Satan, thou art not prepared to entertain Christ; thou art not thus and thus humbled and justified; thou art not heart-sick of sin▪ thou hast not been under horrors and terrours as such and such, thou must stay till thou art prepared, and qu•lified to receive the Lord Jesus, etc.

#strong[Now the remedies against this Device of Satan are these that follow.]

The first #emph[Remedy] against this #emph[Device] #footnote[1 Remedy.] of Satan, is, seriously to consider, that such as have not been so and so prepared and qualified, as Satan suggests have received Christ, believed in Christ, and being saved by Christ. #emph[Mathew] #footnote[Mat. 9. 9.] was called, sitting at the receipt of custom, and there was such power went along with Christs call, that made him to follow. We read not of any horrors or terrours, etc. That he was under before his being called by Christ. Pray what preparations and qualifications were found in #emph[Zacheus, Paul,] the#footnote[Luke 19. 9. Acts 16. chap.] Jaylor, and #emph[Lydia,] before their conversion. God brings in some by the sweet and still voyce of the Gospel, and usually such that are thus brought in to Christ, are the sweetest, humblest, 〈◊〉 isest, and fruitfulest Christians. God is a free agent to work by Law or Gospel; by smiles or frowns; by presenting hell or heaven to sinners souls God thunders from Mount-Sinai upon some souls, & conquers them by thundering God speaks to others in a still voyce, and by that conquers them. You that are brought to Christ by the Law, do not you judge and condemn them that are brought to Christ by the#footnote[Rom. 14.] Gospel: and you that are brought to Christ by the Gospel, do not you despise those that are brought to Christ by the Law. Some are brought to Christ by fire, storms, and tempests, others by more easy and gentle gales of the Spirit. The Spirit is free in the works of#footnote[Iohn 3. 8.] conversion, and as the wind, it blows when, where, & how it pleases. Thrice happy are those souls that are brought to Christ, whether it be in a winters night, or in a summers day.

The second #emph[Remedy] against this #emph[Device] #footnote[2 Remedie.] of Satan, is, solemnly to dwel upon these following Scriptures which do clearly evidence, that poor sinners which are not so and so prepared, and qualified to meet with Christ, to receive and embrace the Lord Jesus Christ, may notwithstanding that believe in Christ, and rest and lean upon him for happiness and blessedness, according to the Gospel. Read the first of the #emph[Proverbs,] from #emph[vers.] 20. To the end, and the 11. First verses of the 8. Of the #emph[Proverbs,] and the six first verses of the 9. Of the #emph[Proverbs,] and the 14. First verses of #emph[Ezek. Chap.] 16. And the 3. Of #emph[John] 14, 15, 16, 17, 18. 36. Verses, and the 3. Of the #emph[Revelations, vers.] 15, 16, 17, 18, 19, 20. Here the Lord Jesus Christ stands knocking at the #emph[Laodiceans] door, he would fain have them to sup with him, and that he might sup with them; that is, that they might have intimate communion and fellowship one with another.

Now pray tell me, what preparations or qualifications had these #emph[Laodiceans] to entertain Christ? Surely none; for they were luke-warm, they were neither cold nor hot; they were wretched, and miserable, and poor, and blind, and naked; and yet Christ to show his free grace, and his condescending love, invites the very worst of sinners to open to him, though they were no ways so or so prepared or qualified to entertain him, etc.

The third #emph[Remedy] against this #emph[Device] #footnote[3 Remedie.] of Satan, is, seriously to consider, that the Lord does not in all the Scripture require such and such preparations#footnote[#emph[Rom.] 4. 5. God justifies the ungodly.] & qualifications before men come to Christ, before they believe in Christ, or entertain, or embrace the Lord Jesus Christ. Believing, believing in Christ is the great thing that God presses upon sinners throughout the Scripture, as all know, that know any thing of Scripture.

#emph[Obi.] But does not Christ say, #emph[Come] #footnote[Mat. 11. 28.] #emph[unto me all ye that labour, and are heavy laden, and I will give you rest?] To this I shall give these three Answers.

1\. That though the invitation be to such that #emph[labour and are heavy laden,] yet the promise of giving rest, its made over to coming to believing.

2\. I answer, that all that this Scripture proves and shows, is, that such as labour under sin as under a heavy burden,#footnote[#emph[Math.] 11. 28. opened and cleared.] and that are laden with the guilt of sin, and sense of Gods displeasure, ought to come to Christ for rest; but it doth not prove that only such must come to Christ, nor that all men must be thus burthened, and laden with the sense of their sins, and the wrath of God before they come to Christ. Poor sinners, when they are under the sense of sin, and wrath of God, they are prone to run from creature to creature, and from duty to duty, and from Ordinance to Ordinance, to find rest; and if they could find it in any thing, or creature, Christ should never hear of them. But here the Lord sweetly invites them, and to encourage them, he engages himself to give them rest. #emph[Come] (saith Christ) #emph[and I will give you rest.] I'le not show you #emph[rest,] nor barely tell you of #emph[rest,] but #emph[I will give you rest.] I am faithfulness it self, and cannot lye, #emph[I will give you rest.] I that have the greatest power to give it, the greatest will to give it, the greatest right to give it, #emph[come laden sinners, and I will give you rest.] Rest is the most desireable good, the most suitable good, & to you the greatest good. Come saith Christ, that is, #emph[Believe in me & I will give you rest.] I will give you peace with God, and peace with conscience, I will turn your storm into an everlasting calm: I will give you such rest, that the world can neither give to you, nor take from you.

3\. I answer, no one Scripture speaks out the whole mind of Christ; therefore do but compare this one Scripture with those several Scriptures that are laid down in the second #emph[Remedy] last mentioned, and it will clearly appear, that though men are not thus and thus burdened and laden with their sins, and filled with horror and terrour, if they may come to Christ, they may receive and embrace the Lord Jesus Christ.

The 4. And last #emph[Remedy] against this#footnote[4 Remedie.] #emph[Device] of Satan is, to consider, that all that trouble for him, all that sorrow, shame, and mourning, etc. Which is acceptable to God, and delightful to God, & prevalent with God, flows from faith in Christ, as the stream doth from the fountain, as the branch doth from the root, as the effect doth from the cause. #emph[Zech. 12. 10. They shall look on] #footnote[Zach. 12. 10.] #emph[him whom they have pierced, and they shall mourn for him.] All Gospel-mourning#footnote[Rom. 14. 23.] flows from believing; they shall first look, and then mourn. All that know any thing, knows this, #emph[that what ever is not of faith is sin.] Till men have faith in Christ, their best services are but glorious sins.
