== The Epistle Dedicatory

Beloved in our dearest Lord;

Christ, the Scripture, your own hearts, and Satan's devices, are the four prime things that should be first and most studied & searched; if any cast off the study of these, they cannot be safe here, nor happy#footnote[If a Minister had as many eyes as #emph[Argus,] to watch; as many heads as #emph[Typheus] to dispose, and as many hands as #emph[Briareus] to labour, he might find employment enough for them all.] hereafter. ’Tis my work as a Christian, but much more as I am a #emph[watchman,] to do my best, to discover the fulness of Christ, the emptiness of the creature, and the snares of the great deceiver; which I have endeavoured to do (in the following discourse) according to that measure of grace, which I have received from the Lord. God once accepted a handful of meal for a sacrifice; and a gripe of goats' hair for an oblation; and I know that you have not so learned the Father, as to despise the day of small things. Beloved, Satan being fallen from light to darkness, from felicity to misery, from heaven to hell, from an angel to a devil, is so full of malice and envy, that he will leave no means unattempted, whereby he may make all others eternally miserable with himself; he being shut out of heaven, #emph[and shut up under chains of darkness till the judgement of the great day,] makes use of all his power and skill, to bring all the sons of men into the same condition, and condemnation with himself. Satan hath cast such sinful seed into our souls, that now he can no sooner tempt, but we are ready to assent; he can no sooner have a plot upon us, but he makes a conquest of us; if he doth but show men a little of the beauty, and bravery of the world, how ready are they to fall down, and worship him.

What ever sin the heart of man is most prone to, that the devil will help forward. If #emph[David] be proud of#footnote[2 Sam. 24.] his people, Satan will provoke him to number them, that he may be yet prouder. If #emph[Peter] be slavishly#footnote[Matth. 16. ver. 22. 26. ch. 69. ult.] fearful, Satan will put him upon rebuking and denying of Christ, to save his own skin. If #emph[Ahab's] #footnote[1 Kings 22.] prophets be given to flatter, the devil will straightway #emph[become a lying spirit in the mouths of four hundred of them,] and they shall flatter #emph[Ahab] to his ruin. If #emph[Judas] will#footnote[John 13. 2.] be a traitor, Satan will quickly enter into his heart, and make him sell his master for money, which some heathens would never have done. If #emph[Ananias] will lie#footnote[Acts 5. 3.] for advantage, #emph[Satan will fill his heart that he may lie] (with a witness) #emph[to the Holy Ghost.] Satan loves to sail with the wind, and to suit men's temptations to their conditions, and inclinations; if they be in prosperity, he will tempt them to deny God; if they be in adversity, he will tempt them to distrust#footnote[Prov. 30. v. 9.] God; if their knowledge be weak, he will tempt them to have low thoughts of God; if their conscience be tender, he will tempt to scrupulosity; if large, to carnal security; if we be bold-spirited, he will tempt to presumption; if timorous, to desperation; if flexible, to inconstancy, if stiff, to impenitency, etc.

From the power, malice, and skill of Satan, doth proceed all the soul killing plots, devices, stratagems, and machinations, that be in the world; Several devices he hath to draw souls to sin, and several plots he hath to keep souls from all holy, and heavenly services; and several stratagems he hath, to keep souls in a mourning, staggering, doubting, and questioning condition. He hath several devices, to destroy the great, and honourable, the wise, and learned; the blind, and ignorant; the rich, and the poor; the real, and the nominal saints, etc. One while he will refrain from tempting, that we may think our selves secure, and neglect our watch; another while he will seem to fly, that he may make us proud of the victory; one while he will fix men's eyes more on others' sins, than their own, that he may puff them; another while he will fix their eyes more on others' graces than their own, that he may overwhelm them etc. A man may as well tell the stars, and number the sands of the sea, as reckon up all the devices of Satan; yet those which are most considerable, and by which he doth most mischief to the precious souls of men, are in the following treatise discovered, and the #emph[remedies] against them prescribed, etc.

Beloved, I think it necessary to give you, and the world a faithful account of the reasons, moving me to appear in print, in these days, wherein we may say there was never more writing, and yet never less practising, and they are these that follow, etc.

First, because Satan hath a#footnote[1\. Reason.] greater influence upon men, and higher advantages over men (having the wind and the hill as it were) than they think he hath, and the knowledge of his high advantages is the high way to disappoint him, and to render the soul strong in resisting, and happy in conquering, etc.

Your importunity, and the importunity#footnote[2\. Reason.] of many other precious sons of #emph[Zion] hath after much striving with God, my own heart, and others, made a conquest of me and forced me to do that at last, which at first was not a little contrary to my inclination, and resolution, etc.

The strange opposition that I#footnote[#emph[3\. Reason.] Pirates make the strongest and the hottest oppositions against those vessels that are most richly laden; so doth Satan that arch Pirate against those truths, that have most of God, Christ, and Heaven in them.] met with from Satan, in the study of this following discourse, hath put an edge upon my spirit, knowing that Satan strives mightily, to keep those things from seeing the light, that tend eminently to shake and break his kingdom of darkness, and to lift up the kingdom and glory of the Lord Jesus Christ, in the souls and lives of the children of men, etc.

Its exceeding usefulness to all sorts, ranks, and conditions of men#footnote[4\. Reason.] in the world; here you have salve for every sore, and a plaster for every wound, and a #emph[remedy] against every disease; especially against those, that tend most to the undoing of souls, and to the ruin of the state, etc.

I know not of any one, or#footnote[5\. Reason.] other that have writ of this subject; all that I have ever seen, have only touched upon this string, which hath been no small provocation to me, to attempt to do something this way, that others, that have better heads and hearts, may be the more stirred to improve their talents, in a further discovery of Satan's devices, and in the making known of such choice #emph[remedies,] as may enable the souls of men to triumph over all his plots and stratagems, #emph[etc.]

I have many precious friends in#footnote[6\. Reason.] several countries, who are not a little desirous, that my pen may reach them, now my voice cannot. I have formerly been, by the help of the mighty God of #emph[Jacob,] a weak instrument of good to them, and cannot but hope, and believe, that the Lord will also bless these labours to them, they being (in part) the fruit of their desires, and prayers, #emph[etc.]

Lastly, not knowing how soon#footnote[7\. Reason.] my glass may be out, and how soon I may be cut off by a hand of death, from all opportunities of doing further service for Christ, or your souls in this world, I was willing to sow a little handful of spiritual seed among you; that so, when I put off this earthly tabernacle, my love to you, and that dear remembrance of you, which I have in my soul, may strongly engage your minds and spirits, to make this Book your companion; and under all external, or internal changes, to make use of this heavenly salve, which I hope, will by the blessing of the Lord, be as effectual for the healing of all your wounds, as their looking up to the brazen serpent, was effectual to heal theirs that were bit, and stung with fiery serpents. I shall leave this Book with you, as a legacy of my dearest love, desiring the Lord to make it a far greater, and sweeter legacy, than all those carnal legacies are, that are left by the high and mighty ones of the earth, to their nearest and dearest relations, #emph[etc.]

Beloved, I would not have affection carry my pen too much beyond my intention; therefore only give me leave to signify my desires for you, and my desires to you; and I shall draw to a close.

My desires for you are, #emph[That he would grant you according to the riches] #footnote[Ephes. 3.] #emph[of his glory, to be strengthened with might by his Spirit in the inner] #footnote[Vers. 17.] #emph[man. That Christ may dwell in your hearts by faith, that ye being rooted and grounded in love; May be able to] #footnote[Vers. 18.] #emph[comprehend with all saints, what is the breadth, and length, and depth,] #footnote[Vers. 19.] #emph[and height: And to know the love of Christ that passeth knowledge; That ye might be filled with all the fullness of God. And that ye might walk] #footnote[Colos. 1. 10.] #emph[worthy of the Lord unto all pleasing, being fruitful in every good work, and increased in the knowledge of God, Strengthened with all might, according] #footnote[Vers. 11.] #emph[to his glorious power, unto all patience, and long-suffering with joyfulness. That ye do no evil. That] #footnote[2 Cor. 13. 7.] #emph[your love may abound yet more and more in Knowledge, and in all judgement.] #footnote[Phil. 1. 9.] #emph[That ye may approve things that are excellent, that ye may be sincere,] #footnote[Vers. 10.] #emph[and without offence till the day of Christ. And that our God would] #footnote[2 Thess. 1. 11.] #emph[count you worthy of this calling, and fulfill all the good pleasure of his goodness, and the work of faith with] #footnote[Vers. 12.] #emph[power. That the name of our Lord Jesus Christ may be glorified in you, and ye in him, according to the grace of our God, and the Lord Jesus Christ.] And that you may be eminent in#footnote[Psal. 93. 5.] sanctity; sanctity being #emph[Zion's] glory, that your hearts may be kept upright, your judgements sound, and your lives unblamable. That as you are now my joy, so in the day of Christ you may be my crown; That I may see my labours in your lives, that your conversation may not be earthly, when the things you hear are heavenly; but that it may be as becomes the gospel. That as the fishes which live in the salt Sea, yet are fresh; so you, though you live in an uncharitable world, may yet be charitable and loving. That ye may like the bee, suck honey out of every flower; That ye may shine in a sea of troubles, as the pearl shines in the sky, though it grows in the Sea; That in all your trials you may be like the stone in #emph[Thracia,] that neither burneth in the fire, nor sinketh in the water. That ye may be like the heavens, excellent in substance, and beautiful in appearance; that so you may meet me with joy, in that day, wherein Christ shall say to his Father, #emph[Lo, here am I, and the children that thou hast given me.]

My desires to you are, That you would make it your business to study Christ, his Word, your own hearts, Satan's plots, and eternity, more than ever; that ye would endeavour more to be inwardly sincere, than outwardly glorious; to live, than to have a name to live. That ye would labour with all your might, to be thankful under mercies, and faithful in your places, and humble under divine appearances, and fruitful under precious ordinances; that as your means and mercies are greater than others, so your account before God may not prove worse than others. That ye would pray for me, who am not worthy to be named among the saints, that I may be a precious instrument in the hand of Christ, to bring in many souls unto him, and to build up those that are brought in, in their most holy faith; And that utterance may be given to me, that I may make known all the will of God. That#footnote[2 Cor. 11. 23, 24, 25, 26, 27, 28.] I may be sincere, faithful, frequent, fervent, and constant in the work of the Lord, and that my labour be not in vain in the Lord; That my labours may be accepted of the Lord, and his saints, and I may daily see the travail of my soul, #emph[etc.]

But above all, pray for me, that I may more and more find the power, and sweet of those things upon my own heart, that I give out to you and others; and that my soul be so visited with strength from on high, that I may live up fully, and constantly to those truths that I hold forth to the world; and that I may be both in life and doctrine, a burning and a shining light; That so, when the Lord Jesus shall appear, I may receive a crown of glory, which he shall give to me in that day, and not only to me, but to all that love his appearing, #emph[etc.]

For a close, remember this, that your life is short, your duties many, your assistance great, and your reward sure; therefore faint not, hold on, and hold up in ways of well doing, and heaven shall make amends for all.

I shall now take leave of you, when my heart hath by my hand subscribed that I am,

Your loving pastor under Christ, according to all pastoral affections, and engagements in our dearest Lord. THOMAS BROOKS.
