== 6. Lost Joy

#strong[The Sixth Device that Satan hath to keep a poor soul in a sad, doubting, and questioning condition, is,]

BY suggesting to the soul, that surely his estate is not good, because he cannot joy and rejoice in Christ, as once he could, because he hath lost that comfort and joy that once was in his spirit. Saith Satan, thou knowest the time was, when thy heart was much carried out to joying and rejoicing in Christ; thou doest not forget the time when thy heart used to be full of joy and comfort; but now, how art thou fallen in thy joys and comforts? Therefore thy estate is not good, thou doest but deceive thy self, to think that ever it was good, for surely if it had, thy joy and comfort would have continued. And hereupon the soul is apt to take part with Satan, and say, ’tis even so, I see all is naught, and I have but deceived my own soul, #emph[etc.]

#strong[Now the Remedies against this device of Satan are these that follow.]

The first remedy against this device of Satan, is to consider, that the loss of comfort is a separable adjunct from grace; the soul may be full of holy affections, when ’tis empty of divine consolations. There may be, and often#footnote[Ps. 63. 1, 2, 8. Isa. 50. 10. 7. Mic. 7. 8, 9. Psal. 42. 5.] is true grace, yea, much grace, where there is not a drop of comfort, nor a dram of joy. Comfort is not of the being, but of the well-being of a Christian. God hath not so linked these 2 choice lovers together, but that they may be#footnote[Spiritual joy is a Sun that is often clouded; though it be as precious a flower as most Paradise affords, yet ’tis subject to fade and wither.] put asunder. That wisdom that is from above, will never work a man to reason thus, I have no comfort, therefore I have no grace, I have lost that joy that once I had, therefore my condition is not good, was never good, #emph[etc.] But ’twill enable a man to reason thus, though my comfort is gone, yet the God of my comfort abides; though my joy is lost, yet the seeds of grace remain. The best men's joys are as glass, bright and brittle, and evermore in danger of breaking.

The second remedy against this device of Satan, is, solemnly to consider, that the precious things that thou still enjoyest, are far better than the joys and comforts that thou hast lost. Thy union with Christ, thy communion with Christ, thy son-ship, thy saint-ship, thy heir-ship, thou still enjoyest by Christ, is far better than the comforts thou hast lost by sin; what though thy comforts be gone, yet thy union and communion with Christ remains, though thy comforts be gone; yet thou art a Son, though#footnote[Jer. 31. 18, 19, 20.] a comfortless Son; an heir, though a comfortless heir; a saint, though a comfortless saint. Though the bag of silver (thy comforts) be lost, yet the#footnote[When one objected to #emph[Faninus,] his cheerfulness to Christ's Agony and sadness, he answered, Christ was sad, that I might be merry, he had my sins, and I have his righteousness.] box of jewels (thy union with Christ, thy communion with Christ, thy Sonship, thy saint-ship, thy heir-ship) which thou still enjoyest, is far better than the bag of silver thou hast lost; yea, the least of those precious jewels is more worth, than all the comforts in the world; well, let this be a cordial to comfort thee, a star to lead thee, and a staff to support thee, that thy box of jewels are safe, though thy bag of silver be lost.

The third remedy against this device of Satan, is to consider, that thy condition is no other than what hath been the condition of those precious#footnote[Psal. 51. 12. Psal. 30. 6, 7. Job 23. 6 8 9. 30. 31. Lam. 1. 16. Mat. 27. 46.] souls whose names were written upon the heart of Christ, and who are now at rest in the bosom of Christ. One day you shall have them praising and rejoicing, the next day a mourning & weeping: one day you shall have them a singing,#footnote[Psal. 42. 5.] #emph[The Lord is our portion,] the next day a sighing and expostulating with themselves,#footnote[Lam. 5. 15.] #emph[Why are ye cast down oh our souls? Why is our harp turned to mourning? And our Organ into the voice of them that weep?] etc.

The fourth remedy against this device of Satan, is solemnly to consider, that the causes of joy and comfort are not always the same. Happily thy former joy and comfort did spring from#footnote[The spirit doth not every day make a feast in the soul, he doth not make every day to be a day of wearing the wedding robes.] the witness of the spirit, he bearing witness to thy soul that thy nature was changed, thy sins pardoned, thy soul reconciled, #emph[etc.] Now the Spirit may upon some special occasion, bear witness to the soul, that the heart of God is dearly set upon him, that he loves him with an everlasting love, #emph[etc.] And yet the soul may never enjoy such a testimony all the days of his life again: Though the spirit be a witnessing spirit, it's not his office every day to witness to believers their interest in God, Christ, heaven, #emph[etc.]

Or happily thy former joy and comfort, did spring from the newness and suddenness of the change of thy condition; for a man in one hour to have#footnote[A pardon given unexpectedly into the hand of a malefactor, when he is on the last step of the ladder, ready to be turn'd off, will cause much joy & rejoicing; the newness and suddenness of the change of his condition, will cause his heart to leap and rejoice; yet in process of time much of his joy will be abated, though his life be as dear to him still, as ever it was.] his night turn'd into day, his darkness turn'd into light, his bitter into sweet, God's frowns into smiles, his hatred into love, his hell into a heaven, must greatly joy and comfort him. It cannot but make his heart to leap, and dance in him, who in one hour shall see Satan accusing him, his own heart condemning him, the eternal God frowning upon him, the gates of heaven bar'd against him, all the creation standing armed at the least beck of God, to execute vengeance on him, and the mouth of the infernal pit open to receive him. Now in this hour, for Christ to come to the amazed soul, and say to it, I have trod the Wine-press of my Father's wrath for thee, I have laid down my life a ransom for thee, by my blood I have satisfied my Father's justice, and pacified his anger, and procured his love for thee; by my blood I have purchased the pardon of thy sins, thy freedom from hell, and thy right to heaven, #emph[etc.] Oh! how wonderfully will this cause the soul to leap for joy?

The fifth remedy against this device of Satan, is, to consider, that God will restore and make up the comforts of his people; though thy candle be put out,#footnote[#emph[Hudson] the Martyr deserted at the stake, went from under his chain, and having prayed earnestly, was comforted immediately, and suffered valiantly. So Mr. #emph[Glover,] when he was within sight of the stake, cried out to his friend, he is come, he is come, meaning the comforter that Christ promised to send.] yet God will light it again, and make it burn more light than ever; though thy sun for the present be clouded, yet he that rides upon the clouds, shall scatter those clouds, and cause the sun to shine, and warm thy heart, as in former days, as the Psalmist speaks, #footnote[Ps. 71. 20, 21.] #emph[Thou which hast showed me great and sore troubles, shalt quicken me again, and shalt bring me up again from the depths of the earth. Thou shalt increase my greatness, and comfort me on every side.] God takes away a little comfort, that he may make room in the soul for a greater degree of comfort. This the prophet #emph[Isaiah] sweetly shows, #footnote[Isa. 57. 18.] #emph[I have seen his ways, and will heal him, I will lead him also, and restore comforts unto him, and to his mourners.] Bear up sweetly oh precious soul! Thy storm shall end in a calm; and thy dark night in a sun-shine day; thy mourning shall be turn'd into rejoicing, and the waters of consolation shall be sweeter and higher in thy soul, than#footnote[See also the 126 #emph[Psal. 6. v.] and the 42 #emph[Psal. 7, 8.]] ever; the mercy is surely thine, but the time of giving it is the Lord's: wait but a little, and thou shalt find the Lord comforting thee on every side.
