== 1. Poring on Sin More than on the Saviour

#align(center)[The third thing to be showed, is the several Devices that Satan hath to keep souls in a sad, doubting, questioning, and uncomfortable condition.#footnote[Blessed #emph[Bradford] in one of his Epistles saith thus; O Lord, sometimes me thinks I feel it so with me, as if there were no difference between my heart and the wicked, I have a blind mind, as they, a stout, stubborn, rebellious, hard heart as they, & so he goes on, etc.]]

Though he can never rob a believer of his crown, yet such is his malice and envy, that he will leave no stone unturn'd, no means unattempted to rob them of their comfort, and peace, to make their life a burden, and a hell unto them, to cause them to spend their days in sorrow and mourning, in sighing and complaining, in doubting and questioning; surely we have no interest in Christ, our graces are not true, our hopes are the hopes of hypocrites; our confidence is but presumption; our enjoyments are but delusions, etc.

I shall show you this in some particulars.

#strong[The first Device that Satan hath to keep souls in a sad, doubting, and questioning condition, and so making their life a hell, is,]

BY causing them to be still poring,#footnote[A Christian should wear Christ in his bosom as a flower of delight, for he is a whole paradise of delight; he that minds not Christ more than his sin, can never be thankful and fruitful as he should.] and musing upon sin, to mind their sins more than their Saviour, yea, so to mind their sins, as to forget, yea, to neglect their Saviour, that as the #emph[Psalmist] speaks; #emph[The Lord is not in all their thoughts;] their eyes are so fixed upon their disease, that they cannot see the #emph[remedy,] though it be near; and they do so muse upon their debts, that they have neither mind nor heart to think of their surety, etc.

#strong[Now the first #emph[Remedy] against this device of Satan, is,]

For weak believers to consider, that though Jesus Christ hath not freed them from the presence of sin, yet he#footnote[#emph[Peccata enim non nocent, si non placent,] my sins hurt me not, if they like me not. Sin is like that wild figtree, or Ivy in the wall, cut off stump, body, bough, and branches; yet some strings or other will sprout out again till the wall be pluckt down. #emph[Rom. 8. 1.]] hath freed them from the damnatory power of sin. It's most true, that sin and grace were never born together, neither shall sin and grace die together; yet while a believer breathes in this world, they must live together, they must keep house together. Christ in this life will not free any believer from the presence of any one sin, though he doth free every believer from the damning power of every sin; #emph[There's no condemnation to them that are in Christ Jesus, who walk not after the flesh, but after the spirit.] The law cannot condemn a believer, for Christ hath fulfilled it for him; divine justice cannot condemn him, for that Christ hath satisfied; his sins cannot condemn him, for they in the blood of Christ are pardoned; and his own conscience (upon righteous grounds) cannot condemn him, because Christ, that is greater than his conscience, hath acquitted him, etc.

The second #emph[remedy] against this device of Satan, is, to consider, that though Jesus Christ hath not freed you from the molesting, and vexing power of sin, yet he hath freed you from the reign and#footnote[The primitive Christians chose rather to be thrown to lions without, than left to lusts within #emph[Ad leonem magis quam ad lenonem,] saith #emph[Tertullian. Rom. 6. 14.]] dominion of sin. Thou sayest that sin doth so molest and vex thee, that thou canst not think of God, nor go to God, nor speak with God; oh! But remember, ’tis one thing for sin to molest and vex thee, and another thing for sin to reign, and have dominion over thee. #emph[For sin shall not have dominion over you; for ye are not under the law, but under grace.] Sin may rebel, but it shall never reign in any saint; it fareth with sin in the regenerate, as with those beasts that #emph[Daniel] speaks of, #emph[That had their dominion taken] #footnote[Dan. 7. 12.] #emph[away, yet their lives were prolonged for a season, and a time.]

Now sin reigns in the soul, when the soul willingly and readily obeys it, and subjects to its commands, as subjects do actively obey, and embrace the commands of their prince. The commands#footnote[’Tis a sign that sin hath not gained your consent, but committed a rape upon your souls, when you cry out to God; if the ravished Virgin under the Law cried out, she was guiltless. #emph[Deut.] 22. 27. So when sin plays the Tyrant over the soul, and the soul cries out ’tis guiltless, those sins shall not be charged upon the soul.] of a king are readily embraced and obeyed by his subjects; but the commands of a tyrant are embraced & obeyed unwillingly. All the service that is done to a tyrant, is out of violence, and not out of obedience; A free and willing subjection to the commands of sin, speaks out the soul to be under the reign and dominion of sin; but from this plague, this hell, Christ frees all believers: sin cannot say of a believer, as the #emph[Centurion] said of his servant; #emph[I bid one go, and he goeth, and to another come, and he cometh, and to another do this, and he doth it.] No, the heart of a saint rises against the commands of sin; and when sin would carry his soul to the devil, he hales his sin before the Lord, and cries out for justice, Lord, saith the believing soul, sin plays the tyrant, the devil in me, it would have me to do that which makes against thy holiness, as well as against my happiness; against thy honour and glory, as my comfort & peace; therefore do me justice, thou righteous Judge of heaven and earth, and let this tyrant sin die for it, etc.

The third #emph[remedy] against this device of Satan, is, constantly to keep one eye upon the promises of remission of sin,#footnote[#emph[Isa. 44. 22. Mica 7. 18, 19. Coloss.] 2. 13, 14. The promises of God are a precious book, every leaf drops myrrh and mercy.] as well as the other eye upon the inward operations of sin. This is most certain truth, that God will graciously pardon those sins to his people, that he will not in this life fully subdue in his people. #emph[Paul] prays thrice, #emph[i. e.] often to be delivered from the thorn in the flesh, all he can get is, #emph[my grace is sufficient for thee;] I will graciously pardon that to thee, that I will not conquer in thee,#footnote[Though the weak Christian cannot open, read, and apply them, Christ can, & will apply them to their souls. #emph[Jer. 33. 8. Isa.] 43. 25. מחה An Hebrew participle, & notes a constant, a continued act of God; I, I am he, blotting out thy transgressions, to day, and to morrow, etc.] saith God. #emph[And I will cleanse them from all their iniquity, whereby they have sinned against me, and I will pardon all their iniquities whereby they have sinned against me, and whereby they have transgressed against me. I, even I am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.] Ah! You lamenting souls, that spend your days in sighing and groaning under the sense and burthen of your sins; why do you deal so unkindly with God, and so injuriously with your own souls, as not to cast an eye upon those precious promises of remission of sin, which may bear up, and refresh your spirits in the darkest night, and under the heaviest burden of sin.

The fourth #emph[remedy] against this device of Satan, is, to look upon all your sins, as charged upon the account of Christ, as debts which the Lord Jesus hath fully satisfied; and indeed were there but one farthing of that debt unpaid, that Christ was engaged to satisfy, it would not have stood with the unspotted justice of God, to have let him come into heaven, and sit down at his own right hand; but all our debts by his death being discharged, we are freed, and he is exalted to sit down at the right hand of his Father, which is the top of his glory, and the greatest pledge of our felicity; #emph[For he hath made him to be sin for] #footnote[#emph[2 Cor.] 5. 21. Christ was (#emph[peccatorum maximus]) the greatest of sinners by imputation, and reputation. #emph[Isa. 53. 5, 6.]] #emph[us that knew no sin, that we might be made the righteousness of God in him,] saith the apostle: All our sins were made to meet upon Christ, as that evangelical prophet hath it. #emph[He was wounded for our transgressions, he was bruised for our iniquities, the chastisement of our peace was upon him, and with his stripes we are healed. All we like sheep have gone astray, we have turned every one to his own way, and the Lord hath laid on him the iniquity of us all;] or as the Hebrew hath it, he hath made the iniquity of us all to meet in him. In law we know, that all the debts of the wife are charged upon the Husband; saith the wife to one, and to another, if#footnote[Christ hath the greatest worth and wealth in him, as the worth and value of many pieces of silver is in one piece of gold, so all the excellencies scattered abroad in the creatures, are united to Christ.] I owe you any thing, go to my husband; so may a believer say to the law, and to the justice of God; if I owe you any thing, go to my Christ, who hath undertaken for me; I must not sit down discouraged under the apprehensions of those debts, that Christ to the utmost farthing hath fully satisfied; would it not argue much weakness, I had almost said much madness, for a debtor to sit down discouraged, upon his looking over those debts, that his surety hath readily, freely, and fully satisfied; the sense of his great love should engage a man for#footnote[All the whole volume of perfections, which is spread through Heaven & earth, is epitomized in him.] ever to love, and honour his surety, and to bless that hand that hath paid the debt, and crossed the books, etc. But to sit down discouraged when the debt is satisfied, is a sin that bespeaks repentance, etc.

Christ hath cleared all reckonings betwixt God and us; you remember the Scape-goat, #emph[upon his head all the iniquities] #footnote[Levit. 16. 21.] #emph[of the children of Israel, and all their transgressions in all their sins were confessed] #footnote[Christ is (#emph[Canalis gratiae]) the channel of grace from God.] #emph[and put, and the goat did bear upon him all their iniquities, etc.] Why, the Lord Jesus is that blessed Scape-goat, upon whom all our sins were laid, and who alone hath carried #emph[our sins away into the land of forgetfulness, where they shall never, never be remembered more;] a believer under the guilt of his sin may look the Lord in the face, and sweetly plead thus with him; ’tis true Lord, I owed thee#footnote[The bloods of #emph[Abel,] for so the Hebrew hath it (as if the blood of one #emph[Abel] had so many tongues as drops) cried for vengeance against sin; but the blood of Christ cries louder for the pardon of sin.] much, but thy Son was my ransom, my redemption; his blood was the price, he was my surety, and undertook to answer for my sins; I know thou must be satisfied, and Christ hath satisfied thee to the utmost farthing, not for himself, for what sins had he of his own? But for me, they were my debts that he satisfied for; be pleased to look over the book, and thou shalt find that ’tis crossed by thy own hand, upon this very account that Christ hath suffered, and satisfied for them.

The fifth #emph[remedy] against this device of Satan, is, solemnly to consider of the reasons, why the Lord is pleased to have his people exercised, troubled, and vexed with the operations of sinful corruptions,#footnote[#emph[Augustin] saith, that the first, second, and third virtue of a Christian is humility.] and they are these; partly to keep them humble, and low in their own eyes; and partly to put them upon the use of all divine helps, whereby sin may be subdued and mortified; And partly, that they may live upon Christ for the perfecting the work of sanctification;#footnote[#emph[Lilmod lelammed,] we therefore learn, that we may teach, is a proverb among the #emph[Rabbins.] After the #emph[Trojans] had been wandering, & tossing up and down the Mediterranean Sea; as soon as they espied #emph[Italy,] they cried out with exulting joy, #emph[Italy, Italy:] so will Saints when they come to Heaven.] and partly, to wean them from things below, and to make them heart-sick of their absence from Christ, and to maintain in them bowels of compassion towards others, that are subject to the same infirmities with them; and that they may distinguish between a state of grace, and a state of glory, and that heaven may be more sweet to them in the close. Now doth the Lord upon these weighty reasons suffer his people to be exercised, and molested with the operations of sinful corruptions; oh! Then let no believer speak, write, or conclude bitter things against his own soul, and comforts; because that sin troubles and vexes his righteous soul, etc. But lay his hand upon his mouth, and be silent, because the Lord will have it so, upon such weighty grounds, as the soul is not able to withstand.

The sixth #emph[remedy] against this device of Satan, is, solemnly to consider, that believers must repent for their being#footnote[God never gave a Believer a new heart, that it should always lie a bleeding, and that it should always be rent and torn in pieces with discouragements.] discouraged by their sins. Their being discouraged by their sins will cost them many a prayer, many a tear, and many a groan: And that, because their discouragements under sin flows from ignorance and unbelief; it springs from their ignorance of the riches, freeness, fulness, and everlastingness of God's love; and from their ignorance of the power, glory, sufficiency, and efficacy of the death and sufferings of the Lord Jesus Christ: And from their ignorance of the worth, glory, fulness, largeness, and completeness of the righteousness of Jesus Christ: And from their ignorance of that real, close, spiritual, glorious, and inseparable union that is betwixt Christ, and their precious soul: Ah! Did precious souls know, and believe the truth of these things, as they should, they would not sit down dejected, and over-whelmed under the sense and operations of sin, etc.
