== 2. False Definitions of Grace

#strong[The second #emph[Device] that Satan#footnote[2 Device.] hath to keep souls in a sad, doubting, and questioning condition, is,]

BY working them to make false definitions of their graces: Satan knows, that as false definitions of sin wrong the soul one way, so false definitions of grace wrong the soul another way.

I will instance only in faith; oh! How doth Satan labour might and main to work men to make false definitions of faith; Some he works to define faith too high, as that it is a full assurance of the love of God to a mans soul in particular, or a full persuasion of the pardon, and remission of a mans own sins in particular; saith Satan, what dost thou talk of faith? Faith is an assurance of the love of God, and of the pardon of sin, and this thou hast not; thou knowest thou art far off from this, therefore thou hast no faith; and by drawing men to make such a false definition of faith, he keeps them in a sad, doubting, and questioning condition, and makes them spend their days in sorrow and sighing, so that tears are their drink, and sorrow is their meat, and sighing is their work all the day long, etc.

The Philosophers say there are eight d•grees of heat; we discern three; now i• a m•n should define heat only by the highest degree, then all other degrees will be cast out from being heat: so if men shall define fai•h only by the highest degrees, by assurance of the love of God, and of the pardon of his sins in particular, what will become of lesser degrees of faith?

If a man should define a man to be a living man, only by the highest and st•ongest demonstrations of life, as laughing, leaping, running, working, walking, etc. Would not many thousands that groan under internal, and external weaknesses, and that cannot laugh, nor leap, nor run, nor work, nor walk, be found dead men by such a definition, that yet we know to be alive; 'tis so here, and you know how to apply it, etc.

#strong[Now the Remedies against this device of Satan are these that follow.]

The first #emph[Remedy] against this Device#footnote[1\. Remedy.] of Satan, is, solemnly •o consider, that there may be true faith, yea, g•eat measures of faith, where there is no assurance. The #emph[Canaanite] woman in the Gospel had strong faith, yet no assurance that we read of. #emph[These things have I written unto you] (saith #emph[John) that believe on the name of the Son of God, that ye may know, that ye have eternal life,, and that ye may beleeve on the name of the Son of God;] In these words you see that they did believe, and had eternal life, in respect of the purpose and promise of God, and in respect of the seeds, and beginnings of it in their souls; and in respect of Christ their head, who sits in Heaven as a public person, representing all his chosen ones; #emph[Who hath raised us up together,] #footnote[Ephes. 2. 6.] #emph[and made us sit together in heavenly places in Christ Jesus;] and yet they did not know that they had eternal life. 'tis one thing to have a right to heaven, and another thing to know it; 'tis one thing to be beloved, and another thing for a man to know that he is beloved. 'tis one thing for God to write a mans name in the book of life, and another thing for God to tell a man, that his name is written in the book of life, and to say to him, #emph[rejoyce, because thy name is written in heaven.]

So #emph[Paul: In whom ye also trusted after] #footnote[#emph[Ephes] 1. 13. So those in •ha• #emph[Isa.] 50. 10 had faith, though they had no assurance. #emph[Mica 7. 8, 9.]] #emph[ye heard the word of truth, the Gospel of your salvation, in whom also after that ye believed, ye were sealed with that holy spirit of promise.]

So #emph[Micha, Rejoyce not against me oh my enemy, when I shall fall, I shall rise; when I shall sit in darkness, the Lord shall be a light unto me. I will bear the indignation of the Lord, because I have sinned, etc. Or the sad countenance of God,] as the Hebrew hath it. This soul had no assurance, for he sits in darkness, and was under the sad countenance of God, and yet had strong faith: As appears in those words, #emph[when I fall, I shall arise: when I sit in darkness, the Lord shall be a light unto me.] He will bring me forth to the light, and I shall behold his righteousness, and let this suffice for the first answer.

The second #emph[Remedy] against this Device#footnote[2\. Remedie.] of Satan, is, solemnly to consider, that God in the Scriptures doth define#footnote[John 1. 12.] faith otherwise; God defines faith to be a ••ceiving of Christ; #emph[As many as received him, to them he gave this priviledge to be] #footnote[Act. 11. 23.] #emph[the sons of God, to as many as beleeved on his name;] to be a cleaving of the soul unto God, though no joy but afflictions attend the soul. Yea, the Lord defines faith to be a coming to God in Christ,#footnote[Mat. 11. 28. John 6. 37. Heb. 7. 25. 26. Isa. 3. 4, etc.] and often to a resting, and staying, or rouling of the soul upon Christ. 'tis safest, and sweetest to define as God defines, both vices and graces; this is the only way to settle the soul, and to secure it against all the wiles of men and devills, who labour by false definitions of grace to keep precious souls in a doubting, staggering, and languishing condition, and so make their lives a burden, a hell unto them.

The third #emph[Remedy] against this device#footnote[3 Remedie.] of Satan, is, seriously to consider this, that there may be true faith, where there#footnote[Mat. 6. 30. chap. 14. 31. & chap. 16. 8.] is much doubtings; witness those frequent sayings of Christ to his Disciples, #emph[Why are ye afraid oh ye of little faith?] #footnote[Luke 12. 28.] Persons may be truly believing, who nevertheless are sometimes doubting; in the same persons (that the fore-mentioned Scriptures speak of) you may see their faith commended, and their doubts condemned, which doth necessarily suppose a presence of both.

The fourth #emph[Remedy] against this device#footnote[4 Remedy.] of Satan, is, solemnly to consider, that assurance is an effect of faith; therefore it cannot be faith. The cause cannot be the effect, nor the root the fruit; as the effect slows from the cause, the fruit from the root, the stream from the fountain, so doth the assurance flow from faith; this truth I shall make good thus.

The assurance of our salvation, and pardon of sin doth primarily arise from the witness of the spirit of God, that#footnote[Ephes. 1. 13. Gal. 5. 6.] we are the children of God: And the spirit never witnesseth this, till we are beleevers; #emph[for we are sons by faith in] #footnote[Gal. 4 6.] #emph[Christ Jesus:] therefore assurance is not faith, but follows it, as the effect follows the cause.

Again, no man can be assured, and persuaded of his salvation, till he be united to Christ, till he be ingrafted into Christ; and a man cannot be ingrafted into Christ, till he hath faith; he must first be ingrafted into Christ by faith, before he can have assurance of his salvation, which doth clearly evidence, that assurance is not faith, but an effect and fruit of faith, etc.

Again, faith cannot be lost, but assurance may; therefore assurance is not faith. Though assurance be a precious#footnote[Psal. 51. 12. Psal. 30. 6, 7.] flower in the garden of a Saint, and is more infinitely sweet, and delightful to the soul, then all outward comforts,#footnote[Cant. 5. 6. Isa. 8. 17.] and contents; yet 'tis but a flower that is subject to fade, and to loose its freshness,#footnote[There is many thousand precious souls, of whom this world is not worthy, that have the •aith of reliance, & yet want assurance, and the effects of it; as high joy, glorious peace, and vehement longings after the coming of Christ.] and beauty, as Saints by sad experience find, etc.

Again, a man must first have faith, before he can have assurance, therefore assurance is not faith; and that a man must first have faith, before he can have assurance, is clear; by this a man must first be saved, before he can be assured of his salvation, for he cannot be assured of that which is not; and a man must first have a saving faith, before he can be saved by faith; for he cannot be saved by that which he hath not; therefore a man must first have faith, before he can have assurance, and so it roundly follows, that assurance is not faith, etc.
