== 3. Cross Providences

#strong[The third Device that Satan hath to keep the soul in a sad, doubting, and questioning condition, is,]

BY working the soul to make false#footnote[Psal. 77. 7. 11. Psal. 88. 1. ult. Psal. 73. 2. 23.] inferences from the cross actings of providence; saith Satan, dost thou not see how providence crosses thy prayers, and crosses thy desires, thy tears, thy hopes, thy endeavours; surely, if his love were toward thee, if his soul did delight and take pleasure in thee, he would not deal thus with thee, etc.

#strong[Now the remedies against this Device of Satan are these that follow.]

The first #emph[remedy] against this device of Satan, is, solemnly to consider that many things may be cross to our desires, that are not cross to our good; #emph[Abraham, Jacob, David, Job, Moses, Jeremiah,] #footnote[The #emph[Circumcellians] being not able to withstand the preaching, & writing of #emph[Augustine,] sought his destruction, having beset the way he was to go his visitation, but by God's providence, he missing his way, escaped the danger.] #emph[Jonah, Paul, etc.] Met with many things that were contrary to their desires, and endeavours, that were not contrary to their good, as all know, that have wisely compared their desires and endeavours, and God's actings together. Physic often works contrary to the patient's desires, when it doth not work contrary to their good. I remember a story of a godly man, who had a great desire to go to #emph[France,] and as he was going to take shipping, he broke his leg, and it pleased providence so to order it, that the ship that he should have gone in, at that very same time was cast away, and not a man saved, and so by breaking a bone, his life was saved. Though providence did work cross to his desires, yet it did not work cross to his good, etc.

The second #emph[remedy] against this device of Satan, is, solemnly to consider, that the hand of God may be against a man, when the love and heart of God is much set upon a man; No man can conclude how the heart of God stands by his hand. The hand of God was against #emph[Ephraim,] and yet his love, his heart was#footnote[#emph[Jer.] 31. 18, 19, 20. God's providential hand may be with persons, when his heart is set against them; God's providential hand was for a time with #emph[Saul, Haman, Ashur,] & #emph[Jehu,] and yet his heart was set against them. No man knoweth love or hatred by all that is before them. #emph[Eccles. 9. 1, 2.]] dearly set upon #emph[Ephraim. I have surely heard Ephraim bemoaning himself thus; thou hast chastised me, and I was chastised as a bullock unaccustomed to the yoke: turn thou me, and I shall be turned, for thou art the Lord my God. Surely after that I was turned, I repented; and after that I was instructed, I smote upon my thigh; I was ashamed, yea, even confounded, because I did bear the reproach of my youth. Ephraim is my dear son, he is a pleasant child; for since I spake against him, I do earnestly remember him still: therefore my bowels are troubled for him, I will surely have mercy upon him, saith the Lord.]

God can look sourly, and chide bitterly, and strike heavily, even where, and when he loves dearly. The hand of God was very much against #emph[Job,] and yet his love, his heart was very much set upon #emph[Job,] as you may see by comparing the 2. first chap. of #emph[Job] with the two last. The hand of God was sore against #emph[David,] and #emph[Jonah,] when his heart was much set upon them. He that shall conclude, that the heart of God is against those that his hand is against, will condemn the generation of the just, whom God unjustly would not have condemned.

The third #emph[remedy] against this device of Satan, is, to consider, that all the cross providences that befall the saints, are but in order to some noble good, that God doth intend to confer upon them. Providence wrought cross to #emph[David's] desire, in taking away the child sinfully begotten, but yet not cross to a more noble good; for was it not far better for #emph[David] to have such a legitimate heir as #emph[Solomon] was, than that a bastard should wear the crown, and sway the scepter?

#emph[Joseph] you know, was sold into a far country by the envy and malice of his brethren, and afterwards imprisoned, because he would not be a prisoner to his #emph[Mistress's] lusts; yet all these cross providences did wonderfully conduce to his advancement, and the preservation of his Father's family, which was then the visible church of Christ. It was so ordered by a noble hand of providence, that what they sought to decline, they did promote; #emph[Joseph] was therefore sold by his brethren, that he might not be worshipped, and yet he was therefore worshipped, because he was sold.

#emph[David] was designed to a kingdom; but oh the straits, troubles, and deaths, that he run through, before he feels the weight of the crown; and all this was but in order to the sweetening of his crown, and to the settling of it more firmly and gloriously upon his head; God did so contrive it, that #emph[Jonah's] offence, and those cross actings of his that did attend it, should advantage that end which they seemed most directly#footnote[The motions of divine providence are so dark, so deep, so changeable, that the wisest and noblest souls cannot tell what conclusions to make.] to oppose; #emph[Jonah] he flies to #emph[Tarshish,] then cast into the Sea, then saved by a miracle: Then the mariners, as is very probable, who cast #emph[Jonah] into the Sea, declared to the #emph[Ninevites] what had happened; therefore he must be a man sent of God, and that his threatenings must be believed, and hearkened to, and therefore they must repent, and humble themselves, that the wrath threatened might not be executed, etc.

The fourth #emph[remedy] against this device of Satan, is, seriously to consider, that all the strange, dark, deep, and changeable providences that believers meet with, shall further them in their way to heaven, in their journey to happiness; divine wisdom and love will so order all things here below, that they shall work for the real, internal, and eternal good of them that love him. All the rugged providences that #emph[David] met with, did contribute to the#footnote[#emph[Orosius] speaking of #emph[Valentinian,] saith, he that for Christ's name sake had lost a tribuneship, within a while after succeeded his persecutor in the Empire.] bringing of him to the throne; and all the rugged promises that #emph[Daniel,] and the three children met with, did contribute to their great advancement; So all the rugged providences that believers meet with, they shall all contribute to the lifting up of their souls, above all things below God. As the waters lifted up #emph[Noah's] ark nearer heaven: and as all the stones that were about #emph[Stephen's] ears, did but knock him the closer to Christ, the corner-stone, so all the strange rugged providences that we meet with, they shall raise us nearer heaven, and knock us nearer to Christ, that precious corner-stone, etc.
