== 8. Temptations

#strong[The eighth #emph[Device] that Satan#footnote[8 Device.] hath to keep souls in a doubting, and questioning condition, is,]

BY persuading them that theis estate is not good, their hearts are not upright, their graces are not sound, because they are so followed, vexed, and tormented with 'temptations; ’tis his method, first to vex, and weary the soul with temptations, and then to tempt the soul, that surely ’tis not beloved,#footnote[He may so tempt, as to make a Saint weary of his life. #emph[Job] 10. 1. My soule is weary of my life.] because ’tis so much tempted; and by this stratagem he keeps many precious souls in a sad, doubting, and mourning temper many years, as many of the precious sons of #emph[Sion] have found by woful experience, etc.

#strong[Now the remedies against this Device of Satan are these that follow.]

The first #emph[remedy] against this #emph[device] #footnote[1 Remedie.] of Satan, is, solemnly to consider, that those that have been best, and most beloved, have been most tempted by Satan. Though Satan can never rob a Christian of his crown, yet such is his malice, that he will therefore tempt, that he may spoil them of their comforts; such is his enmity to the Father, that the nearer and dearer any child is to him, the more will Satan trouble him, and vex him with temptations;#footnote[Pirats do not use to set upon poor, empty vessels; and beggars need not feare the thiese; those that have most of God, and most rich in grace, shall be most set upon by Satan, who is the greatest and wisest Pirate in the world.] Christ himself was most near, and most dear, most innocent, and most excellent, and yet none so much tempted as Christ; #emph[David] was dearly beloved, and yet by Satan tempted to number the people; #emph[Job] was highly praised by God himself, and yet much tempted, witness those sad things that fell from his mouth, when he was wet to the skin; #emph[Peter] was much prized by Christ, witness that choice testimony that Christ gave of his faith and happiness, and his showing him his glory in the #emph[Mount,] and that eye of pity that he cast upon him after his fearful fall, etc. And yet tempted by Satan. #emph[And the Lord said,] #footnote[Luke 22. 31, 32.] #emph[Simon, Simon, behold Satan hath desired to have you, that he may sift you as wheat: But I have prayed for thee, that thy faith fail thee not, etc.]

#emph[Paul] had the honour of being exalted as high as high as heaven, and of seeing that glory that could not be expressed; and yet he was no sooner stepped out of heaven, but he is buffeted by Satan, #emph[lest he should be exalted above measure.] If#footnote[2 Cor. 12. 2. 7.] these that were so really, so gloriously, so eminently beloved of God; if these that have lived in heaven, and set their feet upon the stars, have been tempted, let no saints judge themselves not to be beloved, because they are tempted.

It is as natural for saints to be tempted that are dearly beloved, as ’tis for the sun to shine, or a bird to sing; the Eagle complains not of her wings, nor the peacock of his train, nor the nightingale of her voice, because these are natural to them; no more should Sts. Of their temptations, because they are natural to them; #emph[For we wrestle not against] #footnote[Ephes. 6. 12.] #emph[flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.]

The second #emph[remedy] against this #emph[device] #footnote[2 Remedy.] of Satan, is, to consider, that all the temptations that befall the saints, shall be sanctified to them by a hand of love; ah! The choice experiences that the saints get of the power of God, supporting them, of the wisdom of God directing them (so to handle their spiritual weapons, their graces, as not only to resist, but to overcome) of the mercy and goodness of the Lord, pardoning and succouring of them. And therefore saith #emph[Paul, I received the messenger] #footnote[#emph[2 Cor. 12. 7. Vide Bezam, Grotium, & Estium Lather] said there were three things this made a Preacher; Meditation, prayer, and temptation.] #emph[Satan for to buffet me, lest I should be exalted, lest I should be exalted above measure,] ’tis twice in that verse he begins with it, and ends with it; if he had not been buffeted, who knows how his heart would have swelled; he might have been carried higher in conceit, then before he was in his extacy. The school of temptation is a choice school, a school wherein God gives his people the clearest, and the sweetest discoveries of his love; a school wherein God teaches his people to be more frequent, and fervent in duty; when #emph[Paul] was buffeted, then he prayed thrice, that is, frequently, and fervently; A school wherein God teaches his people to be more tender, meek, and compassionate to other poor tempted souls then ever; A school wherein God teaches his people to see a greater evil in sin then ever, and a greater emptiness in the creature then ever, and a greater need of Christ, and free-grace then ever; A school wherein God will teach his people, that all temptations are but his gold-smiths, by which he will try, and refine, and make his people more bright and glorious. The issue of all temptations shall be the good of the saints; as you may see by the temptations that #emph[Adam,] and #emph[Eve,] and Christ, and #emph[David,] and #emph[Job,] and #emph[Peter,] and #emph[Paul] met with. Those hands of power, and love that bring light out of darkness, good out of evil, sweet out of bitter, life out of death, heaven out of hell, will bring much sweet and good to his people, out of all the temptations that come upon them.

The third #emph[remedy] against this #emph[device] #footnote[3 Remedie.] of Satan is, wisely to consider, that no temptations don't hurt nor harm the saints, so long as they are not resisted by them, and prove the greatest affliction that can befall them; ’tis not Satan's tempting, but your assenting; not his enticing, but your yielding, that makes temptations hurtful to your souls; if the soul when ’tis tempted, resists the temptation, and saith with Christ, #emph[get thee behind me Satan;] and with that young convert, #emph[I am not the man that I] #footnote[Ego non sum ego.] #emph[was;] or as #emph[Luther] counsels all men, to answer all temptations with these words (#emph[Christianus sum]) I am a Christian; if a mans temptations be his greatest affliction, then is the temptation no sin upon his soul, though it be a trouble upon his mind: when a soul can look the Lord in the face, and say, ah Lord! I have many outward troubles now upon me, I have lost such and such a near mercy, and such and such dear desirable mercies, and yet thou that knowest the heart, thou knowest that all my crosses and losses do not make so many wounds in my soul, nor fetch so many sighs from my heart, nor tears from my eyes, as those temptations do, that Satan follows my soul with: when ’tis thus with the soul, then temptations are only the souls trouble, they are not the souls sin.

Satan is a malious and envious enemy;#footnote[Sometimes he shewes his malice, by letting those things abide by the soule, as may most vex, and plague the soule, as #emph[Gregory] observes in his leaving of #emph[Jobs] wife, which was not out of his forgetfulness, carelesnesse, or any love, or pity to #emph[Iob,] but to vex, and torment him, etc. and to work him to blaspheme God, despair, and die, etc.] as his names are, so is he; his names are all names of enmity; the #emph[Accuser,] the #emph[Tempter,] the #emph[Destroyer,] the #emph[Devourer,] the #emph[envious Man;] and this malice, and envy of his, he shows sometimes by tempting men to such sins as are quite contrary to the temperature of their bodies, as he did #emph[Vespasian] and #emph[Julian,] men of sweet and excellent natures to be most bloody murderers; and sometimes he shows his malice, by tempting men to such things as shall bring him no honour, nor profit, etc. #emph[Fall down and worship me,] to blasphemy, and atheism, #emph[etc.] The thoughts and first motions whereof cause the beart and the flesh to tremble; And sometimes he shows his malice, by tempting them to those sins, which they have not found their natures prone to, and which they abhor in others, etc.

Now if the soul resists these, and complains of these, and groans and mourns under these, and looks up to the Lord Jesus to be delivered from these, then shall they not be put down to the souls account, but to Satan's, who shall be so much the more tormented, by how much the more the saints have been by him maliciously tempted, etc.

Make present and peremptory resistance against Satan's temptations, bid defiance to the temptation at first sight;#footnote[When #emph[Constantine] the Emperour was told that there was no means to cure his leprosie, but by bathing his body in the blood of Infants, he presently answered (#emph[malo jemper aegrotare quam tali remedio convalescere]) I had rather not be cured, then use such a remedie.] ’tis safe to resist, ’tis dangerous to dispute; #emph[Eve] lost her self, and her posterity, by falling into the lists of dispute, when she should have resisted, and stood upon terms of defiance with Satan; he that would stand in the hour of temptation, must plead with Christ, ’tis written; he that would triumph over temptations, must plead still, ’tis written. Satan is bold and impudent, and if you are not peremptory in your resistance, he will give you fresh onsets. ’tis your greatest honour, and your highest wisdom, peremptorily to with-stand the beginnings of a temptation, for an after remedy comes often too late.

Mistress #emph[Katherine Bretterge,] once, after a great conflict with Satan, said, #emph[Reason not with me, I am but a weak woman; if thou hast any thing to say, say it to my Christ, he is my Advocate, my strength, and my redeemer, and he shall plead for me.]

Men must not seek to resist Satan's craft with craft (#emph[sed per apertum martem]) but by open defiance; he shoots with Satan in his own bow; who thinks by disputing and reasoning to put him off. As soon as a temptation shows its face, say to the temptation, as #emph[Ephraim] to his idols; #emph[get you hence, what have I any] #footnote[Hosea 14.] #emph[more to do with you?] Oh! Say to the temptation, as #emph[David] said to the sons of #emph[Zerviah; What have I to do with you?] #footnote[2 Sam. 16. 10.] You will be too hard for me. He that doth thus resist temptations, shall never be undone by temptation, etc.

Make strong and constant resistance#footnote[I have read of one who being tempted with offers of money to desert Christ, gave this excellent answer, let not any man think, that he will embrace other mens goods to forsake Christ, who hath forsaken his own proper goods to follow Christ.] against Satan's temptations, make resistance against temptations by arguments drawn from the honour of God, the love of God, your union and communion with God; and from the blood of Christ, the death of Christ, the kindness of Christ, the intercession of Christ, and the glory of Christ; and from the voice of the Spirit, the counsel of the Spirit, the comforts of the Spirit, the presence of the Spirit, the seal of the Spirit, the whisperings of the Spirit, the commands of the Spirit, the assistance of the Spirit, the witness of the Spirit; and from the glory of heaven, the excellency of grace, the beauty of holiness, the worth of the soul, and the vildness or bitterness, and evil of sin, the least sin being a greater evil, then the greatest temptation in the world.

And look that you make constant resistance, as well as strong resistance; be constant in arms, Satan will come on with new temptations; when old#footnote[#emph[Luke] 4. 14. And when the Devil had ended all the temptation, he departed from him for a season. Christ had no rest untill he was exactly tried with all kinds of temtations. #emph[Calvin.]] ones are too weak in a calm, prepare for a storm; the temper is restless, impudent, and subtile; he will suit his temptations to your constitutions, and inclinations; Satan loves to sail with the wind; if your knowledge be weak, he will tempt you to error; if your consciences be tender, he will tempt you to scrupulosity, and too much preciseness, as to do nothing but hear, pray, read, etc. If your consciences be wide and large, he will tempt you to carnal security; if you are bold spirited, he will tempt you to presumption; if timorous, to desperation; if flexible, to inconstancy; if proud and stiff, to gross folly, therefore still fit for fresh assaults; make one victory a step to another. When you have overcome a temptation, take heed of unbending your bow, and look well to it, that your bow be always bent, and that it remains in strength; when you have overcome one temptation, you must Be ready to enter the list with another; as distrust (in some sense) is the mother of safety, so security is the gate of danger; a man had need to fear this most of all, that he fears not all; if Satan be always a roaring, we should be always a watching, and resisting of him; and certainly, he that makes strong and constant resistance of Satan's temptations, shall in the end get above his temptations, and for the present is secure enough from being ruin'd by his temptations, #emph[etc.]

For a close of this, remember that tis#footnote[He that will yeeld to sin, to be rid of temptation, will be so much the more tempted, and the lesse able to withstand temptations.] dangerous, to yield to the least sin, to be rid of the greatest temptation. To take this course were, as if a man should think to wash himself clean in ink; or as if a man should exchange a light cross made of paper, for an iron cross which is heavy, toilsome, and bloody, the least sin set home upon the conscience, will more, wound, vex, and oppress the soul, then all the temptations in the world can; therefore never yield to the least sin, to be rid of the greatest temptation. #emph[Sidonius Apolinaris] relateth, how a certain man named #emph[Maximus,] arriving at the top of honour, by indirect means, was the first day very much wearied, and fetching a deep sigh, said, #emph[Oh Damocles!] How happy do I esteem thee, for having been a King but the space of a dinner, I have been one a wholeday, and can bear it no longer. I will leave you to make the application.
