== 8. Resting in Performances

#strong[The eighth #emph[Device] that Satan hath to keep souls from religious services, from holy performances, is,]

BY working them to rest in their performances, to rest in prayer, and to rest in hearing, reading, and the communion#footnote[Isa. 58. 1, 2, 3. Zech. 7. 4, 5, 6. Mat 6. 2. Rom. 17.] of saints, etc. And when Satan hath drawn the soul to rest upon the service done; then he will help the soul to reason thus; why, thou wert as good never pray, as to pray, and rest in prayer; as good never hear, as to hear, and rest in hearing; as good never be in the communion of saints, as to rest in the communion of saints; and by this device he stops many souls in their heavenly race, and takes off poor souls from those services that should be their joy and crown.

#strong[Now the Remedies against this device of Satan are these that follow.]

The first #emph[remedy] against this device of Satan, is, to dwell much upon the imperfections, and weaknesses that#footnote[Pride and high confidence is most apt to creep in upon duties well done, saith one.] do attend your choicest services; oh the spots! The blots! The blemishes, that are to be seen upon the face of our fairest duties! When thou hast done all thou canst, thou hast need to close up all with this; #emph[Oh! Enter not into judgement with thy servant oh Lord;] for the weaknesses that cleave to my best services, we may all#footnote[Isa. 64. 6.] say with the church; #emph[All our righteousness are as a menstruous clothe.] If God should be strict to mark what is done amiss in our best actions, we were undone. Oh! The water that is mingled with our wine, the dross that cleaves unto our gold.

The second #emph[remedy] against this device of Satan, is, to consider the impotency, and inability of any of your best services, divinely to comfort, refresh, and bear your souls up from fainting, and sinking in the days of troubles, when darkness is round about you; when God shall say to you, as he did#footnote[10\. 14.] once to the #emph[Israelites, Go, and cry unto the gods that you have chosen, let them save you in the time of your tribulation:] So when God shall say in the day of your troubles, go to your prayers, to your hearing, and to your fasting, etc. And see, if they can help you, if they can support you, if they can deliver you; if God in that day doth but with-hold the influence of his grace from thee, thy former services will be but poor cordialls to comfort thee; and then thou must, and wilt cry out, oh! None but Christ, none#footnote[#emph[Omne bonum in summo bono,] all good is in the chiefest good. #emph[Nec Christus nec coelum patitur hyperbolen.]] but Christ; oh! My prayers are not Christ, my hearing is not Christ, my fasting is not Christ, etc. Oh! One smile of Christ, one glimpse of Christ, one good word from Christ, on nod of love from Christ in the day of trouble and darkness, will more revive, and refresh the soul, then all your former services, in which your souls rested, as if they were the bosom of Christ, which should be the only center of our souls. Christ is the crown of crowns, the glory of glories, and the heaven of heaven.

The third #emph[remedy] against this device of Satan, is, solemnly to consider, that good things rested upon, will as certainly undo us, and everlastingly destroy us, as the greatest enormities that can be committed by us; those souls that after they have done all, do not look up so high as a Christ, and rest, and center alone in Christ, laying down their services at the foot-stool of Christ, must lie down in sorrow, their bed is prepared for them in hell. #emph[Behold, all] #footnote[Isa. 50. ult.] #emph[ye that kindle a fire, and compass your selves with the sparks, and walk in the light of your fire, and in the sparks that ye have kindled, this ye shall have at mine hand, ye shall lye down in sorrow;] Is it good dwelling with everlasting burnings? With a devouring fire? If it be, why then rest in your duties still; if otherwise, then see that you center only in the bosom of Christ.

The fourth and last #emph[remedy] against this device of Satan, is, to dwell much upon the necessity and excellency of that resting place that God hath provided for you, above all other resting places; himself is your resting place, his free mercy and love is your resting place; the pure, glorious, matchless, and spotless righteousness of Christ is your resting place; ah! ’tis sadd to think, that most men have forgotten their resting place, as the Lord complains; #emph[My people have been as lost sheep, their shepherds have caused them] #footnote[Jer. 50. 6.] #emph[to go astray, and have turned them away to the mountains, they have gone from mountain to hill and forgotten their resting place.] So poor souls that see not the excellency of that resting place that God hath appointed for their souls to lye down in; they wander ftom mountain to hill, from one duty to another, and here they will rest, and there they will rest; but souls that see the excellency of that resting place that God hath provided for them, they will say, farewell prayer, farewell hearing, farewell fasting, etc. I will rest no more in you, but now will rest only in the bosom of Christ, the love of Christ, the righteousness of Christ.
