== 7. Vain Thoughts in Duty

#strong[The seventh #emph[Device] that Satan hath to keep souls from holy and heavenly services, is,]

BY casting in a multitude of vain thoughts, whilst the soul is in seeking of God, or in waiting on God, and by this device he hath cooled some men's spirits in heavenly services, and taken off (at least for a time) many precious#footnote[#emph[Vellem servire Domine sed cogitationes non patiuntur,] Lord now how fain would I serve thee, & vain thoughts will not suffer me.] souls from religious performances. I have no heart to hear, nor no heart to pray, nor no delight in reading, nor in the society of the saints, etc. Satan doth so dog, and follow my soul, and is still a casting in such a multitude of vain thoughts concerning God, the world, and my own soul, etc. That I even tremble to think of waiting upon God in any religious service; oh! The vain thoughts that Satan casts in, do so distaste my soul, and so grieve, vex, perplex, and distract my soul, that they even make me weary of holy duties, yea, of my very life; oh! I cannot be so raised and ravished, so heated and melted, so quickened and enlarged, so comforted and refreshed as I should be, as I might be, and as I would be in religious services, by reason of that multitude of vain thoughts that Satan is injecting, or casting into my soul, etc.

#strong[Now the Remedies against this device of Satan are these that follow.]

The first #emph[remedy] against this device#footnote[When #emph[Pompey] could not keep his soldiers in the camp by persuasion, he cast himself all along in the narrow passage that lead out of it, and then bid them go if you will, but you shall first trample upon your General, and the thoughts of this overcame them; you are wise, & know how to apply it to the point in hand.] of Satan, is, to have your hearts strongly affected with the greatness, holiness, Majesty, and glory of that God, before whom you stand, and with whom your souls do converse in religious services; Oh! Let your souls be greatly affected with the presence, purity, and majesty of that God before whom thou standest. A man would be afraid of playing with a feather, when he is speaking to a King; ah! When men have poor, low, light, slight, etc. Thoughts of God, in their drawing near to God, they tempt the devil to bestir himself, and to cast in a multitude of vain thoughts to disturb and distract the soul in its waiting on God. There is nothing that will contribute so much to the keeping out of vain thoughts, as to look upon God as an omniscient God, an omnipresent God, an omnipotent God, a God full of all glorious perfections; a God, whose Majesty, purity, and glory will not suffer him to behold the least iniquity. The reason why the blessed saints, and glorious angels in heaven have not so much as one vain thought, is, because they are greatly affected with the greatness, holiness, majesty, purity, and glory of God.

The second #emph[remedy] against this device of Satan, is, to be peremptory in religious services, notwithstanding all those wandering thoughts the soul#footnote[It is a rule in the civil Law, (#emph[nec videtur actum, siquid supersit quod agatur]) nothing seems to be done, if there remains ought to be done.] is troubled with. This will be a sweet help against them for the soul to be resolute in waiting on God, whether it be troubled with vain thoughts, or not; to say, well, I will pray still, and hear still, and meditate still, and keep fellowship with the saints still; many precious souls can say from experience, that when their souls have been peremptory in their waiting on God, that Satan hath left them, and hath not been so busy in vexing their souls with vain thoughts; when Satan perceives that all#footnote[#emph[Si dixisti suffisit periisti,] if once thou sayest ’tis enough, thou art undone, saith #emph[Augustin.]] those trifling vain thoughts that he casts into the soul, do but vex the soul into greater diligence, carefulness, watchfulness, and peremptoriness in holy and heavenly services, and that the soul looses nothing of his zeal, piety, and devotion, but doubles his care, diligence, and earnestness; he often ceases to interpose his triflles, & vain thoughts as he ceased to tempt Christ, when Christ was peremptory in resisting his temptations.

The third #emph[remedy] against this device#footnote[3\. Remedy.] of Satan, is, to consider this, that those vain and trifling thoughts that are cast#footnote[’tis not Satan's casting in of vain thoughts that can keep mercy from the soul, or undo the soul, but the lodging, and cherishing of vain thoughts; oh #emph[Jerusalem!] how long shall vain thoughts lodg within thee (#emph[Jer 4. 14.) Heb.] in the midst of thee; they pass through the best hearts, they are lodged and cherished only in the worst hearts.] into our souls, when we are waiting upon God in this or that religious service, if they are not cherished, and indulged, but abhorred, resisted, and disclaimed; they are not sins upon our souls, though they may be troubles to our minds, they shall not be put upon our accounts, nor keep mercies and blessings from being enjoyed by us; when a soul in uprightness can look God in the face, and say, Lord, when I approach near unto thee, there be a world of vain thoughts crowd in upon me, that do disturb my soul, and weaken my faith, and lessen my comfort, and spiritual strength; oh! These are my clog, my burden, my torment, my hell; oh! Do justice upon these; free me from these that I may serve thee with more freeness, singleness, spiritualness, and sweetness of spirit. These thoughts may vex that soul, but they shall not harm that soul, nor keep a blessing from that soul; If vain thoughts resisted and lamented, could stop the current of mercy, and render a soul unhappy, there would be none on earth that should ever taste of mercy, or be everlastingly happy, etc.

The fourth #emph[remedy] against this device of Satan, is, solemnly to consider, that watching against sinful thoughts, resisting of sinful thoughts, lamenting and weeping over sinful thoughts, carries#footnote[#emph[Psal.] 139. 23. Thoughts are the first born, the blossoms of the soul, the beginning of our strength, whether for good or evil, and they are the greatest evidence for, or against a man that can be.] with it the sweetest, and strongest evidence of the truth, and power of grace, and of the sincerity of your hearts, and is the readiest and the surest way to be rid of them; many low and carnal considerations may work men to watch their words, their lives, their actions; As hope of gain, or to please friends, or to get a name in the world, and many other such like considerations; oh! But to watch our thoughts, to weep and lament over them, etc. This must needs be from some noble, spiritual, and internal principle, as love to God, a holy fear of God, a holy care and delight to please the Lord, etc. The schools do well observe, that outward sins are of greater#footnote[Majoris infamiae. Majoris reatus.] infamy; but inward heart sins are of greater guilt, as we see in the devils. There is nothing that speaks out a man to be thoroughly, and kindly wrought upon, as his having his thoughts to be#footnote[2 Cor. 10. 4, 5.] brought into obedience, as the apostle speaks, grace is grown up to a very great height in that soul, where it prevails, to the subduing of those vain thoughts that walk up and down in the the soul; well, though you cannot be#footnote[#emph[Psal. 139. 2. Isa. 59. 7. ch. 66. 18. Mat. 9. 4. ch. 12. 25. Zeno] a wise heathen affirmed, that God even beheld the thoughts, #emph[Mat. 15. 15, 16, 17, 18, 19.]] rid of them, yet make resistance and opposition against the first risings of them; when sinful thoughts arise, then think thus; the Lord takes notice of these thoughts, #emph[he knows them afar off,] as the #emph[Psalmist] speaks; he knew #emph[Herod's] bloody thoughts, and #emph[Judas] his betraying thoughts, and the #emph[Pharisees] cruel and blasphemous thoughts afar off; oh! Think thus, all these sinful thoughts, they defile and pollute the soul, they deface and spoil much of the inward beauty, and glory of the soul; if I commit this or that sin, to which my thoughts incline me, then either I must#footnote[Tears in stead of Gems were the ornaments of #emph[Davids] bed, when he had sinned, & so they must be thine, or else thou must lie down in a bed of sorrow forever.] repent, or not repent; if I repent, it will cost me more grief, sorrow, shame, heart-breaking, and soul-bleeding, before my conscience will be quieted, divine justice pacified, my comfort and joy restored, my evidences cleared, and my pardon in the court of conscience sealed, then the imagined profit, or seeming sensual pleasure can be worth; #emph[What fruit had you in those things whereof you are now ashamed?]

If I never repent, oh then my sinful#footnote[Inward bleeding kils many a man; so will sinful thoughts, if not repented of.] thoughts will be the scorpions that will eternally vex me; the rods that will eternally lash me; the thorns that will everlastingly prick me; the dagger that will be eternally a stabbing me; the worm that will be for ever a gnawing me; oh! Therefore watch against them, be constant in resisting them, and in lamenting and weeping over them, and then they shall not hurt thee, though they may for a time trouble thee, and remember this; he that doth this, doth more then the most glistering and blustering hypocrite in the world doth.

The fifth #emph[remedy] against this device#footnote[#emph[5\. Remedy. Ephes.] 3. 19. The words are an hebraism; the Hebrews when they would set out many excellent things, they add the name of God to it, City of God, Cedars of God, wrestlings of God, so here, that ye may be filled with the fulness of God.] of Satan, is, to labour more and more to be filled with the fulness of God, and to be enriched with all spiritual and heavenly things; what's the reason that the angels in heaven have not so much as an idle thought? ’tis because they are filled with the fulness of God; take it for an experienced truth, the more the soul is filled with the fulness of God, and enriched with spiritual and heavenly things, the less room there is in that soul for vain thoughts. The fuller the vessel is of wine, the less room there is for water; Oh! Lay up much of God, of Christ, of precious promises, and choice experiences in your hearts, and then you will be less troubled with vain thoughts; #emph[A good man out of the good treasure] #footnote[Mat. 12. 3.] #emph[of his heart bringeth forth good things.] #footnote[6\. Remedy.]

The sixth #emph[remedy] against this device of Satan, is, to keep up holy and spiritual affections; for such as your affections are, such will be your thoughts; #emph[Oh!] #footnote[Psal. 119. 97. Psal. 139. 8.] #emph[How I love thy law, ’tis my meditation all the day;] what we love most, we most muse upon; #emph[when I awake, I am still with thee.] That which we much like, we shall much mind; them that are frequent in their love to God and his law, will be frequent in thinking of God, and his#footnote[Simile.] law; a child will not forget his mother.

The seventh #emph[remedy] against this device#footnote[#emph[7\. Remedy. 2 Tim.] 2. 4. ἐμπλεκεται, is entangled, it is a comparison which St #emph[Paul] borroweth from the custom of the Roman Empire, wherein soldiers were forbidden to be proctors of other men's causes, to undertake husbandry or Merchandize.] of Satan, is, to avoid multiplicity of wordly business; oh! Let not the world take up your hearts & thoughts at other times; souls that are torn In pieces with the cares of the world, will be always vexed and tormented with vain thoughts in all their approaches to God; vain thoughts will be still crowding in upon him that lives in a crowd of business. The stars which have least circuit, are nearest the pole; and men that are least perplexed with business, are commonly nearest to God.
