== 6. The Example of the World

#strong[The sixth #emph[Device] that Satan hath to keep souls off from religious services, is,]

By presenting before them the examples#footnote[John 4. 12. 7. chap. 48, 49. 1 Cor. 1. 26, 27. Mica 7. 2, 3, 4.] of the greatest part of the world that walk in the ways of their own hearts, and that make light and slight of the ways of the Lord; why saith Satan, do not you see, that the great, and the rich, the noble and the honourable, the learned and the wise, even the greatest number of men never trouble themselves about such and such ways, and why then should you be singular and nice? You were far better do as the most do, etc.

#strong[Now the remedies against this Device of Satan are these that follow.]

The first #emph[remedy] against this device of Satan, is, solemnly to consider of those Scriptures that make directly against following the sinful examples of men; as that in #emph[Exodus, Thou shalt not] #footnote[The way to hell is broad, and well beaten, the way to be undone for ever, is to do as the most do, (#emph[argumentum turpissimum est turba]) the multitude is the weakest and worst argument, saith #emph[Seneca.]] #emph[follow a multitude to do evil, neither shalt thou speak in a cause to decline after many to wrest judgement.] The multitude generally are ignorant, and know not the way of the Lord: therefore they speak evil of that they know not, they are envious, and maliciously bent against the service and way of God, and therefore they cannot speak well of the ways of God. This way is every where spoken against, said they: so in that #emph[Numb. 16. Separate from them, and come out from among them.] So the apostle; #emph[Have no fellowship with the unfruitful works of darkness.] So #emph[Solomon, Enter not into the way] #footnote[Prov. 4. 14. ch 9. v. 6.] #emph[of the wicked, forsake the foolish, and live.] They that walk with the most, shall perish with the most. They that do as the most, shall ere long suffer with the most; they that live as the most, must die with the most, and to hell with the most.

The second #emph[remedy] against this device of Satan, is, seriously to consider, that if you will sin with the multitude, all the angels in heaven, and men on earth cannot keep you from suffering#footnote[Sin and punishment are linked together with chains of adamant of sin; we may say as #emph[Isidor] doth of the serpent (#emph[Tot dolores, quot colores,]) so many colours, so many dolours.] with the multitude; if you will be wicked with them, you must unavoidably be miserable with them; say to thy soul, oh my soul! If thou wilt sin with the multitude, thou must be shut out of heaven with the multitude, thou must be cast down to hell with the multitude, etc. #emph[And I heard another voice from heaven, saying, come out of her my people, that ye be not partakers of her sins, and that ye receive not of her plagues.] Come out in affection, in action, and in habitation; for else the infection of sin will bring upon you the infliction of punishment. So saith the wise man; #emph[He that walketh with wise men shall be wise, but a companion of fools shall be destroyed,] or as the #emph[Hebrew] #footnote[ירוע רוע #emph[a Jeroange,] from #emph[ruange,] to be naught.] hath it, shall be broken in pieces. Multitudes may help thee into sin; yea, one may draw thee into sin, but ’tis not multitudes that can help thee to escape punishments: As you may see in #emph[Moses] and #emph[Aaron,] that were provoked to sin by the multitude; but were shut out of the pleasant land, and fell by a hand of justice as well as others.

The third #emph[remedy] against this device of Satan, is, solemnly to consider the worth and excellency of thy immortal soul. Thy soul is a jewel more worth#footnote[What wise man would fetch gold out of a fiery crucible, hazard his immortal soul (to gain the world) by following a multitude in those steps that lead to the chambers of death and darkness.] than heaven and earth: The loss of thy soul is incomparable, irreparable, and irrecoverable; if that be lost, all is lost, and thou art undone for ever. Is it madness and folly in a man to kill himself for company? And is it not greater madness or folly to break the neck of thy soul, and to damn it for company? Suspect that way wherein thou seest multitudes to walk, the multitude being a stream that thou must row hard against, or thou wilt be carried into that gulf, out of which angels cannot deliver thee. Is it not better to walk in a strait way alone, than to wander into crooked ways with company? Sure ’tis better to go to heaven alone, than to hell with company. I might add other things, but these may suffice for the present; and I am afraid if these arguments do not stir you, other arguments will work but little upon you.
