== The Reasons of the Point

#strong[Now I shall come to the Reasons of the Point, and so draw to a close, #emph[etc.]]

The first #emph[Reason] is, that their hearts may be kept in an humble, praying,#footnote[The Philosopher had a ball of brass in his hand, which if he chanced to sleep with, the fall into a bason awaked him to his studies; You are wise: and know how to apply it.] watching frame; oh! Hath Satan so many devices to ensnare, and undo the souls of men? How should this awaken dull, drowsy souls, and make them stand upon their watch? A saint should be like a #emph[Seraphim,] beset all over with eyes and lights, that he may avoid Satan's snares, and stand fast in the hour of temptation. The Lord hath in the Scripture discovered the several snares, plots, and devices that the Devil hath to undo the souls of men, that so being forwarn'd, they may be forearm'd, that they may be always upon their watch-tower, and hold their weapons in their hands, as the #emph[Jews] did in #emph[Nehemiah's] time, etc.

The second #emph[Reason] is, from that malice, envy, and enmity that is in Satan,#footnote[Malice cares not what it saith, or doth, it may kill or gall.] against the souls of men; Satan is full of envy and enmity, & that makes him very studious, to suit his snares and plots to the tempers, constitutions, fancies, and callings of men, that so he may make them as miserable as himself. The #emph[Russians] are so malicious, that you shall have a man hide some of his own goods in the house of him, whom he hateth, and then accuse him for the stealth of them: so doth Satan out of malice to#footnote[An envious heart and a plotting head are inseparable companions.] the souls of men, hide his goods, his wares, as I may say, in the souls of men, and then go, and accuse them before the Lord, and a thousand, thousand other ways Satan's malice, envy, and enmity puts him upon, eternally to undo the precious souls of men, etc.

The third #emph[Reason] is drawn from that long #emph[experience] that Satan hath had, he is a spirit of mighty abilities, and his abilities to lay snares before us, are mightily increased by that long standing of his; he is a spirit of above five thousand years standing; he hath had time enough to study all those ways, and methods, which tend most to ensnare, and undo the souls of men: And as he hath time enough, so he hath made it his whole study, his only study, his constant study to find out snares, depths and stratagems, to entangle, and overthrow the souls of men; when he was but a young serpent, he did easily deceive, and out-wit our first parents, but now he is grown that #emph[Old serpent,] as#footnote[Gen. 3.] #emph[John] speaks, #emph[He is as old as the world,] #footnote[Revel. 12. 9.] and is grown very cunning by experience.

The fourth #emph[Reason] is, in judgement to the men of the world, that they may stumble, and fall, and be ensnared for ever; wicked men that withstand the offers of mercy, and despise the spirit of grace; that will not open, though God knocks never so hard by his word, and rod; by his Spirit, and conscience, are given up by a hand of justice, to be#footnote[1 King. 22. 22.] hardened, deceived, and ensnared by Satan to their everlasting ruin; and what can be more just, than that they should be taken, and charmed with Satan's wiles, who have frequently refused to be charmed by the Spirit of grace, though he hath charmed never so wisely, and never so sweetly, etc.

The fifth #emph[Reason] is, That the excellency, and power of God's grace may be the more illustrated, and manifested, by making man able to grapple with this mighty adversary, and that notwithstanding all the plots, devices, and stratagems of Satan; yet he will make them victorious here, and crown them with glory hereafter; the greater, and the subtiler the enemies of the children of Israel were, the more did divine power, wisdom, and goodness sparkle, and shine; that notwithstanding, all their power, plots, and stratagems, etc. Yet to #emph[Canaan] he would bring them at last. When #emph[Paul] had well weighed this, #emph[he sits down, and glories in his infirmities,] #footnote[2 Cor. 12. 7, 8, 9.] #emph[and distresses, and Satan's buffetings, that the power of Christ might rest upon him.]
