== 12. Wicked Company

The twel•th #emph[Device] that Satan hath#footnote[12\. Device.] to draw the soul to sin, is, to affect wicked company, to keep wicked society, and oh! The horrid impieties and wickedness that Satan hath drawn men to sin by working them, to sit, and associate themselves with vain persons.

#strong[Now the Remedies against this device of Satan are these that follow.]

The first #emph[Remedy] against this device#footnote[1\. Remedy.] of Satan, is, to dwell (till your hearts be affected) upon those commands of God, that do expressly require us, to shun the society of the wicked, #emph[Ephes. 5. 11. And have no fellowship] #footnote[#emph[Non paerentum aut majorum authoritas sed Dei docentis imperium,] Jerom. The commands of God must ou•-weigh all authority, and example of men.] #emph[with the unfruit fud works of darkness, but rather reprove them.] Prov. 4. 14, 15, 16. #emph[Enter not into the path of the wicked, and go not in the way of evil men. Avoid it, pass not by it, turn from it, and pass away.] 1 Cor. 5. 9, 10, 11. 2 Thess. 3. 6. Prov. 1. 10, 11, 12, 13, 14, 15. Turn to these Scriptures, and let your souls dwell upon them, till a holy indignation be raised in your souls, against fellowship with vain men. #emph[God will not take the wicked by the hand,] as #emph[Job] speaks, why then should you? Gods commands are not like those that are easily reversed; but they are like those of the #emph[Medes,] that cannot be changed; if these commands be not now observed by thee, they will at last be witnesses against thee, and milstones to sink thee, in that day, that Christ shall judge thee.

The second #emph[Remedy] against this device#footnote[2\. Remedy.] of Satan, is, seriously to consider, that their company is very infectious,#footnote[#emph[Eusebius] reports of #emph[John] the Evangelist, that he would not suffer #emph[Cerinthus] the heretick, in the same bath him, left some judgement should abide them both. #emph[Euseb. lib. 3. cap.] 25. A man that keepeth ill company, is like him that walketh in the Sun, tanned insensibly.] and dangerous, as is clear from the Scriptures above mentioned. Ah! How many have lost their names, and lost their estates, and strength, and God, and Heaven, and souls, by society with wicked men? As ye shun a stinking carcase; as the Sea-man shuns sands, and rocks, and shelves; As ye shun those, that have the plague-sore running upon them: so should you shun the society of wicked men. As weeds endanger the corn, as bad humors endanger the blood, or as an infected house the neighbourhood: so doth wicked company the soul. #emph[Bias] a heathen man, being at Sea in a great storm, and perceiving many wicked men with him in the ship, calling upon the Gods; oh saith he, forbear prayer, hold your tongues, I would not have the Gods take notice that you are here, they will sure drown us all; if they should. Ah sirs! Could a heathen#footnote[Prov. 13. 20. v.] see so much danger in the society of wicked men, and can you see none?

The third #emph[Remedy] against this device#footnote[#emph[3\. Remedie. 2 Tim. 4. 17. Isa. 11. 7. 29. Ezek. 3. 10. Mat. 16. 9. Revel. 3. 5. 10. Mat. 3. 7. Isa 10. 17. 27. ch 4. 55. 13. Ezek 26. Judg. 9. 14. Job 21. 18. Psal. 18. 42. Psa. 14. 18. Psa. 42. Ezek. 22. 18, 19. 65. Esa. 5. Ezek 24. 6. Lactantius] saith of #emph[Lucian (nec diis, nec hominibus pepercit]) he spared neither God, nor man; such monsters are wicked men, which should render their company to all that have tasted of the sweetnesse of divine love, a burden and not a delight.] of Satan, is, to look always upon wicked men, under those names and notions, that the Scripture sets them out under. The Scripture calls them #emph[Lions] for their fierceness, and #emph[Bears] for their cruelty, and #emph[Dragons] for their hideousness, and #emph[Dogs] for their filthiness, and #emph[Wolves] for their subtilness. The Scripture stiles them #emph[Scorpions, Vipers, Thorns, Briars, Thistles, Brambles, stubble, dirt, chaff, dust, dross, smoke, scum;] as you may see in the margent. 'tis not safe to look upon wicked men, under those names, and notions, that they set out themselves by, or that flatterers sets them out by; this may delude the soul; but the looking upon them under those names, and notions, that the Scripture sets out by, may preserve the soul from frequenting their company, and delighting in their society. Do not tell me what this man calls them, or how such and such count them; but tell me, how doth the Scripture call them? How doth the Scripture count them. As #emph[Naballs] name was, so was his nature; and as wicked mens names are, so are their natures; you may know well enough what is within them, by the apt names that the Holy Ghost hath given them.

The fourth and last #emph[Remedy] against#footnote[#emph[4\. Remedie.] O Lord, let me not goe to hell, where the wicked are, for Lord, thou knowest, I never loved their company here, said a gracious gentlewoman, when she was to die, being in much trouble of conscience.] this device of Satan, is, to consider, that the society and company of wicked men, have been a great grief and burden, to those precious souls, that were once glorious on earth, and are now triumphing in heaven. #emph[Psal. 120. Ver. 5, 6. Woe is me that I dwell in Mesech; that I sojourn in the tents of Kedar. My soul hath long dwelt with him that hateth peace.] So #emph[Jeremiah, Oh that I had in the wilderness a lodging place of wayfaring men, that I might leave my people, and go from them; for they be all adulterers, an assembly of treacherous men,] Jer. 9. Ver. 2. #emph[So they vexed Lots] #footnote[2 Pet. 2. c. ver. 7, 8 Vide Bezam.] #emph[righteous soul by their filthy conversation;] they made his life a burden, they made death more desirable to him then life; yea, they made his life a lingering death. Guilt, or grief is all the good, souls get by conversing with wicked men.
