== A Word to the Reader

Dear friend!

#emph[Solomon] bids us buy the#footnote[Pro. 23. 23] Truth, but doth not tell us what it must cost, because we must get it, though it be never so dear; we must love it both#footnote[Multi amant veritatem lucentem, o derunt redarguentem.] shining and scorching; every parcel of Truth is precious, as the filings of gold; we must either live with it, or dye for it; As #emph[Ruth] said to #emph[Naomi, Whither thou goest, I will go, and] #footnote[Ruth 1. 16, 17.] #emph[where thou lodgest, I will lodge, and nothing but death shall part thee and me;] So must gracious spirits say, where Truth goes, I will go, and where Truth lodges, I will#footnote[Si veritas est causa discordiae, mori possum tacere con possum. #emph[Jerome.]] lodge, and nothing but death shall part me and Truth. A man may lawfully sell his House, lands, and jewels, but Truth is a jewell that exceeds all price, and must not be sould. ’tis our heritage; #emph[Thy Testimonies have I taken] #footnote[Psal. 119. 111.] #emph[as an heritage for ever;] ’tis a legacy that our fore-fathers have hought with their bloods, which should make us willing to lay down any thing, and to lay out any thing, that we may with the wise merchant in the gospel, purchase this precious pearl,#footnote[Mat. 5. 18. Veritas vincit. #emph[Truth at last triumphs.]] which is more worth then heaven and earth, and which will make a man live happily, die comfortably, and reign eternally.

And now if thou pleasest, read the work, and receive this council from me.

First, Thou must know that every man cannot be excellent, that yet may be useful. An iron key may unlock the door of a golden treasure, yea (ferrum potest quod aurum non potest) iron can do some things that gold cannot, #emph[etc.]

Secondly, Remember, ’tis not hasty reading, but serious meditating upon#footnote[’tis a Law among the #emph[Persees] in #emph[India,] to use premeditation in what they are to do, that if it be bad, to reject it, if good, to act it.] holy, and heavenly truths, that makes them prove sweet and profitable to the soul. ’tis not the bees touching of the flower that gathers honey, but her abiding for a time upon the flower, that draws out the sweet. ’tis not he that reads most, but he that meditates most, that will prove the choicest, sweetest, wisest, and strongest Christian, #emph[etc.]

Thirdly, Know, that ’tis not the knowing, nor the talking, nor the reading man, but the doing man, that at last will be found the happiest man; #emph[If you know these things, blessed] #footnote[John 15. 14. Mat. 7. 21.] #emph[and happy are you, if you do them. Not every one that saith Lord, Lord, shall enter into the] #footnote[’twas a good saying of #emph[Justin Martyr, Non in verbis sed in factis res nostrae religionis consistunt.]] #emph[Kingdom of heaven, but he that doth the will of my Father that is in heaven. Judas] called Christ Lord, Lord, and yet betrayed him, and is gone to his place; ah! How many Judasses have we in these days, that kiss Christ, and yet betray Christ; That in their words profess him, but in their works deny him; that bow#footnote[The Heathen Philosopher (#emph[Seneca]) liked not such that are (#emph[semper victuri]) always about to live better, but never begin. God loves (saith #emph[Luther) curristas,] not #emph[quaristas,] the runner not the questioner #emph[Pacunius] hath an elegant saying, I hate (saith he) the men that are idle in deed and philosophical in word, #emph[etc.]] their knee to him, and yet in their hearts despise him; that call him Jesus, and yet will not obey him for their Lord.

#emph[Reader,] If it be not strong upon thy heart, to practise what thou readest, to what end doest thou read, to encrease thy own condemnation? If thy light and knowledge be not turn'd into practise, the more knowing man thou art, the more miserable man thou wilt be in the day of recompense; thy light and knowledge will more torment thee, then all the devils in hell. Thy knowledge will be that rod that will eternally lash thee, and that scorpion that will for ever bite thee, and that worm that will everlastingly gnaw thee; therefore read, and labour to know, that thou mayest do, or else thou art undone for ever. When #emph[Demosthenes] was asked what was the first part of an orator, what the second, what the third; he answered, action; the same may I say, if any should ask me, what is the first, the second, the third part of a Christian? I must answer, action; as that man that reads that he may know; and that labours to know, that he may do, will have two heavens; a heaven of joy, peace, and comfort on earth, and a heaven of glory, and happiness after death.

Fourthly, and lastly, if in thy reading thou wilt cast a serious eye upon the margent, thou wilt find many sweet and precious notes, that will oftentimes give light to the things thou readest, and pay thee for thy pains, with much comfort, and profit; So desiring that thou mayest find as much sweetness, and advantage in reading this treatise, as I have found (by the overshadowings of heaven) in the studying and writing of it, #emph[I commend thee to God, and to the word of his grace, which is able to] #footnote[Acts 20. 32.] #emph[build thee up, and to give thee an inheritance among them which are sanctified.] And rest

Reader,

Thy souls servant in every office of the gospel, THOMAS BROOKS.
