== A Brief Account of the Author’s Call to the Work of the Ministry

265\. And now I am speaking my experience, I will in this place thrust in a word or two concerning my preaching the Word, and of God’s dealing with me in that particular also. For after I had been about five or six years awakened, and helped myself to see both the want and worth of Jesus Christ our Lord, and also enabled to venture my soul upon Him, some of the most able among the saints with us, I say the most able for judgment and holiness of life, as they conceived, did perceive that God had counted me worthy to understand something of His will in His holy and blessed Word, and had given me utterance, in some measure, to express what I saw to others for edification; therefore they desired me, and that with much earnestness, that I would be willing, at sometimes, to take in hand, in one of the meetings, to speak a word of exhortation unto them.

266\. The which, though at the first it did much dash and abash my spirit, yet being still by them desired and intreated, I consented to their request, and did twice at two several assemblies, but in private, though with much weakness and infirmity, discover my gift amongst them; at which they not only seemed to be, but did solemnly protest, as in the sight of the great God, they were both affected and comforted, and gave thanks to the Father of mercies for the grace bestowed on me.

267\. After this, sometimes when some of them did go into the country to teach, they would also that I should go with them; where, though as yet I did not, nor durst not, make use of my gift in an open way, yet more privately still as I came amongst the good people in those places, I did sometimes speak a word of admonition unto them also; the which, they as the other received, with rejoicing at the mercy of God to me-ward, professing their souls were edified thereby.

268\. Wherefore, to be brief, at last, being still desired by the church, after some solemn prayer to the Lord, with fasting, I was more particularly called forth, and appointed to a more ordinary and public preaching of the Word, not only to, and amongst them that believed, but also to offer the gospel to those who had not yet received the faith thereof; about which time I did evidently find in my mind a secret pricking forward thereto; though I bless God, not for desire of vain glory, for at that time I was most sorely afflicted with the fiery darts of the devil concerning my eternal state.

269\. But yet could not be content, unless I was found in the exercise of my gift, unto which I was greatly animated, not only by the continual desires of the godly, but also by that saying of Paul to the Corinthians, ‘I beseech you, brethren (ye know the household of Stephanas, that it is the firstfruits of Achaia, and that they have addicted themselves to the ministry of the saints), that ye submit yourselves unto such, and to every one that helpeth with us, and laboureth’ (I Cor. 16.15, 16) .

270\. By this text I was made to see that the Holy Ghost never intended that men who have gifts and abilities should bury them in the earth, but rather did command and stir up such to the exercise of their gift, and also did commend those that were apt and ready so to do, ‘They have addicted themselves to the ministry of the saints.’ This scripture, in these days, did continually run in my mind, to encourage me and strengthen me in this work for God; I have also been encouraged from several other scriptures and examples of the godly, both specified in the Word and other ancient histories (Act. 8.4; 18.24, 25; 1 Pet. 4.10; Rom. 12.6; Foxe’s Acts and Monuments).

271\. Wherefore, though of myself of all the saints the most unworthy, yet I, but with great fear and trembling at the sight of my own weakness, did set upon the work, and did according to my gift, and the proportion of my faith, preach that blessed gospel that God had showed me in the holy Word of truth; which, when the country understood, they came in to hear the Word by hundreds, and that from all parts, though upon sundry and divers accounts.

272\. And I thank God He gave unto me some measure of bowels and pity for their souls, which also did put me forward to labour with great diligence and earnestness, to find out such a word as might, if God would bless it, lay hold of and awaken the conscience, in which the good Lord had respect to the desire of His servant; for I had not preached long before some began to be touched by the Word, and to be greatly afflicted in their minds at the apprehension of the greatness of their sin, and of their need of Jesus Christ.

273\. But I at first could not believe that God should speak by me to the heart of any man, still counting myself unworthy; yet those who were thus touched would love me and have a peculiar respect for me; and though I did put it from me, that they should be awakened by me, still they would confess it, and affirm it before the saints of God; they would also bless God for me, unworthy wretch that I am! and count me God’s instrument that showed to them the way of salvation.

274\. Wherefore, seeing them in both their words and deeds to be so constant, and also in their hearts so earnestly pressing after the knowledge of Jesus Christ, rejoicing that ever God did send me where they were; then I began to conclude it might be so, that God had owned in His work such a foolish one as I, and then came that word of God to my heart with much sweet refreshment, ‘The blessing of him that was ready to perish came upon me; and I caused the widow’s heart to sing for joy’ (Job 29.13).

275\. At this therefore I rejoiced, yea, the tears of those whom God did awaken by my preaching would be both solace and encouragement to me; for I thought on those sayings, ‘Who is he that maketh me glad but the same which is made sorry by me?’ (II Cor. 2.2); and again, Though ‘I be not an apostle to others, yet doubtless I am to you: for the seal of mine apostleship are ye in the Lord’ (1 Cor. 9.2). These things, therefore, were as another argument unto me that God had called me to, and stood by me in this work.

276\. In my preaching of the Word, I took special notice of this one thing, namely, that the Lord did lead me to begin where His Word begins with sinners; that is, to condemn all flesh, and to open and allege that the curse of God, by the law, doth belong to and lay hold on all men as they come into the world, because of sin. Now this part of my work I fulfilled with great sense; for the terrors of the law, and guilt for my transgressions, lay heavy on my conscience. I preached what I felt, what I smartingly did feel, even that under which my poor soul did groan and tremble to astonishment.

277\. Indeed I have been as one sent to them from the dead; I went myself in chains to preach to them in chains; and carried that fire in my own conscience that I persuaded them to beware of. I can truly say, and that without dissembling, that when I have been to preach, I have gone full of guilt and terror even to the pulpit door, and there it hath been taken off, and I have been at liberty in my mind until I have done my work, and then immediately, even before I could get down the pulpit stairs, I have been as bad as I was before; yet God carried me on, but surely with a strong hand, for neither guilt nor hell could take me off my work.

278\. Thus I went for the space of two years, crying out against men’s sins, and their fearful state because of them. After which the Lord came in upon my own soul with some staid peace and comfort through Christ; for He did give me many sweet discoveries of His blessed grace through Him. Wherefore now I altered in my preaching, for still I preached what I saw and felt; now therefore I did much labour to hold forth Jesus Christ in all His offices, relations, and benefits unto the world; and did strive also to discover, to condemn, and remove those false supports and props on which the world doth both lean, and by them fall and perish. On these things also I staid as long as on the other.

279\. After this, God led me into something of the mystery of union with Christ; wherefore that I discovered and showed to them also. And when I had travelled through these three chief points of the Word of God, about the space of five years or more, I was caught in my present practice and cast into prison, where I have lain above as long again, to confirm the truth by way of suffering, as I was before in testifying of it according to the Scriptures in a way of preaching.

280\. When I have been preaching, I thank God, my heart hath often all the time of this and the other exercise, with great earnestness, cried to God that He would make the Word effectual to the salvation of the soul; still being grieved lest the enemy should take the Word away from the conscience, and so it should become unfruitful. Wherefore I did labour so to speak the Word, as that thereby, if it were possible, the sin and the person guilty might be particularized by it.

281\. Also, when I have done the exercise, it hath gone to my heart to think the Word should now fall as rain on stony places, still wishing from my heart, O that they who have heard me speak this day did but see as I do what sin, death, hell, and the curse of God is; and also what the grace, and love, and mercy of God is, through Christ, to men in such a case as they are, who are yet estranged from Him. And, indeed, I did often say in my heart before the Lord, That if to be hanged up presently before their eyes would be a means to awaken them, and confirm them in the truth, I gladly should be contented.

282\. For I have been in my preaching, especially when I have been engaged in the doctrine of life by Christ, without works, as if an angel of God had stood by at my back to encourage me. Oh, it hath been with such power and heavenly evidence upon my own soul, while I have been labouring to unfold it, to demonstrate it, and to fasten it upon the consciences of others, that I could not be contented with saying, I believe, and am sure; methought I was more than sure, if it be lawful so to express myself, that those things which then I asserted were true.

283\. When I went first to preach the Word abroad, the doctors and priests of the country did open wide against me. But I was persuaded of this, not to render railing for railing, but to see how many of their carnal professors I could convince of their miserable state by the law, and of the want and worth of Christ; for, thought I, This shall answer for me in time to come, when they shall be for my hire before their faces (Gen. 30.33).

284\. I never cared to meddle with things that were controverted, and in dispute amongst the saints, especially things of the lowest nature; yet it pleased me much to contend with great earnestness for the word of faith and the remission of sins by the death and sufferings of Jesus; but I say, as to other things, I should let them alone, because I saw they engendered strife, and because that they neither, in doing nor in leaving undone, did commend us to God to be His. Besides, I saw my work before me did run in another channel even to carry an awakening word; to that therefore did I stick and adhere.

285\. I never endeavoured to, nor durst make use of other men’s lines (Rom. 15.18), though I condemn not all that do, for I verily thought, and found by experience, that what was taught me by the Word and Spirit of Christ, could be spoken, maintained, and stood to by the soundest and best established conscience; and though I will not now speak all that I know in this matter, yet my experience hath more interest in that text of Scripture than many amongst men are aware (Gal. 1.11, 12).

286\. If any of those who were awakened by my ministry did after that fall back, as sometimes too many did, I can truly say their loss hath been more to me than if one of my own children, begotten of my body, had been going to its grave; I think, verily, I may speak it without an offence to the Lord, nothing hath gone so near me as that, unless it was the fear of the loss of the salvation of my own soul. I have counted as if I had goodly buildings and lordships in those places where my children were born; my heart hath been so wrapped up in the glory of this excellent work, that I counted myself more blessed and honoured of God by this than if He had made me the emperor of the Christian world, or the lord of all the glory of the earth without it! O these words, ‘He which converteth the sinner from the error of his way shall save a soul from death’ (Jas. 5.20). ‘The fruit of the righteous is a tree of life; and he that winneth souls is wise’ (Prov. 11.30). ‘They that be wise shall shine as the brightness of the firmament; and they that turn many to righteousness as the stars for ever and ever’ (Dan. 12.3). ‘For what is our hope, or joy, or crown of rejoicing? Are not even ye in the presence of our Lord Jesus Christ at his coming? For ye are our glory and joy’ (1 Thess. 2.19, 20). These, I say, with many others of a like nature, have been great refreshments to me.

287\. I have observed, that where I have had a work to do for God, I have had first, as it were, the going of God upon my spirit to desire I might preach there. I have also observed that such and such souls in particular have been strongly set upon my heart, and I stirred up to wish for their salvation; and that these very souls have, after this, been given in as the fruits of my ministry. I have also observed, that a word cast in by the by hath done more execution in a sermon than all that was spoken besides; sometimes also when I have thought I did no good, then I did the most of all; and at other times when I thought I should catch them I have fished for nothing.

288\. I have also observed, that where there hath been a work to do upon sinners, there the devil hath begun to roar in the hearts, and by the mouths of his servants. Yea, oftentimes when the wicked world hath raged most, there hath been souls awaked by the word. I could instance particulars, but I forbear.

289\. My great desire in fulfilling my ministry was to get into the darkest places of the country, even amongst those people that were farthest off of profession; yet not because I could not endure the light, for I feared not to show my gospel to any, but because I found my spirit leaned most after awakening and converting work, and the Word that I carried did lead itself most that way also; ‘yea, so have I strived to preach the gospel, not where Christ was named, lest I should build upon another man’s foundation’ (Rom. 15.20).

290\. In my preaching I have really been in pain, and have, as it were, travailed to bring forth children to God; neither could I be satisfied unless some fruits did appear in my work. If I were fruitless it mattered not who commended me; but if I were fruitful, I cared not who did condemn. I have thought of that, ‘He that winneth souls is wise’ (Prov. 11.30); and again, ‘Lo, children are an heritage of the Lord; and the fruit of the womb is his reward. As arrows in the hand of a mighty man, so are children of the youth. Happy is the man that hath filled his quiver full of them; they shall not be ashamed, but they shall speak with the enemies in the gate’ (Ps. 127.3-5).

291\. It pleased me nothing to see people drink in opinions if they seemed ignorant of Jesus Christ, and the worth of their own salvation, sound conviction for sin, especially for unbelief, and an heart set on fire to be saved by Christ, with strong breathing after a truly sanctified soul; that it was that delighted me; those were the souls I counted blessed.

292\. But in this work, as in all other, I had my temptations attending me, and that of diverse kinds, as sometimes I should be assaulted with great discouragement therein, fearing that I should not be able to speak the Word at all to edification; nay, that I should not be able to speak sense unto the people; at which times I should have such a strange faintness and strengthlessness seize upon my body that my legs have scarce been able to carry me to the place of exercise.

293\. Sometimes, again, when I have been preaching, I have been violently assaulted with thoughts of blasphemy, and strongly tempted to speak the words with my mouth before the congregation. I have also at some times, even when I have begun to speak the Word with much clearness, evidence, and liberty of speech, yet been before the ending of that opportunity so blinded, and so estranged from the things I have been speaking, and have also been so straitened in my speech, as to utterance before the people, that I have been as if I had not known or remembered what I have been about, or as if my head had been in a bag all the time of the exercise.

294\. Again, when as sometimes I have been about to preach upon some smart and scorching portion of the Word, I have found the tempter suggest, What, will you preach this? this condemns yourself; of this your own soul is guilty; wherefore preach not of it at all; or if you do, yet so mince it as to make way for your own escape; lest instead of awakening others, you lay that guilt upon your own soul as you will never get from under.

295\. But, I thank the Lord, I have been kept from consenting to these so horrid suggestions, and have rather, as Samson, bowed myself with all my might, to condemn sin and transgression wherever I found it, yea, though therein also I did bring guilt upon my own conscience! ‘Let me die,’ thought I, ‘with the Philistines’ (Judg. 16.29, 30), rather than deal corruptly with the blessed Word of God, ‘Thou that teachest another, teachest not thou thyself?’ It is far better that thou do judge thyself, even by preaching plainly to others, than that thou, to save thyself, imprison the truth in unrighteousness; blessed be God for His help also in this.

296\. I have also, while found in this blessed work of Christ, been often tempted to pride and liftings up of heart; and though I dare not say I have not been infected with this, yet truly the Lord, of His precious mercy, hath so carried it towards me, that, for the most part, I have had but small joy to give way to such a thing; for it hath been my every day’s portion to be let into the evil of my own heart, and still made to see such a multitude of corruptions and infirmities therein, that it hath caused hanging down of the head under all my gifts and attainments; I have felt this thorn in the flesh, the very mercy of God to me (II Cor. 12.7-9).

297\. I have had also, together with this, some notable place or other of the Word presented before me, which word hath contained in it some sharp and piercing sentence concerning the perishing of the soul, notwithstanding gifts and parts; as, for instance, that hath been of great use unto me, ‘Though I speak with the tongues of men and of angels, and have not charity, I am become as sounding brass, and a tinkling cymbal’ (1 Cor. 13.1, 2).

298\. A tinkling cymbal is an instrument of music, with which a skilful player can make such melodious and heart-inflaming music, that all who hear him play can scarcely hold from dancing; and yet behold the cymbal hath not life, neither comes the music from it, but because of the art of him that plays therewith; so then the instrument at last may come to naught and perish, though, in times past, such music hath been made upon it.

299\. Just thus I saw it was and will be with them who have gifts, but want saving grace, they are in the hand of Christ, as the cymbal in the hand of David; and as David could, with the cymbal, make that mirth in the service of God, as to elevate the hearts of the worshippers, so Christ can use these gifted men, as with them to affect the souls of His people in His church; yet when He hath done all, hang them by as lifeless, though sounding cymbals.

300\. This consideration, therefore, together with some others, were, for the most part, as a maul on the head of pride, and desire of vain glory; what, thought I, shall I be proud because I am a sounding brass? Is it so much to be a fiddle? Hath not the least creature that hath life, more of God in it than these? Besides, I knew it was love should never die, but these must cease and vanish; so I concluded, a little grace, a little love, a little of the true fear of God, is better than all these gifts; yea, and I am fully convinced of it, that it is possible for a soul that can scarce give a man an answer, but with great confusion as to method, I say it is possible for them to have a thousand times more grace, and so to be more in the love and favour of the Lord than some who, by virtue of the gift of knowledge, can deliver themselves like angels.

301\. Thus, therefore, I came to perceive, that though gifts in themselves were good to the thing for which they are designed, to wit, the edification of others; yet empty and without power to have the soul of him that hath them, if they be alone; neither are they, as so, any sign of a man’s state to be happy, being only a dispensation of God to some, of whose improvement, or non-improvement, they must, when a little love more is over, give an account to Him that is ready to judge the quick and the dead.

302\. This showed me, too, that gifts being alone, were dangerous, not in themselves, but because of those evils that attend them that have them, to wit, pride, desire of vain glory, self-conceit, etc., all of which were easily blown up at the applause and commendation of every unadvised Christian, to the endangering of a poor creature to fall into the condemnation of the devil.

303\. I saw therefore that he that hath gifts had need be let into a sight of the nature of them, to wit, that they come short of making of him to be in a truly saved condition, lest he rest in them, and so fall short of the grace of God.

304\. He hath also cause to walk humbly with God, and be little in his own eyes, and to remember withal, that his gifts are not his own, but the church’s; and that by them he is made a servant to the church; and that he must give at last an account of his stewardship unto the Lord Jesus; and to give a good account, will be a blessed thing.

305\. Let all men therefore prize a little with the fear of the Lord; gifts indeed are desirable, but yet great grace and small gifts are better than great gifts and no grace. It doth not say, the Lord gives gifts and glory, but the Lord gives grace and glory; and blessed is such an one to whom the Lord gives grace, true grace, for that is a certain forerunner of glory.

306\. But when Satan perceived that his thus tempting and assaulting of me would not answer his design, to wit, to overthrow my ministry, and make it ineffectual, as to the ends thereof; then he tried another way, which was to stir up the minds of the ignorant and malicious, to load me with slanders and reproaches; now therefore I may say, that what the devil could devise, and his instruments invent, was whirled up and down the country against me, thinking, as I said, that by that means they should make my ministry to be abandoned.

307\. It began therefore to be rumoured up and down among the people, that I was a witch, a Jesuit, a highwayman, and the like.

308\. To all which, I shall only say, God knows that I am innocent. But as for mine accusers, let them provide themselves to meet me before the tribunal of the Son of God, there to answer for these things, with all the rest of their iniquities, unless God shall give them repentance for them, for the which I pray with all my heart.

309\. But that which was reported with the boldest confidence, was, that I had my misses, my whores, my bastards, yea, two wives at once, and the like. Now these slanders, with the other, I glory in, because but slanders, foolish, or knavish lies, and falsehoods cast upon me by the devil and his seed; and should I not be dealt with thus wickedly by the world, I should want one sign of a saint, and a child of God. ‘Blessed are ye (said the Lord Jesus) when men shall revile you, and persecute you, and shall say all manner of evil against you falsely for my sake; rejoice, and be exceeding glad, for great is your reward in heaven; for so persecuted they the prophets which were before you’ (Matt. 5.11).

310\. These things, therefore, upon mine own account, trouble me not; no, though they were twenty times more than they are. I have a good conscience, and whereas they speak evil of me, as an evil doer, they shall be ashamed that falsely accuse my good conversation in Christ.

311\. So, then, what shall I say to those that have thus bespattered me? Shall I threaten them? Shall I chide them? Shall I flatter them? Shall I intreat them to hold their tongues? No, not I, were it not for that these things make them ripe for damnation, that are the authors and abettors, I would say unto them, Report it, because it will increase my glory.

312\. Therefore I bind these lies and slanders to me as an ornament, it belongs to my Christian profession to be vilified, slandered, reproached and reviled; and since all this is nothing else, as my God and my conscience do bear me witness, I rejoice in reproaches for Christ’s sake.

313\. I also calling all those fools, or knaves, that have thus made it anything of their business to affirm any of the things afore-named of me, namely, that I have been naught with other women, or the like. When they have used to the utmost of their endeavours, and made the fullest inquiry that they can, to prove against me truly, that there is any woman in heaven, or earth, or hell, that can say, I have at any time, in any place, by day or night, so much as attempted to be naught with them; and speak I thus, to beg mine enemies into a good esteem of me? No, not I: I will in this beg relief of no man; believe or disbelieve me in this, all is a case to me.

314\. My foes have missed their mark in this their shooting at me. I am not the man. I wish that they themselves be guiltless. If all the fornicators and adulterers in England were hanged by the neck till they be dead, John Bunyan, the object of their envy, would be still alive and well. I know not whether there be such a thing as a woman breathing under the copes of the whole heaven but by their apparel, their children, or by common fame, except my wife.

315\. And in this I admire the wisdom of God, that He made me shy of women from my first conversion until now. Those know, and can also bear me witness, with whom I have been most intimately concerned, that it is a rare thing to see me carry it pleasant towards a woman, the common salutation of a woman I abhor, it is odious to me in whosoever I see it. Their company alone, I cannot away with. I seldom so much as touch a woman’s hand, for I think these things are not so becoming me. When I have seen good men salute those women that they have visited, or that have visited them, I have at times made my objection against it, and when they have answered, that it was but a piece of civility, I have told them, it is not a comely sight; some indeed have urged the holy kiss but then I have asked why they made baulks, why they did salute the most handsome, and let the ill-favoured go; thus, how laudable soever such things have been in the eyes of others, they have been unseemly in my sight.

316\. And now for a wind up in this matter, I calling not only men, but angels, to prove me guilty of having carnally to do with any woman save my wife, nor am I afraid to do it a second time, knowing that I cannot offend the Lord in such a case, to call God for a record upon my soul, that in these things I am innocent. Not that I have been thus kept, because of any goodness in me more than any other, but God has been merciful to me, and has kept me; to whom I pray that He will keep me still, not only from this, but from every evil way and work, and preserve me to His heavenly kingdom. Amen.

317\. Now as Satan laboured by reproaches and slanders, to make me vile among my countrymen, that, if possible, my preaching might be made of none effect, so there was added hereto a long and tedious imprisonment, that thereby I might be frighted from my service for Christ, and the world terrified, and made afraid to hear me preach, of which I shall in the next place give you a brief account.
