== A Brief Account of the Author’s Imprisonment

318\. Having made profession of the glorious gospel of Christ a long time, and preached the same about five years, I was apprehended at a meeting of good people in the country, among whom, had they let me alone, I should have preached that day, but they took me away from amongst them, and had me before a justice; who, after I had offered security for my appearing at the next sessions, yet committed me, because my sureties would not consent to be bound that I should preach no more to the people.

319\. At the sessions, after I was indicted for an upholder and maintainer of unlawful assemblies and conventicles, and for not conforming to the national worship of the Church of England, and after some conference there with the justices, they, taking my plain dealing with them for a confession, as they termed it, of the indictment, did sentence me to a perpetual banishment, because I refused to conform. So, being again delivered up to a gaoler’s hands, I was had home to prison, and there have lain now complete twelve years, waiting to see what God would suffer those men to do with me.

320\. In which condition I have continued with much content, through grace, but have met with many turnings and goings upon my heart, both from the Lord, Satan, and my own corruption; by all which, glory be to Jesus Christ! I have also received, among many things, much conviction, instruction, and understanding, of which at large I shall not here discourse; only to give you a hint or two, a word that may stir up the godly to bless God, and to pray for me; and also to take encouragement, should the case be their own, not to fear what man can do unto them.

321\. I never had in all my life so great an inlet into the Word of God as now; Those scriptures that I saw nothing in before, were made in this place and state to shine upon me; Jesus Christ also was never more real and apparent than now; here I have seen and felt Him indeed. Oh! that word, We have not preached unto you cunningly devised fables (2 Pet. 1.16), and that, God raised Christ from the dead, and gave him glory, that your faith and hope might be in God, were the blessed words unto me in this my imprisoned condition.

322\. These three or four scriptures also have been great refreshments in this condition to me (John 14.1-4; 16.33; Col. 3.3, 4; Heb. 12.22-24). So that sometimes when I have been in the savour of them I have been able to laugh at destruction, and to fear neither the horse nor his rider. I have had sweet sights of the forgiveness of my sins in this place, and of my being with Jesus in another world. Oh! the Mount Sion, the heavenly Jerusalem, the innumerable company of angels, and God the judge of all, and the spirits of just men made perfect, and to Jesus (Heb. 12.22-24), have been sweet unto me in this place. I have seen that here, that I am persuaded I shall never, while in this world, be able to express: I have seen a truth in this scripture, ‘Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory’ (1 Pet. 1.8).

323\. I never knew what it was for God to stand by me at all turns, and at every offer of Satan to afflict me, etc., as I have found Him since I came in hither: For look how fears have presented themselves, so have supports and encouragements; yea, when I have started, even as it were at nothing else but my shadow, yet God, as being very tender to me, hath not suffered me to be molested, but would, with one scripture or another, strengthen me against all; insomuch that I have often said, Were it lawful, I could pray for greater trouble, for the greater comfort’s sake (Eccles. 7.14; 2 Cor. 1.5).

324\. Before I came to prison I saw what was coming, and had especially two considerations warm upon my heart; the first was, how to be able to endure, should my imprisonment be long and tedious; the second was, how to be able to encounter death, should that be my portion. For the first of these, that scripture (Col. 1.11) was great information to me, namely, to pray to God, ‘to be strengthened with all might, according to his glorious power, unto all patience and long-suffering with joyfulness.’ I could seldom go to prayer before I was imprisoned, but for not so little as a year together, this sentence or sweet petition would, as it were, thrust itself into my mind, and persuade me, that if ever I would go through long-suffering, I must have patience, especially if I would endure it joyfully.

325\. As to the second consideration, that saying was of great use to me, ‘But we had the sentence of death in ourselves, that we should not trust in ourselves, but in God which raiseth the dead’ (2 Cor. 1.9). By this scripture I was made to see, That if ever I would suffer rightly I must first pass a sentence of death upon everything that can properly be called a thing of this life, even to reckon myself, my wife, my children, my health, my enjoyments, and all, as dead to me and myself, as dead to them.

326\. The second was to live upon God that is invisible, as Paul said in another place; the way not to faint is to ‘Look not on the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal’ (2 Cor. 4.18). And thus I reasoned with myself, If I provide only for a prison, then the whip comes at unawares, and so doth also the pillory. Again, if I only provide for these, then I am not fit for banishment: Farther, if I conclude that banishment is the worst, then if death comes I am surprised: So that I see, the best way to go through sufferings is to trust in God through Christ, as touching the world to come; and as touching this world, to count the grave my house, to make my bed in darkness; to say to corruption, Thou art my father, and to the worm, Thou art my mother and sister: that is, to familiarize these things to me.

327\. But notwithstanding these helps, I found myself a man encompassed with infirmities; the parting with my wife and poor children hath often been to me in this place as the pulling the flesh from the bones, and that not only because I am somewhat too fond of these great mercies, but also because I should have often brought to my mind the many hardships, miseries, and wants that my poor family was like to meet with should I be taken from them, especially my poor blind child, who lay nearer my heart than all beside. Oh! the thoughts of the hardship I thought my poor blind one might go under, would break my heart to pieces.

328\. Poor child! thought I, what sorrow art thou like to have for thy portion in this world! Thou must be beaten, must beg, suffer hunger, cold, nakedness, and a thousand calamities, though I cannot now endure the wind should blow upon thee. But yet recalling myself, thought I, I must venture you all with God, though it goeth to the quick to leave you. Oh! I saw in this condition I was as a man who was pulling down his house upon the head of his wife and children; yet thought I, I must do it, I must do it. And now I thought on those two milch kine that were to carry the ark of God into another country, and to leave their calves behind them (1 Sam. 6.10).

329\. But that which helped me in this temptation was divers considerations, of which three in special here I will name: The first was the consideration of these two scriptures, ‘Leave thy fatherless children, I will preserve them alive, and let thy widows trust in me.’ And again, ‘The Lord said, Verily it shall be well with thy remnant, verily I will cause the enemy to entreat thee well in the time of evil’ (Jer. 49.11; 15.11).

330\. I had also this consideration, that if I should venture all for God, I engaged God to take care of my concernments: but if I forsook Him in His ways, for fear of any trouble that should come to me or mine, then I should not only falsify my profession, but should count also that my concernments were not so sure if left at God’s feet, while I stood to and for His name, as they would be if they were under my own care, though with the denial of the way of God. This was a smarting consideration, and as spurs unto my flesh. That scripture also greatly helped it to fasten the more on me where Christ prays against Judas, that God would disappoint him in his selfish thoughts, which moved him to sell his master. Pray read it soberly (Ps. 109.6-20).

331\. I had also another consideration, and that was the dread of the torments of hell, which I was sure they must partake of that for fear of the cross do shrink from their profession of Christ, His words and laws, before the sons of men; I thought also of the glory that He had prepared for those that in faith, and love, and patience, stood to His ways before them. These things, I say, have helped me, when the thoughts of the misery that both myself and mine might, for the sake of my profession, be exposed to, have lain pinching on my mind.

332\. When I have indeed conceited that I might be banished for my profession, then I have thought of that scripture, ‘They were stoned, they were sawn asunder, were tempted, were slain with the sword: they wandered about in sheepskins and goatskins; being destitute, afflicted, tormented; (of whom the world was not worthy)’ (Heb. 11.37, 38); for all they thought they were too bad to dwell and abide amongst them. I have also thought of that saying, ‘The Holy Ghost witnesseth in every city,’ ‘that bonds and afflictions abide me’ (Acts 20.23). I have verily thought that my soul and it have sometimes reasoned about the sore and sad estate of a banished and exiled condition, how they were exposed to hunger, to cold, to perils, to nakedness, to enemies, and a thousand calamities; and at last, it may be, to die in a ditch like a poor and desolate sheep. But I thank God hitherto I have not been moved by these most delicate reasonings, but have rather, by them, more approved my heart to God.

333\. I will tell you a pretty business: I was once above all the rest in a very sad and low condition for many weeks; at which time also, I being but a young prisoner, and not acquainted with the laws, I had this lying much upon my spirits, that my imprisonment might end at the gallows for aught that I could tell. Now therefore Satan laid hard at me, to beat me out of heart, by suggesting thus unto me. But how if, when you come indeed to die, you should be in this condition; that is, as not to savour the things of God, nor to have any evidence upon your soul for a better state hereafter? for indeed at this time all the things of God were hid from my soul.

334\. Wherefore when I at first began to think of this, it was a great trouble to me; for I thought with myself, that in the condition I now was in, I was not fit to die, neither indeed did I think I could if I should be called to it; besides I thought with myself, if I should make a scrambling shift to clamber up the ladder, yet I should, either with quaking or other symptoms of fainting, give occasion to the enemy to reproach the way of God and His people for their timorousness. This, therefore, lay with great trouble upon me, for methought I was ashamed to die with a pale face, and tottering knees, in such a case as this.

335\. Wherefore I prayed to God that He would comfort me, and give me strength to do and suffer what He should call me to; yet no comfort appeared, but all continued hid; I was also at this time so really possessed with the thought of death, that oft I was as if I was on the ladder with a rope about my neck; only this was some encouragement to me, I thought I might now have an opportunity to speak my last words unto a multitude, which I thought would come to see me die; and thought I, if it must be so, if God will but convert one soul by my last words, I shall not count my life thrown away nor lost.

336\. But yet all the things of God were kept out of my sight, and still the tempter followed me with, But whither must you go when you die? what will become of you? where will you be found in another world? what evidence have you for heaven and glory, and an inheritance among them that are sanctified? Thus was I tossed for many weeks, and knew not what to do; at last this consideration fell with weight upon me, that it was for the word and way of God that I was in this condition; wherefore I was engaged not to flinch an hair’s breadth from it.

337\. I thought also that God might choose whether He would give me comfort now or at the hour of death; but I might not therefore choose whether I would hold my profession or no; I was bound, but He was free; yea, ’twas my duty to stand to His word, whether He would ever look upon me or save me at the last: wherefore thought I, the point being thus, I am for going on, and venturing my eternal state with Christ, whether I have comfort here or no. If God doth not come in, thought I, I will leap off the ladder even blindfold into eternity, sink or swim, come heaven, come hell, Lord Jesus, if thou wilt catch me, do; if not, I will venture for thy name.

338\. I was no sooner fixed with this resolution but this word dropped upon me, Doth Job serve God for nought? As if the accuser had said, Lord, Job is no upright man, he serves thee for by-respects: hast thou not made an hedge about him? But put forth now thine hand, and touch all that he hath, and he will curse thee to thy face. How now, thought I, is this the sign of an upright soul, to desire to serve God when all is taken from him? Is he a godly man that will serve God for nothing rather than give out? Blessed be God; then I hope I have an upright heart, for I am resolved, God giving me strength, never to deny my profession, though I had nothing at all for my pains: and as I was thus considering, that scripture was set before me (Ps. 44.12-26).

339\. Now was my heart full of comfort, for I hoped it was sincere: I would not have been without this trial for much; I am comforted every time I think of it, and I hope I shall bless God for ever for the teaching I have had by it. Many more of the dealings of God towards me I might relate, but these, out of the spoils won in battles, have I dedicated to maintain the house of God (1 Chron. 26.27).
