== A Servant’s Faithful and Willing Service

=== §. 20. #emph[Of serving with trembling.]

The #emph[Manner] how servants ought to perform their duties is noted in four phrases:

The first whereof is this, #emph[with fear and trembling.] #footnote[I.]

#emph[Fear] is both as a #emph[fountain] from whence all other duties flow: and also as a #emph[sauce] to season them all.

Commonly the season and savour of waters cometh from the fountain: which Saint #emph[James] implieth, where he saith, #emph[no fountain doth yield salt water and fresh:] for if the fountain be #footnote[#emph[Jam.] 3. 12.] salt, the streams issuing from thence will be salt: and fresh, if the fountain be fresh: so if fear be seated in the heart of servants, all their obedience and submission will be seasoned therewith. Let therefore servants here learn by their manner of performing all their duties, to declare that there is a true servant-like fear seated in their hearts. Hereof I shall need say no more then what hath been #footnote[§. 4.] before delivered.

The other word #footnote[See Treat. 1. §. 124.] #emph[trembling] added to fear, addeth emphasis, showing that it is no small fear that is required of servants: and it giveth them to wit that their masters having a power to punish them, they must so carry themselves as they provoke not their master to wrath, but be very careful and circumspect to avoid his displeasure, that they give him no just occasion of offence. This care had that servant of #emph[David] which first espied #emph[Absalom] hanging in a tree, and told #emph[Joab] thereof: #footnote[2 #emph[Sam.] 18. 12.] he so feared the displeasure of the king his master, as to gain a thousand shekels of silver he durst not kill #emph[Absalom.] The like is noted of #emph[Obadiah,] who was afraid to tell his master #emph[Ahab] where #emph[Elijah] was, lest his master might have thought he had mocked him, if the Spirit had carried #emph[Elijah] away. #footnote[1 #emph[King.] 18. 9. #emph[etc.]]

This trembling fear is needful in regard of the small love that servants commonly bear to their masters. There are not those motives to stir up love in servants to their masters, as in children to their parents: except therefore through awe and dread they be kept in compass, they will exceedingly transgress: and because this is so needful, servants must labour to nourish it, as a means to keep them from over-much boldness.

Contrary on the one side is a proud despising of a masters authority (saying, if not with their mouths, yet in their heart, as #emph[Gaal] of #emph[Abimelech, who is he that we should serve him?] or as those that despised the government of Christ their master, #footnote[#emph[Judg.] 9. 28.] #footnote[#emph[Luk.] 19. 14.] #emph[we will not have this man to reign over us:] and again, #footnote[#emph[Psal.] 2. 3.] #emph[let us break his bonds asunder, and cast away his cords from us.)] And on the other side a wretched carelessness, not fearing any punishment before they feel it: like to many desperate thieves that no whit fear the power of the Judge, but desperately say, #emph[we have but one death to pay.] The authority of God himself is despised, and his revenging hand is lightly regarded by such proud and desperate servants: so as their sin is no small sin.

=== §. 21. #emph[Of serving with sincerity.]

The second branch concerning the #emph[manner] of servants performing their duty is in these words, #emph[in singleness of heart,] #footnote[II.] so as all must be performed with an honest and upright heart: #emph[whatsoever ye do, do it heartily,] saith the Apostle to servants #footnote[#emph[Col.] 3. 23.] in another place. Thus did #emph[Joseph] in singleness of heart serve his master: instance his refusing to abuse his mistress in #footnote[#emph[Gen.] 39. 11, 12.] a private chamber when she desired it, and no other body was in the house. Happy were it for masters to have such servants: then might they take no more care then #emph[Potiphar] did, but put #footnote[#emph[Gen.] 39. 6.] all that they have into their servants hands. Neither would this rare virtue in servants be only profitable to their masters, but also very comfortable to themselves, and bring them much peace of conscience.

Contrary is hypocritical service: when servants have #emph[a heart, and a heart,] making show of one heart outwardly, and have another, even a clean contrary heart within them. Such #footnote[#emph[Psal.] 12. 2.] an one was #emph[Gehazi,] who #emph[came in and stood before his master,] as if he had performed some good service for his master, when #footnote[2 #emph[King]. 5. 25.] he had most highly dishonoured him: and such an one was #emph[Judas] who carried as fair a face to his master as any of the disciples, and yet was an arrant traitor: for when he was thought to go out to buy provision for his master, he went to #footnote[#emph[John] 13. 29.] betray him.

All eye-service is contrary to the forenamed singleness of heart: when servants are diligent so long as their masters eye is on them: #footnote[Eye service.] like little children that will do any thing their mother will have them do, while her eye is upon them; but nothing, when her back is turned. The world is full of such eye-serving servants, who while their masters are present, will be as busy as Bees: but if he be away, then either idling at home, or gadding abroad, or nothing but wrangling, and eating, and drinking with the drunken; like that lewd servant whom Christ noteth in the parable #footnote[#emph[Matth.] 24. 49.] Let the judgment denounced against him be noted of such servants.

=== §. 22. #emph[Of serving for conscience sake.]

The third branch of the #emph[manner] of servants performing #footnote[III. #emph[Sit seruus non vt seruus ad oculum, sed vt domini studiosus. Constit. Apost. l.] 4. #emph[c.] 12.] their duty is in these words, #emph[as unto Christ, as the servants of Christ, doing the will of God, as to the Lord:] all which do set forth a good conscience, or such service as is performed #emph[for conscience sake,] or #emph[for the Lords sake,] which is all one: because the conscience hath an eye only to the Lord, to his will, and to his ordinance. Though there were no other motive in the world to move them to obey their masters, yet their conscience to God would move them. Such was #emph[Josephs] manner of serving his master, as the reason which he himself rendereth to his mistress showeth, #emph[How can I do this great wickedness, and sin against God?] The #footnote[#emph[Gen.] 39. 9.] prayer which #emph[Abrahams] servant made to God, and the thanks #footnote[#emph[Gen.] 24. 12, 27.] which he rendered to him for blessing his journey, show, that he served his master for the Lords sake. It is more clear then needs be proved, that such was #emph[Jacobs] service to his master. This is the rather to be noted of Christian servants, because herein lieth the greatest difference betwixt #emph[believing servants,] and others: others may serve with fear and trembling, in singleness of heart, and with good will; but only Saints do service as to Christ for conscience sake: If this be not that which #emph[only] they aim at, yet assuredly they do #emph[chiefly] and #emph[principally] aim at it: which maketh them not to content themselves with doing the thing, but to endeavour to do it after the best manner that they can, so as God may best accept thereof: whereby as they approve themselves to God, so they do much good to their masters, and bring much comfort unto their own souls.

Contrary is the mind of most, who do all the service which #footnote[Service on by-respects.] they do on by-respects: they may perform much duty, and it may be do much good to their masters; and thereupon they may get good wages at their masters hands, and extraordinary recompense also, and live in much quiet under them: but no reward can they look for at Gods hands: so as I may say to such servants, as Christ said to those who did all to have glory of men, #emph[They have their reward.] #footnote[#emph[Matth.] 6. 2.]

=== §. 23. #emph[Of servants willingness to perform their duty.]

The fourth branch respecting the #emph[manner] of servants performing #footnote[IIII.] their duty, is noted in this phrase, #emph[with good will.] This #emph[good will] of a servant to his master, hath respect partly to the disposition of the servant, and so it implieth #emph[willingness] and cheerfulness; #footnote[Service to be done cheerfully.] and partly to the benefit of the master, and so it implieth #emph[faithfulness.]

Of #emph[willingness] to do that duty which belongeth to a servant, Christ Jesus (who #footnote[#emph[Phil.] 2. 7.] #emph[took upon him the form of a servant)] hath made himself a worthy pattern. #footnote[#emph[Psal.] 40. 8.] #emph[I delight to do thy will,] saith he to him that sent him: and again, #footnote[#emph[Joh.] 4. 34.] #emph[My meat is to do the will of him that sent me, and to finish his work.] Doth not a man eat his meat willingly, with delight and cheerfulness? Even so did Christ the work of him that sent him. So cheerfully did #emph[Jacob] serve his Uncle #emph[Laban,] that #footnote[#emph[Gen.] 29. 20.] #emph[seven years seemed to him but a few days.]

#strong[#emph[Object.] The reason thereof was #emph[the love he had to Rachel.]]

1. #emph[Answ.] This was #emph[one] reason, but not the #emph[only] reason: had he not borne #emph[good will] to his Uncle and master, as well as #emph[love] to his wife, the time might have seemed tedious enough: but both meeting together, made the time pass away the better.

2. #emph[Answ.] If the love he had to #emph[Rachel] made him do his service so cheerfully: then if servants love God, for whose sake they ought to do their service, it will cheerfully be done.

1. That which the Apostle applieth to #emph[giving of alms] (2 #emph[Cor.] 9. 7.) may be extended to all manner of duties which God requireth, #emph[God loveth cheerfulness:] that work therefore which is not seasoned therewith God regardeth not.

2. As #emph[cheerfulness] maketh God the better to like the work, so it maketh the work much more easy to him that doth it. Our common proverb noteth as much, #emph[Nothing is hard to a willing mind.]

3. #footnote[#emph[Apostolus seruos monet dominis suis ex animo cum bona voluntate seruire, vt scilicet si non possunt à dominis liberi fieri, suam seruitutem ipsi quodammedo liberam faciant. Aug de Ciu. Dei, l.] 19. #emph[c.] 15. #emph[Direction.]] Let there be cheerfulness in a servants mind, and he is as free as his master: for such a servant is #emph[the Lords freeman] (1 #emph[Cor.] 7. 22.) and when he cannot be made free of his master, he doth after a manner make his service free.

Have an eye to God, to his acceptation, and remuneration, and it will quicken thy spirit. Mans reward maketh poor men glad of work, and cheerful in doing their work: it is as sugar to sharp wine. Tradesmen, Physicians, Lawyers, all sorts of men, are by gain drawn on with great willingness to take great pains. Should not Gods recompense of our pains make us much more willing? Surely it would, if we had such an eye of #footnote[#emph[Heb.] 11. 26.] faith as #emph[Moses] had, thereby to see the recompense of reward which he saw.

Contrary is heaviness of spirit, and discontentedness of mind, #footnote[Contrary, Discontentedness.] when servants do their service lowringly, grudgingly, by compulsion (as Bears are brought to a stake) and of necessity, as slaves in a galley. Such service must needs be untowardly done: but though outwardly it be well done, yet can the doer have little comfort therein, because God accepteth it not.

=== §. 24. #emph[Of servants quickness and diligence in their service.]

Servants, in testimony of their willingness and cheerfulness, must be both quick and diligent in their service: for these are effects of willingness. #emph[Quickness] hath respect to the time of doing a thing. #emph[Diligence] to the pains that is taken about it.

He that is #emph[quick] in his service taketh up no more time about #footnote[Quickness.] one thing then must needs; but is ready to do one thing after another; and thus doth much more service. It is expressly noted of #emph[Rebekah,] that she #footnote[#emph[Gen.] 24. 18, 20.] #emph[hasted,] and let down her pitcher: and #emph[hasted] and emptied her pitcher, and #emph[ran] again to the Well. And #emph[Abrahams] servant having made what speed he could to the place whither he was sent, #footnote[#emph[Gen.] 24. 33.] #emph[would not eat till he had told his errand:] after he had told it, if he had not sped, #footnote[#emph[vers.] 49.] he would not have delayed time, but have gone again forthwith: when he had well dispatched all, #footnote[#emph[vers.] 56.] he would not stay upon any complements, but hasted away to his master. #footnote[2 #emph[Sam.] 18. 23.] #emph[Ahimaaz] strove with #emph[Cushi] who should soonest bring their message to their master: and #emph[Ahimaaz] outstript #emph[Cushi,] for he had a very willing mind to do the business. The manner of charge which #emph[Elisha] gave to his servant, implieth all the speed he could make: it was this, #footnote[2 #emph[King.] 4. 29.] #emph[Gird up thy loins, go thy way: if thou meet any by the way, salute him not: and if any salute thee, answer him not again.]

He that is #emph[diligent] in his service, will not only be quick for the #footnote[Diligence.] time, but also hold on, and employ all the labour and pains that he can for the well effecting of that which he is to do. That general charge laid upon all men, in particular appertaineth to a servant (#footnote[#emph[Gen.] 3. 19.] #emph[In the sweat of thy face thou shalt eat bread)] and that which #emph[Solomon] noteth (#footnote[#emph[Eccl.] 9. 10.] #emph[what soever thine hand findeth to do, do it with thy might.)] Great was #emph[Jacobs] diligence (for he saith of himself in doing his masters business, #footnote[#emph[Gen.] 31. 40.] #emph[In the day the drought consumed me, and the frost by night, and my sleep departed from mine eyes.)] Great also was the diligence of those shepherds, that #footnote[#emph[Luke] 2. 8.] #emph[kept watch over their flock by night:] and of #footnote[#emph[Mat.] 25. 16, 17.] those servants, that by their pains doubled the talents which were committed to them. As diligence is by these and many like examples commended unto us, so is it further set forth by the many promises which are made unto it, as, #footnote[#emph[Pro.] 10. 4.] #emph[The hand of the diligent maketh rich:] #footnote[#emph[&] 12. 14.] #emph[The recompense of a mans hands shall be rendered unto him:] #footnote[#emph[vers.] 24.] #emph[The hand of the diligent shall bear rule:] #footnote[#emph[&] 14. 23.] #emph[In all labour there is profit.]

The work which servants are by their master appointed to do, is to them the work of God: whereupon the Apostle saith to servants as well as to others, #footnote[1 #emph[Cor.] 7. 17.] #emph[as God hath called every one, so let him walk:] but the work of God is to be done with all diligence: for #footnote[#emph[Jer.] 48. 10.] #emph[Cursed is he that doth the work of the Lord negligently.]

Contrary is the idleness, laziness, slothfulness, and sluggishness #footnote[Idleness.] of servants. These are faults too too common. #emph[Solomon] much inveigheth against these vices, setting them forth in their kind, and setting down the many mischiefs that follow thereupon.

Thus he deciphereth them; #footnote[#emph[Pro.] 26. 13, 14, 15.] #emph[The slothful man saith, there is a Lion in the way] (that is, he pretendeth unlikely danger) #emph[As the door turneth upon the hinges, so a slothful man upon his bed. The slothful hideth his hand in his bosom, it grieveth him to bring it again to his mouth.] #footnote[#emph[&] 24. 33.] #emph[Yet a little sleep, a little slumber, a little folding of the hands to sleep.]

These are the mischiefs which he noteth to come from idleness and sloth, #footnote[#emph[&] 10. 4.] #emph[Poverty,] #footnote[#emph[&] 12. 24.] #emph[Servitude,] #footnote[#emph[&] 13. 4.] #emph[Fruitless wishes and desires,] #footnote[#emph[&] 19. 15.] #emph[Hunger,] #footnote[#emph[&] 20. 4.] #emph[Beggary,] #footnote[#emph[&] 21. 25.] #emph[Death.] And to show what small joy or comfort masters may have in slothful servants, he compareth them to vinegar and smoke, which are as irksome to the teeth and eyes as can be: #footnote[#emph[&] 10. 26.] #emph[As vinegar] (saith he) #emph[is to the teeth, and smoke to the eyes, so is the sluggard to them that send him.] And because many idle packs think and say they do no hurt, he further saith, that #footnote[#emph[&] 18. 9.] #emph[He that is slothful in his work is brother to him that is a great waster:] in which respect Christ styleth a slothful servant, #footnote[#emph[Mat.] 25. 26, 30.] #emph[a wicked] and #emph[unprofitable servant:] and giveth him the portion of those who do much hurt.

How lightly soever many servants esteem idleness and sloth, the truth is, that it is a plain theft. For the best service that servants can do, is due to their master: and they ought to be as diligent in their masters work, as if it were their own. So as it is not enough to avoid idleness in doing nothing at all, but they must take heed that they be not slothful in doing something: for #emph[as good not at all, as never a whit the better.]

I have the further pressed this point, because it is noted as a blemish in such servants as profess religion to be most lazy and negligent, least sedulous and diligent. Much of that time which they should spend about their masters business (which is their particular calling) they spend in prating about state, and Church-business, (matters not belonging to them.) Thus they make their masters weary of their service; and by reason thereof they are oft shifted from house to house, and as #emph[rolling stones, gather no moss:] they neither learn skill, whereby they may, when they are of themselves, maintain themselves, and do good to others: nor lay up any stock or portion, as others which are diligent do: yea they get such an habit of idleness, as they can never shake it off again: for they who are slothful being under masters, seldom prove diligent when they are for themselves. In these is #emph[Solomons] proverb verified, #emph[The talk of the lips tendeth only to penury.] #footnote[#emph[Pro.] 14. 23.]

=== §. 25. #emph[Of servants faithfulness.]

It was #footnote[§. 23.] before noted, that the #emph[good will] here required of servants to their masters had respect to the profit and benefit which servants by their service might bring to their masters: and in that respect it compriseth #emph[faithfulness] under it, #emph[Faithfulness] (I say) whereby servants do well discharge that trust which is committed to them. Expressly it is commanded to servants, #footnote[#emph[Tit.] 2. 10.] #emph[To show all good faithfulness,] and #footnote[1 #emph[Cor.] 4. 2.] #emph[it is required in stewards that a man be found faithful.] The phrase which is used of #emph[Moses,] #footnote[#emph[Heb.] 3. 5.] #emph[He was faithful as a servant,] showeth that faithfulness by a kind of propriety appertaineth to a servant: and #footnote[#emph[Mat.] 25. 21.] where Christ coupleth these two, #emph[good] and faithful, he giveth us to understand that a servants #emph[goodness] consisteth in his #emph[faithfulness.]

Great is the benefit that by servants faithfulness will redound both to master and servant.

The benefit which cometh to the master, #emph[Solomon] noteth in this proverb, #emph[As the cold of snow] (is very acceptable, comfortable #footnote[#emph[Pro.] 25. 13.] and profitable) #emph[in the time of harvest] (when men are even sweltered with heat) #emph[so is a faithful messenger to them that send him: for he refresheth the soul of his masters:] and again in this, #emph[A faithful ambassadour is health,] that is, he bringeth safety to his master. #footnote[#emph[Pro.] 13. 17.]

The benefit which redoundeth to the servant himself by his faithfulness Christ noteth in this his approbation, and remuneration thereof, #emph[Well done thou good and faithful servant,] #footnote[#emph[Mat.] 25. 21.] #emph[thou hast been faithful over a few things, I will make thee Ruler over many things, enter thou into the joy of thy Lord.] Every servant shall be called to his account: if not by his master on earth, yet by his master in heaven: he will say to every one, #emph[Give an account of thy stewardship:] now then if servants have not been #footnote[#emph[Luk.] 16. 2.] faithful, what other discharge can they look for, then that which the wicked, slothful, and unprofitable servant (who hid his talent in a napkin) received, namely this, #emph[Cast ye the] #footnote[#emph[Mat.] 25. 30.] #emph[unprofitable servant into outer darkness, there shall be weeping and gnashing of teeth.] Let all unfaithful servants note this: for to faithfulness is contrary all unfaithfulness, as negligence, deceit, thievery, treachery, and such like vices. Much damage, disgrace, and vexation is brought by such servants to masters: and better it had been that they never had come into a mans house.

But that the point of faithfulness may be the better discerned, and observed, I will exemplify it in seven particulars whereabout it ought especially to be exercised, which are, 1. The #emph[Goods,] 2. The #emph[Businesses] and affairs, 3. The #emph[Counsels] and secrets, 4. The other #emph[servants,] 5. The #emph[children,] 6. The #emph[Bedfellow,] 7. The #emph[person] of their master or mistress.

=== §. 26. #emph[Of servants faithfulness about their masters goods.]

Two things are required of servants to testify their faithfulness about their masters goods. #footnote[1.]

- 1\. A safe keeping of them.
- 2\. An increasing of them.

1. Whatsoever is committed by masters unto their servants, they must so carefully preserve, as it be not lost, spoiled, or impaired #footnote[Servants must well preserve their masters goods.] under their hands, whether they be things within doors, or without. I may to this purpose not unfitly apply that charge unto servants which in another case the Apostle gave to #emph[Timothy,] #footnote[1 #emph[Tim.] 6. 20. τὴν παρακαταθήκην φύλαξον.] #emph[Keep that which is committed to thy trust:] the Metaphor is taken from servants, and so showeth what is their duty. Great was #emph[Josephs] faithfulness in this kind, which made his master #footnote[#emph[Gen.] 39. 4.] #emph[put all that he had into his hand.] So great was #emph[Jacobs] faithfulness, that #footnote[#emph[&] 31. 38, 39.] in twenty years his masters ewes and she Goats, being under his hand, cast not their young, nor the Rams were devoured: if any thing were torn of beasts, he brought it not to his master, but bare the loss of it himself. If servants espy any damage or hurt done by others to their masters goods, they must redress it, if they can, or at least make it known to their masters, that he may give order for the redressing of it: as the servants of him that sowed good seed among which tares were sowed, mentioned #footnote[#emph[Mat.] 13. 27.] in the parable.

Masters that put servants in trust, securely go about other affairs, and look not themselves to those goods which are under their servants custody, which is to be presupposed they would do, if they trusted not their servants. Great reason therefore it is that servants be careful of those things which are so committed to them.

2. They ought further to do what lieth in them to advance #footnote[Servants must endeavour to increase their masters estate. #emph[Gen.] 30. 30. #emph[Mat.] 25. 16, 17.] their masters estate, and to increase his stock. #emph[The little which Laban had was] by #emph[Jacobs] faithfulness in this kind #emph[increased unto a multitude.] The talents which were committed to the two faithful servants were by their industry increased to as many more. So as it is not sufficient for servants not to impair their masters estate, but they must better it: for he that kept safe his masters talent, and gave him his own again, was counted an unprofitable servant, and received the doom of wasters.

Most masters take servants for their advantage and benefit, for it is but little ease for a master to provide diet and lodging for many servants, and to give them wages, if they reap no profit and benefit by them.

=== §. 27. #emph[Of servants carelessness over their masters goods.]

Contrary to servants #emph[fidelity] in safe keeping their masters goods committed to their charge is #emph[Carelessness] and negligence in suffering loss and damage come to their masters as in the fields, when they look not to his fences and gates: or neglect his cattle so as they be stolen, or suffer diseases to grow upon them, or give them not fodder and water in due season. Or in the house, when they leave doors or windows open, and thieves come in and take away, or hook out their masters goods: or carelessly leave the fire, or let candles burn so as the house may be set on fire: or suffer household-stuff, and apparel to lie till it be moth-eaten or otherwise spoiled: or suffer any thing in the house to be broken: or victual to lie in corners moulding, or to be cast up and down for dogs and cats. When Christ so increased the bread and fish, wherewith many thousands were fed, that many fragments were left, he bid his disciples gather up what remained, and rendered this reason, #emph[that nothing be lost.] The damage which may come by #footnote[#emph[John] 6. 12.] servants carelessness, may be more then ever they can be able to make satisfaction for: and therefore they ought the more carefully to prevent it.

=== §. 28. #emph[Of servants fraud.]

Contrary to the other branch of servants #emph[faithfulness] in increasing their masters estate, is all manner of theft and fraud, whether it be by retaining that which is due to their masters, or by purloining from them that which they have. #footnote[#emph[Tit.] 2. 10. μὴ νοσφιζομένους.] The Apostle expressly forbiddeth servants to #emph[purloin.] The word translated #emph[purloin,] is the same whereby the fraud of #emph[Ananias] is set forth, who #footnote[#emph[Acts] 5. 2. ἐνοσφίσατο.] #emph[kept back] part of the price of a possession which they sold: so as thereby is forbidden not only open and manifest stealth, as pilfering money out of their masters purse, chest, or counter; or conveying away their corn, wares, or any other goods: but also putting more into the account of expenses then hath been expended, or into the account of debts less then is due (as the unjust steward, who for a debt of an #emph[hundred] measures of oil put in #emph[fifty,] and for an #emph[hundred] of #footnote[#emph[Luke] 16. 6, 7.] wheat put in #emph[fourescore)] or spending more then needs, or bringing in ill company into the house when their masters are absent, and entertaining them on their masters cost, or concealing part of the price which hath been taken for any wares, or borrowing money in their masters names, or taking greater fees then their masters wot of, or receiving bribes or gifts which their masters refuse (as #emph[Gehazi)] or hiring others to do their work upon their masters cost, or inveigling away their masters #footnote[2 #emph[King.] 5. 22.] customers, or purloining away other mens goods committed to their masters trust (as Tailors servants, who thereby both much discredit their masters, and also hinder their custom.)

#strong[#emph[Object.] What if masters detain their servants wages? may they not by privy means right themselves?]

#emph[Answ.] A masters sin is no warrant to make servants answer sin with sin. The law is as open for servants as for masters: if not, Gods ears are open for their complaints: he can and will redress all, or here or hereafter. #footnote[#emph[Gen.] 31. 42.] Note #emph[Jacobs] example. Many make this a just pretence: but whether it be just or no, it is not safe to open this gap of deceit.

These and such like kinds of deceit are the more heinous sins because of that trust which masters repose in servants: for they violate both the bond of justice, and of fidelity also. If a servant embezzle or defraud his master of any of his #footnote[21\. Of Hen. 8. Stat. 7. And 5. of Eliz. Stat. 10.] goods to the value of forty shillings, he is adjudged a felon by our statute law.

=== §. 29. #emph[Of servants faithfulness in the businesses which they are to dispatch for their masters.]

In the businesses which masters commit to the care of #footnote[II.] their servants to be dispatched by them, they must do their best endeavour that all may prosper under their hands: as it is noted of #emph[Joseph,] #footnote[#emph[Gen.] 39. 2.] #emph[he was a prosperous man:] we have not only a pregnant proof, but also an excellent direction for this point, in the #footnote[#emph[Gen.] 24.] example of #emph[Abrahams] servant, who was very faithful in dispatching the business of fetching a wife for #emph[Isaac:] therein let these particulars be noted.

1. He feared God: the whole carriage of that business testifieth as much. There is a double bond to tie servants hereunto: one in respect of themselves, that in the thing which they do they may be accepted of God: another in respect of their masters, that their masters business may prosper under their hands: God prospereth such as fear him, in all things they take in hand: instance the examples of #footnote[#emph[Gen.] 30. 27.] #emph[Jacob,] #footnote[#emph[&] 39. 2.] #emph[Joseph,] and #footnote[1 #emph[Sam.] 18. 14.] #emph[David.]

2. He #footnote[#emph[Gen.] 24. 12.] called upon God to prosper his endeavours: now prayer is the best means that possibly can be used to obtain any blessing from the Lord. Without it all our endeavours are vain (#footnote[#emph[Psal.] 127. 2.] #emph[It is in vain to rise up early and sit up late, and to eat the bread of carefulness, except Gods blessing accompany all.)]

3. He #footnote[#emph[Gen.] 24. 27.] gave thanks when he saw the Lord begin to prosper that he took in hand: thanksgiving for the beginning of a blessing, is an effectual means for continuance of that blessing: yea it is also an effectual means to move God to prosper other things that we take in hand: so as, if servants desire to prosper in all the affairs which they undertake for their masters, they must render thanks for the first success which he hath given, and so for the second, third, fourth, and for every success.

4. He took all the opportunities he could: #footnote[#emph[Gen.] 24. 17, 23.] when he saw a maid to inquire of, he ran to her, and inquired what was behoveful for his matter: when he had ground to think she was the maid, #footnote[#emph[Vers.] 22.] he presented gifts to her: #footnote[#emph[Vers.] 33.] so soon as he was brought to the house, he falls upon the matter for which he came, even before he did eat any thing: after matters to his liking were concluded, he maketh no tarrying, but with all speed carrieth the maid to #emph[Isaac.] In a word, he omitted nothing that in the uttermost of his wisdom he conceived to be behoveful for that matter: more he could not have done, if the matter had wholly concerned himself. I shall need no further to urge this point, then by setting this pattern before servants.

Contrary is their disposition who care not whether the things which they do for their master prosper or no: if they have taken any pains therein, so as their master cannot say they have altogether neglected it, there is all that they care for. If it succeed not well, they will say they are not in Gods place to make every thing which is done to prosper. But though the whole blessing rest in God, yet hath he sanctified means for obtaining his blessing (as faith, prayer, thanksgiving, and the like) which because they use not, they fail in this point of faithfulness. Nay further, they use those things which do mainly hinder and keep away Gods blessing, and in stead thereof bring a curse upon all they do, as profaneness, uncleanness, drunkenness, and all manner of riotousness, yea despising Gods word and holy ordinances, reproaching his Saints, taking his name in vain by swearing, forswearing, and blaspheming, lying, also backbiting, pilfering, and other like vices. These irreligious and wicked servants, as they sin against God and their own souls, so also against their master: it is not for masters profit to keep such servants.

=== §. 30. #emph[Of servants faithfulness in keeping their masters secrets, and concealing their infirmities.]

By reason of that near bond which is betwixt master #footnote[III.] and servants, and their near and continual abiding together, and the many employments which masters have for their servants, servants come to know many of their masters secrets: #emph[faithfulness] therefore requireth to keep them close. Provided that they be not such secrets as tend to the dishonour of God, or to the danger of the commonwealth and Church, no nor of a private person: for #footnote[1 #emph[Sam.] 20. 12.] #emph[Jonathan] is commended for discovering the mischief which #emph[Saul] had secretly intended against #emph[David.]

For proof of the point, note what #emph[Solomon] saith, #footnote[#emph[Pro.] 11. 13.] #emph[He that is of a faithful spirit concealeth a matter:] namely, a secret matter. Note also how faithful #footnote[#emph[Jer.] 38. 27.] #emph[Jeremiah] was in keeping #emph[Zedekiahs] counsel: though the Princes enquired after it, yet would he not reveal it to them.

To this head is to be referred a faithful concealing of masters infirmities: for the best that be are subject to many: and servants which are under their masters roof continually waiting on them, cannot choose but espy many: if herein servants be not faithful, masters were better be without servants in their houses.

Contrary to keeping close the secrets of masters, is blabbing abroad all such things as servants know concerning their masters: which is too common a fault: for when servants of divers houses men or maids meet together, all their talk for the most part is of their masters and mistresses, whereby it cometh to pass that all the secrets of an house are soon known about the whole town or city. #emph[Solomon] styleth such an one a #emph[tale-bearer: A tale-bearer,] saith he, #emph[revealeth secrets:] or, #emph[he that] #footnote[#emph[Pro.] 11. 13. #emph[&] 20. 19.] #emph[revealeth secrets is a tale-bearer:] for many of #emph[Solomons] proverbs are convertible, they may be turned either way. Now note how #emph[Solomon] noteth out the mischiefs that tale-bearers work: #emph[The words of a tale-bearer are as wounds,] (they wound the precious name and credit of a man) #emph[and they go down into the innermost] #footnote[#emph[Pro.] 18. 8.] #emph[part of the belly,] that is, they do, as it were, strike through the very heart of a man. Again he noteth them to be the cause of all strife, and to raise discord betwixt #emph[chief friends:] and in #footnote[#emph[Pro.] 16. 28. #emph[Pro.] 26. 20.] that respect fitly resembleth them to #emph[wood] which is the very fuel of fire. What enemies then are such servants to an house? They are even as treacherous spies, the most dangerous enemies that be. Thus we see that this is no light sin: yet is it so much the more odious when masters and mistresses infirmities (the publishing whereof may much impair their credit) are made known.

=== §. 31. #emph[Of servants faithfulness in helping one another.]

Where many fellow servants are together, #emph[faithfulness] requireth that one be helpful to another in what they may; #footnote[IV.] as by good example, good counsel, encouragement in good courses, dissuasion from lewd and wicked practises, peace and unity, with the like. The Lord Christ expressly calleth such an one a #emph[faithful servant,] and pronounceth him #emph[blessed.] #footnote[#emph[Mat.] 24. 45, 46.]

Example and advice of one equal prevaileth much with another, so as a fellow servant may in this kind do more good then the master himself: and if by his means he bring his fellow servants to be faithful, his own faithfulness is doubled and trebled; and his master receiveth a double and treble benefit thereby: namely the benefit of this good servants faithfulness, and the benefit of all the other servants faithfulness whom he hath made faithful.

Contrary is their practise who by their ill example corrupt #footnote[#emph[Mat.] 24. 49.] their fellows (as that evil servant, who, when his master was away, #emph[did eat and drink with the drunken,] that is, did cause #footnote[#emph[Gen.] 37. 18, #emph[etc.]] others to be drunken with him) or by ill counsel draw one another on to evil (as the sons of #emph[Jacob,] who when they saw #emph[Joseph] a far off, said one to another, #emph[Behold this dreamer] #footnote[#emph[Mat.] 24. 49.] #emph[cometh, come now and let us slay him, etc.] and as they, who, when they saw their masters son, said among themselves, #emph[This is the heir, come let us kill him, and let us seize on his inheritance)] or are ever quarrelling with their fellows, and smiting them (as that forenamed evil servant whom the Lord threateneth to cut off) or dissuade one another from obedience and subjection (as they who said, #emph[Let us break their bonds] #footnote[#emph[Psal.] 2. 3.] #emph[asunder, and cast away their cords from us;] and as #emph[Sheba,] who said, #emph[we have no part in David: every man to his tents O Israel.)] #footnote[2 #emph[Sam.] 20. 1.] These faults are very rife among servants: whence it cometh to pass that there are so few good, and so many bad servants: too true is this proverb, #emph[One scabbed sheep mars a whole flock.] Let there be in a great family one servant that is profane, proud, riotous, stout, rebellious, or otherwise vicious, and all will soon be like him.

Among other parts of unfaithfulness in this kind one of the most monstrous (which yet is too too frequent) is to allure one another to uncleanness, and men and maids to defile one another. We showed #footnote[§. 11.] before, that it was unlawful for servants during the time of their service to marry without their masters consent: how abominable then is it to defile one another? The sin is doubled being betwixt servants: for as it is a beastly sin in it self, so in the forenamed respect it is greatly dishonourable to their master and his house: besides that the maid so defiled is oft disabled to do her service well: nay many times the charge of the child lieth upon the master. Thus shame and dishonour, grief and vexation, loss and damage all meet together, the more to gall & pierce him to the very heart. Is not this then a great part of unfaithfulness? Deserveth it not to be severely punished, and that openly, and publicly with shame and smart too, that others may take warning thereby? Many use means to escape the revenging hand of man: but though they escape mans hand, they shall be sure to meet with Gods heavy vengeance: #emph[whoremongers God will judge.] Daily experience showeth what misery #footnote[#emph[Heb.] 13. 4.] such wretches bring themselves unto, and how God meeteth with them, and that most fearfully.

=== §. 32. #emph[Of servants faithfulness about their masters children.]

Great faithfulness may servants manifest to their masters #footnote[V.] in and about their children: as while they are young and not able to look to themselves, to be tender over them, and well to tend them: maids especially neatly to handle and look to them, and cleanly to bring them up: and they that have a particular charge of them, to seek their good in every thing they can, and give them their due portion: and (because children are much in servants company) to use in their hearing such speech as may minister grace to them, and to teach them good things, and (when they grow to some ripeness of years) to bear a reverend respect to them, and esteem them their betters because they are their masters children. It is noted of #emph[Abrahams] servant, that he called his masters #footnote[#emph[Gen.] 24. 65.] son, #emph[master.]

Children are dear to parents: the honour and kindness done to them they account as done to themselves: this kind of faithfulness therefore must needs be highly esteemed by masters in their servants: and assuredly it is a great means to work a good respect in masters towards them.

Yet #emph[Contrarily] do many servants carry themselves towards #footnote[Points of unfaithfulness in servants about their masters children.] their masters children, as is apparent by these particulars.

1. Some in their carriage are very hoggish and churlish to their masters children when their parents are out of sight.

2. Others are very careless of them, and tend them very sluttishly, not caring how they go: whereby they oft procure great displeasure from their master and mistress.

3. Others get from their masters children what they can: and deprive them of their allowance, turning it to their own gain.

4. Others exceedingly corrupt their masters children with their filthy and corrupt communication: teaching them to swear, blaspheme, and use all manner of unclean speeches: thus is that proverb verified, #emph[evil communications] #footnote[1 #emph[Cor.] 15. 33.] #emph[corrupt good manners.] Children oft times in their young years learn such ill language and behaviour of lewd servants, as their parents can never get them to leave again: so as they may curse the day that ever such servants came into their house.

5. Others allure them to stage-plays, to dice-houses, and other like places, which are the very bane of youth: and draw them to spend in riot such allowance as their parents allow them, yea and beyond that allowance, so as they run in debt, and get such an habit of spending, as at length they make away their whole estate.

6. Others inveigle their affections: and oft draw them to folly and uncleanness. This filthy kind of unfaithfulness is so much worse then that which was #footnote[§. 31.] before noted betwixt fellow servants, by how much nearer and dearer children are to their parents then servants to their masters.

7. Others that dare not commit this abominable wickedness, stick not to do that which is little better, namely to draw them on to be contracted, yea and married to them often times, and that privily without consent of their parents: whereby parents affections are oft so alienated from their children, as they will not acknowledge them for children, but clean cast them off. These are the fruits of this lewd kind of unfaithfulness in servants.

=== §. 33. #emph[Of servants faithfulness in regard of their masters, or mistresses bed-fellow.]

So faithful ought servants to be to their masters and #footnote[VI.] mistresses, that if one of them should labour to use a servant in any manner of deceit to the other, the servant ought not to yield. As if a master should move his maid privily to take away jewels, plate, money, linen, or any such thing as is in her mistress custody. It skilleth not that the master hath the chiefest power over all the goods: a secret taking of them away without the privity of the mistress in whose custody they are, is in the servant deceit, and a point of unfaithfulness. Much less ought any servants be moved by their mistress privily to take away their masters corn, wares, or any goods for her private use. Of the two this is the greater part of unfaithfulness.

If such deceit ought not to be used about any goods, much less about the body of master or mistress. As if a master should allure his maid to commit folly with him, or a mistress her man, both their conscience to God, and also their faithfulness to their master or mistress should make them utterly to refuse it, and to give no place to any such temptation. #footnote[#emph[Gen.] 39. 7. #emph[etc.]] #emph[Joseph] is propounded as a pattern herein: and against the suggestion of his mistress he rendereth the two forenamed reasons: his conscience to God in these words, #emph[how can I do this great wickedness and sin against God?] His faithfulness to his master in these, #emph[He hath not kept back any thing from me but thee, how then] etc.

To this head may be referred servants faithfulness in making known to their master the sin of his wife, and to their mistress the sin of her husband, especially if it be such a sin as may tend to the ruin of the family, and that by the knowledge thereof, the party that is not blinded and besotted with the sin, but rather free from it, may be a means to redress it. Thus #footnote[1 #emph[Sam.] 25. 14.] #emph[Nabals] servants made known to #emph[Abigail] the churlishness of #emph[Nabal] towards #emph[Davids] servants: by which means the mischief intended against the house was prevented. Thus if servants know that their master intendeth some mortal revenge against another, to tell his wife thereof in time, may be great faithfulness: or if they know their mistress hath appointed to go away privily from her husband, to tell him of it, is a part of faithfulness. This may be applied to many other like cases.

The contrary is yielding to masters or mistresses in any point of deceit one against another: whereunto servants are too prone, because they think to be bolstered out by the authority of the party that setteth them on work to deceive. But no authority can be a warrant for any deceit, or wickedness.

=== §. 34. #emph[Of servants faithfulness about their masters persons.]

Masters and mistresses are flesh and blood as well as servants, #footnote[VII.] and so subject to weakness, sickness, old age, and other distresses, wherein they may stand in great need of servants help: servants therefore must be faithful in affording them the best help that they can. #emph[Sauls] servants did a part of faithfulness to their master, when, he being vexed with an evil spirit, #footnote[1 #emph[Sam.] 16. 16.] they inquired after means to ease him. So did #emph[Davids] servants, when he being bedrid, #footnote[1 #emph[King.] 1. 2.] they sought out one to cherish him. It was a point of faithfulness in #emph[Naamans] #footnote[2 #emph[King.] 5. 3.] maid, to tell her mistress of a means whereby her master might be cured of his leprosy: and in his #footnote[#emph[vers.] 13.] servants, to persuade him to use the means prescribed by the Prophet.

Contrary is a servants ungrateful and inhumane leaving of his master in his time of need, as the servants of #emph[Job] did: for when the hand of God lay heavy upon him, and all his goods were taken from him, and his body full of sore boils, #footnote[#emph[Job] 19. 15, 16.] #emph[they that dwelt] #emph[in his house, and his maids counted him for a stranger: and he was an aliant in their sight: he called his servant, and he gave him no answer.] So did #footnote[2 #emph[Sam.] 19. 26.] #emph[Ziba] leave #emph[Mephibosheth] in his greatest need: and #footnote[#emph[Mat.] 26. 56.] the Disciples fly from their master Jesus Christ. But what shall we say of those that take occasion from their masters impotency to murder him themselves, as #footnote[2 #emph[Sam.] 4. 6.] #emph[Rechab] and #emph[Baanah;] or to betray him to his enemies, as #footnote[#emph[Mat.] 26. 15.] #emph[Judas] betrayed the Lord Christ? What, but that such traitorous servants may look for such ends.
