== A Servant’s Duty and Its Limits under God

=== §. 35. #emph[Of the means to make servants faithful.]

Among many other means to make servants faithful to their master, and careful to perform other duties sincerely, willingly, cheerfully, and diligently, as hath before been noted, this is one of the most general, namely, that #emph[servants,] in all things they do for their master, #emph[make their masters case their own,] and so do for him as they would for themselves, or as they would have their own servants do for them. The general rule of the Law is, #footnote[#emph[Lev.] 19. 18.] #emph[love thy neighbour as thy self;] and #footnote[#emph[Mat.] 7. 12.] #emph[whatsoever you would that men should do to you, do you even so to them.] If thus every man must respect another, yea though he be a stranger, then much more must servants respect their master, because all that they can do is after an especial manner as a debt due to their masters: in which respect Christ saith, that #emph[when they have done all that is] #footnote[#emph[Luke] 17. 10.] #emph[commanded, they have but done their duty.]

This I have the rather noted, because the practise of most servants is contrary thereunto. For while they work for their masters, they will cry out that they are over-burdened, and tired with that work which they will easily go through withal when they work for themselves. They that while they work for their master, must be called to it again and again, and forced to stand to it, and to hold out till it be done, what pains will they take, how early will they rise, how late will they sit up, how diligent will they be for themselves? When Journeymen receive increase of wages according to the work which they do, they will dispatch more then a prentice that hath but cloth, food, and lodging. Again, many that in their masters goods are very lavish, and wasteful, when they come to be for themselves are very sparing, saving, and provident. What do these things argue but that servants do not bear to their masters that mind which they should: they do not for them as they would do for themselves. Very requisite it is therefore that the forenamed general rule be observed.

Hitherto of the several kinds of servants duties, and of the manner of performing them. It remaineth to speak both of the extent of their duties, and also of the restraint of that extent.

=== §. 36. #emph[Of servants endeavour to make their judgment agree with their masters.]

The extent of servants duties is in my text only implied under this indefinite particle #emph[(Obey)] (which being not restrained to any particulars, must be extended to #emph[every thing)] but in other places it is expressly laid down in these general terms, #footnote[#emph[Col.] 3. 22.] #emph[Obey in all things,] #footnote[#emph[Tit.] 2. 9.] #emph[Please well in all things.] It is not therefore sufficient that servants perform their duties well in some things, they must do it in all things, yea in things that may be against their own mind and liking, if their master will have it so. For this end let servants note these two rules. The same extent and restraint #footnote[Extent of servants duties.] that was #footnote[Treat. 3. §. 63, #emph[etc.] & Treat. 5. §. 35.] before noted in laying forth the duties of other inferiors, is here also to be observed in the duties of servants: for therein they all agree. The same rules therefore that were before set down, may here again be applied. I refer the reader to those places for a more large amplification of the generals: and here I will content my self with adding such particular proofs as are most proper and pertinent to servants.

1. That they #emph[labour to bring their judgment to the bent of their masters judgment,] and to think that meet and good which #footnote[Servants must labour to bring their judgment to agree with their masters.] he doth. Thus the #footnote[#emph[Judg.] 19. 11, 12, #emph[etc.]] servant of the Levite which thought it meetest to turn into one of the Cities of the Jebusites to lodge there, because the day was far spent, when he saw his master to be of another mind, yielded to him. So did #footnote[#emph[Luk.] 19. 25, #emph[etc.]] those servants yield to their master, who at first thought it unmeet that he that had ten talents should have one piece more: and #footnote[#emph[Mat.] 13. 28, #emph[etc.]] those servants also, that at first thought it meet that the tares should be plucked up from the wheat. This rule is to be observed in the particular points before delivered, as the work which servants do, and the manner of doing it, their apparel, their allowance, yea and in the correction which their master giveth them, and the rest.

Contrary is that great conceit which many servants have of #footnote[Servants conceit of their own wit.] their own judgment, wit, and wisdom, thinking themselves wiser then their masters; as #emph[Gehazi,] who opposing his own wit to his masters wisdom, said, #footnote[2 #emph[King.] 5. 20.] #emph[Behold my master hath spared Naaman this Syrian, in not receiving at his hands that which he brought: but as the Lord liveth, I will run after him, and take somewhat of him.] This was also a fault in #footnote[2 #emph[King.] 2. 16.] the children of the Prophets, that would not rest on #emph[Elishas] judgment, but importuned him against his mind to send some to seek the body of #emph[Elijah.] This self-conceit is the cause of many mischiefs: as of discontentedness at the work their master appointeth them, and at the allowance of meat and drink which they have; of much liberty they take to themselves, of pride in apparel, and other vices before noted: if the forenamed rule were duly observed, many of those mischiefs would be avoided, and much better obedience yielded.

=== §. 37. #emph[Of servants yielding to do such things at their masters command, as they cannot think to be most meet.]

The second rule which servants must observe is this, that

#emph[Though they cannot in their judgment think that fit to be done which their master will have done, yet upon his peremptory command they must yield to the doing of it:] It appeareth by #emph[Peters] answer to Christ that he did so, for being commanded to let down his net for a draught, thus he answereth, #emph[master, we have toiled all the night, and have taken nothing] (here he showeth that #footnote[#emph[Luke] 5. 5.] his opinion was that it would be in vain to let down their nets) #emph[nevertheless at thy word I will let down the net] (here is his obedience against his opinion.) More clear is the example of #emph[Joab] for this purpose: when the King commanded him to number the #footnote[2 #emph[Sam.] 24. 2, #emph[etc.]] people, he declared that he thought it a very unmeet thing to do, by this phrase, #emph[Why doth my Lord the King delight in this thing?] yet against his judgment he yielded to the Kings peremptory command, for it is said, that #emph[the Kings word prevailed against Joab.]

#strong[#emph[Object.] This is no fit example, because #emph[Joab] sinned in obeying.]

#emph[Answ. Joab] cannot justly be charged with sin, because it was not simply unlawful to number the people. #emph[Davids] sin was not in the act of numbering the people, but in his mind which moved him to do it: for there was no just cause to do it: only pride and curiosity moved him, as may be gathered out of his own reason in these words, #emph[that I may know the number of the people.] To do such a thing only to know it, was #emph[curiosity.] But why would he know it? Surely on a proud conceit that he had so many worthies, so many Captains, so many men of war.

Out of #emph[Joabs] example servants may here learn in humility and reverence to render some reasons to move their master not to press upon them that which they think to be unmeet; but yet if their master will not hearken to their reasons, but stand upon his authority, #emph[his word must prevail.]

Contrary is their peremptoriness, who by no means will be drawn to do any thing at their masters command, which they themselves think not most meet to be done. Such an one is that fool whom #emph[Solomon] thus describeth, #emph[Though thou shouldest] #footnote[#emph[Pro.] 27. 22.] #emph[bray a fool in a mortar among wheat with a pestle, yet will not his foolishness depart from him.] These fools bring much mischief upon their own pates in disobeying their masters: for exceedingly they provoke his wrath who hath power to take vengeance of them. Neither let them think to receive comfort in their suffering, because they refuse an unmeet thing, for #emph[meetness] is not a sufficient warrant against #emph[unlawfulness.] To disobey in a thing which lawfully may be done, is unlawful: if therefore the pretext be only an #emph[unmeet thing,] meetness is preferred before lawfulness, and unlawfulness less accounted of then unmeetness.

=== §. 38. #emph[Of servants forbearing to obey their master against God.]

That the extent of servants obedience be not too far stretched, #footnote[Restraint of the extent of servants duties] the Apostle setteth down an excellent limitation thereof: and that in these four phrases, #emph[As unto Christ, As the servants of Christ, Doing the will of God, As to the Lord;] all which do show that the #emph[obedience which servants yield to their master] #footnote[See the cautions, Treat. 3. §. 51, 52, etc.] #emph[must be such as may stand with their obedience to Christ.] So that if masters command their servants never so peremptorily to do any unlawful thing, that is, any thing forbidden by Gods #footnote[#emph[Nolite fieri serui hominum, i. nolite eis parere cùm turpia praecipiunt. Chrys. in] 1 #emph[Cor.] 7. #emph[hom.] 19. #emph[Exo.] 1. 17.] word, they may not yield to it. The midwives of the Hebrew women did well in refusing to do any thing to help forward the murderous practises of the King of Egypt in slaying all the male-children of the Hebrews: it is expressly said, that #emph[they feared God and did not as the King commanded them:] so as their disobedience in this kind was a token of their fear of God. In this case #emph[Joseph] is commended for not hearkening to his mistress: and the servants of #emph[Saul] for refusing to slay the #footnote[#emph[Gen.] 39. 9. 1 #emph[Sam.] 22. 17.] Lords Priests at their masters command. Thus if a master should command his servant to kill, to steal, to forswear himself, to lie, to use false measures and weights, to go to mass, or do any other unlawful thing, he ought not obey him.

Again, if masters forbid their servants to do that which #footnote[Seruis competit vt obediant dominis in ijs quibus mandato Dei nihil derogatur. Basil.] God hath commanded them to do, they must, notwithstanding their masters prohibition, do it. The Rulers of Israel forbid the Apostles to preach, yet because Christ had commanded them to preach, they would not forbear: nor would #emph[Daniel] forbear to pray to God, though the King and Nobles #footnote[#emph[Ethic. defin.] 75. #emph[Act.] 4. 19. #emph[Dan.] 6. 10.] by express decree forbad him. So if a profane or popish master shall forbid his servant to go to Church, or to hear the word, or to take the Sacrament, or to dwell with his wife if he be married, or to make restitution of that which he hath fraudulently gotten, or any other bounden duty, herein they must say, #emph[we ought to obey God rather then men.] For when masters #footnote[#emph[Act.] 5. 29.] command and forbid any thing against God, they go beyond their commission, and therein their authority ceaseth.

Contrary to this restraint is both a parasitical pleasing of masters: and also a base fear of them. It is the property of a #footnote[Ais? aio. Negas? nego. Terent. in Eun.] parasite to say what a master will have him say, and deny what he will have him deny, and so to do what he will have him to do. #emph[Doeg] that fawning dog at #emph[Sauls] word slew all the Lords #footnote[1 #emph[Sam.] 22. 18.] Priests: and #emph[Absoloms] servants at his word killed #emph[Amnon:] for #footnote[2 #emph[Sam.] 13. 28, 29.] all the reason which they had to commit that murder was this speech of their master, #emph[have not I commanded you?] So prone are servants to sooth their masters, as there is no sin so horrible which at their masters command they will not be ready to do. Thus is that verified which the Prophet long since foretold, #footnote[#emph[Isa.] 24. 2.] #emph[like master like servant, like mistress like maid.] It is also the property of base fearful servants to do nothing but what their master will have them do, and to forbear any duty, though never so necessary, that he forbiddeth them to do. What duty more necessary then prayer? We are commanded to #emph[pray continually:] yet the servants of #emph[Darius] were content to #footnote[1 #emph[Thess.] 5. 17. #emph[Dan.] 6. 7, #emph[etc.]] forbear that duty thirty days together, because it was against the decree of their Lord and King. The like is noted of the people in Christs time, #emph[they durst not make open profession of] #footnote[#emph[Joh.] 7. 13. #emph[&] 9. 22.] #emph[Christ for fear of the Jews.] So in our days many servants there be that dare not make profession of the Gospel, nor go to Church, nor read the word, nor perform other holy religious duties, which they know to be bounden duties, for fear of their masters. Had not then the Apostle just cause to strike so much upon this string as here he hath done, expressly forbidding #emph[eye-service, man-pleasing,] and #emph[doing service to men,] namely in opposition to God?

=== §. 39. #emph[Of servants choosing good masters.]

As a just consequence following from the forenamed extent and restraint of servants duties, I may further gather these two lessons for servants.

1. It is very behoveful that servants make choice of good masters: at least if it be in their power to choose.

2. It is behoveful that they continue and abide under good masters: at least if they continue servants, and abide under any masters.

That these consequences justly follow as aforesaid, is evident: for seeing servants are bound to obey in all things which are not #emph[against God,] and must obey in nothing but what is #emph[in the Lord,] it is very requisite that servants be under such masters as bear the Image of God in the inward disposition, and grace of their heart, as well as in their outward function and place: and will go along with God in using their authority, commanding nothing but what a servant may do with a good conscience, and without transgressing against God: and forbidding nothing that God hath bound a servant to do. There will be comfort in serving such masters: and our obedience to them will be obedience to God. Such masters therefore must be chosen. Yea and with such must servants abide, (if not with the very same, yet with such as they are, of the same disposition) for if they go to other, their former comfort will be taken away, and their servitude will seem so much the more miserable, by how much more knowledge and experience they have had of the benefit of their former liberty (for #footnote[Qui fidelem habet dominum, saluo eius dominio, diligat vt patrem.] we may well call service under unconscionable masters #emph[servitude,] and in opposition thereunto, service under religious masters, #emph[liberty.)] He therefore that hath a master that is faithful, due respect had to his authority, must love him as a father, and #footnote[#emph[Constit. Apost. l.] 4. #emph[c.] 12.] so abide with him.

For choice of good masters, note what is #footnote[#emph[Exo.] 12. 38.] recorded of many of the Egyptians and other people: they left their own country, and went out with the Israelites: what should move them but conscience of the true God whom they knew that Israel served? Now many of these went out as servants, as may be gathered from those many #footnote[#emph[Lev.] 25. 45. #emph[Deut.] 5. 14. #emph[&] 12. 18. #emph[&] 23. 15. #emph[&] 23. 7.] laws which were made in the behalf of servants that were strangers, and in special that were Egyptians. The knowledge which #footnote[#emph[Ruth] 1. 16.] #emph[Ruth] had that #emph[Naomi] her mother in law served the true God, moved her to leave her own country, and to go as a servant with #emph[Naomi.]

For abiding with good masters we have a worthy pattern in the twelve Disciples. #footnote[#emph[Joh.] 6. 66. #emph[etc.]] When many of Christs Disciples at large, #emph[went back, and walked no more with him,] Christ asking the twelve whether they also would go away, #emph[Peter] in the name of all the rest answered, #emph[Lord to whom shall we go? Thou hast the words of eternal life.]

Contrary is the mind and practise of many servants: they never inquire after the religious disposition of their master, nor care though he be popish, or profane, so they may have good wages, diet and lodging: and yet by this means, if at least there be any spark of Gods fear in their heart, they cast themselves upon many sore temptations, and bring themselves into many hard straits, and dangerous snares. And, if God open their eyes to see that wretched condition whereinto they have implunged themselves, they will be forced to cry out and complain as #emph[David] did, when he was in foreign countries where he could not freely serve his God, #footnote[#emph[Psal.] 120. 5.] #emph[Woe is me that I sojourn in Mesech, that I dwell in the tents of Kedar.]

Much more contrary is their mind and disposition who refuse to serve religious masters, and shun them most of all: or being in their service are never quiet till they be out of it again. Of these we spake #footnote[§. 16.] before.

Hitherto have we dealt about servants duties. The reasons which the Apostle rendereth to enforce those duties remain to be declared.

=== §. 40. #emph[Of the first motive, the place of masters.]

The first reason which the Apostle useth to enforce servants #footnote[I.] duties is implied under this phrase, #emph[as to Christ;] it intimateth the #emph[place] of a master, which is to be in #emph[Christs stead.] In this respect the title #emph[Lord] is given to a master. The word which the Apostle useth in Greek is that which in the new testament #footnote[Κύριος.] answereth to that proper Hebrew name of God #emph[Jehovah,] and it setteth forth the absolute sovereignty of God, and power over all creatures: #footnote[#emph[Matt.] 28. 18.] which power because the father hath given to his son as Mediator, God-man, he is called the #footnote[1 #emph[Cor.] 8. 6. εἷς κύριος.] #emph[one] or #emph[only Lord:] and because masters by virtue of their office and place bear Christs image, and stand in his stead, by communication of Christs authority to them, they are called #emph[Lords,] yea also #footnote[#emph[Psal.] 82. 6.] #emph[Gods] (for that which a Magistrate is in the common-wealth a master is in the family).

Hence it followeth that servants in performing duty to their master perform duty to Christ, and in rebelling against their master they rebel against Christ; as the Lord said to #emph[Samuel] of the peoples rejecting his government, #emph[they have not rejected] #footnote[1 #emph[Sam.] 8. 7.] #emph[thee, but they have rejected me that I should not reign over them.] Is not this a strong motive to provoke servants to all duty, and to restrain them from rebellion? If it be well weighed what Christ is, it cannot be but a weighty reason. For though masters should neither reward their good service, nor revenge their ill service, yet will Christ do both.

=== §. 41. #emph[Of the second motive, the place of servants.]

The second reason is implied under this phrase, #emph[as servants] #footnote[II.] #emph[of Christ:] it noteth the place of a servant: which though it may seem to be a mean and base place, yet is it indeed an honourable place. Men count it an honour to be servants to a King: but Christ is higher then all Kings. On this ground the Apostle saith, #emph[Art thou called being a servant? Care not for it:] #footnote[1 #emph[Cor.] 7. 21, 22.] and that upon this reason, #emph[He that is called in the Lord being a servant, is the Lords freeman.] This reason is to be noted against the conceit that most have of a servants place, that it is so mean and base as there can be no honour nor comfort in doing the duties thereof. But that is a foolish, and unjust conceit: look to Christ the highest master, and there is as much honour, and comfort in doing the duties of the lowest servants place, as of the highest masters.

=== §. 42. #emph[Of the third motive, Gods will.]

The third reason is implied under this phrase, #emph[doing the] #footnote[III.] #emph[will of God,] which declareth the ground of servants subjection. God in his word hath plainly made it known that it is his pleasure that they who are under the authority of masters should obey them, therefore as servants would please God, they must obey: if they refuse to obey, they thwart the #emph[will of God.] This also is a motive of moment: for Gods will is that mark which every one ought to aim at, and it is much urged by the Holy Ghost, as a general reason to all duty in these and such like phrases, #footnote[1 #emph[Thes.] 4. 3.] #emph[This is the will of God,] #footnote[1 #emph[Pet.] 2. 15.] #emph[So is the will of God:] upon which ground we are exhorted to #footnote[#emph[Ephes.] 5. 17.] #emph[understand,] and to #footnote[#emph[Rom.] 12. 2.] #emph[prove what is the will of God.]

Good reason there is to press this reason: for

1. Gods will is the very ground of goodness: things are therefore good because they are agreeable to Gods will: Gods will giveth the very being to goodness.

2. Gods will is a rule to square all our actions by, even as the kings statutes and proclamations are to his subjects.

3. It is a perfect rule #emph[(the law of the Lord is perfect)] so as we #footnote[#emph[Psal.] 19. 7.] may be sure not to swerve, if we hold close thereunto.

4. It is a sufficient rule, it will give every one (and among other, servants) direction how to carry themselves in every thing they take in hand, yea in every thing that appertaineth to them. For, #emph[Gods word is given to make us perfect, thoroughly] #footnote[2 #emph[Tim.] 3. 17.] #emph[furnished unto all good works.]

5. It is a good warrant to justify us in all our actions: so as, going along with it, we need not care what any man can say against us. If a man be sure that he have statute law, or the kings proclamation on his side, he is bold.

From this reason which is of such weight, I gather two propositions to add force to this motive.

1. That servants obey their masters, is no arbitrary matter, but a necessary duty: not left to his will whether he will do it or no, but a thing whereunto he is bound: and that not only by civil constitutions of men, but also by a divine institution of God: so as it is not only a matter of civil policy, but also of conscience, to be done for conscience sake.

2. That no creature can dispense with servants, so as they should be exempted from doing their duty to their master. If they could, they were greater then God, and their will above Gods will. Among creatures, masters themselves are to be reckoned: now because it is Gods will that servants should be in subjection, their masters cannot exempt them from it. Masters may let them go free: but retaining them as servants, they cannot exempt them from a servants subjection. Wherefore though masters be careless in exacting duty, yet let servants be conscionable in yielding duty, because it is Gods will.

=== §. 43. #emph[Of the fourth reason, the reward of good service.]

The fourth reason is plainly and largely expressed in these #footnote[IIII.] words, #emph[Knowing that whatsoever good thing any man doth, the] #footnote[#emph[Sciat seruus Deum redditurum seruitutis mercedem. Constit. Apost. l.] 4. #emph[c.] 12. #emph[Col.] 3. 24.] #emph[same shall he receive of the Lord, whether he be bond or free.] The general sum whereof is a #emph[Declaration of the reward of good service.] To which purpose saith the Apostle to servants in another place, #emph[Of the Lord ye shall receive a reward.]

This first is to be noted to add force to the former reasons. For if any ask, what if masters stand in Christs stead, what maketh that to the purpose? Surely it maketh much to move servants: because masters stand in his room who will reward that which is done for his sake.

If again they ask, what benefit is it to be Christs servant? It may be answered, #emph[very great:] for Christ will reward all his servants.

If further it be asked, what is gotten by doing Gods will?

#emph[Answ.] Even that which all aim at, reward for service.

As this addeth weight to all the other reasons, so is it in it self a weighty reason, as weighty as any can be to our corrupt nature. Hope of reward is it which maketh all sorts of people to take the pains which they do in their several places. But having #footnote[Treat. 1. §. 127.] before handled this general point of reward, I will here more distinctly show what kind of reward it is wherewith the Lord will recompense the good service of faithful servants.

Gods reward is both of temporal and eternal blessings.

The temporal blessings which heretofore God hath bestowed #footnote[What reward God giveth to good servants.] on faithful servants, and which on that ground other like servants may expect, are these especially.

1. He will move masters to respect such servants, as he moved #footnote[#emph[Est.] 6. 3.] #emph[Ahasuerus] to recompense the fidelity of #emph[Mordecai.]

2. If masters fail therein, he will move strangers to recompense them: as he moved #footnote[#emph[Gen.] 39. 21.] the Jailer to favour #emph[Joseph] when his master had cast him in prison: and #footnote[#emph[&] 41. 40.] #emph[Pharaoh] to advance him to great dignity.

3. To draw the hearts of their masters and others the more unto them, he will make the things which they take in hand to prosper. Thus did he bless #footnote[#emph[Gen.] 39. 2.] #emph[Joseph,] and #footnote[#emph[&] 24. 56.] #emph[Abrahams] servant.

4. In dealing for themselves he will bless their labours, as he blessed #footnote[#emph[Gen.] 30. 43.] #emph[Jacobs.]

5. He will, when they come to keep servants, provide such servants for them, as they were to their masters. #footnote[#emph[Gen.] 43. 23.] In Egypt God blessed #emph[Joseph] with a faithful servant. #emph[David,] who #footnote[1 #emph[Sam.] 17. 34.] ventured his life to save his fathers sheep, had #footnote[2 #emph[Sam.] 21. 17. #emph[&] 23. 15.] many servants that ventured their lives for him.

To this purpose may be applied that proverb which Christ oft useth, #footnote[#emph[Luk.] 6. 38.] #emph[with what measure ye mete shall it be measured to you again.]

The eternal reward is expressed in this phrase, #footnote[#emph[Col.] 3. 24.] #emph[the reward of the inheritance,] for that inheritance is meant which Christ mentioneth in this clause, #footnote[#emph[Mat.] 25. 34.] #emph[Come ye blessed of my father, inherit the kingdom prepared for you from the beginning of the world,] and Saint #emph[Peter] in this, #footnote[1 #emph[Pet.] 1. 4.] #emph[an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven.] What can be more said? What shall not be undergone for this reward? How willingly do prentices pass over their apprenticeship in hope of a temporary freedom of an earthly city? #footnote[#emph[Gen.] 29. 20.] Many years service were but as a few days to #emph[Jacob] because he liked his reward. But behold here a greater reward, which we must needs like much better. If this be not sufficient to move servants to all duty, I know not what can be sufficient.
