== Children Giving Back to Parents

=== §. 39. #emph[Of childrens Recompence.]

The generall head whereunto al the duties which children owe to their parents in regard of their #emph[Necessity,] is in one word #emph[Recompence,] which is a dutie whereby children indeauour as much as in them lieth, to repay what they can for their parents kindnesse, care, and cost towards them, and that in way #footnote[#emph[Arist. Ethic. l.] 8. #emph[c.] 14.] of thankfulnesse; which maketh a childe thinke he cannot doe too much for his parent, & well may he thinke so, for a parent doth much more for his childe before it is able to doe for it selfe, then the childe possibly can doe for the parent. So as if the parents #emph[authority] were laid aside, yet the law of #emph[equity] requireth this dutie of #emph[Recompence:] so also doth the law of #emph[piety] and #emph[charity.] Wherefore of all other Duties this is most due. #footnote[1 #emph[Tim.] 5. 4..] It is in expresse termes giuen in charge to children by the Apostle, who willeth them to learne to #emph[requite their parents.]

Contrary is neglect of parents in their need, which is more #footnote[It is monstrous ingratitude for children to neglect their parents.] then monstrous ingratitude. As all ingratitude is odious to God and man, so this most of all, and yet very many are guilty thereof. In them the prouerbe is verified that #emph[loue is weighty.] For it is the property of weighty things to fall downe apace, out to ascend slowly, and that not without some violence. Thus loue from the parent to the childe falleth downe apace, but it hardly ascendeth from children to parents. In which respect another prouerbe saith, #emph[One father will better nourish nine children, then nine children one father.] Many children in his kinde doe no more for their parents, then for strangers. They either consider not how much their parents haue done for them; or else they conceit that what their parents did, was of meere dutie, and needeth no recompence. Fie vpon such barbarous and inhumane children!

=== §. 40. #emph[Of infirmities whereunto parents are subiect.]

The rule of the forenamed recompence is on the one side #footnote[A rule of recompence.] the #emph[parents Necessity,] and on the other, the #emph[childes Ability.] So as in euery thing wherein a parent needeth his childes helpe, the childe to his power must afford his best helpe. #emph[Beyond ones power nothing can be expected.] #footnote[Ultra posse non est esse.]

A parents #emph[Necessity] may be through

+ #emph[Naturall infirmities.]
+ #emph[Casuall extremities.]

Naturall infirmities are

+ #emph[Inward.]
+ #emph[Outward.]

#emph[Inward] Infirmities are weakenesse of iudgement, slipperinesse of memory, violence of passion with the like; whence proceed frowardnesse, testinesse, suspiciousnesse, iealousie, feare, griefe, &c.

#emph[Outward] Infirmities are such as arise from some instant temptation, as were #footnote[#emph[Gen.] 9. 21.] #emph[Noahs] and #footnote[#emph[&] 19. 33.] #emph[Lots] drunkennesse; #footnote[#emph[&] 19. 33.] #emph[Lots] and #footnote[2 #emph[Sam.] 11. 4.] #emph[Dauids] vncleanesse; #footnote[#emph[Gen.] 12. 13.] #emph[Abrahams] and #footnote[#emph[&] 26. 7.] #emph[Isaakes] dissimulation; #footnote[#emph[&] 37. 34, 35.] #emph[Iaakobs] and #footnote[2 #emph[Sam.] 18. 33.] #emph[Dauids] excessiue lamentation, &c.

Some of these latter, which may seeme most heinous and odious sinnes, are then to be accounted infirmities, when they who commit them make not a sport of them, nor delight to liue and lie in them, as swine to wallow and lie in the mire: but only at some times, through some temptation, as it were vnawares, fall into them; and after they are committed they are themselues more ashamed of them, and more grieued for them, then any other that see them, or heare of them.

In regard of the naturall infirmities of parents, the dutie of children is both to #emph[beare with them,] and also to #emph[couer them] so farre as they can.

=== §. 41. #emph[Of childrens bearing with their parents infirmities.]

Children beare with their parents infirmities when they doe not the lesse reuerendly esteeme their place, or person, nor performe the lesse dutie to them because of their infirmities.

This is the first particular branch of recompence. For children in their yonger and weaker yeares are subiect to many infirmities: if parents had the lesse respected them for their infirmities, and from thence had taken occasion to neglect them, and would not haue borne with them, surely they could not haue beene so well brought vp. That great patience, long-sufferance, and much forbearance which parents haue shewed towards their children, requireth that children in way of recompence shew the like to their parents as occasion is offered. It was a great infirmity in #emph[Isaak] to preferre #emph[Esau] a prophane childe, before #emph[Iaakob] a religious childe, especially against Gods expresse word concerning #emph[Iaakob;] yet #emph[Iaakob] respected not his father a whit the lesse for it, as appeares by his #footnote[#emph[Gen.] 27. 12.] feare to offend him, and by his #footnote[#emph[&] 28. 5.] readinesse to obey him. #footnote[#emph[&] 37. 10.] #emph[Iaakobs] vniust reproofe of #emph[Ioseph] was no small infirmity, and yet how much #emph[Ioseph] reuerenced and euery way respected his father the history following sheweth. #emph[Sauls] infirmities were farre more and much greater then any of theirs, yet what dutie and faithfulnesse did #emph[Ionathan] his sonne performe to him, euen to their deaths? for #footnote[1 #emph[Sam.] 31. 2.] he died with him.

We haue herein the patterne of Christ himselfe: how great infirmity did his mother bewray, when ouer-rashly she rebuked him being about a good worke, a bounden duty, his Fathers businesse? yet immediatly thereupon it is noted that #emph[he went downe with his parents, and was subiect to them:] which #footnote[#emph[Luk.] 2. 51.] manifesteth the honour he gaue to his mother, notwithstanding her infirmitie.

Contrary to this duty doe they, who take occasion from their parents infirmities to thinke basely of their person and #footnote[A childe may not dispise a parent for any infirmity.] their place, and thereupon grow carelesse in duty, either refusing to doe any duty at all, or else doing it carelesly, grudgingly, disdainefully, and scornefully. #emph[Absolom] made a supposed infirmity of his father the ground of his rebellion. Had #footnote[2 #emph[Sam.] 15. 3.] his pretence beene true, yet had it not beene a sufficient cause for him to disgrace, and rise against his father, as he did. The law that threatneth Gods vengeance against such children as #emph[mocke at their father, or despise to obey their mother,] maketh #footnote[#emph[Pro.] 30. 17.] no exception of parents infirmities.

=== §. 42. #emph[Of childrens couering their parents infirmities.]

Children couer their parents infirmities both by passing by them (as we speake) and taking no notice of them, and also by concealing them from others as much as they can. The Scripture noteth it to be a property of #emph[loue] to #emph[couer a multitude] #footnote[1 #emph[Pet.] 4. 8.] #emph[of sinnes:] now in whom should loue abound, if not in children? And who should more manifest this property of loue then children?

Of passing by and concealing from others a parents infirmity, we haue a worthy patterne in #emph[Shem] and #emph[Iaphet:] when #emph[Noah] their father being drunken lay vncouered in the midst of his tent, #emph[they went backward] (that they might not themselues #footnote[#emph[Gen.] 9. 23.] see their fathers infirmity) and #emph[couered his nakednesse] (that others might not see it.) The blessing which vpon this occasion was then promised to them and their posterity, sheweth how acceptable this dutie was to God.

Contrary was #emph[Chams] practise, who discouered, and made #footnote[A Sinne for a childe to discouer a parents infirmity.] knowne his fathers nakednesse. The curse thereupon denounced against him, sheweth how odious that sinne was vnto God. Too many there be of #emph[Chams] cursed brood, who blaze abroad their parents infirmities, and make such things knowne of them, #footnote[#emph[Gen.] 9. 22. #emph[Vers.] 25.] as otherwise would not be knowne: whereby they bring much dishonour and shame vpon their parents (which can be no honour #footnote[#emph[Parent is imprecatione nihil perniciosius excogitari potest. Plato de Leg. lib.] 11.] to the children,) and withall a curse from their parents on themselues, which the heathen accounted very dreadfull.

More contrary was #emph[Absoloms] practise, who raised a most malicious slander of his father, and thereby alienated his subiects hearts from him. Too many #emph[Absolom-]like seeke to raise a supposed #footnote[More then monstrous for a childe to raise a slander of a parent.] reputation and honour to themselues by vilifying and disgracing their parents: but let them note #emph[Absoloms] end. Assuredly, if they hold on in that course, the like, or a worse, shall be their end.

=== §. 43. #emph[Of childrens bearing with their parents casuall necessities.] #footnote[2 #emph[Sam.] 15. 3.]

Casuall extremities, are all manner of crosses which by the prouidence of God are laid vpon a man: whether vpon his bodie, as blindnesse, lamenesse, sicknesse, &c. or on his person, as captiuitie, banishment, imprisonment, &c. or on his estate, as pouerrie, penurie, &c. In all these, children must beare with their parents, as in the forenamed infirmities; neither lesse reuerendly esteeme of them, nor performe the lesse dutie because of them. These are such necessities, as are not sinfull in themselues; and therefore in regard of these, parents are much more to be borne withall. Though #emph[Isaak] were #emph[blinde,] yet did not #emph[Iaakob] a whit the lesse respect #footnote[#emph[Gen] 27. 1. #emph[Ruth] 1, 16, 21.] him. Though #emph[Naomi] were poore, yet #emph[Ruth] her daughter in law continued to doe a childs dutie and seruice vnto her.

Contrary is the vnnaturall disposition of such children, as #footnote[Vnnaturall to despise a parent for any casuall infirmitie.] take occasion from these casuall necessities of their parents to despise them. God hath made an expresse law against despising those who are by any outward defects impotent, as #emph[deafe, blinde,] &c. If no person may despise another, for these, much lesse children #footnote[#emph[Leu.] 19. 14.] their parents. They are worse then #emph[Cham] that doe so, and may looke for an heauier curse.

=== §. 44. #emph[Of childrens releeuing their parents according to their neede.]

Besides bearing with parents necessities, in such cases as parents stand in need of their childrens releefe and succour, they must afford it them. In sicknesse they must visit them, as #footnote[#emph[Gen.] 48. 1.] #emph[Ioseph] visited his father. In time of mourning, they must comfort them, as #footnote[#emph[&] 37. 35.] the children of #emph[Iaakob.] In want, they must prouide things needfull for them, as #footnote[#emph[&] 42. 8.] the sonnes of #emph[Iaakob,] who went vp to buy food for their father; and as #footnote[#emph[&] 47. 12.] #emph[Ioseph,] who sent for #emph[Iaakob] into Egypt, and there nourished him. It is noted of #footnote[#emph[Ruth] 2. 18.] #emph[Ruth,] that shee did not only gleane for her mother a poore woman, but also reserued some of that food which was giuen to her selfe to eat, for her. In time of danger they must doe what they can for their protection and preseruation, as #footnote[1 #emph[Sam.] 22. 3, 4.] #emph[Dauid] had in this respect an especiall care of his father and mother. Yea, if God be pleased to #footnote[Vetustissima lex erat inscripta mentibus omnium, vt liberi si hoc officij grauentur impendere quod pulli ciconiarum reponunt suis parentibus, velut impij conijciantur in vincula. Erasm. Instit. Matrim.] take children out of this world before their parents, and their parents be succourlesse, they must take what order they can for the well-being of their parents after their owne departure, as #footnote[#emph[Iohn] 19. 27.] Christ, who commended his mother to his disciple #emph[Iohn] a little before his death. These and such like duties are particular branches of #emph[recompence,] and are all comprised vnder that #footnote[1 #emph[Tim.] 5. 4..] #emph[requitall,] which the Apostle requireth of children: And they are but a small part of requitall of all the paines, care, and charges, that parents haue been at with their children. Yea, this only thing, that parents haue brought forth children into the world, can children neuer sufficiently requite. Nature hath taught thus much, not only vnto heathen men, but also vnto the vnreasonable creatures. Among other vnreasonable creatures, the example of the #footnote[Arist. Plin. Suidas.] #emph[Storke] is worthy to be noted: for it is recorded of that kinde, that when the dammes are old, the young ones feed them; and when through age, they are ready to faint in their flying, the young ones will helpe; and when they are past flying, the young ones carrie them on their backs. The #footnote[Sin of Pharisies in freeing children from relieuing their parents.] Greeke name of a #emph[Storke] is taken from that #emph[word,] which signifieth, to #emph[requite a parents kindnesse:] or else this word is taken from that name: they are both of the same notation.

Contrary is the opinion of Pharisies, who thought that children by consecrating their substance to the Temple, might be freed from this dutie of #emph[recompence] to parents, which is the mysterie of that Hebrew word #footnote[#emph[Mar.] 7. 11.] #emph[Corban.] They made a meere pretext of piety to God, a cause of manifest impietie against parents. Christ giueth this verdict of them, that #footnote[#emph[vers.] 13.] #emph[they make the word of God of none effect.] #footnote[See §. 14. 1. Sin of children in denying releefe to parents.] Papists are of the same opinion, and so vnder the same censure.

Contrary also is their practise, who hauing the goods of this world, suffer their parents to want. #footnote[1 #emph[Ioh.] 3. 17. #emph[Iniquissimum est patren egere, cùm filius sit in facultatibus. Digest. lib.] 25. #emph[tit.] 3. §. 5.] #emph[S. Iohn] saith, that #emph[the loue of God dwelleth not in him, who shutteth vp his compassion from his brother] in that case; how then can it dwell in such a childe? Not they only who suffer their parents to starue, offend in this extreme, but they also who suffer them to liue poorely, and basely, when themselues #footnote[#emph[Luk.] 16. 19. 2. In bringing parents into extremities.] Diues-like fare delicately, and goe gorgeously attired euery day.

In an higher degree doe they offend, who bring their parents to such extremities, as to pouertie by their lauish spending; to prison by importuning them to be their sureties; to excessiue griefe by their mischieuous practises, as #footnote[#emph[Gen.] 37. 34. 3. In striking parents.] the sonnes of #emph[Iaakob.]

But what shall we say of such gracelesse children, as dare strike their parents? #footnote[#emph[Exod.] 21. 15. 4. In murthering parents.] Gods law accounteth such a childe vnworthy of life, and adiudgeth him to death.

Nay, what may be said of #emph[father-quellers,] and #emph[mother-quellers?] There was of old no particular law made against them, because it is, supposed, that no childe can be so vnnaturall and inhumane. In imitation whereof #footnote[Solon cùm interrogaretur, cur nullum supplicium constituisset. in eum qui parentem necasset, respondit, se id neminem facturum putasse. Cic. pro Ros. Amer.] #emph[Solon,] that wise law-maker among the heathen, made no law against them: and his reason being asked, he answered, that he thought no childe would commit such a fact.

When afterwards such inhumane impietie was manifested in the world, the Ciuill Law ordained this punishment; #footnote[#emph[Si quis parentus fata propera uerit, neque gladio, neque ignibus, neque vlli alij solenni poenae subiugetur, sed insutus culeo cum cane, & gallo gallinaceo, & vipera, & simia, vel in vicinun mare, vel in amnem proijciatur, &c. Justin. Cod. l.] 9. #emph[tit.] 17. #emph[Cur voluerint parricidas insui in culeum viuos, atque ita in flumen deijci, docet Cicero pro Ros. Amer. Ad famam filij attinet, vt videatur honorem debitum patri] defuncto #emph[praestitisse. Cic. Philip.] 9.] #emph[If any shall kill his parent, let him not be put to the sword, nor fire, nor any other vsuall punishment: but let him be sowed in a sacke with a dog, and a cocke, and a viper, and an ape, and cast into the next sea, or riuer; that while life is in him, he may begin to want all vse of the elements, and be depriued, while he liueth, of the aire, and when he is dead, of the earth.]

This sinne hauing beene committed among the heathen, the Apostle reckoneth it vp among other most notorious and barbarous sinnes, 1. #emph[Tim.] 1. 9. As murther is one of those sinnes, which the earth can least beare, and which cryeth loudest to heauen for vengeance; so among the seuerall kinds of murther, this is the most vnsupportable, and crying.

#quote(block: true)[Thus much of the duties of children, which they are to performe while their parents liue. It remaineth to speake of those which they are to performe when their parents are dead.]

=== §. 45. #emph[Of childrens care to burie their parents being dead.]

The duties which children owe to their parents after they are dead, concerne the

+ #emph[Bodie]
+ #emph[Credit]

of their deceased parent.

It is the dutie of children to bring the bodies of their parents deceased, with such decencie and honour, as may be answerable to the place and reputation wherein they liued.

So as both the #emph[thing] it selfe, and the #emph[manner] of doing it, is to be obserued. #footnote[Buriall a meanes to maintaine hope of resurrection.]

The thing it selfe, namely #emph[Buriall] of the corps of such as are deceased, hath euer beene in vse in Gods Church: and it hath beene vsed as a meanes to maintaine our hope of the resurrection of our bodies. Many of the heathen, who neuer dreamt of the resurrection, #footnote[#emph[Constituere pyras: huc corpora quisque suorum More tulere patrum, subiect siue ignibus, &c. Virg. Aeneid.] 11.] were wont to burne the dead bodies of their friends: other heathen learned this manner of buriall from the Church, though they knew not the mysterie thereof. It is more cleare then needs be proued, that Gods people, from the beginning of the world, haue performed this dutie of buriall to their friends; but it is not pertinent to the point in hand, to insist vpon the generall: that it belongs especially to children to procure this dutie to be performed, is now the point to be proued, which is readily done by the approued examples of #footnote[#emph[Gen.] 25. 9.] #emph[Isaak,] #footnote[& 35. 29.] #emph[Iaakob,] #footnote[& 50. 7.] #emph[Ioseph,] and others expresly recorded in Scripture.

And great reason there is for it: for

1. It is a testimonie of great loue and good respect to the partie #footnote[1\. #emph[Reason.]] deceased. Now who should manifest more loue, and greater respect then a childe?

2. It is a kinde of #footnote[1 #emph[King.] 14. 13. 2 #emph[King.] 22. 20.] #emph[blessing,] promised by God to his Saints, #emph[to] #footnote[2\. #emph[Reason.]] #emph[be buried:] as on the other side, it is a #footnote[#emph[Ier.] 22. 19. 1 #emph[King.] 21. 23, 24. #emph[Psal] 79. 3.] #emph[curse] threatned against obstinate sinners, #emph[not to be buried.] In this respect, #footnote[2 #emph[Sam.] 2. 5.] #emph[Dauid] blesseth the men of #emph[Iabesh Gilead] for burying #emph[Saul,] and acknowledgeth it a kindnesse done to #emph[Saul.] Now who ought rather to procure a blessing, and doe a kindnesse to parents, then children, who are oft blessed through their parents meanes?

3. It being a great deformity to haue a mans corps lie aboue #footnote[3\. #emph[Reason.]] ground (for no carkase will be more loathsome then a mans if it lie vnburied) children, who are most bound to couer their parents deformity, are in this respect bound to burie their corps. #footnote[Sinne of children to neglect their parents dead corps.]

Contrary is their practise whose mindes are so set on their parents goods, as they cleane neglect their bodies. So soone as their parents breath is out of their body, they so busie themselues about the things which they haue left behinde them, as their corps is ready to stinke before care be taken for the buriall of it. Yea, some will purposely keepe their parents corps aboue ground till they be exceeding noisome, for receiuing some reuenues, or debts, or other accounts, which must be paid before the corps be buried. If their corps must needes for sometime be kept aboue ground, let them be imbalmed, or so vsed as they may not sauour. They who are carelesse hereof, shew that they respect their parents wealth #footnote[Sinne of children entring vpon their parents estate before they are dead. 1 #emph[King.] 1. 5.] more then his person and honour.

In which respect they also heinously transgresse, who are so greedy of their parents estate, as they must needs preuent his departure, and like #emph[Adoniah] enter vpon their fathers estate, and take possession of his goods before breath is out of his body: whereby they doe oft cause great disquietnesse to him that would depart in peace.

Againe, others bearing an inward grudge and secret hatred #footnote[Sinne of children disturbing their parents funerall.] against a brother, or other kinsman, whom their parent intirely loued, and in that respect durst not meddle with him in their parents life-time, so soone, as their parent is dead, picke a quarrell with the party hated, and so disturbe and hinder their parents funerall. Such a plot #emph[Esau] intended: but God defeated #footnote[#emph[Gen.] 27. 41.] it, whereby it appeareth that God is displeased therewith.

=== §. 46. #emph[Of the decency wherewith children ought to see their parents buried.]

The #emph[manner] after which children ought to see their parents buried, must be with such #emph[decency] as is agreeable to the commendable custome of the countrie and Church where their parents die, and with such #emph[honour] as is in some measure answerable to the estate, and place of their parents while they liued (at least if it be not aboue the meanes that the parent hath left, or aboue the abilitie of the childe that maketh the solemnitie.) #emph[Ioseph] was a great Gouernour in Egypt, by reason whereof his father when he came thither was highly accounted of: accordingly #footnote[#emph[Gen.] 50. 7.] with great honour did he carry him to his graue.

There are two extremes contrary to the forenamed #emph[decency] #footnote[Contrary, 1. Too sumptuous funerals.] and #emph[honour.] One is an ouerlauish and prodigall sumptuousnesse and solemnitie at their parents funerall, farre aboue the estate, and farre beyond the meanes which the parent hath left, and farre also aboue the estate and ability of the childe himselfe. Some by the needlesse solemnitie of their parents funerall are so farre cast into debt, as they are neuer able to recouer themselues againe, and so bring more dishonour to their parents by the weaknesse of their childes estate, then honour by the solemnitie of the funerall: there may be great honour, and much decency in a funerall, where is not extraordinary charges: instance #emph[Steuens] funerall. #footnote[#emph[Act.] 8. 2.]

The other extreme is too base and priuate a manner of #footnote[2\. Too base funeralls.] burying their parents, much vnbeseeming both their parents and their owne estate, and means; which ariseth from a mixture of pride, and couetousnesse possessing their hearts. Pride maketh them haue no solemnity at all, because couerousnesse will not suffer them to exceed in their solemnitie. Hence it commeth to passe that they chuse out strange places where neither their parents or selues are knowne, and the dead of the night that none may espie them; and appoint an vncertaine time, that no friend may accompany them. God oft meeteth with such proud, couetous children in their kinde, and causeth them with like dishonour to be brought to their graues.

=== §. 47. #emph[Of childrens paying their parents debts after their death.]

As children must haue respect to the body of their parents #footnote[Childrens respect to the credit of their deceased parents.] deceased, so also to their credit and name, which is a thing of greater account, and honour: a thing wherein they may bring a kinde of blessing to their parents and make them liue after their death.

Parents themselues cannot doe any thing when they are dead to preserue the same: children therefore being the liuing Image of their parents must indeuour to doe it.

Three things there be which children must make conscience of, euen in regard of their deceased parents credit, and reputation; one, to pay their debts: another, to suppresse ill rumors: a third, to imitate their good example.

I. If the estate of parents, their goods or lands come to their children, their dutie is to pay their debts, so farre as they can: especially if by law those debts may be recouered at their hands. For what law may force others to doe in equitie and Iustice, conscience must moue good children to doe in charitie, and recompence to their parents. The holy Ghost makes it a #footnote[#emph[Psal.] 37. 21.] note of a wicked man #emph[to borrow and not to pay.] Wherfore to wipe away that blot from the name of a parent deceased, children must be ready in this kinde to doe what the parent himselfe, if he were liuing, would, or should doe. Yea if children of themselues be well able, though their parents left not sufficient to pay all their debts, they ought to pay them. Herein especially a childlike affection is manifested to the parent.

Contrary is their practise who striue to get all they can of their parents, and yet make no conscience of paying any debts at all, vnlesse law force them thereto. What they doe in this case cannot be thought to be done for their parents sake, but rather for their owne sake. Many so little respect their parents credit in this kinde, as they priuily conueigh away and vtterly conceale much of their parents estate, of purpose to defeate Creditors: which as it is a part of apparent iniustice, so it is a cause of opening the mouthes of men against their parents, to their discredit and shame.

=== §. 48. #emph[Of childrens suppressing euill reports against their parents deceased.]

\* The direction giuen before concerning childrens speech #footnote[§. 7.] of their parents behinde their backs, may fitly be applied also to the care which children ought to haue of the speeches and reports which are made of their parents after their departure. It followeth as #emph[from the lesse to the greater,] that what children doe for their parents credit in absence behinde their backes, they must much more doe when they are dead: for then there is no hope, no possibilitie that parents should doe any thing to right their owne wrong in that kinde: it lyeth therefore vpon children to doe it.

Doe not they cleane contrary, who take occasion from the departure of their parents, both to open their eares to receiue any ill reports of them, and also to open their mouthes to speake ill of them: then blazing abroad all their infirmities, and stretching their ill reports of their parents beyond the lists of truth. Ill birds they are that so bewray their owne neast. They know that their parents being dead can haue no notice thereof: whereby they shew what little piety to God or parent is in their heart. But there is an euer-liuing, all-seeing, and all-knowing Father that taketh notice of all: who beside other vengeance will cause such measure to be meated out to them, as they mete to their parents. There is no one thing wherein this prouerb, #emph[(With what measure you mete it shall be measured] #footnote[#emph[Mat.] 7. 2.] #emph[to you againe)] is more often verified then in childrens ingratitude #footnote[#emph[Quaecunque parentibus stipendia intuleris, eadem ipse a filiis expecta. Thal. Miles. apud Diog. Laert. l.] 1.] to their parents. All ages haue giuen many instances thereof. (The very heathen obserued it.) Which sheweth Gods great indignation against it.

=== §. 49. #emph[Of childrens imitating their parents good example.]

If parents haue beene persons of good carriage in their life time, as religious towards God, iust in their dealings with men, mercifull to such as stood in need of their helpe, doing much good in their place, and so ended their daies with much credit; it is an especiall meanes to maintaine and continue this their credit, for children to walke in their steps, and to indeuour to be like them.

Thus is a blessed memorie of their parents kept fresh and greene (as we speake) though their bodies be rotten. For when they who knew the parents behold the like good qualities and actions in their children, they will thereby be put in minde of the parties deceased, and say, Oh how such parents yet liue! behold a liuely, and liuing Image of them. Thus did #emph[Salomon, Asa, Iehosaphat, Hezekiah, Iosiah] and such like good Kings which came of the stocke and linage of #emph[Dauid,] keepe the memory of their father #emph[Dauid,] fresh, faire, and flourishing (long after his body was rotten) as is euident by these and such like phrases, #emph[He walked in the ordinances of Dauid his] #footnote[1 #emph[King.] 3. 3.] #emph[father: he walked in all the waies of Dauid his father: he did] #footnote[2 #emph[King.] 22. 2.] #emph[that which was right as Dauid his father,] &c. There can be no #footnote[1 #emph[King.] 15. 11.] better monument of a parents pietie, honestie, and vertue, then a childes liuely representation of the same. Wherefore #footnote[#emph[Nullum monumentum clarius relinquere potuit, quàm effigiem morum suorum, virtutis, constantiae, pietatis filium. Cic. Philip.] 9.] as a motiue to stirre vp children to walke in the good waies of their parents, God hath promised to #emph[shew mercy to thousands of them that loue him and keepe his commandements,] that is, such as hauing religious and righteous parents walke in their steps.

Contrary are both those that are vnlike good parents, and those that are like euill parents. The former sort doe much impeach and dishonour the reputation of their parents, as #emph[Rehoboam,] who by his foolish rigorous and vniust carriage, made the people speake contemptuously of #emph[Dauid.] #footnote[1 #emph[King.] 12. 16.]

The latter sort continue in memorie the euill name, and the shame of their parents, and cause them to stinke more and more: as the sonnes and successors of #emph[Ieroboam,] who following his idolatrous course, made it the more remembred, and caused this blur to remaine in his stile from age to age, #emph[Ieroboam which made Israel to sinne.] #footnote[1 #emph[King.] 15. 26.]

As #emph[they] stop the current, and hinder the passage of the blessing of righteous parents: so #emph[these] propagate, and open a way for the curse of vnrighteous parents.

=== §. 50. #emph[Of the superstitious dutie enioyned by Papists to children after their parents decease.]

To the two forenamed duties of #emph[burying the corps,] and #emph[preseruing the credit] of parents, #emph[Papists] adde a third, and #emph[Heathen] a fourth, whereof neither are warrantable by Gods word, but directly contrary thereto.

That which #emph[Papists] adde is, that children after their parents #footnote[#emph[Bellar. Tom.] 2. #emph[Contr.] 3. #emph[De Purgator. l.] 2. #emph[c.] 16. #emph[&c.]] death ought to procure #emph[Diriges, Masses, Pardons, Releases,] and such like toies for them, and make continuall prayers to free them out of Purgatory, and bring them to rest in heauen: of the vanity of these prayers, and folly of the other toies I haue #footnote[In whole armour of God Treat. 3. §. 39. 40. #emph[in Ephes.] 6. 18.] elsewhere spoken.

The Scripture expresly teacheth that after death the soule goeth to the place appointed for it, of endlesse blisse or woe: so as there is no meanes of altering the one, or helping forward the other.

=== §. 51. #emph[Of the vnlawfulnesse of childrens seeking to reuenge their parents wrongs.]

That which #emph[Heathen] adde, is, that children after their parents #footnote[Seneca in Agamen. Poetae tradiderunt filios patris vlciscendi causa supplicium de matre sumpsisse, idque deorum iussis, atque oraculis fecisse. Cic. pro. Sex. Ros.] death reuenge such wrongs as haue beene done to them in their life time. And they presse this so farre vpon children, as they affright them with their parents #emph[Ghost,] saying, that if they neglect to reuenge their parents wrongs, their Ghost will follow them, and not suffer them to liue in quiet, but molest them continually. This conceipt ariseth from the corruption of nature, which is exceeding prone to reuenge: but it is expresly forbidden in Scripture, in these and such prohibitions, #emph[Resist not euill,] #footnote[#emph[Rom.] 12. 17,] #emph[Recompence to no man euill for euill.] #footnote[19.] #emph[Auenge not] #footnote[#emph[Mat.] 5. 39.] #emph[our selues] &c. Yet some in iustification thereof alledge #footnote[1 #emph[King.] 2. 5. 8.] #emph[Dauids] charge to #emph[Salomon] of taking vengeance on #emph[Ioab] and #emph[Shemei,] after his death.

#emph[Answ.] The charge which #emph[Dauid] gaue, & #emph[Salomons] execution thereof, was no matter of priuate reuenge, but only a lawfull execution of iustice which children may and ought to doe. Iust reasons there were to moue #emph[Dauid] to put off the execution of iustice vpon the one & the other so long. #footnote[2 #emph[Sam.] 3. 39.] #emph[Ioab] was too mightie to haue execution done on him in #emph[Dauids] time: and #emph[Shemeis] #footnote[& 19. 23.] offence was committed in the time of #emph[Dauids] humiliation, which made him sweare that he would not himselfe take Vengeance of him. Besides, #emph[Salomon] executed iustice on the one and the other, not for the wrongs they did to his father, but for other crimes which they committed in his time: onely their former offences were remembred to aggrauate the matter.

Thus farrc of childrens #emph[duties.] The #emph[manner] of performing them followeth to be declared.
