"""Illegible gaps filled for this edition, keyed by the TEI pipeline's gap
index (build_tei.py --list). Read from context, the scripture quoted, and
the page images (archive.org, the same microfilm in grayscale; most losses
are line ends in the binding, lost there too). Gaps in the title page,
contents and Advertisement (not in this edition) are left open."""

GAP_FIXES = {
    6: (',', 'medium', 'a stop after "Treatise" (page image: blotted)'),
    7: ('not ', 'medium', '"some Congregations have not duly weighed"; page image: the line end is lost'),
    8: ('d', 'high', 'duly'),
    9: ('ei', 'high', 'their'),
    10: ('in', 'high', 'indispensible'),
    11: ('over', 'high', 'page image: "over them in the Lord" (1 Thess. 5:12)'),
    12: ('e', 'high', 'well'),
    60: ('sp', 'high', 'respite'),
    61: ('w', 'high', 'we trust'),
    62: ('W', 'high', 'Work'),
    63: ('so', 'medium', '"so long the hope and expectation"'),
    64: ('all', 'high', '"of all that truly love and fear the Lord"'),
    65: ('W', 'high', 'We'),
    66: ('co', 'high', 'concerned'),
    67: ('Im', 'high', 'Improvement'),
    68: ('ne', 'high', 'Goodness'),
    69: ('tak', 'high', 'taking into consideration'),
    70: ('tio', 'high', 'Condition'),
    71: ('can', 'high', 'cannot'),
    72: ('nt', 'high', 'inadvertent'),
    73: ('d', 'high', "call'd"),
    74: ('nt', 'high', 'competent'),
    75: ('t', 'high', 'them'),
    76: ('19', 'high', 'page image: "Mark, 3. 13. to the 19."'),
    77: ('an', 'high', 'and (Mark 3:13)'),
    78: ('t', 'high', 'they (Mark 3:13)'),
    79: ('th', 'high', 'that (Mark 3:14)'),
    80: ('h', 'high', 'he (Mark 3:14)'),
    81: ('w', 'high', 'whom (Luke 6:13)'),
    82: ('w', 'high', 'with'),
    83: ('of', 'high', 'page image: "Invocation of the Father"'),
    84: ('re', 'high', 'Hire (Luke 10:7)'),
    85: ('ll', 'high', 'page image: "of all Power"'),
    86: ('t', 'medium', "Matt. (this book's usual abbreviation)"),
    87: ('d', 'high', 'and (Matt. 28:18)'),
    88: ('is', 'high', 'Matt. 28:18 "All power is given"'),
    89: ('&c.', 'high', 'page image: "Teach all Nations, &c."'),
    90: ('unto', 'high', 'Matt. 28:20 "even unto the end of the world"'),
    91: ('1', 'high', 'Heb. 8:1 "the throne of the Majesty in the heavens"'),
    92: ('dain', 'high', 'page image: "Or-|daine Elders" (Titus 1:5)'),
    93: ('ir', 'high', 'their'),
    94: ('e', 'high', 'Exercise'),
    95: ('t', 'high', 'what'),
    96: ('ll', 'high', 'call'),
    97: ('t', 'high', 'not'),
    98: ('t', 'high', 'Meet'),
    99: ('e', 'high', 'we'),
    100: ('e', 'high', 'have'),
    101: ('m', 'high', 'seem'),
    102: ('t', 'high', 'it'),
    103: ('a', 'medium', '"to receive a Yearly or Quarterly Allowance"'),
    104: ('f', 'high', 'of'),
    105: ('e', 'high', 'more'),
    106: ('f', 'high', 'of'),
    107: ('e', 'high', 'the'),
    108: ('e', 'medium', 'the'),
    109: ('ss', 'high', 'Remissness'),
    110: ('f', 'high', 'for'),
    111: ('no', 'high', 'nor (Matt. 10:9)'),
    112: ('no', 'high', 'nor (Matt. 10:10)'),
    113: ('C', 'high', 'Coats (Matt. 10:10)'),
    114: ('W', 'high', 'Workman (Matt. 10:10)'),
    115: ('e', 'high', 'Rule (1 Tim. 5:17)'),
    116: ('ur,', 'medium', "Honour, (1 Tim. 5:17; the book's spelling)"),
    117: ('he', 'high', '1 Cor. 9:10 "Or saith he it altogether for our sakes?"'),
    118: ('r', 'high', 'our (1 Cor. 9:10)'),
    119: ('e', 'high', 'he (1 Cor. 9:10)'),
    120: ('e', 'high', 'made (1 Cor. 9:10)'),
    121: ('e', 'high', 'have (1 Cor. 9:11)'),
    122: ('t', 'high', 'the (1 Cor. 9:14)'),
    123: ('t', 'high', 'there'),
    124: ('e', 'high', 'evident'),
    125: ('S', 'high', 'Scripture'),
    126: ('s', 'high', 'strangly'),
    127: ('L', 'high', 'Loss'),
    128: ('t', 'high', 'to'),
    129: ('o', 'high', 'or'),
    130: ('t', 'high', 'the'),
    131: ('a', 'high', 'and'),
    132: ('It', 'high', '"It appears that"'),
    133: ('S', 'high', 'Saviour'),
    134: ('the', 'high', '"to Preach the Gospel"'),
    135: ('his', 'high', 'page image: "this part of his Will"'),
    136: ('ld', 'high', 'should'),
    137: ('ce', 'high', 'Substance'),
    138: ('or', 'high', '"either Gold or Silver" (Matt. 10:9)'),
    139: ('n', 'high', 'intimate'),
    140: ('ld', 'high', 'Gold'),
    141: ('es', 'high', 'Shoes'),
    142: ('m', 'high', 'them'),
    143: ('g', 'high', 'being'),
    144: ('of', 'high', '"the Kingdom of God"'),
    145: ('this', 'medium', '"Object this was but a temporary Precept" (page image: t-)'),
    146: ('the', 'medium', '"being the Will of God concerning them"'),
    147: ('ort', 'medium', '"for that short Journey"'),
    148: ('us', 'high', '"it seemeth to us"'),
    149: ('ill', 'high', 'Will'),
    150: ('th', 'high', 'Faithful'),
    151: ('y', 'high', 'Necessary'),
    152: ('ges', 'high', 'Ages'),
    153: ('do', 'medium', '"our Worthy Annotators do directly agree"'),
    154: ('ough', 'high', 'though'),
    155: ('is', 'high', 'this'),
    156: ('at', 'high', 'what'),
    157: ('th', 'high', "them (Poole's Annotations on Matt. 10:10; page image)"),
    158: ('he', 'high', 'page image: "he taught"'),
    159: ('nor', 'high', 'page image: "nor overmuch Sollicitous"'),
    160: ('to', 'high', 'page image: "the People to provide"'),
    161: ('in', 'high', 'page image: "in things Spiritual"'),
    162: ('v', 'high', 'given'),
    163: ('s', 'high', 'so'),
    164: ('a', 'high', 'and'),
    165: ('it', 'high', 'page image: "put it out of all doubt"'),
    166: ('con', 'high', 'page image: "consider"'),
    167: ('in', 'high', 'page image: "in this Matter"'),
    168: ('th', 'high', 'nothing'),
    169: ('L', 'high', 'Lord'),
    170: ('S', 'high', 'Servants'),
    171: ('h', 'high', 'Churches'),
    172: ('in', 'high', 'Maintenance'),
    173: ('d', 'high', 'and'),
    174: ('to', 'high', '"to whom they belong"'),
    175: ('t', 'high', 'Servant'),
    176: ('ne', 'high', 'none'),
    177: ('e', 'high', 'more'),
    178: ('d', 'high', 'Sacred'),
    179: ('i', 'high', 'evident'),
    180: ('9.', 'high', '1 Cor. 9:14, quoted next'),
    181: ('th', 'high', 'hath (1 Cor. 9:14)'),
    182: ('ch', 'high', 'Preach (1 Cor. 9:14)'),
    183: ('e,', 'medium', '"True, the Lord hath not Ordained"'),
    184: ('his', 'high', '"that his Servants"'),
    185: ('o', 'high', 'Gospel'),
    186: ('h', 'high', 'Tenth'),
    187: ('r', 'high', 'formerly'),
    188: ('t', 'high', 'yet'),
    189: ('m', 'high', 'them'),
    190: ('the', 'high', '"live of the Gospel"'),
    191: (')', 'high', 'closes "(unless Necessity requires"'),
    192: ('eir', 'high', 'their'),
    193: ('n', 'high', 'Men'),
    194: ('the', 'high', '"\'tis not said the Church"'),
    195: ('the', 'high', '"nor we the Apostles"'),
    196: ('the', 'high', '"but the Lord"'),
    197: ('for', 'high', '"a Comfortable Livelyhood for them"'),
    198: ('9.', 'high', 'Deut. 10:9 "Levi hath no part nor inheritance"'),
    199: ('to', 'high', '"needed not to Labor"'),
    200: ('Hands', 'high', '"with their Hands to get Bread"'),
    201: ('l', 'high', 'Gospel'),
    202: ('e', 'high', 'Comfortable'),
    203: ('s', 'high', 'Incumbrances'),
    204: ('r', 'high', 'or'),
    205: ('in', 'high', 'indispensable'),
    206: ('se', 'medium', '"are, see Ephes. 4"'),
    207: ('no', 'high', 'Eph. 4:28 "steal no more"'),
    208: ('hi', 'high', 'his (Eph. 4:28)'),
    209: ('on', 'high', 'Communication (Eph. 4:29)'),
    210: ('ag', 'high', 'again'),
    211: ('yo', 'high', 'you (Eph. 5:33)'),
    212: ('Y', 'high', 'You'),
    213: ('gr', 'high', 'great'),
    214: ('ex', 'high', 'excused'),
    215: ('H', 'high', 'Holy'),
    216: ('joy', 'high', 'injoyn (the book\'s "injoyned")'),
    217: ('of', 'high', '"form of Speech"'),
    218: ('to', 'high', 'Gal. 6:6 "communicate unto him that teacheth"'),
    219: ('in', 'high', 'Gal. 6:6 "in all good things"'),
    220: ('h', 'high', 'have'),
    221: ('Sac', 'high', 'Sacred'),
    222: ('Jes', 'high', 'Jesus'),
    223: ('N', 'high', 'Neglect'),
    224: ('sait', 'high', 'saith (John 15:14)'),
    225: ('wh', 'high', 'whatsoever (John 15:14)'),
    226: ('let', 'medium', '"pray let this great Ordinance then be thought upon"'),
    227: ('up', 'high', 'upon'),
    228: ('as', 'high', '"as a Gospel Institution"'),
    229: ('r', 'medium', 'for'),
    230: ('he', 'high', 'the'),
    231: ('n', 'high', 'when (Ps. 119:6)'),
    232: ('s', 'high', 'as'),
    233: ('t', 'high', 'not'),
    234: ('e', 'high', 'the'),
    235: ('ly', 'high', 'fitly'),
    236: (',', 'medium', 'a stop after "Communicate"'),
    237: ('o', 'high', 'to'),
    238: ('t', 'high', 'Text'),
    239: ('t', 'high', 'that'),
    240: ('e', 'high', 'the'),
    241: ('t', 'high', 'to'),
    242: ('t', 'high', 'those'),
    243: ('S', 'high', 'Spiritual'),
    244: ('n', 'high', 'in'),
    245: ('e', 'high', 'i. e.'),
    246: ('r', 'high', 'other'),
    247: ('e', 'high', 'please (2 Tim. 2:4)'),
    248: ('e', 'high', 'give'),
    249: ('o', 'high', 'to (1 Tim. 4:13)'),
    250: ('.', 'medium', 'a stop before "Meditate" (1 Tim. 4:15)'),
    251: ('e', 'high', 'give (1 Tim. 4:15)'),
    252: ('s', 'high', 'his'),
    253: ('k', 'high', 'Work'),
    254: ('ese', 'high', 'these'),
    255: ('nd', 'high', 'and'),
    256: ('in', 'high', '"so it is in the Greek"'),
    257: ('es', 'high', 'observes'),
    258: ('ust', 'high', 'must'),
    259: ('i', 'high', 'Ministry'),
    260: ('t', 'high', 'to'),
    261: ('t', 'high', 'the'),
    262: ('st', 'high', 'Ministers'),
    263: ('B', 'high', 'Blessed'),
    264: ('c', 'high', 'concealed'),
    265: ('st', 'high', 'amongst'),
    266: ('s', 'high', 'Thoughts'),
    267: ('h', 'high', 'with'),
    268: ('r', 'high', 'for'),
    269: ('r', 'high', 'Minister'),
    270: ('it', 'high', '"if it be possible"'),
    271: ('ll', 'high', 'shall'),
    272: ('e', 'high', 'Tongue'),
    273: ('d', 'high', 'deserved'),
    274: ('on', 'high', 'only'),
    275: ('re', 'high', 'are'),
    276: ('us', 'high', 'thus'),
    277: ('it', 'high', '"We find it from hence"'),
    278: ('ll', 'high', 'Calling'),
    279: ('at', 'medium', 'that'),
    280: ('e', 'high', 'the'),
    281: ('e', 'high', 'one'),
    282: ('t', 'high', 'least'),
    283: ('lf', 'high', 'himself (2 Tim. 2:15)'),
    284: ('d', 'high', 'ashamed (2 Tim. 2:15)'),
    285: ('at', 'high', 'that'),
    286: ('of', 'high', '"portion of Meat in due Season" (Luke 12:42)'),
    287: ('o', 'high', 'Timothy'),
    288: ('re', 'high', 'are'),
    289: ('ve', 'high', 'every'),
    290: ('d', 'high', 'and'),
    291: ('d', 'high', 'and'),
    292: ('is', 'high', '"There is another great Duty"'),
    293: ('m', 'high', 'them'),
    294: ('e', 'high', 'the'),
    295: ('ey', 'high', 'they'),
    296: ('re', 'high', 'Warfare (1 Cor. 9:7)'),
    297: ('o', 'high', 'Who (1 Cor. 9:7)'),
    298: ('a', 'high', '1 Cor. 9:7 "feedeth a flock"'),
    299: ('e', 'high', 'the (1 Cor. 9:7)'),
    300: ('e', 'high', 'the'),
    301: ('a', 'high', 'a'),
    302: ('e', 'high', 'The'),
    303: ('in', 'high', '"but in expectation"'),
    304: ('e', 'high', 'thence'),
    305: ('t', 'high', 'but'),
    306: ('it', 'high', '"is it then a great thing" (1 Cor. 9:11)'),
    307: ('f', 'high', 'of'),
    308: ('t', 'high', 'that'),
    309: ('u', 'high', 'you'),
    310: ('r', 'high', 'their'),
    311: ('old', 'high', 'withhold (printed with-|hold)'),
    312: ('a', 'high', 'such a'),
    313: ('l', 'high', 'tell'),
    314: ('r', 'high', 'our'),
    315: ('us', 'high', 'page image: "desire it of u-"'),
    316: ('t', 'high', 'get'),
    317: ('o', 'high', 'who'),
    318: ('to', 'medium', '"left to the thorny cares of this World"'),
    319: ('as', 'high', '"so to him as to put him"'),
    320: ('r', 'high', 'answer'),
    321: ('re', 'high', 'where'),
    322: ('r', 'high', 'concerned'),
    323: ('of', 'high', '"giving Proof of this Grace"'),
    324: ('re', 'high', 'there'),
    325: ('are', 'high', 'Phil. 4:8 "whatsoever things are honest"'),
    326: ('ood', 'high', 'good (Phil. 4:8)'),
    327: ('aise', 'high', 'Praise (Phil. 4:8)'),
    328: ('w', 'high', 'How'),
    329: ('u', 'high', 'you'),
    330: ('ho', 'high', 'who'),
    331: ('n', 'high', 'in'),
    332: ('d', 'high', 'and'),
    333: ('s', 'high', 'Jesus'),
    334: ('l', 'high', 'deliver'),
    335: ('t', 'high', 'think'),
    336: ('a', 'high', 'Christians'),
    337: ('t', 'high', 'they'),
    338: ('b', 'high', 'be'),
    339: ('d', 'high', 'doors'),
    340: ('g', 'high', 'ground'),
    341: ('se', 'high', 'raise'),
    342: ('ir', 'high', 'their'),
    343: ('m', 'high', 'esteem'),
    344: ('e', 'high', 'the'),
    345: ('he', 'high', 'the (1 Tim. 5:17)'),
    346: ('or', 'high', 'worthy (printed w-|thy across the line)'),
    347: ('ho', 'high', 'who (1 Tim. 5:17)'),
    348: ('or', 'high', 'For (1 Tim. 5:18)'),
    349: ('uzzle', 'high', 'Muzzle (1 Tim. 5:18)'),
    350: ('out', 'high', '1 Tim. 5:18 "treadeth out the corn"'),
    351: ('of', 'high', '1 Tim. 5:18 "worthy of his reward"'),
    352: ('t', 'high', 'meant'),
    353: ('o', 'high', 'Honourable'),
    354: (',', 'medium', 'a stop after "Sake"'),
    355: ('to', 'high', '"said to be"'),
    356: ('d', 'high', 'Sacred'),
    357: ('nt', 'high', 'evident'),
    358: ('e', 'high', 'place'),
    359: ('he', 'high', 'the'),
    360: ('re', 'medium', 'Scripture'),
    361: ('x', 'high', 'Ox'),
    362: ('the', 'high', '"and the Labourer"'),
    363: ('his', 'high', 'This'),
    364: ('ht', 'high', 'ought'),
    365: ('in', 'high', '"in most Congregations"'),
    366: ('th', 'high', 'them'),
    367: ('d', 'high', 'and'),
    368: ('r', 'high', 'near'),
    369: ('r', 'high', 'favour'),
    370: ('s', 'high', 'This'),
    371: ('s', 'high', 'this'),
    372: ('do', 'medium', '"Inconveniences that do follow"'),
    373: ('e', 'high', 'some'),
    374: ('e', 'high', 'were'),
    375: ('e', 'high', 'are'),
    376: ('r', 'high', 'Secular'),
    377: ('n', 'high', 'Men'),
    378: ('is', 'high', '"How is it possible"'),
    379: ('es', 'high', 'Families'),
    380: ('u', 'high', 'Incouragement'),
    381: ('o', 'high', 'who'),
    382: ('i', 'high', 'Graciously'),
    383: ('ts', 'high', 'Gifts'),
    384: ('es', 'high', 'themselves'),
    385: ('r', 'high', 'better'),
    386: ('e', 'high', 'the'),
    387: ('n', 'high', 'now'),
    388: ('t', 'high', 'the'),
    389: ('n', 'high', 'not'),
    390: ('h', 'high', 'have'),
    391: ('a', 'high', 'and'),
    392: ('h', 'high', 'hath'),
    393: ('t', 'high', 'but'),
    394: ('n', 'high', 'seen'),
    395: ('it', 'high', 'Profit'),
    396: ('st', 'high', 'least'),
    397: ('d', 'high', 'and'),
    398: ('e', 'high', 'some'),
    399: ('ts', 'high', 'Parents'),
    400: ('e', 'high', 'the'),
    401: ('l', 'high', 'follow'),
    402: ('t', 'high', 'themselves'),
    403: ('i', 'high', 'in'),
    404: ('t', 'high', 'the'),
    405: ('L', 'high', 'Loss'),
    406: ('c', 'high', 'come'),
    407: ('l', 'high', 'long'),
    408: ('t', 'high', 'the'),
    409: ('t', 'high', 'the'),
    410: ('a', 'high', 'a'),
    411: ('t', 'high', 'that'),
    412: ('st', 'high', 'Ministers'),
    413: ('a', 'high', 'are'),
    414: ('be', 'high', '"if the Ministry be not awakened"'),
    415: ('a', 'high', 'all'),
    416: ('t', 'high', 'intangled'),
    417: ('t', 'high', 'that'),
    418: ('t', 'high', 'the'),
    419: ('t', 'high', 'they'),
    420: ('f', 'high', 'of'),
    421: ('k', 'high', 'look'),
    422: ('t', 'high', 'that'),
    423: ('t', 'high', 'but'),
    424: ('r', 'high', 'their'),
    425: ('t', 'high', 'great'),
    426: ('l', 'high', 'called'),
    427: ('u', 'high', 'ought (page image: "o[ught] not to Preach")'),
    428: ('ght', 'high', 'ought'),
    429: ('Lu', 'high', 'Lucres (1 Pet. 5:2), as later on the page'),
    430: ('s', 'high', 'is'),
    431: ('f', 'high', 'himself'),
    432: ('t', 'high', 'at'),
    433: ('t', 'high', 'three (Acts 20:31)'),
    434: ('t', 'high', 'time'),
    435: ('e', 'high', 'every (Acts 20:31)'),
    436: ('j', 'high', 'injoyned'),
    437: ('I', 'high', 'If'),
    438: ('h', 'high', 'here'),
    439: ('t', 'high', 'than'),
    440: ('is', 'high', 'his'),
    441: ('on', 'high', 'page image: "here on Earth"'),
    442: ('r', 'high', 'after'),
    443: ('', 'medium', 'no word lost: the line ends "look after" (page image)'),
    444: ('t', 'high', 'their'),
}
