== Serving Each Other in the Fear of the Lord

#align(center)[
  #block(width: 85%)[
    #set par(justify: false)
    #text(size: 0.9em, weight: 600)[EPHES. 5. 21.]

    #text(style: "italic")[Submit your selves one to another in the fear of God.]
  ]
]

#v(0.8em)

=== §. 1. #emph[Of the Apostles transition from general duties to particulars.]

As there are two vocations whereunto it hath pleased God to call every one; #emph[one general,] by virtue whereof certain common duties which are to be performed of all men, are required, (as knowledge, faith, obedience, repentance, love, mercy, justice, truth, etc.) #emph[the other particular,] by virtue whereof certain peculiar duties are required of several persons, according to those distinct places wherein the Divine Providence hath set them in common-wealth, Church, or family; so ought Gods Ministers to be careful in instructing Gods people in both kinds of duties; both those which concern their #emph[general,] and those also which concern their #emph[particular] calling. Accordingly #emph[S. Paul] (who, as #footnote[#emph[Num.] 12. 7.] #emph[Moses,] was #emph[faithful in all the house of God)] after he had sufficiently instructed Gods Church in such #emph[general] duties, as belong to all Christians, of what sex, state, degree, or condition soever they be, proceedeth to lay down certain #emph[particular] duties, which appertain to particular callings and conditions: among which, he maketh choice of those which God hath established in a family. With excellent Art doth he pass from those #emph[generals,] to these #emph[particulars:] laying down a #emph[transition] betwixt them, in these words, #emph[Submitting your selves one to another in the fear of God;] which words have reference both to that which goeth before, and also to that which followeth after. The form and manner of setting down this verse, with a participle thus, #emph[submitting,] showeth that it dependeth on that which went before, and so hath reference thereunto. Again, the word it self being the very same which is used #footnote[submitting. submit.] in the next verse following, showeth, that this verse containeth the #emph[sum] of that which followeth, and so hath reference thereunto, as a general unto particulars. This manner of passing from one point to another, by a #emph[perfect transition] which looketh both ways, both to that which is past, and to that which cometh on, as it is very elegant, so is it frequent with this our Apostle. Whereby he teacheth us, #footnote[Note.] so to give heed to that which followeth, as we forget not that which is past: as we must give diligent attention to that which remaineth, so we must well retain that which we have heard, and not let it slip: otherwise, if (as one nail driveth out another) one precept maketh another to be forgotten, it will be altogether in vain to add line unto line, or precept unto precept.

=== §. 2. #emph[Of joining service to men with our praising of God.]

As this verse hath reference to that which was delivered before, concerning our duty to God, it teacheth us this lesson:

#emph[It is the duty of Christians as to set forth the praise of God, so to be serviceable one to another.] For this purpose in the #footnote[Doct.] Decalogue to the first table, which prescribeth that duty which we owe to God, is added the second table, which declareth the service that we owe one to another: and he that said, #footnote[#emph[Matt.] 22. 38, 39.] #emph[The first and great Commandment is this, Thou shalt love the Lord,] etc. Said also, #emph[The second is like to this, Thou shalt love thy neighbour,] etc. Whereupon the #footnote[#emph[Heb.] 13. 15, 16.] Apostle declaring what those sacrifices be wherewith God is well pleased, joineth these two together, #emph[to give thanks to God, and to do good to man.] The service which in the fear of God we perform one to another, is an evident and real demonstration of the respect we bear unto God. #footnote[#emph[Psal.] 16. 2.] #emph[To God our goodness extendeth not.] #footnote[#emph[Job] 22. 3. & 35. 7.] He is so high above us, so perfect and complete in himself, that neither can we give to him, nor he receive of us. But in his own stead he hath placed our brother like to our selves; to whom, #footnote[#emph[Job] 35. 8.] as we may do hurt, so by our faithful service we may do much #footnote[#emph[Psal.] 16. 3.] good: in doing whereof God is much honoured.

This discovereth their hypocrisy, who make great pretence #footnote[1\. #emph[Use.] A note of hypocrisy.] of praising God, and yet are scornful, and disdainful to their brethren, and slothful to do any service to man: #emph[These mens religion is vain.] By this note did the Prophets #footnote[#emph[Jam.] 1. 26. #emph[Isa.] 58. 3 #emph[etc. Mic.] 6. 6. #emph[etc. Matt.] 23. 14. 1 #emph[Joh.] 4. 20.] in their time, and Christ and his Apostles in their time also, discover the hypocrisy of those among whom they lived: and so may we also in our times. For many there be, who frequently in their houses, and in the middest of the Congregation sing praise unto God, and perform other parts of Gods outward worship, but towards one another, are proud, stout, envious, unmerciful, unjust, slanderous, and very backward to do any good service. Surely, that outward service which they pretend to perform to God, doth not so much wipe out the spot of profaneness, as their neglect of duty unto man brandeth their foreheads with the stamp of hypocrisy. #footnote[2\. #emph[Use.] Put not off one duty with another. #emph[Matt.] 23. 23.]

For our parts, let us not upon pretext of one duty, though it may seem to be the weightier, think to shift off another; lest that fearful #emph[woe] which Christ denounced against the #emph[Scribes] and #emph[Pharisees] fall upon our pates. As God is careful to instruct us how to carry our selves both to his own Majesty, and also one to another, so let us in both approve our selves to him: remembering what Christ said to the Pharisees, #emph[These ought ye to have done, and not to leave the other undone.] The same Lord that requireth praise to his own Majesty, enjoineth mutual service one to another; the neglect of this, as well as of that, showeth too light respect of his will and pleasure: #emph[What therefore God] #footnote[#emph[Matth.] 19. 6.] #emph[hath joined together, let not man put asunder.]

=== §. 3. #emph[Of every ones submitting himself to another.]

Again, as this verse hath reference to that which followeth, it declareth the general sum of all, which is mutually to submit our selves one to another in the fear of God. The parts hereof are two:

- 1\. An Exhortation.
- 2\. A Direction.

In the exhortation is noted, both the #emph[duty] it self in this word #emph[submit,] and also the #emph[parties] to whom it is to be performed, #emph[one to another.]

Both branches of the exhortation, viz. The #emph[duty,] and the #emph[parties] joined together, afford this doctrine, that

#emph[It is a general mutual duty appertaining to all Christians,] #footnote[2\. #emph[Doct.]] #emph[to submit themselves one to another:] For this precept is as general as any of the former, belonging to all sorts and degrees whatsoever: and so much doth this word #emph[one another] imply: in which extent the Apostle in another place exhorteth to #emph[serve one another:] and again, #emph[every man to seek] #footnote[#emph[Gal.] 5. 13. 1 #emph[Cor.] 10. 24.] #emph[anothers wealth.]

Concerning #emph[inferiors,] it is without question clear, that #footnote[Quest.] they ought to submit themselves to their superiors: yea, concerning #emph[equals] no great question can be made, but they #emph[in giving honour must go one before another,] and so submit #footnote[#emph[Rom.] 12. 10. How superiors ought to subject themselves.] themselves: but concerning #emph[superiors,] just question may be made, whether it be a duty required of them to submit themselves to their inferiors.

To resolve this doubt, we must first distinguish betwixt #footnote[Answ.] subjection of #emph[reverence,] and subjection of #emph[service.]

#emph[Subjection of reverence] is that whereby one testifieth an eminency and superiority in them whom he reverenceth, and that in speech, by giving them titles of honour; or in gesture, by some kind of obeisance; or in action, by a ready obeying of their commandment. This is proper to inferiors.

#emph[Subjection of service] is that whereby one in his place is #footnote[Difference betwixt subjection of #emph[Reverence] and #emph[Service.]] ready to do what good he can to another. This is common to all Christians: a duty which even superiors owe to inferiors, according to the fore-named extent of this word #emph[one another:] in which respect even the highest governor on earth is called a #emph[minister,] for the good of such as #footnote[#emph[Rom.] 13. 4.] are under him.

Secondly, we must put difference betwixt the #emph[work] it #footnote[Difference betwixt the #emph[work] and #emph[manner] of doing it.] self, and the #emph[manner] of doing it. That work which in it self is a work of superiority and authority, in the manner of doing it may be a work of submission, viz. If it be done in humility and meekness of mind. The Magistrate by ruling with meekness and humility, submitteth himself to his subject. In this respect the Apostle exhorteth that #emph[nothing] (no not the highest and greatest works that #footnote[#emph[Phil.] 2. 3.] can be) #emph[be done in vain-glory, but in meekness.]

Thirdly, we must distinguish betwixt the several places wherein men are: for even they who are superiors to some, #footnote[Every one under some authority. #emph[Matth.] 8. 9.] are inferiors to others: as he that said, #emph[I have under me, and am under authority.] The master that hath servants under him, may be under the authority of a Magistrate. Yea, God hath so disposed every ones several place, as there is not any one, but in some respect is under another. The wife, though a mother of children, is under her husband. The husband, though head of a family, is under public Magistrates. Public Magistrates one under another, and all under the King. The King himself under God and his word delivered by his Ambassadours, whereunto the highest are to submit themselves. And Ministers of the word, as subjects, are under their Kings and Governors. He that saith, #emph[Let every soul be subject to the higher powers,] #footnote[#emph[Rom.] 13. 1.] excepteth not Ministers of the word: and he that saith, #emph[obey them that have the oversight of you, and submit your selves,] #footnote[#emph[Heb.] 13. 17. Difference betwixt Magistrates and Ministers authority.] excepteth not kings: only the difference is in this, that the authority of the king is in himself, and in his own name he may command obedience to be performed to himself: but the authority of a Minister is in Christ, and in Christs name only may he require obedience to be performed to Christ.

The reason why all are bound to submit themselves one #footnote[#emph[Reason.] Every ones Office for the good of another.] to another is, because every one is set in his place by God, not so much for himself, as for the good of others: whereupon the Apostle exhorteth, that #emph[none seek his own, but every man anothers wealth.] Even Governors are advanced #footnote[1 #emph[Cor.] 10. 24.] to places of dignity and authority, rather for the good of their subjects then for their own honour. Their callings are in truth offices of service, yea burdens under which they must willingly put their shoulders, being called of God, and of which they are to give an account concerning the good which they have done to others: for the effecting whereof, it is needful that they submit themselves.

Let every one therefore high and low, rich and poor, #footnote[1\. #emph[Use.] Exhortation unto all to do service.] superior and inferior, Magistrate and subject, Minister and people, husband and wife, parent and child, master and servant, neighbours and fellows, all of all sorts in their several places take notice of their duty in this point of submission, and make conscience to put it in practice: #emph[Magistrates,] by procuring the wealth and peace of their people, as #emph[Mordecai: Ministers,] by making themselves servants #footnote[#emph[Est.] 10. 3.] unto their people, not seeking their own profit, but the #footnote[1 #emph[Cor.] 9. 19. & 10. 33.] profit of many, that they may be saved, as #emph[Paul: fathers,] by well educating their children, and taking heed that they #emph[provoke them not to wrath,] as #emph[David: husbands,] #footnote[#emph[Prov.] 4. 3, 4.] by dwelling with their wives according to knowledge; giving honour to the wife as to the weaker vessel, as #emph[Abraham:] #footnote[#emph[Gen.] 16. 6.] #emph[masters,] by doing that which is just and equal to their servants, as the #emph[Centurion:] Every one, by being of like #footnote[#emph[Luke] 7. 2.] affection one towards another, and by serving one another in love, according to the Apostles rule. Let this duty of #footnote[#emph[Rom.] 12. 16. #emph[Gal.] 5. 13.] submission be first well learned, and then all other duties will better be performed.

Be not high minded, nor swell one against another. #footnote[2\. #emph[Use.] Dehortation from swelling one against another.] Though in outward estate some may be higher than other, yet #emph[in Christ all are one whether bond or free:] all #emph[members of one and the same body.] Now consider the mutual affection (as I may so speak) of the members of a natural body one towards another: not any one of them will puff it self up, #footnote[#emph[Gal.] 3. 28.] and rise against the other: the head which is the highest #footnote[1 #emph[Cor.] 12. 27.] and of greatest honour will submit it self to the feet in performing the duty of an head, as well as the feet to the head in performing their duty; so all other parts. Neither is it hereby implied that they which are in place of dignity and authority should forget or relinquish their place, dignity, or authority, and become as inferiors under authority, no more than the head doth: for the head in submitting it self doth not go upon the ground and bear the body, as the feet; but it submitteth it self by directing and governing the other parts, and that with all the humility, meekness, and gentleness that it can. So must all superiors: much more must equals and inferiors learn with humility, and meekness, without scorn or disdain, to perform their duty: this is that which was before by the Apostle #footnote[#emph[Ephes.] 4. 2.] expressly mentioned, and is here again intimated; none are exempted and privileged from it. We know that it is unnatural, and unbeseeming the head to scorn the feet, and to swell against them, but more than monstrous for one hand to scorn another: what shall we then say if the feet swell against the head? Surely such scorn and disdain among the members, would cause not only great disturbance, but also utter ruin to the body. And can it be otherwise in a politic body? But on the contrary, when all of all sorts shall (as hath been before showed) willingly submit themselves one to another, the whole body, and every member thereof will reap good thereby: yea, by this mutual submission, as we do good, so we shall receive good.

=== §. 4. #emph[Of the fear of God.]

Hitherto of the #emph[exhortation.] The #emph[direction] followeth. #emph[In the fear of the Lord.] This clause is added, to declare partly the #emph[means,] how men may be brought to submit themselves readily one to another: and partly the #emph[manner,] how they ought to submit themselves. #emph[The fear of the Lord] is both the #emph[efficient cause] that moveth a true Christian willingly to perform all duty to man, and also the #emph[end] whereunto he referreth every thing that he doth. For the better conceiving whereof, I will briefly declare

- 1\. What this fear of the Lord is.
- 2\. How the Lord is the proper object of it.
- 3\. What is the extent thereof.
- 4\. Why it is so much urged.

First, fear of God is an awful respect of the divine Majesty. #footnote[1\. What the fear of God is. The causes of it.] Sometimes it ariseth from faith in the mercy and goodness of God: for when the heart of man hath once felt a sweet taste of Gods goodness, and found that in his favour only all happiness consisteth, it is strucken with such an inward awe and reverence, as it would not for any thing displease #footnote[Two effects of a filial fear of God.] his Majesty, but rather do whatsoever it may know to be pleasing and acceptable unto him. For these are two effects which arise from this kind of fear of God:

1. #emph[A careful endeavour to please God,] in which respect #footnote[#emph[Deum timere est nulla mala facere, & nulla bona quae facienda sunt praeterire. Bernar. de modo benè viuen. ser.] 4.] good king #emph[Jehoshaphat] having exhorted his Judges to execute the judgment of the Lord aright, addeth this clause as a motive thereunto, #emph[Let the fear of the Lord be upon you:] implying thereby that Gods fear would make them endeavour to approve themselves to God.

2. #emph[A careful avoiding of such things as offend the Majesty of God,] and grieve his spirit: in which respect the Wiseman #footnote[2 #emph[Chro.] 19. 6, 7.] saith, #emph[The fear of the Lord is to hate evil:] and of #emph[Job] it is #footnote[#emph[Prov.] 8. 13.] said that he #emph[fearing God departed from evil.] #footnote[#emph[Job.] 1. 1.]

Sometimes again, awe and dread of the divine Majesty ariseth from diffidence: For when a mans heart doubteth of Gods mercy, and expecteth nothing but vengeance, the very thought of God striketh an awe or rather dread into him, and so maketh him fear God.

From this double cause of fear, whereof one is contrary #footnote[Difference betwixt filial and servile fear.] to another, hath arisen that usual distinction of a #emph[filial] or son-like fear, and a #emph[servile] or slavish fear: which distinction is grounded on these words of the Apostle, #emph[ye have not received the spirit of bondage again to fear] (this is #footnote[Bernard. loc. citat.] a servile fear) #emph[but ye have received the spirit of adoption] #footnote[#emph[Rom.] 8. 15.] #emph[whereby we cry, Abba, father:] this causeth a filial fear. The #emph[filial] fear is such a fear as dutiful children bear to their fathers. But the #emph[servile] fear is such an one as bondslaves bear to their masters. A son feareth simply to offend or displease his father: so as #footnote[#emph[Est timor ne amittatur gratia beneficij. Hic timor castus est, non eum charitas eijcit, sed asciscit. August. epist.] 120.] it is accompanied with love. A bondslave feareth nothing but the punishment of his offence; so as it is joined with hatred: and such an one feareth not to sin, but to burn in hell for sin. Faithful #emph[Abraham] like a gracious child feared God (as Gods Angel beareth witness, #emph[Gen.] 22. 12.) when he was ready rather to sacrifice his only son, then offend God by refusing to #footnote[#emph[Qui gehennas metuit, non peccare metuit sed ardere. Aug. epist.] 144.] obey his commandment. But faithless #emph[Adam] like a servile bondslave feared God (as he himself testifieth against himself #emph[Gen.] 3. 10.) when after he had broken Gods commandment, he hid himself from the presence of God. This slavish fear is a plain diabolical fear (for #emph[the devils] #footnote[#emph[Jam.] 2. 19.] so fear as they #emph[tremble:)] It maketh men wish there were no hell, no day #emph[of Judgment,] no Judge, yea no God. This is that fear #emph[without which] we must serve the Lord. In this #footnote[#emph[Luke] 1. 74.] fear to submit ones self is nothing acceptable to God: It is therefore the #emph[filial fear] which is here meant.

Secondly, of this fear God is the proper #emph[object,] as by #footnote[2\. How God is the proper object of fear.] this and many more testimonies of Scripture is evident, where the fear of #emph[God] and of #emph[the Lord] is mentioned. This fear hath so proper a relation unto God, as the Scripture styleth God by a kind of propriety, with this title #emph[Fear:] for where #emph[Jacob] mentioneth #emph[the fear of Isaac,] he meaneth #footnote[#emph[Gen.] 31. 42, 53.] the Lord whom #emph[Isaac] feared.

It is then unlawful to fear any but God? #footnote[Quest.]

No: men also may be feared, as Princes, parents, masters, #footnote[#emph[Ans.] How men are to be feared.] and other superiors; For the Apostle exhorting to give every one their due, giveth this instance, #emph[fear,] #footnote[#emph[Rom.] 13. 7.] #emph[to whom fear is due.] But yet may God notwithstanding be said to be the proper object of fear, because all the fear that any way is due to any creature, is due to him in and for the Lord whose image he carrieth: so as in truth it is not so much the person of a man, as the image of God placed in him, by virtue of some authority or dignity appertaining to him, which is to be feared. If there should fall out any such opposition betwixt God and man, as in fearing man our fear would be withdrawn from God, then the rule of Christ is to take place, which is this, #emph[fear not them which] #footnote[#emph[Matth.] 10. 28.] #emph[kill the body, but are not able to kill the soul: but rather fear him which is able to destroy both soul and body in hell.]

Thirdly, the extent of this true filial fear of God is #footnote[3\. Every duty to be seasoned with a fear of God.] very large. No one point throughout the whole Scripture is more urged than this #emph[fear of the Lord.] It is oft added to other duties, as that whereby they are seasoned, and without which they cannot well be performed: wherefore we are commanded to #emph[serve the Lord in fear, to perfect holiness] #footnote[#emph[Psal.] 2. 11.] #emph[in the fear of God, to work out our salvation with fear:] and #footnote[2 #emph[Cor.] 7. 1.] the Churches are commended for #emph[walking in the fear of the] #footnote[#emph[Phil.] 2. 12.] #footnote[#emph[Acts] 9. 31.] #emph[Lord:] so likewise particular men as #footnote[a #emph[Gen.] 22. 12.] #emph[Abram,] #footnote[b & 42. 18.] #emph[Joseph,] #footnote[c #emph[Job] 1. 1.] #emph[Job,] and many other: yea the whole worship of God is oft comprised under this branch of #emph[fear:] whereupon our Saviour Christ alleging this text, #emph[thou shalt fear the Lord thy God,] #footnote[#emph[Deut.] 6. 13.] thus expresseth it, #emph[thou shalt worship the Lord thy God.] And #footnote[#emph[Matth.] 4. 10.] again where the Lord by his Prophet #emph[Isaiah] saith, #emph[Their fear] #footnote[#emph[Isa.] 29. 13.] #emph[toward me is taught by the precept of men,] Christ thus quoteth that text, #emph[In vain do they worship me, teaching for doctrines] #footnote[#emph[Matth.] 15. 9.] #emph[the commandments of men:] out of which places compared together, it is evident, that under the #emph[fear] of God, is comprised the #emph[worship] of God. Yea, all that duty which we owe to God and man is comprised under this title, #emph[the fear of God:] for #emph[David] when he would in one word declare the sum and substance of all that which a Minister ought to teach his people, saith, #emph[I will teach you the fear of] #footnote[#emph[Psal.] 34. 11.] #emph[the Lord.] #footnote[4\. Why a fear of God is so much urged.]

Fourthly, The reason why the Holy Ghost so much urgeth #emph[the fear of God,] and that in so large an extent as hath been showed, I take to be this; to show a difference betwixt that integrity and perfection of Gods image which was at mans creation first planted in him, and the renovation thereof while here he liveth in this world. So complete and perfect was then Gods image in man, as he needed no other motive to provoke him to any duty but #emph[love.] Wherefore when the Holy Ghost would set forth that perfection of Gods image first planted in man, he addeth this title #emph[love] unto other duties, whether they concern God or man. Concerning God, #emph[Moses] exhorteth Israel to #emph[love the] #footnote[#emph[Deut.] 11. 13.] #emph[Lord and serve him:] and again, #emph[to love the Lord, to walk in] #footnote[#emph[Deut.] 30. 16.] #emph[his ways, to keep his commandments, etc.] Concerning man, the Apostle exhorteth to #emph[serve one another by love:] and #emph[to do] #footnote[#emph[Gal.] 5. 13.] #emph[all things in love.] Yea, sometimes the Holy Ghost is pleased #footnote[1 #emph[Cor.] 16. 14.] to comprise all duties under #emph[love:] In which respect Christ calleth this commandment #emph[(Thou shalt love the Lord) the] #footnote[#emph[Matth.] 22. 38.] #emph[great commandment,] which compriseth all the commandments of the first table under it: and for the second table, #emph[S. Paul] saith, that #emph[love is the fulfilling of the law.] But by #emph[Adam's] #footnote[#emph[Rom.] 13. 10.] fall, and the corruption which thereby infected mans nature, the love of God hath waxed cold in man, and though the Saints be created again according to that image of God, yet while in this world they live, that image is not so perfect as it was, the flesh remaineth in the best: in which respect God hath fast fixed this affection of #emph[fear] in mans heart, and thereby both restraineth him from sin, and also provoketh him unto every good duty.

=== §. 5. #emph[Of the fear of God moving us to do service to men.]

Having briefly declared the #emph[nature, object, extent,] and #emph[use] of fear, I return to the point in hand, #emph[viz.] to show 1. How it is here laid down as a motive to stir up men to perform the duty here required: for by this clause, #emph[in the fear of the Lord,] the Apostle implieth that

#emph[It is the fear of God which moveth men conscionably to submit] #footnote[Doct.] #emph[themselves one to another.] This made #footnote[2 #emph[Sam.] 23. 3.] #emph[David] so well to rule the people of God: and #footnote[#emph[Gen.] 42. 18.] #emph[Joseph] to deal so well with his brethren: yea, #footnote[#emph[Isa.] 11. 2, 3.] this is noted to be the cause of the righteous regiment of Christ himself. Well did that good King #emph[Jehoshaphat] know this, and therefore when he appointed Judges over his people, as a motive to stir them up to execute the judgments of the Lord aright, he saith unto them, #emph[Let the fear of the Lord be upon you.] So also #emph[S. Peter,] #footnote[2 #emph[Chron.] 19. 7.] to move subjects to honour their King, prefixeth this exhortation, #emph[Fear God.] #footnote[1 #emph[Pet.] 2. 17.]

By fear of man, may one be brought to submit himself #footnote[Object.] to another: as a magistrate may be moved to deal justly and mildly with his people through fear of insurrections and rebellions: subjects may by severe laws and tyranny be brought to submit themselves: and so other inferiors also by threats, by hard usage, and other by-respects.

1. Though fear of man be a motive, yet it followeth #footnote[Answ.] not, that therefore fear of God should be no motive: it may be another motive, and a better motive.

2. The submission which is performed through fear of #footnote[Difference betwixt doing a thing for fear of God and fear of man.] man is a forced and a slavish submission, nothing acceptable to God: but that which is performed through a true filial fear of God, is a free, willing, ready, cheerful, conscionable submission: such a submission as will stir us up to do the best good we can thereby unto them, to whom we submit our selves, and so is more acceptable to God, by reason of the cause thereof, and more profitable unto man, by reason of the effect and fruit thereof.

For a true fear of God maketh us more respect what #footnote[#emph[Reason.] The power of a fear of God.] God requireth and commandeth, than what our corrupt heart desireth and suggesteth: It subdueth our unruly passions, and bringeth them within compass of duty: It maketh us deny our selves and our own desires: and though through the corruption of our nature and inborn pride we be loth to submit, yet will Gods fear bring down that proud mind, and make us humble and gentle. It will keep those who are in authority from tyranny, cruelty, and over-much severity: and it will keep those who are under subjection from dissimulation, deceit, and privy conspiracies.

Behold how necessary it is, that a true fear of the Lord #footnote[#emph[Use.] The necessity of a fear of God.] be planted in mens hearts, in the hearts of Kings and all Governors, in the hearts of subjects and all people, whether superiors or inferiors. Where no fear of God is, there will be no good submission unto man. #emph[Abraham] #footnote[#emph[Gen.] 20. 11.] thought that the men of Gerar would have no respect to him or his wife, nor make conscience of common honesty, nor abstain from innocent blood, because #emph[he saw no fear of God in that place:] and the Apostle having reckoned up #footnote[#emph[Rom.] 3. 11, #emph[etc.]] many notorious effects of mans natural corruption, concludeth all with this, as the cause of all, #emph[There is no fear of God before their eyes.] Wherefore let Magistrates, parents, masters, and all in authority, have especial care that their subjects, children, servants, and all under them may be taught and brought to fear the Lord. I dare avouch it, that such inferiors which are taught to fear God, will do better service to their superiors, than such as fear their superiors only as men, and fear not God. Let Ministers especially urge and press upon the consciences of men a fear of God. Let all inferiors pray that the fear of the Lord may be planted in the hearts of their superiors, that so they may live a quiet and peaceable life in all godliness and honesty under them. Happy is that kingdom where Magistrates and subjects fear the Lord. Happy is that Church where Ministers and people fear the Lord. Happy is that family where husband and wife, parents and children, master and servants fear the Lord. In such a Kingdom, Church, and family, will every one, to the mutual good one of another, submit themselves one to another. But if such as fear not God submit themselves, whether they be superiors or inferiors, it is for their own ends and advantages, and not for their good to whom they submit themselves.

=== §. 6. #emph[Of limiting all duty to man, within the compass of the fear of God.]

Again, as this clause #emph[(In the fear of the Lord)] declareth the manner of submission, it showeth, that

#emph[No submission is to be performed unto man, but that which] #footnote[Doct.] #emph[may stand with the fear of God.] Whereby we show that we have respect to God, and labour above all to approve our selves to him. Thus #emph[David] is commanded to #emph[rule in the] #footnote[2 #emph[Sam.] 23. 3.] #emph[fear of God:] and other Magistrates to perform their duty #footnote[2 #emph[Chro.] 19. 9.] #emph[in the fear of the Lord:] which #emph[Nehemiah] that good Governor #footnote[#emph[Neh.] 5. 15.] was careful to do. So also subjects are to obey in the #emph[fear of the Lord,] which the Apostle implieth by prefixing #footnote[1 #emph[Pet.] 2. 17.] this precept, #emph[Fear God,] before that, #emph[honour the King;] as if he had said, so honour the King, as in and thereby you may manifest your fear of God: let not this latter cross the former. Servants likewise are commanded to be obedient unto their masters with this proviso, #emph[fearing the Lord.] Such #footnote[#emph[Coloss.] 3. 22.] phrases as these, #emph[For the Lords sake, As unto the Lord, In the] #footnote[1 #emph[Pet.] 2. 13.] #emph[Lord, As servants of Christ,] with the like, being annexed to #footnote[#emph[Eph.] 5. 22. #emph[&] 6. 1, 6.] the duties of inferiors, do imply as much.

Great reason there is that all service should be limited #footnote[1\. #emph[Reason.] God the highest Lord.] with the #emph[fear of God:] for God is the highest Lord to whom all service primarily and principally is due: whatsoever service is due to any man, high or low, is due in and for the Lord. The Lord hath set superiors in the places of eminency, wherein they bear the image of God. The Lord also hath set inferiors in their places, and commended them as his charge to the government of those who are over them. He that obeyeth not those who are over him #emph[in the fear of God,] showeth no respect of Gods image: and he who governeth not those who are under him #emph[in the fear of God,] showeth no respect of Gods charge.

Besides, God is that great Judge to whom all of all sorts, #footnote[2\. #emph[Reason.] God the Judge of all.] superiors and inferiors are to give an account of their service. Though by our service we have never so well approved our selves to men, yet if we have not therein had respect unto God, and approved our selves to him, with what face may we appear before his dreadful judgment seat? #footnote[1\. #emph[Use.] The folly of all those who fear man more than God.] Can the favour of those whom we have pleased in this world, protect and shelter us from the fury of Gods displeasure?

Behold the folly of such Governors as wholly apply themselves to the fancy of their people, yea though it be against the Lord and his word. This was #emph[Adam's] folly, who #footnote[#emph[Gen.] 3. 6.] at his wives motion did eat of the forbidden fruit. This was #emph[Aarons] folly, who to please the people, erected an #footnote[#emph[Exod.] 32. 1.] Idol. And this was #emph[Sauls] folly, who against Gods express #footnote[1 #emph[Sam.] 15. 21.] prohibition suffered his people to take some of the spoil of the Amalekites. The like may be said of #emph[Joash,] who #footnote[2 #emph[Chro.] 24. 17.] hearkened to his Princes to set up Idols: and of #emph[Pilate,] who #footnote[#emph[Mark] 15. 15.] to please the people, against his conscience, delivered Christ to be crucified. The fearful issue of this their submission, not seasoned with a fear of God, but contrary thereunto, may be a warning to all superiors, to take heed how they seek to please them that are under them, more than God who is above them. The issue of #emph[Adam's, Aarons, Sauls,] and #emph[Joash] his base submission, is noted by the Holy Ghost in their several histories. Of #emph[Pilate] it is recorded, that being #footnote[#emph[Euseb. hist. Eccl. lib] 2. #emph[cap.] 7.] brought into extreme necessity, he laid violent hands upon himself.

Neither is it to be accounted folly only in superiors to submit themselves to their inferiors against the Lord, but also in inferiors to their superiors: for thereby they show that they fear man more than God, which Christ expressly #footnote[#emph[Luke] 12. 4, 5.] forbiddeth his friends to do. The captains which went #footnote[2 #emph[King.] 1. 9, #emph[etc.]] to fetch #emph[Elijah,] obeyed their king therein; but what got they thereby? Was the king able to save them from the fire which God sent down from heaven upon them? The women #footnote[#emph[Jer.] 44. 19.] reproved for offering incense to the Queen of heaven, did it not without their husbands, yet were they not excused thereby. The children and others in the family #footnote[#emph[Numb.] 16. 32.] submitted themselves to #emph[Dathan] and #emph[Abiram] in standing in the door of their tents at defiance against #emph[Moses;] but because it was not in the Lord, but against him, they were not exempted from the judgment. Wherefore let all of all sorts set the #emph[fear of God] as a mark before them to aim at in all their actions. Let superiors #footnote[#emph[Numb.] 11. 29.] neither do any thing to give content to their inferiors: #footnote[1 #emph[Sam.] 24. 8. #emph[&] 26. 9.] nor suffer any thing to be done for their sakes by their inferiors, which cannot stand with the #emph[fear of God.] And let inferiors #footnote[#emph[Gen.] 39. 10.] nor do, #footnote[1 #emph[Sam.] 22. 17.] #footnote[#emph[Act.] 4. 19.] nor forbear to do at the will of their superiors any thing swerving from the fear of God: but #emph[every one submit themselves one to another in the fear of God.]
