== Chapter XI

#block(inset: (x: 1em))[The third direction proposed: Load thy conscience with the guilt of the perplexing distemper — The ways and means whereby that may be done — The fourth direction: Vehement desire for deliverance — The fifth: Some distempers rooted deeply in men’s natural tempers — Considerations of such distempers; ways of dealing with them — The sixth direction: Occasions and advantages of sin to be prevented — The seventh direction: The first actings of sin vigorously to be opposed.]

This is my third direction, —

#emph[Load thy conscience with the guilt of it.] Not only consider that it hath a guilt, but load thy conscience with the guilt of its actual eruptions and disturbances.

For the right improvement of this rule I shall give some particular directions:—

1\. Take #emph[God’s method] in it, and begin with generals, and so descend to particulars:—

(1.) Charge thy conscience with that guilt which appears in it #emph[from the rectitude and holiness of the law]. Bring the holy law of God into thy conscience, lay thy corruption to it, pray that thou mayst be affected with it. Consider the holiness, spirituality, fiery severity, inwardness, absoluteness of the law, and see how thou canst stand before it. Be much, I say, in affecting thy conscience with the terror of the Lord in the law, and how righteous it is that every one of thy transgressions should receive a recompense of reward. Perhaps thy conscience will invent shifts and evasions to keep off the power of this consideration; — as, that the condemning power of the law doth not belong to thee, thou art set free from it, and the like; and so, though thou be not conformable to it, yet thou needest not to be so much troubled at it. But, —

\[1.\] Tell thy conscience that it cannot manage any evidence to the purpose that thou art free from the #emph[condemning] power of sin, whilst thy #emph[unmortified] lust lies in thy heart; so that, perhaps, the law may make good its plea against thee for a full dominion, and then thou art a lost creature. Wherefore it is best to ponder to the utmost what it hath to say.

Assuredly, he that pleads in the most secret reserve of his heart that he is freed from the condemning power of the law, thereby secretly to countenance himself in giving the least allowance unto any sin or lust, is not able, on gospel grounds, to manage any evidence, unto any tolerable spiritual security, that indeed he is in a due manner freed from what he so pretends himself to be delivered.

\[2.\] Whatever be the #emph[issue], yet the law hath commission from God to seize upon transgressors wherever it find them, and so bring them before his throne, where they are to plead for themselves. This is thy present case; the law hath found thee out, and before God it will bring thee. If thou canst plead a pardon, well and good; if not, the law will do its work.

\[3.\] However, this is the #emph[proper work] of the law, to discover sin in the guilt of it, to awake and humble the soul for it, to be a glass to represent sin in its colours; and if thou deniest to deal with it on this account, it is not through faith, but through the hardness of thy heart and the deceitfulness of sin.

This is a door that too many professors have gone out at unto open apostasy. Such a deliverance from the law they have pretended, as that they would consult its guidance and direction no more; they would measure their sin by it no more. By little and little this principle hath insensibly, from the notion of it, proceeded to influence their practical understandings, and, having taken possession there, hath turned the will and affections loose to all manner of abominations.

By such ways, I say, then, as these, persuade thy conscience to hearken diligently to what the law speaks, in the name of the Lord, unto thee about thy lust and corruption. Oh! if thy ears be open, it will speak with a voice that shall make thee tremble, that shall cast thee to the ground, and fill thee with astonishment. If ever thou wilt mortify thy corruptions, thou must tie up thy conscience to the law, shut it from all shifts and exceptions, until it owns its guilt with a clear and thorough apprehension; so that thence, as David speaks, thy “iniquity may ever be before thee.”

(2.) Bring #emph[thy lust to the gospel], — not for relief, but for farther conviction of its guilt; look on Him whom thou hast pierced, and be in bitterness. Say to thy soul, “What have I done? What love, what mercy, what blood, what grace have I despised and trampled on! Is this the return I make to the Father for his #emph[love], to the Son for his #emph[blood], to the Holy Ghost for his #emph[grace]? Do I thus requite the Lord? Have I defiled the heart that Christ died to wash, that the blessed Spirit hath chosen to dwell in? And can I keep myself out of the dust? What can I say to the dear Lord Jesus? How shall I hold up my head with any boldness before him? Do I account communion with him of so little value, that for this vile lust’s sake I have scarce left him any room in my heart? How shall I escape if I neglect so great salvation? In the meantime, what shall I say to the Lord? Love, mercy, grace, goodness, peace, joy, consolation, — I have despised them all, and esteemed them as a thing of nought, that I might harbour a lust in my heart. Have I obtained a view of God’s fatherly countenance, that I might behold his face and provoke him to his face? Was my soul washed, that room might be made for new defilements? Shall I endeavour to disappoint the end of the death of Christ? Shall I daily grieve that Spirit whereby I am sealed to the day of redemption?” Entertain thy conscience daily with this treaty. See if it can stand before this aggravation of its guilt. If this make it not sink in some measure and melt, I fear thy case is dangerous.

2\. Descend to #emph[particulars]. As under the general head of the gospel all the benefits of it are to be considered, as redemption, justification, and the like; so, in particular, consider the management of the love of them towards thine own soul, for the aggravation of the guilt of thy corruption. As, —

(1.) Consider #emph[the infinite patience and forbearance] of God towards thee in particular. Consider what advantages he might have taken against thee, to have made thee a shame and a reproach in this world, and an object of wrath for ever; how thou hast dealt treacherously and falsely with him from time to time, flattered him with thy lips, but broken all promises and engagements, and that by the means of that sin thou art now in pursuit of; and yet he hath spared thee from time to time, although thou seemest boldly to have put it to the trial how long he could hold out. And wilt thou yet sin against him? wilt thou yet weary him, and make him to serve with thy corruptions?

Hast thou not often been ready to conclude thyself, that it was utterly impossible that he should bear any longer with thee; that he would cast thee off, and be gracious no more; that all his forbearance was exhausted, and hell and wrath was even ready prepared for thee? and yet, above all thy expectation, he hath returned with visitations of love. And wilt thou yet abide in the provocation of the eyes of his glory?

(2.) How often hast thou been #emph[at the door of being hardened] by the deceitfulness of sin, and by the infinite rich grace of God hast been recovered to communion with him again?

Hast thou not found grace decaying; delight in duties, ordinances, prayer and meditation, vanishing; inclinations to loose careless walking, thriving; and they who before were entangled, almost beyond recovery? Hast thou not found thyself engaged in such ways, societies, companies, and that with delight, as God abhors? And wilt thou venture any more to the brink of hardness?

(3.) All God’s gracious dealings with thee, in providential dispensations, deliverances, afflictions, mercies, enjoyments, all ought here to take place. By these, I say, and the like means, load thy conscience; and leave it not until it be thoroughly affected with the guilt of thy indwelling corruption, until it is sensible of its wound, and lie in the dust before the Lord. Unless this be done to the purpose, all other endeavours are to no purpose. Whilst the conscience hath any means to alleviate the guilt of sin, the soul will never vigorously attempt its mortification.

Fourthly. Being thus affected with thy sin, in the next place get #emph[a constant longing, breathing after deliverance from the power of it]. Suffer not thy heart one moment to be contented with thy present frame and condition. Longing desires after any thing, in things natural and civil, are of no value or consideration, any farther but as they incite and stir up the person in whom they are to a diligent use of means for the bringing about the thing aimed at. In spiritual things it is otherwise. Longing, breathing, and panting after deliverance is a grace in itself, that hath a mighty power to conform the soul into the likeness of the thing longed after. Hence the apostle, describing the repentance and godly sorrow of the Corinthians, reckons this as one eminent grace that was then set on work, “Vehement desire,” 2 Cor. vii. 11. And in this case of indwelling sin and the power of it, what frame doth he express himself to be in? Rom. vii. 24. His heart breaks out with longings into a most passionate expression of desire of deliverance. Now, if this be the frame of saints upon the general consideration of indwelling sin, how is it to be heightened and increased when thereunto is added the perplexing rage and power of any particular lust and corruption! Assure thyself, unless thou #emph[longest] for deliverance thou shalt not have it.

This will make the heart watchful for all opportunities of advantage against its enemy, and ready to close with any assistances that are afforded for its destruction. Strong desires are the very life of that “praying always” which is enjoined us in all conditions, and in none is more necessary than in this; they set faith and hope on work, and are the soul’s moving after the Lord.

Get thy heart, then, into a panting and breathing frame; long, sigh, cry out. You know the example of David; I shall not need to insist on it.

The fifth direction is, —

Consider whether the distemper with which thou art perplexed be not rooted in thy #emph[nature], and cherished, fomented, and heightened from thy #emph[constitution]. A proneness to some sins may doubtless lie in the natural temper and disposition of men. In this case consider, —

1\. This is not in the least an #emph[extenuation] of the guilt of thy sin. Some, with an open profaneness, will ascribe gross enormities to their temper and disposition; and whether others may not relieve themselves from the pressing guilt of their distempers by the same consideration, I know not. It is from the fall, from the original depravation of our natures, that the #emph[fomes] and nourishment of any sin abides in our natural temper. David reckons his being shapen in iniquity and conception in sin#footnote[Ps. li. 5.] as an aggravation of his following sin, not a lessening or extenuation of it. That thou art peculiarly inclined unto any sinful distemper is but a peculiar breaking out of original lust in thy nature, which should peculiarly abase and humble thee.

2\. That thou hast to #emph[fix] upon on this account, in reference to thy walking with God, is, that so great an advantage is given to sin, as also to Satan, by this thy temper and disposition, that without extraordinary watchfulness, care, and diligence, they will assuredly prevail against thy soul. Thousands have been on this account hurried headlong to hell, who otherwise, at least, might have gone at a more gentle, less provoking, less mischievous rate.

3\. For the mortification of any distemper so rooted in the nature of a man, unto all other ways and means already named or farther to be insisted on, there is one #emph[expedient] peculiarly suited; this is that of the apostle, 1 Cor. ix. 27, “I keep under my body, and bring it into subjection.” The bringing of the very body into subjection is an ordinance of God tending to the mortification of sin. This gives check unto the natural root of the distemper, and withers it by taking away its fatness of soil. Perhaps, because the Papists, men ignorant of the righteousness of Christ, the work of his Spirit, and whole business in hand, have laid the whole weight and stress of mortification in voluntary services and penances, leading to the subjection of the body, knowing indeed the true nature neither of sin nor mortification, it may, on the other side, be a temptation to some to neglect some means of humiliation which by God himself are owned and appointed. The bringing of the body into subjection in the case insisted on, by cutting short the natural appetite, by fasting, watching, and the like, is doubtless acceptable to God, so it be done with the ensuing limitations:—

(1.) That the outward weakening and impairing of the body be not looked upon as a thing good in itself, or that any mortification doth consist therein, — which were again to bring us under carnal ordinances; but only as a means for the end proposed, — the weakening of any distemper in its natural root and seat. A man may have leanness of body and soul together.

(2.) That the means whereby this is done, — namely, by fasting and watching, and the like, — be not looked on as things that in themselves, and by virtue of their own power, can produce true mortification of any sin; for if they would, sin might be mortified without any help of the Spirit in any unregenerate person in the world. They are to be looked on only as ways whereby the Spirit may, and sometimes doth, put forth strength for the accomplishing of his own work, especially in the case mentioned. Want of a right understanding and due improvement of these and the like considerations, hath raised a mortification among the Papists that may be better applied to horses and other beasts of the field than to believers.

This is the sum of what hath been spoken: When the distemper complained of seems to be rooted in the natural temper and constitution, in applying our souls to a participation of the blood and Spirit of Christ, an endeavour is to be used to give check in the way of God to the natural root of that distemper.

The sixth direction is, —

Consider what #emph[occasions], what #emph[advantages] thy distemper hath taken to exert and put forth itself, and watch against them all.

This is one part of that duty which our blessed Saviour recommends to his disciples under the name of #emph[watching]: Mark xiii. 37, “I say unto you all, Watch;” which, in Luke xxi. 34, is, “Take heed lest your hearts be overcharged.” Watch against all eruptions of thy corruptions. I mean that duty which David professed himself to be exercised unto. “I have,” saith he, “kept myself from mine iniquity.” He watched all the ways and workings of his iniquity, to prevent them, to rise up against them. This is that which we are called unto under the name of “considering our ways.” Consider what ways, what companies, what opportunities, what studies, what businesses, what conditions, have at any time given, or do usually give, advantages to thy distempers, and set thyself heedfully against them all. Men will do this with respect unto their bodily infirmities and distempers. The seasons, the diet, the air that have proved offensive shall be avoided. Are the things of the soul of less importance? Know that he that dares to dally with occasions of sin will dare to sin. He that will venture upon temptations unto wickedness will venture upon wickedness. Hazael thought he should not be so wicked as the prophet told him he would be. To convince him, the prophet tells him no more but, “Thou shalt be king of Syria.” If he will venture on temptations unto cruelty, he will be cruel. Tell a man he shall commit such and such sins, he will startle at it. If you can convince him that he will venture on such occasions and temptations of them, he will have little ground left for his confidence. Particular directions belonging to this head are many, not now to be insisted on. But because this head is of no less importance than the whole doctrine here handled, I have at large in another treatise, about entering into temptations, treated of it.

The seventh direction is, —

Rise mightily against #emph[the first actings] of thy distemper, its first conceptions; suffer it not to get the least ground. Do not say, “Thus far it shall go, and no farther.” If it have allowance for one step, it will take another. It is impossible to fix bounds to sin. It is like water in a channel, — if it once break out, it will have its course. Its not acting is easier to be compassed than its bounding. Therefore doth James give that gradation and process of lust, chap. i. 14, 15, that we may stop at the entrance. Dost thou find thy corruption to begin to entangle thy thoughts? rise up with all thy strength against it, with no less indignation than if it had fully accomplished what it aims at. Consider what an unclean thought would have; it would have thee roll thyself in folly and filth. Ask #emph[envy] what it would have; — #emph[murder] and #emph[destruction] is at the end of it. Set thyself against it with no less vigour than if it had utterly debased thee to wickedness. Without this course thou wilt not prevail. As sin gets ground in the affections to delight in, it gets also upon the understanding to slight it.
