== Chapter VI

#block(inset: (x: 1em))[The mortification of sin in particular described — The several parts and degrees thereof — The habitual weakening of its root and principle — The power of lust to tempt — Differences of that power as to persons and times — Constant fighting against sin — The parts thereof considered — Success against it — The sum of this discourse considered.]

What it is to mortify a sin in general, which will make farther way for particular directions, is nextly to be considered.

2\. The mortification of a lust consists in three things:—

(1.) An #emph[habitual] weakening of it. Every lust is a depraved habit or disposition, continually inclining the heart to evil. Thence is that description of him who hath no lust truly mortified, Gen. vi. 5, “Every imagination of the thoughts of his heart is only evil continually.” He is always under the power of a strong bent and inclination to sin. And the reason why a natural man is not always perpetually in the pursuit of some one lust, night and day, is because he hath many to serve, every one crying to be satisfied; thence he is carried on with great variety, but still in general he lies towards the satisfaction of self.

We will suppose, then, the lust or distemper whose mortification is inquired after to be in itself a strong, deeply-rooted, habitual inclination and bent of will and affections unto some actual sin, as to the matter of it, though not, under that formal consideration, always stirring up imaginations, thoughts, and contrivances about the object of it. Hence, men are said to have their “hearts set upon evil,” the bent of their spirits lies towards it, to make “provision for the flesh.”#footnote[Rom. xiii 14.] And a sinful, depraved habit, as in many other things, so in this, differs from all natural or moral habits whatever: for whereas they incline the soul gently and suitably to itself, sinful habits impel with violence and impetuousness; whence lusts are said to fight or wage “war against the soul,”#footnote[Στρατεύονται κατὰ τῆς ψυχῆς.] 1 Pet. ii. 11, — to rebel or rise up in war with that conduct and opposition which is usual therein,#footnote[Ἀντιστρατευόμενον, αἰχμαλωτίζοντα.] Rom. vii. 23, — to lead captive, or effectually captivating upon success in battle, — all works of great violence and impetuousness.

I might manifest fully, from that description we have of it, Rom. vii., how it will darken the mind, extinguish convictions, dethrone reason, interrupt the power and influence of any considerations that may be brought to hamper it, and break through all into a flame. But this is not my present business. Now, the first thing in mortification is the weakening of this habit of sin or lust, that it shall not, with that violence, earnestness, frequency, rise up, conceive, tumultuate, provoke, entice, disquiet, as naturally it is apt to do, James i. 14, 15.

I shall desire to give one caution or rule by the way, and it is this: Though every lust doth in its own nature equally, universally, incline and impel to sin, yet this must be granted with these two limitations:—

\[1.\] #emph[One lust], or a lust in one man, may receive many accidental improvements, heightenings, and strengthenings, which may give it life, power, and vigour, exceedingly above what another lust hath, or the same lust (that is, of the same kind and nature) in another man. When a lust falls in with the natural constitutions and temper, with a suitable course of life, with occasions, or when Satan hath got a fit handle to it to manage it, as he hath a thousand ways so to do, that lust grows violent and impetuous above others, or more than the same lust in another man; then the steams of it darken the mind so, that though a man knows the same things as formerly, yet they have no power nor influence on the will, but corrupt affections and passions are set by it at liberty.

But especially, lust gets strength by #emph[temptation]. When a suitable temptation falls in with a lust, it gives it a new life, vigour, power, violence, and rage, which it seemed not before to have or to be capable of. Instances to this purpose might be multiplied; but it is the design of some part of another treatise to evince this observation.

\[2.\] Some lusts are far more sensible and discernible in their violent actings than others. Paul puts a difference between uncleanness and all other sins: 1 Cor. vi. 18, “Flee fornication. Every sin that a man doeth is without the body; but he that committeth fornication sinneth against his own body.” Hence, the motions of that sin are more sensible, more discernible than of others; when perhaps the love of the world, or the like, is in a person no less habitually predominant than that, yet it makes not so great a combustion in the whole man.

And on this account some men may go in their own thoughts and in the eyes of the world for mortified men, who yet have in them no less predominancy of lust than those who cry out with astonishment upon the account of its perplexing tumultuatings, yea, than those who have by the power of it been hurried into scandalous sins; only their lusts are in and about things which raise not such a tumult in the soul, about which they are exercised with a calmer frame of spirit, the very fabric of nature being not so nearly concerned in them as in some other.

I say, then, that the first thing in mortification is the #emph[weakening] of this habit, that it shall not impel and tumultuate as formerly; that it shall not entice and draw aside; that it shall not disquiet and perplex the killing of its life, vigour, promptness, and readiness to be stirring. This is called “crucifying the flesh with the lusts thereof,” Gal. v. 24; that is, taking away its blood and spirits that give it strength and power, — the wasting of the body of death “day by day,” 2 Cor. iv. 16.

As a man #emph[nailed to the cross]\; he first struggles, and strives, and cries out with great strength and might, but, as his blood and spirits waste, his strivings are faint and seldom, his cries low and hoarse, scarce to be heard; — when a man first sets on a lust or distemper, to deal with it, it struggles with great violence to break loose; it cries with earnestness and impatience to be satisfied and relieved; but when by mortification the blood and spirits of it are let out, it moves seldom and faintly, cries sparingly, and is scarce heard in the heart; it may have sometimes a dying pang, that makes an appearance of great vigour and strength, but it is quickly over, especially if it be kept from considerable success. This the apostle describes, as in the whole chapter, so especially, Rom. vi. 6.

“Sin,” saith he, “is crucified; it is fastened to the cross.” To what end? “That the body of death may be destroyed,” the power of sin weakened and abolished by little and little, that “henceforth we should not serve sin;” that is, that sin might not incline, impel us with such efficacy as to make us servants to it, as it hath done heretofore. And this is spoken not only with respect to carnal and sensual affections, or desires of worldly things, — not only in respect of the lust of the flesh, the lust of the eyes, and the pride of life, — but also as to the flesh, that is, in the mind and will, in that opposition unto God which is in us by nature. Of what nature soever the troubling distemper be, by what ways soever it make itself out, either by impelling to evil or hindering from that which is good, the rule is the same; and unless this be done effectually, all after-contention will not compass the end aimed at. A man may beat down the bitter fruit from an evil tree until he is weary; whilst the root abides in strength and vigour, the beating down of the present fruit will not hinder it from bringing forth more. This is the folly of some men; they set themselves with all earnestness and diligence against the appearing eruption of lust, but, leaving the principle and root untouched, perhaps unsearched out, they make but little or no progress in this work of mortification.

(2.) In constant #emph[fighting] and #emph[contending] against sin. To be able always to be laying load on sin is no small degree of mortification. When sin is strong and vigorous, the soul is scarce able to make any head against it; it sighs, and groans, and mourns, and is troubled, as David speaks of himself, but seldom has sin in the pursuit. David complains that his sin had “taken fast hold upon him, that he could not look up,” Ps. xl. 12. How little, then, was he able to fight against it! Now, sundry things are required unto and comprised in this fighting against sin:—

\[1.\] To #emph[know] that a man hath such an enemy to deal withal, to take notice of it, to consider it as an enemy indeed, and one that is to be destroyed by all means possible, is required hereunto. As I said before, the contest is vigorous and hazardous, — it is about the things of eternity. When, therefore, men have slight and transient thoughts of their lusts, it is no great sign that they are mortified, or that they are in a way for their mortification. This is every man’s “knowing the plague of his own heart,” 1 Kings viii. 38, without which no other work can be done. It is to be feared that very many have little knowledge of the main enemy that they carry about with them in their bosoms. This makes them ready to justify themselves, and to be impatient of reproof or admonition, not knowing that they are in any danger, 2 Chron. xvi. 10.

\[2.\] To labour to be acquainted with the ways, wiles, methods, advantages, and occasions of its #emph[success], is the beginning of this warfare. So do men deal with enemies. They inquire out their counsels and designs, ponder their ends, consider how and by what means they have formerly prevailed, that they may be prevented. In this consists the greatest skill in conduct. Take this away, and all waging of war, wherein is the greatest improvement of human wisdom and industry, would be brutish. So do they deal with lust who mortify it indeed. Not only when it is actually vexing, enticing, and seducing, but in their retirements they consider, “This is our enemy; this is his way and progress, these are his advantages, thus hath he prevailed, and thus he will do, if not prevented.” So David, “My sin is ever before me,” Ps. li. 3. And, indeed, one of the choicest and most eminent parts of practically spiritual wisdom consists in finding out the subtilties, policies, and depths of any indwelling sin; to consider and know wherein its greatest strength lies, — what advantage it uses to make of occasions, opportunities, temptations, — what are its pleas, pretences, reasonings, — what its stratagems, colours, excuses; to set the wisdom of the Spirit against the craft of the #emph[old man]\; to trace this serpent in all its turnings and windings; to be able to say, at its most secret and (to a common frame of heart) imperceptible actings, “This is your old way and course; I know what you aim at;” — and so to be always in readiness is a good part of our warfare.

\[3.\] To load it daily with all the things which shall after be mentioned, that are grievous, killing, and destructive to it, is the height of this contest. Such a one never thinks his lust dead because it is quiet, but labours still to give it new wounds, new blows every day. So the apostle, Col. iii. 5.

Now, whilst the soul is in this condition, whilst it is thus dealing, it is certainly uppermost; sin is under the sword and #emph[dying].

(3.) In #emph[success]. Frequent success against any lust is another part and evidence of mortification. By success I understand not a mere disappointment of sin, that it be not brought forth nor accomplished, but a victory over it, and pursuit of it to a complete conquest. For instance, when the heart finds sin at any time at work, seducing, forming imaginations to make provision for the flesh, to fulfil the lusts thereof, it instantly apprehends sin, and brings it to the law of God and love of Christ, condemns it, follows it with execution to the uttermost.

Now, I say, when a man comes to this state and condition, that lust is weakened in the root and principle, that its motions and actions are fewer and weaker than formerly, so that they are not able to hinder his duty nor interrupt his peace, — when he can, in a quiet, sedate frame of spirit, find out and fight against sin, and have success against it, — then sin is mortified in some considerable measure, and, notwithstanding all its opposition, a man may have peace with God all his days.

Unto these heads, then, do I refer the mortification aimed at; that is, of any one perplexing distemper, whereby the general pravity and corruption of our nature attempts to exert and put forth itself:—

First, The #emph[weakening] of its indwelling disposition, whereby it inclines, entices, impels to evil, rebels, opposes, fights against God, by the implanting, habitual residence, and cherishing of a principle of grace that stands in direct opposition to it and is destructive of it, is the foundation of it. So, by the implanting and growth of humility is pride weakened, passion by patience, uncleanness by purity of mind and conscience, love of this world by heavenly-mindedness: which are graces of the Spirit, or the same habitual grace variously acting itself by the Holy Ghost, according to the variety or diversity of the objects about which it is exercised; as the other are several lusts, or the same natural corruption variously acting itself, according to the various advantages and occasions that it meets withal. — The #emph[promptness, alacrity, vigour] of the Spirit, or new man, in contending with, cheerful fighting against, the lust spoken of, by all the ways and with all the means that are appointed thereunto, constantly using the succours provided against its motions and actings, is a second thing hereunto required. — Success unto #emph[several degrees] attends these two. Now this, if the distemper hath not an unconquerable advantage from its natural situation, may possibly be to such a #emph[universal] conquest as the soul may never more sensibly feel its opposition, and shall, however, assuredly arise to an allowance of peace to the conscience, according to the tenor of the covenant of grace.
