== Chapter VIII

#block(inset: (x: 1em))[The second general rule proposed — Without universal sincerity for the mortifying of every lust, no lust will be mortified — Partial mortification always from a corrupt principle — Perplexity of temptation from a lust oftentimes a chastening for other negligences.]

2\. The second principle which to this purpose I shall propose is this:—

#emph[Without sincerity and diligence in a universality of obedience, there is no mortification of any one perplexing lust to be obtained.]

The other was to the person; this to the thing itself. I shall a little explain this position.

A man finds any lust to bring him into the condition formerly described; it is powerful, strong, tumultuating, leads captive, vexes, disquiets, takes away peace; he is not able to bear it; wherefore he sets himself against it, prays against it, groans under it, sighs to be delivered: but in the meantime, perhaps, in other duties, — in constant communion with God, — in reading, prayer, and meditation, — in other ways that are not of the same kind with the lust wherewith he is troubled, — he is loose and negligent. Let not that man think that ever he shall arrive to the mortification of the lust he is perplexed withal. This is a condition that not seldom befalls men in their pilgrimage. The Israelites, under a sense of their sin, drew nigh to God with much diligence and earnestness, with fasting and prayer, Isa. lviii.: many expressions are made of their earnestness in the work, verse 2 “They seek me daily, and delight to know my ways; they ask of me the ordinances of justice; they take delight in approaching to God.” But God rejects all. Their fast is a remedy that will not heal them, and the reason given of it, verses 5–7, is, because they were particular in this duty. They attended diligently to that, but in others were negligent and careless. He that hath a “running sore” (it is the Scripture expression) upon him, arising from an ill habit of body, contracted by intemperance and ill diet, let him apply himself with what diligence and skill he can to #emph[the cure of his sore], if he leave #emph[the general habit of his body] under distempers, his labour and travail will be in vain. So will his attempts be that shall endeavour to stop a bloody issue of sin and filth in his soul, and is not equally careful of his universal spiritual temperature and constitution. For, —

(1.) This kind of endeavour for mortification proceeds from a #emph[corrupt principle], ground, and foundation; so that it will never proceed to a good issue. The true and acceptable principles of mortification shall be afterward insisted on. Hatred of sin as sin, not only as galling or disquieting, a sense of the love of Christ in the cross, lie at the bottom of all true spiritual mortification. Now, it is certain that that which I speak of proceeds from #emph[self-love]. Thou settest thyself with all diligence and earnestness to mortify such a lust or sin; what is the reason of it? It disquiets thee, it hath taken away thy peace, it fills thy heart with sorrow, and trouble, and fear; thou hast no rest because of it. Yea; but, friend, thou hast neglected prayer or reading; thou hast been vain and loose in thy conversation in other things, that have not been of the same nature with that lust wherewith thou art perplexed. These are no less sins and evils than those under which thou groanest. Jesus Christ bled for them also. Why dost thou not set thyself against them also? If thou hatest sin as sin, every evil way, thou wouldst be no less watchful against every thing that grieves and disquiets the Spirit of God, than against that which grieves and disquiets thine own soul. It is evident that thou contendest against #emph[sin] merely because of thy own #emph[trouble] by it. Would thy conscience be quiet under it, thou wouldst let it alone. Did it not disquiet thee, it should not be disquieted by thee. Now, canst thou think that God will set in with such hypocritical endeavours, — that ever his Spirit will bear witness to the treachery and falsehood of thy spirit? Dost thou think he will ease thee of that which perplexeth thee, that thou mayst be at liberty to that which no less grieves him? No. Says God, “Here is one, if he could be rid of this lust I should never hear of him more; let him wrestle with this, or he is lost.” Let not any man think to do his own work that will not do God’s. God’s work consists in #emph[universal obedience]\; to be freed of the present perplexity is their own only. Hence is that of the apostle, 2 Cor. vii. 1, “Cleanse yourselves from all pollution of the flesh and spirit, perfecting holiness in the fear of God.” If we will do any thing, we must do all things. So, then, it is not only an intense opposition to this or that peculiar lust, but a universal humble frame and temper of heart, with watchfulness over every evil and for the performance of every duty, that is accepted.

(2.) How knowest thou but that God hath suffered the lust wherewith thou hast been perplexed to get strength in thee, and power over thee, to chasten thee for thy other negligences and common lukewarmness in walking before him; at least to awaken thee to the consideration of thy ways, that thou mayst make a thorough work and change in thy course of walking with him?

The rage and predominancy of a particular lust is commonly the fruit and issue of a careless, negligent course in general, and that upon a double account:—

\[1.\] As its #emph[natural effect], if I may so say. Lust, as I showed in general, lies in the heart of every one, even the best, whilst he lives; and think not that the Scripture speaks in vain, that it is subtle, cunning, crafty, — that it seduces, entices, fights, rebels. Whilst a man keeps a diligent watch over his heart, its root and fountain, — whilst above all keepings he keeps his heart, whence are the issues of life and death, — lust withers and dies in it. But if, through negligence, it makes an eruption any particular way, gets a passage to the thoughts by the affections, and from them and by them perhaps breaks out into open sin in the conversation, the strength of it bears that way it hath found out, and that way mainly it urgeth, until, having got a passage, it then vexes and disquiets, and is not easily to be restrained: thus, perhaps, a man may be put to wrestle all his days in sorrow with that which, by a strict and universal watch, might easily have been prevented.

\[2.\] As I said, God oftentimes suffers it to #emph[chasten] our other negligences: for as with wicked men, he gives them up to #emph[one] sin as the judgment of another, #emph[a greater for the punishment of a less], or one that will hold them more firmly and securely for that which they might have possibly obtained a deliverance from;#footnote[Rom. i. 26.] so even with his own, he may, he doth, leave them sometimes to some vexatious distempers, either to prevent or cure some other evil. So was the messenger of Satan let loose on Paul, that he “might not be lifted up through the abundance of spiritual revelations.”#footnote[2 Cor. xii. 7.] Was it not a correction to Peter’s vain confidence, that he was left to deny his Master? Now, if this be the state and condition of lust in its prevalency, that God oftentimes suffers it so to prevail, at least to admonish us, and to humble us, perhaps to chasten and correct us for our general loose and careless walking, is it possible that the #emph[effect] should be removed and the #emph[cause] continued, — that the #emph[particular] lust should be mortified and the #emph[general] course be unreformed? He, then, that would really, thoroughly, and acceptably mortify any disquieting lust, let him take care to be equally diligent in all parts of obedience, and know that every lust, every omission of duty, is burdensome to God, though but one is so to him.#footnote[Isa. xliii. 24.] Whilst there abides a treachery in the heart to indulge to any negligence in not pressing universally to all perfection in obedience, the soul is #emph[weak], as not giving faith its whole work; and #emph[selfish], as considering more the trouble of sin than the filth and guilt of it; and lives under a constant #emph[provocation] of God: so that it may not expect any comfortable issue in any spiritual duty that it doth undertake, much less in this under consideration, which requires another principle and frame of spirit for its accomplishment.
