== Chapter V

#block(inset: (x: 1em))[The principal intendment of the whole discourse proposed — The first main case of conscience stated — What it is to mortify any sin, negatively considered — Not the utter destruction of it in this life — Not the dissimulation of it —Not the improvement of any natural principle — Not the diversion of it — Not an occasional conquest — Occasional conquests of sin, what and when; upon the eruption of sin; in time of danger or trouble.]

These things being premised, I come to my principal intention, of handling some questions or practical cases that present themselves in this business of mortification of sin in believers.

The first, which is the head of all the rest, and whereunto they are reduced, may be considered as lying under the ensuing proposal:—

Suppose a man to be a true believer, and yet finds in himself a powerful indwelling sin, leading him captive to the law of it, consuming his heart with trouble, perplexing his thoughts, weakening his soul as to duties of communion with God, disquieting him as to peace, and perhaps defiling his conscience, and exposing him to hardening through the deceitfulness of sin, — what shall he do? what course shall he take and insist on for the mortification of this sin, lust, distemper, or corruption, to such a degree as that, though it be not utterly destroyed, yet, in his contest with it, he may be enabled to keep up power, strength, and peace in communion with God?

In answer to this important inquiry, I shall do these things:—

I. Show what it is to mortify any sin, and that both negatively and positively, that we be not mistaken in the foundation.

II. Give general directions for such things as without which it will be utterly impossible for any one to get any sin truly and spiritually mortified.

III. Draw out the particulars whereby this is to be done; in the whole carrying on this consideration, that it is not of the doctrine of mortification in general, but only in reference to the particular case before proposed, that I am treating.

I. 1. (1.) To mortify a sin is not utterly to #emph[kill], root it out, and destroy it, that it should have no more hold at all nor residence in our hearts. It is true this is that which is aimed at; but this is not in this life to be accomplished. There is no man that truly sets himself to mortify any sin, but he aims at, intends, desires its utter destruction, that it should leave neither root nor fruit in the heart or life. He would so kill it that it should never move nor stir any more, cry or call, seduce or tempt, to eternity. Its #emph[not-being] is the thing aimed at. Now, though doubtless there may, by the Spirit and grace of Christ, a wonderful success and eminency of victory against any sin be attained, so that a man may have almost constant triumph over it, yet an utter killing and destruction of it, that it should not be, is not in this life to be expected. This Paul assures us of, Phil. iii. 12, “Not as though I had already attained, either were already perfect.” He was a #emph[choice saint], a pattern for believers, who, in faith and love, and all the fruits of the Spirit, had not his fellow in the world, and on that account ascribes perfection to himself in comparison of others, verse 15; yet he had not “attained,” he was not “perfect,” but was “following after:” still a vile body he had, and we have, that must be changed by the great power of Christ at last, verse 21. This we would have; but God sees it best for us that we should be complete in nothing in ourselves, that in all things we must be “complete in Christ;” which is best for us, Col. ii. 10.

(2.) I think I need not say it is not the #emph[dissimulation] of a sin. When a man on some outward respects forsakes the practice of any sin, men perhaps may look on him as a changed man. God knows that to his former iniquity he hath added cursed hypocrisy, and is got in a safer path to hell than he was in before. He hath got another heart than he had, that is more cunning; not a new heart, that is more holy.

(3.) The mortification of sin consists not in the improvement of a #emph[quiet, sedate] nature. Some men have an advantage by their natural constitution so far as that they are not exposed to such violence of unruly passions and tumultuous affections as many others are. Let now these men cultivate and improve their natural frame and temper by discipline, consideration, and prudence, and they may seem to themselves and others very mortified men, when, perhaps, their hearts are a standing sink of all abominations. Some man is never so much troubled all his life, perhaps, with anger and passion, nor doth trouble others, as another is almost every day; and yet the latter hath done more to the mortification of the sin than the former. Let not such persons try their mortification by such things as their natural temper gives no life or vigour to. Let them bring themselves to self-denial, unbelief, envy, or some such spiritual sin, and they will have a better view of themselves.

(4.) A sin is not mortified when it is only diverted. Simon Magus for a season left his #emph[sorceries]\; but his #emph[covetousness and ambition], that set him on work, remained still, and would have been acting another way. Therefore Peter tells him, “I perceive thou art in the gall of bitterness;” — “Notwithstanding the profession thou hast made, notwithstanding thy relinquishment of thy sorceries, thy lust is as powerful as ever in thee; the same lust, only the streams of it are diverted. It now exerts and puts forth itself another way, but it is the old gall of bitterness still.” A man may be sensible of a lust, set himself against the eruptions of it, take care that it shall not break forth as it has done, but in the meantime suffer the same corrupted habit to vent itself some other way; as he who heals and skins a running sore thinks himself cured, but in the meantime his flesh festereth by the corruption of the same humour, and breaks out in another place. And this diversion, with the alterations that attend it, often befalls men on accounts wholly foreign unto grace: change of the course of life that a man was in, of relations, interests, designs, may effect it; yea, the very alterations in men’s constitutions, occasioned by a natural progress in the course of their lives, may produce such changes as these. Men in age do not usually persist in the pursuit of youthful lusts, although they have never mortified any one of them. And the same is the case of bartering of lusts, and leaving to serve one that a man may serve another. He that changes pride for worldliness, sensuality for Pharisaism, vanity in himself to the contempt of others, let him not think that he hath mortified the sin that he seems to have left. He hath changed his master, but is a servant still.

(5.) #emph[Occasional conquests] of sin do not amount to a mortifying of it.

There are two occasions or seasons wherein a man who is contending with any sin may seem to himself to have mortified it:—

\[1.\] When it hath had some sad #emph[eruption], to the disturbance of his peace, terror of his conscience, dread of scandal, and evident provocation of God. This awakens and stirs up all that is in the man, and amazes him, fills him with abhorrency of sin, and himself for it; sends him to God, makes him cry out as for life, to abhor his lust as hell, and to set himself against it. The whole man, spiritual and natural, being now awaked, sin shrinks in its head, appears not, but lies as dead before him: as when one that hath drawn nigh to an army in the night, and hath killed a principal person, — instantly the guards awake, men are roused up, and strict inquiry is made after the enemy, who, in the meantime, until the noise and tumult be over, hides himself, or lies like one that is dead, yet with firm resolution to do the like mischief again upon the like opportunity. Upon the sin among the Corinthians, see how they muster up themselves for the surprisal and destruction of it, 2 Epist. chap. vii. 11. So it is in a person when a breach hath been made upon his conscience, quiet, perhaps credit, by his lust, in some eruption of actual sin; — carefulness, indignation, desire, fear, revenge, are all set on work about it and against it, and lust is quiet for a season, being run down before them; but when the hurry is over and the inquest past, the thief appears again alive, and is as busy as ever at his work.

\[2.\] In a time of some #emph[judgment], calamity, or pressing affliction; the heart is then taken up with thoughts and contrivances of flying from the present troubles, fears, and dangers. This, as a convinced person concludes, is to be done only by relinquishment of sin, which gains peace with God. It is the anger of God in every affliction that galls a convinced person. To be quit of this, men resolve at such times against their sins. Sin shall never more have any place in them; they will never again give up themselves to the service of it. Accordingly, sin is quiet, stirs not, seems to be mortified; not, indeed, that it hath received any one wound, but merely because the soul hath possessed its faculties, whereby it should exert itself, with thoughts inconsistent with the motions thereof; which, when they are laid aside, sin returns again to its former life and vigour. So they Ps. lxxviii. 32–37, are a full instance and description of this frame of spirit whereof I speak: “For all this they sinned still, and believed not for his wondrous works. Therefore their days did he consume in vanity, and their years in trouble. When he slew them, then they sought him: and they returned and inquired early after God. And they remembered that God was their rock, and the high God their redeemer. Nevertheless they did flatter him with their mouth, and they lied unto him with their tongues. For their heart was not right with him, neither were they steadfast in his covenant.” I no way doubt but that when they sought, and returned, and inquired early after God, they did it with full purpose of heart as to the relinquishment of their sins; it is expressed in the word “returned.” To turn or return to the Lord is by a relinquishment of sin. This they did “early,” — with earnestness and diligence; but yet their sin was unmortified for all this, verses 36, 37. And this is the state of many humiliations in the days of affliction, and a great deceit in the hearts of believers themselves lies oftentimes herein.

These and many other ways there are whereby poor souls deceive themselves, and suppose they have mortified their lusts, when they live and are mighty, and on every occasion break forth, to their disturbance and disquietness.
