== Chapter XII

#block(inset: (x: 1em))[The eighth direction: Thoughtfulness of the excellency of the majesty of God — Our unacquaintedness with him proposed and considered.]

Eighthly, Use and exercise thyself to such meditations as may serve to fill thee at all times with #emph[self-abasement] and thoughts of thine own vileness; as, —

1\. Be much in thoughtfulness of the #emph[excellency] of the majesty of God and thine infinite, inconceivable distance from him. Many thoughts of it cannot but fill thee with a sense of thine own vileness, which strikes deep at the root of any indwelling sin. When Job comes to a clear discovery of the greatness and the excellency of God, he is filled with self-abhorrence and is pressed to humiliation, Job xlii. 5, 6. And in what state doth the prophet Habakkuk affirm himself to be cast, upon the apprehension of the majesty of God? chap. iii. 16. “With God,” says Job, “is terrible majesty.”#footnote[Job xxxvii. 22.] Hence were the thoughts of them of old, that when they had seen God they should die. The Scripture abounds in this self-abasing consideration, comparing the men of the earth to “grasshoppers,” to “vanity,” the “dust of the balance,” in respect of God.#footnote[Isa. xl. 12–25.] Be much in thoughts of this nature, to abase the pride of thy heart, and to keep thy soul humble within thee. There is nothing will render thee a greater indisposition to be imposed on by the deceits of sin than such a frame of heart. Think greatly of the greatness of God.

2\. Think much of thine #emph[unacquaintedness] with him. Though thou knowest enough to keep thee low and humble, yet how little a portion is it that thou knowest of him! The contemplation hereof cast that wise man into that apprehension of himself which he expresses, Prov. xxx. 2–4, “Surely I am more brutish than any man, and have not the understanding of a man. I neither learned wisdom, nor have the knowledge of the holy. Who hath ascended up into heaven, or descended? who hath gathered the wind in his fists? who hath bound the waters in a garment? who hath established the ends of the earth? what is his name, and what is his Son’s name, if thou canst tell?” Labour with this also to take down the pride of thy heart. What dost thou know of God? How little a portion is it! How immense is he in his nature! Canst thou look without terror into the abyss of eternity? Thou canst not bear the rays of his glorious being.

Because I look on this consideration of great use in our walking with God, so far as it may have a consistency with that filial boldness which is given us in Jesus Christ to draw nigh to the throne of grace, I shall farther insist upon it, to give an abiding impression of it to the souls of them who desire to walk humbly with God.

Consider, then, I say, to keep thy heart in continual awe of the majesty of God, that persons of the most high and eminent attainment, of the nearest and most familiar communion with God, do yet in this life know but a very little of him and his glory. God reveals his name to Moses, — the most glorious attributes that he hath manifested in the covenant of grace, Exod. xxxiv. 5, 6; yet all are but the “back parts” of God. All that he knows by it is but little, low, compared to the perfections of his glory. Hence it is with peculiar reference to Moses that it is said, “No man hath seen God at any time,” John i. 18; of him in comparison with Christ doth he speak, verse 17; and of him it is here said, “No man,” no, not Moses, the most eminent among them, “hath seen God at any time.” We speak much of God, can talk of him, his ways, his works, his counsels, all the day long; the truth is, we know very little of him. Our thoughts, our meditations, our expressions of him are low, many of them unworthy of his glory, none of them reaching his perfections.

You will say that Moses was under the law when God wrapped up himself in darkness, and his mind in types and clouds and dark institutions; — under the glorious shining of the gospel, which hath brought life and immortality to light, God being revealed from his own bosom, we now know him much more clearly, and as he is; we see his #emph[face] now, and not his #emph[back parts] only, as Moses did.

#emph[Ans.] 1. I acknowledge a vast and almost inconceivable difference between the acquaintance we now have with God, after his speaking to us by his own Son,#footnote[Heb. i. 2.] and that which the generality of the saints had under the law; for although their eyes were as good, sharp, and clear as ours, their faith and spiritual understanding not behind ours, the object as glorious unto them as unto us, yet our day is more clear than theirs was, the clouds are blown away and scattered,#footnote[Cant. iv. 6.] the shadows of the night are gone and fled away, the sun is risen, and the means of sight is made more eminent and clear than formerly. Yet, —

2\. That peculiar sight which Moses had of God, Exod. xxxiv., was a #emph[gospel-sight], a sight of God as “gracious,” etc., and yet it is called but his “back parts;” that is, but low and mean, in comparison of his excellencies and perfections.

3\. The apostle, exalting to the utmost this glory of light above that of the law, manifesting that now the “vail” causing darkness is taken away, so that with “open” or uncovered “face#footnote[Ἀνακεκαλυμμένῳ προσώπῳ.] we behold the glory of the Lord,” tells us how: “As in a glass,” 2 Cor. iii. 18. “In a glass,” how is that? Clearly, perfectly? Alas, no! He tells you how that is, 1 Cor. xiii. 12, “We see through a glass, darkly,” saith he. It is not a telescope that helps us to see things afar off, concerning which the apostle speaks; and yet what poor helps are they! how short do we come of the truth of things notwithstanding their assistance! It is a looking-glass whereunto he alludes (where are only obscure species and images of things, and not the things themselves), and a sight therein that he compares our knowledge to. He tells you also that all that we do see, δι’ ἐσόπτρου, “by” or “through this glass,” is in αἰνίγματι, — in “a riddle,” in darkness and obscurity. And speaking of himself, who surely was much more clear-sighted than any now living, he tells us that he saw but ἐκ μέρους, — “in part.” He saw but the back parts of heavenly things, verse 12, and compares all the knowledge he had attained of God to that he had of things when he was a child, verse 11. It is a μέρος, short of the τὸ τέλειον· yea, such as καταργηθήσεται, — “it shall be destroyed,” or done away. We know what weak, feeble, uncertain notions and apprehensions children have of things of any abstruse consideration; how when they grow up with any improvements of parts and abilities, those conceptions vanish, and they are ashamed of them. It is the commendation of a child to love, honour, believe, and obey his father; but for his science and notions, his father knows his childishness and folly. Notwithstanding all our confidence of high attainments, all our notions of God are but childish in respect of his infinite perfections. We lisp and babble, and say we know not what, for the most part, in our most accurate, as we think, conceptions and notions of God. We may love, honour, believe, and obey our Father; and therewith he accepts our childish thoughts, for they are but childish. We see but his back parts; we know but little of him. Hence is that promise wherewith we are so often supported and comforted in our distress, “We shall see him as he is;” we shall see him “face to face;” “know as we are known; comprehend that for which we are comprehended,” 1 Cor. xiii. 12, 1 John iii. 2; and positively, “Now we see him not;” — all concluding that here we see but his back parts; not as he is, but in a dark, obscure representation; not in the perfection of his glory.

The queen of Sheba had heard much of Solomon, and framed many great thoughts of his magnificence in her mind thereupon; but when she came and saw his glory, she was forced to confess that the one half of the truth had not been told her. We may suppose that we have here attained great knowledge, clear and high thoughts of God; but, alas! when he shall bring us into his presence we shall cry out, “We never knew him as he is; the thousandth part of his glory, and perfection, and blessedness, never entered into our hearts.”

The apostle tells us, 1 John iii. 2, that we know not what we ourselves shall be, — what we shall find ourselves in the issue; much less will it enter into our hearts to conceive what God is, and what we shall find him to be. Consider either him who is to be known, or the way whereby we know him, and this will farther appear:—

(1.) We know so little of #emph[God], because it is #emph[God] who is thus to be known, — that is, he who hath described himself to us very much by this, that we #emph[cannot] know him. What else doth he intend where he calls himself invisible, incomprehensible, and the like? — that is, he whom we do not, cannot, know as he is. And our farther progress consists more in knowing what he is not, than what he is. Thus is he described to be immortal, infinite, — that is, he is not, as we are, mortal, finite, and limited. Hence is that glorious description of him, 1 Tim. vi. 16, “Who only hath immortality, dwelling in the light which no man can approach unto; whom no man hath seen, nor can see.” His light is such as no creature can approach unto. He is not seen, not because he cannot be seen, but because we cannot bear the sight of him. The light of God, in whom is no darkness, forbids all access to him by any creature whatever. We who cannot behold the sun in its glory are too weak to bear the beams of infinite brightness. On this consideration, as was said, the wise man professeth himself “a very beast, and not to have the understanding of a man,” Prov. xxx. 2; — that is, he knew nothing in comparison of God; so that he seemed to have lost all his understanding when once he came to the consideration of him, his work, and his ways.

In this consideration let our souls descend to some particulars:—

\[1.\] For the #emph[being] of God; we are so far from a knowledge of it, so as to be able to instruct one another therein by words and expressions of it, as that to frame any conceptions in our mind, with such species and impressions of things as we receive the knowledge of all other things by, is to make an idol to ourselves, and so to worship a god of our own making, and not the God that made us. We may as well and as lawfully hew him out of wood or stone as form him a being in our minds, suited to our apprehensions. The utmost of the best of our thoughts of the being of God is, that we can have no thoughts of it. Our knowledge of a being is but low when it mounts no higher but only to know that we know it not.

\[2.\] There be #emph[some] things of God which he himself hath taught us to speak of, and to regulate our expressions of them; but when we have so done, we see not the things themselves; we know them not. To #emph[believe] and #emph[admire] is all that we attain to. We profess, as we are taught, that God is infinite, omnipotent, eternal; and we know what disputes and notions there are about omnipresence, immensity, infiniteness, and eternity. We have, I say, words and notions about these things; but as to the things themselves what do we know? what do we comprehend of them? Can the mind of man do any more but swallow itself up in an infinite abyss, which is as nothing; give itself up to what it cannot conceive, much less express? Is not our understanding “brutish” in the contemplation of such things, and is as if it were not? Yea, the perfection of our understanding is, not to understand, and to rest there. They are but the back parts of eternity and infiniteness that we have a glimpse of. What shall I say of the Trinity, or the subsistence of distinct persons in the same individual essence, — a mystery by many denied, because by none understood, — a mystery, whose every letter is mysterious? Who can declare the generation of the Son, the procession of the Spirit, or the difference of the one from the other? But I shall not farther instance in particulars. That infinite and inconceivable distance that is between him and us keeps us in the dark as to any sight of his face or clear apprehension of his perfections.

We know him rather by what he does than by what he is, — by his doing us good than by his essential goodness; and how little a portion of him, as Job speaks, is hereby discovered!

(2.) We know little of God, because it is #emph[faith] alone whereby here we know him. I shall not now discourse about the remaining impressions on the hearts of all men by nature that there is a God, nor what they may rationally be taught concerning that God from the works of his creation and providence, which they see and behold. It is confessedly, and that upon the woful experience of all ages, so weak, low, dark, confused, that none ever on that account glorified God as they ought, but, notwithstanding all their knowledge of God, were indeed “without God in the world.”

The chief, and, upon the matter, almost only acquaintance we have with God, and his dispensations of himself, is by faith. “He that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him,” Heb. xi. 6. Our knowledge of him and his rewarding (the bottom of our obedience or coming to him), is believing. “We walk by faith, and not by sight,” 2 Cor. v. 7; — Διὰ πίστεως οὐ διὰ εἴδους· by faith, and so by faith as not to have any express idea, image, or species of that which we believe. Faith is all the argument we have of “things not seen,” Heb. xi. 1. I might here insist upon the nature of it; and from all its concomitants and concernments manifest that we know but the back parts of what we know by faith only. As to its rise, it is built purely upon the testimony of Him whom we have not seen: as the apostle speaks, “How can ye love him whom ye have not seen?” — that is, whom you know not but by faith that he is. Faith receives all upon #emph[his] testimony, whom it receives to be only on his own testimony. As to its nature, it is an assent upon testimony, not an evidence upon demonstration; and the object of it is, as was said before, above us. Hence our faith, as was formerly observed, is called a “seeing darkly, as in a glass.” All that we know this way (and all that we know of God we know this way) is but low, and dark, and obscure.

But you will say, “All this is true, but yet it is only so to them that know not God, perhaps, as he is revealed in Jesus Christ; with them who do so it is otherwise. It is true, ‘No man hath seen God at any time,’ but ‘the only-begotten Son, he hath revealed him,’ John i. 18; and ‘the Son of God is come, and hath given us an understanding, that we may know him that is true,’ 1 John v. 20. The illumination of ‘the glorious gospel of Christ, who is the image of God,’ shineth upon believers, 2 Cor. iv. 4; yea, and ‘God, who commanded the light to shine out of darkness, shines into their hearts, to give them the knowledge of his glory in the face of his Son,’ verse 6. So that ‘though we were darkness,’ yet we are now ‘light in the Lord,’ Eph. v. 8. And the apostle says, ‘We all with open face behold the glory of the Lord,’ 2 Cor. iii. 18; and we are now so far from being in such darkness, or at such a distance from God, that ‘our communion and fellowship is with the Father and with his Son,’ 1 John i. 3. The light of the gospel whereby now God is revealed is glorious; not a star, but the sun in his beauty is risen upon us, and the vail is taken from our faces. So that though unbelievers, yea, and perhaps some weak believers, may be in some darkness, yet those of any growth or considerable attainments have a clear sight and view of the face of God in Jesus Christ.”

To which I answer, —

\[1.\] The truth is, we all of us know #emph[enough] of him to love him more than we do, to delight in him and serve him, believe him, obey him, put our trust in him, above all that we have hitherto attained. Our darkness and weakness is no plea for our negligence and disobedience. Who is it that hath walked up to the knowledge that he hath had of the perfections, excellencies, and will of God? God’s end in giving us any knowledge of himself here is that we may “glorify him as God;” that is, love him, serve him, believe and obey him, — give him all the honour and glory that is due from poor sinful creatures to a sin-pardoning God and Creator. We must all acknowledge that we were never thoroughly transformed into the image of that knowledge which we have had. And had we used our talents well, we might have been trusted with more.

\[2.\] #emph[Comparatively], that knowledge which we have of God by the revelation of Jesus Christ in the gospel is exceeding eminent and glorious. It is so in comparison of any knowledge of God that might otherwise be attained, or was delivered in the law under the Old Testament, which had but the shadow of good things, not the express image of them; this the apostle pursues at large, 2 Cor. iii. Christ hath now in these last days revealed the Father from his own bosom, declared his name, made known his mind, will, and counsel in a far more clear, eminent, distinct manner than he did formerly, whilst he kept his people under the pedagogy of the law; and this is that which, for the most part, is intended in the places before mentioned. The clear, perspicuous delivery and declaration of God and his will in the gospel is expressly exalted in comparison of any other way of revelation of himself.

\[3.\] The difference between believers and unbelievers as to knowledge is not so much in the #emph[matter of their knowledge] as in #emph[the manner of knowing]. Unbelievers, some of them, may know more and be able to say more of God, his perfections, and his will, than many believers; but they know nothing as they ought, nothing in a right manner, nothing spiritually and savingly, nothing with a holy, heavenly light. The excellency of a believer is, not that he hath a large apprehension of things, but that what he doth apprehend, which perhaps may be very little, he sees it in the light of the Spirit of God, in a saving, soul-transforming light; and this is that which gives us communion with God, and not prying thoughts or curious-raised notions.

\[4.\] Jesus Christ by his word and Spirit reveals to the hearts of all his, God as a Father, as a God in covenant, as a rewarder, every way sufficiently to teach us to obey him here, and to lead us to his bosom, to lie down there in the fruition of him to eternity. But yet now,

\[5.\] Notwithstanding all this, it is but a #emph[little portion] we know of him; we see but his back parts. For, —

1#emph[st]. The intendment of all gospel revelation is, not to #emph[unvail God’s essential glory], that we should see him as he is, but merely to declare so much of him as he knows sufficient to be a bottom of our faith, love, obedience, and coming to him, — that is, of the faith which here he expects from us; such services as beseem poor creatures in the midst of temptations. But when he calls us to eternal admiration and contemplation, without interruption, he will make a new manner of discovery of himself, and the whole shape of things, as it now lies before us, will depart as a shadow.

2#emph[dly]. We are dull and slow of heart to receive the things that are in the word revealed; God, by our infirmity and weakness, keeping us in continual dependence on him for teachings and revelations of himself out of his word, never in this world bringing any soul to the utmost of what is from the word to be made out and discovered: so that although the way of revelation in the gospel be clear and evident, yet we know little of the things themselves that are revealed.

Let us, then, revive the use and intendment of this consideration: Will not a due apprehension of this inconceivable greatness of God, and that infinite distance wherein we stand from him, fill the soul with a holy and awful fear of him, so as to keep it in a frame unsuited to the thriving or flourishing of any lust whatever? Let the soul be continually wonted to reverential thoughts of God’s greatness and omnipresence, and it will be much upon its watch as to any undue deportments. Consider him with whom you have to do, — even “our God is a consuming fire;” and in your greatest abashments at his presence and eye, know that your very nature is too narrow to bear apprehensions suitable to his essential glory.
