== Chapter I

#block(inset: (x: 1em))[The foundation of the whole ensuing discourse laid in Rom. viii. 13 — The words of the apostle opened — The certain connection between true mortification and salvation — Mortification the work of believers — The Spirit the principal efficient cause of it — What meant by “the body” in the words of the apostle — What by “the deeds of the body” — Life, in what sense promised to this duty.]

That what I have of direction to contribute to the carrying on of the work of mortification in believers may receive order and perspicuity, I shall lay the foundation of it in those words of the apostle, Rom. viii. 13, “If ye through the Spirit do mortify the deeds of the body ye shall live;” and reduce the whole to an improvement of the great evangelical truth and mystery contained in them.

The apostle having made a recapitulation of his doctrine of justification by faith, and the blessed estate and condition of them who are made by grace partakers thereof, verses 1–3 of this chapter, proceeds to improve it to the holiness and consolation of believers.

Among his arguments and motives unto holiness, the verse mentioned containeth one from the contrary events and effects of holiness and sin: “If ye live after the flesh, ye shall die.” What it is to “live after the flesh,” and what it is to “die,” that being not my present aim and business, I shall no otherwise explain than as they will fall in with the sense of the latter words of the verse, as before proposed.

In the words peculiarly designed for the foundation of the ensuing discourse, there is, —

First, A #emph[duty] prescribed: “Mortify the deeds of the body.”

Secondly, The persons are denoted to #emph[whom] it is prescribed: “Ye,” — “if ye mortify.”

Thirdly, There is in them a #emph[promise] annexed to that duty: “Ye shall live.”

Fourthly, The #emph[cause] or means of the performance of this duty, — the Spirit: “If ye through the Spirit.”

Fifthly, The #emph[conditionality] of the whole proposition, wherein duty, means, and promise are contained: “If ye,” etc.

1\. The first thing occurring in the words as they lie in the entire proposition is the conditional note, Εἰ δὲ, “But if.” Conditionals in such propositions may denote two things:—

(1.) The #emph[uncertainty] of the #emph[event] or thing promised, in respect of them to whom the duty is prescribed. And this takes place where the condition is absolutely necessary unto the issue, and depends not itself on any determinate cause known to him to whom it is prescribed. So we say, “If we live, we will do such a thing.” This cannot be the intendment of the conditional expression in this place. Of the persons to whom these words are spoken, it is said, verse 1 of the same chapter, “There is no condemnation to them.”

(2.) The #emph[certainty] of the #emph[coherence] and connection that is between the things spoken of; as we say to a sick man, “If you will take such a potion, or use such a remedy, you will be well.” The thing we solely intend to express is the certainty of the connection that is between the potion or remedy and health. And this is the use of it here. The certain connection that is between the #emph[mortifying] of the deeds of the body and #emph[living] is intimated in this conditional particle.

Now, the connection and coherence of things being manifold, as of cause and effect, of way and means and the end, this between mortification and life is not of cause and effect properly and strictly, — for “eternal life is the gift of God through Jesus Christ,” Rom. vi. 23, — but of means and end. God hath appointed this means for the attaining that end, which he hath freely promised. Means, though necessary, have a fair subordination to an end of free promise. A gift, and procuring cause in him to whom it is given, are inconsistent. The intendment, then, of this proposition as conditional is, that there is a certain infallible connection and coherence between true mortification and eternal life: if you use this means, you shall obtain that end; if you do mortify, you shall live. And herein lies the main motive unto and enforcement of the duty prescribed.

2\. The next thing we meet withal in the words is the #emph[persons] to whom this duty is prescribed, and that is expressed in the word “Ye,” in the original included in the verb, θανατοῦτε “if ye mortify;” — that is, ye believers; ye to whom “there is no condemnation,” verse 1; ye that are “not in the flesh, but in the Spirit,” verse 9; who are “quickened by the Spirit of Christ,” verses 10, 11; to you is this duty prescribed. The pressing of this duty immediately on any other is a notable fruit of that superstition and self-righteousness that the world is full of, — the great work and design of devout men ignorant of the gospel, Rom. x. 3, 4; John xv. 5. Now, this description of the persons, in conjunction with the prescription of the duty, is the main foundation of the ensuing discourse, as it lies in this thesis or proposition:—

#emph[The choicest believers, who are assuredly freed from the condemning power of sin, ought yet to make it their business all their days to mortify the indwelling power of sin.]

3\. The principal #emph[efficient cause] of the performance of this duty is the Spirit: Εἰ δὲ Πνεύματι, — “If by the Spirit.” The Spirit here is the Spirit mentioned verse 11, the Spirit of Christ, the Spirit of God, that “dwells in us,” verse 9, that “quickens us,” verse 11; “the Holy Ghost,” verse 14;#footnote[There seems to be an oversight here, as the expression “Holy Ghost” does not occur in the verse cited. — Ed.] the “Spirit of adoption,” verse 15; the Spirit “that maketh intercession for us,” verse 26. All other ways of mortification are vain, all helps leave us helpless; it must be done by the Spirit. Men, as the apostle intimates, Rom. ix. 30–32, may attempt this work on other principles, by means and advantages administered on other accounts, as they always have done, and do: but, saith he, “This is the work of the Spirit; by him alone is it to be wrought, and by no other power is it to be brought about.” Mortification from a self-strength, carried on by ways of self-invention, unto the end of a self-righteousness, is the soul and substance of all false religion in the world. And this is a second principle of my ensuing discourse.

4\. The #emph[duty] itself, “Mortify the deeds of the body,” is nextly to be remarked.

Three things are here to be inquired into:— (1.) What is meant by #emph[the body]\; (2.) What by #emph[the deeds of the body]\; (3.) What by #emph[mortifying] of them.

(1.) #emph[The body] in the close of the verse is the same with #emph[the flesh] in the beginning: “If ye live after the flesh ye shall die; but if ye … mortify the deeds of the body,” — that is, of the flesh. It is that which the apostle hath all along discoursed of under the name of #emph[the flesh]\; which is evident from the prosecution of the antithesis between the Spirit and the flesh, before and after. #emph[The body], then, here is taken for that corruption and depravity of our natures whereof the body, in a great part, is the seat and instrument, the very members of the body being made servants unto unrighteousness thereby, Rom. vi. 19. It is indwelling sin, the corrupted flesh or lust, that is intended. Many reasons might be given of this metonymical expression, that I shall not now insist on. The “body” here is the same with παλαιὸς ἄνθρωπος, and σῶμα τῆς ἁμαρτίας, the “old man,” and the “body of sin,” Rom. vi. 6; or it may synecdochically express the whole person considered as corrupted, and the seat of lusts and distempered affections.

(2.) The #emph[deeds of the body]. The word is πράξεις, which, indeed, denoteth the outward actions chiefly, “the works of the flesh,” as they are called, τὰ ἔργα τῆς σαρκός, Gal. v. 19; which are there said to be “manifest,” and are enumerated. Now, though the outward deeds are here only expressed, yet the inward and next causes are chiefly intended; the “axe is to be laid to the root of the tree,” — the deeds of the flesh are to be mortified in their causes, from whence they spring. The apostle calls them #emph[deeds], as that which every lust tends unto; though it do but conceive and prove abortive, it aims to bring forth a perfect sin.

Having, both in the seventh and the beginning of this chapter, treated of indwelling lust and sin as the fountain and principle of all sinful actions, he here mentions its destruction under the name of the effects which it doth produce. Πράξεις τοῦ σώματος are, as much as φρόνημα τῆς σαρκός, Rom. viii. 6, the “wisdom of the flesh,” by a metonymy of the same nature with the former; or as the παθήματα and ἐπιθυμίαι, the “passions and lusts of the flesh,” Gal. v. 24, whence the deeds and fruits of it do arise; and in this sense is #emph[the body] used, Rom. viii. 10: “The body is dead because of sin.”

(3.) To #emph[mortify]. Εἰ θανατοῦτε, — “If ye put to death;” a metaphorical expression, taken from the putting of any living thing to death. To kill a man, or any other living thing, is to take away the principle of all his strength, vigour, and power, so that he cannot act or exert, or put forth any proper actings of his own; so it is in this case. Indwelling sin is compared to a person, a living person, called “the old man,” with his faculties, and properties, his wisdom, craft, subtlety, strength; this, says the apostle, must be killed, put to death, mortified, — that is, have its power, life, vigour, and strength, to produce its effects, taken away by the Spirit. It is, indeed, meritoriously, and by way of example, utterly mortified and slain by the cross of Christ; and the “old man” is thence said to be “crucified with Christ,” Rom. vi. 6, and ourselves to be “dead” with him, verse 8, and really initially in regeneration, Rom. vi. 3–5, when a principle contrary to it, and destructive of it, Gal. v. 17, is planted in our hearts; but the whole work is by degrees to be carried on towards perfection all our days. Of this more in the process of our discourse. The intendment of the apostle in this prescription of the duty mentioned is, — that #emph[the mortification of indwelling sin remaining in our mortal bodies, that it may not have life and power to bring forth the works or deeds of the flesh is the constant duty of believers].

5\. The #emph[promise] unto this duty is life: “Ye shall live.” The life promised is opposed to the death threatened in the clause foregoing, “If ye live after the flesh, ye shall die;” which the same apostle expresseth, “Ye shall of the flesh reap corruption,” Gal. vi. 8, or destruction from God. Now, perhaps the word may not only intend eternal life, but also the spiritual life in Christ, which here we have; not as to the essence and being of it, which is already enjoyed by believers, but as to the joy, comfort, and vigour of it: as the apostle says in another case, “Now I live, if ye stand fast,” 1 Thess. iii. 8; — “Now my life will do me good; I shall have joy and comfort with my life;” — “Ye shall live, lead a good, vigorous, comfortable, spiritual life whilst you are here, and obtain eternal life hereafter.”

Supposing what was said before of the connection between mortification and eternal life, as of means and end, I shall add only, as a second motive to the duty prescribed, that, —

#emph[The vigour, and power, and comfort of our spiritual life depends on the mortification of the deeds of the flesh.]
