== Chapter III

#block(inset: (x: 1em))[The second general principle of the means of mortification proposed to confirmation — The Spirit the only author of this work — Vanity of popish mortification discovered — Many means of it used by them not appointed of God — Those appointed by him abused — The mistakes of others in this business — The Spirit is promised believers for this work, Ezek. xi. 19, xxxvi. 26 — All that we receive from Christ is by the Spirit — How the Spirit mortifies sin — Gal. v. 19–23 — The several ways of his operation to this end proposed — How his work and our duty.]

The next principle relates to the great sovereign cause of the mortification treated of; which, in the words laid for the foundation of this discourse, is said to be the Spirit, — that is, the Holy Ghost, as was evinced.

II. #emph[He only is sufficient for this work; all ways and means without him are as a thing of nought; and he is the great efficient of it, — he works in us as he pleases.]

1\. In vain do men seek other remedies; they shall not be healed by them. What several ways have been prescribed for this, to have sin mortified, is known. The greatest part of popish religion, of that which looks most like religion in their profession, consists in mistaken ways and means of mortification. This is the pretence of their rough garments, whereby they deceive. Their vows, orders, fastings, penances, are all built on this ground; they are all for the mortifying of sin. Their preachings, sermons, and books of devotion, they look all this way. Hence, those who interpret the locusts that came out of the bottomless pit, Rev. ix. 3, to be the friars of the Romish church, who are said to torment men, so “that they should seek death and not find it,” verse 6, think that they did it by their stinging sermons, whereby they convinced them of sin, but being not able to discover the remedy for the healing and mortifying of it, they kept them in such perpetual anguish and terror, and such trouble in their consciences, that they desired to die. This, I say, is the substance and glory of their religion; but what with their labouring to mortify dead creatures, ignorant of the nature and end of the work, — what with the poison they mixed with it, in their persuasion of its merit, yea, #emph[supererogation] (as they style their unnecessary merit, with a proud, barbarous title), — their glory is their shame: but of them and their mortification more afterward, chap. vii.

That the ways and means to be used for the mortification of sin invented by them are still insisted on and prescribed, for the same end, by some who should have more light and knowledge of the gospel, is known. Such directions to this purpose have of late been given by some, and are greedily catched at by others professing themselves Protestants, as might have become popish devotionists three or four hundred years ago. Such outside endeavours, such bodily exercises, such self-performances, such merely legal duties, without the least mention of Christ or his Spirit, are varnished over with swelling words of vanity, for the only means and expedients for the mortification of sin, as discover a deep-rooted unacquaintedness with the power of God and mystery of the gospel. The consideration hereof was one motive to the publishing of this plain discourse.

Now, the reasons why the Papists can never, with all their endeavours, truly mortify any one sin, amongst others, are, —

(1.) Because many of the ways and means they use and insist upon for this end were never appointed of God for that purpose. (Now, there is nothing in religion that hath any efficacy for compassing an end, but it hath it from God’s appointment of it to that purpose.) Such as these are their rough garments, their vows, penances, disciplines, their course of monastical life, and the like; concerning all which God will say, “Who hath required these things at your hand?” and, “In vain do ye worship me, teaching for doctrines the traditions of men.” Of the same nature are sundry self-vexations insisted on by others.

(2.) Because those things that are appointed of God as means are not used by them in their due place and order, — such as are praying, fasting, watching, meditation, and the like. These have their use in the business in hand; but whereas they are all to be looked on as streams, they look on them as the fountain. Whereas they effect and accomplish the end as means only, subordinate to the Spirit and faith, they look on them to do it by virtue of the work wrought. If they fast so much, and pray so much, and keep their hours and times, the work is done. As the apostle says of some in another case, “They are always learning, never coming to the knowledge of the truth;” so they are always mortifying, but never come to any sound mortification. In a word, they have sundry means to mortify the natural man, as to the natural life here we lead; none to mortify lust or corruption.

This is the general mistake of men ignorant of the gospel about this thing; and it lies at the bottom of very much of that superstition and will-worship that hath been brought into the world. What horrible self-macerations were practised by some of the ancient authors of monastical devotion! what violence did they offer to nature! what extremity of sufferings did they put themselves upon! Search their ways and principles to the bottom, and you will find that it had no other root but this mistake, namely, that attempting rigid mortification, they fell upon the natural man instead of the corrupt old man, — upon the body wherein we live instead of the body of death.

Neither will the natural Popery that is in others do it. Men are galled with the guilt of a sin that hath prevailed over them; they instantly promise to themselves and God that they will do so no more; they watch over themselves, and pray for a season, until this heat waxes cold, and the sense of sin is worn off: and so mortification goes also, and sin returns to its former dominion. Duties are excellent food for a healthy soul; they are no physic for a sick soul. He that turns his meat into his medicine must expect no great operation. Spiritually sick men cannot sweat out their distemper with working. But this is the way of men who deceive their own souls; as we shall see afterward.

That none of these ways are sufficient is evident from the nature of the work itself that is to be done; it is a work that requires so many concurrent actings in it as no self-endeavour can reach unto, and is of that kind that an almighty energy is necessary for its accomplishment; as shall be afterward manifested.

2\. It is, then, the work of the Spirit. For, —

(1.) He is #emph[promised] of God to be given unto us to do this work. The taking away of the stony heart, — that is, the stubborn, proud, rebellious, unbelieving heart, — is in general the work of mortification that we treat of. Now this is still promised to be done by the Spirit, Ezek. xi. 19, xxxvi. 26, “I will give my Spirit, and take away the stony heart;” and by the Spirit of God is this work wrought when all means fail, Isa. lvii. 17, 18.

(2.) We have all our mortification from the #emph[gift] of Christ, and all the gifts of Christ are communicated to us and given us by the Spirit of Christ: “Without Christ we can do nothing,” John xv. 5. All communications of supplies and relief, in the beginnings, increasings, actings of any grace whatever, from him, are by the Spirit, by whom he alone works in and upon believers. From him we have our mortification: “He is exalted and made a Prince and a Saviour, to give repentance unto us,” Acts v. 31; and of our repentance our mortification is no small portion. How doth he do it? Having “received the promise of the Holy Ghost,” he sends him abroad for that end, Acts ii. 33. You know the manifold promises he made of sending the Spirit, as Tertullian speaks, “Vicariam navare operam,” to do the works that he had to accomplish in us.

The resolution of one or two questions will now lead me nearer to what I principally intend.

The first is, #emph[How doth the Spirit mortify sin?]

I answer, in general, three ways:—

\[1.\] By causing our hearts to abound in #emph[grace] and the fruits that are contrary to the flesh, and the fruits thereof and principles of them. So the apostle opposes the fruits of the flesh and of the Spirit: “The fruits of the flesh,” says he, “are so and so,” Gal. v. 19–21; “but,” says he, “the fruits of the Spirit are quite contrary, quite of another sort,” verses 22, 23. Yea; but what if these are in us and do abound, may not the other abound also? No, says he, verse 24, “They that are Christ’s have crucified the flesh with the affections and lusts.” But how? Why, verse 25, “By living in the Spirit and walking after the Spirit;” — that is, by the abounding of these graces of the Spirit in us, and walking according to them. For, saith the apostle, “These are contrary one to another,” verse 17; so that they cannot both be in the same subject, in any intense or high degree. This “renewing of us by the Holy Ghost,” as it is called, Tit. iii. 5, is one great way of mortification; he causes us to grow, thrive, flourish, and abound in those graces which are contrary, opposite, and destructive to all the fruits of the flesh, and to the quiet or thriving of indwelling sin itself.

\[2.\] By a #emph[real physical efficiency] on the root and habit of sin, for the weakening, destroying, and taking it away. Hence he is called a “Spirit of judgment and burning,” Isa. iv. 4, really consuming and destroying our lusts. He takes away the stony heart by an almighty efficiency; for as he begins the work as to its kind, so he carries it on as to its degrees. He is the fire which burns up the very root of lust.

\[3.\] He brings the #emph[cross of Christ] into the heart of a sinner by faith, and gives us communion with Christ in his death, and fellowship in his sufferings: of the manner whereof more afterward.

Secondly. If this be the work of the Spirit alone, how is it that we are exhorted to it? — seeing the Spirit of God only can do it, let the work be left wholly to him.

\[1.\] It is no otherwise the work of the Spirit but as all graces and good works which are in us are his. He “works in us to will and to do of his own good pleasure,” Phil. ii. 13; he works “all our works in us,” Isa. xxvi. 12, — “the work of faith with power,” 2 Thess. i. 11, Col. ii. 12; he causes us to pray, and is a “Spirit of supplication,” Rom. viii. 26, Zech. xii. 10; and yet we are exhorted, and are to be exhorted, to all these.

\[2.\] He doth not so work our mortification in us as not to keep it still an act of our #emph[obedience]. The Holy Ghost works in us and upon us, as we are fit to be wrought in and upon; that is, so as to preserve our own liberty and free obedience. He works upon our understandings, wills, consciences, and affections, agreeably to their own natures; he works #emph[in us] and #emph[with us], not #emph[against us] or #emph[without us]\; so that his assistance is an encouragement as to the facilitating of the work, and no occasion of neglect as to the work itself. And, indeed, I might here bewail the endless, foolish labour of poor souls, who, being convinced of sin, and not able to stand against the power of their convictions, do set themselves, by innumerable perplexing ways and duties, to keep down sin, but, being strangers to the Spirit of God, all in vain. They combat without victory, have war without peace, and are in slavery all their days. They spend their strength for that which is not bread, and their labour for that which profiteth not.

This is the saddest warfare that any poor creature can be engaged in. A soul under the power of conviction from the law is pressed to fight against sin, but hath no strength for the combat. They cannot but fight, and they can never conquer; they are like men thrust on the sword of enemies on purpose to be slain. The #emph[law] drives them on, and sin beats them back. Sometimes they think, indeed, that they have foiled sin, when they have only raised a dust that they see it not; that is, they distemper their natural affections of fear, sorrow, and anguish, which makes them believe that sin is conquered when it is not touched. By that time they are cold, they must to the battle again; and the lust which they thought to be slain appears to have had no wound.

And if the case be so sad with them who do labour and strive, and yet enter not into the kingdom, what is their condition who despise all this; who are perpetually under the power and dominion of sin, and love to have it so; and are troubled at nothing, but that they cannot make sufficient provision for the flesh, to fulfil the lusts thereof?
