== Chapter X

#block(inset: (x: 1em))[The second particular direction: Get a clear sense of, — 1. The guilt of the sin perplexing — Considerations for help therein proposed — 2. The danger manifold — (1.) Hardening — (2.) Temporal correction — (3.) Loss of peace and strength — (4.) Eternal destruction — Rules for the management of this consideration — 3. The evil of it — (1.) In grieving the Spirit — (2.) Wounding the new creature — \[(3.) Taking away a man’s usefulness.\]]

The second direction is this: #emph[Get a clear and abiding sense upon thy mind and conscience of the guilt, danger, and evil] of that sin wherewith thou art perplexed:—

1\. Of the #emph[guilt] of it. It is one of the deceits of a prevailing lust to extenuate its own guilt. “Is it not a little one?” “When I go and bow myself in the house of Rimmon, God be merciful to me in this thing.” “Though this be bad, yet it is not so bad as such and such an evil; others of the people of God have had such a frame; yea, what dreadful actual sins have some of them fallen into!” Innumerable ways there are whereby sin diverts the mind from a right and due apprehension of its guilt. Its noisome exhalations darken the mind, that it cannot make a right judgment of things. Perplexing reasonings, extenuating promises, tumultuating desires, treacherous purposes of relinquishment, hopes of mercy, all have their share in disturbing the mind in its consideration of the guilt of a prevailing lust. The prophet tells us that lust will do thus wholly when it comes to the height: Hos. iv. 11, “Whoredom and wine and new wine take away the heart,” — the heart, that is the understanding, as it is often used in the Scripture. And as they accomplish this work to the height in unregenerate persons, so in part in regenerate also. Solomon tells you of him who was enticed by the lewd woman, that he was “among the simple ones;” he was “a young man void of understanding,” Prov. vii. 7. And wherein did his folly appear? Why, says he, in the 23d verse, “He knew not that it was for his life;” he considered not the guilt of the evil that he was involved in. And the Lord, rendering a reason why his dealings with Ephraim took no better effect, gives this account: “Ephraim is like a silly dove without heart,” Hos. vii. 11; — had no understanding of his own miserable condition. Had it been possible that David should have lain so long in the guilt of that abominable sin, but that he had innumerable corrupt reasonings, hindering him from taking a clear view of its ugliness and guilt in the glass of the law? This made the prophet that was sent for his awaking, in his dealings with him, to shut up all subterfuges and pretences by his parable, that so he might fall fully under a sense of the guilt of it. This is the proper issue of lust in the heart, — it darkens the mind that it shall not judge aright of its guilt; and many other ways it hath for its own extenuation that I shall not now insist on.

Let this, then, be the first care of him that would mortify sin, — to fix a right judgment of its guilt in his mind. To which end take these considerations to thy assistance:—

(1.) Though the power of sin be weakened by #emph[inherent grace] in them that have it, that sin shall not have dominion over them as it hath over others, yet #emph[the guilt of sin that doth yet abide and remain is aggravated and heightened by it]: Rom. vi. 1, 2, “What shall we say then? shall we continue in sin, that grace may abound? God forbid. How shall we, that are dead to sin, live any longer therein?” — “How shall we, that are dead?” The emphasis is on the word “we.” How shall #emph[we] do it, who, as he afterward describes it, have received grace from Christ to the contrary? We, doubtless, are more evil than any, if we do it. I shall not insist on the special aggravations of the sins of such persons, — how they sin against more love, mercy, grace, assistance, relief, means, and deliverances than others. But let this consideration abide in thy mind, — there is inconceivably more evil and guilt in the evil of thy heart that doth remain, than there would be in so much sin if thou hadst no grace at all. Observe, —

(2.) That as God sees abundance of beauty and excellency in the desires of the heart of his servants, more than in any the most glorious works of other men, yea, more than in most of their own outward performances, which have a greater mixture of sin than the desires and pantings of grace in the heart have; so God sees #emph[a great deal of evil in the working of lust in their hearts, yea, and more than in the open, notorious acts of wicked men], or in many outward sins whereinto the saints may fall, seeing against them there is more opposition made, and more humiliation generally follows them. Thus Christ, dealing with his decaying children, goes to the root with them, lays aside their profession: Rev. iii. 15, “I know thee;” — “Thou art quite another thing than thou professest; and this makes thee abominable.”

So, then, let these things, and the like considerations, lead thee to a clear sense of the guilt of thy indwelling lust, that there may be no room in thy heart for extenuating or excusing thoughts, whereby sin insensibly will get strength and prevail.

2\. Consider the #emph[danger] of it, which is manifold:—

(1.) Of being #emph[hardened by the deceitfulness]. This the apostle sorely charges on the Hebrews, chap. iii. 12, 13, “Take heed, brethren, lest there be in any of you an evil heart of unbelief, in departing from the living God. But exhort one another daily, while it is called To-day; lest any of you be hardened through the deceitfulness of sin.” “Take heed,” saith he, “use all means, consider your temptations, watch diligently; there is a treachery, a deceit in sin, that tends to the hardening of your hearts from the fear of God.” The hardening here mentioned is to the utmost, — utter obduration; sin tends to it, and every distemper and lust will make at least some progress towards it. Thou that wast tender, and didst use to melt under the word, under afflictions, wilt grow as some have profanely spoken, “sermon-proof and sickness-proof.” Thou that didst tremble at the presence of God, thoughts of death, and appearance before him, when thou hadst more assurance of his love than now thou hast, shalt have a stoutness upon thy spirit not to be moved by these things. Thy soul and thy sin shall be spoken of and spoken to, and thou shalt not be at all concerned, but shalt be able to pass over duties, praying, hearing, reading, and thy heart not in the least affected. Sin will grow #emph[a light thing] to thee; thou wilt pass it by as a thing of nought; this it will grow to. And what will be the end of such a condition? Can a sadder thing befall thee? Is it not enough to make any heart to tremble, to think of being brought into that estate wherein he should have slight thoughts of sin? Slight thoughts of grace, of mercy, of the blood of Christ, of the law, heaven, and hell, come all in at the same season. Take heed, this is that thy lust is working towards, — the hardening of the heart, searing of the conscience, blinding of the mind, stupifying of the affections, and deceiving of the whole soul.

(2.) The danger of some great #emph[temporal correction], which the Scripture calls “vengeance,” “judgment,” and “punishment.” Ps. lxxxix. 30–33, Though God should not utterly cast thee off for this abomination that lies in thy heart, yet he will visit thee with the rod; though he pardon and forgive, he will take vengeance of thy inventions. O remember David and all his troubles! look on him flying into the wilderness, and consider the hand of God upon him. Is it nothing to thee that God should kill thy child in anger, ruin thy estate in anger, break thy bones in anger, suffer thee to be a scandal and reproach in anger, kill thee, destroy thee, make thee lie down in darkness, in anger? Is it nothing that he should punish, ruin, and undo others for thy sake? Let me not be mistaken. I do not mean that God doth send all these things always on #emph[his] in anger; God forbid! but this I say, that when he doth so deal with thee, and thy conscience bears witness with him what thy provocations have been, thou wilt find his dealings full of bitterness to thy soul. If #emph[thou fearest] not these things, #emph[I fear] thou art under hardness.

(3.) #emph[Loss of peace and strength] all a man’s days. To have peace with God, to have strength to walk before God, is the sum of the great promises of the covenant of grace. In these things is the life of our souls. Without them in some comfortable measure, to live is to die. What good will our lives do us if we see not the face of God sometimes in peace? if we have not some strength to walk with him? Now, both these will an unmortified lust certainly deprive the souls of men of. This case is so evident in David, as that nothing can be more clear. How often doth he complain that his bones were broken, his soul disquieted, his wounds grievous, on this account! Take other instances: Isa. lvii. 17, “For the iniquity of his covetousness I was wroth, and hid myself.” What peace, I pray, is there to a soul while God hides himself, or strength whilst he smites? Hos. v. 15, “I will go and return to my place, till they acknowledge their offence, and seek my face;” — “I will leave them, hide my face, and what will become of their peace and strength?” If ever, then, thou hast enjoyed peace with God, if ever his terrors have made thee afraid, if ever thou hast had strength to walk with him, or ever hast mourned in thy prayer, and been troubled because of thy weakness, think of this danger that hangs over thy head. It is perhaps but a little while and thou shalt see the face of God in peace no more. Perhaps by to-morrow thou shalt not be able to pray, read, hear, or perform any duties with the least cheerfulness, life, or vigour; and possibly thou mayst never see a quiet hour whilst thou livest, — that thou mayst carry about thee broken bones, full of pain and terror, all the days of thy life. Yea, perhaps God will shoot his arrows at thee, and fill thee with anguish and disquietness, with fears and perplexities; make thee a terror and an astonishment to thyself and others; show thee hell and wrath every moment; frighten and scare thee with sad apprehensions of his hatred; so that thy sore shall run in the night season, and thy soul shall refuse comfort; so that thou shalt wish death rather than life, yea, thy soul may choose strangling. Consider this a little, — though God should not utterly destroy thee, yet he might cast thee into this condition, wherein thou shalt have quick and living apprehensions of thy destruction. Wont thy heart to thoughts hereof; let it know what is like to be the issue of its state. Leave not this consideration until thou hast made thy soul to tremble within thee.

(4.) There is the danger of #emph[eternal destruction].

For the due management of this consideration, observe, —

\[1.\] That there is such a #emph[connection] between a #emph[continuance in sin] and #emph[eternal destruction], that though God does resolve to deliver some from a continuance in sin that they may not be destroyed, yet he will deliver none from destruction that continue in sin; so that whilst any one lies under an abiding power of sin, the threats of destruction and everlasting separation from God are to be held out to him. So Heb. iii. 12; to which add chap. x. 38. This is the rule of God’s proceeding: If any man “depart” from him, “draw back” through unbelief, “God’s soul hath no pleasure in him;” — “that is, his indignation shall pursue him to destruction:” so evidently, Gal. vi. 8.

\[2.\] That he who is #emph[so entangled], as above described, under the power of any corruption, can have at that present no clear prevailing evidence of his interest in the covenant, by the efficacy whereof he may be delivered from fear of destruction; so that destruction from the Lord may justly be a terror to him; and he may, he ought to look upon it, as that which will be #emph[the end of his course and ways]. “There is no condemnation to them that are in Christ Jesus,” Rom. viii. 1. True; but who shall have the comfort of this assertion? who may assume it to himself? “They that walk after the Spirit, and not after the flesh.” But you will say, “Is not this to persuade men to unbelief?” I answer, No. There is a twofold judgment that a man may make of himself, — first, of his #emph[person]\; and, secondly, of his #emph[ways]. It is the judgment of his ways, not his person, that I speak of. Let a man get the best evidence for his person that he can, yet to judge that an evil way will end in destruction is his duty; not to do it is atheism. I do not say, that in such a condition a man ought to throw away the evidences of his personal interest in Christ; but I say, he cannot keep them. There is a twofold condemnation of a man’s self:— First, In respect of #emph[desert], when the soul concludes that it deserves to be cast out of the presence of God; and this is so far from a business of unbelief that it is an effect of faith. Secondly, With respect to the #emph[issue and event], when the soul concludes it shall be damned. I do not say this is the duty of any one, nor do I call them to it; but this I say, that the end of the way wherein a man is ought by him to be concluded to be death, that he may be provoked to fly from it. And this is another consideration that ought to dwell upon such a soul, if it desire to be freed from the entanglement of its lusts.

3\. Consider the #emph[evils] of it; I mean its #emph[present evils]. Danger respects what is to come; evil, what is present. Some of the many evils that attend an unmortified lust may be mentioned:—

(1.) It #emph[grieves] the holy and blessed Spirit, which is given to believers to dwell in them and abide with them. So the apostle, Eph. iv. 25–29, dehorting them from many lusts and sins, gives this as the great motive of it, verse 30, “Grieve not the Holy Spirit, whereby ye are sealed unto the day of redemption.” “Grieve not that Spirit of God,” saith he, “whereby you receive so many and so great benefits;” of which he instances in one signal and comprehensive one, — “sealing to the day of redemption.” He is grieved by it. As a tender and loving friend is grieved at the unkindness of his friend, of whom he hath well deserved, so is it with this tender and loving Spirit, who hath chosen our hearts for a habitation to dwell in, and there to do for us all that our souls desire. He is grieved by our harbouring his enemies, and those whom he is to destroy, in our hearts with him. “He doth not afflict willingly, nor grieve us,” Lam. iii. 33; and shall we daily grieve him? Thus is he said sometimes to be “vexed,” sometimes “grieved at his heart,” to express the greatest sense of our provocation. Now, if there be any thing of gracious ingenuity left in the soul, if it be not utterly hardened by the deceitfulness of sin, this consideration will certainly affect it. Consider who and what thou art; who the Spirit is that is grieved, what he hath done for thee, what he comes to thy soul about, what he hath already done in thee; and be ashamed. Among those who walk with God, there is no greater motive and incentive unto universal holiness, and the preserving of their hearts and spirits in all purity and cleanness, than this, that the blessed Spirit, who hath undertaken to dwell in them as temples of God, and to preserve them meet for him who so dwells in them, is continually considering what they give entertainment in their hearts unto, and rejoiceth when his temple is kept undefiled. That was a high aggravation of the sin of Zimri, that he brought his adulteress into the congregation in the sight of Moses and the rest, who were weeping for the sins of the people, Numb. xxv. 6. And is it not a high aggravation of the countenancing a lust, or suffering it to abide in the heart, when it is (as it must be, if we are believers) entertained under the peculiar eye and view of the Holy Ghost, taking care to preserve his tabernacle pure and holy?

(2.) The #emph[Lord Jesus Christ is wounded afresh] by it; his new creature in the heart is wounded; his love is foiled; his adversary gratified. As a total relinquishment of him, by the deceitfulness of sin, is the “crucifying him afresh, and the putting of him to open shame;” so every harbouring of sin that he came to destroy wounds and grieves him.

(3.) It will #emph[take away a man’s usefulness] in his generation. His works, his endeavours, his labours, seldom receive blessing from God. If he be a preacher, God commonly blows upon his ministry, that he shall labour in the fire, and not be honoured with any success or doing any work for God; and the like may be spoken of other conditions. The world is at this day full of poor withering professors. How few are there that walk in any beauty or glory! how barren, how useless are they, for the most part! Amongst the many reasons that may be assigned of this sad estate, it may justly be feared that this is none of the least effectual, — many men harbour spirit-devouring lusts in their bosoms, that lie as worms at the root of their obedience, and corrode and weaken it day by day. All graces, all the ways and means whereby any graces may be exercised and improved, are prejudiced by this means; and as to any success, God blasts such men’s undertakings.

This, then, is my second direction, and it regards the opposition that is to be made to lust in respect of its habitual residence in the soul:— Keep alive upon thy heart these or the like considerations of its guilt, danger, and evil; be much in the meditation of these things; cause thy heart to dwell and abide upon them; engage thy thoughts into these considerations; let them not go off nor wander from them until they begin to have a powerful influence upon thy soul, — until they make it to tremble.
