== Chapter IV

#block(inset: (x: 1em))[The last principle; of the usefulness of mortification — The vigour and comfort of our spiritual lives depend on our mortification — In what sense — Not absolutely and necessarily; Ps. lxxxviii., Heman’s condition — Not as on the next and immediate cause — As a means; by removing of the contrary — The desperate effects of any unmortified lust; it weakens the soul, Ps. xxxviii. 3, 8, sundry ways, and darkens it — All graces improved by the mortification of sin — The best evidence of sincerity.]

The last principle I shall insist on (omitting, first, the necessity of mortification unto life, and, secondly, the certainty of life upon mortification) is, —

III. #emph[That the life, vigour, and comfort of our spiritual life depend much on our mortification of sin.]

Strength and comfort, and power and peace, in our walking with God, are the things of our desires. Were any of us asked seriously, what it is that troubles us, we must refer it to one of these heads:— either we want strength or power, vigour and life, in our obedience, in our walking with God; or we want peace, comfort, and consolation therein. Whatever it is that may befall a believer that doth not belong to one of these two heads, doth not deserve to be mentioned in the days of our complaints.

Now, all these do much depend on a constant course of mortification, concerning which observe, —

1\. I do not say they proceed from it, as though they were #emph[necessarily] tied to it. A man may be carried on in a constant course of mortification all his days; and yet perhaps never enjoy a good day of peace and consolation. So it was with Heman, Ps. lxxxviii.; his life was a life of perpetual mortification and walking with God, yet terrors and wounds were his portion all his days. But God singled out Heman, a choice friend, to make him an example to them that afterward should be in distress. Canst thou complain if it be no otherwise with thee than it was with Heman, that eminent servant of God? and this shall be his praise to the end of the world. God makes it his prerogative to speak peace and consolation, Isa. lvii. 18, 19. “I will do that work,” says God, “I will comfort him,” verse 18. But how? By an immediate work of the new creation: “I create it,” says God. The #emph[use of means] for the obtaining of peace is ours; the #emph[bestowing] of it is God’s prerogative.

2\. In the ways instituted by God for to give us life, vigour, courage, and consolation, mortification is not one of the immediate causes of it. They are the privileges of our adoption made known to our souls that give us immediately these things. “The Spirit bearing witness with our spirits that we are the children of God,” giving us a new name and a white stone, adoption and justification, — that is, as to the sense and knowledge of them, — are the immediate causes (in the hand of the Spirit) of these things. But this I say, —

3\. In our ordinary walking with God, and in an ordinary course of his dealing with us, the vigour and comfort of our spiritual lives depend much on our mortification, not only as a “causa sine qua non,” but as a thing that hath an effectual influence thereinto. For, —

(1.) This alone keeps sin from depriving us of the one and the other.

Every unmortified sin will certainly do two things:— \[1.\] It will #emph[weaken] the soul, and deprive it of its vigour. \[2.\] It will #emph[darken] the soul, and deprive it of its comfort and peace.

\[1.\] It #emph[weakens] the soul, and deprives it of its strength. When David had for a while harboured an unmortified lust in his heart, it broke all his bones, and left him no spiritual strength; hence he complained that he was sick, weak, wounded, faint. “There is,” saith he, “no soundness in me,” Ps. xxxviii. 3; “I am feeble and sore broken,” verse 8; “yea, I cannot so much as look up,” Ps. xl. 12. An unmortified lust will drink up the spirit, and all the vigour of the soul, and weaken it for all duties. For, —

1#emph[st]. It #emph[untunes] and unframes the heart itself, by entangling its affections. It diverts the heart from the spiritual frame that is required for vigorous communion with God; it lays hold on the affections, rendering its object beloved and desirable, so expelling the love of the Father, 1 John ii. 15, iii. 17; so that the soul cannot say uprightly and truly to God, “Thou art my portion,” having something else that it loves. Fear, desire, hope, which are the choice affections of the soul, that should be full of God, will be one way or other entangled with it.

2#emph[dly]. It fills the #emph[thoughts] with contrivances about it. Thoughts are the great purveyors of the soul to bring in provision to satisfy its affections; and if sin remain unmortified in the heart, they must ever and anon be making provision for the flesh, to fulfil the lusts thereof. They must glaze, adorn, and dress the objects of the flesh, and bring them home to give satisfaction; and this they are able to do, in the service of a defiled imagination, beyond all expression.

3#emph[dly]. It breaks out and actually hinders duty. The ambitious man must be studying, and the worldling must be working or contriving, and the sensual, vain person providing himself for vanity, when they should be engaged in the worship of God.

Were this my present business, to set forth the breaches, ruin, weakness, desolations, that one unmortified lust will bring upon a soul, this discourse must be extended much beyond my intendment.

\[2.\] As sin #emph[weakens], so it #emph[darkens] the soul. It is a cloud, a thick cloud, that spreads itself over the face of the soul, and intercepts all the beams of God’s love and favour. It takes away all sense of the privilege of our adoption; and if the soul begins to gather up thoughts of consolation, sin quickly scatters them: of which afterward.

Now, in this regard doth the vigour and power of our spiritual life depend on our mortification: It is the only means of the removal of that which will allow us neither the one nor the other. Men that are sick and wounded under the power of lust make many applications for help; they cry to God when the perplexity of their thoughts overwhelms them, even to God do they cry, but are not delivered; in vain do they use many remedies, — “they shall not be healed.” So, Hos. v. 13, “Ephraim saw his sickness, and Judah his wound,” and attempted sundry remedies: nothing will do until they come (verse 15) to “acknowledge their offence.” Men may see their sickness and wounds, but yet, if they make not due applications, their cure will not be effected.

(2.) Mortification prunes all the graces of God, and makes room for them in our hearts to grow. The life and vigour of our spiritual lives consists in the vigour and flourishing of the plants of grace in our hearts. Now, as you may see in a garden, let there be a precious herb planted, and let the ground be untilled, and weeds grow about it, perhaps it will live still, but be a poor, withering, unuseful thing. You must look and search for it, and sometimes can scarce find it; and when you do, you can scarce know it, whether it be the plant you look for or no; and suppose it be, you can make no use of it at all. When, let another of the same kind be set in the ground, naturally as barren and bad as the other, but let it be well weeded, and every thing that is noxious and hurtful removed from it, — it flourishes and thrives; you may see it at first look into the garden, and have it for your use when you please. So it is with the graces of the Spirit that are planted in our hearts. That is true; they #emph[are] still, they abide in a heart where there is some neglect of mortification; but they are ready to die, Rev. iii. 2, they are withering and decaying. The heart is like the sluggard’s field, — so overgrown with weeds that you can scarce see the good corn. Such a man may search for faith, love, and zeal, and scarce be able to find any; and if he do discover that these graces are there yet alive and sincere, yet they are so weak, so clogged with lusts, that they are of very little use; they remain, indeed, but are ready to die. But now let the heart be cleansed by mortification, the weeds of lust constantly and daily rooted up (as they spring daily, nature being their proper soil), let room be made for grace to thrive and flourish, — how will every grace act its part, and be ready for every use and purpose!

(3.) As to our peace; as there is nothing that hath any evidence of sincerity without it, so I know nothing that hath such an evidence of sincerity in it; — which is no small foundation of our peace. Mortification is the soul’s vigorous opposition to self, wherein sincerity is most evident.
