== Chapter VII

#block(inset: (x: 1em))[General rules, without which no lust will be mortified — No mortification unless a man be a believer — Dangers of attempting mortification of sin by unregenerate persons — The duty of unconverted persons as to this business of mortification considered — The vanity of the Papists’ attempts and rules for mortification thence discovered.]

II. The #emph[ways] and #emph[means] whereby a soul may proceed to the mortification of any particular lust and sin, which Satan takes advantage by to disquiet and weaken him, come next under consideration.

Now, there are some general considerations to be premised, concerning some principles and foundations of this work, without which no man in the world, be he never so much raised by convictions, and resolved for the mortification of any sin, can attain thereunto.

General rules and principles, without which no sin will be ever mortified, are these:—

1\. #emph[Unless a man be a believer, — that is, one that is truly] ingrafted into Christ#emph[, — he can never mortify any one sin]\; I do not say, unless he know himself to be so, but unless indeed he be so.

Mortification is the work of believers: Rom. viii. 13, “If ye through the Spirit,” etc., — ye #emph[believers], to whom there is no condemnation, verse 1. They alone are exhorted to it: Col. iii. 5, “Mortify therefore your members which are upon the earth.” Who should mortify? You who “are risen with Christ,” verse 1; whose “life is hid with Christ in God,” verse 3; who “shall appear with him in glory,” verse 4. An unregenerate man may do something like it; but the work itself, so as it may be acceptable with God, he can never perform. You know what a picture of it is drawn in some of the philosophers, — Seneca, Tully, Epictetus; what affectionate discourses they have of contempt of the world and self, of regulating and conquering all exorbitant affections and passions! The lives of most of them manifested that their maxims differed as much from true mortification as the sun painted on a sign-post from the sun in the firmament; they had neither light nor heat. Their own Lucian sufficiently manifests what they all were. There is no death of sin without the death of Christ. You know what attempts there are made after it by the Papists, in their vows, penances, and satisfactions. I dare say of them (I mean as many of them as act upon the principles of their church, as they call it) what Paul says of Israel in point of righteousness, Rom. ix. 31, 32, — They have followed after mortification, but they have not attained to it. Wherefore? “Because they seek it not by faith, but as it were by the works of the law.” The same is the state and condition of all amongst ourselves who, in obedience to their convictions and awakened consciences, do attempt a relinquishment of sin; — they follow after it, but they do not attain it.

It is true, it #emph[is], it #emph[will be], required of every person whatever that hears the law or gospel preached, that he mortify sin. It is his #emph[duty], but it is not his #emph[immediate duty]\; it is his duty to do it, but to do it in God’s way. If you require your servant to pay so much money for you in such a place, but first to go and take it up in another, it is his duty to pay the money appointed, and you will blame him if he do it not; yet it was not his immediate duty, — he was first to take it up, according to your direction. So it is in this case: sin is to be mortified, but something is to be done in the first place to enable us thereunto.

I have proved that it is the Spirit alone that can mortify sin; he is promised to do it, and all other means without him are empty and vain. How shall he, then, mortify sin that hath not the Spirit? A man may easier see without eyes, speak without a tongue, than truly mortify one sin without the Spirit. Now, how is he attained? It is the Spirit of Christ: and as the apostle says, “If we have not the Spirit of Christ, we are none of his,” Rom. viii. 9; so, if we are Christ’s, have an interest in him, we have the Spirit, and so alone have power for mortification. This the apostle discourses at large, Rom. viii. 8, “So then they that are in the flesh cannot please God.” It is the inference and conclusion he makes of his foregoing discourse about our natural state and condition, and the enmity we have unto God and his law therein. If we are in the flesh, if we have not the Spirit, we cannot do any thing that should please God. But what is our deliverance from this condition? Verse 9, “But ye are not in the flesh, but in the Spirit, if so be that the Spirit of God dwell in you;” — “Ye believers, that have the Spirit of Christ, ye are not in the flesh.” There is no way of deliverance from the state and condition of being in the flesh but by the Spirit of Christ. And what if this Spirit of Christ be in you? Why, then, you are mortified; verse 10, “The body is dead because of sin,” or unto it; mortification is carried on; the new man is quickened to righteousness. This the apostle proves, verse 11, from the union we have with Christ by the Spirit, which will produce suitable operations in us to what it wrought in him. All attempts, then, for mortification of any lust, without an interest in Christ, are vain. Many men that are galled with and for sin, the arrows of Christ for conviction, by the preaching of the word, or some affliction having been made sharp in their hearts, do vigorously set themselves against this or that particular lust, wherewith their consciences have been most disquieted or perplexed. But, poor creatures! they labour in the fire, and their work consumeth. When the Spirit of Christ comes to this work he will be “like a refiner’s fire and like fullers’ soap,” and he will purge men as gold and as silver, Mal. iii. 2, 3, — take away their dross and tin, their filth and blood, as Isa. iv. 4; but men must be gold and silver in the bottom, or else refining will do them no good. The prophet gives us the sad issue of wicked men’s utmost attempts for mortification, by what means soever that God affords them: Jer. vi. 29, 30, “The bellows are burned, and the lead is consumed of the fire; the founder melteth in vain. Reprobate silver shall men call them, because the Lord hath rejected them.” And what is the reason hereof? Verse 28, They were “brass and iron” when they were put into the furnace. Men may refine brass and iron long enough before they will be good silver.

I say, then, mortification is not the #emph[present] business of #emph[unregenerate] men. God calls them not to it as yet; #emph[conversion] is their work, — the conversion of the #emph[whole] soul, — not the mortification of #emph[this] or #emph[that particular] lust. You would laugh at a man that you should see setting up a great fabric, and never take any care for a foundation; especially if you should see him so foolish as that, having a thousand experiences that what he built one day fell down another, he would yet continue in the same course. So it is with convinced persons; though they plainly see, that what ground they get against sin one day they lose another, yet they will go on in the same road still, without inquiring where the destructive flaw in their progress lies. When the Jews, upon the conviction of their sin, were cut to the heart, Acts ii. 37, and cried out, “What shall we do?” what doth Peter direct them to do? Does he bid them go and mortify their pride, wrath, malice, cruelty, and the like? No; he knew that was not their present work, but he calls them to conversion and faith in Christ in general, verse 38. Let the soul be first thoroughly converted, and then, “looking on Him whom they had pierced,” humiliation and mortification will ensue. Thus, when John came to preach repentance and conversion, he said, “The axe is now laid to the root of the tree,” Matt. iii. 10. The Pharisees had been laying heavy burdens, imposing tedious duties, and rigid means of mortification, in fastings, washings, and the like, all in vain. Says John, “The doctrine of conversion is for you; the axe in my hand is laid to the root.” And our Saviour tells us what is to be done in this case; says he, “Do men gather grapes from thorns?” Matt. vii. 16. But suppose a thorn be well pruned and cut, and have pains taken with him? “Yea, but he will never bear figs,” verses 17, 18; it cannot be but every tree will bring forth fruit according to its own kind. What is then to be done, he tells us, Matt. xii. 33, “Make the tree good, and his fruit will be good.” The root must be dealt with, the nature of the tree changed, or no good fruit will be brought forth.

This is that I aim at: unless a man be #emph[regenerate], unless he be a believer, all attempts that he can make for mortification, be they never so specious and promising, — all means he can use, let him follow them with never so much diligence, earnestness, watchfulness, and intention of mind and spirit, — are to no purpose. In vain shall he use many remedies; he shall not be healed. Yea, there are sundry desperate evils attending an endeavour in convinced persons, that are no more but so, to perform this duty:—

(1.) The mind and soul is taken up about that which is not the man’s #emph[proper business], and so he is diverted from that which is so. God lays hold by his word and judgments on some sin in him, galls his conscience, disquiets his heart, deprives him of his rest; now other diversions will not serve his turn; he must apply himself to the work before him. The business in hand being to awake the whole man unto a consideration of the state and condition wherein he is, that he might be brought home to God, instead hereof he sets himself to mortify the sin that galls him, — which is a pure issue of self-love, to be freed from his trouble, and not at all to the work he is called unto, — and so is diverted from it. Thus God tells us of Ephraim, when he “spread his net upon them, and brought them down as the fowls of heaven, and chastised them,” Hos. vii. 12, caught them, entangled them, convinced them that they could not escape; saith he of them, “They return, but not to the Most High;” — they set themselves to a relinquishment of sin, but not in that manner, by #emph[universal conversion], as God called for it. Thus are men diverted from coming unto God by the most glorious ways that they can fix upon to come to him by. And this is one of the most common deceits whereby men ruin their own souls. I wish that some whose trade it is to daub with untempered mortar in the things of God did not teach this deceit, and cause the people to err by their ignorance. What do men do, what ofttimes are they directed unto, when their consciences are galled by sin and disquietment from the Lord, who hath laid hold upon them? Is not a relinquishment of the sin, as to practice, that they are, in some fruits of it, perplexed withal, and making head against it, the sum of what they apply themselves unto? and is not the gospel end of their convictions lost thereby? Here men abide and perish.

(2.) This duty being a thing good in itself, in its proper place, a duty evidencing sincerity, bringing home peace to the conscience; a man finding himself really engaged in it, his mind and heart set against this or that sin, with purpose and resolution to have no more to do with it, — he is ready to conclude that his state and condition is good, and so to delude his own soul. For, —

\[1.\] When his conscience hath been made sick with sin, and he could find no rest, when he should go to the great Physician of souls, and get healing in his blood, the man by this engagement against sin pacifies and quiets his conscience, and sits down without going to Christ at all. Ah! how many poor souls are thus #emph[deluded] to eternity! “When Ephraim saw his sickness, he sent to king Jareb,” Hos. v. 13; which kept him off from God. The whole bundle of the popish religion is made up of designs and contrivances to pacify conscience without Christ; all described by the apostle, Rom. x. 3.

\[2.\] By this means men #emph[satisfy] themselves that their state and condition is good, seeing they do that which is a work good in itself, and they do not do it to be seen. They know they would have the work done in sincerity, and so are hardened in a kind of self-righteousness.

(3.) When a man hath thus for a season been deluded, and hath deceived his own soul, and finds in a #emph[long course] of life that indeed his sin is #emph[not mortified], or if he hath changed one he hath gotten another, he begins at length to think that all contending is in vain, — he shall never be able to prevail; he is making a dam against water that increaseth on him. Hereupon #emph[he gives over], as one despairing of any success, and yields up himself to the power of sin and that habit of formality that he hath gotten.

And this is the usual issue with persons attempting the mortification of sin without an interest in Christ first obtained. It #emph[deludes] them, #emph[hardens] them, — #emph[destroys] them. And therefore we see that there are not usually more vile and desperate sinners in the world than such as, having by conviction been put on this course, have found it fruitless, and deserted it without a discovery of Christ. And this is the substance of the religion and godliness of the choicest formalists in the world, and of all those who in the Roman synagogue are drawn to mortification, as they drive Indians to baptism or cattle to water. I say, then, that mortification is the work of believers, and believers only. To kill sin is the work of living men; where men are #emph[dead] (as all unbelievers, the best of them, are dead), sin is #emph[alive], and will live.

2\. It is the work of #emph[faith], the #emph[peculiar] work of faith. Now, if there be a work to be done that will be effected by one only instrument, it is the greatest madness for any to attempt the doing of it that hath not that instrument. Now, it is faith that purifies the heart, Acts xv. 9; or, as Peter speaks, we “purify our souls in obeying the truth through the Spirit,” 1 Pet. i. 22; and without it, it will not be done.

What hath been spoken I suppose is sufficient to make good my first #emph[general rule]:— #emph[Be sure to get an interest in Christ; if you intend to mortify any sin without it, it will never be done.]

#emph[Obj.] You will say, “What, then, would you have unregenerate men that are convinced of the evil of sin do? Shall they cease striving against sin, live dissolutely, give their lusts their swing, and be as bad as the worst of men? This were a way to set the whole world into confusion, to bring all things into darkness, to set open the flood-gates of lust, and lay the reins upon the necks of men to rush into all sin with delight and greediness, like the horse into the battle.”

#emph[Ans.] 1. God forbid! It is to be looked on as a great issue of the wisdom, goodness, and love of God, that by manifold ways and means he is pleased to restrain the sons of men from running forth into that compass of excess and riot which the depravedness of their nature would carry them out unto with violence. By what way soever this is done, it is an issue of the care, kindness, and goodness of God, without which the whole earth would be a hell of sin and confusion.

2\. There is a peculiar #emph[convincing] power in the word, which God is oftentimes pleased to put forth, to the wounding, amazing, and, in some sort, humbling of sinners, though they are never converted. And the word is to be preached though it hath this end, yet not with this end. Let, then, the word be preached, and the sins of men \[will be\] rebuked, lust will be restrained, and some oppositions will be made against sin; though that be not the effect aimed at.

3\. Though this be the #emph[work] of the word and Spirit, and it be good in itself, yet it is not profitable nor available as to the main end in them in whom it is wrought; they are still in the gall of bitterness, and under the power of darkness.

4\. Let men know it is their #emph[duty], but in its proper place; I take not men from mortification, but put them upon conversion. He that shall call a man from mending a hole in the wall of his house, to quench a fire that is consuming the whole building, is not his enemy. Poor soul! it is not thy sore finger but thy hectic fever that thou art to apply thyself to the consideration of. Thou settest thyself against #emph[a particular] sin, and dost not consider that thou art #emph[nothing] but sin.

Let me add this to them who are preachers of the word, or intend, through the good hand of God, that employment: It is their duty to plead with men about their sins, to lay load on particular sins, but always remember that it be done with that which is the proper end of law and gospel; — that is, that they make use of the sin they speak against to the discovery of the state and condition wherein the sinner is; otherwise, haply, they may work men to formality and hypocrisy, but little of the true end of preaching the gospel will be brought about. It will not avail to beat a man off from his drunkenness into a sober formality. A skilful master of the assemblies lays his axe at the root, drives still at the heart. To inveigh against particular sins of ignorant, unregenerate persons, such as the land is full of, is a good work; but yet, though it may be done with great efficacy, vigour, and success, if this be all the effect of it, that they are set upon the most sedulous endeavours of mortifying their sins preached down, all that is done is but like the beating of an enemy in an open field, and driving him into an impregnable castle, not to be prevailed against. Get you at any time a sinner at the advantage, on the account of any one sin whatever? have you any thing to take hold of him by? — bring it to his state and condition, drive it up to the head, and there deal with him. To break men off particular sins, and not to break their hearts, is to deprive ourselves of advantages of dealing with them.

And herein is the Roman mortification grievously peccant; they drive all sorts of persons to it, without the least consideration whether they have a principle for it or no. Yea, they are so far from calling on men to believe, that they may be able to mortify their lusts, that they call men to mortification instead of believing. The truth is, they neither know what it is to #emph[believe] nor what #emph[mortification] itself intends. Faith with them is but a general assent to the doctrine taught in their church; and mortification the betaking of a man by a vow to some certain course of life, wherein he denies himself something of the use of the things of this world, not without a considerable compensation. Such men know neither the Scriptures nor the power of God. Their boasting of their mortification is but their glorying in their shame. Some casuists among ourselves, who, overlooking the necessity of regeneration, do avowedly give this for a direction to all sorts of persons that complain of any sin or lust, that they should vow against it, at least for a season, a month or so, seem to have a scantling of light in the mystery of the gospel, much like that of Nicodemus when he came first to Christ. They bid men vow to abstain from their sin for a season. This commonly makes their lust more impetuous. Perhaps with great perplexity they keep their word; perhaps not, which increases their guilt and torment. Is their sin at all mortified hereby? Do they find a conquest over it? Is their condition changed, though they attain a relinquishment of it? Are they not still in the gall of bitterness? Is not this to put men to make brick, if not without #emph[straw], yet, which is worse, without #emph[strength]? What promise hath any unregenerate man to countenance him in this work? what assistance for the performance of it? Can sin be killed without an interest in the death of Christ, or mortified without the Spirit? If such directions should prevail to change men’s lives, as seldom they do, yet they never reach to the change of their hearts or conditions. They may make men self-justiciaries or hypocrites, not Christians. It grieves me ofttimes to see poor souls, that have a zeal for God and a desire of eternal welfare, kept by such directors and directions under a hard, burdensome, outside worship and service of God, with many specious endeavours for mortification, in an utter ignorance of the righteousness of Christ, and unacquaintedness with his Spirit, all their days. Persons and things of this kind I know too many. If ever God shine into their hearts, to give them the knowledge of his glory in the face of his Son Jesus Christ, they will see the folly of their present way.
