== Preface

Christian Reader,

I shall in a few words acquaint thee with the reasons that obtained my consent to the publishing of the ensuing discourse. The consideration of the present state and condition of the generality of professors, the visible evidences of the frame of their hearts and spirits, manifesting a great disability of dealing with the temptations wherewith, from the peace they have in the world and the divisions that they have among themselves, they are encompassed, holds the chief place amongst them. This I am assured is of so great importance, that if hereby I only occasion others to press more effectually on the consciences of men the work of considering their ways, and to give more clear direction for the compassing of the end proposed, I shall well esteem of my lot in this undertaking. This was seconded by an observation of some men’s dangerous mistakes, who of late days have taken upon them to give directions for the mortification of sin, who, being unacquainted with the mystery of the gospel and the efficacy of the death of Christ, have anew imposed the yoke of a self-wrought-out mortification on the necks of their disciples, which neither they nor their forefathers were ever able to bear. A mortification they cry up and press, suitable to that of the gospel neither in respect of nature, subject, causes, means, nor effects; which constantly produces the deplorable issues of superstition, self-righteousness, and anxiety of conscience in them who take up the burden which is so bound for them.

What is here proposed in weakness, I humbly hope will answer the spirit and letter of the gospel, with the experiences of them who know what it is to walk with God, according to the tenor of the covenant of grace. So that if not this, yet certainly something of this kind, is very necessary at this season for the promotion and furtherance of this work of gospel mortification in the hearts of believers, and their direction in paths safe, and wherein they may find rest to their souls. Something I have to add as to what in particular relates unto myself. Having preached on this subject unto some comfortable success, through the grace of Him that administereth seed to the sower, I was pressed by sundry persons, in whose hearts are the ways of God, thus to publish what I had delivered, with such additions and alterations as I should judge necessary. Under the inducement of their desires, I called to remembrance the debt, wherein I have now for some years stood engaged unto sundry noble and worthy Christian friends, as to a treatise of Communion with God, some while since promised to them;#footnote[Since the first edition of this treatise; that other also is published.] and thereon apprehended, that if I could not hereby compound for the greater debt, yet I might possibly tender them this discourse of #emph[variance with themselves], as interest for their forbearance of that of #emph[peace and communion with God]. Besides, I considered that I had been providentially engaged in the public debate of sundry controversies in religion, which might seem to claim something in another kind of more general use, as a fruit of choice, not necessity. On these and the like accounts is this short discourse brought forth to public view, and now presented unto thee. I hope I may own in sincerity, that my heart’s desire unto God, and the chief design of my life in the station wherein the good providence of God hath placed me, are, that mortification and universal holiness may be promoted in my own and in the hearts and ways of others, to the glory of God; that so the gospel of our Lord and Saviour Jesus Christ may be adorned in all things: for the compassing of which end, if this little discourse (of the publishing whereof this is the sum of the account I shall give) may in any thing be useful to the least of the saints, it will be looked on as a return of the weak prayers wherewith it is attended by its unworthy author,

John Owen.
